### PR TITLE
Source refactor. Abstracted common functionalities from 4 onTouches meth...

### PR DESCRIPTION
**Pull request by krishnanm86**
...ods in Camera3dTest

### CODE REVIEW

**Comment by krishnanm86** [comment]
Passes all tests and removes redundant code.  Cam this be accepted?

**Comment by mannewalis** [comment]
Hi, was looking at this and I think you do not need a template type here, you can just make the method onTouchesCommon take a bool, since all the places you call it you are passing a bool. 

Also, you just just return the true/false... setting touchProperty to true does nothing since it was passed in by value. :)

**Comment by krishnanm86** [comment]
Hi,
   So how do you propose I resolve this? 

Would it help if I just changed the argument to bool pointer and actually passed in a pointer to the corresponding touch property that is being set?

**Comment by mannewalis** [comment]
Yeah that looks better :)

**Comment by krishnanm86** [comment]
Nice. So can this be merged now?

**Comment by minggo** [comment]
We will merge it when jenkins passes.

**Pull request merged**
