### PR TITLE
Update CSLoader.cpp

### PR DESCRIPTION
**Pull request by G17hao**
add assert for createNode.
Because this is a very common problem that programmer giving a wrong path, but Considered as the  framework's problem.

### CODE REVIEW

**Comment by chengstory** [comment]
I ask @pipu to take a look

**Comment by pipu** [comment]
If the actual parameter is an absolute path, the assert can be added for method createNode.

**Comment by minggo** [comment]
@pipu 
So, can merge it or not?

**Comment by pipu** [comment]
No, we can't merge it because we can't ensure the actual parameter value is absolute path.

**Comment by minggo** [comment]
Got it.
Thanks.

**Comment by minggo** [comment]
@G17hao 
Any update?

**Pull request closed without merging**
