### PR TITLE
Motionstreak3d

### PR DESCRIPTION
**Pull request by super626**

### CODE REVIEW

**Comment by super626** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@super626 Has this PR being reviewed ? if yes by who ?

**Comment by super626** [comment]
@pandamicro Please assign some one to review it.

**Comment by pandamicro** [comment]
@fusijie @yangws Please help review this PR

**Comment by yangws** [comment]
@pandamicro 
Reviewed OK, it seem's all good. Please merge it.

**Comment by super626** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Please create an issue and link this PR

**Comment by super626** [comment]
fix #13920

**Pull request merged**
