### PR TITLE
issue #2823: [JSB] Support remote debugging JSB project by FireFox.

### PR DESCRIPTION
**Pull request by dumganhar**
### NOT FINISHED
- Step into can't work.

### CODE REVIEW

**Comment by jdmunro** [comment]
@dumganhar I'm really keen on using this - how usable is it? Are there any preliminary instructions to try it?

**Comment by dumganhar** [comment]
@jdmunro 
It's not finished yet. There is an issue about using Spidermonkey v24.
This Pull Request is still using Spidermonkey23, it will cause some problems (like the offset of js source is wrong) when debugging.
I will update the README.md after I fix this issue. 

I don't know whether some one else could help me fix it.
Anyway, I will also send a PR of upgrading spidermonkey to v24.
Thanks.

**Comment by dumganhar** [comment]
@jdmunro 

I found that the problem of wrong offset of break point is caused by firefox in my Retina MBP 15inch.
Therefore, I think this PR could work.
I will update the README soon. THanks.

**Comment by dumganhar** [comment]
@jdmunro 

README.md was updated. Please view it at https://github.com/cocos2d/cocos2d-x/blob/develop/scripting/javascript/bindings/js/debugger/README.md 
thanks.

**Comment by jdmunro** [comment]
@dumganhar Great, thanks I'll take a look. At the minute we're working with a cocos2d-x 2.2 based project. Will there be any plans to port this functionality back to the 2.x branch or will it remain part of 3.0 only?

**Pull request merged**
