### PR TITLE
fix dos2unix not in run path, on new lua project

### PR DESCRIPTION
**Pull request by flamefox**
当你使用lua新项目的时候，使用tools\tolua\genbindings.py时，其162行会调用dos2unix，而在templates/cocos2dx_files.json中，exe文件被忽略了，这里手动添加上这一行

### CODE REVIEW

**Comment by flamefox** [comment]
see https://github.com/cocos2d/cocos2d-x/issues/10230

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by samuele3hu** [comment]
Thanks to @flamefox .It's right to add dos2unit.exe to templates\cocos2dx_files.json to ensure the project created by the template can use bindings-generator on the windows platform.But this files was modified automatically,so we should optimize the tools/travis-scripts/generate-template-files.py.

**Comment by samuele3hu** [comment]
I have fixed it in #10632.

**Pull request merged**
