### PR TITLE
Eclipse project fixes & improvements

### PR DESCRIPTION
**Pull request by newnon**
Eclipse project compile fix
resource link fix
disabled syntax error highlighting 
disabled CDT syntax warning about override final nullptr
added ability do debug c++ code
fixed include warning
everything work out of box you don't need to add native support its already added!
work on both versions of eclipse on bundle and new one.
template contains 2 build configurations debug & release switch from eclipse project menu.

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. I'm interested in how to debug c++ code in eclipse. Could you share some articles about that?

**Comment by dumganhar** [comment]
Thank you. I'll try it. :)

**Comment by newnon** [comment]
really simple 
1. Add android:debuggable="true" to manifest
2. http://tools.android.com/recent/usingthendkplugin but change build command to ${ProjDirPath}/build_native.py - n NDK_DEBUG = 1
but first target of this pull request to repair eclipse project, at this moment its totally broken.
And it's very bat practice to set NDK_MODULE_PATH in build script because eclipse don't parse this project correct, don't add necessary includes and can not debug build.

this 3 lines fixing that problems
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/cocos)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/external)

**Comment by newnon** [comment]
not looks like we also need file .cproject to be included into repository without it eclipse does not recognize project as native

**Comment by newnon** [comment]
Finally i've got working template which eclipse correctly recognize as native support project.

**Comment by newnon** [comment]
And what about this changes without it eclipse project just wont compile.

**Comment by dumganhar** [comment]
Yep, this patch looks really cool. But it seems that my eclipse version is wrong, i could not add `native` support in my current eclipse. I will download a new version and have a try. Thanks.

**Comment by newnon** [comment]
yes it is better to use latest eclipse version not from bundle
but it is 2 possible solutions
first do 2 differents templates for different eclipse version
or remove  .cproject
and some lines from from .project 
after that user must click on android tool and add native support then change build command to 
${ProjDirPath}/build_native.py -n NDK_DEBUG=1
and clean param to -n clean but project will be compatible for all eclipse versions

**Comment by newnon** [comment]
I will make one more pull request for lite version of this

**Comment by dumganhar** [comment]
Yep, i used the `bundle` version downloaded from `android` website.
Agree with removing `.cproject`, we just need to provide a way for our developer who want to debug `c++` code in eclipse, since there is an ugly bug that ndk project will be re-compiled whenever java project is refreshed or cleaned.

**Comment by dumganhar** [comment]
screen shot 2014-04-09 at 16 37 49
I downloaded the latest version of ADT bundle, but there still isn't `add native support`. Anyway, i will try the normal version of eclipse.

**Comment by newnon** [comment]
in this version it is already added(you can check in settings that c++ build active)
i send 1 more request https://github.com/cocos2d/cocos2d-x/pull/6196 where you must add native support by your self, but it i little bit more compatible with different Eclipse versions

**Comment by newnon** [comment]
Final version everything work out of box you don't need to add native support its already added!
Work on both versions of eclipse on bundle and new one.
Template  contains 2 build configurations debug & release switch from eclipse project menu.

**Comment by cocosQA** [comment]
Dear newnon:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6427
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
