### PR TITLE
Fix bugs of skeleton animation

### PR DESCRIPTION
**Pull request by geron-cn**
1. fix:  draw node which in skeleton but it is not a BoneNode or SkinNode. see changes in `BoneNode::visit`
2. fix crash when BoneNode destruct after skeleton destructed. see chagnes in `SkeletonNode::~SkeletonNode`

### CODE REVIEW

**Comment by geron-cn** [comment]
@pandamicro  @VisualSJ   the submodule i'am  init updating, too slow..

**Comment by geron-cn** [comment]
merge wrong branch

**Comment by geron-cn** [comment]
@pandamicro @VisualSJ  make skeleton's debugdrawEnable  contorls all subbone's debug draw， and modify test case.

**Comment by pandamicro** [comment]
@VisualSJ Please async the new logic to JS

**Comment by geron-cn** [comment]
[ci rebuild]

**Pull request closed without merging**
