### PR TITLE
Removed no_gl_PointSize shaders for Windows Phone 8.1

### PR DESCRIPTION
**Pull request by stammen**
This pull request removes the special case shaders for Window Phone 8.1. The latest version of Angle now supports gl_PointSize correctly.

### CODE REVIEW

**Comment by stammen** [comment]
@minggo please update download-deps.py so the new Angle dll's get downloaded

Thanks!

**Comment by minggo** [comment]
@stammen 
We will update it in these two days as we will modify it soon.
As you know, the speed is slow here, so we want to do less updating as possible.

**Comment by stammen** [comment]
Sure. But with the removed WP8 and old WinRT DLL's the download will be a lot smaller.

**Comment by minggo** [comment]
Yep, the package size will be smaller.
As we are using prebuilt version of all 3rd party libraries, it will be larger again.

**Comment by stammen** [comment]
@minggo We are working to remove png, jpeg, and tiff libs from Windows 8.1 Store and Phone external dependencies by using the Windows Imaging Component (WIC). We are also planning on implementing native networking code to remove curl and openssl. This will really help reduce the size of the download, especially when we add Windows 10 (Visual Studio 2015) support in the coming months.

**Comment by minggo** [comment]
Sounds great.

**Pull request merged**
