### PR TITLE
Handle auto layout with scaled widget

### PR DESCRIPTION
**Pull request by thuydx55**

### CODE REVIEW

**Comment by zilongshanren** [comment]
hi, @thuydx55 

What issue does this PR address?

**Comment by thuydx55** [comment]
@zilongshanren I got problem while displaying scaled Widget in a Layout. They're placed in weird positions. This PR uses boundingBox instead of contentSize for calculating Widget position in layout

**Comment by zilongshanren** [comment]
@thuydx55 
could you add a test in cpp-tests to reproduce the scaled widget in Layout issue, thanks.

**Comment by thuydx55** [comment]
@zilongshanren I've added test for this issue (C++)

`51. Node: UI` > `1. GUI Dynamic Create Test` > `16. Layout Test` > `10. Layout Scaled Widget`

Before:
simulator screen shot may 22 2017 1 42 26 pm

After:
simulator screen shot may 22 2017 1 29 54 pm

**Comment by thuydx55** [comment]
Just added test for JS

**Comment by thuydx55** [comment]
@zilongshanren All checks are passed

**Review by zilongshanren — APPROVED** [review]
thanks, this PR looks good to me.
@minggo

**Comment by zilongshanren** [comment]
@thuydx55 
Thanks

**Comment by thuydx55** [comment]
@zilongshanren Pls take a look at cocos2d/cocos2d-html5#3488. Thanks

**Pull request merged**
