### PR TITLE
FileUtilsWin32 removeDirectory correct remove file begins with point

### PR DESCRIPTION
**Pull request by perminovVS**
Need check fileName . and .. for delete folders and files begin name character point.

### CODE REVIEW

**Comment by jianglong0156** [comment]
don't need change, there are two siduation:
1、wfd.cFileName  is L"."  the judgement wfd.cFileName[0] != '.'  is false
2、 wfd.cFileName  is L".." the judgement wfd.cFileName[0] != '.'  also false

**Comment by perminovVS** [comment]
@jianglong0156 have file first symbol equals poin, example .git .vs
Now spread use first point for name hide and settings folders.

Real now not remove folder and file first character point. It is bag

**Comment by jianglong0156** [comment]
@perminovVS  yes. you are right, when the dir name start with ".", it can't remove. @pandamicro  the pr can be merged

**Comment by pandamicro** [comment]
@perminovVS Thanks !

**Pull request merged**
