### PR TITLE
get_num_of_cpu() returns 1 after update to OS X Yosemite

### PR DESCRIPTION
**Pull request by ZhangZiqi**

### CODE REVIEW

**Comment by minggo** [comment]
We should test if it has problem that not using OS X Yosemite.

**Comment by minggo** [comment]
@zii 
Thanks for testing.

**Comment by minggo** [comment]
@ZhangZiqi 
So we can not change it like this.
Should only change it when using OS X Yosemite?

**Comment by ZhangZiqi** [comment]
@minggo 
Why？According to @zii，it is usable on the other platforms.

**Comment by minggo** [comment]
@ZhangZiqi 
Oh, i misunderstood.
Sorry.

**Comment by pyrosphere** [comment]
The exact same code and issue is also present in [templates/cpp-template-default/proj.android/build_native.py](https://github.com/cocos2d/cocos2d-x/blob/3e124222d95a6944ba228c1b0608c00f7e8e4d4a/templates/cpp-template-default/proj.android/build_native.py#L22-23)

**Pull request closed without merging**
