### PR TITLE
Added SDK / NDK detection based on PATH - tested on Linux only

### PR DESCRIPTION
**Pull request by asmodehn**
This is done similarly to ant detection.
Tested on Linux AlexV-Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

### CODE REVIEW

**Comment by natural-law** [comment]
@asmodehn,
It's a good job. But I think there is a bug in your PR.

```
        elif var_name == NDK_ROOT:
            ndkpath = self._get_ndkbuild_path()
            if ndkpath is not None:
                return os.path.abspath(os.path.join(ndkpath,os.pardir))
            else:
                return None
```

These lines should be replaced with:

```
        elif var_name == NDK_ROOT:
            return self._get_ndkbuild_path()
```

Because the dirname of `ndk-build` is the `NDK_ROOT` we needed. But not the parent directory.

BTW, please replace the `tabs` with `spaces` in your code. And pay attention to the format.
Thank you!

**Comment by natural-law** [comment]
One more question:
I think these code should be added into `_get_android_path()`:

```
            if sdkpath is not None:
                return os.path.abspath(os.path.join(sdkpath,os.pardir))
            else:
                return None
```

Then the method `_get_android_path()` can get the `ANDROID_SDK_ROOT`. Don't need any other logic code for the return value.

**Comment by asmodehn** [comment]
@natural-law,
Thanks for the review. I was indeed confused about created variable and already existing ones when testing for NDK path.
I believe I fixed the problem you highlighted.

Here is the output when i run it on my system :

alex@Alex-XPS:~/Projects/cocos2d-x$ unset NDK_ROOT
alex@Alex-XPS:~/Projects/cocos2d-x$ unset ANDROID_SDK_ROOT
alex@Alex-XPS:~/Projects/cocos2d-x$ ./setup.py

Setting up cocos2d-x...
->Check environment variable COCOS_CONSOLE_ROOT
  ->Find environment variable COCOS_CONSOLE_ROOT...
    ->COCOS_CONSOLE_ROOT is found : /home/alex/Projects/cocos2d-x/tools/cocos2d-console/bin

->Configuration for Android platform only, you can also skip and manually edit "/home/alex/.bashrc"

->Check environment variable NDK_ROOT
  ->Find environment variable NDK_ROOT...
    ->NDK_ROOT not found

  ->Find command ndk-build in system...
    ->Path "/opt/android-ndk-r9d" was found

  -> Add NDK_ROOT environment variable...
    ->Added NDK_ROOT=/opt/android-ndk-r9d

->Check environment variable ANDROID_SDK_ROOT
  ->Find environment variable ANDROID_SDK_ROOT...
    ->ANDROID_SDK_ROOT is found : /opt/android-sdk-linux

->Check environment variable ANT_ROOT
  ->Find environment variable ANT_ROOT...
    ->ANT_ROOT is found : /usr/bin

Let me know if you see anything else I should fix.

**Comment by asmodehn** [comment]
rebased version of this pull request has been submitted #6658.
closing this one.

**Pull request closed without merging**
