### PR TITLE
Update Makefile for linux extensions

### PR DESCRIPTION
**Pull request by slobodin**

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @flaming0 
Now, only win32, android and iOS support websocket.
If you want to make it works on Linux, please compile `libwebsockets` firstly.
Otherwise, adding `WebSocket` to makefile will make no sense.

**Comment by slobodin** [comment]
Hi!

Yes, I've complied libwebsockets and installed it. But I got unresolved externals of WebSocket class members. So, I decided to include this rule to Makefile.

**Comment by slobodin** [comment]
Am I understand right, that libwebsockets is not installed on build server?

**Comment by dumganhar** [comment]
How did you install `libwebsockets`? By `apt-get install` ?
If so, you should modify `tools/travis-script/before-install.sh` for linux port.

**Comment by slobodin** [comment]
Unfortunately, there is no libwebsockets package on my Ubuntu 13.04.
I built it from source.

**Comment by dumganhar** [comment]
So I think we should also install `libwebsocket` from source in `tools/travis-script/before-install.sh`.
Could you try to do that?

**Comment by slobodin** [comment]
Actually I'm not master of writing bash scripts :). But in order to install `libwebsockets` we need to create Makefile via cmake and install additional dependencies (on my machine this library required only `libssl`). And then simply run make && make install.

**Comment by dumganhar** [comment]
OK, I'll try to make `WebSocket` works on Linux too.

**Comment by slobodin** [comment]
Thank you!

**Comment by dumganhar** [comment]
Closed this PR since we're using CMake for linux build now.

**Pull request closed without merging**
