### PR TITLE
Fix all capital letters on Android (Editbox)

### PR DESCRIPTION
**Pull request by ghost**
This patch sets capital letter at sentences start only, not on every single character.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@Delape 
We use all capital letters only for compatible with other platforms, especially iOS.
I think this change will break the back compatibility.

**Comment by Delape** [comment]
Hi @zilongshanren 
What do you mean? This patch is only for the Android platform. Why you say so?
Current EditBox's behaviour is not the one users expect. 

Greetings!

**Comment by zilongshanren** [comment]
@Delape 
I mean on the other platforms, the initial value is also all capital letters... You could call setInputFlag to change the default value. 
I mean we should keep the initial value all the same on all the supported platforms.
thanks.

**Comment by Delape** [comment]
@zilongshanren 
I didn't know about "setInputFlag" existence, that's why I suggested that change in the code.
Thanks for your help :+1: 

I understand your point and now I'm fine with it but I would like to know one last thing:
Why cocos2d-x sets all capital letters by default? Which is the reason behind that decision? It impresses me a lot because It's not the behaviour I would expect (in terms of default mode).

**Comment by zilongshanren** [comment]
@Delape 
I think It's a historical mistake...  maybe @dumganhar  know better about the design decision...

**Comment by zilongshanren** [comment]
@Delape 
If the default is not what all the developers want, we could change this value on all platforms.
@ricardoquesada  Thoughts?

**Comment by ricardoquesada** [comment]
yep. I agree that we shouldn't break compatibility. Migrating to new versions should be smooth.
As @zilongshanren  suggested, using `setInputFlag` looks Ok to me.

**Comment by zilongshanren** [comment]
@ricardoquesada  thanks, I will close this PR now.

**Pull request closed without merging**
