### PR TITLE
V2

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by 11lin** [comment]
good

**Comment by shishiswe** [comment]
您好，我使用的是cocos2dx—3.x版本，C++语言，编辑环境是苹果的Xcode，在升级之后运行进程中WebSocket.cpp文件抛出大量错误，请问如何解决？我使用3.x按照2.x修改了WebSocket.cpp文件还是有很多错误。麻烦您能百忙之中写一下3.x版本怎么修改WebSocket.cpp与WebSocket.h文件吗？谢谢了，确实有点着急，打搅了。

**Comment by openwave1** [comment]
@minggo 您好~麻烦问下，我这边cocos2dx-2.x版本，接完最新修改后，使用域名解析是可以链接的，但是使用ipv4的固定ip链接失败，这个可能是哪里问题，谢谢~

**Comment by openwave1** [comment]
@shishiswe  
https://github.com/cocos2d/cocos2d-x/pull/15666/commits/43dd696750014efa9b0419a59f72ba1c4cdaba50
这是websocket文件

**Comment by jianhuang0** [comment]
quick 3.3的版本，替换了 webSocket 和 curl 的库之后 [43dd696](https://github.com/cocos2d/cocos2d-x/pull/15666/commits/43dd696750014efa9b0419a59f72ba1c4cdaba50) 再替换了websocket的代码，xcode 编译报错 "libwebsockets.h not found"  @minggo 请问要怎么解决？

@shishiswe  请问你的问题解决了吗？

**Comment by minggo** [comment]
Hi guys, please use english in future, then other developers can help you too. If you are not confident with English, you can google translate to translate it. You can paste english together with Chinese. Thanks.

@redcloser `libwebsockets.h`'s location keeps the same as previous version. Could you please check if it  exists in `external/libwebsockets/ios/includes`. If it exists, then just add it to search path. If it is not exists, then i think you don't replace the libs correctly.

**Comment by openwave1** [comment]
@minggo  I has Used the new curl. In ipv6 network, it can connect the domain name, but can not connect a fixed ip (such as *. *. *. *), is it something wrong with me?

**Comment by minggo** [comment]
@openwave1 Yep, you should use domain name. Fix ip address is IPv6/v4 specific.

**Comment by openwave1** [comment]
@minggo  Thank you!

**Comment by jianhuang0** [comment]
thanks, file libwebsockets.h exists in external/websockets/include/ and i have added this path into the xcode Hearder Search Path like this `$(SRCROOT)/../../cocos2d-x/external/websockets/include/ios`.
 but xcode still compile error libwebsockets.h not found @minggo

**Comment by yuanyouli** [comment]
when connect to tomcat 8.0.33

ERR: lws_client_interpret_server_handshake: unable to parse remote defaults 'client_max_window_bits=15'
WebSocket (0x12d764790) onConnectionError ...
Ready state is closing or was closed, code=2, quit websocket thread!
NOTICE: lws_context_destroy

**Comment by minggo** [comment]
@redcloser I have not idea, please make sure `$(SRCROOT)/../../cocos2d-x/external/websockets/include/ios` is correct.

@yuanyouli 
`ERR: lws_client_interpret_server_handshake: unable to parse remote defaults 'client_max_window_bits=15'` 
The error log tell you the problem. But i don't know why it has the problem, i think you should ask it in [libwebsocket repo](https://github.com/warmcat/libwebsockets).

**Comment by 0xJimmyBeh** [comment]
@shishiswe @redcloser 

I have success compiled the Cocos2d-JS library v3.8.1 but not sure it's working as i can't setup the NAT64 network provided by Apple.

If you follow v2 modification on v3, you need to change `enum lws_callback_reasons` to `int reason`

You don't need to add this
`#include "external/websockets/include/ios/libwebsockets.h" in WebSocket.h`

WebSocket.h
Change this
`int onSocketCallback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len);`

to this
`int onSocketCallback(struct lws *wsi, int reason, void *user, void *in, ssize_t len);`

WebSocket.cpp
Change this
`int WebSocket::onSocketCallback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len)`

to this
`int WebSocket::onSocketCallback(struct lws *wsi, int reason, void *user, void *in, ssize_t len)`

Please check if it works.
Thank you.

**Comment by zhoujianghai** [comment]
My project was developed with cocos2d-x 2.1.5, I updated the libcurl.a from v2-deps-v7, but build error with arm64, the version of libcurl.a not supporting 64-bits?
the error log info:
Undefined symbols for architecture arm64:
"_MD4_Init", referenced from:
_Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
"_MD4_Update", referenced from:
_Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
"_MD4_Final", referenced from:
_Curl_ntlm_core_mk_nt_hash in libcurl.a(libcurl_la-curl_ntlm_core.o)
"_UI_get_string_type", referenced from:
_ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
_ssl_ui_writer in libcurl.a(libcurl_la-openssl.o)
"_UI_method_get_reader", referenced from:
_ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
"_UI_set_result", referenced from:
_ssl_ui_reader in libcurl.a(libcurl_la-openssl.o)
"_SSL_write", referenced from:
_ossl_send in libcurl.a(libcurl_la-openssl.o)
"_SHA256_Init", referenced from:
_Curl_ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
"_SHA256_Final", referenced from:
_Curl_ossl_sha256sum in libcurl.a(libcurl_la-openssl.o)
"_MD5_Update", referenced from:
_Curl_ossl_md5sum in libcurl.a(libcurl_la-openssl.o)
_Curl_md5it in libcurl.a(libcurl_la-md5.o)
_Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
_Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
"_MD5_Final", referenced from:
_Curl_ossl_md5sum in libcurl.a(libcurl_la-openssl.o)
_Curl_md5it in libcurl.a(libcurl_la-md5.o)
_Curl_HMAC_MD5 in libcurl.a(libcurl_la-md5.o)
_Curl_DIGEST_MD5 in libcurl.a(libcurl_la-md5.o)
"_RAND_load_file", referenced from:
_Curl_ossl_seed in libcurl.a(libcurl_la-openssl.o)
"_RAND_status", referenced from:
_Curl_ossl_seed in libcurl.a(libcurl_la-openssl.o)
"_SSLeay", referenced from:
_Curl_ossl_version in libcurl.a(libcurl_la-openssl.o)
(maybe you meant: __ZN4NGcp11RAND_SSLeayEv, __ZN4NGcp16RSA_PKCS1_SSLeayEv )
"_SSL_pending", referenced from:
_Curl_ossl_data_pending in libcurl.a(libcurl_la-openssl.o)
"_SSL_CTX_set_alpn_protos", referenced from:
_ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
"_SSL_CTX_set_default_passwd_cb_userdata", referenced from:

**Comment by chenzhongqiang** [comment]
现在情况是，按照cocos2dx 的集成说明集成了最新ipv6的相关库和代码，ipv6环境搭建成功

返回: CURLE_COULDNT_CONNECT(7)   connect()的主机或代理失败。

IPV4网络环境正常下载

IPV6网络环境返回 CURLE_COULDNT_CONNECT(7) , 但使用浏览器是能打印这个链接地址的。

**Comment by chenzhongqiang** [comment]
I have success compiled the quickv3.3 library, i meet error  CURLE_COULDNT_CONNECT(7)  or CURLE_COULDNT_RESOLVE_HOST(6)

**Comment by minggo** [comment]
This PR is for v2, please create an github issue about it. And you can not use IP address, use domain instead.

**Comment by chenzhongqiang** [comment]
I used domain

**Comment by chenzhongqiang** [comment]
i visit http://www.baidu.com failed by error  CURLE_COULDNT_RESOLVE_HOST(6)

**Comment by chenzhongqiang** [comment]
i open curl debug info 

Rebuilt URL to: http://www.baidu.com/
-   Trying 180.97.33.108...
- Immediate connect fail for 180.97.33.108: Network is unreachable
-   Trying 180.97.33.107...
- Immediate connect fail for 180.97.33.107: Network is unreachable
- Closing connection 0
  request onrequest S_ID:2 errorcode 7

**Comment by hemanthunity** [comment]
Hi,
I followed your steps to upgrade my old project which was developed on 2.x, After adding libcrypto.a,libcurl.a,libwebsocket.a it worked like charm. Thanks for the Post

**Pull request merged**
