### PR TITLE
Cmake fix modules include path

### PR DESCRIPTION
**Pull request by vovkasm**
This change allow to include cocos project directory from another CMakeFiles.txt (with add_subdirectory). And allow to us connect cocos as submodule in our own projects and build it with projects itself.

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by vovkasm** [comment]
@minggo What bad with this patch? (Without this, if I do in my project `add_subdirectory(cocos2d-x)`, then cocos itself can't find `cmake/Modules` directory...)

**Comment by minggo** [comment]
Sorry.
It is my mistake.
I thought it was to resolve building error.

**Comment by minggo** [comment]
And there is conflict.
Could you please fix it?
I will merge it if it passes CI.

**Comment by vovkasm** [comment]
Ah, ok )
I will sync with recent v3 then in few minutes.

**Comment by vovkasm** [comment]
@minggo 
Sorry, I can't easily sync with current 'v3' and simple cherry-pick one commit to new branch and create new pull request #9250. This pull request can be closed.

**Comment by minggo** [comment]
Got it.
Thanks.

**Pull request closed without merging**
