### PR TITLE
Fix #24345

### PR DESCRIPTION
**Pull request by chengstory**
TMX Iso Zorder and TMX Ortho Zorder rendering error in TestCPP.

### CODE REVIEW

**Comment by xiaofeng11** [comment]
@zilongshanren Please review this PR. It resolve z-order bug after combine studio change to TMX parser.

**Comment by zilongshanren** [comment]
I'm not familiar with TMX related code.  @ricardoquesada  is the owner. :smile:

**Comment by chengstory** [comment]
This pr means revert code to cocos2d-x 3.9, the same implementation is moved to editor source code，Refer to http://git.ck/cocostudio/cocostudio/merge_requests/4491​

**Comment by xiaofeng11** [comment]
@zilongshanren Sorry, I think this is a part of UI component.
@ricardoquesada Please review this PR, Thanks. It's should been merge to version 3.10.

**Comment by pandamicro** [comment]
@dabingnn can also help to review TMX modifications

**Comment by ricardoquesada** [comment]
thanks. merged.

**Pull request merged**
