### PR TITLE
Support the new line element. Fixed a problem of UIRichText.

### PR DESCRIPTION
**Pull request by m-yukio**
Support the new line element of UIRichText.
Fixed a problem that protrude from the drawing area.

richtext

### CODE REVIEW

**Comment by pandamicro** [comment]
@liamcindy Please review this PR, @zilongshanren please help review it

**Comment by pandamicro** [comment]
Also, @m-yukio please fix the compilation issues

**Comment by m-yukio** [comment]
[ci rebuild]

**Comment by m-yukio** [comment]
a issues is fixed.

**Comment by liamcindy** [comment]
Based on current implementation, it's ok to be merged.

**Comment by pandamicro** [comment]
@zilongshanren Please confirm

**Comment by zilongshanren** [comment]
@m-yukio 
:+1:  Thanks for your contribution.

**Pull request merged**
