### PR TITLE
Adds Point::ANCHOR_XXX constants

### PR DESCRIPTION
**Pull request by ricardoquesada**
Make the code more explicit, less error prone, and less objects to create
Updates the SpriteTest with these constants as well

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks Totally Evil Jake for the idea!

**Comment by totallyeviljake** [comment]
haha - love it

**Comment by litefeel** [comment]
please modify the name to english style.thanks.
TOP_LEFT(左上),TOP_CENTER(中上),TOP_RIGHT(右上),
CENTER_LEFT(左中),CENTER(中间),CENTER_RIGHT(右中),
BOTTOM_LEFT(左下),BOTTOM_CENTER(中下),BOTTOM_RIGHT(右下).

**Comment by ricardoquesada** [comment]
@lite3 what do you mean by "english style" ? Thanks.
Just replacing "UPPER" with "TOP" and, "LOWER" with "BOTTOM" ?

I guess upper/lower is "english style" too.

@totallyeviljake Which one is more correct ? top/bottom or upper/lower ? thanks.

**Comment by dumganhar** [comment]
IMO,lower could mean value is low, upper could mean value is high. It seems
that TOP and BOTTOM are more suitable to describe direction.
- James
  ÔÚ 2013-9-28 ÏÂÎç12:55£¬"Ricardo Quesada" notifications@github.comÐ´µÀ£º

**Comment by ricardoquesada** [comment]
thanks.
both names looks fine for me (although english is not my native language), but `TOP` and `BOTTOM` are already used by cocos2d-x, so I renamed them to be more consisten.

**Comment by totallyeviljake** [comment]
Top and Bottom are physical descriptors usually, whereas these are conceptual descriptors - left, right, upper, lower. They describe the u,v space of the anchor rather than the actual space. Top and Bottom are relationship terms. That's why I chose upper/lower in our case.

**Comment by ricardoquesada** [comment]
@dumganhar 
Your call. My pull request has both versions: `TOP,BOTTOM`, and `UPPER, LOWER`.
So, merge the commit that you think is more convinient for cocos2d-x.

**Comment by dumganhar** [comment]
@ricardoquesada 
OK, thanks. I'll discuss with @minggo .

**Comment by ricardoquesada** [comment]
Any update on this pull request ?

**Comment by winipcfg** [comment]
For your information

Anchor style, horizontal/vertical alignment (.NET)
http://msdn.microsoft.com/zh-tw/library/system.windows.forms.anchorstyles%28v=vs.110%29.aspx
http://msdn.microsoft.com/en-us/library/system.windows.horizontalalignment.aspx
http://msdn.microsoft.com/en-us/library/system.windows.verticalalignment%28v=vs.110%29.aspx

Component Alignment (Java)
http://docs.oracle.com/javase/7/docs/api/java/awt/Component.html

wxWidgets::wxSizerFlags
http://docs.wxwidgets.org/trunk/classwx_sizer_flags.html

**Comment by dumganhar** [comment]
Hi @winipcfg ,
Thank you. I saw the URL you posted are all using `TOP`, `BOTTOM`.

**Comment by ricardoquesada** [comment]
Hi,

Any update on this one ? thanks.

**Comment by minggo** [comment]
Oh, the folder structure is changed. So this pull request can not be merged automatically. I will ask somebody to send another pull request for it.

**Comment by ricardoquesada** [comment]
ok. thanks.

**Comment by minggo** [comment]
@Dhilan007
Could you please help to do it?
Thanks.

**Comment by WenhaiLin** [comment]
@minggo 
Yes,I will send another pull request fot it  this week.

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
It is done in #4127.

**Pull request closed without merging**
