### PR TITLE
WinRT support mouse

### PR DESCRIPTION
**Pull request by perminovVS**
Show/Hide mouse cursor.
Mouse event implemented similar Desktop version.
Left button send mouse event and touch.
Support other mouse button and scroll wheel.

### CODE REVIEW

**Comment by pandamicro** [comment]
@stammen Can you take a look at this PR ?
@perminovVS have proposed many PRs to improve Cocos engine on windows platforms, you can take a look at other PRs here: https://github.com/cocos2d/cocos2d-x/pulls/perminovVS

**Comment by stammen** [comment]
@perminovVS Thanks for your pull request. Please move your changes to the following files

templates/cpp-template-default/proj.win10/App/Cocos2dEngine/OpenGLES.cpp
templates/cpp-template-default/proj.win10/App/Cocos2dEngine/OpenGLESPage.xaml.cpp
templates/cpp-template-default/proj.win10/App/Cocos2dEngine/OpenGLESPage.xaml.h

to the following folder

cocos\platform\win8.1-universal

These files are used by all of the Windows 8.1 and 10.0 projects and are automatically copied to the correct template locations during a build of the Windows 8.1 and 10.0 solutions in the build directory.

Please let me know if you have any questions.

**Comment by perminovVS** [comment]
@stammen did it.

**Comment by WenhaiLin** [comment]
@pandamicro I think this PR is OK for merge. 
Update:
@stammen I found templates without copying those files automatically.

**Pull request merged**
