### PR TITLE
Adds iOS tests, calls GC after replacing scene

### PR DESCRIPTION
**Pull request by ricardoquesada**
and some bug fixes

Squashed commit of the following:

commit 36b74ce4e68bf2f4a4c464453e695497716506eb
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Dec 22 19:07:01 2015 -0800

```
adds missing file
```

commit 017d03807122faa38fefaa8f4554db8edc83561d
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Dec 22 19:02:27 2015 -0800

```
disables GC by default
```

commit a2f3767a952e052eb8f0391bb5cbd1a8d0ce1b38
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Dec 22 18:57:14 2015 -0800

```
Adds iOS test and calls GC after replacing the scene
```

commit 7b3b628caeb3366356d9a896aebd9c96887a85ed
Merge: 79e926a e311655
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Dec 22 15:29:01 2015 -0800

```
Merge branch 'v3' into v3_js_memory_test_and_fixes
```

commit 79e926a970e3153ee826b299c3417fb6ac599153
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Mon Dec 21 21:27:19 2015 -0800

```
fixes crashes
```

commit 76f3910748e15c4ea179eab846f24f3e65d52d2d
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Mon Dec 21 11:57:56 2015 -0800

```
Adds standalone test for JS GC memory

and fixes leaks on extended/subclassed objects
```

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Any update on this PR?

**Comment by ricardoquesada** [comment]
@linshun @pandamicro could we please merge this PR in v3?

I really don't want to update this PR anymore when someone changes the xcodeproj in v3.
Thanks.

**Comment by linshun** [comment]
Yes, it could be merged if it is ready. Current version release branch has been created, so it is ok to merge them in v3 branch.

**Comment by linshun** [comment]
@pandamicro could you please review it?

**Comment by pandamicro** [comment]
It doesn't have any side effect on current v3 branch, no problem to merge it

**Pull request merged**
