### PR TITLE
V3: Windows 10.0 Universal App (UWP) support

### PR DESCRIPTION
**Pull request by stammen**
This pull request adds the project files for Windows 10.0 Universal App (UWP). All cocos2d-x features are supported except CURL and AssetsManager (which will be added next week). JavaScript support will be added in a separate pull request. 

The VS2015 compiler is more strict than VS2013. A few double to float warnings were fixed.

This pull request depends on the Win10 dependencies added in pull request https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/152

### CODE REVIEW

**Comment by stammen** [comment]
@minggo Please restart build. iOS build system went offline. Other platforms built fine.

**Comment by stammen** [comment]
@minggo Please restart build. iOS build system went offline. The other platforms are building without error.

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@stammen 
Thanks for the contribution.

@andyque 
The pull request looks good to me.

**Comment by stammen** [comment]
Thanks for pulling the Windows 10 code. Please tag https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin with version 57 so the Windows 10 dependencies can be downloaded with download-deps.py.

**Comment by zilongshanren** [comment]
Thanks @stammen  
it's done.

**Pull request merged**
