### PR TITLE
UIWidget::getChildByName should recursive search

### PR DESCRIPTION
**Pull request by zhujj2008**
Hi,  
     In v3.0 beta, the UIWidget::getChildByNam does not recursively search the children widgets when parsing the cocosstudio exported json file,  which cause our code cannot find some child widget when loading cocossdudio generated UI.  
    Hope this patch can fix all the problem.

```
Thanks.
```

### CODE REVIEW

**Comment by nutty898** [comment]
Hello.

Thanks for your pull request.

If you want to recursively search a widget, you can use Helper::seekWidgetByName(Widget\* root, const char\* name);.

We hope that "getChildByName" and "getChildByTag" are the same "level".

Node::getChildByTag does not recursively search, right?

**Comment by zhujj2008** [comment]
Understand,  thanks for give then right usage method.

**Comment by dumganhar** [comment]
@zhujj2008 
So could this PR be closed?

**Comment by zhujj2008** [comment]
Closed

**Pull request closed without merging**
