### PR TITLE
add blendfunc cascade to its skin in BoneNode

### PR DESCRIPTION
**Pull request by geron-cn**
add blendfunc cascade to its skin in BoneNode

### CODE REVIEW

**Comment by geron-cn** [comment]
reference to https://github.com/cocos2d/cocos2d-x/pull/13359

**Comment by pandamicro** [comment]
It's ok, but can you squash your commits to one ?

Here is a tutorial: https://docs.google.com/document/d/1PQHXTEQ3GoI0XH1YQNf1P-d79BAkRanzeIocdrHlGiI/edit

**Comment by geron-cn** [comment]
just has on commit now.

**Comment by pandamicro** [comment]
Thanks !

**Pull request merged**
