### PR TITLE
#Optimize, nodeComparisonLess, What's about, Let's discuss

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
What's wrong?

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
jekins has problem: 
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Yep, iOS and Mac slave is blocked, we are fixing it.

**Comment by minggo** [comment]
@halx99 why to change it like this?

**Comment by halx99** [comment]
According my test result: this optimize can improve  sort performance for 64bit program:

qq 20160713100319

**Comment by minggo** [comment]
But it makes codes more complex and hard to maintain. Are the codes being hotpot of the game?

**Comment by halx99** [comment]
Not yet, well this optimize is not emergency.

**Pull request closed without merging**
