### PR TITLE
fix for #19363

### PR DESCRIPTION
**Pull request by MrCapone**
#19363

https://discuss.cocos2d-x.org/t/cocos2d-x-3-17-and-android-studio-3-3-build-issue-or-error/45503/6?u=capone

### CODE REVIEW

**Comment by minggo** [comment]
It seems there is a conflict, could you please fix it, and could you please modify other templates too.

**Comment by MrCapone** [comment]
Done. I also updated the tests too.

**Comment by minggo** [comment]
@MrCapone have you tested it? @PatriceJiang told me it didn't take effect to modify like this. The warnings are gone, but the task was not executed.

**Comment by MrCapone** [comment]
I already using this code in my projects. Assets folder has been successfully generated and copied to apk. So nothing wrong with this line. 
I'm using Android Studio version 3.4 with gradle plugin version 3.4.0.

**Comment by PatriceJiang** [comment]
I tested the current v3 branch with similar changes and the files were not copied to the assets folder. @MrCapone would you please tell which version of gradle is used in your project?

**Comment by MrCapone** [comment]
@PatriceJiang im using gradle plugin v3.4.0 which downloading gradle 5.1.1

**Comment by PatriceJiang** [comment]
~~It seems to be a bug of AndroidStudio I am using, which is perhaps too new.~~  
~~The task is triggered correctly from the console, but it does not run in AndroidStudio.~~ 

It is caused by gradle version change.

**Comment by MrCapone** [comment]
I've tested CppTest from main branch without this commit and then on my branch with it. In both cases assets folder didn't created and REsources didn't copied. So this commit has nothing to do with that issue. Anyway my project from cpp-template still working fine.

**Comment by PatriceJiang** [comment]
The issue was introduced since https://github.com/cocos2d/cocos2d-x/pull/19657,  we may choose another version of gradle or modify gradle build scripts.  @MrCapone

**Comment by MrCapone** [comment]
@PatriceJiang I've created empty project from my branch and tried build apk. Everything works fine. So gradle build scripts in cpp-template already working.

**Comment by minggo** [comment]
Because we need to copy resources, and it doesn't depend any other thing. So i think we can copy resources not using gradle task. Then it will not be affected by gradle.

**Comment by MrCapone** [comment]
not relevant

**Comment by hbSumrain** [comment]
Can you tell me how to resolve this problem ,it also happened to me

**Comment by MrCapone** [comment]
@hbSumrain https://discuss.cocos2d-x.org/t/cocos2d-x-3-17-and-android-studio-3-3-build-issue-or-error/45503/6?u=capone

**Pull request closed without merging**
