### PR TITLE
fix TextureCache memory leak on android

### PR DESCRIPTION
**Pull request by andylua040427a**

### CODE REVIEW

**Comment by Obg1** [comment]
It seems the fix doesn't free "texture" if the file couldn't be loaded, and there's no auto release call for it in that case.

**Comment by minggo** [comment]
@andylua040427a Could you please say more about this PR? Why it causes memory leak? Thanks.

**Comment by andylua040427a** [comment]
I repeat with the 3D particle system added to the layer, and then removed from the layer "on android"
windows Will not happen

**Comment by minggo** [comment]
And it is fixed by this PR?

**Comment by andylua040427a** [comment]
There should be，you can try

**Comment by minggo** [comment]
How did you check the memory usage on Android?

**Comment by andylua040427a** [comment]
adb shell procrank

**Comment by minggo** [comment]
@Obg1 Yep, i agree with you though the codes looks good.

**Pull request closed without merging**
