### PR TITLE
touches improvement like apple UIEvent getAllTouches

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by newnon** [comment]
is it possible to get some logs why it does not compile?

**Comment by dumganhar** [comment]
Please refer to http://115.28.134.83:8000/job/cocos-2dx-pull-request-build/1995/.

**Comment by newnon** [comment]
where is only log for android_mac what build successful i tested all projects on my computes everything works i don't understand whats wrong

**Comment by cocosQA** [comment]
Dear newnon:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6442
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
