### PR TITLE
Auto culling support for Label class

### PR DESCRIPTION
**Pull request by thoechsmann**
I moved the culling test function from Sprite up to the Node class. Label is now using the same test as Sprite to skip Labels that are offscreen. Only complete Labels will be tested and not single characters.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Yes, I think it should work.

It will fail with particles, because particles don't update their `contentSize`, but that is a bug in the particles.
So, in order to prevent confusion with the users I think we should rename `isInsideBounds()` to `isContentSizeInsideBounds()`  (or something like that)

**Comment by thoechsmann** [comment]
Currently I only added culling to Labels in addition to the Sprites. 

I would add a parameter to the isContentSizeInBounds function for the bounds the user want to check. the draw Function will use the whole screen as bounds. 

But with the parameter the function can be used by users for other bounds checks, too.

**Comment by ricardoquesada** [comment]
@thoechsmann
What is the Use Case of passing a parameter?
I mean, in which scenario would you like to use a different value than the size of the screen?
thanks.

**Comment by thoechsmann** [comment]
if scissoring is activated. Maybe this can be detected automatically...

**Comment by minggo** [comment]
I think it is better to culling the whole screen one time a frame. Not to do culling on every node.

**Comment by ricardoquesada** [comment]
@minggo 
What Thomas said was that we could add an optional "screen size" parameter to the culling function.
By default it is the size of the view port, but you can make smaller if needed.

**Comment by minggo** [comment]
@ricardoquesada 
Thanks for you explain.

What i wonder is that could we have a method just do culling one time per loop. Now Label should do its culling, Sprite should do its culling, and so on. Is there any method to do culling in a place for all of them. I know we can not achieve it in current design.

**Comment by ricardoquesada** [comment]
@minggo 
As I mentioned earlier, to all the nodes have the `contentSize()` set correctly, and for some nodes it might not be efficient to check it (eg: `Scene`).
So, it make sense to check the culling at `draw` time.

**Comment by minggo** [comment]
Ok, got it.

**Comment by cocosQA** [comment]
Dear thoechsmann:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6425
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
