### PR TITLE
add Gleed2D editor support

### PR DESCRIPTION
**Pull request by hzl2928963**
GLEED2D (Generic LEvel EDitor 2D) is a general purpose, non tile-based Level Editor for 2D games of any genre that allows arbitrary placement of textures and other items in 2D space. Levels are saved in XML format. But it only support XNA with C# API officially. I just add new source file written to support loading Gleed2D level file into Cocos2d-x scene.

### CODE REVIEW

**Comment by minggo** [comment]
@hzl2928963 
Thanks for contribution.
 GLEED2D is written in C# and XNA Game Studio 3.1. So it can run only on windows?

**Comment by hzl2928963** [comment]
Yes,it needs the XNA Framework Redistributable 3.1 (download from Microsoft) and the Microsoft .Net Framework 3.5. I write my parser and loader in similer patern like TMXTiledMap, it is easy to be used.
Here is official website of Gleed2D http://gleed2d.codeplex.com/

**Comment by hzl2928963** [comment]
I have test my Gleed2D loader on both Windows 7 32bit and Android 4.0.3, it performs well.

**Comment by minggo** [comment]
I have not idea with Gleed2D. I don't know if we should integrate it or not.
@ricardoquesada 
What's your opinion?

**Comment by hzl2928963** [comment]
I just now add a sample project for Gleed2D in test-cpp,

**Comment by ricardoquesada** [comment]
@hzl2928963 Thanks for the pull request

@minggo I've never used Gleed2d before.
Is it a popular editor in the Windows world ? Which games are using it ?

What about adding this contribution in the cocos2d-x hub:
http://cocos2d-x.org/hub

**Comment by minggo** [comment]
I am not familiar with Gleed2d too. 
@hzl2928963 I think it is a good idea to add it in the cocos2d-x hub.

**Comment by hzl2928963** [comment]
@ricardoquesada
@minggo 
Gleed2D is just a small open source project. Because I works on windows platform,I am looking for a generic level editor to help build level for my game and then I got Gleed2D.
It is not complete but light weight,So I write a loader to use it in Cocos2d-x.
Maybe, your suggestion is sound.Thanks ,I have added it in hub.

**Comment by cocosQA** [comment]
Dear hzl2928963:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6462
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
