### PR TITLE
init widget properties

### PR DESCRIPTION
**Pull request by 2youyou2**

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Yep. I forgot that, jenkins now doesn't support v2. And we will use travis for it.

**Pull request merged**
