### PR TITLE
Android arm64-v8a also uses Luajit.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
This pull request needs https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/246 to be merged

**Comment by dumganhar** [comment]
@zilongshanren, please review.

**Comment by zilongshanren** [comment]
@dumganhar  looks good to me

**Comment by minggo** [comment]
@dumganhar i think we should provide tool to generate 64-bit bytecode, currently `cocos luacompile` only generate 32-bit bytecode.

**Comment by dumganhar** [comment]
It's a pity that cocos luacompile doesn't support to generate 64bit bytecode... : ( 
But how do developers generate 64bit luajit bytecode for 64bit bytecode now?

**Comment by minggo** [comment]
In previous, it is not convenient to generate 64bit bytecode, you need to use real 64bit device(iPhone6 or so) to generate it. But @dualface told me that, now it can generate 64bit bytecode in PC, but i haven't tried it.

**Comment by dumganhar** [comment]
So do you mean we should make `cocos luacompile` supports this feature in v3.13?

**Comment by minggo** [comment]
Yep, i think it is better.

**Comment by minggo** [comment]
@dumganhar i merged cocos2d/cocos2d-x-3rd-party-libs-bin#246 and release `deps-108`. Could you please update it in this PR?

**Comment by dumganhar** [comment]
OK, I will.

**Comment by dumganhar** [comment]
Updated.

**Pull request merged**
