### PR TITLE
update ui button size changed logic

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by minggo** [comment]
@andyque 
Could you please review it?

**Comment by minggo** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@minggo 
Hi, We could merge this PR now.

**Comment by minggo** [comment]
@andyque
Could you please send a pull request to modify changelog?
Thanks.

**Comment by zilongshanren** [comment]
@minggo 
Here is the changelog PR: https://github.com/cocos2d/cocos2d-x/pull/8954

**Pull request merged**
