### PR TITLE
Multiprocessor Compilation on Windows

### PR DESCRIPTION
**Pull request by lgb**
I just enable subj for all VC++ projects. Also I set Minimal Rebuid to default (off) for all debug configurations because conflicts with Minimal Rebuild and Multiprocessor Compilation.

It's two changes decrease times of build from 4-5 minutes to 1.5

### CODE REVIEW

**Comment by dumganhar** [comment]
> It's two changes decrease times of build from 4-5 minutes to 1.5

Which project ? Did you mean the time of building the whole solution?

**Comment by lgb** [comment]
build-win32.bat compile entire solution, I check with it.

**Comment by dumganhar** [comment]
@lgb 
OK, thank you. I'll also check it by using that script.

**Comment by rtissera** [comment]
Very useful change, VS2012 tends to compile slowly without this option.
Could you merge it please ?

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2976 .

**Pull request closed without merging**
