### PR TITLE
android & ios screen size change support

### PR DESCRIPTION
**Pull request by ondesly**
- applicationScreenSizeChanged method only for ios and android
- nativeactivity in android waits for onContentRectChanged and after 30 ms calls applicationScreenSizeChanged
- didRotateFromInterfaceOrientation in ios calls applicationScreenSizeChanged

### CODE REVIEW

**Comment by sachingarg05** [comment]
@minggo I tested this a bit and it seems to work ok. Can we please have this merged before the next alpha release?

**Comment by minggo** [comment]
@sachingarg05
Sure, i will test it and merge it.
Thanks for notifying.

@ondesly 
Good job.

**Comment by ondesly** [comment]
@minggo 
Thank you! It's my first pull request. I'm very excited.

**Comment by sachingarg05** [comment]
@ondesly @minggo Now that native activity is gone from 3.0, we will need to add a JNI function call in Java onSurfaceChanged, and that JNI function will need to call our new cocos2d::Application::getInstance()->applicationScreenSizeChanged(newWidth, newHeight);

**Comment by minggo** [comment]
@sachingarg05 
We will support it.
Thanks.

**Pull request merged**
