### PR TITLE
android crash

### PR DESCRIPTION
**Pull request by adriandiesel**
acer z120 
I/GraphicBuffer(   96): allocate buffer (w:320 h:480 f:5) err(0)

W/MMUMapper(   96): fail to register MVA, unsupported format(0x5)

I/BufferQueue(   96): [SurfaceView] createGraphicBuffer before(NULL) after(0x422344f8, handle=0x42232260, w=320, h=480, f=5)

W/MMUMapper( 7569): fail to register MVA, unsupported format(0x5)

F/libc    ( 7569): Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 7582 (Thread-704)

### CODE REVIEW

**Comment by minggo** [comment]
@adriandiesel 
Did you sent to error branch?

**Comment by adriandiesel** [comment]
No, where is that?

**Comment by minggo** [comment]
I don't know what's your problem.
I think you should use `v3` as base branch to continue your work.
I think [this news](http://cocos2d-x.org/news/226) is good to know.

**Comment by minggo** [comment]
@adriandiesel 
I think you work on error branch.
There are so many commits that don't need.

**Comment by adriandiesel** [comment]
În data de luni, 26 mai 2014, minggo notifications@github.com a scris:

> @adriandiesel https://github.com/adriandiesel
> I think you work on error branch.
> There are so many commits that don't need.
> 
> —
> Where do I report crashes for android?

**Pull request closed without merging**
