### PR TITLE
use cocos console in build_native.py and android-build.py

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by andyque** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
