### PR TITLE
Add "id" for parser object

### PR DESCRIPTION
**Pull request by feijing566**
Add "id" for parser object

### CODE REVIEW

**Comment by feijing566** [comment]
qq 20160223141445

**Comment by minggo** [comment]
Sorry, i am not quite familiar with TiledMap, but i have a question:

Is `id` useful since it is not parsed, and nobody complained it, could you show me the usage? Thanks.

**Comment by feijing566** [comment]
@minggo 
id is the unique identification for object . sometime I need to distinguish between different objects.

**Comment by minggo** [comment]
I search the resources of `cpp-tests`, and could not find `id` element. Is it a new element?

**Comment by feijing566** [comment]
@minggo 
Yes,it is added in version 0.11.0
https://github.com/bjorn/tiled/blob/master/NEWS

**Comment by minggo** [comment]
@feijing566 Thanks for the link.

**Pull request merged**
