### PR TITLE
Universal build fix

### PR DESCRIPTION
**Pull request by mannewalis**

### CODE REVIEW

**Comment by mannewalis** [comment]
Reverted changes to sln file. I thought the project was in there, but I was mistaken. Added the correct files.

**Comment by minggo** [comment]
Could you please fix conflict?

**Comment by stammen** [comment]
@mannewalis @minggo I fixed most of this in my last pull request. I am adding the allocator in my next pull request. There is no need to merge this pull request.

@mannewalis Thanks for your help!

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/9736

**Pull request closed without merging**
