### PR TITLE
fix restart game crash in FT_Get_Char_Index

### PR DESCRIPTION
**Pull request by Sumxx**
fix restart game crash in FT_Get_Char_Index    why not call cache     FontAtlasCache::purgeCachedData() or Director::purgeCachedData() ?

### CODE REVIEW

**Comment by minggo** [comment]
@Sumxx how to reproduce it?

**Comment by Sumxx** [comment]
use third-party Font lib.

**Comment by minggo** [comment]
I don't quite understand. If you can give me a test case and show me how to reproduce it step by step, it is better.

**Comment by Sumxx** [comment]
Because unload freeType lib of  FontFreeType::shutdownFreeType. but, not clear FontAtlasCache::purgeCachedData(). look at 
`    auto it = _atlasMap.find(atlasName);

```
if ( it == _atlasMap.end() )
{
    auto font = FontFreeType::create(config.fontFilePath, fontSize, config.glyphs, 
        config.customGlyphs, useDistanceField, config.outlineSize);
    if (font)
    {
        auto tempAtlas = font->createFontAtlas();
        if (tempAtlas)
        {
            _atlasMap[atlasName] = tempAtlas;
            return _atlasMap[atlasName];
        }
    }
}
else
{
    _atlasMap[atlasName]->retain();
    return _atlasMap[atlasName];
}`
```

_atlasMap is not clear, so _atlasMap[atlasName] is invain

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
