### PR TITLE
Update build_native.py

### PR DESCRIPTION
**Pull request by flashjay**
copy_resources use build-cfg.json config

### CODE REVIEW

**Comment by minggo** [comment]
Why change it like this?

This script will be removed in future, because we have cocos commands.

**Comment by flashjay** [comment]
eclipse project use this script

python ${ProjDirPath}/build_native.py -b debug

**Comment by minggo** [comment]
Eclipse project can use cocos command too.

**Comment by flashjay** [comment]
So, eclipse project template should be changed.

**Comment by minggo** [comment]
I send a pull request to use cocos console in #9708.

**Pull request closed without merging**
