### PR TITLE
fix the AssetsManagerEx can not continuous transmission

### PR DESCRIPTION
**Pull request by jianglong0156**
fix the AssetsManagerEx can not continuous transmission for large zip file.

the testcase is extension/assetsmanager

### CODE REVIEW

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by jianglong0156** [comment]
relate issue:https://github.com/cocos2d/cocos2d-x/issues/13729

**Comment by pandamicro** [comment]
Please take a look at https://github.com/cocos2d/cocos2d-x/pull/13617/files

He has a mutex to protect file writing process, it's more secured

**Comment by jianglong0156** [comment]
don't need to add the mutex, because the saveToFile callback to be called in main thread.There is no multi thread to use the function

**Comment by pandamicro** [comment]
Ok, review done, but this PR will have conflict with @yangws 's work, I will merge it to make the current Downloader working. After @yangws refined his PR, we will look into it together to see how to support well the download resuming.

**Comment by pandamicro** [comment]
@jianglong0156 I succeed to download the file but failed to extract it, log here:

```
JS: 98.00016021728516%
JS: 99.0000991821289%
Fail to rename file /Users/panda/Documents/JSBTests/AssetsManagerTest/scene4/cocos2d-x-3.8-rc0.zip.temp to /Users/panda/Documents/JSBTests/AssetsManagerTest/scene4/cocos2d-x-3.8-rc0.zip !Error code is -1
JS: 100%
JS: 100%
Fail to rename file /Users/panda/Documents/JSBTests/AssetsManagerTest/scene4/cocos2d-x-3.8-rc0.zip.temp to /Users/panda/Documents/JSBTests/AssetsManagerTest/scene4/cocos2d-x-3.8-rc0.zip !Error code is -1
AssetsManagerEx : can not extract file cocos2d-x-3.8-rc0/.gitattributes

JS: Unable to decompress file /Users/panda/Documents/JSBTests/AssetsManagerTest/scene4/cocos2d-x-3.8-rc0.zip
JS: Update finished. 
```

Please change the target file to a smaller one which should be about 20mb to 50mb.

**Pull request merged**
