### PR TITLE
add test javascript proj to mac port;

### PR DESCRIPTION
**Pull request by aninggo**

### CODE REVIEW

**Comment by minggo** [comment]
Thank you.
Could you please move the mac project file into samples/TestJavascript?

And i find there is a compiling error.

**Comment by minggo** [comment]
CompileC /Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/Objects-normal/i386/AppDelegate.o ../Classes/AppDelegate.cpp normal i386 c++ com.apple.compilers.llvmgcc42
    cd /Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac
    setenv LANG en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/usr/bin/llvm-gcc-4.2 -x c++ -arch i386 -fmessage-length=0 -pipe -Wno-trigraphs -fpascal-strings -O0 -Wreturn-type -Wunused-variable -DTARGET_OS_MAC -DDEBUG=1 -DUSE_FILE32API -DDEBUG=1 -fasm-blocks -mmacosx-version-min=10.6 -gdwarf-2 -iquote /Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/HelloCpp-generated-files.hmap -I/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/HelloCpp-own-target-headers.hmap -I/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/HelloCpp-all-target-headers.hmap -iquote /Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/HelloCpp-project-headers.hmap -I/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Products/Debug/include -I/usr/include/libxml2 -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../cocos2dx/include -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../cocos2dx -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../cocos2dx/platform/mac -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../cocos2dx/kazmath/include -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../scripting/javascript/spidermonkey-mac/include -I/Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../../../CocosDenshion/include -I/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/DerivedSources/i386 -I/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/DerivedSources -F/Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Products/Debug -include /Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/PrecompiledHeaders/TestJavascript_Prefix-dpbggavoyorvyngshypniodapnfv/TestJavascript_Prefix.pch -c /Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../Classes/AppDelegate.cpp -o /Users/zhangkoumyou/Library/Developer/Xcode/DerivedData/TestJavascript-damxenxzrzofcdfrmyudghzhlweg/Build/Intermediates/TestJavascript.build/Debug/TestJavascript.build/Objects-normal/i386/AppDelegate.o

i686-apple-darwin11-llvm-gcc-4.2: /Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/proj.mac/../Classes/AppDelegate.cpp: No such file or directory
i686-apple-darwin11-llvm-gcc-4.2: warning: '-x c++' after last input file has no effect
i686-apple-darwin11-llvm-gcc-4.2: no input files
Command /Applications/Xcode.app/Contents/Developer/usr/bin/llvm-gcc-4.2 failed with exit code 1

**Comment by aninggo** [comment]
it should be in samples/TestJavascript。 I made a mistake in commit。

**Comment by minggo** [comment]
I am sorry, there are many bugs.
I have fixed many, but at last, it says that :

ld: warning: ignoring file /Users/zhangkoumyou/SourceCode/cocos2d-x/scripting/javascript/spidermonkey-mac/lib/libjs_static.a, file was built for archive which is not the architecture being linked (i386)
Undefined symbols for architecture i386:
  "_JS_Init", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_NewContext", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_SetOptions", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_SetVersion", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_SetErrorReporter", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_NewCompartmentAndGlobalObject", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o
  "_JS_InitStandardClasses", referenced from:
      ScriptingCore::ScriptingCore()in ScriptingCore.o
      ScriptingCore::ScriptingCore()in ScriptingCore.o

It seems that the libjs_static.a is wrong.
Did you test the codes?

**Comment by aninggo** [comment]
XN-MBP:lib aninggo$ nm libjs_static.a | grep _JS_Init
000000000000b720 T _JS_Init
00000000000087c0 T _JS_InitClass
0000000000000620 T _JS_InitDestroyPrincipalsCallback
00000000000096a0 T _JS_InitStandardClasses
nm: no name list
0000000000000b10 T _JS_InitReflect
nm: no name list
nm: no name list
nm: no name list
nm: no name list
                 U _JS_InitClass

**Comment by aninggo** [comment]
XN-MBP:lib aninggo$ nm libjs_static.a | grep _JS_InitStandardClasses
00000000000096a0 T _JS_InitStandardClasses
nm: no name list
nm: no name list
nm: no name list
nm: no name list
nm: no name list

**Comment by aninggo** [comment]
XN-MBP:lib aninggo$ nm libjs_static.a | grep _JS_NewContext
000000000000ac90 T _JS_NewContext

**Comment by aninggo** [comment]
no link error happens when i run the test in my development environment。

**Comment by minggo** [comment]
@aninggo 
Did you syn your codes with latest cocos2d-x?

**Comment by aninggo** [comment]
I think so. possible path error for libjs_static.a 。try remove it 。re-add it in your environment。

**Pull request closed without merging**
