### PR TITLE
GLProgram replaceDefines correct and other feature

### PR DESCRIPTION
**Pull request by perminovVS**
replaceDefines if input more ; incorrect out
Example:
compileTimeDefines = "MAX_OPTIMIZATION;USE_PARAM1;"
out:
# define MAX_OPTIMIZATION
# define USE_PARAM1
# define

some device not compile this shader

Now compileTimeDefines = ";;MAX_OPTIMIZATION;;;USE_PARAM1;;;;"
out correct:
# define MAX_OPTIMIZATION
# define USE_PARAM1

### CODE REVIEW

**Comment by perminovVS** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
Thanks!

**Comment by ricardoquesada** [comment]
ouch... it is crashing right now with the Material Tests... I'll fix the patch.
The problem with this patch is that if the define doesn't end with a `;` it won't use it, and there is code that are setting defines without the final `;` and it must be 100% backward compatible

**Comment by perminovVS** [comment]
@ricardoquesada fix it #15376

**Pull request merged**
