### PR TITLE
Add Animate:getCurrentFrameIndex

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by pandamicro** [comment]
I think instead of giving the SpriteFrame reference, we should give user the frame id which will be more useful to identify the progression of the Animation, you can refer to the discussion in the original issue

**Comment by WenhaiLin** [comment]
@pandamicro I agree with you.

**Comment by WenhaiLin** [comment]
@pandamicro I agree with you.

**Comment by pandamicro** [comment]
@WenhaiLin Are you interested in adding the same functionality into the web engine ?

**Pull request merged**
