### PR TITLE
fix bug #12292 at CCLabel   and bug #12943 at CCScene

### PR DESCRIPTION
**Pull request by qiululu**
fix two bugs and at CCLabel and CCScene, test case can be seen at physicsTest demo.

### CODE REVIEW

**Comment by pandamicro** [comment]
Thank you, here are some suggestions and questions:
1. You should not mix two bug fixes into one PR.
2. Why do we need to add APIs for fixing bug ?
3. getFontConfigInfo is a getter function, it should not modify anything, it's also a serious mistake to modify another object's content.
4. You shouldn't use public APIs `setAdditionalProjection` internally, it will prevent user from using it, and it will cause issues when user use it

**Comment by qiululu** [comment]
1， for some reason , but it still have can be read easily.
2,  because it if I don't do so , it will be some modify to base class CCNode, it may be bad in design.
3, I will fix itl
4, for the concepts of the tranlation to a scene, this doing if better I think.

**Comment by pandamicro** [comment]
Your solution is not very proper, and it cannot be accepted.

**Comment by qiululu** [comment]
ok , wait for your suggestion. fixed 3

**Comment by qiululu** [comment]
ok, thanks,  I'll think it twice

**Pull request closed without merging**
