### PR TITLE
allow to use custom shader uniforms and attributes on drawNode

### PR DESCRIPTION
**Pull request by wighawag**

### CODE REVIEW

**Comment by wighawag** [comment]
I don't think the change is the reason the build is failing.

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@wighawag The PR seems not doing the things as the title said.

**Comment by wighawag** [comment]
it does though :)
basically the current method content

``` cpp
auto glProgram = getGLProgram();
glProgram->use();       
glProgram->setUniformsForBuiltins(transform);
```

does not call  applyAttributes(), nor   applyUniforms();
while te following does

``` cpp
getGLProgramState()->apply(transform);
```

see : https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/renderer/CCGLProgramState.cpp#L453

The current behavior disallow as the title say the use of custom shader uniforms and attribute

**Comment by minggo** [comment]
@wighawag Yep, you are right, `GLProgramState::apply()` will update uniforms and attributes too. Would you mind showing me how to reproduce the issue?

**Comment by wighawag** [comment]
if you do the following, the unifroms wont be taken into account:

``` cpp
darkenNode = DrawNode::create();
darkenNode->drawSolidRect(cocos2d::Vec2((winSize.width - nodeSize.width)/2.0, 0), nodeSize, cocos2d::Color4F(0.0, 0.0, 0.0, 0.0));
addChild(darkenNode);

auto glProgram = cocos2d::GLProgramCache::getInstance()->getGLProgram(ShaderTypes::kCCShader_RadialGradient);
auto glState = cocos2d::GLProgramState::getOrCreateWithGLProgram(glProgram);
darkenNode->setGLProgramState(glState);
glState->setUniformVec2("centre", cocos2d::Vec2(frameSize.width / 2.0, frameSize.height / 4.0));
glState->setUniformFloat("power", 1.0);
glState->setUniformVec2("dimensions", cocos2d::Vec2(frameSize.width / 5.0, frameSize.height / 5.0));
glState->setUniformVec4("centreColor", cocos2d::Vec4(17.0 / 255.0, 11.0 / 255.0, 56.0 / 255.0, 1.0));
glState->setUniformVec4("edgeColor", cocos2d::Vec4(0.0, 0.0, 0.0, 0.0));
```

**Comment by minggo** [comment]
Yep, you are right.

**Pull request merged**
