### PR TITLE
[cpp test]Unit Tests/9 neon math crash

### PR DESCRIPTION
**Pull request by PatriceJiang**
ref https://github.com/cocos2d/cocos2d-x/issues/19187#issuecomment-442970218

### CODE REVIEW

**Comment by Dimon4eg** [comment]
What reason of crash?
How replacing raw arrays by vector fixes the crash?

**Comment by crazyhappygame** [comment]
I join the question. Could you explain what and how it was fixed?

**Comment by PatriceJiang** [comment]
Sorry, I don't get the real reason for now. It may be a issue about `-O3` & `inline asm code`.

**Comment by PatriceJiang** [comment]
Here is another neat solution https://github.com/cocos2d/cocos2d-x/pull/19224, I will close this PR later.

**Comment by crazyhappygame** [comment]
Sorry this is not a solution. You have workaround for test but what about production code?

Could you check https://github.com/cocos2d/cocos2d-x/pull/18895 ? It could be related.

**Comment by PatriceJiang** [comment]
Yes, it is just a workaround to make the test case pass, and I will try to fix this issue early next week.

**Pull request closed without merging**
