### PR TITLE
HttpClient Android supports gzip

### PR DESCRIPTION
**Pull request by gyf19**
HttpClient Android supports gzip

### CODE REVIEW

**Comment by gyf19** [comment]
为什么只改java代码， mac 版本编译错误？

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Originally reported: https://github.com/cocos2d/cocos2d-js/issues/1756

Thank you for the fix, we will test it on win32

**Comment by gyf19** [comment]
ok , Thank you

**Comment by gyf19** [comment]
[ci rebuild]

**Comment by jianglong0156** [comment]
[ci rebuild]

**Pull request merged**
