### PR TITLE
fix: Scale9Sprite test case 18

### PR DESCRIPTION
**Pull request by ricardoquesada**
Bug calculating rotated frames.
the width was being used instead of the height and vice-versa

### CODE REVIEW

**Comment by minggo** [comment]
please send to v3.14 branch too, thanks

**Comment by ricardoquesada** [comment]
@minggo 
oops, yes. here it is:
https://github.com/cocos2d/cocos2d-x/pull/16898

**Comment by dumganhar** [comment]
This pull request fixes `UIS9_TexturePacker`.
But `UIS9FrameNameSpriteSheetCropped` and `UIS9FrameNameSpriteSheetCroppedRotated ` is still not fixed.

**Comment by ricardoquesada** [comment]
@dumganhar yes, correct. I'm still working on that. I thought it was the same bug, but it is not :(

**Comment by ricardoquesada** [comment]
@dumganhar so, I almost fixed test cases 8 and 7. There is an offset of 2 pixels... I might be doing the math incorrectly somewhere. I'll fix it after holidays (this monday).

I did the math manually, and it matches what it happens on the code... but as I said, perhaps the bug is somewhere else.
screen shot 2016-11-24 at 1 03 26 am

**Comment by ricardoquesada** [comment]
I'll merge it and on Monday I'll send a new PR with this "2 pixel" issue bug.

**Comment by ricardoquesada** [comment]
PR for v3.14: https://github.com/cocos2d/cocos2d-x/pull/16902

**Comment by minggo** [comment]
Currently, the codes is complex. I think we can use matrix to simplify it. Don't modify texture coordinate and vertex coordinate manually, just use model matrix to do it. It will make things more clear. Of course we can optimize matrix operation as we did in `Node::getNodeToParentTransform()`.

**Comment by ricardoquesada** [comment]
yes, agreed. the code is complex.  good idea about rotating the texture, although I'm not sure if that would be feasible... but for sure, the code should be simplified. too many `if(_rotated)` scattered in different files.

**Pull request merged**
