### PR TITLE
fix: uses correct constant for Eye in Director

### PR DESCRIPTION
**Pull request by ricardoquesada**
fixes github issue #8354

### CODE REVIEW

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by TheCodez** [comment]
@ricardoquesada I get some strange artifacts of the background leaking 1 pixel after this change. The object has a y position of 0 so the background shouldn't be visible
Left side before the change, right after:

image

**Comment by ricardoquesada** [comment]
@TheCodez thanks. I'll review it.

**Comment by ricardoquesada** [comment]
@TheCodez thanks. I need to do more research. PR reverted.

**Pull request merged**
