### PR TITLE
Fixed compile error when I turned off physics definitions.

### PR DESCRIPTION
**Pull request by cpascal**
Fixed the following compile error.
cocos2d\extensions\physics-nodes\ccphysicssprite.cpp(305): error C4716:
'cocos2d::extension::PhysicsSprite::getRotation' : must return a value
and more..

Conditions:
CC_USE_PHYSICS = 0
CC_ENABLE_CHIPMUNK_INTEGRATION = 0
CC_ENABLE_BOX2D_INTEGRATION = 0

### CODE REVIEW

**Comment by minggo** [comment]
But `CC_USE_PHYSICS` is used for physics integration in engine. It is not used for using external physical engine.

**Comment by cpascal** [comment]
@minggo Is it okay to use "#if (!CC_ENABLE_CHIPMUNK_INTEGRATION) and (!CC_ENABLE_BOX2D_INTEGRATION)" instead of "#if CC_USE_PHYSICS"?

**Comment by minggo** [comment]
@cpascal 
I think it is ok.
The modification seems good.

**Comment by cpascal** [comment]
I've checked the build server log at http://115.28.134.83:8000/job/cocos-2dx-pull-request-build/5250/node=linux_centos/console

It says "fatal: Not a git repository: external/../.git/modules/external"..
It seems that this error is not occured by this code.

**Comment by darkdukey** [comment]
[ci rebuild]

**Pull request merged**
