### PR TITLE
fix problem : JumpTo position is changed each repeat.

### PR DESCRIPTION
**Pull request by ton1517**
example:

```
sprite->runAction(
    RepeatForever::create(
        Sequence::create(
            JumpTo::create(1, Vec2(300, 200), 100, 2),
            MoveTo::create(1, Vec2(100, 200)),
            nullptr
        )
    )
);
```

### CODE REVIEW

**Comment by minggo** [comment]
I am sorry.
What's the issue?

**Comment by ton1517** [comment]
The issue is JumpTo action go to wrong position in Repeat action.

`_delta` is changed at `startWithTarget` each time repeat.

```
_delta = Vec2(_delta.x - _startPosition.x, _delta.y - _startPosition.y);
```

fix

```
_delta = Vec2(_endPosition.x - _startPosition.x, _endPosition.y - _startPosition.y);
```

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Yep.
You are right.

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
