### PR TITLE
fix bug:use wrong _modelviewTransform in director to draw bone

### PR DESCRIPTION
**Pull request by geron-cn**
fix bug:use wrong _modelviewTransform in director to draw bone

### CODE REVIEW

**Comment by geron-cn** [comment]
@zilongshanren @pandamicro   fix a bug: bone draw at the other edge when move to outside right edge.

@VisualSJ   could you please sync this to js.

**Comment by pandamicro** [comment]
We should enhance our test case to ensure this problem is solved and future stability

**Comment by pandamicro** [comment]
[ci rebuild] ios not pass

**Comment by pandamicro** [comment]
Bug fix for https://github.com/cocos2d/cocos2d-x/issues/12982

**Pull request merged**
