### PR TITLE
NaCl fixes

### PR DESCRIPTION
**Pull request by sbc100**
This is largely a simplification to use the new nacl_io module which makes filesystem access much easier.

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. @sbc100 
But it seems that you didn't pull the latest codes of `cocos2d/cocos2d-x` `develop` branch.
There will be lots of conflicts since we have done a refactor of member variable renaming.

**Comment by dumganhar** [comment]
BTW, does native client support C++11? 
We are developing `cocos2d-x 3.0` on develop branch.
I closed the travis-ci build for `native client` since it seems that `native client` doesn't support `c++11` well.

**Comment by dumganhar** [comment]
@sbc100 
You probably need to close `travis-ci` build for your own remote repo(sbc100/cocos2d-x).
Otherwise the travis-ci doesn't know to build the Pull Request for cocos2d/cocos2d-x.

**Comment by sbc100** [comment]
I made these changes against master, hoping to get them pulled into master.

I didn't know about the new develop branch.   Does this mean that the master branch is completely closed now?  Any chance I can still land these changes in master?  What is the plan regarding the develop branch?

Regarding C++-11, we have some support for some features but it depends on which of the compilers is being used, we have separate, x86-gcc, arm-gcc and clang compilers in NaCl.  Are you planning on making C++-11 a core requirement of the new version?   That would seem to me to go against the goal of maximum portability.

Regarding travis, I'd quite like to keep my travis build going so I can push changes to my repo and confirm that they pass.  Right now the only failure with travis seems to be related to the GEN_JSB stage, which seems to be failing with no reason give.  Can you shed any light on this?

**Comment by sbc100** [comment]
Ok, I will rebase this change onto "develop" and try to re-enable travis for at least some of the nacl configs on the develop branch, and send a new PR for that.

If there is any chance of another 2.X release then I'd like to land this change on there too.

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/2955.
Close it.

**Pull request closed without merging**
