### PR TITLE
issue #3828: Remove samples other than testcpp/testjavascript/testlua

### PR DESCRIPTION
**Pull request by dumganhar**
Sample games should be placed at https://github.com/cocos2d/samples.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@minggo @dumganhar 
After this PR, I cannot longer run "Test JavaScript iOS" (device or simulator).
Whenever I try to run it, Xcode gives me a very weird error.

Could you take a lookt at it ?
thanks.

**Comment by ricardoquesada** [comment]
screen shot 2014-01-31 at 5 24 14 pm

That's the error that I'm receiving.

What is strange is that: Test Lua iOS works Ok, and Test JavaScript Mac works Ok too.

**Comment by dumganhar** [comment]
Hi Riq,
    That’s really strange. I just removed unused targets(HelloCpp, HelloLua, JSB games..) from cocos2d_samples projects.
I didn’t modify any configuration of TestCpp, TestLua and TestJS. After I googled it, lots of voice said that it’s a bug of Xcode.
And I tried all methods they mentioned, but also could not fix the problem.
All target for Mac could work as expect. And the target for iOS device could also work on my computer.
Only TestLua and TestJavascript COULD NOT run. I will try to check out the problem when I have time. Sorry for that. ;)

Happy New Year!
James

**Comment by ricardoquesada** [comment]
Thanks James!
Yes, I tried to do the "Reset..." thing on the Simulator, remove the files from the Library, tried on a different computer, but it didnd't work.

Perhaps there is something different on the Xcode project... Not sure what it is.

**Comment by ricardoquesada** [comment]
and yes, Happy New Year!

**Comment by dumganhar** [comment]
I fixed it. I will submit a new PR soon and share the solution.

**Comment by ricardoquesada** [comment]
great! thanks!

**Comment by dumganhar** [comment]
Riq, I fixed it at https://github.com/cocos2d/cocos2d-x/pull/5281 .
Could you try again? Don't forget to 
- Reset simulator
- Remove files in `/Users/your_name/Library/Developer/Xcode/DerivedData`

**Comment by dumganhar** [comment]
Re-add Icon resources at https://github.com/cocos2d/cocos2d-x/pull/5282.

**Comment by ricardoquesada** [comment]
thanks James. It is working Ok now.

**Pull request merged**
