### PR TITLE
Update CCTransformHelp.cpp

### PR DESCRIPTION
**Pull request by halx99**
fix bug: nodeToMatrix(const BaseData&, Mat4&)

### CODE REVIEW

**Comment by halx99** [comment]
sin,cos,etc accept radius，but degrees gives.

**Comment by minggo** [comment]
@chengstory 
Please take a look.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by dabingnn** [comment]
@xseekerj The newest codes of `nodeToMatrix` and `matrixToNode` are a pair function.
It is radian, I think you can convert you data to radian before using the function.
Thanks.

**Comment by halx99** [comment]
@dabingnn I'm not call the function directly; that's the truth:when I rotate a armture throgth touch enent,the behavior isn't correctly.

**Comment by dabingnn** [comment]
I think there is no bug in `nodeToMatrix`. If the behaviour of `Armature` is  not correct, there may be some bugs in armature. Could you please give a description of the problem? And if there is a test case to reproduce the bug, it would be more clearer.

**Comment by halx99** [comment]
In Version:3.2: This function is called at CCBone.cpp:219, and _skewX,_skewY,_rotationZ_X,_rotationZ_Y are used directly which are the members of cocos2d::Node. 

I  realized follow diff: 
version 3.2: 
_worldInfo->skewX = _worldInfo->skewX + _skewX + rotationZ_X; 
_worldInfo->skewY = _worldInfo->skewY + _skewY - rotationZ_Y; 
newest version:
_worldInfo->skewX = _worldInfo->skewX + _skewX + CC_DEGREES_TO_RADIANS(_rotationZ_X); 
_worldInfo->skewY = _worldInfo->skewY + _skewY - CC_DEGREES_TO_RADIANS(_rotationZ_Y);

**Comment by halx99** [comment]
So I think convert the data to radian in the pair function maybe a better choice.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
