### PR TITLE
v3.11 updated expiration dates of all winrt test app and template certificates

### PR DESCRIPTION
**Pull request by stammen**
This pull requests fixes the expiring app certificates for all of the winrt projects and templates.

@minggo Please pull this request before v3.11 ships as some of the certs expired yesterday.

### CODE REVIEW

**Comment by minggo** [comment]
@stammen Could you please fix compiling error?

**Comment by stammen** [comment]
@minggo it is not a compiling error

PDB API call failed, error code '23'  is a known Jenkins issue.

https://issues.jenkins-ci.org/browse/JENKINS-9104

Please do another build

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@stammen Is there a method to fix it?

**Comment by stammen** [comment]
@minggo I opened issue https://github.com/cocos2d/cocos2d-x/issues/15506 to track the PDB API call failed, error code '23' Jenkins issue.

**Comment by minggo** [comment]
@stammen Thanks.

**Pull request merged**
