### PR TITLE
Fix ParticleSystem etc1 alpha support.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by minggo** [comment]
@dumganhar has a point to refactor ECT1 support. @dumganhar could you please discuss it with @halx99 ?

**Comment by dumganhar** [comment]
Basically, current etc1 support is a little tricky.
`setGLProgramState` is invoked in `Sprite::setTexture` while it was set in `Sprite::initWithFile` before.  So
* We have coupled the `setTexture` and `setGLProgramState` now.
* `GLProgramState::getOrCreateWithGLProgramName` should pass a second parameter `texture` for detecting whether it's a etc1 texture instance which is strange, from developer's view, why should this public interface need a texture argument?
* We change the shader internally by `GLProgramState::getOrCreateWithGLProgramName(const std::string& glProgramName, Texture2D* texture)` which isn't clear enough. Because we steal the program name developer passes in and replace it with a new `ETC1` one. Please refer to the following logic.
```c++
void Sprite::setTexture(Texture2D *texture)
{
    if(_glProgramState == nullptr)
    {
        setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP, texture));
    }
    ...
}

GLProgramState* GLProgramState::getOrCreateWithGLProgramName(const std::string& glProgramName, Texture2D* texture)
{
    if (texture != nullptr && texture->getAlphaTextureName() != 0) {
        if (glProgramName == GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR) {
            return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR);
        }
        else if (glProgramName == GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP) {
            return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR_NO_MVP);
        }
        else if (glProgramName == GLProgram::SHADER_NAME_POSITION_GRAYSCALE) {
            return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_GRAY_NO_MVP);
        }
    }

    return GLProgramState::getOrCreateWithGLProgramName(glProgramName);
}
```

Possible Solution I guess:

* Decouple the `Sprite::setTexture` and `setGLProgramState`.
* Revert to `setGLProgramState` in `Sprite::initWithFile/initWithTexture`.
* Developer has responsibility to reset `GLProgram` from `Normal` to `ETC1` or from `ETC1` to `Normal`. For example,
```c++
auto sprite = Sprite::create("xxx.png"); // Normal png file
sprite->setTexture("yyy.pkm"); // Set to a ETC1 texture.
sprite->setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR_NO_MVP)); // Developer has responsibility to set it to ETC1 shader
```
```c++
auto sprite = Sprite::create("xxx.pkm"); // ETC1 file
sprite->setTexture("yyy.png"); // Set to a png texture
sprite->setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP)); // Developer has responsibility to set it to normal shader
```

* getOrCreateWithGLProgramName(name, texture) method isn't needed any more.

In this case, it's more complex than before, however, they are decoupled and we don't hide any implementation.
This is my ten cents. What about your opinions, @minggo @halx99 and all developers?

@minggo , Anyway, for now, I suggest to merge the etc1 patches from @halx99 since there are some bugs need to fixed. Otherwise, developer probably can not use etc1 for particles, UIs.

For further, we need to refactor this logic. I know that may be some days or months later if this is assigned to me. If you guys have better solutions, please reply here.

Perhaps, @halx99 has time to refactor this?

**Comment by halx99** [comment]
Currently, I have no time to refactor this, and I have not a good idea to refactor it.
which is easy to use without any additional changes at developer side.

**Comment by halx99** [comment]
what about add a function to Node setGLProgramStateStable to prevent engine update it internally?

**Comment by halx99** [comment]
> Basically, current etc1 support is a little tricky.
> `setGLProgramState` is invoked in `Sprite::setTexture` while it was set in `Sprite::initWithFile` before. So
> 
> * We have coupled the `setTexture` and `setGLProgramState` now.
> * `GLProgramState::getOrCreateWithGLProgramName` should pass a second parameter `texture` for detecting whether it's a etc1 texture instance which is strange, from developer's view, why should this public interface need a texture argument?
> * We change the shader internally by `GLProgramState::getOrCreateWithGLProgramName(const std::string& glProgramName, Texture2D* texture)` which isn't clear enough. Because we steal the program name developer passes in and replace it with a new `ETC1` one. Please refer to the following logic.
> 
> ```c++
> void Sprite::setTexture(Texture2D *texture)
> {
>     if(_glProgramState == nullptr)
>     {
>         setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP, texture));
>     }
>     ...
> }
> 
> GLProgramState* GLProgramState::getOrCreateWithGLProgramName(const std::string& glProgramName, Texture2D* texture)
> {
>     if (texture != nullptr && texture->getAlphaTextureName() != 0) {
>         if (glProgramName == GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR) {
>             return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR);
>         }
>         else if (glProgramName == GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP) {
>             return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR_NO_MVP);
>         }
>         else if (glProgramName == GLProgram::SHADER_NAME_POSITION_GRAYSCALE) {
>             return GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_GRAY_NO_MVP);
>         }
>     }
> 
>     return GLProgramState::getOrCreateWithGLProgramName(glProgramName);
> }
> ```
> 
> Possible Solution I guess:
> 
> * Decouple the `Sprite::setTexture` and `setGLProgramState`.
> * Revert to `setGLProgramState` in `Sprite::initWithFile/initWithTexture`.
> * Developer has responsibility to reset `GLProgram` from `Normal` to `ETC1` or from `ETC1` to `Normal`. For example,
> 
> ```c++
> auto sprite = Sprite::create("xxx.png"); // Normal png file
> sprite->setTexture("yyy.pkm"); // Set to a ETC1 texture.
> sprite->setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_ETC1AS_POSITION_TEXTURE_COLOR_NO_MVP)); // Developer has responsibility to set it to ETC1 shader
> ```
> 
> ```c++
> auto sprite = Sprite::create("xxx.pkm"); // ETC1 file
> sprite->setTexture("yyy.png"); // Set to a png texture
> sprite->setGLProgramState(GLProgramState::getOrCreateWithGLProgramName(GLProgram::SHADER_NAME_POSITION_TEXTURE_COLOR_NO_MVP)); // Developer has responsibility to set it to normal shader
> ```
> 
> * getOrCreateWithGLProgramName(name, texture) method isn't needed any more.
> 
> In this case, it's more complex than before, however, they are decoupled and we don't hide any implementation.
> This is my ten cents. What about your opinions, @minggo @halx99 and all developers?
> 
> @minggo , Anyway, for now, I suggest to merge the etc1 patches from @halx99 since there are some bugs need to fixed. Otherwise, developer probably can not use etc1 for particles, UIs.
> 
> For further, we need to refactor this logic. I know that may be some days or months later if this is assigned to me. If you guys have better solutions, please reply here.
> 
> Perhaps, @halx99 has time to refactor this?

Agree withs you.

**Comment by halx99** [comment]
Recently, I think, we should design multi-texture support to cover ETC1 alpha or other purpose use, and we should like follow:
1. Now the CCTexture2D should replace textureID to std::vector<GLuint> textureIDs, and the index 0 is major textureID which used for _materialID
2. Provide a global config such globalShaderIndexs for texture format default shader program, for etc1 we can add to the  globalShaderIndexs, and index ```1``` default use as etc1 alpha program.
3. And user can setup them custom mutli-texture program, add more than 2 texture.
4. This solution is will reduce memory use: single memory(CCTexture2D), mutli-GPU memory(textureIDs).
@minggo what do you think about this.

**Comment by minggo** [comment]
How can you achieve it without break compatibility?

**Comment by halx99** [comment]
Maybe v4 or v4-next

**Comment by minggo** [comment]
Support multi texture is much more easier in v4. Can i close this PR?

**Comment by halx99** [comment]
Yes, I think you can create another issue for muti texture topic.

**Comment by halx99** [comment]
And this pr should be closed.

**Pull request closed without merging**
