### PR TITLE
use tinyxml2 instead of libxml2

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by martell** [comment]
Man that was good thanks minggo :)

**Comment by minggo** [comment]
It is my pleasure.

**Comment by martell** [comment]
Does this get me on the Authors list for my CV? :)

**Comment by minggo** [comment]
I am sorry, just added it.

**Comment by martell** [comment]
Yay :+1:
On my CV :)

**Comment by RichardGale** [comment]
Does tinyxml improve parsing time, or decrease memory use? Any links to resources/results on this change?

**Pull request merged**
