### PR TITLE
[iOS EditBox] add toolbar to exit out of numeric keyboard

### PR DESCRIPTION
**Pull request by saumyamukul**
There is no way to exit out of the keypad. This adds a "Done" button

### CODE REVIEW

**Comment by saumyamukul** [comment]
What it looks like

IMG_0076

**Comment by minggo** [comment]
The keyboard will disappear if you click the area that outside of EditBox.

**Comment by saumyamukul** [comment]
Thats a good point. We've implemented accessibility for our cocos2d-x application, and with Voiceover on, it is not possible for the user to exit the keypad. 
Feel free to close this though. Anyone who wants this functionality can refer to this MR :)

**Comment by minggo** [comment]
Thanks.

**Pull request closed without merging**
