### PR TITLE
Run script from string

### PR DESCRIPTION
**Pull request by alenl2**
I use this so i can reload my JS files directly from server(Websocket or xmlhttprequest) i makes quick fixes much quicker :)

### CODE REVIEW

**Comment by nakosung** [comment]
You can do that within javascript by calling 'eval(javascriptSourceCode)'. BTW, AFAIK, spider monkey has a performance issue with eval'ed code comparing to compiled code..

**Comment by alenl2** [comment]
i was thinking the same thing but it dos not work. if i use eval() you get errors like 
Cocos2d: JS: ....../jsb_cocosbuilder.js:74:TypeError: _ccbGlobalContext[documentControllerName] is not a constructor

and i'm thinking i dident do the pull request right... right?

**Comment by nakosung** [comment]
Disclaimer: I'm not a collab of cocos2d-x.

'eval' isn't different from executeScript. You can check it within console of your browser. Are you requiring jsb.js in your 'eval'?

**Comment by alenl2** [comment]
yes i do. i use cocosbuilder generated files

**Pull request closed without merging**
