### PR TITLE
Add scrolling to item and magnetic scroll into ListView

### PR DESCRIPTION
**Pull request by neokim**
Improvements for ListView
- Add APIs to scroll to specific item in list.
- Add APIs to get an item in specific position like center, leftmost, rightmost, topmost and bottommost.
- Add a feature for magnetic scrolling.

### CODE REVIEW

**Comment by pandamicro** [comment]
@zilongshanren @ZhangMenghe Please review this PR

**Comment by zilongshanren** [comment]
@neokim 
The win32 and windows-universal build is failed.

**Comment by zilongshanren** [comment]
@neokim 
After the CI is passed, I will merge this PR.

**Comment by neokim** [comment]
@zilongshanren Ok, thanks. :+1:

**Comment by zilongshanren** [comment]
@neokim  
:+1:    merged.

**Pull request merged**
