### PR TITLE
fix cocostudio anchor point bug

### PR DESCRIPTION
**Pull request by m2q1n9**
fix a bug which will cause anchor point config not work

### CODE REVIEW

**Comment by minggo** [comment]
@chengstory 
Could you please take a look?

**Comment by chengstory** [comment]
I ask @pipu to take a look.

**Comment by pipu** [comment]
@m2q1n9 
Could you tell us which version of cocos2d-x are you using?

**Comment by m2q1n9** [comment]
@pipu 
cocos2d-x 3.4 + cocostudio 1.6

**Comment by pipu** [comment]
Thanks for m2q1n9.
This pull request can be merged.

**Comment by zilongshanren** [comment]
@m2q1n9  This PR is buggy. :-1:

**Pull request merged**
