### PR TITLE
replaces std::for_each with for()

### PR DESCRIPTION
**Pull request by ricardoquesada**
replaces `std::for_each` with C++11 `for( : )`

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks, Riq.:)

**Comment by ricardoquesada** [comment]
no problem.
If you search for `std::for_each` there are a few places that I didn't change... (two or three more places).
If you could replace them with `for()` it would be great. thanks.

**Comment by dumganhar** [comment]
OK, I will replace it today.
- James

**Comment by ricardoquesada** [comment]
thanks

**Pull request merged**
