### PR TITLE
Fixed the video player not showing on iOS if it's not in FullScreen mode

### PR DESCRIPTION
**Pull request by ghost**
Hi,

it's just a quick fix (setHidden:!visible), I'm sorry about the all the tabs getting removed, but my editor remove them automatically on save.

### CODE REVIEW

**Comment by WenhaiLin** [comment]
@DavidPartouche Thank you.
@minggo We should merge this PR.

**Comment by minggo** [comment]
@DavidPartouche 
Would you please fix the conflict?

**Comment by minggo** [comment]
@Dhilan007 
Could you please send a pull request to fix conflict of this PR?

**Comment by minggo** [comment]
I fixed conflict in #7715.

**Comment by ghost** [comment]
Hi I'm really sorry I don't get the notifications by emails, so didn't see the request, I'm gonna activate them now for next time.

**Comment by minggo** [comment]
@DavidPartouche 
No problem.
Thank you for your contribution.

**Pull request merged**
