### PR TITLE
Adds setNormalizedPosition()

### PR DESCRIPTION
**Pull request by ricardoquesada**
Changes in `visit()` were done in order to do it
in a robust and fast way.

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ChinaPuffer** [comment]
我可以说中文么

在 2014-06-03 03:55:13，"minggo" notifications@github.com 写道：

[ci rebuild]

**Comment by minggo** [comment]
English please, or @ricardoquesada will not understand what you say.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
any update?

**Comment by minggo** [comment]
I think it is not problem for the PR.
But the building seems to failed.

**Comment by ricardoquesada** [comment]
where does it fail?

UPDATE: I found where if fails. I'll fix it and once it compiles Ok I'll merge it.

**Pull request merged**
