### PR TITLE
fix crash if csb file is broken

### PR DESCRIPTION
**Pull request by Dimon4eg**

### CODE REVIEW

**Comment by pandamicro** [comment]
@xiaofeng11 Please review this PR

**Comment by xiaofeng11** [comment]
@Dimon4eg I think this pr is fix program crash when csb file is broken, but not csb file missing, please fix the title of this pr, thanks.

**Comment by pandamicro** [comment]
Done, @xiaofeng11 is this a proper fix ?

**Comment by xiaofeng11** [comment]
@pandamicro Yes, If there's nothing have been readout from the csb file, We won't need parse a blank data buffer, It will cause access error.

**Pull request merged**
