### PR TITLE
Add scroll bar feature into ScrollView

### PR DESCRIPTION
**Pull request by neokim**
Add scroll bar feature into ScrollView.
- It can be enabled / disabled.
- It auto-hides itself when move is ended. Auto-hide can be also enabled / disabled.
- The width is adjustable.
- The color is adjustable.
- Position can be changed.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@neokim  :+1:   I will review the code later.
Thanks very much.

**Comment by man2** [comment]
Wow. This is really great, thanks

**Comment by TheCodez** [comment]
@andyque Please get this into 3.7

**Comment by zilongshanren** [comment]
@TheCodez  The v3.7 is in feature freeze stage, so I'm sorry.  If you do need this feature, you could manually grab this patch. Thanks.

**Comment by zilongshanren** [comment]
@neokim  There is a bug here. When the scrollview is created, if I press the button and start to drag, the scrollview can't be moved. If I don't touch a Button and start drag, the scrollview can be dragged and now if I press the button to drag again, it works.

**Comment by neokim** [comment]
@andyque I found that the bug you mentioned about button is originated from elastic scroll view PR. I will figure it out soon. Thanks.

**Comment by zilongshanren** [comment]
@neokim  This PR is great. At first, I would say thanks again for your hard work :+1: 
A few suggestions here: I found many indentation fix in your commit which is not friendly for me to review.  Lots of change highlighting in the diff view. I suggest you to configure your editor with cocos2d-x indent convention.
Thanks.

**Comment by neokim** [comment]
@andyque It was annoying me either, because I had to change tabs to spaces every time. As you suggested, I found per-project configuration in Xcode and modified it. You can change the per-project setting and commit it. Why don't you change all project settings in Cocos2d-x to use spaces instead of tab?

**Comment by zilongshanren** [comment]
@neokim  thanks. I don 't know why cocos2d-x don't change all the project settings. Because my XCode global settings are using 4 spaces instead of tab.

**Comment by neokim** [comment]
@andyque The bug you mentioned is not caused by my change.
Currently, if scroll view intercepts a touch from its widget at first, `_hittedByCamera` is null. And it causes `handleMoveLogic()` to cancel every move. It is committed in f8a5b1e18c071bb1bcc37c4dd273f93ee4d730ad.
 You can find same bug in 2774d6ff1d26fa267014f89e8ff3e557fb12d90c as well.

**Comment by zilongshanren** [comment]
@neokim  Thanks, I will check with @yangws  about the bug.

**Comment by neokim** [comment]
@andyque Ok, thanks.

**Comment by zilongshanren** [comment]
@neokim  The touch bug has been solved here: https://github.com/cocos2d/cocos2d-x/pull/12711

**Comment by neokim** [comment]
Good :+1: 
@andyque Thank you!

**Pull request merged**
