### PR TITLE
update for light3d reader

### PR DESCRIPTION
**Pull request by liamcindy**
https://github.com/dumganhar/ccs-res/pull/51

### CODE REVIEW

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
There is a problem in submodule, please fix it

**Comment by liamcindy** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Please add JS parser for Light 3D

**Pull request merged**
