### PR TITLE
Update Cocos2dxTextInputWraper.java

### PR DESCRIPTION
**Pull request by hongwd75**
If you enter in that letter that you are using the Korean and combination-type language in the 3.7 version, there are times when a problem occurs assets in the course of the combination of the character character is wrong output.

### CODE REVIEW

**Comment by hongwd75** [comment]
If you enter in that letter that you are using the Korean and combination-type language in the 3.7 version, there are times when a problem occurs assets in the course of the combination of the character character is wrong output.

**Comment by pandamicro** [comment]
Sorry we can't review and merge your contribution for a short time, because we are testing v3.8 and prepare its release, so please be patient
If you think it's very important, please tell us

**Comment by hongwd75** [comment]
이 문제는 cocos2dx 2.0 부터 계속되어 발생하고 있는 문제입니다.
한국의 개발자들은 매번 새로운 cocos2dx 버전이 나 올때 마다, 
cocos2dx의 코드를 수정해야 텍스트 입력기가 제대로 동작하여, 많이 힘듭니다.
이번 버전에서는 반드시 수정되었으면 합니다.
この問題は、 cocos2dx 2.0から続いて発生している問題です。
韓国の開発者は、毎回新しいcocos2dxバージョンや来るたびに、
cocos2dxのコードを変更する必要がテキスト入力システムが正常に動作して、多くの困難です。
今回のバージョンでは、必ず修正された場合です。
This problem is a problem that is occurring Following from cocos2dx 2.0.
Korean developers , each time you come new cocos2dx version and every time ,
cocos2dx need a text input system to change the code of the operating normally , there are many difficulties.
In this version , it is the case that always has been fixed .

**Comment by pandamicro** [comment]
@WenhaiLin @zilongshanren Please give some advises

**Comment by zilongshanren** [comment]
@hongwd75  Could you resolve the merge conflicts, thanks.

**Pull request closed without merging**
