### PR TITLE
Fix GroupRadioButton disallow selection won't work bug.

### PR DESCRIPTION
**Pull request by xiaofeng11**
In CocoStudioTest->CocoStudioGUITest->UIRadioBoxTest of lua-test project, use toggle button switch between "No selection is allowed" and "No selection is disallowed", there hasn't any difference between these mode, In "No selection is allowed" mode, still can change selection to other radio button

### CODE REVIEW

**Comment by xiaofeng11** [comment]
@neokim GroupRadioButton fix pr move to here, please review.

**Comment by zilongshanren** [comment]
[ci rebulid]

**Comment by neokim** [comment]
@xiaofeng11 Hi, could you describe what this fix is for exactly?

**Comment by xiaofeng11** [comment]
@neokim I've add the reason why do I change code to description section.

**Comment by neokim** [comment]
@xiaofeng11 There must be some misunderstanding.

Allowing no-selection feature is for an option that a radio button group can have no selected radio button at all in its group. Please have a look at the API description of `RadioButtonGroup::setAllowedNoSelection()`.

If no-selection is disallowed, the first item will be auto-selected when it is being added. You can see the difference when you add and remove radio buttons several times in `UIRadioButtonGroupTest` in cocos2d_tests project.

**Comment by xiaofeng11** [comment]
@neokim OK, seems our test group give me a wrong message to look this as a bug. I'll close this pr now.

**Pull request closed without merging**
