### PR TITLE
Combine Studio change for spine

### PR DESCRIPTION
**Pull request by xiaofeng11**
Add export statement to function and class to make them can be compile as dynamic library in cocostudio project

@pandamicro @minggo Please review this pr

### CODE REVIEW

**Comment by minggo** [comment]
As i know, we can not modify spine codes because of its license.

**Comment by xiaofeng11** [comment]
@minggo Just talk with XieXin we will use static lib of spine, so we won't need modify it any more. But the license of spine is conflict with cocos2dx license, why does it have been embed?

**Comment by minggo** [comment]
Because spine is well, many developers want it.
If developers modify the spine code, it is nothing about cocos2d-x, but we can not modify it.

**Comment by xiaofeng11** [comment]
I known, Thanks a lot. I'll close this PR.

**Pull request closed without merging**
