### PR TITLE
performance fixes in QuadCommand

### PR DESCRIPTION
**Pull request by ricardoquesada**
performance fixes in QuadCommand

### CODE REVIEW

**Comment by minggo** [comment]
I think `generateMaterialID` should be `protected` or `private`.

**Comment by ricardoquesada** [comment]
yes, you are right. But this patch didn't change the scope of `generateMaterialID()`.
This patch fixes the cache. There was a `dirty` flag but it was always `dirty = true;`. 
I think it is `public` for legacy reasons, but, yes, feel free to change it.

**Comment by minggo** [comment]
Ok, I will modify it in other thread.

**Comment by ricardoquesada** [comment]
ok. thanks.

**Comment by minggo** [comment]
@ricardoquesada 
Done in #6174.

@thoechsmann 

> Looks like the _last members are not initialised. Do you need them at all? Just move the test if a parameter has changed a bit upwards.

Yep, `_lastShader` and `_lastBlendType` are not initialized. I will fix it in another PR. But what did you mean they were needless?

**Comment by thoechsmann** [comment]
Like this. If I am not missing something, it will do the same without the need of the "last" members.

```
void QuadCommand::init(float globalOrder, GLuint textureID, GLProgram* shader, BlendFunc blendType, V3F_C4B_T2F_Quad* quad, ssize_t quadCount, const kmMat4 &mv)
{
    if( _textureID != textureID || _blendType.src != blendType.src || _blendType.dst != blendType.dst || _shader != shader) {
        generateMaterialID();
    }

    _textureID = textureID;
    _blendType = blendType;
    _shader = shader;
    _globalOrder = globalOrder;
    _quadsCount = quadCount;
    _quads = quad;
    _mv = mv;
}
```

**Comment by thoechsmann** [comment]
small fix:

```
void QuadCommand::init(float globalOrder, GLuint textureID, GLProgram* shader, BlendFunc blendType, V3F_C4B_T2F_Quad* quad, ssize_t quadCount, const kmMat4 &mv)
{
    if( _textureID != textureID || _blendType.src != blendType.src || _blendType.dst != blendType.dst || _shader != shader) {
       _textureID = textureID;
       _blendType = blendType;
       _shader = shader;
        generateMaterialID();
    }

    _globalOrder = globalOrder;
    _quadsCount = quadCount;
    _quads = quad;
    _mv = mv;
}
```

**Comment by minggo** [comment]
Yep, you are right.
Thanks.

**Comment by minggo** [comment]
@thoechsmann 
Done in #6230.

@ricardoquesada 
Am i missing something?
Why add _lastXXX variables?

**Comment by ricardoquesada** [comment]
no need for the `_last` ivars. @thoechsmann 's patch looks good.

**Pull request merged**
