### PR TITLE
3D Physics: remove addChildToPhysics

### PR DESCRIPTION
**Pull request by super626**
Because component::onEnter component::onExit works now.

### CODE REVIEW

**Comment by super626** [comment]
[ci rebuild]

**Comment by dabingnn** [comment]
Please merge it.
This pull request removed the old function for adding Physics3DComponent to PhysicWorld3D. Now it is added in Component::OnEnter and OnExit, which will be called automatically.

**Comment by zilongshanren** [comment]
Is it ready to merge now?
@dabingnn

**Comment by dabingnn** [comment]
Yes, please.

**Pull request merged**
