### PR TITLE
add another .mk file for android release build

### PR DESCRIPTION
**Pull request by ntotani**
To turn off 'COCOS2D_DEBUG' flug, add another .mk file for android release build.

see also
https://github.com/cocos2d/cocos2d-console/pull/110

### CODE REVIEW

**Comment by minggo** [comment]
Is it other method do remove `COCOS2D_DEBUG` other than adding new Android.mk?

**Comment by ntotani** [comment]
`ndk-build` can't switch C++ flags in single Application.mk file (not Android.mk).
I don't know other way...

**Comment by newnon** [comment]
There is a better way to do this
here is my `Application.mk` file

```
APP_STL := gnustl_static
APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char

APP_DEBUG := $(strip $(NDK_DEBUG))
ifeq ($(APP_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif
```

it solves all problems
you run `build_native.py -n NDK_DEBUG=0` or `build_native.py -n NDK_DEBUG=1`

**Comment by minggo** [comment]
Thanks @newnon.
This method seems better.

**Comment by ntotani** [comment]
Thaks @newnon .
I fix it.

**Comment by newnon** [comment]
i have made new pull request with this & native debug support on eclipse
https://github.com/cocos2d/cocos2d-x/pull/6820

**Comment by minggo** [comment]
@ntotani 
I will close this PR since i have merged #6820.

**Pull request closed without merging**
