### PR TITLE
fix billboard

### LINKED ISSUE #10199: [FantasyWarrior3D] Billboard bug.
The billboard sometimes does not face to current camera.

### PR DESCRIPTION
**Pull request by super626**
fix #10199

### CODE REVIEW

**Comment by zilongshanren** [comment]
@super626 
Linux build is failed at the moment.

**Comment by super626** [comment]
fix #10020

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
I ran the billboard test and verify the fix

**Pull request merged**
