### PR TITLE
remove useless warning log of stencil buffer.

### PR DESCRIPTION
**Pull request by zilongshanren**
1. disable GC for Native object (it is not mature...)  @pandamicro 
2. improve js tests of label

### CODE REVIEW

**Comment by zilongshanren** [comment]
The log message `CCLOG("Stencil buffer is not enabled.");` is useless when using Stencil buffer in the first scene. Which means, when you use ui::Layout, ui::ScrollView, ui::ListView, ui::PageView or ClippingNode in the first scene, you will get the warning.. which is confusing..

Because the following method is only called after the first scene is initialized:

```
- (void) layoutSubviews
{
    [renderer_ resizeFromLayer:(CAEAGLLayer*)self.layer];
    size_ = [renderer_ backingSize];

    // Issue #914 #924
//     Director *director = [Director sharedDirector];
//     [director reshapeProjection:size_];
    cocos2d::Size size;
    size.width = size_.width;
    size.height = size_.height;
    //cocos2d::Director::getInstance()->reshapeProjection(size);

    // Avoid flicker. Issue #350
    //[director performSelectorOnMainThread:@selector(drawScene) withObject:nil waitUntilDone:YES];
    if ([NSThread isMainThread])
    {
        cocos2d::Director::getInstance()->drawScene();
    }
}

```

After the above method call , the color framebuffer and stencil buffer could be setup properly..

**Comment by zilongshanren** [comment]
@minggo  Please review this PR, I think it should be included in v3.11...

**Comment by minggo** [comment]
It is not a critical bug, so i don't think it needs to be included in v3.11.

**Comment by zilongshanren** [comment]
@pandamicro  how about disabling the GC for native object in jsb?  @ricardoquesada

**Comment by ricardoquesada** [comment]
If I recall correctly, the idea was to have the GC disabled in cocos2d-x, and that it will be enabled by default in Creator runtime.

**Comment by zilongshanren** [comment]
@ricardoquesada  yep, but it is enabled by default on v3.11, I think it's risky and it makes a lot of js-tests not working, so I disable it by default in this PR, please check...

**Comment by ricardoquesada** [comment]
looks good to me. not sure why the `boundingWitdh` of the test was also updated on this PR, but it looks safe

**Comment by zilongshanren** [comment]
@ricardoquesada  the `boundingWidth` settings is no longer working, because we added new Overflow feature to the Label...  Maybe there is a back compatibility issue here, but I think the impact is small...

**Pull request merged**
