### PR TITLE
Cocos2d-x 3.0 Windows Phone 8 support

### PR DESCRIPTION
**Pull request by stammen**
This pull requests contains all of the projects and files needed to build cocos2d-x 3.0 for Windows Phone 8.0.

Future pull requests will add support for the following items:
1. Accelerometer
2. Custom shaders (needed for shader tests)
3. Console support
4. modifications to cocos2d-console to fully support cpp template for WP8

### CODE REVIEW

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Does it only support WP8?
How about Windows 8?

**Comment by minggo** [comment]
Why use pthread?
Does WP8 doesn't support std::thread?

**Comment by minggo** [comment]
@dumganhar 
I think it is our build system error.
Because this PR only modified CCLayer.cpp. And it seems not problem of the modification.
So i think we can merge it.

@koowolf
Please test it.
Thanks.

**Comment by stammen** [comment]
@minggo 
WP8 is using std:thread. Where do you see pthread?

**Comment by minggo** [comment]
I found there are CCPThreadWinRT.cpp/.h.

**Comment by stammen** [comment]
That is to support old pthread code from cocos2d-x 2.2.  It is not used in the new 3.0 cocos2d-x code. For example, the texture loading and networking code uses cocos2d-x 3.0 code unmodified. This version of wp8 supports curl and websockets using the same code as the other platforms. All of the networking and curl tests pass.

I can remove the CCPThreadWinRT.cpp/.h files if you want.

For example, look at httpclient.cpp or websocket.cpp and you will see WP8 uses std::thread. Your team did a great job with with the C++ 11 changes.

**Comment by minggo** [comment]
Ok, no problem.
You can keep it if you think it is needed.

**Comment by stammen** [comment]
@minggo 

WinRT support will be added in a separate pull request. It will take me about a week after I finish the remaining WP8 items. WinRT networking support will take some time as it does not have access to WinSock API which is available to WP8.

**Comment by minggo** [comment]
@stammen

Thanks for your awesome work.

**Comment by stammen** [comment]
@minggo 

Thanks! The new cocos2d-x 3.0 codebase made it a lot easier to do the WP8 work. The cocos2d-x team is writing excellent cross-platform code.

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
