### PR TITLE
LabelTTF vertical alignment fixed on OS X

### PR DESCRIPTION
**Pull request by ricardoquesada**
vertical alignment was broken on OS X.
top and bottom were switched.

IMPORTANT:
This patch should be applied in "master" as well (both on "develop" and "master")

### CODE REVIEW

**Comment by minggo** [comment]
@ricardoquesada 

> IMPORTANT:
> This patch should be applied in "master" as well (both on "develop" and "master")

But master has been released. And developer will be merged into master when releasing a new version.

**Comment by ricardoquesada** [comment]
@minggo 
I don't think it will be a problem to merge this patch in master.
Git won't apply it again in develop if it is already present there.

**Comment by minggo** [comment]
What i mean is that i have uploaded zip file to google code for releasing. If i merge this code into master i have to replace the zip file with these code. Should i?

**Comment by minggo** [comment]
merged into master.

**Comment by ricardoquesada** [comment]
@minggo yes, you will need to upload a new version to google code :)

**Pull request merged**
