### PR TITLE
Add JS bindings for Spine

### PR DESCRIPTION
**Pull request by randyv2zhurosoft**
Add CCSkeleton and CCSkeletonAnimation to the list of classes to generate bindings for. This doesn't expose all of spine to JSB, but it at least gives you an entry point where you can add animations to your game.

### CODE REVIEW

**Comment by dumganhar** [comment]
`We can’t automatically merge this pull request.`

**Comment by dumganhar** [comment]
Plz pull the latest codes and resolve the conflict.

**Comment by nakosung** [comment]
Was this PR merged?

**Comment by dumganhar** [comment]
@nakosung 
Not yet. There are conflicts.

**Pull request closed without merging**
