### PR TITLE
Animation3D

### PR DESCRIPTION
**Pull request by super626**
Add transition between Animate3D.

### CODE REVIEW

**Comment by super626** [comment]
[ci rebuild]

**Comment by minggo** [comment]
About `Sequence3D`, please discuss it in [this thread](http://discuss.cocos2d-x.org/t/does-3d-node-need-to-support-actions/16691).

**Comment by super626** [comment]
I have removed Sequence3D according to Riq's suggestion.

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
