### PR TITLE
fix  skybox error with editor files

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by liamcindy** [comment]
@pandamicro  Please review this PR, thanks

**Comment by pandamicro** [comment]
@super626 Please take a look

**Comment by pandamicro** [comment]
@liamcindy Please fix compilation issue

**Comment by super626** [comment]
It is ok.

**Comment by super626** [comment]
@pandamicro

**Comment by pandamicro** [comment]
@liamcindy Can you squash these commits?

**Pull request closed without merging**
