### PR TITLE
Add a setter for line width in DrawNode

### PR DESCRIPTION
**Pull request by neokim**
It was unable to change DrawNode line width which was set to 2. Add a setter for line width.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@neokim  Is the line width always be 2 in all OpenGL & OpenGLES implementation?

**Comment by neokim** [comment]
@andyque I have no idea about that. But in current implementation of DrawNode, the line width is hard-coded as 2 and not adjustable.

**Comment by zilongshanren** [comment]
@neokim  I see. If it  passes the CI, I will merge this PR.
Thanks.

**Comment by zilongshanren** [comment]
@neokim Thanks :+1:

**Pull request merged**
