### PR TITLE
clear exception flag after each jni call

### PR DESCRIPTION
**Pull request by newnon**
otherwise after wrong java call, application falls down

### CODE REVIEW

**Comment by dumganhar** [comment]
What do you mean `wrong call application`? 
Could `invoking non-exist function in Java` reproduce the issue?

**Comment by newnon** [comment]
yes after wrong java call, application fall down. 
include invoking non-exist function in Java

**Comment by dumganhar** [comment]
Thanks, we will check this issue soon. :)

**Comment by WenhaiLin** [comment]
Why clear exception flag?The application should crash when invoking  the function  incorrectly. What do you think?

**Comment by newnon** [comment]
no it bad practice application fall down in other place and its make project undebuggable 
and second strange thing that getMethodInfo clear this flags and getStaticMethodInfo not

**Comment by newnon** [comment]
May be also change 
`LOGD("Failed to find class %s", className);`
to 
`LOGE("Failed to find class %s", className);`

**Comment by dumganhar** [comment]
> no it bad practice application fall down in other place and its make project undebuggable

Do you mean debugging `c++` codes or `java` codes?
Yep, `LOGD` -> `LOGE` will make the log more conspicuous

**Comment by newnon** [comment]
i mean debug all application, because even in debugger you will not see why and where you app crashed

**Comment by cocosQA** [comment]
Dear newnon:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6417
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
