### PR TITLE
fix RotateTo animation when angle is bigger than 360

### PR DESCRIPTION
**Pull request by dzj0821**
```c++
sprite->runAction(RotateTo::create(1, 720));
```
Sprite rotate 720 degrees should be unchanged, but the sprite rotated 360 degrees.

### CODE REVIEW

**Comment by sonyps5201314** [comment]
```lua
	local angle = rotateParam[idx].angle + 360 * 5
	local act = cc.RotateTo:create(10, angle)
	local easeRotate = cc.EaseCircleActionOut:create(act)
		local call = cc.CallFunc:create(function( )
		print("rotate over")
	end)
	local seq = cc.Sequence:create(easeRotate, call)
	self.m_spTable:stopAllActions()
	self.m_spTable:runAction(seq)
```
中文：这是一个错误的提交，这样改了之后就不能用类似上面的代码来做转盘游戏了，本来是需要转很多圈的，这样改了只能转一圈内了，官方麻烦你们不要别人提交什么都想当然的信任别人的代码了，麻烦你们能不能多测试下再合并进去这些可能带来灾难性后果的代码，不要想当然，否则这些合并是不负责任，顾此失彼的。类似的案例还有#20182，如果没有用户使用你们的git版本来开发测试，这些问题将永久存在并被掩盖。
English：Submit this was a mistake, after this change will not be able to use similar to the above code for rotary table games, is originally need to turn a lot of laps, such change can only turn a circle, the official trouble you don't submit anything others for granted the trust of other people's code, can't you be more trouble under test to merge into the code may have disastrous consequences, don't take it for granted, otherwise the merge is irresponsible, attend.In a similar case #20182, if no user USES your git version to develop tests, these problems will persist and be covered up.

**Comment by dzj0821** [comment]
> ```lua
> 	local angle = rotateParam[idx].angle + 360 * 5
> 	local act = cc.RotateTo:create(10, angle)
> 	local easeRotate = cc.EaseCircleActionOut:create(act)
> 		local call = cc.CallFunc:create(function( )
> 		print("rotate over")
> 	end)
> 	local seq = cc.Sequence:create(easeRotate, call)
> 	self.m_spTable:stopAllActions()
> 	self.m_spTable:runAction(seq)
> ```
> 
> 中文：这是一个错误的提交，这样改了之后就不能用类似上面的代码来做转盘游戏了，本来是需要转很多圈的，这样改了只能转一圈内了，官方麻烦你们不要别人提交什么都想当然的信任别人的代码了，麻烦你们能不能多测试下再合并进去这些可能带来灾难性后果的代码，不要想当然，否则这些合并是不负责任，顾此失彼的。类似的案例还有#20182，如果没有用户使用你们的git版本来开发测试，这些问题将永久存在并被掩盖。
> English：Submit this was a mistake, after this change will not be able to use similar to the above code for rotary table games, is originally need to turn a lot of laps, such change can only turn a circle, the official trouble you don't submit anything others for granted the trust of other people's code, can't you be more trouble under test to merge into the code may have disastrous consequences, don't take it for granted, otherwise the merge is irresponsible, attend.In a similar case #20182, if no user USES your git version to develop tests, these problems will persist and be covered up.

中文：从语义上来看，RotateTo代表旋转至某状态，30度的状态和390度的状态本来就是一样的，不旋转我觉得没有问题，既然要固定旋转360度为什么不用RotateBy呢？
English: When the node rotates 30 degrees, it is the same as when it rotates 390 degrees. I don't think there is any problem.  Why don't use RotateBy when you have to rotate 360 degrees?

**Comment by sonyps5201314** [comment]
一句话就是，你这个修改破坏了API兼容性，让成千上万的老cocos游戏代码可能因为升级cocos引擎而面临兼容性问题，cocos本身之前的版本就版本兼容性做得比较差了，一直为用户所诟病而不敢轻易升级，你这样做就是锦上添花了。另外从文档角度研究，https://cocos2d-x.org/reference/native-cpp/V3.0alpha0/d0/d71/classcocos2d_1_1_rotate_to.html ， https://cocos2d-x.org/reference/native-cpp/V3.0rc0/d0/d28/classcocos2d_1_1_rotate_by.html ，RotateTo是旋转到多少度，参数是叫dstAngle 终点角度，强调的是最终，是从0度开始的旋转；而RotateBy 是通过多少度来旋转，参数是叫deltaAngle 变化角度，强调的是变化，是从当前角度开始的再次相对旋转，所以两者用处是不同的，另外看官方文档也没有说明限制必须是360度以内的角度，像你这么说旋转360度就相当于没有旋转了，那361的广告也不用打了，直接改名叫1度算了。另外你这个修改可能解决了你遇到的问题，你其实可以修改你自己的游戏代码来解决的，但是你选择修改了引擎代码，你修改了引擎代码你自己用还好，但是一提交就可能会让大家的代码面临问题，所以还是请谨慎提交，官方也请谨慎对待第三方提交的代码，防止引入新的BUG，或者代码污染，力求稳定性第一，任何没有大面积测试的代码合并，都是不可靠的。国外的大部分开源项目，对第三方提交的代码就很谨慎，甚至不理睬，没有充分论证及实验可靠性不会去合并，说实话cocos是我见到对合并代码管理最松懈的，所以经常因为升级版本而引入新的BUG，这样子用户就会更加怕升级新版本了，适得其反，所以还是请官方谨慎考虑吧。git版本不能用于生产环境，不是理由，你看谷歌的代码项目，如[angle](https://chromium.googlesource.com/angle/angle)基本上都是直接使用的最新git版本作为发布的，版本名字都是git 提交hash值。
我自己的软件也是全是使用各个开源软件的git版本作为开发，都没因为是因为使用的git版本而出现问题，但是cocos就是个例外，我也不是第一次向你们反馈问题了。之前3.17.1发布之前也反应及吐槽过几次，后面一段时间因为怕了，心有余悸了，所以一直不敢升级，后面看到3.17.2发布了所以还是想找个时间升级下结果一升级就发现[#20182](https://github.com/cocos2d/cocos2d-x/issues/20182)反馈的同样问题，于是找到作者，请他上来修正了。请官方考虑下我的建议吧，代码质量及稳定性真的很重要，要是在商业公司上班因为这些出问题，可能就会挨骂了，压力真的好大。谢谢。
Translated by google:
In a word, your modification has broken the API compatibility, and thousands of old cocos game code may face compatibility problems due to the upgrade of the cocos engine. The previous versions of cocos itself have done a relatively poor version compatibility. If you are criticized by users and don't dare to upgrade easily, you will be icing on the cake. Also from a documentation perspective, https://cocos2d-x.org/reference/native-cpp/V3.0alpha0/d0/d71/classcocos2d_1_1_rotate_to.html , https://cocos2d-x.org/reference/native-cpp/ V3.0rc0/d0/d28/classcocos2d_1_1_rotate_by.html, RotateTo is the degree of rotation, the parameter is called dstAngle end angle, the emphasis is the final rotation from 0 degrees; and RotateBy is rotated by how many degrees, the parameter is Called deltaAngle change angle, emphasizes the change, is the relative rotation from the current angle, so the use of the two is different, and the official document does not indicate that the limit must be within 360 degrees, as you say 360 The degree is equivalent to no rotation, and the 361 advertisement does not need to be played, and the name is directly changed to 1 degree. In addition, your modification may solve the problem you encountered, you can actually modify your own game code to solve, but you choose to modify the engine code, you modify the engine code you use, but a commit may Will make everyone's code face problems, so please be cautious to submit, the official also please be cautious about the third-party submitted code to prevent the introduction of new bugs, or code pollution, and strive for stability first, any code that does not have large-area test merge, They are all unreliable. Most foreign open source projects are cautious about the code submitted by third parties, and even ignore it. Without sufficient argumentation and experimental reliability, they will not be merged. To be honest, cocos is the most lax I have seen in the management of merged code, so often Because the upgrade version introduces a new bug, so sub-users will be more afraid to upgrade the new version, which is counterproductive, so please ask the official to consider it. The git version can't be used in a production environment, it's not a reason. You see Google's code project, such as angle, which is basically the latest git version that is used directly, and the version name is git to submit the hash value.
My own software is also using the git version of each open source software as a development, not because of the problem with the git version, but cocos is an exception, I am not the first time to give you feedback. Before the release of 3.17.1, I also reacted and spit a few times before. I was afraid of it for a while, but I was afraid to upgrade. I saw that 3.17.2 was released later, so I still want to find a time to upgrade the results. I found the same problem with #20182 feedback, so I found the author and asked him to fix it. Please consider my suggestion, the quality and stability of the code is really important. If you go to work in a commercial company because of these problems, you may be embarrassed, and the pressure is really great. Thank you.

**Comment by dzj0821** [comment]
> 一句话就是，你这个修改破坏了API兼容性，让成千上万的老cocos游戏代码可能因为升级cocos引擎而面临兼容性问题，cocos本身之前的版本就版本兼容性做得比较差了，一直为用户所诟病而不敢轻易升级，你这样做就是锦上添花了。另外从文档角度研究，https://cocos2d-x.org/reference/native-cpp/V3.0alpha0/d0/d71/classcocos2d_1_1_rotate_to.html ， https://cocos2d-x.org/reference/native-cpp/V3.0rc0/d0/d28/classcocos2d_1_1_rotate_by.html ，RotateTo是旋转到多少度，参数是叫dstAngle 终点角度，强调的是最终，是从0度开始的旋转；而RotateBy 是通过多少度来旋转，参数是叫deltaAngle 变化角度，强调的是变化，是从当前角度开始的再次相对旋转，所以两者用处是不同的，另外看官方文档也没有说明限制必须是360度以内的角度，像你这么说旋转360度就相当于没有旋转了，那361的广告也不用打了，直接改名叫1度算了。另外你这个修改可能解决了你遇到的问题，你其实可以修改你自己的游戏代码来解决的，但是你选择修改了引擎代码，你修改了引擎代码你自己用还好，但是一提交就可能会让大家的代码面临问题，所以还是请谨慎提交，官方也请谨慎对待第三方提交的代码，防止引入新的BUG，或者代码污染，力求稳定性第一，任何没有大面积测试的代码合并，都是不可靠的。国外的大部分开源项目，对第三方提交的代码就很谨慎，甚至不理睬，没有充分论证及实验可靠性不会去合并，说实话cocos是我见到对合并代码管理最松懈的，所以经常因为升级版本而引入新的BUG，这样子用户就会更加怕升级新版本了，适得其反，所以还是请官方谨慎考虑吧。git版本不能用于生产环境，不是理由，你看谷歌的代码项目，如[angle](https://chromium.googlesource.com/angle/angle)基本上都是直接使用的最新git版本作为发布的，版本名字都是git 提交hash值。
> 我自己的软件也是全是使用各个开源软件的git版本作为开发，都没因为是因为使用的git版本而出现问题，但是cocos就是个例外，我也不是第一次向你们反馈问题了。之前3.17.1发布之前也反应及吐槽过几次，后面一段时间因为怕了，心有余悸了，所以一直不敢升级，后面看到3.17.2发布了所以还是想找个时间升级下结果一升级就发现[#20182](https://github.com/cocos2d/cocos2d-x/issues/20182)反馈的同样问题，于是找到作者，请他上来修正了。请官方考虑下我的建议吧，代码质量及稳定性真的很重要，要是在商业公司上班因为这些出问题，可能就会挨骂了，压力真的好大。谢谢。
> Translated by google:
> In a word, your modification has broken the API compatibility, and thousands of old cocos game code may face compatibility problems due to the upgrade of the cocos engine. The previous versions of cocos itself have done a relatively poor version compatibility. If you are criticized by users and don't dare to upgrade easily, you will be icing on the cake. Also from a documentation perspective, https://cocos2d-x.org/reference/native-cpp/V3.0alpha0/d0/d71/classcocos2d_1_1_rotate_to.html , https://cocos2d-x.org/reference/native-cpp/ V3.0rc0/d0/d28/classcocos2d_1_1_rotate_by.html, RotateTo is the degree of rotation, the parameter is called dstAngle end angle, the emphasis is the final rotation from 0 degrees; and RotateBy is rotated by how many degrees, the parameter is Called deltaAngle change angle, emphasizes the change, is the relative rotation from the current angle, so the use of the two is different, and the official document does not indicate that the limit must be within 360 degrees, as you say 360 The degree is equivalent to no rotation, and the 361 advertisement does not need to be played, and the name is directly changed to 1 degree. In addition, your modification may solve the problem you encountered, you can actually modify your own game code to solve, but you choose to modify the engine code, you modify the engine code you use, but a commit may Will make everyone's code face problems, so please be cautious to submit, the official also please be cautious about the third-party submitted code to prevent the introduction of new bugs, or code pollution, and strive for stability first, any code that does not have large-area test merge, They are all unreliable. Most foreign open source projects are cautious about the code submitted by third parties, and even ignore it. Without sufficient argumentation and experimental reliability, they will not be merged. To be honest, cocos is the most lax I have seen in the management of merged code, so often Because the upgrade version introduces a new bug, so sub-users will be more afraid to upgrade the new version, which is counterproductive, so please ask the official to consider it. The git version can't be used in a production environment, it's not a reason. You see Google's code project, such as angle, which is basically the latest git version that is used directly, and the version name is git to submit the hash value.
> My own software is also using the git version of each open source software as a development, not because of the problem with the git version, but cocos is an exception, I am not the first time to give you feedback. Before the release of 3.17.1, I also reacted and spit a few times before. I was afraid of it for a while, but I was afraid to upgrade. I saw that 3.17.2 was released later, so I still want to find a time to upgrade the results. I found the same problem with #20182 feedback, so I found the author and asked him to fix it. Please consider my suggestion, the quality and stability of the code is really important. If you go to work in a commercial company because of these problems, you may be embarrassed, and the pressure is really great. Thank you.

中文：好的，感谢指点。我的确只从设计的角度在考虑而没有考虑兼容性等问题，之后会更谨慎的考虑。 这个改动请官方来评判吧 @minggo 
English: Thanks for pointing. I only consider it from the design level, but I have not considered the compatibility level. I will consider the issue more carefully in the future. Please judge this commit, thanks.

**Comment by minggo** [comment]
@sonyps5201314 sorry about that, i think you are right, we should consider more about compatibility. But it is hard to test all situations. 

About this PR, i think we should revert it.

**Comment by sonyps5201314** [comment]
Thanks!

**Pull request merged**
