### PR TITLE
works on win32

### PR DESCRIPTION
**Pull request by ricardoquesada**
std::iterators weren't used correctly

### CODE REVIEW

**Comment by totallyeviljake** [comment]
This fixed the problem that I ran into, and it builds on my windows 8 box just fine.

**Comment by CraigJamesMitchell** [comment]
Still doesn't compile or link using VS2013 I'm afraid.

**Comment by totallyeviljake** [comment]
Make sure you run the python script at the root to download the dependencies. Once you do that then it should build for you. also, Ricardo, myself, and our team, are all using VS2013 Professional.

**Comment by CraigJamesMitchell** [comment]
I always run the download-deps script when I do a pull...
cocos2d-win32.vc2012.sln is seriously messed up.
For instance it refs the project libBox2d in external, which doesn't exist anymore.
There are lots of other problems involving include and library paths I think...
I am try to build the win32 debug config in VS2013 express.
Try pulling the whole repo to a clean folder to test...
Apolgies if I'm doing something wrong...

**Comment by totallyeviljake** [comment]
Hey Craig, can we start fresh? When I had this problem, I ran the following steps:

$ git clone git@github.com:cocos2d/cocos2d-x.git
$ cd cocos2d-x
$ python download-deps.py
$ git submodule update --init

Use python27. It doesn't work with python30

Once you do this, you should have a Box2D in your "external" directory.

**Comment by CraigJamesMitchell** [comment]
Thanks. I missed the git submodule update step...
Now I get 
Error   135 error C1083: Cannot open include file: 'atlbase.h': No such file or directory   C:\Users\craig_000\Documents\cocos2d-x\cocos\ui\UIWebViewImpl-win32.cpp 30  1   libcocos2d
Error   176 error LNK1104: cannot open file 'C:\Users\craig_000\Documents\cocos2d-x\build\Debug.win32\libcocos2d.lib'   C:\Users\craig_000\Documents\cocos2d-x\tests\cpp-empty-test\proj.win32\LINK cpp-empty-test
Error   267 error LNK1104: cannot open file 'C:\Users\craig_000\Documents\cocos2d-x\build\Debug.win32\libcocos2d.lib'   C:\Users\craig_000\Documents\cocos2d-x\tests\lua-tests\project\proj.win32\LINK  lua-tests
Error   274 error LNK1104: cannot open file 'C:\Users\craig_000\Documents\cocos2d-x\build\Debug.win32\libcocos2d.lib'   C:\Users\craig_000\Documents\cocos2d-x\tests\lua-empty-test\project\proj.win32\LINK lua-empty-test
Error   275 error LNK1104: cannot open file 'C:\Users\craig_000\Documents\cocos2d-x\build\Debug.win32\libcocos2d.lib'   C:\Users\craig_000\Documents\cocos2d-x\tests\cpp-tests\proj.win32\LINK  cpp-tests

**Comment by totallyeviljake** [comment]
You need to get the ATL. This is the template library from Microsoft. I dunno if that comes with VS express....

**Comment by zhaijialong** [comment]
I think this is because VS epress version does not have ATL.
2014年10月4日 上午2:05于 "CraigJamesMitchell" notifications@github.com写道：

**Comment by CraigJamesMitchell** [comment]
Thanks guys. I can confirm ATL is missing in VS2013 Express. 
I've done a quick Google, but can not seem to find the correct ATL download for VS2013 Express.
Can you help please?
Many thanks again. These dependence needs to be documented somewhere perhaps?

**Comment by zhaijialong** [comment]
copying atlmfc folder from ultimate/pro version will work, but that is not
valid due to copyright.

**Comment by CraigJamesMitchell** [comment]
Can I use this?
http://sourceforge.net/projects/wtl/
If win32 cocos2d-x suddenly has an IDE requirement (ATL files in pro/ultimate) that costs many dollars then that is a disaster!!!!!!!

**Comment by totallyeviljake** [comment]
Does this help:

http://stackoverflow.com/questions/71659/how-to-add-wtl-and-atl-to-visual-studio-c-express-2008

**Comment by zhaijialong** [comment]
Maybe MS has a seperate free sdk which include atl, sorry I'm not sure.
2014年10月4日 上午2:48于 "CraigJamesMitchell" notifications@github.com写道：

**Comment by CraigJamesMitchell** [comment]
@totallyeviljake 
Thanks, but this answer seems to preclude using WTL
http://stackoverflow.com/a/23664649

We seem to be at a bit of an impasse. Not sure @ricardoquesada will be happy about the win32 webview code breaking free development of cocos2d-x games (As I understand the situation currently...)

**Comment by zhaijialong** [comment]
After a quick search , I found the free and valid way to use ATL in VS express is to install Windows Driver Kit(WDK). It includes ATL :)
http://msdn.microsoft.com/en-us/windows/hardware/hh852365

**Comment by CraigJamesMitchell** [comment]
Thanks. Am downloading now to give it a try! :)
...1.4 GB download. I may be some time... :(

**Comment by CraigJamesMitchell** [comment]
The WDK driver kit 8.1 doesn't contain the ATL headers e.g. atlbase.h
So, we are back to a broken cocos2d-x win32 for VS2013 Express.

**Comment by zhaijialong** [comment]
Really? I found that in http://www.cplusplus.com/forum/windows/102538/.

**Comment by CraigJamesMitchell** [comment]
That post was from May 2013. Things must have changed since then.
I downloaded the WDK 8.1 update 1 version as I have 8.1 update 1 and you need that version of Windows to do WP8.1 dev.
I did a whole drive search for atlbase.h after the install...
:(

**Comment by zhaijialong** [comment]
Oh no, this does be a problem. Anyhow we should reconsider the win32 webview implementation based on ATL. Is there any other way to embed a IE webview in win32 via COM? @minggo

**Comment by CraigJamesMitchell** [comment]
Am sorry to be the finder of bad news :(
Maybe some VS Express guards around the win32 webview code in the interim.
Sorry I can't be more helpful than that...

**Pull request merged**
