### PR TITLE
add issue9898

### PR DESCRIPTION
**Pull request by fusijie**
refer to : [https://github.com/cocos2d/cocos2d-x/issues/9898](https://github.com/cocos2d/cocos2d-x/issues/9898)

### CODE REVIEW

**Comment by minggo** [comment]
Thanks.
But i think it is better not use is id as class name.
Please use a class name that can describe the issue.

**Comment by fusijie** [comment]
@minggo 
ok, I will correct it and resend the pr.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Duplicated with #9963.

**Pull request closed without merging**
