### PR TITLE
Scale9Sprite / Slider / LoadingBar fixes

### PR DESCRIPTION
**Pull request by ricardoquesada**
Fixes issues #16930 #16928 

There were different bugs:

* cloning was not supported in the new API. Actually, the previous API was cloning inside the `init` method which was extremely confusing. Added `copyTo` in `Scale9Sprite`
* fix negative streching
* fix bug when calculating centerRect after the texRect was modified

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@dumganhar this PR should fix the slider/loadingbar issues. thanks.

**Comment by dumganhar** [comment]
@ricardoquesada, thanks. I will test it.

**Comment by dumganhar** [comment]
uiloadingbarreloadtexturebug

@ricardoquesada , I found this test still can't work correctly.

UPDATED:

Reproduce steps:

* Go to `6, UILoadingBarReloadTexture`
* Click `ToggleScale9` once
* Click `ChangeTexture` once
* Click `ToggleScale9` once again

Current result:

The purple progress bar will move as the gif picture I uploaded.

Correct result:

The left picture in the gif.

**Comment by dumganhar** [comment]
Another issue is:
different-height

**Comment by ricardoquesada** [comment]
@dumganhar thanks.

I'll try to fix the height... but it is mostly black magic. The thing is that it is using invalid capInsets... like super invalid capInsets, so the texture displayed in v3.13 is incorrect. In v3.14 is the correct one. 

The capInsets used for left,right,top,bottom are: 66.6, 66.6, 66.6, 66.6. And the texture size is 50x57.  I really don't know what should be the expected behavior when using invalid capInsets.

As an example, the rendered quad has the same dimensions both in v3.13 and v3.14 but the texture coordinates are different. in v3.13 they are going beyond the texture limits.

screen shot 2016-12-02 at 8 21 20 am

**Comment by ricardoquesada** [comment]
@dumganhar regarding the other bug, fixed!
thanks.

**Comment by dumganhar** [comment]
@ricardoquesada 

> so the texture displayed in v3.13 is incorrect. In v3.14 is the correct one.

Yes, I also checked it, and found that it's incorrect in v3.13. I think developer will not pass in an incorrect capInset all the time. Therefore, it's probably safe to correct the mistake.

> regarding the other bug, fixed!

Thank you, I have confirmed that they were fixed in this Pull Request.

So, feel free to merge this Pull Request. :)

**Comment by ricardoquesada** [comment]
Thanks for the great testing!

**Pull request merged**
