### PR TITLE
Fix gamenode3d parse failed error - by Liam

### PR DESCRIPTION
**Pull request by xiaofeng11**

### CODE REVIEW

**Comment by liamcindy** [comment]
@pandamicro Please review this PR, thanks

**Comment by pandamicro** [comment]
@dabingnn Can you take a look?

**Comment by pandamicro** [comment]
@liamcindy Please squash your commits, here is a tutorial about how to squash: https://docs.google.com/document/d/1PQHXTEQ3GoI0XH1YQNf1P-d79BAkRanzeIocdrHlGiI/edit

Then can you explain exactly what's the issue and how your PR fix the issue ?

**Comment by dabingnn** [comment]
@liamcindy I found that there are only some project file changes. Could you describe the purpose of this pull request?

**Comment by liamcindy** [comment]
@dabingnn 提交之前的遗漏了多平台的文件配置

**Comment by pandamicro** [comment]
How can we verify that it's correct ?

**Comment by xiaofeng11** [comment]
If the problem exist, run last test of "cocostudio 3d test" in cpp-test project under MacOSX will cause program crash.

**Pull request closed without merging**
