### PR TITLE
Let Widget class don't support cascaded opacity and cascaded color on default.

### PR DESCRIPTION
**Pull request by zilongshanren**
Make Widget class disable cascaded color and opacity on default.

### CODE REVIEW

**Comment by darkdukey** [comment]
Can you give a use case for it?

**Comment by liamcindy** [comment]
some one want to set different color for an widget and its parent;

**Comment by darkdukey** [comment]
Just to see if I understand correctly, correct me if I'm wrong
1. If I add a `slider` as a child of a `button`, if I change the color of `button`, slider's color won't change
2. If I change the color of a `slider`, the color of the `slider ball` will change.

**Comment by zilongshanren** [comment]
@darkdukey 
This PR will guarantee the above two points.

**Comment by darkdukey** [comment]
@andyque Sounds good thanks~

**Pull request merged**
