### PR TITLE
Platforms: enabled c++11 flag on Linux, NaCL, Android, Emscripten.

### PR DESCRIPTION
**Pull request by sergey-shambir**

### CODE REVIEW

**Comment by gelldur** [comment]
Finally :)

**Comment by aberaud** [comment]
Why not using the standard flag " -std=c++11 " ?

This would force compilation with a compiler that actually support the final version of the standard.

**Comment by sergey-shambir** [comment]
GCC 4.6 is primary platform for cocos2d v.3, because it's default compiler for Android, Blackberry, some Linux distributions. It supports all important features of c++11, but have no flag "-std=c++11" (which was turned on in version 4.7).

**Comment by ricardoquesada** [comment]
yeah!

**Comment by minggo** [comment]
@sergey-shambir 
Is there any difference between `-std=gnu++0x` and `-std=c++11`?
And could you please add comments in makefiles that describe why not use `-std=c++11`?

**Comment by minggo** [comment]
I have sent a pull request #2709 to enable c++11. I used `-std=c++11`, it works ok on Android and linux(ubuntu 12.0).

I also enabled c++11 for all samples.

**Comment by sergey-shambir** [comment]
Thanks, I'll close this request now.

**Comment by minggo** [comment]
Yeap, `-std=c++11` failed on travis, so i use `-std=gnu++0x` instead.
Thank you @sergey-shambir.

**Pull request closed without merging**
