### PR TITLE
JSB SocketIO.connect supports to pass a CA cert file

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Review by minggo — APPROVED** [review]

**Comment by pandamicro** [comment]
I don't quite understand the official API documentation, it declares there is no parameter for socket.connect which is not as our current API.

https://socket.io/docs/client-api/#socket-connect

**Comment by dumganhar** [comment]
Just add a optional parameter (caFilePath) for SocketIO.connect method，it will not conflict with the  the API of socket io official.

**Comment by minggo** [comment]
Hi guys, please use english. We ask developers using english, we should obey it ourselves.

**Comment by pandamicro** [comment]
I'm ok now if the original C++ SocketIO::connect support such API form, it's just the difference between our implementation and SocketIO official documentation makes me confused, I think it should be fixed when we upgrade our C++ SocketIO implementation to the latest version

**Review by pandamicro — APPROVED** [review]

**Pull request merged**
