### PR TITLE
Hide cursor

### PR DESCRIPTION
**Pull request by darkdukey**
Credit to @Sheado for the initial pull request #10502 
Implement Hide/Show cursor with test case feature #8766

### CODE REVIEW

**Comment by zilongshanren** [comment]
ni/../../Classes/InputTest/MouseTest.cpp: In member function 'void MouseEventTest::onMouseDown(cocos2d::Event_)':
jni/../../Classes/InputTest/MouseTest.cpp:142:12: error: 'to_string' is not a member of 'std'
     str += std::to_string(e->getMouseButton());
            ^
jni/../../Classes/InputTest/MouseTest.cpp: In member function 'void MouseEventTest::onMouseUp(cocos2d::Event_)':
jni/../../Classes/InputTest/MouseTest.cpp:150:12: error: 'to_string' is not a member of 'std'
     str += std::to_string(e->getMouseButton());
            ^
jni/../../Classes/InputTest/MouseTest.cpp: In member function 'void MouseEventTest::onMouseMove(cocos2d::Event_)':
jni/../../Classes/InputTest/MouseTest.cpp:158:17: error: 'to_string' is not a member of 'std'
     str = str + std::to_string(e->getCursorX()) + " Y:" + std::to_string(e->getCursorY());
                 ^
jni/../../Classes/InputTest/MouseTest.cpp:158:59: error: 'to_string' is not a member of 'std'
     str = str + std::to_string(e->getCursorX()) + " Y:" + std::to_string(e->getCursorY());
                                                           ^
jni/../../Classes/InputTest/MouseTest.cpp: In member function 'void MouseEventTest::onMouseScroll(cocos2d::Event_)':
jni/../../Classes/InputTest/MouseTest.cpp:166:17: error: 'to_string' is not a member of 'std'
     str = str + std::to_string(e->getScrollX()) + " Y: " + std::to_string(e->getScrollY());
                 ^
jni/../../Classes/InputTest/MouseTest.cpp:166:60: error: 'to_string' is not a member of 'std'
     str = str + std::to_string(e->getScrollX()) + " Y: " + std::to_string(e->getScrollY());

**Comment by darkdukey** [comment]
Which platform is it? std::to_string() should be part of c++11 and we're using c++ 11

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by Sheado** [comment]
Thanks guys. I see it failed on Linux, I think it's because of missing ifdefs for that too - haven't had a chance to fully test it on Linux yet. I'll try to get around to that as soon as possible.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
I was able to build successfully on local with ubuntu 14.10

**Comment by Sheado** [comment]
Ah, cool. I created a cleaner pull request for you all just in case you were going to reject this one. 
https://github.com/cocos2d/cocos2d-x/pull/10833

**Comment by Sheado** [comment]
Thanks for the merge @darkdukey

**Comment by darkdukey** [comment]
@Sheado Thank you for contributing! Sorry for the delay, I had a hard time setup ubuntu dual boot with my mac,  now I will start help you with the controller. I know there are a lot of PR for it, which one do you think we can start to working on?

**Comment by Sheado** [comment]
@darkdukey Glad to help. Cocos2d-x is awesome =]

As for the controller support, my latest pull request is this one: https://github.com/cocos2d/cocos2d-x/pull/10760 
I rushed and messed up a bit in creating the pull request, accidentally checking in too many other changes. If I have time, I'll create a cleaner one, but if you don't want to wait then I recommend going with that pull request since it includes xbox and ps3 controller support. 

Also, this fork has my latest changes: https://github.com/Sheado/cocos2d-x/tree/v3-sheado-merge

**Pull request merged**
