### PR TITLE
Added new audio engine with wav support

### PR DESCRIPTION
**Pull request by anniruddh**

### CODE REVIEW

**Comment by stammen** [comment]
The Linux build seems to have failed for an unrelated reason. This code is from MSOpenTech and is good to pull once the Linux build passes.

**Comment by minggo** [comment]
Sorry.
There is a conflict.
Could you please fix it?
Thanks.

**Comment by minggo** [comment]
Why use so many wav files to test?

**Comment by anniruddh** [comment]
Currently this code supports only wav files hence added those files so that the tests can work. Support for MP3 and Ogg is in progress. Once that is in place these wav files can be dropped.

**Comment by anniruddh** [comment]
Closing this PR for now. Will make a new PR with all the issues resolved.

**Pull request closed without merging**
