### PR TITLE
JavaScript debugger, improved and bugfixed.

### PR DESCRIPTION
**Pull request by folecr**

### CODE REVIEW

**Comment by folecr** [comment]
@dumganhar

**Comment by dumganhar** [comment]
Hi, Surith,
After this changes, is it the same way to use debugger as mentioned here(https://github.com/cocos2d/bindings-generator/blob/master/targets/spidermonkey/common/README.md).

**Comment by folecr** [comment]
Similar but slightly simpler. I will update the readme tomorrow.

**Comment by dumganhar** [comment]
OK, thanks.

**Comment by folecr** [comment]
Updated documentation and sample script https://github.com/cocos2d/bindings-generator/pull/6
In cocos2d-x the TestJavaScript project is setup correctly for debugging.

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
