### PR TITLE
Add Cocostudio Armature getOffsetPoints API for Lua

### PR DESCRIPTION
**Pull request by yestein**

### CODE REVIEW

**Comment by yestein** [comment]
Why failed?

**Comment by yestein** [comment]
[ci rebuild]

**Comment by yestein** [comment]
This API is useful to me, so I think it is the same to others.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Could you please fix indent.
Replace tab with 4 spaces.

**Comment by yestein** [comment]
OK, I have replaced tab to 4 spaces, thx.

**Comment by yestein** [comment]
When does this request can merge please? :-)

**Comment by minggo** [comment]
I have to ask cocos studio guys to take a look

**Comment by yestein** [comment]
oh, thank u :-)

**Comment by chengstory** [comment]
@minggo it may be merged. Thanks @yestein

**Comment by samuele3hu** [comment]
This function would be bound to lua automaticlly,so we could move manual bindings.

**Pull request merged**
