### PR TITLE
Gles20

### PR DESCRIPTION
**Pull request by mrmop**
Marmalade for Mac OS fixes

### CODE REVIEW

**Comment by dumganhar** [comment]
I haven't seen any commits about Mac OS fixes.
Also, you didn't pull the latest codes, so this Pull Request isn't clean. It contains lots of changed files that have been merged.

Maybe you should do it in another branch.
<code>
$ git remote add cocos2d-x https://github.com/cocos2d/cocos2d-x.git
$ git fetch cocos2d-x
$ git checkout -b another_branch remotes/cocos2d-x/gles20
</code>

In this way, you will get a clean branch that synchronizing the _cocos2d-x/gles20_ branch.

**Comment by mrmop** [comment]
Ah, I forgot to sync the Mac OS changes.
My experience with Github is not great. I usually download the latest repo from https://github.com/cocos2d/cocos2d-x (GLES2 branch) as a zip then merge into my local Githuib repo. 
I notice that many deprecated methods have been removed in the latest. I will merge these changes into my local branch then commit again.

**Comment by dumganhar** [comment]
I think you just need half hour to study how to use git. So why not? :)

**Comment by dumganhar** [comment]
Thanks, this issue has been fixed at https://github.com/cocos2d/cocos2d-x/pull/1741. So i closed it manually.

**Pull request closed without merging**
