### PR TITLE
use inch for childFocusCancelOffset in UIScrollView

### PR DESCRIPTION
**Pull request by TimothyZhang**
just like what CCScrollView did.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
Thanks, @TimothyZhang 
I think we should merge the PR after release v3.3 final. Now the `Device::getDPI()` returns a wrong value in iPhone6 Plus.  We should fix it at first.

Thoughts?

**Comment by TimothyZhang** [comment]
Has `Device::getDPI()` been fixed?

**Comment by zilongshanren** [comment]
@TimothyZhang  Not yet, we will deal with this issue in v3.8.

**Comment by zilongshanren** [comment]
@TimothyZhang  new PR is here : https://github.com/cocos2d/cocos2d-x/pull/12537
So I will close your PR here. 
Thanks.

**Pull request closed without merging**
