### PR TITLE
enable android_gen_libs

### PR DESCRIPTION
**Pull request by crazyhappygame**

### CODE REVIEW

**Comment by drelaptop** [comment]
@crazyhappygame cocos-console submodule have been updated

You could use empty commit to trigger CI
```
git commit --allow-empty -m "Trigger CI"
```

**Comment by crazyhappygame** [comment]
@drelaptop Please check below error in CI.
```
The directory 'android-22' can't be found in ANDROID_SDK_ROOT/platforms, please use --ap to set needed API level
Error running command, return code: 12.
```
This check should be removed. Starting from gradle 4.0. All needed dependencies (like android platforms) are downloaded automatically.

By the way could you also update grade (4.4), grade plugin(3.1.0), build tools (27.0.3) to latest version??
https://developer.android.com/studio/releases/gradle-plugin

**Comment by drelaptop** [comment]
@crazyhappygame the gradle-plugin is 3.0.0 version now. I don't think this is necessary to update the version to 3.1.0. it's a little version update for Gradle. 

I think `--ap` parameter might need to be update, it should means min_sdk_version, not compile_sdk_version, for we always use the latest SDK to compile Android.

**Comment by minggo** [comment]
will it slow down trivas building speed?

**Comment by drelaptop** [comment]
All the travis-ci build tasks start at the same time, they are parallel. Another side, appveyor tasks start one by one, they are serial. When a PR comes, the travis-ci always be finished before appveyor. So I think add travis-ci tasks won't slow down the total speed.

**Comment by crazyhappygame** [comment]
This PR is not ready for merge. I will let you know when you can merge it.

**Comment by drelaptop** [comment]
@crazyhappygame all right, thanks

**Comment by crazyhappygame** [comment]
@drelaptop I do not know how to use prebuilt for android ... Could you help me? 
Which files should be update and what command should be run to use android gen-libs for release mode?
"cocos.py gen-libs -p android -m release" - works but I do not know how to use output of  gen-libs for android project  ...

```
$ python -u tools/cocos2d-console/bin/cocos.py gen-libs -p android -m release --ap android-27 --app-abi armeabi-v7a:x86 --agreement n.
$ python -u tools/cocos2d-console/bin/cocos.py --agreement n new -l cpp -p my.pack.qqqq1 cocos_new_test1
$ python -u tools/cocos2d-console/bin/cocos.py --agreement n new -l cpp -p my.pack.qqqq2 cocos_new_test2
$ cd cocos_new_test1/proj.android
$ # update Android.mk and other files?
```

**Comment by drelaptop** [comment]
@crazyhappygame I am afraid that you have to write `Android.mk ` manually, to include header directory and link generated library. I know it's unfriendly  and hard to use, but I don't know any other method.

AFAIK, cocos2d-x supplied 2 kinds of template projects times ago. just like 

__sources-cpp-template__, build a app by compiling all sources
__links-cpp-template__, build a app by compiling part sources, and link generated libs.

but for some reasons, links-cpp-template is removed, and only sources-cpp-template existed. @minggo is this right?

**Comment by crazyhappygame** [comment]
@drelaptop I tried "to write Android.mk manually, to include header directory and link generated library" but failed ....
Could you help me write Android.mk for this PR?

**Comment by drelaptop** [comment]
@crazyhappygame yep, I will have a try to write Android.mk manually in next days.

**Comment by crazyhappygame** [comment]
@drelaptop did you try to write Android.mk for prebuilds?

**Comment by drelaptop** [comment]
@crazyhappygame sorry, last week I was busy, but I will try to do it this week.

**Comment by drelaptop** [comment]
As I known Cocos Creator support binary template, so I look into the CocosCreator.app contents.. 

many `prebuilt-mk/Android.mk` files existed at `Contents/Resources/cocos2d-x/cocos`, so as to support prebuilt on android. and `cocos/Android.mk` is so similar with `cocos/prebuilt-mk/Android.mk`, except with `LOCAL_C_INCLUDES` removed, and `LOCAL_SRC_FILES` modified. 

 writing `Android.mk` manually for prebuilt will spend many duplicate works, it should been done by cocos console, but now it seems like this feature was not existed at cocos console @crazyhappygame

**Comment by crazyhappygame** [comment]
@drelaptop I do not know Android.mk but can not we just add all static libs create by gen-libs to Android.mk ?

**Comment by drelaptop** [comment]
sure, we can. it's possible to add all static libs link into single Android.mk file. @crazyhappygame

**Comment by drelaptop** [comment]
@crazyhappygame 

those are the both Android.mk files.
[UseAndroidGenLibs.zip](https://github.com/cocos2d/cocos2d-x/files/2065196/UseAndroidGenLibs.zip)

It works when I tested it by a new cpp project.
discuss at, https://discuss.cocos2d-x.org/t/cocos2dx-v3-17-prebuilt-mk-is-not-generated/42670/9

**Comment by crazyhappygame** [comment]
With cmake it will be much simpler

**Pull request closed without merging**
