### PR TITLE
V3 Layout scissors clipping mode fix

### PR DESCRIPTION
**Pull request by newnon**
fix bugs in Layout scissors clipping mode

### CODE REVIEW

**Comment by newnon** [comment]
@minggo @dumganhar please look here

**Comment by minggo** [comment]
Is there any test case to reproduce it?

**Comment by newnon** [comment]
Yes see pull request

**Comment by rh101** [comment]
@minggo This fix is better than the one I recently submitted in #20352 and #20407 and actually addresses a few more issues with the clipping.  It should replace the ones I submitted.  I'll submit a new V4 PR with this same code, but it's best if the changes in this PR are used for V3 since it's already here.

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
Yep, i don't know why i missed this PR.
@newnon could you please fix conflict?

**Comment by rh101** [comment]
@minggo Do you want me to submit a new PR based on the code in this PR, since the original author hasn't been actively working on it?  I would really like to see this go into the next v3 release.  The equivalent V4 fixes have already been approved and merged in #20415

**Comment by minggo** [comment]
@rh101 you are appreciated if you can send a new PR.

**Comment by rh101** [comment]
Will do so today

**Pull request closed without merging**
