### PR TITLE
fix delete wild opengl buffers

### LINKED ISSUE #9599: Android: minimizing/restoring app causing assertion errors and OpenGL issues
Minimizing the barebones cocos2d-x app created with _cocos new_ causes the following warning in logcat

`W/ManagedEGLContext(23450): doTerminate failed: EGL count is 3 but managed count is 1`

Additionally when restoring my game, I sometimes get an assertion error and numerous OpenGL errors. This is not reproducible with the barebones app.

```
12-23 21:11:42.831: D/JniHelper(23729): JniHelper::getJavaVM(), pthread_self() = 1610240568
12-23 21:11:43.409: D/cocos2d-x debug info(23729): reload all texture
12-23 21:11:44.197: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 360 
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 32 91
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 2424 
12-23 21:11:44.198: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.198: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 3702 
12-23 21:11:44.199: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.199: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 64 2202
12-23 21:11:44.199: D/cocos2d-x debug info(23729): come to foreground of IndexBuffer
12-23 21:11:44.200: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 2 1824 
12-23 21:11:44.200: D/cocos2d-x debug info(23729): come to foreground of VertexBuffer
12-23 21:11:44.200: D/cocos2d-x debug info(23729): recreate IndexBuffer with size 32 351
12-23 21:11:44.214: W/Adreno-ES20(23729): : GL_INVALID_VALUE
12-23 21:11:44.214: E/cocos2d-x assert(23729): jni/../../cocos2d/cocos/./renderer/CCGLProgramState.cpp function:setVec4 line:166
12-23 21:11:44.215: D/cocos2d-x debug info(23729): OpenGL error 0x0501 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.216: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.216: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.228: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.229: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.238: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.238: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
12-23 21:11:44.244: W/Adreno-ES20(23729): : GL_INVALID_OPERATION
12-23 21:11:44.244: D/cocos2d-x debug info(23729): OpenGL error 0x0502 in jni/../../cocos2d/cocos/./renderer/CCTextureAtlas.cpp drawNumberOfQuads 689
...
```

Link to Cocos-2dx forum [thread](http://discuss.cocos2d-x.org/t/android-minimizing-restoring-app-causing-warnings-and-errors/19059)

### PR DESCRIPTION
**Pull request by dabingnn**
Fix #9599 `GL_INVALID_VALUE` bug.

### CODE REVIEW

**Comment by dabingnn** [comment]
Please do not merge it now, please we can not reproduced the bug reported at #9599.
We need the @maltium to review and test this pull request.

**Comment by dabingnn** [comment]
@minggo could you please review the pull request? If it is OK, then we can merge it safely.

**Comment by minggo** [comment]
- please clear VAO too
- please add comment why need to clear VAO and VBO here
- then please merge it and change CHANGELOG

Thanks.

**Comment by dabingnn** [comment]
[ci rebuild]

**Pull request merged**
