### PR TITLE
FileUtilsWin32 correct use unicode version

### PR DESCRIPTION
**Pull request by perminovVS**
all dependent on the encoding win api move to FileUtilsWin32 and use Wide Char version(not Ansi).
add StringUtf8ToWideChar and StringWideCharToUtf8 to convert utf8 and
unicode

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by perminovVS** [comment]
Build failed only ios, that has not changed.( ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel )

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by perminovVS** [comment]
new version #11866 (for easy merge)

**Pull request closed without merging**
