### PR TITLE
V3 remove simulator

### PR DESCRIPTION
**Pull request by SunLightJuly**
removed simulator from V3

### CODE REVIEW

**Comment by darkdukey** [comment]
why remove simulator? how can developer build their own version?

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@SunLightJuly 
Please send a pull request to v4-develop too.
Thanks.

**Comment by SunLightJuly** [comment]
ok

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
