### PR TITLE
Downloader improvements

### PR DESCRIPTION
**Pull request by ricardoquesada**
Adds many improvements to Downloader
- curl code decoupled from it. Moved to `CCDownloaderImpl`
- uses less memory: Duplicated data removed. ProgressData merged into DownloadUnit
- faster: no need to allocate many small objects
- code is simpler: threading code is simpler, but as robust as before.
- sync operations are faster since they are not scheduled
- adds tests for `Downloader` in "cpp-tests/Downloader Test"
- and other minor fixes

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@pandamicro 

Please, let me know if you like the changes that I did. Thanks!

**Comment by pandamicro** [comment]
Many thanks @ricardoquesada , I will check it out today

**Comment by ricardoquesada** [comment]
@pandamicro 
Thanks.
I updated all projects.
For some reason iOS and Lua-Android are not compiling.
But Linux, Mac, Windows and the JS/C++ Android are compiling. I'll continue working on this tomorrow.

**Comment by pandamicro** [comment]
Hi, riq, 

It's great to see a more proper implementation of network layer.
I like your idea to separate the file/stream manipulation and download process. Now only `DownlaodImpl` interface need to be adapt to different platform which is much simpler than the original `Downloader` interface. For the next step, it will also be easier to remove curl dependency on iOS/Android.

I tested iOS and Mac, it works like a charm. Haven't got a chance to test other platforms yet.

**Comment by ricardoquesada** [comment]
@pandamicro 
Thanks.
It is compiling an running on all platforms except on android lua-tests, which for some reason it doesn't compile. The rest of the Android tests compile Ok, including lua-empty-test.
The error message that I got is:

```
[armeabi] StaticLibrary  : libluacocos2d.a
[armeabi] StaticLibrary  : libcocos2d.a
[armeabi] StaticLibrary  : libcocostudio.a
[armeabi] StaticLibrary  : libcocosbuilder.a
[armeabi] StaticLibrary  : libcocos3d.a
[armeabi] StaticLibrary  : libspine.a
[armeabi] StaticLibrary  : libnetwork.a
[armeabi] StaticLibrary  : libui.a
[armeabi] StaticLibrary  : libcocosdenshion.a
[armeabi] StaticLibrary  : flatbuffers.a
[armeabi] StaticLibrary  : libextension.a
[armeabi] StaticLibrary  : libaudioengine.a
[armeabi] StaticLibrary  : libcocos2dxinternal.a
[armeabi] StaticLibrary  : libbox2d.a
[armeabi] StaticLibrary  : libbullet.a
[armeabi] StaticLibrary  : librecast.a
[armeabi] StaticLibrary  : libluacocos2dandroid.a
[armeabi] StaticLibrary  : libcocos2dandroid.a
[armeabi] StaticLibrary  : libcpufeatures.a
[armeabi] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi/gdbserver
[armeabi] Gdbsetup       : libs/armeabi/gdb.setup
[armeabi] SharedLibrary  : liblua_tests.so
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:82: error: undefined reference to 'cocos2d::network::Downloader::Downloader()'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:83: error: undefined reference to 'cocos2d::network::Downloader::setConnectionTimeout(int)'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:443: error: undefined reference to 'cocos2d::network::Downloader::downloadAsync(std::string const&, std::string const&, std::string const&)'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:499: error: undefined reference to 'cocos2d::network::Downloader::downloadAsync(std::string const&, std::string const&, std::string const&)'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:564: error: undefined reference to 'cocos2d::network::Downloader::batchDownloadAsync(std::unordered_map<std::string, cocos2d::network::DownloadUnit, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, cocos2d::network::DownloadUnit> > > const&, std::string const&)'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:622: error: undefined reference to 'cocos2d::network::Downloader::batchDownloadAsync(std::unordered_map<std::string, cocos2d::network::DownloadUnit, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, cocos2d::network::DownloadUnit> > > const&, std::string const&)'
/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android/../../../../extensions/assets-manager/AssetsManagerEx.cpp:771: error: undefined reference to 'cocos2d::network::Downloader::batchDownloadAsync(std::unordered_map<std::string, cocos2d::network::DownloadUnit, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, cocos2d::network::DownloadUnit> > > const&, std::string const&)'
/Users/riq/androiddev/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:573: error: undefined reference to 'cocos2d::network::Downloader::~Downloader()'
/Users/riq/androiddev/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/shared_ptr_base.h:373: error: undefined reference to 'cocos2d::network::Downloader::~Downloader()'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi/liblua_tests.so] Error 1
make: Leaving directory `/Users/riq/progs/cocos2d-x/tests/lua-tests/project/proj.android'
Error running command, return code: 2.
Build dynamic library for project [ /Users/riq/progs/cocos2d-x/build/../tests/lua-tests ] fails!
```

which is strange.
Apparently lua-tests is not linking with the new code... but that is strange is that lua-empty-test, cpp-tests and the others are linking Ok.

Any idea? Thanks!

**Comment by pandamicro** [comment]
I failed to compile lua-test too with the same errors.

I think it's due to the `lua_assetsmanager_test_sample.cpp` which included `extensions/cocos-ext.h` which finally included `AssetsManagerEx.h`.

For some reason, AssetsManagerEx can't be link for liblua_tests.so.

Don't know exactly how to solve it, I'm not very familiar with Android, but I will keep trying

**Comment by zilongshanren** [comment]
@ricardoquesada 
Could you squash the commits?  Thanks.

**Comment by pandamicro** [comment]
I tried to modify `extension/android.mk` by adding

```
LOCAL_STATIC_LIBRARIES += cocos_network_static
```

This avoid the undefined reference to `Downloader` issues, but it raises new issues in bullet. I think there is something wrong with Lua-tests android project settings. Both bullet and network shouldn't be reference while compiling `liblua-tests.so`

Here is the new errors:

```
[armeabi] SharedLibrary  : liblua_tests.so
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:99: error: undefined reference to 'btAlignedAllocInternal(unsigned int, int)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h:99: error: undefined reference to 'btAlignedFreeInternal(void*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h:112: error: undefined reference to 'btAlignedAllocInternal(unsigned int, int)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h:112: error: undefined reference to 'btAlignedFreeInternal(void*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:86: error: undefined reference to 'btDefaultCollisionConfiguration::btDefaultCollisionConfiguration(btDefaultCollisionConstructionInfo const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:90: error: undefined reference to 'btCollisionDispatcher::btCollisionDispatcher(btCollisionConfiguration*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:92: error: undefined reference to 'btDbvtBroadphase::btDbvtBroadphase(btOverlappingPairCache*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:95: error: undefined reference to 'btSequentialImpulseConstraintSolver::btSequentialImpulseConstraintSolver()'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:101: error: undefined reference to 'btDiscreteDynamicsWorld::btDiscreteDynamicsWorld(btDispatcher*, btBroadphaseInterface*, btConstraintSolver*, btCollisionConfiguration*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DWorld.cpp:282: error: undefined reference to 'btCollisionWorld::convexSweepTest(btConvexShape const*, btTransform const&, btTransform const&, btCollisionWorld::ConvexResultCallback&, float) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionDispatch/btCollisionObject.h:123: error: undefined reference to 'btAlignedAllocInternal(unsigned int, int)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionDispatch/btCollisionObject.h:123: error: undefined reference to 'btAlignedFreeInternal(void*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/LinearMath/btDefaultMotionState.h:14: error: undefined reference to 'btAlignedAllocInternal(unsigned int, int)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/LinearMath/btDefaultMotionState.h:14: error: undefined reference to 'btAlignedFreeInternal(void*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:89: error: undefined reference to 'btRigidBody::btRigidBody(btRigidBody::btRigidBodyConstructionInfo const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:94: error: undefined reference to 'btCollisionObject::setActivationState(int) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:102: error: undefined reference to 'btCollisionObject::setActivationState(int) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:143: error: undefined reference to 'btRigidBody::applyDamping(float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:188: error: undefined reference to 'btRigidBody::setCenterOfMassTransform(btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:198: error: undefined reference to 'btRigidBody::setDamping(float, float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:213: error: undefined reference to 'btRigidBody::setGravity(btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:233: error: undefined reference to 'btRigidBody::setMassProps(float, btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:357: error: undefined reference to 'btCollisionObject::setActivationState(int) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:362: error: undefined reference to 'btCollisionObject::setActivationState(int) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:377: error: undefined reference to 'btGhostObject::btGhostObject()'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DObject.cpp:379: error: undefined reference to 'btGhostObject::~btGhostObject()'
./obj/local/armeabi/libcocos2dxinternal.a(CCPhysics3DObject.o):CCPhysics3DObject.cpp:function vtable for cocos2d::btCollider: error: undefined reference to 'btCollisionObject::serialize(void*, btSerializer*) const'
./obj/local/armeabi/libcocos2dxinternal.a(CCPhysics3DObject.o):CCPhysics3DObject.cpp:function vtable for cocos2d::btCollider: error: undefined reference to 'btCollisionObject::serializeSingleObject(btSerializer*) const'
./obj/local/armeabi/libcocos2dxinternal.a(CCPhysics3DObject.o):CCPhysics3DObject.cpp:function typeinfo for cocos2d::btCollider: error: undefined reference to 'typeinfo for btGhostObject'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionShapes/btConvexInternalShape.h:52: error: undefined reference to 'btConvexShape::~btConvexShape()'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionShapes/btConvexInternalShape.h:52: error: undefined reference to 'vtable for btConvexInternalShape'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionShapes/btSphereShape.h:29: error: undefined reference to 'btConvexInternalShape::btConvexInternalShape()'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletCollision//CollisionShapes/btSphereShape.h:34: error: undefined reference to 'vtable for btSphereShape'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:130: error: undefined reference to 'btBoxShape::btBoxShape(btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:142: error: undefined reference to 'btCylinderShape::btCylinderShape(btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:148: error: undefined reference to 'btCapsuleShape::btCapsuleShape(float, float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:155: error: undefined reference to 'btConvexHullShape::btConvexHullShape(float const*, int, int)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:162: error: undefined reference to 'btTriangleMesh::btTriangleMesh(bool, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:164: error: undefined reference to 'btTriangleMesh::addTriangle(btVector3 const&, btVector3 const&, btVector3 const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:166: error: undefined reference to 'btBvhTriangleMeshShape::btBvhTriangleMeshShape(btStridingMeshInterface*, bool, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:185: error: undefined reference to 'btHeightfieldTerrainShape::btHeightfieldTerrainShape(int, int, void const*, float, float, float, int, PHY_ScalarType, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:194: error: undefined reference to 'btCompoundShape::btCompoundShape(bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DShape.cpp:196: error: undefined reference to 'btCompoundShape::addChildShape(btTransform const&, btCollisionShape*)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h:185: error: undefined reference to 'btAngularLimit::set(float, float, float, float, float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h:223: error: undefined reference to 'btAngularLimit::getLow() const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btHingeConstraint.h:232: error: undefined reference to 'btAngularLimit::getHigh() const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./../external/bullet/BulletDynamics/ConstraintSolver/btSliderConstraint.h:273: error: undefined reference to 'btSliderConstraint::calculateTransforms(btTransform const&, btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:113: error: undefined reference to 'btPoint2PointConstraint::btPoint2PointConstraint(btRigidBody&, btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:122: error: undefined reference to 'btPoint2PointConstraint::btPoint2PointConstraint(btRigidBody&, btRigidBody&, btVector3 const&, btVector3 const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:169: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btTransform const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:180: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btVector3 const&, btVector3 const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:191: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btRigidBody&, btVector3 const&, btVector3 const&, btVector3 const&, btVector3 const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:204: error: undefined reference to 'btHingeConstraint::btHingeConstraint(btRigidBody&, btRigidBody&, btTransform const&, btTransform const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:230: error: undefined reference to 'btHingeConstraint::setFrames(btTransform const&, btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:253: error: undefined reference to 'btHingeConstraint::setMotorTarget(btQuaternion const&, float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:257: error: undefined reference to 'btHingeConstraint::setMotorTarget(float, float)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:284: error: undefined reference to 'btHingeConstraint::getHingeAngle()'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:291: error: undefined reference to 'btHingeConstraint::getHingeAngle(btTransform const&, btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:342: error: undefined reference to 'btSliderConstraint::btSliderConstraint(btRigidBody&, btRigidBody&, btTransform const&, btTransform const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:621: error: undefined reference to 'btConeTwistConstraint::btConeTwistConstraint(btRigidBody&, btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:637: error: undefined reference to 'btConeTwistConstraint::btConeTwistConstraint(btRigidBody&, btRigidBody&, btTransform const&, btTransform const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:705: error: undefined reference to 'btConeTwistConstraint::setMotorTarget(btQuaternion const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:711: error: undefined reference to 'btConeTwistConstraint::setMotorTargetInConstraintSpace(btQuaternion const&)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:716: error: undefined reference to 'btConeTwistConstraint::GetPointForAngle(float, float) const'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:748: error: undefined reference to 'btGeneric6DofConstraint::btGeneric6DofConstraint(btRigidBody&, btTransform const&, bool)'
/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android/../../../../cocos/./physics3d/CCPhysics3DConstraint.cpp:764: error: undefined reference to 'btGeneric6DofConstraint::btGeneric6DofConstraint(btRigidBody&, btRigidBody&, btTransform const&, btTransform const&, bool)'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi/liblua_tests.so] Error 1
make: Leaving directory `/Users/panda/StudyWork/Cocos/CocosFramework/tests/lua-tests/project/proj.android'
```

**Comment by ricardoquesada** [comment]
@minggo do you have any idea why lua-tests in android are not compiling ?

@zilongshanren sure, once it compiles Ok, I'll squash the commits.

**Comment by minggo** [comment]
@ricardoquesada 
There is an error happened when processing binding-generator for extension section.

`7. <severity = Fatal, location = <SourceLocation file '/jenkins/workspace/ccspr/node/mac/cocos/network/CCDownloaderImpl.h', line 30, column 10>, details = "'curl/curl.h' file not found">`

The reason is:
- AssetsManagerEx.h > cocos/network/CCDownloader.h >  cocos/network/CCDownloaderImpl.h > curl/curl.h

`>` means `includes`.

So i think you should do in the three ways:
1. don't include `cocos/network/CCDownloaderImpl.h` in `cocos/network/CCDownloader.h` if possible
2. add header path of `curl/curl.h` in `cocos_headers` section in `tools/tolua/cocos2dx_extensions.ini`
3. don't include `curl/curl.h` in `cocos/network/CCDownloaderImpl.h`

I think 3 is more reasonable because developers don't have to include `curl/curl.h` path when including `cocos/network/CCDownloader.h`.

**Comment by minggo** [comment]
About the compiling error for lua-tests, i have no idea now too. I will take a look tomorrow.

**Comment by minggo** [comment]
I don't know why cpp-tests can link ok on Android, because i think it has the same problem as lua-tests. I printed the full link command of cpp-tests and lua-tests, libnetwork.a is linked before libextension.a in both projects.

I modified as @pandamicro did. It has the same problem as he said. It is because libbullet.a is linked before libcocos2dxinternal.a. But i don't know why the link sequence changed. There is not documentation saying how link sequence is generated.

**Comment by minggo** [comment]
@ricardoquesada 
I fixed it and send you a pull request here: https://github.com/ricardoquesada/cocos2d-x/pull/4.

**Comment by ricardoquesada** [comment]
@minggo Thaaaaaaaaanks :)

**Comment by minggo** [comment]
@ricardo
It is my pleasure. But the binding error still exists. I will try to fix it too and send you a pull request.

**Comment by minggo** [comment]
@ricardoquesada 
I sent you a pull request to fix the binding error in this PR: https://github.com/ricardoquesada/cocos2d-x/pull/5.

**Comment by ricardoquesada** [comment]
@minggo thaaaanks again :)

**Comment by minggo** [comment]
You are welcome.

**Comment by minggo** [comment]
It is strange that it also has the error.
I tested in my machine and can work.
I am busy today to continue fixing it.
I will try to fix it when i am free tomorrow.

**Comment by ricardoquesada** [comment]
ok. thanks. I really don't know what is the problem :(
On my machines, everything is compilling Ok, but for some reason Jenkins doesn't like it.

**Comment by minggo** [comment]
I checked it again. There is not issue in binding codes, what i did are
- create a new branch based on v3
- pull the codes from ricardo's downloader_decouple branch
- run cocos/tools/tolua/genbindings.py

**Comment by minggo** [comment]
[ci  rebuild]

**Comment by minggo** [comment]
Ok, the js-binding has the same error as lua binding.
I fixed it and send you a PR: https://github.com/ricardoquesada/cocos2d-x/pull/6.

**Comment by ricardoquesada** [comment]
@minggo thanks!

**Comment by minggo** [comment]
jenkins passed but failed to update status.

**Comment by ricardoquesada** [comment]
@minggo ok. thanks. So is it safe to merge it? If so, I'll create a new squashed PR. Thanks.

**Comment by minggo** [comment]
Yep, it is safe to merge it.

**Comment by ricardoquesada** [comment]
@minggo thanks.

@zilongshanren  squashed PR is here:
https://github.com/cocos2d/cocos2d-x/pull/13355

**Pull request closed without merging**
