### PR TITLE
Script component

### PR DESCRIPTION
**Pull request by pandamicro**

### CODE REVIEW

**Comment by pandamicro** [comment]
For fixing https://github.com/cocos2d/cocos2d-x/issues/13989

**Comment by pandamicro** [comment]
iOS, Mac, Linux passed.
Android, Windows platforms failed

@WenhaiLin Can you help me fix this PR ?

**Comment by WenhaiLin** [comment]
@pandamicro Okay. I'll check on it.

**Comment by pandamicro** [comment]
Thanks !

**Pull request closed without merging**
