### PR TITLE
 cocos2dInternal cleaned from warnings on Linux with gcc-6.2

### PR DESCRIPTION
**Pull request by yahont**
Mainly:
- unused parameters
- signed-unsigned comparisons
- missing breakets

### CODE REVIEW

**Comment by minggo** [comment]
About unused parameters please refer to this PR: https://github.com/cocos2d/cocos2d-x/pull/16812

**Comment by yahont** [comment]
Ok, I'll rebase after you merge #16812, and then I'll submit it again. As here not only unused parameters are fixed but all other, too.

**Comment by minggo** [comment]
yep, i see, thanks

**Comment by yahont** [comment]
Rebasing after #16812 merge, is not at all easy. I'll cherry-pick the valuable changes and submit another PR. Closing this now then

**Pull request closed without merging**
