### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by ricardoquesada**
added some asserts and some `signed` types for sizes

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@ricardoquesada 
This PR is ok. But our code base has some issue on Android platform. After we resolve the compile issue, you could rebuild it. Now it's no need to rebuild. Or you can just merge it.

Thanks.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
I sent [a post](http://discuss.cocos2d-x.org/t/use-size-t-or-ssize-t/20375) to discuss size_t and ssize_t.

**Pull request merged**
