### PR TITLE
add a new simple AssestsManagerEXTest2 exsample.

### PR DESCRIPTION
**Pull request by qiancy**
I think AssestsManagerEXTest  is more complicated for normal user.
So base on AssestsManagerEXTest ,add a new simple AssestsManagerEXTest2 exsample.
I think maybe help user save their time to implement very simple resource hot update app.
Please check it.
Thanks your great works. =)

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@qiancy  Thanks. I will take a look at your PR.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Pull request closed without merging**
