### PR TITLE
cmake for android

### PR DESCRIPTION
**Pull request by ricardoquesada**
cmake for android (squashed)

commit 59e43a3c80f4af8998e4a14f6463bd7a91617d5f
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 15:19:48 2016 -0800

```
uses new naming convention for projects

uses _ instead of -
```

commit f97ba56608d48b17909649c8617ba9047b566196
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 14:49:22 2016 -0800

```
fooling cmake for real
```

commit 20c2560f75eab952e5131b484284bf20cb07fe07
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 14:43:05 2016 -0800

```
fooling cmake
```

commit a0ada44bc82941830f6c71219a1492d28c28c306
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 14:26:59 2016 -0800

```
makes CMake for Mac happy
```

commit 656b4f5e2dd741215a4699db979fe1b0dce60298
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 13:50:15 2016 -0800

```
linux fix
```

commit fa98aeac8505c764f4a69f15c8a8ff1123fad2a3
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Wed Mar 2 11:18:18 2016 -0800

```
links correctly!
```

commit 9c56ce7143d3a35b44d33f246cec093ca9eaa7d9
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Mar 1 17:44:58 2016 -0800

```
Squashed commit of the following:

commit 2ef52723dae44204c047cb177d5a5670fb659c79
Merge: 8a5c998 25cf1f1
Author: Ricardo Quesada <ricardoquesada@gmail.com>
Date:   Tue Mar 1 16:54:04 2016 -0800

    Merge branch 'v3' into cmake_android

commit 8a5c9981192e344fffc9f14be5cb14f66eccfa24
Author: Chaoren Lin <chaorenl@google.com>
Date:   Thu Feb 11 18:34:46 2016 -0800

    Fix module name in Android template to match CMake project.

commit be85e19e852a9d5fbd6c58cea60c75fe47a5a576
Author: Chaoren Lin <chaorenl@google.com>
Date:   Thu Feb 11 18:27:45 2016 -0800

    Add missing platform specific source file to CMake project.

commit 705389ac6582107a381d0cbc56268eaa98ffc5c3
Author: Chaoren Lin <chaorenl@google.com>
Date:   Wed Feb 10 19:21:12 2016 -0800

    Find AndroidNdkModules.cmake relative to android.toolchain.cmake.

commit a10075e2cb30af2e1f9a30da99efac880658ad6b
Author: Chaoren Lin <chaorenl@google.com>
Date:   Wed Feb 10 19:03:11 2016 -0800

    Remove cpp-empty-test from project templates.

commit e070fcbf210b8628f75785e738202a80a95ac0ff
Author: WenhaiLin <wenhai.lin@chukong-inc.com>
Date:   Mon Aug 31 09:56:03 2015 +0800

    Fix CMake for Android Target
```

### CODE REVIEW

**Comment by zilongshanren** [comment]
@ricardoquesada  After merging this PR, could we use Android Studio to debug the NDK code ?

**Comment by ricardoquesada** [comment]
@zilongshanren I don't think so since Android Studio doesn't support cmake yet... but if I understood correctly, Google is working on that.
But I'm not 100% sure. I'll ask them.

Also, the PR is not complete. I'm working on having "cocos new" create valid Cmakefiles for android.

**Comment by zilongshanren** [comment]
@ricardoquesada 
Good to know that Google is working on that.  There is still one issue about the chipmunk jsb auto bindings, I have mentioned it in https://github.com/cocos2d/cocos2d-x/pull/15159

**Comment by ricardoquesada** [comment]
@zilongshanren yeah... I tried to reproduce it but I couldn't... what are the steps to reproduce it?  thanks.

**Comment by zilongshanren** [comment]
@ricardoquesada  
It's not easy to reproduce this issue, I think you must have some jsb config files to generate these auto bindings, right?

**Comment by zilongshanren** [comment]
@ricardoquesada  How do you generate this file? https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/auto/js_bindings_chipmunk_auto_classes.h

**Comment by ricardoquesada** [comment]
with this script: https://github.com/ricardoquesada/jsbindings

**Comment by zilongshanren** [comment]
`chipmunk_jsb.ini` should be put into the directory "tools/tojs\* and we have to modify genbindings.py to add the `chipmunk_jsb.ini` file.
OK, I will use your repo to resolve this issue, thanks.

**Comment by ricardoquesada** [comment]
Ok. Thanks. My suggestion is that we shouldn't use my repo to host the script...
Actually the script was originally hosted at Zynga (https://github.com/zynga/jsbindings) and I cloned it so that I could fix the chipmunk bindings. If you move it to "tools/tojs*", then I will stop using my own repo. Thanks!

**Comment by zilongshanren** [comment]
@ricardoquesada 
The https://github.com/ricardoquesada/jsbindings/blob/master/configs/chipmunk/chipmunk.bridgesupport file you patched seems not compatible with https://github.com/cocos2d/bindings-generator/tree/0bec01d038c2d764d5e6244b41d149efb858b243/targets/spidermonkey

Maybe @pandamicro  know better how to merge back your patch...

**Comment by ricardoquesada** [comment]
@zilongshanren how is that possible? We don't have chipmunk bindings for lua.

**Comment by zilongshanren** [comment]
@ricardoquesada 
My mistake, I mean https://github.com/cocos2d/bindings-generator/tree/0bec01d038c2d764d5e6244b41d149efb858b243/targets/spidermonkey

**Pull request merged**
