### PR TITLE
SpriteFrameCache support async load

### PR DESCRIPTION
**Pull request by perminovVS**
Async based on Sprite3D and TextureCache.
Load texture and plist file in AsyncTaskPool TASK_IO thread.
Add TextureCache image and generate Sprite Frames in main thread.

update it: #10911

### CODE REVIEW

**Comment by perminovVS** [comment]
Build error no my code (cocos2d_specifics.hpp(66): error C2100:)

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by perminovVS** [comment]
[ci rebuild]

**Comment by minggo** [comment]
close it since there is conflict

**Pull request closed without merging**
