### PR TITLE
WP8 XAML support

### PR DESCRIPTION
**Pull request by stammen**
This pull request adds support for Windows Phone 8 XAML apps.

### CODE REVIEW

**Comment by dungmv** [comment]
cocos2d-x support for Windows Phone 8 XAML. hope that

**Comment by stammen** [comment]
Did you do a git submodule init and git submodule update to update angleproject files?

**Comment by dungmv** [comment]
yes :)

**Comment by stammen** [comment]
?Would you please verify if the file is in cocos2dx/platform/third_part/winrt/angleproject/src/common?

**Comment by dungmv** [comment]
oh, it's submodule, i found it.
Is it in the branche wp8-xaml?

**Comment by dungmv** [comment]
i was test it. but which is version of cocos? it's not cocos2d-x 2.2?

**Pull request merged**
