### PR TITLE
SpriteBatchNode时，对子节点setLocalZOrder排序时无效

### PR DESCRIPTION
**Pull request by zhs007**
Node::setLocalZOrder时，先改变了自己的_localZOrder，如果父节点是SpriteBatchNode，则会在实际排序以前检查子节点的_localZOrder是否改变，所以会导致批量渲染时无法通过子节点的setLocalZOrder来排序。

没有很仔细的读代码，感觉上粒子不是走的这个分支（粒子的子节点是ParticleSystem？），这块代码感觉有点乱，特别是加了粒子以后......

### CODE REVIEW

**Comment by zilongshanren** [comment]
@zhs007  If there are no merge conflicts and you don't want  rebase your current branch, it's better not to merge the upstream to your local branch and push to the remote upstream.
This will cause useless commits and waste CI resources.

As you see, in your current PR, there are 3 commits, but only one commits is useful and contains the needed information, other two commits are useless.

Thanks.

**Comment by zhs007** [comment]
@andyque sorry, I'll be careful.

**Comment by zilongshanren** [comment]
@zhs007  I would rather suggest you to start a new PR and that PR should track from the latest upstream. Thanks. Your PR now even contains some unrelated changes...

**Comment by zhs007** [comment]
@andyque ok

**Comment by pandamicro** [comment]
@zhs007 Please resubmit your changes in another PR, thanks

**Pull request closed without merging**
