### PR TITLE
implement Menu create function by variadic template

### PR DESCRIPTION
**Pull request by jwvg0425**
I think C++11 variadic template is better then classic C style variadic function.

### CODE REVIEW

**Comment by minggo** [comment]
@jwvg0425 Could you please fix the indent issue? It is hard to review. Thanks.

**Comment by jwvg0425** [comment]
@minggo sorry, I fix all tab to 4 space.

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
@jwvg0425 This pull request is good for c++, but template is hard for script bindings.

**Comment by jwvg0425** [comment]
oh, I should've thought of that. close this PR.

**Comment by minggo** [comment]
Thanks.

**Pull request closed without merging**
