### PR TITLE
Fixes compilation errors if ARCH=i386

### PR DESCRIPTION
**Pull request by NatWeiss**

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by shujunqiao** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@NatWeiss 
How to reproduce it?

**Comment by shujunqiao** [comment]
[ci rebuild]

**Comment by NatWeiss** [comment]
Compile the build all libs Mac target on the command line using ARCH=i386.

**Comment by minggo** [comment]
I can not reproduce it. Following is my screenshot
image

**Comment by minggo** [comment]
mac-compile-png

**Comment by NatWeiss** [comment]
Hmm. I was compiling with commandline Xcode. Not a big deal though.

**Pull request closed without merging**
