### PR TITLE
Combine Studio change for get program file full path.

### PR DESCRIPTION
**Pull request by xiaofeng11**
_get_wpgmptr function will cause ASSERT in system library when program is start by C#, so it can not use in Cocos Studio.

@pandamicro @minggo Please reivew this PR.

### CODE REVIEW

**Comment by xiaofeng11** [comment]
Remove condition macro, use GetModuleFileNameW in all case, it is more safe.

@ricardoquesada @pandamicro @minggo Please review this PR.

**Comment by minggo** [comment]
It looks good to me.
Just need to run cocos2d-x tests on windows to check if it can work or not.

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Comment by xiaofeng11** [comment]
@minggo I have run cpp-test, js-test and lua-test under windows system, all works fine.

**Comment by xiaofeng11** [comment]
@minggo I've test and confirm this change is OK for all test under windows system, and before "FileUtils" start use _get_wpgmptr get current program path, old version is use GetModuleFileName to get program path. Could this PR been merged?

**Pull request merged**
