### PR TITLE
fix LabelAtlas constructor protected to CC_CONSTRUCTOR_ACCESS

### PR DESCRIPTION
**Pull request by zhaijialong**

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by zhaijialong** [comment]
[ci rebuild]

**Comment by zhaijialong** [comment]
hi, @minggo 
Can this pr get merged? I don't know why it build failed. This pr is very helpfull to fix jsbinding's bug.

**Comment by minggo** [comment]
It seems breaks lua binding.

**Comment by darkdukey** [comment]
Should be good to merge now.

**Pull request merged**
