### PR TITLE
add Mac Editbox multiline  support.

### PR DESCRIPTION
**Pull request by zilongshanren**
1. It also refactor the original logic and optimize the iOS EditBox implementation.

### CODE REVIEW

**Comment by zilongshanren** [comment]
it also fixed https://github.com/cocos2d/cocos2d-x/issues/14884

**Comment by zilongshanren** [comment]
@xiaofeng11  @WenhaiLin  @ricardoquesada  please review...

**Comment by ricardoquesada** [comment]
what does it do? thanks.

**Comment by zilongshanren** [comment]
@ricardoquesada 
It added multiline editing support to EditBox on Mac platform.
And it also did some minor refactoring to better implement this feature.

**Comment by ricardoquesada** [comment]
sounds good. I think owen should review/merge this feature.

**Comment by zilongshanren** [comment]
@ricardoquesada  
Actually I'm `owen`, I have changed my nick name :smile:

**Comment by ricardoquesada** [comment]
@zilongshanren ha ha. sorry about that :)

I noticed that you renamed some functions... is that correct? or diff is playing some tricks on me?
If so, is this change backwards compatible? If not, why?
Thanks!

**Comment by zilongshanren** [comment]
@ricardoquesada 
It's backwards compatible.  All modifications are internal implementation details.

**Comment by zilongshanren** [comment]
@ricardoquesada 
I indeed rename some functions, but it's due to the new inheritance relations.
I have merged this PR... If you find some issues, please ping me...

**Comment by ricardoquesada** [comment]
@zilongshanren  ok. thanks.

**Pull request merged**
