### PR TITLE
a better CSLoader::bindCallback implementing

### PR DESCRIPTION
**Pull request by ts0307**
This is the method using binding callback at http://www.cocoachina.com/bbs/read.php?tid=274210
It has five steps,

but using my implementing,It can be reduced to a 2 steps,

in other words,Only the second and the fifth step is necessary.

Of course you must  implement this interface cocostudio::WidgetCallBackHandlerProtocol.

I updated the test CustomWidgetCallbackBindTest

notice you must clear the class name of "CustomRootNode" in cocosui/CustomTest/CustomWidgetCallbackBindTest/CustomWidgetCallbackBindTest.csb

### CODE REVIEW

**Comment by ts0307** [comment]
in this way,you don't need to create class of CustomRootNode and CustomRootNodeReader, and call registReaderObject,you only need to create a class which inherit from WidgetCallBackHandlerProtocol and implements it's interface.the last,you need to add a parameter of cocos2d::Node\* deleget to CSLoader::createNode as this CSLoader::createNode(const std::string& filename, cocos2d::Node\* deleget).now you can call createNode with parameters csb's path and point to object of class which implementing WidgetCallBackHandlerProtocol above,
this all.

**Comment by darkdukey** [comment]
@chengstory I think this solution is better than the one we currently have.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
