### PR TITLE
Fix SimpleAudioEngine::sharedEngine()->playBackgroundMusic() freeze on Lollipop[Android 5.0]

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by zszen** [comment]
thank you very much. It worked.

**Comment by Jayatubi** [comment]
Update: This fix is not perfect for Android 4.4. It leads the BGM stop if the 'playBackgroundMusic' has been invoked more than once without stop. The behavior ought to be rewinding the music.

**Comment by WenhaiLin** [comment]
@Jayatubi I will check it, thank you for your feedback.

**Comment by Jayatubi** [comment]
Never mind. After check the latest official release of 2.2.6 it has been fixed well.

**Pull request merged**
