### PR TITLE
Fixes potential crash in AudioEngine::uncache(filePath).

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
@zilongshanren , please review.

**Comment by zilongshanren** [comment]
@dumganhar  Looks good to me.

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@dumganhar any issue related with this PR? Please connect it if there is. Thanks.

**Comment by dumganhar** [comment]
The issue was reported by our QA team, here it is: http://punchbox.info:3000/issues/25880

**Pull request merged**
