### PR TITLE
Revert "Remove ccglstatecache (#19013)"

### PR DESCRIPTION
**Pull request by drelaptop**
- To keep forward compatibility, revert this renderer logic changes

this modify will comes again with multi renderer background, for at that time we didn't need to consider compatibility strictly.

### CODE REVIEW

**Comment by vkreal** [comment]
@drelaptop can you please elaborate more on this drastic revert?

**Comment by minggo** [comment]
Because it breaks compatibility, and it may bring some bugs that are not easy to found and fix, such as this one https://github.com/cocos2d/cocos2d-x/pull/19177.

When supporting metal(may be next version), these OpenGL ES related codes will be deleted too, and that's a better time to do it.

**Review by minggo — APPROVED** [review]

**Comment by minggo** [comment]
And we found wrong effect in 3D modules too.

**Comment by vkreal** [comment]
Make sense. Thank you!

**Pull request merged**
