### PR TITLE
Alignment support for CCLabelBMFont

### PR DESCRIPTION
**Pull request by irwinb**
I ported over [pingpongboss's](https://github.com/pingpongboss/CCLabelBMFontMultiline) awesome addition to CCLabelBMFont to cocos2d-x.

No tests yet..

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, irwinb, thanks for your contribution first.
I have found some issues in your code.
My test code as follow:

<pre>
    CCLabelBMFont* pFont = CCLabelBMFont::labelWithString("My LabelMy LabelMy Label", "bitmapFontChinese.fnt", CCTextAlignmentCenter, 200);
    pFont->setPosition( ccp(size.width/2, size.height/2) );
    addChild(pFont);
</pre>

this works as expected.But nothing will be shown if I change the string to "MyLabelMyLabelMyLabel".
And another issue is that you haven't consider other language like Chinese, Korean or Japanese. Since this is supported in the latest code as a new feature.So you should know how this works by reading the code of 'CCLabelBMFont::createFontChars'. Do not deal with string as ANSI string, but UTF-8 string, therefore, the way of counting string length need to be changed to 'cc_utf8_strlen' and the character buffer need to be changed from UTF-8 to Unicode since 'char id' is using unicode in '.fnt' files. 

Regards,
James Chen

**Comment by dumganhar** [comment]
Yes, it's the same as '\0' to terminate string.

> I will fix all of this, but before I do, I was wondering the reasoning behind these two lines
> 
> `unsigned short* pUniStr = new unsigned short[utf8len+1];
>         pUniStr[utf8len] = 0;`
> 
> What is the purpose of setting pUniStr[utf8len] to 0?  Is it the same as '\0' to terminate the string?

**Comment by dumganhar** [comment]
Hi, irwinb,
Thanks for your works, but it still can't work perfectly. For example, when I use "M yLabelMyLabelMyLabel" as a string, nothing will be shown. If I use "MyLabelMyLabelMyLabel", labels are just shown in one line rather than multi-line. My test code is as follows:

<pre>
LabelBMFontChinese::LabelBMFontChinese()
{
    CCSize size = CCDirector::sharedDirector()->getWinSize();
    CCLabelBMFont* pLable = CCLabelBMFont::labelWithString("M yLabelMyLabelMyLabel", "fonts/bitmapFontChinese.fnt", CCTextAlignmentCenter, 200);
    pLable->setPosition(ccp(size.width / 2, size.height /2));
    this->addChild(pLable);
}
</pre>

**Comment by dumganhar** [comment]
If I use the code which use Chinese letters below, my application will crash.

<pre>
LabelBMFontChinese::LabelBMFontChinese()
{
    CCSize size = CCDirector::sharedDirector()->getWinSize();
    CCLabelBMFont* pLable = CCLabelBMFont::labelWithString("中国", "fonts/bitmapFontChinese.fnt", CCTextAlignmentCenter, 200);
    pLable->setPosition(ccp(size.width / 2, size.height /2));
    this->addChild(pLable);
}
</pre>

Could you please fix this issue?

**Comment by dumganhar** [comment]
Hi, irwinb,
I have reviewed your code, you have done a perfect work, but I found that when there are not space and '\n 'characters, the bitmap label will not be set a newline. I don't know whether this is necessary? What's your opinion?

**Comment by irwinb** [comment]
You are too kind..

Hmm, it should probably be that new line characters be inserted if the string contains 0 white space characters.  The reason for that is because if a user gives a label an explicit width, they would expect that the label never expands past the defined bounds.  I was thinking about that but I totally forgot :).  I'll quickly fix that.

**Comment by dumganhar** [comment]
Ok, thank you so much.

**Comment by irwinb** [comment]
So I was using the label today; I found that I preferred that it never break lines at places other than spaces.  I'm not sure what is preferred for other languages, but for English at least, I would prefer that it not break up words.

It would be nice to get some input about other languages.

**Comment by dumganhar** [comment]
Yes, English uses space to distinguish words, but for other languages, they may not use space to achieve that, for example, for Chinese, we use symbol like comma to distinguish sentence, however, there is not space between words. So I think 'break line' is necessary.

**Comment by dumganhar** [comment]
Hello, irwinb,
  Do you still focus on this issue?

**Comment by irwinb** [comment]
Hey dumhanhar, sorry to keep you guys waiting and not following up.  It is crunch time for us right now preparing for GDC..

After GDC passes and it quites down a bit, I will finish this.  I see the next release is in 24 days.  That is more than reachable.

**Comment by dumganhar** [comment]
Okay, thanks. :)

**Comment by irwinb** [comment]
Not sure if anyone has looked at this yet but I implemented both line breaking strategies.  The user can set which strategy they prefer.  Lines are broken on white space by default but can be set to break on any character.  

I chose this because when creating English labels, it is often desirable to have automatic breaking on white space characters.  On the other hand, as dumganhar mentioned, some languages don't require the use of spaces in their text so breaking on any character is required.

**Comment by dumganhar** [comment]
Hi, irwinb, I am testing this pull request. If there are no bugs, I will merge it to our master branch.
Thanks a lot. :)

**Comment by dumganhar** [comment]
Great work, irwinb, I have merged your commit to the master, Thanks very much.

**Pull request merged**
