### PR TITLE
Fix typo: "angel" to "angle"

### PR DESCRIPTION
**Pull request by kobake**
Fixed typo "angel" to "angle" in comments.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@kobake Good catch!
One thing to notice: you don't need to care the cocos/scripting/lua-bindings/auto/api/OrbitCamera.lua file, the CocosRobot will generate it automatically.

You only need to fix the typo in CCOrbitCamera.cpp.

Thanks.

**Comment by kobake** [comment]
I see. Where is CCOrbitCamera.cpp?

**Comment by zilongshanren** [comment]
@kobake  Sorry, I mean the OrbitCamera class. You have fixed it  in your PR. So you just need to remove `cocos/scripting/lua-bindings/auto/api/OrbitCamera.lua` in your PR and it's done.

**Comment by kobake** [comment]
Ok. I have removed OrbitCamera.lua in PR. Thanks for information :)

**Pull request merged**
