### PR TITLE
support animation list

### PR DESCRIPTION
**Pull request by 2youyou2**
Supports animation list.
You can play ActionTimeline with animation name.

### CODE REVIEW

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by 2youyou2** [comment]
ci rebuild

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
Should fix the mac build

**Comment by 2youyou2** [comment]
please don't merge now, need update flat buffer reader.

**Pull request closed without merging**
