### PR TITLE
BMFont need to refresh size by refresh the string

### PR DESCRIPTION
**Pull request by liamcindy**
@minggo  please review this pr for UITextBMFont

### CODE REVIEW

**Comment by minggo** [comment]
Why?

**Comment by liamcindy** [comment]
@minggo The BMFont need to refresh size while change BMFont file. But only setString could refresh BMFont's size.... If there is anther funtion to refresh BMFont's size, it will be cool

**Comment by WenhaiLin** [comment]
@liamcindy I think you should update the implementation of TextBMFont::setFntFile.

**Comment by liamcindy** [comment]
@Dhilan007 There is setString in setFntFile，so we need anther function

**Comment by liamcindy** [comment]
@Dhilan007 Please check this

**Comment by liamcindy** [comment]
@Dhilan007 update setString

**Comment by WenhaiLin** [comment]
@minggo This PR could be merge after the CI server is ready.

**Pull request merged**
