### PR TITLE
Update Reader

### PR DESCRIPTION
**Pull request by pipu**
Update:
1. CSParseBinary_generated.h
2. FlatBufferSerialize.cpp
3. CCActionTimelineCache.cpp
4. TextFieldReader.cpp
5. TextReader.cpp
6. ButtonReader.cpp

### CODE REVIEW

**Comment by minggo** [comment]
Could you please describe what's this PR do?
I know these files are modified, bug why?

**Comment by minggo** [comment]
And you commit message just `update reader`.
What's updated?
Why update?

**Comment by pipu** [comment]
ok.
I fixed a bug that serialize and parse plist attribute for texture frame.

**Comment by edwardzhou** [comment]
At least, TextReader still has some bug on attributes parsing.
Test case:
1. Open CocoStudio 2.0.5, create a new scene and add a Text widget.
2. change the Text properties as following in the properties editor

```
 Auto Adjust:  false
 Size:    200 x 100 px
 FontSize: 20
```
1. export in csb format
2. use CSLoader to load the scene
3. call Text widget's setString("在代码里用 setString设置一个长一些的字符串时，1. 字符串不会自动换行，2. Text控件的尺寸会错乱")

I guess either CosoStudio export data missing the properties, or TextReader's FlatBuffer data definition got problem.

**Comment by pipu** [comment]
@edwardzhou

I fix the problem that is what you mentioned.

**Comment by edwardzhou** [comment]
great, i will help on verification once merged.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by edwardzhou** [comment]
this patch works. But I found another problem in Text Widget. I created a new PR #9462 .

**Pull request merged**
