### PR TITLE
Update HTTPClient to use C++11 callbacks

### PR DESCRIPTION
**Pull request by Mazyod**
[NEW]: update HTTPClient to use C++11 callbacks
[NEW]: updated tests to use the new API
[DEP]: deprecated old target/selector API

I tried to follow the conventions found in `CCMenuItem` as much as possible.

**Note**: This fixes [issue #4702 on the issue tracker](http://www.cocos2d-x.org/issues/4702).
Thanks,
Maz

### CODE REVIEW

**Comment by Mazyod** [comment]
I don't know why it would fail on Android... I'll test it tomorrow, unless someone can point out why?

**Comment by dumganhar** [comment]
It isn't your fault about the `CI build failure`. We will check it out.

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
