### PR TITLE
Fix keyboard type for cocos2d::ui::EditBox::InputMode::NUMERIC.

### PR DESCRIPTION
**Pull request by dmurtagh**
Should be UIKeyboardTypeNumberPad.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@dmurtagh 
Thanks， what's the difference between both?

**Comment by WenhaiLin** [comment]
UIKeyboardTypeDecimalPad:
image

UIKeyboardTypeNumberPad:
image

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@WenhaiLin 
NUMERIC means decimal?

**Comment by zilongshanren** [comment]
`
case kEditBoxInputModeDecimal:

```
this.mInputModeConstraints = InputType.TYPE_CLASS_NUMBER |   

                                   InputType.TYPE_NUMBER_FLAG_DECIMAL |       

                                   InputType.TYPE_NUMBER_FLAG_SIGNED;

                                   break;
```

`

On Android, the ui::EditBox::InputMode::NUMERIC means the input should have `dot` key. But the number keypad doesn't have `dot` key.

@dmurtagh 
please check.

**Pull request closed without merging**
