### PR TITLE
Fix bug: CCControl's touch priority is not set correctly; m_nDefaultTouchPriority is never used;

### PR DESCRIPTION
**Pull request by tiantian20007**
Fix bug: CCControl's touch priority is not set correctly; m_nDefaultTouchPriority is never used;

### CODE REVIEW

**Comment by dumganhar** [comment]
So do you think we should remove `(g|s)etDefaultTouchPriority` in `CCControl` class?
It seems to be unused now.

**Comment by tiantian20007** [comment]
Yeah, maybe it's better to remove this duplicate property, I was thinking why this property was added;

**Comment by dumganhar** [comment]
I'm also confused. :(
If you have found out why the author add this property, plz let me know. Thanks.

**Comment by tiantian20007** [comment]
See from previous change log of CCControl.cpp:

``` c++
 void CCControl::registerWithTouchDispatcher()
 {
-    CCDirector::sharedDirector()->getTouchDispatcher()->addTargetedDelegate(this, m_nDefaultTouchPriority, true);
+    CCDirector::sharedDirector()->getTouchDispatcher()->addTargetedDelegate(this, getTouchPriority(), true);
 }
```

then m_nDefaultTouchPriority is never used again;

**Comment by tiantian20007** [comment]
Js binding needs to be update.

**Comment by dumganhar** [comment]
OK, don't worry about jsbinding, it'll be auto generated by jenkins.
Thanks.:)

**Comment by tiantian20007** [comment]
Well, that's awesome to me ！So I don't need to run generateJsBinding.sh manually every time the interface of my c++ code changed after using jenkins?

**Comment by dumganhar** [comment]
If you delete or adding some methods, you should run `tools/tojs/genbindings-win32.bat or genbindings.sh` to test whether your changes could take effect. But the modified codes in the submodule of `scripting/javascript/bindings/generated` should not be committed. And it should be reverted before you pull the latest codes which merge your changes.

You could look at the status of cxx-generator project on jenkins here(http://ci.cocos2d-x.org/)
Every time there is a interface changed, jenkins will pull latest codes, and re-generate binding codes.
Then, send a PR by `cocosRobot` like this (https://github.com/cocos2d/cocos2d-x/pull/2278).

**Comment by dumganhar** [comment]
Thanks. Merged. I will update the AUTHOR file later.

**Pull request merged**
