### PR TITLE
Fix missing protocol method warning for iOS 6.0 addition

### PR DESCRIPTION
**Pull request by mchinen**
Fixes a warning when compiling for iOS 6.0 (a new method was added to UITextInput Protocol in iOS 6.0, which EAGLView implements).

The method does nothing but CCLog, like the other method implementations for hit detection.

### CODE REVIEW

**Comment by michaelcontento** [comment]
It would be nice, if you could indent the method body with 4 instead of 3 spaces :)

**Comment by mchinen** [comment]
Ah, sorry, forgot about that.  Fix with proper indent added.

**Comment by michaelcontento** [comment]
Thanks and I hope it gets merged soon :+1:

**Comment by minggo** [comment]
Thank you.

**Pull request merged**
