### PR TITLE
Correct use and convert unicode from utf8. WinRT

### PR DESCRIPTION
**Pull request by perminovVS**
Move StringUtf8ToWideChar and StringWideCharToUtf8 to CCWinRTUtils(
Replace CCUtf8ToUnicode)
Use StringUtf8ToWideChar for convert utf8 to unicode
Use StringWideCharToUtf8 for convert unicode to utf8
CCUtf8ToUnicode and CCUnicodeToUtf8 deprecated

### CODE REVIEW

**Comment by pandamicro** [comment]
@jianglong0156 @WenhaiLin Please take a look at this PR, do we need to include it in v3.8 ?

**Comment by perminovVS** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
@pandamicro @jianglong0156 I think this pr is OK for merge.

**Comment by jianglong0156** [comment]
@pandamicro @WenhaiLin  I think this pr is OK for merge too

**Comment by pandamicro** [comment]
Thanks @perminovVS

**Pull request merged**
