### PR TITLE
CCLayerColor opacity fix

### PR DESCRIPTION
**Pull request by edbartley**
CCLayerColor::_realOpacity is not set in ::initWithColor(…) causing unexpected behavior if a ::runAction(CCFadeTo::create(…)) applied to the LayerColor.

### CODE REVIEW

**Comment by sergey-shambir** [comment]
Finally, this code changes 1 line... How about to clear commit history (reproduce change in new branch, created from origin/master)?

**Comment by edbartley** [comment]
@sergey-shambir Are you suggesting there is a problem with this pull request? If so, what exactly is the problem?

**Comment by winipcfg** [comment]
@edbartley There are 20 commits while it only involves single line of code in the final. Therefore, @sergey-shambir suggested to cleanup commit history and submit request again. My two cents.

**Comment by edbartley** [comment]
Sorry, I still don't see the problem. What will be the end result if this PR is merged?                                                                                                                                                                                                                           From: SummonerSent: Wednesday, April 24, 2013 9:49 PMTo: cocos2d/cocos2d-xReply To: cocos2d/cocos2d-xCc: Ed BartleySubject: Re: [cocos2d-x] CCLayerColor opacity fix (#2432)@edbartley There are 20 commits while it only involves single line of code in the final. Therefore, @sergey-shambir suggested to cleanup commit history and submit request again. My two cents.

—Reply to this email directly or view it on GitHub.

**Comment by dumganhar** [comment]
@winipcfg @sergey-shambir 
I'll help to fix the issue. I mean i'll only make a single commit in another Pull Request.

@edbartley , thanks for your contribution, your fix needs to be merged in next release.
I have created an issue on Redmine(http://www.cocos2d-x.org/issues/2080).

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2444.
Thank all of you.

**Pull request closed without merging**
