### PR TITLE
luabindings: Add script with utf-8 bom support.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by minggo** [comment]
@halx99 Thanks for the PR, but is it needed, because developers will encrypt script files.

**Comment by halx99** [comment]
Yes, In our project, I also encrypt all script files.

**Comment by minggo** [comment]
If so, then why you add the logic in `else`?

**Comment by halx99** [comment]
I missing that, should handle encrypted script at same time.
Well, in our project, bacause I hook FileUtils to decrypt all assets and scripts, so I ignore the else logic.

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
