### PR TITLE
win32 can not stop looping sound effect

### PR DESCRIPTION
**Pull request by rny**

### CODE REVIEW

**Comment by minggo** [comment]
@Dhilan007
Could you please review it?
Thanks.

**Comment by minggo** [comment]
I do it like this:
- run cpp-tests
- enter `Audio - CocosDenshion`
- touch `play in loop`
- after playing the effect several times, touch `stop`
- effect was stopped

So it can stop loop sound effect.
How to reproduce the issue you said?

**Comment by minggo** [comment]
@rny 
Any thought?

**Comment by rny** [comment]
we have two audio effect playing simultaneously with different files, 

```
1. play one time effect A
2. play loop effect B
3. A finished playing
4. call stop for B
```

B stopped this time, but playing again from the beginning soon.

**Pull request merged**
