### PR TITLE
Allow input '\n' on desktop.

### PR DESCRIPTION
**Pull request by xpol**
Android and iOS are allow input '\n' so should desktop.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@xpol 
Why add this patch, what issue does it  try to solves?

**Comment by xpol** [comment]
This allow custom implemented text edit node to have multiple line text be inputted on desktop.
So they behave the same as Android and iOS.

**Comment by stevetranby** [comment]
Assuming this is approved, it should only occur (or be allowed) with an editbox multi-line enabled? It probably should behave more like backspace and then internally check for multiline and insert text or if single-line then it should maybe "blur" the input (make it no longer in focus, hide keyboard on mobile).

**Comment by zilongshanren** [comment]
@xpol 
I agree with @stevetranby , and I think editbox could handle enter key by itself, I'm working on implementing multiline input on Mac and Win32.

I think your patch is only for TextField, right?

**Comment by xpol** [comment]
Yes, This is for Cocos internal nodes like Text Field.
on mobile platforms it is already send newline to text field.but on windows, it does not send newlines to text field.

This shoud not affect editbox, because it does not use the Cocos events.

**Comment by zilongshanren** [comment]
@xpol  since this PR contains merge conflicts, I choose to close it here.

Feel free to reopen a new PR and let's continue the discussion there. thanks.

**Pull request closed without merging**
