### PR TITLE
Fix iOS 5.1.1 crash caused by interruptionHandler

### PR DESCRIPTION
**Pull request by hawkwood**
checks OS version and sets handling based on what is available.

### CODE REVIEW

**Comment by minggo** [comment]
@WenhaiLin 
Please help to check if it can work on newer iOS versions, such as iOS 8 and iOS 7.

**Comment by minggo** [comment]
@hawkwood 
Do you know why it will cause crash on iOS 5.1.1?

**Comment by WenhaiLin** [comment]
@minggo It's work fine on iOS8.1.

**Comment by hawkwood** [comment]
It was crashing because the notification **AVAudioSessionInterruptionNotification** was added in iOS 6.

**Pull request merged**
