### PR TITLE
ipv6  CURLE_COULDNT_RESOLVE_HOST or CURLE_COULDNT_CONNECT

### PR DESCRIPTION
**Pull request by chenzhongqiang**
i update newest curl and websocket libs, and add "$(QUICK_V3_ROOT)/external/websockets/include/ios/"  to search path and add libcrypto.a , libssl.a in xcode, i compile success, but i visit server failed by CURLE_COULDNT_RESOLVE_HOST or CURLE_COULDNT_CONNECT

ipv4 network is ok,
ipv6 network error with CURLE_COULDNT_CONNECT, safari is ok

### CODE REVIEW

**Comment by chenzhongqiang** [comment]
how to fix bug?

**Comment by minggo** [comment]
You send v2 to v3? I don't know what branch you want to send to. If you want to send a PR to v2, then you should create a branch based on v2, and send the PR  to cocos2d-x v2 branch.

You can select which branch to send to when generating a pull request. More detail information please refer to github documentation.

**Comment by chenzhongqiang** [comment]
i use quick 3.3,  i download v3-deps-94 by    https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases/tag/v3-deps-94 , i upgrade external/curl, and add libcrypto.a and libssl.a to libraries link,  i compile quick 3.3 success, but i can not connect in ipv6 network,  error by CURLE_COULDNT_CONNECT

**Comment by minggo** [comment]
So you don't want to send a PR, just want to create an issue?

**Pull request closed without merging**
