### PR TITLE
Android studio gradle cpp-template

### PR DESCRIPTION
**Pull request by asmodehn**
This is a new cpp-template that can be built out of the box with android studio.
Tested on Linux and Windows with Android-Studio 0.5.7

### CODE REVIEW

**Comment by minggo** [comment]
@asmodehn
Because we reduce repo size that corrupt the pull request.
Could you re-send the pull request?
Thanks.

**Comment by asmodehn** [comment]
@minggo
OK, I will prepare a new one from the new v3 branch... I ll keep this one here until then.

**Comment by asmodehn** [comment]
New rebased pull request #6656 submitted. closing this one.

**Comment by minggo** [comment]
Thanks.

**Pull request closed without merging**
