### PR TITLE
Fix the bug in ui::LoadingBar->setProgress()

### PR DESCRIPTION
**Pull request by doomsdayer**
Think about this code:

```
auto bar = ui::LoadingBar::create("1.png");  //create the bar
bar->setPercent(80); //set to 80%
bar->loadTexture("2.jpg"); //change the bar's background to another image, and it is reverted to 100%
bar->setPercent(80); //BUG: This will not work, because the same percent, it is returnd in setPercent()
```

### CODE REVIEW

**Comment by minggo** [comment]
@andyque 
Please take a look.

**Comment by zilongshanren** [comment]
@doomsdayer 
Thanks.
@minggo  I think we could merge it now.

**Comment by doomsdayer** [comment]
Maybe it's better do something in loadTexture().

The CORE problem is: 
After loadTexture(), the loadingBar shows in 100%, but the _percent in it is 80%.
The return sentence in setPercent is for a better performance, it's not wrong itself.

I think it's better to add setPercent(_percent); in the end of loadTexture().
But still it will be returned.....

@andyque how do you think?

**Comment by zilongshanren** [comment]
@doomsdayer 
yeah, it would be nicer. Could you modify your code based on this PR?

**Comment by doomsdayer** [comment]
ok, I'll do it.

**Pull request closed without merging**
