### PR TITLE
[ci skip]Skip a frame if there is no action updated or event dispatched

### PR DESCRIPTION
**Pull request by cocosQA**
To reduce power consumption

### CODE REVIEW

**Comment by sachingarg05** [comment]
This seems to be a very useful and interesting pull request. Hope it gets merged soon.

**Comment by heliclei** [comment]
@ricardoquesada , Do we have a plan to add this feature in v3.1?

**Comment by thoechsmann** [comment]
+1 for such a feature.

But I am not sure if this pull request is doing this correctly.

See comments here: https://github.com/cocos2d/cocos2d-x/pull/6178#issuecomment-39937536

**Comment by rny** [comment]
+1 for such a feature!

**Comment by IcePower** [comment]
+10086 for such a feature
@thoechsmann you said you have already implemented a similar feature at  #6178 (comment). Can  you make a pull request? Thank you very much!

**Pull request closed without merging**
