### PR TITLE
Fix a bug: to handle big frame packet

### PR DESCRIPTION
**Pull request by cnsoft**
Ensure trigger message read event after got whole frame packet.

### CODE REVIEW

**Comment by samuele3hu** [comment]
Sorry, i didn't understand the result for this pr.Can you give the test cases about this pr?thanks.

**Comment by cnsoft** [comment]
@samuele3hu  in some case, the websocket packet of one frame will trigger the data received event more than once time, but, current implement in cocos , it will cause one whole packet is splitted into two message data. this make high level logic confused.

**Comment by samuele3hu** [comment]
Sorry for replying late.I have known your meaning,but how can I reproduce this bug?

**Comment by zilongshanren** [comment]
@cnsoft  @samuele3hu  Any updates?

**Pull request closed without merging**
