### PR TITLE
Clear bad smell code of android fps control.

### PR DESCRIPTION
**Pull request by ggggamer**
Clear bad smell code of android fps control.

### CODE REVIEW

**Comment by ggggamer** [comment]
@minggo Any help? 
Code change is really simple and the android project can build in my win7 + eclipse.
I checked Jenkins's console but can't find any useful info.

**Comment by minggo** [comment]
@ggggamer 
Thanks. Have you synchronized codes before doing this PR? Because some codes is fixed. You can refer to [the codes](https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/platform/android/java/src/org/cocos2dx/lib/Cocos2dxRenderer.java#L104).

**Comment by ggggamer** [comment]
@minggo I synchronized and compared v2, Is it necessary to keep all branch synchronous?

I checked your links above, the same code is already merged in v3 branch.  So just Ignore this. 

Thanks.

**Comment by minggo** [comment]
Oh, sorry. It is my fault.
I thought you were sending to v3.

**Comment by ggggamer** [comment]
@minggo Thanks.

**Comment by StevenGardnerGMJ** [comment]
ok

在 2014-08-19 09:34:51，"ggggamer" notifications@github.com 写道：

@minggo Thanks.

**Pull request merged**
