### PR TITLE
Fix compile error on 64 bit Linux.  Fix some warnings.

### PR DESCRIPTION
**Pull request by leon-li**

### CODE REVIEW

**Comment by minggo** [comment]
#STATICLIBS = $(STATICLIBS_DIR)/libfreetype.a \

# $(STATICLIBS_DIR)/libcurl.a \

# $(STATICLIBS_DIR)/libxml2.a \

# $(STATICLIBS_DIR)/libpng.a \

# $(STATICLIBS_DIR)/libjpeg.a

Why comment these lines? Doesn't it cause error?

**Comment by leon-li** [comment]
Those static libs were compiled on 32 bit system.  Cause linking errors on 64 bit system.

**Comment by minggo** [comment]
Oh, it is the problem. Could you offer 64 bit version?
And should modify the makefile to link correct libs.

**Comment by leon-li** [comment]
Do we really need to bundle those libraries for Linux?  For any Linux distribution, it is very trivial to install those libs.

**Comment by minggo** [comment]
You comment the link, then it can not work on 32 bit and 64 bit.

**Comment by leon-li** [comment]
I will address this a bit later.

**Comment by tangzero** [comment]
I have the static libs for 64 bits systems: http://db.tt/0TFvzjLb

**Comment by minggo** [comment]
tangzero, have you tested on 64-bits linux?

**Comment by leon-li** [comment]
Hi tangzero,
Do you have 64 bit libmodex for CocosDenshion?

**Comment by leon-li** [comment]
I have bundled the 64 bit libs provided by tangzero.  Please help me do a test?  CocosDenshion does not work at the moment because of the lack of 64 bit libfmodex.

**Comment by tangzero** [comment]
I tested on Ubuntu 11.10 64bit.

**Comment by minggo** [comment]
Thank you.

**Pull request merged**
