### PR TITLE
fixing windows8 build

### PR DESCRIPTION
**Pull request by mannewalis**

### CODE REVIEW

**Comment by stammen** [comment]
This  change should also include CC_PLATFORM_WINRT

+#elif CC_TARGET_PLATFORM == CC_PLATFORM_WIN32 || CC_TARGET_PLATFORM == CC_PLATFORM_WP8 || CC_TARGET_PLATFORM == CC_PLATFORM_WINRT

**Comment by mannewalis** [comment]
Does WinRT use the same API calls for ciritical sections?

**Comment by mannewalis** [comment]
And more importantly #include "windows.h"

**Comment by stammen** [comment]
Yes. CC_PLATFORM_WP8 is for Windows Phone 8.0. CC_PLATFORM_WINRT is for the Universal App for Windows Phone 8.1 and Windows Store 8.1 Apps.

**Comment by mannewalis** [comment]
OK added.

**Comment by stammen** [comment]
These functions are already defined in

cocos/platform/winrt/CCPThreadWinRT.cpp

You just need to include CCPThreadWinRT.h to get the needed functions for WINRT and WP8

**Comment by ricardoquesada** [comment]
great. thanks!

**Pull request merged**
