### PR TITLE
refactor Layout, LayoutParameter and LayoutExecutant

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
I think `Executant` is not a good name. Please find a better name for it.

**Comment by zilongshanren** [comment]
@ricardoquesada  How about LayoutStrategy?

**Comment by ricardoquesada** [comment]
Could you describe the functionality of `LayoutExecutant` ? thanks

**Comment by zilongshanren** [comment]
@ricardoquesada  
It rearranges the elements of a  Layout.  The elements could be arranged horizontally or vertically.

**Comment by ricardoquesada** [comment]
How about `LayoutManager` ?

**Comment by zilongshanren** [comment]
@ricardoquesada 
LayoutManager seems good for me, since Android also use this concept: http://android-journey.blogspot.com/2010/03/android-layout-managers.html
Thanks, I will rename it tomorrow.

**Comment by ricardoquesada** [comment]
ok.

**Pull request merged**
