### PR TITLE
[ci skip] Rewrite testcase for stencil depth mask

### PR DESCRIPTION
**Pull request by ZhangMenghe**
In Web Engine we can't push renderCmd halfway through rendering, therefore, I changed another way to express the effect of stencil depth mask.
- Firstly, the whole scene is rendered.
- When Click the text, depthStencil begin to work and makes the screen black.
- Touch anywhere to disable stencil and back to normal scene.

### CODE REVIEW

**Comment by ZhangMenghe** [comment]
@VisualSJ Please help to review

**Comment by fusijie** [comment]
@pandamicro It can be merged.

**Comment by ZhangMenghe** [comment]
New modification see
https://github.com/cocos2d/cocos2d-x/pull/13379

**Comment by fusijie** [comment]
@zilongshanren Please merge it.

**Comment by pandamicro** [comment]
@fusijie You mean we can merge #13379 ?

**Comment by fusijie** [comment]
@pandamicro Yes, It can be merged.

**Pull request merged**
