### PR TITLE
[android] Fix crash caused by JNIEnv null pointer in getStringUTFCharsJNI function

### PR DESCRIPTION
**Pull request by EricDDK**
tmp_crash_android_getstring

### CODE REVIEW

**Comment by EricDDK** [comment]
The probability of crash on the model in the figure(lenovo ipad) is 100 percent.

**Comment by drelaptop** [comment]
did you reproduce this crash locally? 

I think the game have been out-of-work when the `JNIEnv` equals nullptr, even with your crash fixed.

**Comment by EricDDK** [comment]
> did you reproduce this crash locally?
> 
> I think the game have been out-of-work when the `JNIEnv` equals nullptr, even with your crash fixed.

No,this crash only occurs on some special models, the probability is 100%, after the bug is fixed, the game is running normally. I tested it locally, Lenovo's Yoga model, Android 5.0.

I guess Lenovo's tablet Android system has experienced some secondary developments that are not in place.

**Review by drelaptop — APPROVED** [review]
add `nullptr` check to make more stable

**Pull request merged**
