### PR TITLE
fix enable box2d compile error

### PR DESCRIPTION
**Pull request by svzdev**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@mailgyc 
Hi, I have enabled box2d in cpp-test mac， but I can compile it successfully

**Comment by svzdev** [comment]
please review the change:

in the CCColliderDetector.h file 
    std::vectorcocos2d::Vec2 _calculatedVertexList;

but in the CCColliderDetector.cpp file
    _calculatedVertexList = Array::create();

It's clear an error.

**Comment by zilongshanren** [comment]
@xiaofeng11  please take a look at this issue.

**Comment by xiaofeng11** [comment]
@zilongshanren Yes, the code in CCColliderDetector.cpp is a bug.

@mailgyc Why do you change CCColliderDetector.h? Chipmunk and box2d won't work together, so I think the old code won't have problem here.

**Comment by svzdev** [comment]
i don't really understand the relation between  ColliderDetector and box2d,  I enable both of them :-(

**Comment by xiaofeng11** [comment]
@mailgyc ColliderDetector use physical engine to detect collision.  There's two physical engine embed in cocos2d-x, chipmunk and box2d, user can only enable one of them, but not both.  Your change in  CCColliderDetector.h make both of them can be enable, this may cause error.  Please rollback .h file, the changes in cpp file already solved the bug.

**Comment by svzdev** [comment]
@xiaofeng11   I revert the .h file.
can you please explain the code for me again, I can't understand the design.

In class ColliderBody

`#if ENABLE_PHYSICS_BOX2D_DETECT
    b2Fixture *_fixture;
    ColliderFilter *_filter;
#elif ENABLE_PHYSICS_CHIPMUNK_DETECT
    cpShape *_shape;
    ColliderFilter *_filter;
#elif ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX
    std::vector<cocos2d::Vec2> _calculatedVertexList;
#endi`

As I think, ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX is just a calculate result cache, it must enable with box2d or chipmunk, what's the if-else meaning ?

**Comment by xiaofeng11** [comment]
@mailgyc ColliderFilter use box2d or chipmunk to detect collision and the calculate result only been saved when  ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX set. ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX is a separate setting other than box2d or chipmunk.
And yes there is a bug in code you post here. ENABLE_PHYSICS_SAVE_CALCULATED_VERTEX should be a separate #ifdef check but not a #elif.
Now CocosStudio won't use CCColliderDetector  any more, and the original designer has left maintain team, so the code has a long time hasn't update. Could you help us to improve it? Thanks a lot.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
