### PR TITLE
refactor-CCDrawNode

### PR DESCRIPTION
**Pull request by JohnCoconut**
* remove unecessary intermediate temp variables
* remove redundant pointer cast
* remove redundant memset, as the values are assigned immediately in a
for loop.
* minor formatting

### CODE REVIEW

**Comment by JohnCoconut** [comment]
@minggo Do you know why are v2xx functions necessary, Like `v2f` and `__v2f`? It seems to me they are not doing anything particular. `__v2f` is prefixed with double underscores, which is not allowed in standard.

There is a comment saying,

> Vec2 == CGPoint in 32-bits, but not in 64-bits (OS X), that's why the "v2f" functions are needed 

Could you explain it further more? 

https://github.com/cocos2d/cocos2d-x/blob/a40444c5c1bfb7338c82a8821655f88e7ebcbb4c/cocos/2d/CCDrawNode.cpp#L40-L98

**Comment by minggo** [comment]
I have not idea too. It seems they are not needed.

**Comment by minggo** [comment]
May be the original type is not Vec2, it is other types that don't have neg, dot and other functions.

**Comment by minggo** [comment]
Will you please refactor it?

**Comment by JohnCoconut** [comment]
> Will you please refactor it?

Sure.

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
