### PR TITLE
CMake fix for Mac Os X

### PR DESCRIPTION
**Pull request by iSevenDays**

### CODE REVIEW

**Comment by minggo** [comment]
Thanks @iSevenDays .
How can i test it?

**Comment by iSevenDays** [comment]
You can download CLion(free for 60 days) and open project with it. 
And you need somebody with Mac Os X.

If you want, I can send you a cmake log, or screenshot if you don't have a testers with Mac Os.

**Comment by minggo** [comment]
Thanks, i will test it.
I am using Mac OS X.

**Comment by iSevenDays** [comment]
I've finished porting project template for iOS/Mac Os( before I've only ported cocos2d-x ). I will update this commit.

**Pull request merged**
