### PR TITLE
Simplified the way to bind callbacks from Cocostudio

### PR DESCRIPTION
**Pull request by TheCodez**
This change simplifies the way callbacks can be handled from Cocostudio. Instead of registering a new node reader you just call CSLoader::createNodeWithRoot with the desired target rootnode. Additionally, I've added three macros to simplify the process of binding your custom events.

this :

``` c++
if (callBackName == "onClick")
{
        return CC_CALLBACK_1(CustomRootNode::onClick, this);
}
```

becomes this :

``` c++
CCS_CLICK_CALLBACK_GLUE(this, "onClick", CustomRootNode::onClick)
```

### CODE REVIEW

**Comment by chengstory** [comment]
Thanks @minggo  @TheCodez ,  I ask @pipu to take a look.

**Comment by TheCodez** [comment]
This is pretty much the same as in this pr : https://github.com/cocos2d/cocos2d-x/pull/10403
But a bit simpler and with extra macros.

**Comment by TheCodez** [comment]
@chengstory @pipu any news?

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
