### PR TITLE
Rewrote all action ease classes to remove the redundancy of having a …

### PR DESCRIPTION
**Pull request by Jakz**
…single class definition for every possible ease function. This has been done through some template classes which accept functions as arguments.

This makes both header and source file much shorter and much more maintanable. Readability shouldn't be a concern since now there is almost no code to read.

Performance should identical since everything is bound at compile time. The following patch should be compatible with all recent (C++11) compilers but I have no way to test it, I tested it on LLVM3.4 on a OS X machine.

This patch also gives the possiblity to have ready to go custom ease function without the need to sublass ActionEase at all (as long as the prototype of the function is supported).

### CODE REVIEW

**Comment by ricardoquesada** [comment]
+1

BTW, are you developing things for the Commodore?

**Comment by Jakz** [comment]
not anymore unfortunately :(

**Comment by pandamicro** [comment]
Thanks @Jakz , looks like a great PR,
As it's a big and important PR, I will ask more people to review it
@minggo @WenhaiLin @VisualSJ Can you please help review it ?

For now, it can't help the Jenkins build, can you give a look at the error messages and try to fix the platforms that you can test ?

**Comment by minggo** [comment]
It looks good to me, but i am not sure if it will bring troubles to script bindings.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@Jakz  This patch is great, but it can't work with Javascript and Lua binding.

**Comment by ricardoquesada** [comment]
@zilongshanren what are the issues with the bindings? could those be fixed? thanks.

**Comment by zilongshanren** [comment]
@ricardoquesada  I haven't taken a look at the details. I will check it later and post my findings.

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@dabingnn @yangws If you guys have time, please take a look at this PR too

**Comment by yangws** [comment]
[ci rebuild]

**Comment by yangws** [comment]
It seems all good, and i run ActionEase Test on Mac OK. But ci built failed.
@pandamicro

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@Jakz Hi, can you verify why the ci build failed ? Here is the error of Android platform:

CCActionEase.h:132:21: error: expected unqualified-id before ')' token
EaseTemplate<F>() { }

Besides, we can't bind template functions now into JSB and Lua, so I think we should find a way before this can be merged.

**Comment by minggo** [comment]
@Jakz Could you please fix conflict? And i will take a look if i can fix bindings.

**Comment by minggo** [comment]
it is fixed

**Pull request closed without merging**
