### PR TITLE
beauty cmake format, reduce duplicate defines 

### PR DESCRIPTION
**Pull request by drelaptop**

### CODE REVIEW

**Comment by drelaptop** [comment]
many cmake files modified but little kind of changes occur, please merge @minggo

**Comment by minggo** [comment]
please fix CI error

**Comment by drelaptop** [comment]
@minggo the only one CI task failed is  `linux_cocos_new_test`, the reason is some cmake module files are renamed, but `cocos new` didn't copy them, it need __cocos robot__ to update the cocos files later.

Why I rename custom cmake module files? it make the cmake module files more clear. easy to find the custom modules, now files like:
```
.
├── Modules
│   ├── CocosBuildHelpers.cmake
│   ├── CocosBuildModules.cmake
│   ├── CocosBuildSet.cmake
│   ├── CocosCompileOptions.cmake
│   ├── CocosPickLibs.cmake
│   ├── CocosSelectModule.cmake
│   ├── CocosUseLibs.cmake
│   ├── FindChipmunk.cmake
│   ├── FindFMOD.cmake
│   ├── FindFontconfig.cmake
│   ├── FindGLFW3.cmake
│   ├── FindGTK3.cmake
│   ├── FindMINIZIP.cmake
│   ├── FindMPG123.cmake
│   ├── FindOgg.cmake
│   ├── FindRecast.cmake
│   ├── FindSQLite3.cmake
│   ├── FindTinyXML2.cmake
│   ├── FindVorbis.cmake
│   ├── FindWEBSOCKETS.cmake
│   ├── FindWebP.cmake
│   ├── Findflatbuffers.cmake
│   ├── Findxxhash.cmake
│   └── iOSBundleInfo.plist.in
├── README.md
└── ios.toolchain.cmake
```

**Comment by minggo** [comment]
Then you should modify the cocos console, and update the submodule in this PR. Any PR should pass the CI before being merged.

**Comment by drelaptop** [comment]
fixed, merge please @minggo

**Pull request merged**
