### PR TITLE
Fix crash on Windows if pass string more than 16kb to cocos2d::log.

### PR DESCRIPTION
**Pull request by Dimon4eg**
Fixed two issues if pass string bigger 16kb to cocos2d::log:
- crash on Windows
- string is cut in output of Visual Studio

Tested on Windows, Android and iOS.

### CODE REVIEW

**Comment by zilongshanren** [comment]
Thanks, @Dimon4eg 
I found that you put two fixes in the same PR which is not good.
I have opened a issue for adding setTitleAlignment for ui::Button here https://github.com/cocos2d/cocos2d-x/issues/9633
I suggest you to open another PR and link your PR with the issue I listed above.

Thanks.

**Comment by Dimon4eg** [comment]
Sorry, I should create branch for each task.

**Comment by zilongshanren** [comment]
@Dimon4eg You should create another topic branch and isolate your changes only in that branch.

**Comment by Dimon4eg** [comment]
Thanks, but what do now?

**Comment by zilongshanren** [comment]
@Dimon4eg 
Try `git reset --hard HEAD~1` and `git push origin v3 --force`.

Or you could just close this PR and create another two topic branch and cherry-pick the commits in this branch.

The later option is safer, the first option might lose data. Do it carefully...

**Pull request closed without merging**
