### PR TITLE
refactor cmake copy res, fix #18813

### LINKED ISSUE #18813: Problem with resource copying on linux
- cocos2d-x version:git
- devices test on: linux mint 18.3
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Build game on linux.
2. Change  some resource files.
3. Build again, and resources will NOT be updated.

What could be a problem?

### PR DESCRIPTION
**Pull request by drelaptop**
Using `configure_file(<input> <output> COPYONLY)` to copy res files, instead of custom command.
fix #18813 

### Refer to:
https://stackoverflow.com/questions/34799916/cmake-copy-file-from-source-directory-to-binary-directory
> Unlike file(COPY ...) it creates a file-level dependency between input and output, that is:
> If the input file is modified the build system will re-run CMake to re-configure the file and generate the build system again.

### CODE REVIEW

**Comment by v1993** [comment]
Now it updates changed files (thanks for that!), but removed files isn't removed.

It isn't critical, but still is a problem.

**Comment by drelaptop** [comment]
What means __removed files isn't removed.__ could you describe it in detail. or make a example @v1993

**Comment by v1993** [comment]
Oh my god, my poor logic…
I meant that if I remove file from resources (project) it will not be removed from target directory (build).

**Comment by drelaptop** [comment]
I don't know if CMake existed any policy support this feature you want.

As you said, it isn't critical. we can try to improve this later.

**Comment by crazyhappygame** [comment]
I think that we should not copy resources at all. Runtime should just load resources from proper location.

**Comment by v1993** [comment]
@crazyhappygame It makes harder distributibg game to testers and move to another location/computer. Also, it requires separated commands for deploy/compile and run. It doesn't make any sence for packages (android/iOS/macOS).

So I think that small results requires a lot of work.

**Comment by crazyhappygame** [comment]
@v1993 what do you think about following
Resources - original source location
bin - new folder with libs, binaries

And for deploy you have one command: "copy bin, Resource" folders

Resources are always loaded from relative path ../Resources/.....

**Comment by crazyhappygame** [comment]
@v1993 there is also symlink option:
http://qrikko.blogspot.com/2016/05/cmake-and-how-to-copy-resources-during.html?m=1

**Comment by v1993** [comment]
@crazyhappygame Symlink sounds interesting… So we can use this pull request for deploy and symlinks for different builds. APK still sounds like a problem: we can't pack symlink.

**Comment by v1993** [comment]
@minggo Can you merge this into main branch, please? It is important for my project.

**Comment by drelaptop** [comment]
the PR improve the way of  cmake copy res, please merge into v3 @minggo

**Pull request merged**
