### PR TITLE
Better handling of invalid shaders.

### PR DESCRIPTION
**Pull request by AIGRIND-LLC**
If shader is invalid the programm will be crashed.
The better way is to rise an assert and write message to the error log.
Platform: Windows
Explain: Functions in glew32.dll have non-standard call conversion. Typecast (GLInfoFunction) is invalid.

### CODE REVIEW

**Comment by dumganhar** [comment]
> Functions in glew32.dll have non-standard call conversion. Typecast (GLInfoFunction) is invalid.
> But it was built successfully on Win32 without this patch.

How to reproduce the issue?

**Comment by AIGRIND-LLC** [comment]
1. First you need to make some invalid shader. For example you may corrupt existed shader (%cocos2dx%\samples\Cpp\TestCpp\Resources\Shaders\example_Monjori.fsh). 
2. Next run TestCpp sample and open "ShaderTest" menu.
3. If there is no our fix the application will crash without any log message.
   If you apply our fix the shader content and error message will be pushed into the log.

**Comment by dumganhar** [comment]
OK, I will check it .Thanks.

**Comment by cocosQA** [comment]
Dear AIGRIND-LLC:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6463
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
