### PR TITLE
Fixes the font rendering on Windows

### PR DESCRIPTION
**Pull request by seagullua**
When font was rendered the black pixels used to appear around the letters. This patch fixes this issue

### CODE REVIEW

**Comment by seagullua** [comment]
Labels zoomed 300%
cocos2d-bug

**Comment by sergey-shambir** [comment]
After this patch, is blurred area white or semi-transparrent? In other words, would it look normally at black surface?

**Comment by seagullua** [comment]
Yes it is semi-tranparrent.

**Comment by seagullua** [comment]
untitled-3

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
