### PR TITLE
CCUserDefault.cpp: Should not compile on Mac platform

### PR DESCRIPTION
**Pull request by wefiends**
On the Mac, the CCUserDefault.mm implementation should be used (it already checks for the Mac platform). That way NSUserDefaults can be used.

On a related note, why is KEEP_COMPATABILITY defined at the top of CCUserDefault.mm? Will this be removed in future releases? Otherwise, the only way to use NSUserDefaults is to remove the define. Should this setting be moved to Configuration or ccConfig?

### CODE REVIEW

**Comment by minggo** [comment]
Yep, i think we can remove it now.

**Comment by minggo** [comment]
KEEP_COMPATABILITY is used for the purpose
- in previous we use xml to save data for all platforms
- then we use system API to record data on iOS and on Android, because using xml may lost data

**Comment by minggo** [comment]
So we use this macro just for the users that update from older version, may be v2.1.x.

**Comment by minggo** [comment]
I think it is reasonable to move the macro to `ccConfig.h`.

**Comment by minggo** [comment]
What's suitable macro name for it?

**Comment by wefiends** [comment]
Maybe CC_ENABLE_NATIVE_USERDEFAULT and set it enabled by default. You want me to send you a PR?

**Pull request merged**
