### PR TITLE
Added OGG support to winrt audio

### PR DESCRIPTION
**Pull request by anniruddh**
-- Winrt new audio engine now supports ogg files.
-- Fixed issue #150 (https://github.com/MSOpenTech/cocos2d-x/issues/150)
-- Fixed issue #151 (https://github.com/MSOpenTech/cocos2d-x/issues/151)

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by stammen** [comment]
This pull request require https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin to be tagged version v3-deps-62.

**Comment by zilongshanren** [comment]
@stammen  thanks, I will create v3-deps-62

**Comment by stammen** [comment]
@andyque Thanks. I just pushed the updated version of config.json. It is updated to v3-deps-62.

**Comment by zilongshanren** [comment]
@stammen  v3-deps-62 is ready.

**Comment by stammen** [comment]
Thanks for your help.

**Comment by stammen** [comment]
@andyque  It looks like there is a stuck build on the cocos build system

Started 17 hr ago
Build has been executing for 17 hr on master
Progress:  
In progress Build #1346 (Jun 7, 2015 11:44:16 AM)

**Comment by zilongshanren** [comment]
@stammen  The two slaves in our US office are down. I have told the staff here to resolve this issue.

**Comment by stammen** [comment]
@ricardoquesada @minggo @andyque please rebuild. The mac/ios build system has been offline/gone offline each time this pull request attempts to build.

**Comment by anniruddh** [comment]
Built successfully this time.

**Pull request merged**
