### PR TITLE
Fixed compile-errors the 'extensions' when CC_USE_PHYSICS is 0.

### PR DESCRIPTION
**Pull request by syrokomskyi**

### CODE REVIEW

**Comment by dumganhar** [comment]
Which platform are you testing?
I tested it with XCode ios and mac port. And there are not any problems.

**Comment by syrokomskyi** [comment]
Do you tested with CC_USE_PHYSICS = 0?
Win32, VS2012.

**Comment by dumganhar** [comment]
@signmotion , Thank you. I will test it .

**Comment by syrokomskyi** [comment]
Thanks for the excellent engine powered by C++11.

**Comment by WenhaiLin** [comment]
@signmotion I tested it on vs2012,and it's no problem,not have compile-errors .

**Comment by syrokomskyi** [comment]
1. Project libcocos2d / include / ccConfig.h.
   #define CC_USE_PHYSICS 0
2. Project libExtensions / Properties / C++ / Preprocessor.
   CC_ENABLE_CHIPMUNK_INTEGRATION=0
   CC_ENABLE_BOX2D_INTEGRATION=0
3. Compile and result: methods of the PhysicsSprite is not feasible.

With proposed fix we may have "libExtensions.lib" without physics. IMHO, it's good solution, because "libExtensions" consist of not only physics.

**Comment by WenhaiLin** [comment]
@signmotion I fixed at https://github.com/cocos2d/cocos2d-x/pull/5045.The CC_USE_PHYSICS not associated with two other  macros.it is new macro.

**Comment by syrokomskyi** [comment]
Good.

**Pull request closed without merging**
