### PR TITLE
Improve StringUtils::format implementation.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by summerinsects** [comment]
I suggest calling `shrink_to_fit` before return

**Comment by halx99** [comment]
I don't think so, the shrink_to_fit maybe trigger memory reallcoate & copy.

**Comment by drelaptop** [comment]
@halx99 https://github.com/cocos2d/cocos2d-x/issues/18724 is a `StringUtils::format` issue, would you like to solve that? I think this PR and that issue is related.

**Comment by halx99** [comment]
@drelaptop ok, let me see.

**Pull request merged**
