### PR TITLE
Updates gradle relevant files for Android Studio 3.0.0.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by madebymozart** [comment]
@dumganhar is this PR to replace https://github.com/cocos2d/cocos2d-x/pull/18470 ?

**Comment by Anywhere-Music-Player** [comment]
Yea, thats strange why duplicate it..

**Comment by madebymozart** [comment]
It's also not targeting the latest version of the build tools (27.0.1) and not using `c++_static`. I am currently updating PR #18470 to do this

**Comment by dumganhar** [comment]
Yep. it's duplicated. i didn't notice that PR before sending this one. Close this one.

**Pull request closed without merging**
