### PR TITLE
Fixing linking errors for TestCPP with libcurl

### PR DESCRIPTION
**Pull request by gelldur**
Topic: http://www.cocos2d-x.org/boards/23/topics/26702?r=26820

### CODE REVIEW

**Comment by gelldur** [comment]
That was removed in this commit https://github.com/cocos2d/cocos2d-x/commit/66376b4011d04ecf94943a85f419e459be8a5f85 

Probably other projects need add this too.

**Comment by rtissera** [comment]
Got this issue too, I can confirm this PR fixes it building on Ubuntu 12.10 i386 (at least).
Please merge ;)

**Comment by gelldur** [comment]
I have Xubuntu 12.04 32 bit

**Comment by rtissera** [comment]
Please merge into 2.1.3, thanks !

**Pull request merged**
