### PR TITLE
Added TMX polygon parsing.

### PR DESCRIPTION
**Pull request by NatWeiss**
This parses a TMX file's polygon node into a CCArray of CCDictionary objects containing a x and y keys.

### CODE REVIEW

**Comment by NatWeiss** [comment]
I used autorelease for the CCString objects to keep it the same as the above code for parsing an x and y value for an object. However, wouldn't it be better if they were all using release instead? If so, I can submit another pull request.

**Comment by minggo** [comment]
@NatWeiss
Yep, release is better than autorelease here.

**Comment by minggo** [comment]
@NatWeiss
Would you add TMX polyline parsing too?

**Comment by NatWeiss** [comment]
Yep.

**Pull request merged**
