### PR TITLE
Update CSLoader.cpp

### PR DESCRIPTION
**Pull request by slug404**
path根本就没使用

### CODE REVIEW

**Comment by chengstory** [comment]
I ask @pipu to take a look.

**Comment by minggo** [comment]
@chengstory 
Any update?

**Comment by pipu** [comment]
@minggo 
@chengstory 
Cocos2d-x current version doesn't have method nodeFromProtocolBuffersFile() in CSLoader.cpp, which this commit "Update CSLoader.cpp"" mentioned in this pull request.

**Comment by minggo** [comment]
Got it.
So this pull request is out dated.
Thanks.

**Pull request closed without merging**
