### PR TITLE
Speed up windows build

### PR DESCRIPTION
**Pull request by Dimon4eg**
Huge speed up build on windows!

Project | was | now (with pch) | Speed up (times)
-- | -- | -- | --
libcocos2d | 0:22:46 | 0:01:51 | 12
libjscocos2d | 0:01:02 | 0:00:23 | 3
cpp test | 0:03:00 | 0:01:01 | 3

Time format is hh:mm:ss

I configured precompiled headers for Visual Studio projects.

I don't have Mac to do same in XCode.

### CODE REVIEW

**Comment by crazyhappygame** [comment]
Impressive! 
In appveyor https://ci.appveyor.com/project/minggo/cocos2d-x/history I see speedup 31:23 vs 12:49. 

Few questions:
1. It seems like some project from cocos2d-win32.sln do not have precompiled headers (there is still 12:49 for cocos2d-win32.sln)
`& msbuild $env:APPVEYOR_BUILD_FOLDER\build\cocos2d-win32.sln /t:Build /p:Platform="Win32" /p:Configuration="Release" /`m
2. Could you enable pch for android?
3. Could you enable pch after cmake:
https://github.com/cocos2d/cocos2d-x/pull/18646
http://discuss.cocos2d-x.org/t/in-progress-cmake-support-all-platform-for-cocos2d-x/41164/2
It seems like than it will be enough to do it in one place and have for all platforms.

**Comment by Dimon4eg** [comment]
1. I configured cocos2d VS project for all configurations.
It's slower on appveyor because each time it downloads sources, dependencies and after builds.
2. Tried to do same for android but without success.
3. I don't know cmake.

**Comment by crazyhappygame** [comment]
1. In cocos2d-win32.sln  I see:
```
"cpp-tests", "..\tests\cpp-tests\proj.win32\cpp-tests.vcxproj"
"lua-tests", "..\tests\lua-tests\project\proj.win32\lua-tests.win32.vcxproj"
"cpp-empty-test", "..\tests\cpp-empty-test\proj.win32\cpp-empty-test.vcxproj"
"lua-empty-test", "..\tests\lua-empty-test\project\proj.win32\lua-empty-test.vcxproj"
"libcocos2d", "..\cocos\2d\libcocos2d.vcxproj"
"libluacocos2d", "..\cocos\scripting\lua-bindings\proj.win32\libluacocos2d.vcxproj"
"libjscocos2d", "..\cocos\scripting\js-bindings\proj.win32\libjscocos2d.vcxproj"
"js-tests", "..\tests\js-tests\project\proj.win32\js-tests.vcxproj"
"performance-tests", "..\tests\performance-tests\proj.win32\performance-tests.vcxproj"
"game-controller-test", "..\tests\game-controller-test\proj.win32\game-controller-test.vcxproj"
"cpp-tests", "..\tests\cpp-tests\proj.win32\cpp-tests.vcxproj"
"lua-tests", "..\tests\lua-tests\project\proj.win32\lua-tests.win32.vcxproj"
"cpp-empty-test", "..\tests\cpp-empty-test\proj.win32\cpp-empty-test.vcxproj"
"lua-empty-test", "..\tests\lua-empty-test\project\proj.win32\lua-empty-test.vcxproj"
"libcocos2d", "..\cocos\2d\libcocos2d.vcxproj"
"libluacocos2d", "..\cocos\scripting\lua-bindings\proj.win32\libluacocos2d.vcxproj"
"libjscocos2d", "..\cocos\scripting\js-bindings\proj.win32\libjscocos2d.vcxproj"
"js-tests", "..\tests\js-tests\project\proj.win32\js-tests.vcxproj"
"performance-tests", "..\tests\performance-tests\proj.win32\performance-tests.vcxproj"
"game-controller-test", "..\tests\game-controller-test\proj.win32\game-controller-test.vcxproj"
```
Some of those vcxproj  (i.e. performance-tests) were not update and have lots of cpp files...

**Comment by crazyhappygame** [comment]
ad2.  For android I tried once as well but for me gcc+pch=failure. Latest cocos2d-x switch to clang for android there is chance that it will work.

**Comment by Dimon4eg** [comment]
I added pch to projects with big amount of C++ files

**Comment by crazyhappygame** [comment]
@minggo could you merge it?

**Pull request merged**
