### PR TITLE
fixed bug of binding of class "Spawn"

### PR DESCRIPTION
**Pull request by SunLightJuly**

### CODE REVIEW

**Comment by samuele3hu** [comment]
This binding wrote like this was to support v2.x.

**Comment by SunLightJuly** [comment]
But in the original codes, the function "extendSpawnDeprecated()" is never be called, why? Some users maybe want to use "cc.Spawn:createWithTwoActions()".

**Comment by samuele3hu** [comment]
Yes,"extendSpawnDeprecated()" was called is a bug.From 3.x, we should call "cc.Spawn:create(action1,action2)" instead of "cc.Spawn:createWithTwoActions()"

**Comment by SunLightJuly** [comment]
OK，got it.

**Pull request closed without merging**
