### PR TITLE
Add test wrap unicode text

### PR DESCRIPTION
**Pull request by Dimon4eg**
Added test for verifying unicode text wrap:
image

### CODE REVIEW

**Comment by Dimon4eg** [comment]
[CI REBUILD]

**Comment by Dimon4eg** [comment]
[ci rebuild]

**Comment by drelaptop** [comment]
seems like script errors occur on AppVeyor, a little strange
```
git checkout -qf FETCH_HEAD
./tools/appveyor-scripts/before-build.ps1
git.exe : Submodule 'tests/cpp-tests/Resources/ccs-res' (git://github.com/dumganhar/ccs-res.git) registered for path 'tests/cpp-tests/Resources/ccs-res'
At C:\projects\cocos2d-x\tools\appveyor-scripts\before-build.ps1:77 char:2
+     & git submodule init
+     ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Submodule 'test...ources/ccs-res':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Submodule 'tools/bindings-generator' (git://github.com/cocos2d/bindings-generator.git) registered for path 'tools/bindings-generator'
Submodule 'tools/cocos2d-console' (git://github.com/cocos2d/cocos2d-console.git) registered for path 'tools/cocos2d-console'
Submodule 'web' (git://github.com/cocos2d/cocos2d-html5.git) registered for path 'web'
git.exe : Cloning into 'C:/projects/cocos2d-x/tests/cpp-tests/Resources/ccs-res'...
At C:\projects\cocos2d-x\tools\appveyor-scripts\before-build.ps1:78 char:2
+     & git submodule update --recursive
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into 'C...ces/ccs-res'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Cloning into 'C:/projects/cocos2d-x/tools/bindings-generator'...
Cloning into 'C:/projects/cocos2d-x/tools/cocos2d-console'...
Cloning into 'C:/projects/cocos2d-x/web'...
```

**Comment by Dimon4eg** [comment]
[ci rebuild]

**Comment by drelaptop** [comment]
unicode test

test success on win32 compiled by vs2015,  this PR add res folder: `strings/`, this should been added into Xcode project references. suggest merge @minggo

**Pull request merged**
