### PR TITLE
getAllTouches() in GLViewProtocol

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by minggo** [comment]
The error is caused by lua binding. It can not automatically binding std::vect<Touch>.
We will fix it based on this PR, then merge it.

Thanks.

**Comment by minggo** [comment]
@samuele3hu
Could you continue the work:
- fix conflict
- fix lua-binding issue

Thanks.

**Comment by newnon** [comment]
i will fix conflict but i have no idea how to fix lua binding issue

**Comment by minggo** [comment]
@samuele3hu
Could you please fix lua-binding issue?
Thanks.

**Comment by newnon** [comment]
Sorry i don't know how.

**Comment by minggo** [comment]
@newnon 
I asked @samuele3hu 's help.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
It is fixed in #7951.

**Pull request merged**
