### PR TITLE
Updating the following:

### PR DESCRIPTION
**Pull request by dducharme**
CocosDenshion - now using OpenAL exclusively for audio, added ogg/vorbis support there
Accelerometer - fixing the accelerometer for different initial orientations of the device
Application - paying attention to the locale of the device and setting the current language accordingly
CCEGLView - paying attention to navigator events (menu, application go to background, application enters foreground), fixed up orientation code, fixed up screen event pointer code

### CODE REVIEW

**Comment by minggo** [comment]
There is an ogg file in tests/Res, could you use it and not add background.ogg?
I think we it it better to keep cocos2d-x as small size as possible.

**Comment by dducharme** [comment]
The cocosdenshion test would then not play any sound for the background.  I guess we could change it to some other wav file that could act as a background?

**Comment by dumganhar** [comment]
Hi, dducharme,
Is mp3 format not supported in OpenAL? Does it just support wav format? I notice ogg file need to be decoded to pcm buffer.

**Comment by dducharme** [comment]
It doesn't.  OpenAL only supports pcm audio. 

----- Original Message -----

**Pull request merged**
