### PR TITLE
Initial example working version of a lua project generator

### PR DESCRIPTION
**Pull request by ciaranj**
Hiyah.  This pull requests provides an example ant build script and associated template file for generating adhoc lua projects, it doesn't currently use 'HelloLua' (for purely historic/organic reasons) .. it would perhaps be better if it did..but it doesn't.. although I suspect it would be easy enough to re-point it at the HelloLua project.

What do you think?

### CODE REVIEW

**Comment by minggo** [comment]
Could you please write a README to describe the purpose of it, and the usage?

**Comment by ciaranj** [comment]
Sure.  'ant' again :).  the file exposes its own description but I'll add a readme too :)

**Comment by minggo** [comment]
Thank you.
Could you also write a document in http://www.cocos2d-x.org/projects/cocos2d-x/boards/11 to describe it and the lua binding. Then more people will notify it and share it.

**Comment by ciaranj** [comment]
Okey-dokey :) will do

**Comment by ciaranj** [comment]
Ok. This is done :)  And as requested, posted a link here: http://www.cocos2d-x.org/boards/11/topics/3957

**Comment by minggo** [comment]
Does it copy all the files into tools/lua_project_generator/template?
If the cocos2dx modify it's code, can this template work ok?

**Comment by ciaranj** [comment]
No, sadly at the minute it doesn't.  It is separate from HelloLua (HelloLua had 'too much').   I think that that would be a sensible move forward at some point though ?

**Comment by minggo** [comment]
Yes, thank you.

**Pull request merged**
