### PR TITLE
Spine updated

### PR DESCRIPTION
**Pull request by newnon**
Spine runtime updated to last version
- IK Support
- flip support
- several bug fixes & improvements

### CODE REVIEW

**Comment by dabingnn** [comment]
@newnon Thanks, could you please add the version of spine in this PR?

**Comment by newnon** [comment]
I cant find version it is based on commit b3b3b25a83d27e6e1c4b6ae64b7d15dcfefda6fe

**Comment by minggo** [comment]
I think we should use a stable version.

**Comment by newnon** [comment]
it is stable they changed a little their politics, every time you need to take last version from git you can see there http://en.esotericsoftware.com/spine-runtimes.

**Comment by newnon** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@newnon 
Sorry, i don't understand what you said: `it is stable they changed a little their politics, every time you need to take last version from git`.

Now, i can find in spine runtime repo, the latest version is v2.1.08: https://github.com/EsotericSoftware/spine-runtimes/tree/2.1.08.

**Comment by newnon** [comment]
Ok you are right i forgot about tags, it is runtime version 2.1.08 there is no changes from 2.1.08 to b3b3b25a83d27e6e1c4b6ae64b7d15dcfefda6fe that change something for c or cocos part of sources

**Comment by minggo** [comment]
@newnon 
So it is v2.1.08?

**Comment by dabingnn** [comment]
@newnon
Thanks for your pull request, but I found the commit is not a stable version in official runtime.
This pull request will be closed, thanks again.

**Pull request closed without merging**
