### PR TITLE
rename some class names to obey cocos2d-x coding style

### PR DESCRIPTION
**Pull request by minggo**
AccelerometerEvent -> EventAccelerometer
TouchEvent -> EventTouch
KeyboardEvent -> EventKeyboard
CustomEvent -> EventCustom

AccelerometerEventListener -> EventListenerAccelerometer
TouchEvent -> EventListenerTouch
KeyboardEvent -> EventListenerKeyboard
CustomEvent -> EventListenerCustom

### CODE REVIEW

**Comment by dumganhar** [comment]
Do the file names also need to be renamed?
- James

**Comment by minggo** [comment]
I think it is not needed now.

**Comment by dumganhar** [comment]
OK, but it looks a little strange.
- James

**Comment by walzer** [comment]
Well, do we have enough time to rename files?

**Comment by dumganhar** [comment]
Sorry, I am at my hometown.And you know there are lots of things to be
done. But if i have time ,i will try to do it.
- James

**Pull request merged**
