### PR TITLE
extend the RichText

### PR DESCRIPTION
**Pull request by m-yukio**
This is a PR to extend the RichText.
- Set of default values.
- Append to ability to extend the tags.
- Add the effect of outline, shadow and glow.
- Catch a event of open url.
- Anchor of the image tag.

I have consulted the arguments for the initialization function of RichElementText.
By this time of expansion, the number of arguments of the init() and create() has increased (8 -> 11). The increase was the argument made to have a default value, you have to maintain compatibility, but you will not be able to be only part of the growing argument.
For example, I think that the argument is ValueMap or the structure, but when it will change, it will affect compatibility.
If there is good correspondence way, will not you tell me?

### CODE REVIEW

**Comment by m-yukio** [comment]
[ci rebuild]

**Comment by m-yukio** [comment]
Using the API example

``` C++
    static char str[] =
    "<span>"
    "Plain Text<br />"
    "<font color=\"#006600\" face=\"Marker Felt.ttf\" size=\"24\">Set to color and font name, size.</font><br />"
    "<img src=\"CloseNormal.png\" /><br />"
    "<a href=\"http://www.cocos2d-x.org/\">Anchor(cocos2d-x)</a><br />"
    "<a href=\"scene://id1234\">scene(id1234)</a><br />"
    "<a href=\"http://blog.cocos2d-x.org/\"><img src=\"CloseNormal.png\" /></a><br />"
    "<a href=\"https://github.com/cocos2d/cocos2d-x\"><font size=\"18\" color=\"#7fffd4\" face=\"ipaexm.ttf\">Anchor(Set to size and color, font name)</font></a><br />"
    "<CloseNormal /><br />"
    "<CloseSelected></CloseSelected><br />"
    "<b>Bold</b><br />"
    "<i>Italic</i><br />"
    "<del>Del (Strikethrough)</del><br />"
    "<small>Small</small><br />"
    "<big>Big</big><br />"
    "<outline color=\"#D2B48C\" size=\"4\">OUTLINE</outline><br />"
    "<shadow color=\"#4169E1\" offsetWidth=\"8\" offsetHeight=\"-8\" blurRadius=\"2\">SHADOW</shadow><br />"
    "<glow color=\"#AFEEEE\">GLOW</glow><br />"
    "</span>";
    string xml(str);

    /* Tag extension */
    RichText::setTagDescription("CloseNormal", false, [](const std::map<std::string, std::string>& tagAttrMap, std::map<std::string, std::string>& attrValueMap, RichElement** richElement) {
        attrValueMap.clear();
        *richElement = RichElementImage::create(0, Color3B::WHITE, 255, "CloseNormal.png");
    });
    RichText::setTagDescription("CloseSelected", false, [](const std::map<std::string, std::string>& tagAttrMap, std::map<std::string, std::string>& attrValueMap, RichElement** richElement) {
        attrValueMap.clear();
        *richElement = RichElementImage::create(0, Color3B::WHITE, 255, "CloseSelected.png");
    });

    /* Defaults */
    ValueMap defaults;
    defaults[RichText::KEY_FONT_COLOR_STRING] = "#FFF";
    defaults[RichText::KEY_FONT_SIZE] = 24.0f;
    defaults[RichText::KEY_FONT_FACE] = "ipaexm.ttf";
    defaults[RichText::KEY_ANCHOR_FONT_COLOR_STRING] = "#f0f8ff";
    defaults[RichText::KEY_ANCHOR_TEXT_BOLD] = false;
    defaults[RichText::KEY_ANCHOR_TEXT_ITALIC] = false;
    //defaults[RichText::KEY_ANCHOR_TEXT_LINE] = RichText::VALUE_TEXT_LINE_NONE;
    //defaults[RichText::KEY_ANCHOR_TEXT_LINE] = RichText::VALUE_TEXT_LINE_DEL;
    defaults[RichText::KEY_ANCHOR_TEXT_LINE] = RichText::VALUE_TEXT_LINE_UNDER;
    //defaults[RichText::KEY_ANCHOR_TEXT_STYLE] = RichText::VALUE_TEXT_STYLE_NONE;
    defaults[RichText::KEY_ANCHOR_TEXT_STYLE] = RichText::VALUE_TEXT_STYLE_OUTLINE;
    //defaults[RichText::KEY_ANCHOR_TEXT_STYLE] = RichText::VALUE_TEXT_STYLE_SHADOW;
    //defaults[RichText::KEY_ANCHOR_TEXT_STYLE] = RichText::VALUE_TEXT_STYLE_GLOW;
    defaults[RichText::KEY_ANCHOR_TEXT_OUTLINE_COLOR] = "#D2B48C";
    defaults[RichText::KEY_ANCHOR_TEXT_OUTLINE_SIZE] = 4;
    defaults[RichText::KEY_ANCHOR_TEXT_SHADOW_COLOR] = "#4169E1";
    defaults[RichText::KEY_ANCHOR_TEXT_SHADOW_OFFSET_WIDTH] = 4.0f;
    defaults[RichText::KEY_ANCHOR_TEXT_SHADOW_OFFSET_HEIGHT] = -4.0f;
    defaults[RichText::KEY_ANCHOR_TEXT_SHADOW_BLUR_RADIUS] = 0;
    defaults[RichText::KEY_ANCHOR_TEXT_GLOW_COLOR] = "#AFEEEE";

    /* create RichText */
    _richText = RichText::createWithXML(xml, defaults, [](const string& url) {
        if (regex_search(url, regex("^scene:"))) {
            /* Scene transition */
        }
        else {
            Application::getInstance()->openURL(url);
        }
    });

    const cocos2d::Size winSize = Director::getInstance()->getWinSize();
    _visibleSize.setSize(winSize.width - 24.0 , winSize.height - 24.0);

    auto layer = LayerColor::create(Color4B::GRAY, _visibleSize.width, _visibleSize.height);
    layer->setPosition((Director::getInstance()->getVisibleSize().width - _visibleSize.width) / 2.0,
                       (Director::getInstance()->getVisibleSize().height - _visibleSize.height) / 2.0);

    if (_richText) {
        _richText->ignoreContentAdaptWithSize( false );
        _richText->setVerticalSpace(8.0);
        _richText->setContentSize(_visibleSize);
        _richText->setPosition(layer->getContentSize() / 2.0);

        layer->addChild(_richText);
    }
    this->addChild(layer);
```

richtext

**Comment by m-yukio** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by m-yukio** [comment]
Since I am reviewing, please wait a little.

**Comment by ricardoquesada** [comment]
@m-yukio let me know once the pull request is finished.
also, could you add the sample that you posted inside the PR? 
Having a test case in test-cpp is ideal. thanks.

**Comment by m-yukio** [comment]
Well it noted.
Since it has to fix the JS/Lua bridge portion, please wait a little.

**Comment by m-yukio** [comment]
@ricardoquesada the pull request is finished.
a test case were added to the cpp-tests.

**Comment by ricardoquesada** [comment]
@m-yukio thanks. very useful. I've just tried it, and outline doesn't work. Could you take a look at it?
I tested it on Mac. Attached screenshot:
screen shot 2016-04-19 at 2 34 00 pm

**Comment by m-yukio** [comment]
@ricardoquesada The Outline of the Label is enabled, it seems to have caught the limit of true type font and system font.
Modify to specify the font.

**Comment by m-yukio** [comment]
@ricardoquesada Since I was fixed, please check.

**Comment by ricardoquesada** [comment]
Thanks. It works as expected.
Could you just squash the last commit ? Thanks!

**Comment by m-yukio** [comment]
@ricardoquesada I squashed the last commit.

**Comment by ricardoquesada** [comment]
Thanks. merged!

**Comment by m-yukio** [comment]
Thank you!

**Pull request merged**
