### PR TITLE
Skip UTF8 BOM if it exists before parsing by rapidjson

### PR DESCRIPTION
**Pull request by hanjukim**

### CODE REVIEW

**Comment by dumganhar** [comment]
If BOM was not skipped, what problems will it trigger?

**Comment by hanjukim** [comment]
if BOM was not skipped, json.HasParseError returns true because

```
        switch (stream.Peek()) {
            case '{': ParseObject<parseFlags>(stream, handler); break;
            case '[': ParseArray<parseFlags>(stream, handler); break;
            default: RAPIDJSON_PARSE_ERROR("Expect either an object or array at root", stream.Tell());
        }
```

Above switch case goes to default because of rapidjson can't skip bom (rapidjson supports UTF8 with BOM on their trunk repository though, but it needs extra work. So I decided just skip BOM and pass it to rapidjson. see: https://code.google.com/p/rapidjson/)

**Comment by hanjukim** [comment]
019f3f5 also needs to fixed because error will occur from rapidjson with not properly terminated string

**Comment by dumganhar** [comment]
@hanjukim ,thank you. We will check it soon.

**Comment by minggo** [comment]
@hanjukim
Because we reduce repo size that corrupt the pull request.
Could you re-send the pull request?
Thanks.

**Comment by hanjukim** [comment]
Ok, I will do it soon.

**Pull request closed without merging**
