### PR TITLE
Supports full screen for iPhone X and uses Storyboard for launch screen.

### PR DESCRIPTION
**Pull request by dumganhar**
For developer's project, please follow the steps:
* Copy `LaunchScreen.storyboard` and `LaunchScreenBackground.png` to `proj.ios` or `ios` folder.

d86ac683-e9cb-4dd5-a918-4d3bd281ce94

* Add `LaunchScreen.storyboard` and `LaunchScreenBackground.png` to project, and add them to `Build Phases` -> `Copy Bundle Resource` too.

a362eed6-3de8-47be-8512-529f5ff89fc8

* Set `Launch Screen File` to `LaunchScreen`.

6081272d-e85f-43ba-8a90-e0e783908544

Discussion: http://discuss.cocos2d-x.org/t/iphone-x-slow-transitions-xcode-bug-and-not-full-screen-solved/38942

### CODE REVIEW

**Comment by minggo** [comment]
I think we can remove other background images after testing iOS 6+.

**Comment by dumganhar** [comment]
If we don't care about iOS 6, yes, we could remove them.

**Comment by linshun** [comment]
Remove the old old age and old old platform images.

**Comment by dumganhar** [comment]
- [X] Removes unused LaunchScreen images.
- [X] Updates template projects configuration for iOS.

**Comment by jacket-code** [comment]
I found a bug, I use v3.16 and merge this commit, but the utils::captureScreen is not right, you can see my pic, a half of screen is back, using v3.15.1, I don't have this problem
img_6445

**Comment by wjezxujian** [comment]
How can i do it in the safearea? We must support iOS7!

**Comment by dumganhar** [comment]
@jacket-code , I have no idea of that. Could you upload a demo or code snippet for this issue?

> How can i do it in the safearea? We must support iOS7!

@wjezxujian , as I know, if you wanna you game running on iPhone X, you have to use Storyboard for making a full screen display. 
Currently, iOS7 has few devices and iPhoneX is a big cake.
You could refer to https://developer.apple.com/support/app-store/

screen shot 2017-10-31 at 11 08 39

**Comment by dumganhar** [comment]
@wjezxujian , if setting deployment target to 7.0 and run your game in Xcode 9, you will get this error:

screen shot 2017-10-31 at 11 34 56

So, if you wanna iOS 7 support, go back to Xcode 8, if you wanna the big cake of iPhoneX, go to use Xcode 9 and forget about iOS7.

**Comment by wjezxujian** [comment]
@dumganhar Our game has been shipped for 2 years。Recently，we need to make new content that for match iphoneX resolution。if it possible our content can be display fully in the safe area of iphoneX?Because some content that can not be displayed in the face id camera。

**Comment by dumganhar** [comment]
@wjezxujian ,  this Pull Request just make your game display in full screen (2436 x 1125) including the area being cut out. 
You have to re-layout your game elements for iPhoneX  in order not to be covered by the camera area.

Currently, Director::getInstance()->getFrameSize() should return 2436x1125 size and Application::getInstance()->getTargetPlatform() return iphone enum. By this two factors, you could indicate it's iPhoneX. And you could hack some code to adjust game UI.

**Comment by ShuraLiu** [comment]
@dumganhar is there any plan to support ios11 safe area? I think it need to rewrite the RootViewController but i have no idera how to make it right

**Comment by wjezxujian** [comment]
@dumganhar,I have no idea，can you give me some suggestion？

**Comment by ShuraLiu** [comment]
@wjezxujian The engine can not deal with safe area in ios11. In my project, i render my scene to rendertexture with our design size, and put the rendertexutre in center of scene. You can have a try.

**Comment by cmqzpp** [comment]
@dumganhar

**Comment by cnbcloud** [comment]
@dumganhar according to the method provided by you,my game launch scene can be displayed in full screen ,but other scenes still have black edges,how can i do it,and i hope you can reply,thanks

**Comment by drelaptop** [comment]
@cnbcloud I think you could refer to safe area at Apple docs
https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

set a full screen background to avoid black edges, and put you UI into safe area.
> please run cpp-empty-test using cocos2d-x 3.17 on iPhone X, to see the full screen background and safe area

**Comment by cnbcloud** [comment]
@drelaptop Thank you for your reply. my problem has been solved, but I have encountered a new problem. the pop-up of the edit box input on iphone x will affect the ui layout.do you have some idea

**Comment by drelaptop** [comment]
@cnbcloud suggest to new a issue, describe it in detail, and it's better to add some screenshot.

**Comment by yuan282828sc** [comment]
为什么  我的项目按照这种方式改了之后 黑屏 打不开了呢？ 求大神指点迷津。。。。。。。。。。。。。

**Pull request merged**
