### PR TITLE
[Windows]Fix edit box spacing and alignment

### PR DESCRIPTION
**Pull request by saumyamukul**
Also prevent a crash inside setText due to invalid cast

### CODE REVIEW

**Comment by minggo** [comment]
@saumyamukul  `100644 → 100755` please don't change the file attributes.

**Comment by minggo** [comment]
@saumyamukul please don't change the file attribute from `100644` to `100755`. You can click the `FileChanges` to check that, the file attribute is changed. And source code files do need execution permission.

**Comment by saumyamukul** [comment]
@minggo Thats for the feedback. I got caught up with other work. I'll fix that soon

**Comment by minggo** [comment]
thanks

**Comment by saumyamukul** [comment]
File attributes have been reset!

**Pull request merged**
