### PR TITLE
fix issue #16921

### PR DESCRIPTION
**Pull request by ricardoquesada**
call setupScale9() always

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@dumganhar should I merge it? or should you test it first?

**Comment by dumganhar** [comment]
I'm testing it now. Please wait a moment.

**Comment by dumganhar** [comment]
@ricardoquesada , I checked it and confirmed that it was fixed by this PR. Thanks.

**Comment by ricardoquesada** [comment]
ok. great. I'll merge it.

**Pull request merged**
