### PR TITLE
remove unneeded codes

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
Please don't merge it.
Just merge it after discussing.

**Comment by ricardoquesada** [comment]
Yes, I know why they are there:

in cocos2d-iphone I added those 2 functions in order to support creating PVR textures in the PVRTexture.m file.

Probable cocos2d-x is using another code to create the PVRTextures, so it might not be needed in cocos2d-x.

**Comment by minggo** [comment]
No. 
cocos2d-x doesn't support creating PVR textures from a file.

But if even we want to support this feature, the logical codes is wrong. Because `Texture2D::keepData` just return passed in parameter.

**Comment by minggo** [comment]
I will merge it if there is not problem.

**Pull request merged**
