### PR TITLE
do not change anchor point of child.

### PR DESCRIPTION
**Pull request by litefeel**

### CODE REVIEW

**Comment by sergey-shambir** [comment]
Can you please describe what this change gives?

**Comment by litefeel** [comment]
scrollView->addChild(child) <==> scrollView->getContainer()->addChild(child)

so. `ScrollView::addChild` should not be change anchor point.

**Comment by litefeel** [comment]
why not merge this?

**Comment by minggo** [comment]
Please send pull request to develop branch.
Thanks.

**Comment by litefeel** [comment]
Yes. I send to develop branch. but develop is 3.x , master is 2.x.
so. I think 2.x need too.

**Comment by litefeel** [comment]
develop branch pull request https://github.com/cocos2d/cocos2d-x/pull/3988

**Comment by minggo** [comment]
We only fix critical bug on master because of resource limited. So please don't send pull request to master if it is not a critical bug.

Thanks.

**Comment by litefeel** [comment]
Oh. I see. Please merge #3988 of develop.

**Pull request closed without merging**
