### PR TITLE
You have to pass long pointer for CURLINFO_RESPONSE_CODE.

### PR DESCRIPTION
**Pull request by ledyba**
You should pass long pointer to curl_easy_getinfo when you want to get CURLINFO_RESPONSE_CODE.

``` C+++
  CURLINFO_RESPONSE_CODE    = CURLINFO_LONG   + 2,
```

In 64bit gcc, sizeof(int) == 4 and sizeof(long) == 8, so irrelevant memory area will be overwritten when compiling on 64bit.

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. I will check it.

**Comment by ledyba** [comment]
Thanks.
On Linux 64bit, HttpClient always crashes due to this problem.
In android and iOS, both of them are 32bit platform, so HttpClient do not crash at all.

But, iPhone 5s will be 64 bit platform, so it may cause crash.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/3652 . Thanks. Could you please test the codes on develop branch? Thanks. If no problems, please close this PR.

**Comment by ledyba** [comment]
Thanks！I have checked!

**Pull request closed without merging**
