### PR TITLE
fix issues of textfield

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by Guy-kun** [comment]
This fixes the reported issue in https://github.com/cocos2d/cocos2d-x/issues/20174#issuecomment-550347355 at first signs.
Will say if there's any further bugs after QA

**Comment by minggo** [comment]
@Guy-kun any update?

**Comment by Guy-kun** [comment]
We've confirmed that there seems to be no regression and it's working correctly.

There's one small issue which is:
- On iPadOS (tested on 13.3), using the 'english' mode of the Japanese keyboard defaults to starting the input with a capital letter. (this does not happen for all text fields, such as safari url)
It's a minor issue however, does cocos have an option for this behavior? If not it should likely be forced disabled.

**Comment by minggo** [comment]
Sorry, i don't know how to handle the issue in codes. And it seems it can be resolved by changing iOS devices's settings: https://www.idownloadblog.com/2015/09/18/how-to-keyboard-uppercase-iphone-ipad-ios-9/.

**Comment by Guy-kun** [comment]
This isn’t the same thing, the link is for changing the keyboard display case, the actual issue is auto-capitalization of the first letter which is likely a hint set on the text field itself.
Either way this isn’t a blocking issue as it’s somewhat specific.

**Pull request merged**
