### PR TITLE
Linux: added project part for QtCreator.

### PR DESCRIPTION
**Pull request by sergey-shambir**
Allows easily setup cocos2d on Linux in QtCreator IDE. User can just add 2 strings to `*.pro`, example:

``` c++
COCOS2D_MODULES += extensions box2d CocosDenshion
include(/home/sergey/Applications/cocos2d-x/cocos2dx/proj.linux/cocos2dx.pri)
```

It adds defines, include paths, scans COCOS2D_MODULES to include modules and builds (+links with) shared and static libraries on demand.

I can write wiki page about setup steps, if needed.

### CODE REVIEW

**Comment by dumganhar** [comment]
Yes, it'll be better if there is a wiki page for describing this functionality. Thanks.

**Comment by sergey-shambir** [comment]
There is wiki page: http://www.cocos2d-x.org/projects/cocos2d-x/wiki/QtCreator_project_setup_on_Linux

**Comment by sergey-shambir** [comment]
I'll update it soon to support c++11 and switch to OpenAL by default (since FMOD is free only for non-commercial use).

**Comment by dumganhar** [comment]
Merged. Thanks.

**Pull request merged**
