### PR TITLE
add UIEditBox support linux platform

### PR DESCRIPTION
**Pull request by hanxi**
I think this EditBox is useful. But is not good realize, it use GTK+. Document in here http://blog.hanxi.info/7

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@hanxi  It can't pass the Jenkins CI, please fix it, thanks.

**Comment by hanxi** [comment]
I think need  execute this script `cocos2d-x/build/install-deps-linux.sh`. Because dependens `libgtk-3-dev`.

Or  execute this commond: `sudo apt-get instal libgtk-3-dev`

Error is this:

``` bash
CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find GTK3 (missing: GTK3_LIBRARIES GTK3_INCLUDE_DIRS)
Call Stack (most recent call first):
  cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindGTK3.cmake:54 (find_package_handle_standard_args)
  cmake/Modules/CocosBuildHelpers.cmake:44 (find_package)
  CMakeLists.txt:205 (cocos_find_package)
```

**Comment by zilongshanren** [comment]
@hanxi  I will manually execute the `install-deps-linux.sh` script and rebuilt your PR. thanks.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@hanxi  I will add your patch to v3.9, thanks.

**Comment by hanxi** [comment]
:laughing: :+1:

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/issues/13432

**Comment by WenhaiLin** [comment]
Hi @hanxi I think the pop-up input box should not support minimize and maximize.  

Update: The pop-up input box should be closed automatically after lost focus.

**Comment by hanxi** [comment]
@WenhaiLin Very good suggestions.

**Comment by pandamicro** [comment]
Hi, @hanxi  Jenkins build fails on linux

**Comment by WenhaiLin** [comment]
@hanxi I have squashed your commits and rebase to latest v3.
Here is the new PR: https://github.com/cocos2d/cocos2d-x/pull/13922

**Comment by hanxi** [comment]
@WenhaiLin Sorry, too late to see. I use the `UIEditBoxImpl-common.h` to let code looks like more clean.

**Comment by WenhaiLin** [comment]
@hanxi :+1:  Could you squashed your commits and rebase to latest v3.

**Comment by hanxi** [comment]
Let me try.

**Comment by WenhaiLin** [comment]
@pandamicro Please merge this PR. @hanxi Thank you!

**Comment by Pouja** [comment]
If another fedora (or dnf) user is searching for `libgtk-3-dev`, for us it is `gtk3-devel`

**Pull request merged**
