### PR TITLE
stopAllActionsByTag && removeAllActionsByTag

### PR DESCRIPTION
**Pull request by newnon**
It is not possible to remove all actions by tugs 
this pull request add this 2 methods and give ability to make it faster.

### CODE REVIEW

**Comment by minggo** [comment]
Thanks.
Will you add corresponding test case?

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@newnon 
Could you please add a test case?

**Comment by newnon** [comment]
ok i'll do

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
Any update?

**Comment by newnon** [comment]
Done

**Pull request merged**
