### PR TITLE
Use browser font rendering instead of FreeType

### PR DESCRIPTION
**Pull request by j4m3z0r**
This moves to using Emscripten's SDL implementation to render TTF fonts. This resolves a number of font rendering bugs (though probably adds some different ones), simplifies the font-rendering code substantially and makes font rendering lightning fast -- previously UIs would have visible pauses while waiting for FreeType. Diff also removes FreeType headers and .a for Emscripten.

I have also included code to use the same technique for texture loading. This works, however it breaks something else meaning that the EffectsTest no longer works correctly. I have #ifdefed it out for the time being, but this will yield similar performance improvements in startup time once it works.

### CODE REVIEW

**Comment by j4m3z0r** [comment]
Oh, it also includes a rebuild of the other .a files, since Emscripten changed their ABI.

**Comment by j4m3z0r** [comment]
Ricardo helped me find the issue with texture loading, so that's now in this PR also. The same issue (alpha pre-multiply) was causing the weird borders on text rendering too, so that's now fixed too. Looks really good, and it's fast! :)

**Comment by dumganhar** [comment]
@j4m3z0r 
When I tested Emscripten port on my MBP 10.8.3. There are some errors as follows, could you let me know how to fix it?

<pre>
EMSCRIPTEN=/Users/james/Project/cocos2d-x/external/emscripten /Users/james/Project/cocos2d-x/external/emscripten/emcc -MMD -Wall -fPIC -Qunused-arguments -Wno-overloaded-virtual -Qunused-variable -s TOTAL_MEMORY=268435456 -s VERBOSE=1 -U__native_client__ -g -O2 --jcache -s GL_UNSAFE_OPTS=0 -s ASM_JS=1 -I../include/chipmunk -DEMSCRIPTEN -DNDEBUG -DCP_USE_DOUBLES=0 -c ../src/cpSweep1D.cpp -o obj/release/cpSweep1D.o
EMSCRIPTEN=/Users/james/Project/cocos2d-x/external/emscripten /Users/james/Project/cocos2d-x/external/emscripten/emcc -MMD -Wall -fPIC -Qunused-arguments -Wno-overloaded-virtual -Qunused-variable -s TOTAL_MEMORY=268435456 -s VERBOSE=1 -U__native_client__ -g -O2 --jcache -s GL_UNSAFE_OPTS=0 -s ASM_JS=1 -I../include/chipmunk -DEMSCRIPTEN -DNDEBUG -DCP_USE_DOUBLES=0 -c ../src/cpSpaceComponent.cpp -o obj/release/cpSpaceComponent.o
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
warning: LLVM version appears incorrect (seeing "Apple LLVM version 4.2 (clang-425.0.27) (based on LLVM 3.2svn)", expected "clang version 3.2")
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
(Emscripten: Running sanity checks)
FATAL: Cannot find clang++, check the paths in ~/.emscripten
FATAL: Cannot find clang++, check the paths in ~/.emscripten
make[1]: *** [obj/release/cpSpace.o] Error 1
make[1]: *** Waiting for unfinished jobs....
FATAL: Cannot find clang++, check the paths in ~/.emscripten
FATAL: Cannot find clang++, check the paths in ~/.emscripten
make[1]: *** [obj/release/cpBody.o] Error 1
make[1]: *** [obj/release/cpArbiter.o] Error 1
make[1]: *** [obj/release/cpSpatialIndex.o] Error 1
FATAL: Cannot find clang++, check the paths in ~/.emscripten
FATAL: Cannot find clang++, check the paths in ~/.emscripten
make[1]: *** [obj/release/chipmunk.o] Error 1
make[1]: *** [obj/release/cpSweep1D.o] Error 1
FATAL: Cannot find clang++, check the paths in ~/.emscripten
FATAL: Cannot find clang++, check the paths in ~/.emscripten
make[1]: *** [obj/release/cpCollision.o] Error 1
make[1]: *** [obj/release/cpSpaceComponent.o] Error 1
</pre>

**Comment by j4m3z0r** [comment]
Interesting. It says it can't find clang++, but also notes that the version string for clang is slightly different, suggesting that it did in fact find it. Check your ~/.emscripten file first. If that's not it, I'd suggest compiling llvm and clang from source to make sure you have everything. I believe that's how my system is setup -- just installed it into my home directory. Remember you need to unpack clang into the tools directory (I think) of the llvm source tree for it to compile both. Instructions are on the llvm site.

Before you go back to compiling cocos, I'd make sure that you can compile a simple "hello world" program with emscripten in c++. That will be easier to debug.

Hope that helps!

James.

**Pull request merged**
