### PR TITLE
Controller support. Mouse cursor. Path fix. Win/Mac/Linux Tested.

### PR DESCRIPTION
**Pull request by Sheado**
Hey Everybody,

Sorry this request has multiple fixes in it, but I'm having difficulty managing the fixes across 3 operating systems without keeping them separate. Also, for some reason, the lua-test files were committed by accident. Please let me know if there's a better way to submit multiple fixes in a case like this.

This request contains fixes for:
Controller support for Win/Mac/Linux #9912
(Added XBox controller support & tested on the 3 operating systems)
FEATURE 8766 #10502 (hide cursor - added Linux support)
Default search path on win32 points to current directory not Resources folder #8451 (Fixed)

### CODE REVIEW

**Comment by minggo** [comment]
This PR includes too many other modification that is not needed.

**Comment by Sheado** [comment]
Sorry about that. I was rushing too much. I'll clean it up and resubmit - that might take me a while though. If anybody wants to merge it for me in the meantime, you can find the latest code in this branch: https://github.com/Sheado/cocos2d-x/tree/v3-sheado

**Comment by FryDay** [comment]
As this is something that I need and am also working on, I'll see if I can get a clean PR made.

**Comment by Sheado** [comment]
Thanks @FryDay,

I've been meaning to get to this, but I haven't been able to find the time and I probably won't be able to add to this for a couple months. @darkdukey mentioned (here: https://github.com/cocos2d/cocos2d-x/pull/10720 ) he was going to work on this too - not sure how far he got. 
Also, in case it helps, here's another branch merged with a more recent state of cocos2d-x: https://github.com/Sheado/cocos2d-x/tree/v3-sheado-merge

**Comment by FryDay** [comment]
Only thing I'm having issues with is actually being able to use EventController. I'm sure I'm missing something, just don't know what. https://github.com/FryDay/cocos2d-x/tree/v3-controller

**Comment by darkdukey** [comment]
@FryDay can you show me the where do you receive the controller inputs?

**Comment by FryDay** [comment]
@darkdukey: I'm not sure I understand your question. I've been working on this blind without any way to test it at the moment. Tonight/tomorrow I'll actually be home and be able to work on it with a controller in front of me so I can properly debug and find what I missed/did wrong.

**Comment by Sheado** [comment]
Here's some really rough code for using the EventController:

```
   EventListenerController* _listener = EventListenerController::create();
    _eventDispatcher->addEventListenerWithSceneGraphPriority(_listener, this);
    _listener->onKeyDown = [=](Controller* controller, int keyCode, cocos2d::Event *event)
    {
        isGamepadPresent = true; // TODO - onconnected isn't being called yet
// do stuff with controller->getDeviceID() and keycode
    };

    _listener->onKeyRepeat = [=](Controller* controller, int keyCode, cocos2d::Event *event)
    {
// do stuff with controller->getDeviceID() and keycode
    };
    _listener->onKeyUp = [=](Controller* controller, int keyCode, cocos2d::Event *event)
    {
// do stuff with controller->getDeviceID() and keycode
    };
    _listener->onAxisEvent = [=](Controller* controller, int keyCode, cocos2d::Event *event)
    {
// do stuff with controller->getDeviceID() and keycode
        const auto& keyStatus = controller->getKeyStatus(keyCode);

        float value = keyStatus.value;
        // do something with value
        switch (keyCode)
        {
            case Controller::Key::JOYSTICK_LEFT_X:
// do something
                break;
            case Controller::Key::JOYSTICK_LEFT_Y:
// do something
                break;
            case Controller::Key::JOYSTICK_RIGHT_X:
// do something
                break;
            case Controller::Key::JOYSTICK_RIGHT_Y:
// do something
                break;
            case Controller::Key::AXIS_LEFT_TRIGGER:
// do something
                break;
            case Controller::Key::AXIS_RIGHT_TRIGGER:
// do something
                break;
            default:
                break;
        }
    };
```

**Comment by FryDay** [comment]
Excellent, I'm on the right track. I plan to work on this tonight and pretty much all day tomorrow.

**Comment by FryDay** [comment]
Everything seems to work. I haven't had a chance to update the xcode project or test in Linux yet, but I see no reason why it wouldn't work.

**Pull request closed without merging**
