### PR TITLE
Fix Socket IO handshake issue with latest version libwebsocket

### PR DESCRIPTION
**Pull request by pandamicro**
Plus:
- Update Bindings Generator
- Support llvm 3.5 for latest version idk

### CODE REVIEW

**Comment by pandamicro** [comment]
@dumganhar I found "client_no_context_takeover" is not supported on iOS and will cause all Socket IO connections fail, what do you suggest to solve this issue ?

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@zilongshanren 为什么 Android 平台一直报：sh: cocos: command not found

**Comment by zilongshanren** [comment]
@pandamicro  可能是环境配置出了问题，我修一下

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Pull request merged**
