### PR TITLE
Support Belarusian language

### PR DESCRIPTION
**Pull request by Dimon4eg**

### CODE REVIEW

**Comment by Dimon4eg** [comment]
[ci rebuild]

**Comment by Dimon4eg** [comment]
Travis-ci fails:
The command "tools/travis-scripts/before-install.sh" failed and exited with 56 during.

**Comment by Dimon4eg** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Will you please support it for other platform too?

**Comment by Dimon4eg** [comment]
Which? Also updated for web platform, here's pr https://github.com/cocos2d/cocos2d-html5/pull/3547

**Comment by minggo** [comment]
I found you only modify for Android platform, how about iOS, mac and other platforms?

**Comment by Dimon4eg** [comment]
Done

**Pull request merged**
