### PR TITLE
Added CCUserDefault and updated accelerometer based on G.Zito

### PR DESCRIPTION
**Pull request by styck**
Added CCUserDefault to Marmalade and associated test.  It works in simulator.

Updated the Accelerometer based on feedback from G.Zito.   Works in simulator.

### CODE REVIEW

**Comment by dumganhar** [comment]
hi, styck
I am merging your pull request, but I get some error when I double click test.mkb file on windows. Could you please fix it ?

e:\Marmalade\5.2\s3e\makefile_builder\mkb.py F:\Project\dumganhar\cocos2d-x\test
s\test.marmalade\test.mkb
Building project: F:/Project/dumganhar/cocos2d-x/tests/test.marmalade/test.mkb
F:/Project/dumganhar/cocos2d-x/tests/test.marmalade/test.mkb(25) : warning: file
name case does not match the filesystem: e:/marmalade/5.2/modules/IwGL/IwGL.mkf
f:/project/dumganhar/cocos2d-x/chipmunk/proj.marmalade/chipmunk.mkf(56) : warnin
g: unable to find file(s) chipmunk.cpp in path(s):
  f:/project/dumganhar/cocos2d-x/chipmunk/src
f:/project/dumganhar/cocos2d-x/chipmunk/proj.marmalade/chipmunk.mkf(56) : error:
 Unable to find file chipmunk.cpp in path(s):
  f:/project/dumganhar/cocos2d-x/chipmunk/src
FAILED (error code=2)

**Comment by dumganhar** [comment]
I compared test.mkb with old version, found that MARMALADEUSECHIPMUNK was set to 1, I changed it to 0 then it works on windows.

defines
{
    # chipmunk currently only supported on Mac OS (Xcode).
    # if you want to use the chipmunk - set MARMALADEUSECHIPMUNK = 1
    MARMALADEUSECHIPMUNK = 0
}

Why isn't chipmunk supported in windows and Just support Mac OS?

**Comment by styck** [comment]
Chipmunk files will not compile with Visual Studio as .C files because the code is using C++ syntax.  If you renamed all the Chipmunk files to .CPP and load them in the chipmunk.mkf file and enable Chipmunk in test.mkb then it will work.

I am not sure if the Visual Studio compiler can be set in the .mkb file to compile .C files as .CPP files.

**Comment by dumganhar** [comment]
Could you please pull the latest cocos2d-x master source, and pull request again?

**Comment by styck** [comment]
I can try, I am new at using GIT, more familiar with Subversion.

**Comment by dumganhar** [comment]
Visual Studio have the Property setting to compile .c files as .cpp files. But user have to open this property by themself. What about in XCODE? After double click test.mkb, whether need to modify the xcode project setting?

**Comment by styck** [comment]
I am not sure with Xcode, I have a MAC but have not used Marmalade system on it, I will try to set this up next week so that I can do additional testing.

The best solution for Visual Studio would be to have a setting in the .mkb file but I do not know if this is possible.  I had problems compiling as x86 and as Arm.

Looking at the Marmalade documenation file, the Build Options seems to have many options, I think this will be possible and will review tomorrow, it is late evening for me.

**Pull request closed without merging**
