### PR TITLE
VS and XCode project files have non-existent file references

### PR DESCRIPTION
**Pull request by rh101**
Removed and renamed several files that do not exist or have been renamed, but the project files had never been updated.  This was causing an issue building with Visual Studio 2015/2017, with a "Project is out of date" warning every time the program is run from within the IDE.

### CODE REVIEW

**Comment by dumganhar** [comment]
@rh101 , good catch.
But we need to rename `.hpp` to `.h` for header files since most of header files are named as `***.h`.

**Comment by rh101** [comment]
All good! For reference, the specific files causing the "Project is out of date" message to pop up in Visual Studio can be found by setting the MSBuild output verbosity to Detailed or Diagnostic.  This is in the menu under Tools – Options – Projects and Solutions – Build and Run.

**Comment by dumganhar** [comment]
@rh101 , so could you update this Pull Request to use `.h` instead of `.hpp`? Thanks.

**Comment by rh101** [comment]
All done, I think. Let me know if the changes don't show up for some reason.

**Review by dumganhar — APPROVED** [review]

**Comment by minggo** [comment]
thanks

**Pull request merged**
