### PR TITLE
deprecated CCControlExtensions and add UIScale9Sprite

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by newnon** [comment]
i thing it is not so good idea i use control extensions more than other

**Comment by minggo** [comment]
@newnon 
UI system has needed widgets. You can use them.
And it is confused to have more UI system. So i think we should merge it into UI system.

**Comment by newnon** [comment]
I use my own fork of cocos with support of SpriteBuilderX(it is my special fork of sprite builder with full cocos2d-x support) https://github.com/newnon/SpriteBuilderX
after this system will be table i will make pull request with it. (Somewhere SpriteBuilder much much better then cocos studio for example it support physics)

**Comment by newnon** [comment]
If you want to speak about it contact me in skype newnon
or you can take SpriteBuilderX here http://newnon.github.io/SpriteBuilderX/

**Comment by zilongshanren** [comment]
@newnon 
I think you can still use ControlExtension, but  other developers will get confused if there exists more than one GUI system.
BTW, thanks for your mention of SpriteBuilderX, It will try it later.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by Mazyod** [comment]
@newnon I took a look at your work, freakin awesome, great job!! .. and open source FTW!!

**Pull request closed without merging**
