### PR TITLE
Change the line break mode of system font(in Mac OS X) to 'ByWordWrapping'.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
@xiaofeng11 Please review this PR

**Comment by zilongshanren** [comment]
@WenhaiLin 
Is this a patch for v3.10 or v3?

**Comment by xiaofeng11** [comment]
@zilongshanren This change should merge to v3.10, @WenhaiLin Please send this pr to V3.10 brach, Thanks.

**Comment by xiaofeng11** [comment]
I have move it to v3.10 at https://github.com/cocos2d/cocos2d-x/pull/14801

**Pull request closed without merging**
