### PR TITLE
JS bindings fixes for Menu, Sprite and Label

### PR DESCRIPTION
**Pull request by ricardoquesada**
Label, Sprite and Menu fixes for JS bindings

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@pandamicro another PR with JS bindings fixes.
If it is Ok for you, I'll merge it.

**Comment by pandamicro** [comment]
:+1: It's ok for me

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Pull request merged**
