### PR TITLE
Add missing class declaration and remove duplicate declaration

### PR DESCRIPTION
**Pull request by mogemimi**
This PR adds a missing type declaration and header include for class `Quaternion`, it also removes a duplicate declaration of `Data` in `CCProperties.h`. Thanks!

### CODE REVIEW

**Comment by minggo** [comment]
But why it doesn't have compiling error? Does it mean we can remove some `#include`?

**Comment by mogemimi** [comment]
@minggo  Thank you for quick reply.

> But why it doesn't have compiling error?

The following ascii art represents the dependency graph:

```
"math/Vec2.h"
"math/Vec3.h"
"math/Vec4.h"
"math/Mat4.h"
"math/Quaternion.h"
      ^
      +
"math/CCMath.h"
      ^     ^
      |     +--------------+
      +                    |
"math/CCGeometry.h"        |
      ^     ^              |
      |     +--------+     |
      |              +     +
      |            "base/ccTypes.h"
      |              ^     ^
      +              +     |
"renderer/CCTexture2D.h"   |
      ^                    |
      +--------------------+
      +
"base/CCProperties.h"
```

`CCProperties.h` indirectly depends on `math/Quaternion.h` as shown in the graph.

> Does it mean we can remove some #include?

Probably yes. I guess we can remove `#include "renderer/CCTexture2D.h"` and `#include "base/ccTypes.h"` from `CCProperties.h` in favour of adding them to `CCProperties.cpp` instead. So I tried to apply these changes and it worked fine with Xcode, but I don't know if these can cause some side effects. 

Btw, if we are going to improve the compile time and any redundant dependencies, we can use a automated static analysis tool such as [include-what-you-use (IWYU)](http://include-what-you-use.org/), which will help us to solve the `#include` and type declaration problems.

**Comment by minggo** [comment]
@mogemimi good to know, thanks

**Comment by minggo** [comment]
And yes, we need to improve compile time if possible.

**Comment by mogemimi** [comment]
@minggo Sounds good! I'll try to improve the build performance using IWYU, thanks.

**Comment by minggo** [comment]
thanks @mogemimi

**Pull request merged**
