### PR TITLE
[FIX]: HTTPClient should not report 2xx status codes as errors!

### PR DESCRIPTION
**Pull request by Mazyod**
Current implementation of HttpClient reports HTTP responses with status code other than 200 as failures, but when consuming a RESTful API, status codes can range across the 2xx realm, and still be considered a success.

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. Could you provide any references about that?

**Comment by Mazyod** [comment]
@dumganhar Yeah, [here](http://en.wikipedia.org/wiki/HTTP_status_code#2xx_Success).

**Comment by dumganhar** [comment]
Thanks. we will check that.  :+1:

**Comment by dumganhar** [comment]
Merged. :)

**Comment by Mazyod** [comment]
awesome :smile: I am just getting started with HttpClient, will try to improve it as much as possible. (e.g. Thinking about fixing the callbacks from target/selector, to c++11 `std::function`)

**Comment by dumganhar** [comment]
Right now, we're using `std::function` instead of `target/selector` in develop branch.
Is there still `target/selector` stuff in HttpClient?

**Comment by Mazyod** [comment]
Yeah, I created an [issue #4702](http://cocos2d-x.org/issues/4702) for that. I could've sworn I marked it as refactor, but it's somehow under bugs.

**Comment by dumganhar** [comment]
I see, yep, it will be better if using `std::function`, thanks for point it out. :)

**Comment by Mazyod** [comment]
Np :) I already fixed this on my branch, but didn't send a pull request because I need to update the test cases and docs. Hopefully, this weekend.

**Pull request merged**
