### PR TITLE
WinRT In-situ edit/password box

### PR DESCRIPTION
**Pull request by joshbodily**
Adds an "in-place" Win RT edit box that is comparable in feature completeness to Android & iOS.  We've used a similar implementation (pre UIEditBoxImpl-common refactor) in our company's mobile PFM app (Boeing Employee's Credit Union MoneyManager) for a number of months now with no reported issues.

Lots of credit goes to original implementation by @stammen.

Complete implementation will depend on a pending PR by a colleague @steerlink:
https://github.com/cocos2d/cocos2d-x/pull/14914
- [ ] Unicode text not being displayed correctly in cocos2d-x CCLabel
- [x] Styles are wrong for Universal app (text aligned top instead of center, background is white instead of transparent)
- [x] Text doesn't persist when giving focus second time to edit box
- [x] Password chars should be \u25CF (Black Circle) instead of '?'

### CODE REVIEW

**Comment by stammen** [comment]
I am working with @joshbodily on the code review of this PR.

**Comment by joshbodily** [comment]
@stammen.  So I addressed three of the 4 issues.  I'll patch your PR into this branch so you can continue to test on UWP10.  I'm not set up to test yet, I'm on Windows 8.1 w/ Visual Studio 2015.  I'll upgrade to 10 over lunch and/or download the Windows 10 SDK.  Can you verify the fixes on the `cocos2d-win8.1-universal` app until I'm set up on Windows 10?

As for the first issue, what are your thoughts?  It looks like CCLabel on windows doesn't play nice with Unicode chars and emojis.  Is that a known limitation of cocos2d-x on Windows?  The below screenshot is from v3 branch as of when I cloned yesterday.

untitled

**Comment by minggo** [comment]
@stammen How about this PR?
Could you please take a look?
Thanks.

**Comment by stammen** [comment]
@minggo I will take a look. Do you want to pull this to v3 or v3.11?

**Comment by minggo** [comment]
@stammen I think it is ok to pull this to v3. Of course if you think it is critical, then we can merge it into v3.11 too.

**Comment by stammen** [comment]
@joshbodily Please update to the latest version of cocos2d-x v3 branch.

**Comment by joshbodily** [comment]
Nice!  I'll update to the latest version today.  I also have a minor fix
for multi-line that needs to go in as well.

**Pull request closed without merging**
