### PR TITLE
* fixed crash on EventDispatcher::updateListeners lost setDirty

### PR DESCRIPTION
**Pull request by shrimpz**

### CODE REVIEW

**Comment by dumganhar** [comment]
@shrimpz , thanks for your contribution. 
Could you please also add a testcase to `cpp-tests` project for reproducing this issue?

**Comment by shrimpz** [comment]
I'm sorry.
my project is too complicated.
I can't extract a testcase from my project, but I'm sure that it fixed.

The original issue is  CCASSERT in CCEventDispatcher.cpp:734  
        CCASSERT(listeners->getGt0Index() <= static_cast<ssize_t>(fixedPriorityListeners->size()), "Out of range exception!");

**Comment by dumganhar** [comment]
OK. Could you just paste some code snippets for how you're using EventDispatcher?

**Comment by shrimpz** [comment]
void test_for_crash_in_event_dispatcher( Scene\* scene, Label\* lbl )
{
    if( lbl )
    {
        lbl->removeFromParentAndCleanup( true );
    }

```
auto d = Director::getInstance();
unsigned char rawData[] = {
    0xEF, 0xBB, 0xBF, 0xE4, 0xBD, 0x9C, 0xE7, 0xBB, 0x88, 0xE4, 0xB8, 0xAD,
    0xE7, 0xBD, 0xAE, 0xE8, 0x87, 0xB3, 0xE6, 0x94, 0xAF, 0xE6, 0xAD, 0xA3,
    0xE5, 0x9C, 0xA8, 0xE8, 0xAF, 0xAD, 0xE4, 0xBA, 0x8E, 0xE7, 0x94, 0xB1,
    0xE7, 0x94, 0xA8, 0xE8, 0xAF, 0x91, 0xE8, 0xAE, 0xAE, 0xE5, 0xB7, 0xB2,
    0xE4, 0xBA, 0x9A, 0xE5, 0x8D, 0x8F, 0xE8, 0xAF, 0xA6, 0xE9, 0x97, 0xB2,
    0xE4, 0xB8, 0x8B, 0xE5, 0x8A, 0xA1, 0xE6, 0x97, 0xA0, 0xE6, 0x96, 0x87,
    0xE7, 0xBD, 0x91, 0xE8, 0xB7, 0xB3, 0xE4, 0xBD, 0x93, 0xE7, 0xB4, 0xA2,
    0xE9, 0x80, 0x9F, 0xE6, 0x90, 0x9C, 0xE9, 0x80, 0x81, 0xE6, 0x96, 0xAF,
    0xE6, 0x97, 0xB6, 0xE6, 0xB2, 0x99, 0xE5, 0xA1, 0x9E, 0xE8, 0xAF, 0xB7,
    0xE6, 0x83, 0x85, 0xE5, 0x99, 0xA8, 0xE9, 0x85, 0x8D, 0xE5, 0xB0, 0xBC,
    0xE8, 0x83, 0xBD, 0x0D, 0x0A, 0xE6, 0x85, 0xA2, 0xE7, 0xBB, 0x9C, 0xE7,
    0xBD, 0x97, 0xE8, 0xBF, 0x9E, 0xE5, 0x88, 0xA9, 0xE4, 0xBA, 0x86, 0xE5,
    0x85, 0xB0, 0xE6, 0x8B, 0x89, 0xE5, 0x86, 0xB5, 0xE7, 0xA9, 0xBA, 0xE5,
    0x85, 0x8B, 0xE5, 0x8F, 0xAF, 0xE5, 0xBC, 0x80, 0xE5, 0xA2, 0x83, 0xE8,
    0xBF, 0x9B, 0xE8, 0xA7, 0xA3, 0xE6, 0x8E, 0xA5, 0xE7, 0x96, 0x86, 0xE9,
    0x94, 0xAE, 0xE7, 0xAE, 0x80, 0xE5, 0x8A, 0xA0, 0xE5, 0x8D, 0xB3, 0xE6,
    0x9C, 0xBA, 0xE6, 0x88, 0x96, 0xE4, 0xBC, 0x9A, 0xE5, 0x9B, 0x9E, 0xE7,
    0x8E, 0xAF, 0xE8, 0xAF, 0x9D, 0x00
};

TTFConfig ttfcfg( "fonts/game-sc.ttf", 32 );
lbl = Label::createWithTTF( ttfcfg, (char *)rawData );
lbl->enableOutline( Color4B::RED, 2 );
lbl->setPosition( 800, 800 );
scene->addChild( lbl );

auto listener = EventListenerTouchOneByOne::create();
listener->setSwallowTouches( true );
listener->onTouchBegan = [ scene, lbl ]( Touch * t, Event * e )
{
    if( !lbl->getBoundingBox().containsPoint(
        lbl->getParent()->convertToNodeSpace( t->getLocation() )
        ) ) return false;
    test_for_crash_in_event_dispatcher( scene, lbl );
    return false;
};
lbl->getEventDispatcher()->addEventListenerWithSceneGraphPriority( listener, lbl );
```

}

**Comment by shrimpz** [comment]
```
auto director = Director::getInstance();
auto scene = director->getRunningScene();
auto winsize = director->getWinSize();
if( !scene )
{
    scene = Scene::create();
    director->runWithScene( scene );
}

test_for_crash_in_event_dispatcher(scene, nullptr);
```

in AppDelegate::applicationDidFinishLaunching

**Comment by shrimpz** [comment]
run on Android.
Touch some times word.
switch to desktop(home)
switch back.
crashed!!!

**Comment by dumganhar** [comment]
Thank you . I will check it. :)

**Comment by dumganhar** [comment]
@shrimpz, which device did you test on?
Did it happen on other platforms?

**Comment by shrimpz** [comment]
my devices:
HTC droid dna
HTC htc butterfly (miui)
LG g3
HongMi 1S telecom

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Pull request closed without merging**
