### PR TITLE
use correct shader

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by halx99** [comment]
ok, it's good.

**Comment by halx99** [comment]
@minggo I test your fix code, and for ETC1, the programTimer seems not support alpha

**Comment by minggo** [comment]
@halx99 may be we should not just change the shader to support ETC1, should do more work. Will you please send a PR for it and add a test case? Thanks.

**Comment by halx99** [comment]
Yes ,I will, I just work for it

**Comment by minggo** [comment]
thanks, and please send to v3.13 branch.

**Comment by halx99** [comment]
ok

**Comment by halx99** [comment]
I done it, see the PR: https://github.com/cocos2d/cocos2d-x/pull/16296

**Pull request merged**
