### PR TITLE
update for lay out component

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by liamcindy** [comment]
@minggo please review this pr for LayoutComponent

**Comment by zilongshanren** [comment]
Thanks, @liamcindy 
@minggo  This PR could be merge after the CI server is ready.

**Comment by minggo** [comment]
@andyque
Please create an issue and connect this PR to it.
Thanks.

**Comment by liamcindy** [comment]
@andyque Add state for layoutcomponent to use percent size and percent position only

**Comment by zilongshanren** [comment]
This PR fixed issue https://github.com/cocos2d/cocos2d-x/issues/10088

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
