### PR TITLE
support tizen

### PR DESCRIPTION
**Pull request by sukwonsuh**
This request is for Tizen mobile profile.

### CODE REVIEW

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
@andyque Please update tools\jenkins-scripts\pull-request-builder.py for support v35-for-tizen branch.

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by skaljac** [comment]
Hi @sukwonsuh 
I would like to thank you for your awesome work on Tizen port!
I have try to do it myself but I did not have enough time to learn enlightenment :-(

Everything work nice in simulator, but on Tizen device RD PQ with Tizen 2.3 I have error:

E/EFL     ( 2711): elementary<2711> elm_glview.c:205 _elm_glview_smart_add() Failed Creating an Evas GL Object.

this error can be solved in CCApplication-tizen.cpp with one line changed:

elm_config_accel_preference_set(gl_mode);

should be 

elm_config_accel_preference_set("opengl");

Unfortunately my Tizen device does not support "opengl:alpha:depth24:stencil8" as parameter for this config function.

Best regards, and keep up with good work!

**Comment by QingliWang** [comment]
Hi @skaljac 
To change the attributes for suitable context by "void AppDelegate::initGLContextAttrs()" might resolve your issue.
Thanks a lot.

**Comment by sukwonsuh** [comment]
@skaljac 
Thank you for good information. RD PQ device was not tested yet. I'll check then let you know result.
And would you please your device version information? I want to make sure your firmware is latest or not.
Thank you!

**Comment by skaljac** [comment]
Hi @sukwonsuh 

I have latest Tizen firmware available for RD PQ.
Firmware file is tizen-2.3-mobile_20150311 downloaded from here:
http://download.tizen.org/releases/2.3/2.3-mobile/tizen-2.3-mobile_20150311.3/images/target/mobile_target/

And after that simple modification, Cocos2D v3.5 was working for me just like it works on android device ;-)

Thank you for your great effort in translating Cocos2D to Tizen!
It is much appreciated!

Best regards,
Bojan

**Pull request merged**
