### PR TITLE
Fix APK not have assets folder

### LINKED ISSUE #19301: Apk not have asssets folder Or When running, have error: "TypeError: cc.Class is undefined" (cocos2dx v3.17 js project, run with gradle version 4.6 and android plugin version 3.2.1)
Reason: in gradle 4.6, merge assets is changed to folder merged_assets, not in assets folder
I fixed it with modify build.gradle file: 
 copy {
            println("copy " + Paths.get("${buildDir}", "/../../../../../res") + "  ===>  " + Paths.get("${buildDir}",
                    "/intermediates/merged_assets/${variant.dirName}/merge${variant.dirName}Assets/out/res"))
//           from "${buildDir}/../../../../../res"
//           into "${buildDir}/intermediates/assets/${variant.dirName}/res"
            from(Paths.get("${buildDir}", "/../../../../../res"))
            into(Paths.get("${buildDir}", "/intermediates/merged_assets/${variant.dirName}/merge${variant.dirName}Assets/out/res"))
        }
Another "copy {}" lines and "delete" line is modified similarly

### PR DESCRIPTION
**Pull request by ghost**
fixed #19301 

test:

```
cocos new -l js jsv3 && cocos run -p android
```

should not be black screen.

### CODE REVIEW

**Comment by minggo** [comment]
Thanks, i got it the idea now. Android Studio changed the output directory.

Is there a function to get the output directory, or it will have problem in future.

**Comment by ghost** [comment]
I can not find a function to get the `android_merged_assets` path.

I think we can do better:
1.  set `assets.srcDir "assets"`.
```
    sourceSets.main {
        java.srcDir "src"
        res.srcDir "res"
        jniLibs.srcDir "libs"
        manifest.srcFile "AndroidManifest.xml"
        assets.srcDir "assets" // Add this line
    }
```
2. change `variant.mergeAssets.doLast {` to `variant.mergeAssets.doFirst {`

```
android.applicationVariants.all { variant ->
    def project_root_folder = "${buildDir}/../../../../.."
    def dest_assets_folder = "${buildDir}/../assets/" // copy assets to proj.android/app/assets folder
    // ${buildDir}/intermediates/assets/${variant.dirName}/

    // delete previous files first
    delete dest_assets_folder

    variant.mergeAssets.doFirst {
```

**Comment by minggo** [comment]
@yinjimmy could you please explain the reason?

**Comment by ghost** [comment]
https://developer.android.com/studio/projects

`assets/`
> Contains file that should be compiled into an .apk file as-is. You can navigate this directory in the same way as a typical file system using URIs and read files as a stream of bytes using the AssetManager . For example, this is a good location for textures and game data.

**Comment by ffxiangyu** [comment]
did the trick for me in cocos2d-x 4.0 lua

**Pull request merged**
