### PR TITLE
Fixed bone's position is wrong  when animation has only a single bone

### PR DESCRIPTION
**Pull request by mikeweib**
when sub bone is single frame in animation and parent bone is not single frame. the transform of sub bone is error.

### CODE REVIEW

**Comment by 2youyou2** [comment]
Thanks a lot.
I have tested it,  it's really a problem.

**Comment by mikeweib** [comment]
How fix it?

**Comment by dumganhar** [comment]
@2youyouo2 who takes charge of Armature said it's good for merging this PR.

**Comment by dumganhar** [comment]
@mikeweib thanks.

**Pull request merged**
