### PR TITLE
add download multi task test case

### PR DESCRIPTION
**Pull request by drelaptop**
related PR.

https://github.com/cocos2d/cocos2d-x/pull/17761

https://github.com/cocos-creator/cocos2d-x-lite/pull/1222

### CODE REVIEW

**Comment by drelaptop** [comment]
1. add a Downloader test case
2. fix a resource using error

please review and merge @minggo

**Comment by drelaptop** [comment]
[ci rebuild]

use empty commit to trigger CI

`git commit --allow-empty -m "Trigger CI"`

**Comment by minggo** [comment]
You can just close and reopen the PR to trigger travis CI.

**Comment by drelaptop** [comment]
thanks for telling this.

**Pull request merged**
