### PR TITLE
added setStringWithFormat for CCLabelxxx.

### PR DESCRIPTION
**Pull request by tks2shimizu**
When setting a string to CCLabelxxx, it is convenient if you can use a format. 
Therefore, setStringWithFormat was added. 
(The kMaxStringLen is using the same value as CCString class.)

### CODE REVIEW

**Comment by dumganhar** [comment]
Do we really need this method?
It's easy to achieve that by:

<pre>
ttf->setString(CCString::createWithFormat("%d, %s", 123, "Hello")->getCString());
</pre>

**Comment by tks2shimizu** [comment]
One line will become simple if this is used. 

<pre>
ttf->setStringWithFormat("%d, %s", 123, "Hello");
</pre>

**Comment by dumganhar** [comment]
But you can easily define a macro like that:
`#define ccsf(...) CCString::createWithFormat(__VA_ARGS__)->getCString()`
Then it will be:
`ttf->setString(ccsf("%d, %s", 123, "Hello"));`
What's your opinion?

**Comment by tks2shimizu** [comment]
Oh. I'm sorry.
I don't know the ccsf(...).

**Comment by dumganhar** [comment]
`ccsf` is not defined in cocos2d-x
What i mean is that you can define it in your application.

**Pull request closed without merging**
