### PR TITLE
Update _bPlaying on CCActionObject.

### PR DESCRIPTION
**Pull request by maldewar**
The method CCActionObject::isPlaying() returns the state of the member var _bPlaying,
which is initially declared false and never gets updated. The change updates this variable
across the play, pause, stop and end states of the action.

### CODE REVIEW

**Comment by chengstory** [comment]
I think it can be merged!  Thanks @maldewar

**Comment by minggo** [comment]
@maldewar 
Could you please fix conflict?

**Comment by maldewar** [comment]
I've fixed the conflicts @chengstory @minggo, thanks

**Comment by minggo** [comment]
Thanks @maldewar.

**Pull request merged**
