### PR TITLE
Fix compile error under ubuntu 11.10

### PR DESCRIPTION
**Pull request by leon-li**
Changed all NULL to 0

### CODE REVIEW

**Comment by minggo** [comment]
NULL cause compile error on ubuntu 11.10?

**Comment by leon-li** [comment]
Yes.  Can also be fixed by "include <cstddef>"

**Comment by moadib** [comment]
Or even
`#ifndef NULL
#define NULL 0 
#endif`
No need so many changes as requested.

**Comment by tangzero** [comment]
"include <cstddef>" works fine.

**Comment by minggo** [comment]
I agree with tangzero. And bug 780 had been created for it some days ago.
http://www.cocos2d-x.org/issues/780

**Comment by leon-li** [comment]
I knew we can solve this by defining NULL or including the proper headers.

But what are the drawbacks of using "0" directly?  You will never have this problem if "0" is used directly.   And how "NULL" should be defined is an debatable topic.  The meaning of a "0" pointer should be very clear to every C/C++ programmer.  Until we have "nullptr" from C++ standard, I think using "0" is actually simpler and easier to understand.  Changing "NULL" to "0" was just minutes of search and replace.

**Comment by minggo** [comment]
Ok. You win. It is not a big issue.

**Pull request merged**
