### PR TITLE
Fixed invalid use of CC_TARGET_PLATFORM in the CCClippingNode

### PR DESCRIPTION
**Pull request by cpascal**
I modified CC_PLATFORM_WINDOWS to CC_PLATFORM_WIN32.
## 

In the CCPlatformConfig.h,
the definitions are..

// win32
# if defined(WIN32) && defined(_WINDOWS)
# undef

CC_TARGET_PLATFORM
# define CC_TARGET_PLATFORM

CC_PLATFORM_WIN32
# endif

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
