### PR TITLE
dispatch websocket callbacks to ui thread

### PR DESCRIPTION
**Pull request by PatriceJiang**
refactor websocket.cpp, improve lock safety

### CODE REVIEW

**Comment by minggo** [comment]
@drelaptop please take a look of CI, it seems it is nothing about this issue.

**Comment by drelaptop** [comment]
OK, I will check the CI build.

**Comment by drelaptop** [comment]
In file `tools/appveyor-scripts/before-build.ps1`
```sh
function Update-SubModule
{
    Push-Location $env:APPVEYOR_BUILD_FOLDER
    & git submodule init
    & git submodule update --recursive --depth=1 // only checkout latest one commit
    Pop-Location
}
```
With Repo: cocos-console updated, but submodule commit ID didn't updated. So checkout failed when you checkout a oldder commit. 

To correct this, I think update the sub-module commit ID is a better choice than remove `--depth=1 `.

**Comment by drelaptop** [comment]
@PatriceJiang the CI failed issue have been found at https://github.com/cocos2d/cocos2d-x/pull/18930, now you can rebase your branch to latest v3 to pass CI.

**Comment by drelaptop** [comment]
I think it's unnecessary to close this PR, and open another for same issue. finally the PR will be __Squash and Merge__.

**Pull request closed without merging**
