### PR TITLE
Fixes TMX map parsing problems

### PR DESCRIPTION
**Pull request by MartinLutherSu**
Now, TMX map can parse rotation of object correctly.

### CODE REVIEW

**Comment by minggo** [comment]
could you please add a test case?

**Comment by xbpiao** [comment]
@MartinLutherSu  Great job!

**Comment by v1993** [comment]
@minggo Why still isn't merged?

**Comment by minggo** [comment]
Because i don't know how to reproduce it.
@drelaptop could you please take a look too?

**Comment by drelaptop** [comment]
@v1993 not test case or test descriptions to tell us this is a right bug-fix

I will try to test it later

**Comment by drelaptop** [comment]
link https://github.com/cocos2d/cocos2d-x/pull/11540 , which added a simple `rotation` property parse

**Review by kangzixiang — APPROVED** [review]
Nice

**Pull request closed without merging**
