### PR TITLE
Detect Apple platforms

### PR DESCRIPTION
**Pull request by xpol**
As `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/TargetConditionals.h` documented:

```
    TARGET_OS_* 
    These conditionals specify in which Operating System the generated code will
    run.  Indention is used to show which conditionals are evolutionary subclasses.  

    The MAC/WIN32/UNIX conditionals are mutually exclusive.
    The IOS/TV/WATCH conditionals are mutually exclusive.


        TARGET_OS_WIN32           - Generated code will run under 32-bit Windows
        TARGET_OS_UNIX            - Generated code will run under some Unix (not OSX) 
        TARGET_OS_MAC             - Generated code will run under Mac OS X variant
           TARGET_OS_IPHONE          - Generated code for firmware, devices, or simulator 
              TARGET_OS_IOS             - Generated code will run under iOS 
              TARGET_OS_TV              - Generated code will run under Apple TV OS
              TARGET_OS_WATCH           - Generated code will run under Apple Watch OS
           TARGET_OS_SIMULATOR      - Generated code will run under a simulator
           TARGET_OS_EMBEDDED       - Generated code for firmware
```

That says:
- IOS/TV/WATCH is a subset of TARGET_OS_IPHONE.
- TARGET_IPHONE_SIMULATOR is also a subset of TARGET_OS_IPHONE.
- TARGET_OS_IPHONE is a subset of TARGET_OS_MAC.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@xpol  good work. :+1:  [ci rebuild]

**Comment by WenhaiLin** [comment]
Generating JS/LUA bindings fails. You can fix it like : 

```
// android
#if defined(ANDROID)
    #undef  CC_TARGET_PLATFORM
    #define CC_TARGET_PLATFORM         CC_PLATFORM_ANDROID
// Apple: Mac and iOS
#elif defined(__APPLE__)
    #include <TargetConditionals.h>
    //// TARGET_OS_IPHONE inlcudes TARGET_OS_IOS TARGET_OS_TV and TARGET_OS_WATCH. see TargetConditionals.h
    #if TARGET_OS_IPHONE
        #undef  CC_TARGET_PLATFORM
        #define CC_TARGET_PLATFORM         CC_PLATFORM_IOS
    #elif TARGET_OS_MAC
        #undef  CC_TARGET_PLATFORM
        #define CC_TARGET_PLATFORM         CC_PLATFORM_MAC
    #endif
#endif
```

**Comment by xpol** [comment]
Can't find any official docs about `TargetConditionals.h`.

Find one [here](https://github.com/tezzutezzu/openFrameworks/blob/master/docs/osx.md#common-issues-), it says:

> "TargetConditionals.h" not found -- Xcode Terminal may not be installed

And I guess Xcode Terminal is `Xcode Command Line Tools`.

And some other search results says it needs `macosx10.9`.

**Comment by WenhaiLin** [comment]
@zilongshanren This PR is OK for merge now.

**Comment by zilongshanren** [comment]
@xpol  Thanks :+1:

**Pull request merged**
