### PR TITLE
Linux implementation of CCImage::initWithString now uses fontconfig

### PR DESCRIPTION
**Pull request by peoro**
Added fontconfig support for Linux.

`CCImage::initWithString` now uses fontconfig to find a font matching its `pFontName` parameter.

By disabling hte `USE_FONTCONFIG` macro it's possible to use the old function, where `pFontName` was used a font file path.

This should fix issue #732

### CODE REVIEW

**Comment by minggo** [comment]
Is fontconfig a common library?
If not, the engine should offer one?

**Comment by peoro** [comment]
Fontconfig is a very common library: kind of any graphical application and library that needs to display some text uses fontconfig, including Qt and GTK. Cocos2dx users may require to install development files for fontconfig, but they are available for any distribution.

About libraries needed by cocos2dx I've got some doubts though:
- FreeType2 is shipped with cocos2dx sources, although it's really common as well (fontconfig depends on FreeType2): you'll find it on any Linux system with any kind of graphical interface installed.
- GLFW is not shipped with cocos2dx sources, and it's far less common: GLFW is available on any Linux distribution as well, but never installed by default.
  I think an issue could be opened about this, but I don't really mind.

Last thing about this pull request: the semantics of my `CCImage::initWithString` is that of using the font matching `pFontName`. If `pFontName` is a path to a TTF file it won't load it, will rather load the font matching such path (which will probably be the default system font).
The function should be changed a little if its semantics should be something like "load a font file or a font matching the given name".

**Comment by minggo** [comment]
Thank you.
I am not familiar with linux, the port of it is finished by a developer.

I compile the code, and find my system don't install fontconfig. There is an error to include <fontconfig/fontconfig.h>, my system is ubuntu11.04. So fontconfig is not so common that it is installed by default.

So I think you can not use fontconfig as default, or many developers may meet the same problem like me.
How about remove -DUSE_FONTCONFIG as default.

**Comment by minggo** [comment]
Thank you.
I am not familiar with linux, the port of it is finished by a developer.

I compile the code, and find my system don't install fontconfig. There is an error to include <fontconfig/fontconfig.h>, my system is ubuntu11.04. So fontconfig is not so common that it is installed by default.

So I think you can not use fontconfig as default, or many developers may meet the same problem like me.
How about remove -DUSE_FONTCONFIG as default.

**Comment by peoro** [comment]
I believe that fontconfig is installed, try typing `fc-match Arial` in a terminal: that command should use fontconfig to look for a font matching "Arial". Also the fontconfig library should be present: its path would be something like `/usr/lib/libfontconfig.so.1`.

The problem is that development files (ie: header files) are not installed by default, you'll need to install `libfontconfig-dev` for that. This is the same for any software, ubuntu doesn't install any -dev package by default.

Anyway ok, should I remove USE_FONTCONFIG macro and pull the request again?

**Comment by minggo** [comment]
Yes, please remove USE_FONTCONFIG macro.
Thank you.

**Pull request merged**
