### PR TITLE
use size_t instead of long in Array

### PR DESCRIPTION
**Pull request by minggo**
1. use `size_t` instead of `long` in Array API
2. remove unneeded spaces
3. add spaces before and after binary operation, such as `+`

### CODE REVIEW

**Comment by minggo** [comment]
@ricardoquesada 
Could you please review it?

**Comment by minggo** [comment]
I will add other commit after this one is merged.

**Comment by minggo** [comment]
I will change the API first, then fix warnings later.

**Comment by ricardoquesada** [comment]
Sure. I'll review tomorrow Tuesday.

**Comment by minggo** [comment]
I am not sure if i use too much `size_t`. May be only `count` and `capacity` should use `size_t`.

**Comment by ricardoquesada** [comment]
@minggo 
Looks good to me.

You are using `size_t` for size and index, and that is the expected use:
http://stackoverflow.com/a/1951548

**Comment by minggo** [comment]
Ok.

**Comment by minggo** [comment]
I change the type of `Array::getIndexOfObject()` to `size_t`, then what's the return value when the object is not contained in the Array?

**Comment by minggo** [comment]
Ok, i can return the max value of size_t.

**Comment by ricardoquesada** [comment]
Good point.

2 options:
-  return std::max() or something like that
- or `assert()` if the object doesn't exist

**Comment by minggo** [comment]
Thanks. Since we will return `ssize_t` instead of `size_t`, i think it can return `-1`.

**Pull request merged**
