### PR TITLE
Incompatible pointer type?

### PR DESCRIPTION
**Pull request by iSevenDays**
Why sizeof(void*_) and not sizeof(void_)?

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. could you also send the patch to https://github.com/slembcke/Chipmunk2D ?

**Comment by iSevenDays** [comment]
Yes, thanks, I will send the patch now.

**Comment by iSevenDays** [comment]
The patch is already there.

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
