### PR TITLE
add CCMenu::init() and CCMenu::menu() to create empty menus

### PR DESCRIPTION
**Pull request by leon-li**

### CODE REVIEW

**Comment by minggo** [comment]
Why to add these functions to CCMenu.

**Comment by leon-li** [comment]
Sometimes it is more logical to create the menu a one place and add items to it at another place.  It's more convenient to have these functions.

**Comment by minggo** [comment]
I think you can use menuWithItem(NULL) and addChild() to achieve the logic.
All right?

**Comment by leon-li** [comment]
Yes.  However, it is more convenient to have menu() and init().  And more importantly, the purpose is more clear.

**Comment by minggo** [comment]
If so, I think the name can be node, not menu.
In fact, it hase node in cocos2d-iphone, because c++ should implement it in every class.

**Comment by minggo** [comment]
And the node call init() in it, not add another method.

**Comment by leon-li** [comment]
ok.  I will rename menu() to node()

**Comment by leon-li** [comment]
Done.  Please check.

**Comment by minggo** [comment]
Oh, I think you can add the logic of init() in node(), and remove the init().
I think less function is great.

**Comment by leon-li** [comment]
The init() serves another purpose: to avoid putting the object into the auto release pool.

**Comment by minggo** [comment]
I don't understand. Could you give me a example?

**Comment by leon-li** [comment]
If you call CCMenu::node(), the created object is "autorelease"ed.  If you call" CCMenu \* menu = new CCMenu(); menu->init();", it is not "autorelease"ed. There is a slight performance gain by not putting it into the pool. Plus, our auto release pool is not thread safe at the moment.

**Comment by minggo** [comment]
Yeap, you are right.
Thank you.

**Pull request merged**
