### PR TITLE
GLView::setFrameSize fixed

### PR DESCRIPTION
**Pull request by MrCapone**
fix for https://github.com/cocos2d/cocos2d-x/issues/16003
also fixed changing size of resizable window

### CODE REVIEW

**Comment by minggo** [comment]
thanks

**Comment by ricardoquesada** [comment]
This is probably is the correct fix for the design resolution, but it is breaking backward compatibility. See this issue: https://github.com/cocos2d/cocos2d-x/issues/16485

@minggo I think we should revert this PR, and find a better way to fix it.

**Comment by ricardoquesada** [comment]
This PR should fix both #16003 and #16485 
https://github.com/cocos2d/cocos2d-x/pull/16533

**Comment by minggo** [comment]
@ricardoquesada it may break backward compatibility, but why it will cause crash?

**Comment by minggo** [comment]
Oh, it is an assert error.

**Comment by ricardoquesada** [comment]
@minggo my PR won't break backward compatibility. The one that broke compatibility was this PR (#16031). My PR fixes the backward compatibility issued caused by this PR while fixing bug #16003

**Comment by minggo** [comment]
@ricardoquesada yep, i got it. Thanks.

**Pull request merged**
