### PR TITLE
fix bug:backgourd  of PageView,ListView,ClippingNode display green

### PR DESCRIPTION
**Pull request by myourys**
I found backgourd  of PageView,ListView,ClippingNode display green in android device.

### CODE REVIEW

**Comment by minggo** [comment]
You can not pass `Cocos2dxGLView`, many native classes depends it.

**Comment by minggo** [comment]
Sorry, it will create `Cocos2dxView`. You should override `onCreateView` and create needed format.

**Comment by myourys** [comment]
@minggo 
All my PageView,ListView display incorrect.
Can you provide a correct way to solve this Problem?
I override onCreateView function at AppActivity.java in my project now~

**Comment by shujunqiao** [comment]
[ci rebuild]

**Comment by myourys** [comment]
It should be a common problem, it's better to have a official way to rolve it . thanks

**Comment by shujunqiao** [comment]
[ci rebuild]
the last command was be flushed, so i try it again.

**Comment by minggo** [comment]
@myourys 
I am confused. This PR is not resolve your mentioned issue?

**Comment by myourys** [comment]
@minggo 可能是我表达不清楚
在Android中，PageView,ListView,ClippingNode 显示背景为绿色，整个屏幕为白色。我目前在我自己的项目中在AppActivity.java中重载了 onCreateView 去设置setEGLConfigChooser解决了这个问题。

但是我觉得这个是普遍问题，所以提交了这个PR，将setEGLConfigChooser放在了Cocos2dxActivity.java中。但是你好像说这个不是正确的做法？

**Comment by minggo** [comment]
Yep. Because not all problems needs stencil buffer. Enable stencil buffer will cause more memory. If you want to use `clipping node`, should override `onCreateView` to set wanted format. `onCreateView` is created for it.

Sorry, i can not replay in Chinese because all other developers don't understand Chinese.

**Comment by myourys** [comment]
@minggo I get it , thanks!

**Comment by minggo** [comment]
So i will close this PR.
And thanks for your contribution.

**Pull request closed without merging**
