### PR TITLE
[android/cpp test]Unit Test/9 neon32 release mode crash

### PR DESCRIPTION
**Pull request by PatriceJiang**
ref https://github.com/cocos2d/cocos2d-x/issues/19187#issuecomment-442970218

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@PatriceJiang could you check if below helps:
https://github.com/cocos2d/cocos2d-x/pull/18895

**Comment by PatriceJiang** [comment]
I think `asm` code is considered manually optimized, and disable compiler's optimize action is reasonable. 
It's also difficult to predict how will compiler 'optimize' our asm code.

**Comment by crazyhappygame** [comment]
@sp-stefano-lanza could you check this fix and issue? Is it ok to disable optimization for asm?

**Comment by crazyhappygame** [comment]
@PatriceJiang does #18895 fix this crash?

**Comment by PatriceJiang** [comment]
The test case dose not crash on 64bit mode. @crazyhappygame

**Comment by PatriceJiang** [comment]
According to the [arm document](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100748_0606_00_en/ddx1471430827125.html)
> Use the `volatile` qualifier for assembler instructions that have processor side-effects, which the compiler might be unaware of. The volatile qualifier disables certain compiler optimizations. The `volatile` qualifier is optional.

`asm volatile` is expected to disable compiler optimization, but it takes no effect. That is perhaps `inline` function's side effect.

**Pull request merged**
