### PR TITLE
openUrl function for all platform but on windows RT empty function

### PR DESCRIPTION
**Pull request by newnon**
Just open any url in default browser or application
also can run applications or open files

### CODE REVIEW

**Comment by minggo** [comment]
Please don't add it into Application. It is better to add it into namespace utils.

**Comment by newnon** [comment]
I've added it to application because of iphone & cocos2d they have this function in UIApplication
https://developer.apple.com/library/ios/documentation/uikit/reference/UIApplication_Class/Reference/Reference.html#//apple_ref/occ/instm/UIApplication/openURL:

**Comment by minggo** [comment]
Ok.
Will you please fix conflict?

**Comment by newnon** [comment]
Done

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Will you please add a test case?

**Comment by newnon** [comment]
In which category?

**Comment by minggo** [comment]
How about add a new file in cpp-tests?

**Comment by guykogus** [comment]
I've got URL opening in my WP8 game. Should I create a new pull request for it or can I add to this one?

**Comment by newnon** [comment]
i'm not sure, but you can send pull request to my fork and i will merge it.

**Comment by guykogus** [comment]
Hey newnon, I did it but I can't fork your repository as it's already a fork. I've created a new repo with the fix here:
https://github.com/guykogus/cocos2d-x-newnon
Can you please look at my commits and implement them yourself? I've even added a test case so you can check that it works.

**Comment by newnon** [comment]
ok i'll try

**Comment by minggo** [comment]
@guykogus 
Indeed you can edit pull request before sending a pull request.
You can edit it to send to @newnon.

**Comment by guykogus** [comment]
@minggo it looks like my commits were added to this pull request, but I have no idea how. I did a kind of manual fork of @newnon 's repo, maybe GitHub managed to pick up on that.

**Comment by minggo** [comment]
@newnon 
Will you please fix conflict and add test case for it?
Thanks.

**Comment by newnon** [comment]
I pulled from your repository and after that add test files to all other projects

**Comment by newnon** [comment]
[ci rebuild]

**Comment by newnon** [comment]
No a don't understand why it does not want to compile

**Comment by newnon** [comment]
[ci rebuild]

**Comment by guykogus** [comment]
I don't think it's to do with our code, it's a Jenkins issue.

**Comment by newnon** [comment]
[ci rebuild]

**Pull request merged**
