### PR TITLE
AudioEngine:Linux: implementation using FMOD, refactor to SimpleAudio…

### PR DESCRIPTION
**Pull request by cesarpachon**
…Engine now as wrapper of AUdioEngine, upgrade FMOD binaries. I just made another PR to the external-dependencies binaries project with an upgraded version of linux FMOD binaries.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@WenhaiLin 
please take a look at this PR.

@cesarpachon  
:+1:  I will merge your PR in cocos2d-x-3rd-party-bin, but you should also update the reference in `external/config.json` to a new value.

**Comment by zilongshanren** [comment]
@cesarpachon 
The latest external deps is `v3-deps-76`.

**Comment by cesarpachon** [comment]
hello @zilongshanren, the update in external/config.json  is just a matter of changing the version number from 75 to 76, or there is some other steps I am missing out?

**Comment by zilongshanren** [comment]
@cesarpachon  you need to change the version number in your PR, otherwise your PR can't pass the CI.

**Comment by cesarpachon** [comment]
after adding the change to version number in config.json and checking jenkings, I noticed It failed by an incomplete commit to deps project. I made a new PR to fix that: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/191

**Comment by zilongshanren** [comment]
@cesarpachon 
Why not change the config.json in this PR thus we could see the jenkins result here.

**Comment by zilongshanren** [comment]
@cesarpachon 
The new version is v3-deps-78

**Comment by cesarpachon** [comment]
it seems CI failed because of the presence of linux symbolic links in the lib folder. I made a PR about that: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/192

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@cesarpachon 
:+1:  Thanks.

**Pull request merged**
