### PR TITLE
[lua-tests] Reverts uniform after GetUniformTest.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
@ricardoquesada , please review this PR. Thanks.

**Comment by dumganhar** [comment]
`createGetUniformTest` in OpenGLTest.lua will modify the uniform (CC_MVPMatrix) of the default shader `ShaderPositionTextureColor`, it's just a test, we need to revert it to the old uniform after test.

**Comment by dumganhar** [comment]
@minggo, please review too.

**Comment by ricardoquesada** [comment]
@dumganhar what bug are you fixing with this? thanks.

**Pull request merged**
