### PR TITLE
Fix compile error isnan -> std::isnan #15111

### PR DESCRIPTION
**Pull request by gelldur**
Issue: https://github.com/cocos2d/cocos2d-x/issues/15111

### CODE REVIEW

**Comment by minggo** [comment]
> f:\jenkins\workspace\ccs-pr\node\windows-universal_bak\cocos\2d\libcocos2d_8_1\libcocos2d_8_1\libcocos2d_8_1.Shared......\CCActionCamera.cpp(197): error C2039: '_isnan' : is not a member of 'std' [f:\jenkins\workspace\ccs-pr\node\windows-universal_bak\cocos\2d\libcocos2d_8_1\libcocos2d_8_1\libcocos2d_8_1.Windows\libcocos2d_8_1.Windows.vcxproj]

It seems std::isnan is missing in VS.

**Comment by stammen** [comment]
@gelldur I think you might need to #include <cmath> to get isnan into the std namespace.

**Comment by stammen** [comment]
@gelldur @minggo The issue with std::isnan is in cocos2d\cocos\platform\winrt\CCStdC.h

Please add the following at line 35 
#include <cmath>

Please remove the following at line 49

#if !defined(isnan)
    #define isnan   _isnan
#endif

I suspect that the win32 version will have the same issue.

**Comment by minggo** [comment]
@gelldur Could you try as @stammen suggested?

**Comment by minggo** [comment]
I did as @stammen suggested in #15569

**Pull request closed without merging**
