### PR TITLE
fix some warnings under android

### PR DESCRIPTION
**Pull request by leon-li**
This request specify the only needed commit for the fix.

### CODE REVIEW

**Comment by minggo** [comment]
Can not use NULL in ndk-r5?

**Comment by leon-li** [comment]
I don't think there is any harm using NULL like this: if(p != NULL) ...

How gcc gives warning "NULL used in arithmetic".  I simply change NULL to 0 or change the statement to if(p) to avoid the annoying warning.

The commit also contain other changes like deleting a pointer without the declaration of the class.

**Comment by walzer** [comment]
Could not find the branch of leon-li-acfe927.

**Comment by walzer** [comment]
Could not find the branch named leon-li-acfe927.

**Comment by leon-li** [comment]
I am having difficulties submitting pull request with specific commits.  I will close this request and try again.

**Pull request closed without merging**
