### PR TITLE
Fix Travis CI compilation issue

### PR DESCRIPTION
**Pull request by pandamicro**

### CODE REVIEW

**Comment by pandamicro** [comment]
@minggo we should block these annoying ads

**Comment by minggo** [comment]
I am not the owner of this repo.
I have asked @ricardoquesada help to block  it.

**Comment by ricardoquesada** [comment]
I blocked him following these instructions:
https://help.github.com/articles/blocking-a-user

Let me know if he appears again. thanks.

**Comment by edwardzhou** [comment]
@ricardoquesada 
that motherfucker are still pumping annoying messages, although I blocked him in my profile. Can absolutely block him or kick him?

**Pull request merged**
