### PR TITLE
Make viewport constructor more compile friendly

### PR DESCRIPTION
**Pull request by dabingnn**

### CODE REVIEW

**Comment by dabingnn** [comment]
@pandamicro Could you please review this pull request, it changes the code slightly, which is more friendly to old compiler.
Fix #13134

**Comment by pandamicro** [comment]
Ok, review done

**Comment by zilongshanren** [comment]
@pandamicro doesn't merge

**Comment by zilongshanren** [comment]
@pandamicro Commit message is not good.

**Comment by pandamicro** [comment]
I think the message itself is clear enough, why ?

**Pull request merged**
