### PR TITLE
Vibrate support in v4

### PR DESCRIPTION
**Pull request by kompjoefriek**
Implementation of feature request #10415

The Device class seemed like a logical place for such a feature.

Added:

```
bool Device::isVibrateSupported();
void Device::startVibrate(int);
void Device::stopVibrate();
```

I also added VibrateTest to cpp-tests, and added empty stubs for the plaforms i did not implement.
Currently only Android has been implemented, and has been tested on Lollipop.

### CODE REVIEW

**Comment by darkdukey** [comment]
Nice

**Comment by minggo** [comment]
Nice feature.
Could you please fix conflict?

And i have one question, does `isVibrateSupported` need?

**Comment by minggo** [comment]
There is not effect when it is not support.
How about that?

**Comment by minggo** [comment]
As i find the API of Android here http://developer.android.com/reference/android/os/Vibrator.html, it has more feature than just start vibrate for a duration.

So i think we should discuss what is developer needed first [here](http://discuss.cocos2d-x.org/c/cocos2d-x-dev-discussion).
I will create a ticket there.

**Comment by minggo** [comment]
I created a [ticket](http://discuss.cocos2d-x.org/t/vibrate-requirement-collection/20207) to discuss the requirement.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@kompjoefriek  Please fix iOS platform compile issues.
Thanks.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by walzer** [comment]
Add to v3.7 roadmap

**Comment by kompjoefriek** [comment]
@walzer This Pull Request was intended for the 4.x branch. Does the milestone for 3.x mean something needs to be changed so it works for the 3.x branch?

**Comment by pandamicro** [comment]
@kompjoefriek If it doesn't take a lot of time, we'd appreciate it if you can re-send a pull request to our v3 branch. It will need some extra work, but I'm not sure if it's hard or not.

**Comment by kompjoefriek** [comment]
It looks like not much work, except for the cpp test class (all test classes in v3 have changed a lot). I will try to get this working on the v3 branch with a new pull request.

Will this pull-request ever be merged into v4?

**Comment by pandamicro** [comment]
@kompjoefriek In fact, v4 development is freezing now, so I'm not sure when it will get merged

**Comment by minggo** [comment]
close this  PR since v4 is frozen currently

**Pull request closed without merging**
