### PR TITLE
Clipping node does not work for Sprite3D

### PR DESCRIPTION
**Pull request by super626**
Clipping node does not work for Sprite3D.

More discussion is needed.

### CODE REVIEW

**Comment by pandamicro** [comment]
Jenkins have failed, please fix issues on Windows universal and Linux

**Comment by super626** [comment]
@pandamicro 
Discuss it here,
http://discuss.cocos2d-x.org/t/how-to-make-clipping-node-work-for-3d/22252

**Comment by ricardoquesada** [comment]
I added my comments on the thread. Once the build passes, feel free to commit your test case (without the fix). thanks.

**Comment by super626** [comment]
New PR to v3.7-release is here,
https://github.com/cocos2d/cocos2d-x/pull/12618

**Comment by pandamicro** [comment]
#12618 have been merged for v3.7 rc0

**Pull request closed without merging**
