### PR TITLE
[ci skip] Testcase for multiple items in scrollView

### PR DESCRIPTION
**Pull request by ZhangMenghe**
- Testcase for #13959
- Since V3.9

### CODE REVIEW

**Comment by pandamicro** [comment]
What's the performance difference between v3.8 and v3.9

**Comment by ZhangMenghe** [comment]
<table>
    <tr>
        <th rowspan="2">RenderMode</th>
        <th colspan="2">Canvas</th>
        <th colspan="2">WebGL</th>
    </tr>
    <tr>
        <td>v3.8</td>
        <td>v3.9</td>
        <td>v3.8</td>
        <td>v3.9</td>
    </tr>
    <tr>
        <td colspan="5">Draw 1000 Texts</td>
    </tr>
    <tr>
        <td>DrawCalls</td>
        <td>1026</td>
        <td>48</td>
        <td>1028</td>
        <td>48</td>
    </tr>
    <tr>
        <td>FPS:Safari</td>
        <td>11~13</td>
        <td>35(fast scroll)~60</td>
        <td>13~19</td>
        <td>58~60</td>
    </tr>
    <tr>
        <td>FPS:QQ WebSite</td>
        <td>16~20</td>
        <td>38~43</td>
        <td>17~23</td>
        <td>38~42</td>
    </tr>
    <tr>
        <td>FPS:UC WebSite</td>
        <td>13~20</td>
        <td>20~38</td>
        <td></td>
    </tr>
        <tr>
        <td colspan="5">Draw 500 Buttons</td>
    </tr>
    <tr>
        <td>DrawCalls</td>
        <td>2026</td>
        <td>48</td>
        <td>2028</td>
        <td>48</td>
    </tr>
    <tr>
        <td>FPS:Safari</td>
        <td>11~13</td>
        <td>30~48</td>
        <td>13~19</td>
        <td>39~55</td>
    </tr>
    <tr>
        <td>FPS:QQ WebSite</td>
        <td>6~11</td>
        <td>17~22</td>
        <td>5~9</td>
        <td>14~28</td>
    </tr>
    <tr>
        <td>FPS:UC WebSite</td>
        <td>6~10</td>
        <td>12~23</td>
        <td></td>
    </tr>
        <tr>
</table>

**Comment by WenhaiLin** [comment]
:+1:

**Comment by pandamicro** [comment]
What's the performance difference for Scale9Sprite objects ?

**Pull request merged**
