### PR TITLE
projection fixes

### PR DESCRIPTION
**Pull request by newnon**
This fix cropped pixel on screen border in 3d projection #8354

### CODE REVIEW

**Comment by newnon** [comment]
You can take this image [maxresdefault.jpg](https://i.ytimg.com/vi/CrOhSeG8Zc4/maxresdefault.jpg) place it on 0, 0 on full hd screen and make screenshot, you will see that back rect of pixel start exactly from border but on image it have 2 white pixels before black. And also you can see other artefacts because of this.

**Comment by 1scaR1** [comment]
Do you really need digits in constant after 7th digit in fraction path, because of float number precision?

**Comment by newnon** [comment]
May be but why not? compiler will take as much digits as it's possible.

**Comment by minggo** [comment]
> on full hd screen and make screenshot

@newnon  Could you please use sample codes to describe it? Can i test it in iPhone devices or Mac?

**Comment by newnon** [comment]
Shell i add it to test or what? you can test it on any device bigger resolution more pixels will be cropped

**Comment by minggo** [comment]
> place it on 0, 0 on full hd screen and make screenshot

I don't understand what does it mean. Could you please describe it in more detail?

**Comment by newnon** [comment]
1. make any full screen project(mac, win, android, ios)
2. set projection to 3d(it is default behavior)
3. make empty scene
4. create sprite with some good image you can take it form here [sample](https://i.ytimg.com/vi/CrOhSeG8Zc4/maxresdefault.jpg)
5. set position to 0,0
6. set anchor point to 0,0
7. add sprite to scene
8. make screenshot 
compare screenshot with original image you will see that 1-2 pixels are cropped from every side
repeat it with  after this PR
and you will see that all pixel on their plaices

**Comment by newnon** [comment]
comparison before PR http://screenshotcomparison.com/comparison/205616
after PR http://screenshotcomparison.com/comparison/205617

**Comment by newnon** [comment]
@minggo did you checked this?

**Comment by minggo** [comment]
Sorry, i was busy with v3.15 releasing.

**Review by dumganhar — APPROVED** [review]

**Comment by dumganhar** [comment]
@newnon  👍 
@minggo , this patch is good for being merged.

**Pull request merged**
