### PR TITLE
Remove unneeded resources

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@WenhaiLin 
You should also update the submodule after the ccs-res  is merged.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
