### PR TITLE
 Setup android builds: cpp_test, cpp_empty, cocos_new for appveyor 

### PR DESCRIPTION
**Pull request by crazyhappygame**
@minggo What do you think to run the same android builds (cpp_test, cpp_empty, cocos_new) for linux? 
Unfortunately we can not enable androids builds for mac/ios. Mac travis build nodes are to slow to compile  cpp_test in 1 hour.

### CODE REVIEW

**Comment by crazyhappygame** [comment]
Added appveyor artifacts: https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact

Example:
https://ci.appveyor.com/api/projects/minggo/cocos2d-x/artifacts/debug/CppTests-debug.apk?job=Environment%3A%20build_type%3Dandroid_cpp_tests

**Comment by crazyhappygame** [comment]
@minggo Could you accept this pull request?

**Comment by minggo** [comment]
Did you mean use appveyor instead of travis to build tests for linux? Can appveyor be used to build linux?

**Comment by crazyhappygame** [comment]
> Did you mean use appveyor instead of travis to build tests for linux?

No. I meant add (in separate PR) to travis linux "android_cocos_new_test" build configuration

**Comment by minggo** [comment]
Sure, we can add it as a separate task.

**Comment by minggo** [comment]
@crazyhappygame it seems not it will have 4 jobs for each PR, and these jobs are not run simultaneously. Now it will about more than 2 hours for a PR: https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.668. And it only takes about 40-50 minutes before.

**Comment by crazyhappygame** [comment]
Do you mean no for "cpp_test, cpp_empty, cocos_new for linux". ? 
Current travis problem is with Mac build. (Please check travis queue) Linux builds run in parallel.

I will remove cpp_empty appveyor configuration.
Could you ask appveyor guys for two concurrent builds? Cocos2dx has more than 11000 github stars. I heard that for well known projects appveyor guys do exception.

**Comment by minggo** [comment]
> Do you mean no for "cpp_test, cpp_empty, cocos_new for linux". ?
Current travis problem is with Mac build. (Please check travis queue) Linux builds run in parallel.

No, current problem is in appveyor instead of travis.

> I will remove cpp_empty appveyor configuration.
Could you ask appveyor guys for two concurrent builds? Cocos2dx has more than 11000 github stars. I heard that for well known projects appveyor guys do exception.

I don't know about it, i can have a try.

**Comment by crazyhappygame** [comment]
https://travis-ci.org/cocos2d/cocos2d-x/pull_requests - 10 builds in progress
https://travis-ci.org/cocos2d/cocos2d-x/builds - 2 builds in progress

https://ci.appveyor.com/project/minggo/cocos2d-x/history - 6 builds in progress

I will reduce number of appveyor Android builds configurations

**Pull request merged**
