### PR TITLE
fix : flickering when use fade animation with easing

### PR DESCRIPTION
**Pull request by keidroid**
invalid opacity value (when use fade animation with elastic or back easing)
ex. EaseBackIn::create(FadeTo::create(1.0f, 255.0f));

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Could you please add a test case?

**Comment by keidroid** [comment]
@minggo sorry, I added a test case to EaseAction test.

**Comment by minggo** [comment]
It is ok to add there.
Thanks.

**Comment by keidroid** [comment]
thanks for reviewing.

**Pull request closed without merging**
