### PR TITLE
from spine source code

### PR DESCRIPTION
**Pull request by ricardoquesada**
Related to:
- Github issue #16263
- Github issue #16294

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Not sure why github doesn't like my PR... it is very simple

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@minggo I can create a PR for v3.13... let me know if you want it.

**Comment by minggo** [comment]
Yes, please.

**Comment by minggo** [comment]
Thanks.

**Comment by ricardoquesada** [comment]
done:
- v3.13 branch PR: https://github.com/cocos2d/cocos2d-x/pull/16340

**Comment by minggo** [comment]
thanks @ricardoquesada

**Pull request merged**
