### PR TITLE
V3: Window 10 UWP project fixes

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates the Win10 UWP projects to correctly build with the final release version of Visual Studio 2015. Changes were made to the Windows 10 UWP cpp template files so it can pass the Windows App Certification (WACK) tests. The Windows 8.1 cpp templates were also updated to pass the latest WACK tests.

### CODE REVIEW

**Comment by KelvinJin** [comment]
:+1:

**Comment by pandamicro** [comment]
Hi, Dale, thanks for your contribution. Can you fix the conflict and squash the commits ?

**Comment by stammen** [comment]
Will do. Thanks.

**Comment by stammen** [comment]
@pandamicro fixed in PR https://github.com/cocos2d/cocos2d-x/pull/13452

**Pull request closed without merging**
