### PR TITLE
Clang static analyzer crash fix

### PR DESCRIPTION
**Pull request by newnon**
Clang static analyzer crash on this two lines
just ignore it in analyzer

### CODE REVIEW

**Comment by minggo** [comment]
@newnon 
Why it will crash?

**Comment by minggo** [comment]
And how did you use clang to do static analyzation?
Is there any document for it?

**Comment by newnon** [comment]
Simplest way to run it just run XCode - Analyze it will run CLang static analyzer for whole project. but unfortunately it will crash on this 2 files, after some research if found that it crashes on this 2 lines of code

**Comment by newnon** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Thanks @newnon , i will try it.

**Comment by minggo** [comment]
Yep, i have tried, and met the problem you said.
Do you know why it will cause crash?

**Comment by newnon** [comment]
No i have absolutely no idea why, but i think it's a clang bug. But the simplest way to fix it just add this few lines.

**Comment by minggo** [comment]
Ok.
Could you please add some comment for these added codes?

**Pull request merged**
