### PR TITLE
Josh/winrt inplace editbox

### PR DESCRIPTION
**Pull request by joshbodily**
Updated to latest upstream v3 and copied to our corporate fork of cocos2d-x from joshbodily:cocos2d-x.  Added 2 other bug fixes that have gone into our company's version of Windows Edit Box (1) Font family & (2) Text Wrapping.

See original here => https://github.com/cocos2d/cocos2d-x/pull/14917

@stammen @minggo

### CODE REVIEW

**Comment by stammen** [comment]
@joshbodily  Please fix the build errors

Checking headers in: f:/jenkins/workspace/ccs-pr/node/windows-universal_bak/cocos
ui/UIEditBox/UIEditBoxImpl-winrt.cpp:
    #include "UIEditBoxImpl-winrt.h" should be #include "ui/UIEditBox/UIEditBoxImpl-winrt.h"
ui/UIEditBox/UIEditBoxImpl-winrt.h:
    #include "UIEditBoxImpl-common.h" should be #include "ui/UIEditBox/UIEditBoxImpl-common.h"
Total: 2 errors in 2 files

**Comment by joshbodily** [comment]
Oops, fixing...

**Comment by minggo** [comment]
@stammen Is it ok to be merged?

**Comment by stammen** [comment]
@joshbodily There seems to be an issue with the text input. 

The 53 Node::UI./ 1.GUI Dynamic Create Test / 1, EditBox Test comes up looking like

image

However, when I click on the text field I get

image

Would you please investigate?

**Comment by joshbodily** [comment]
So, the placeholder label & label are CCLabels, correct?  I could not, for
the life of me, figure out how to get Unicode chars to show up in a CCLabel
😕. I think the original impl of UIEditBox (for winrt) had the same
problem, not surprisingly, since it would be an issue w/ CCLabel more than
w/ UIEditBox-impl.  Would it make sense at this point to file an issue on it in CCLabel and address is separately from this PR, I wouldn't mind taking a look at it.  I should have some bandwidth next week.

**Comment by joshbodily** [comment]
untitled

**Comment by stammen** [comment]
@minggo Go ahead and pull this PR. @joshbodily and I will look into the unicode problem as a separate issue. @joshbodily Thanks for all of your work on this. Great job!

**Comment by stammen** [comment]
@joshbodily Go ahead and open the unicode problem as a new issue.

**Comment by minggo** [comment]
> @minggo Go ahead and pull this PR

@stammen Did you mean i can merge this PR?

**Comment by stammen** [comment]
@minggo yes go ahead and merge.

**Comment by minggo** [comment]
Thanks guys.

**Comment by joshbodily** [comment]
Thank you 👍 .  I'll file a ticket on the CCLabel issue this week and start working on that.

**Pull request merged**
