### PR TITLE
V3 remove WP8 project files

### PR DESCRIPTION
**Pull request by stammen**
This pull request removes all WP8 files from cocos2d-x v3.6. Support for WP8 is discontinued starting with cocos2d-x v3.6. The removal of WP8 from cocos2d-x v3.6 was approved by Ricardo, Minggo and Walter.

This pull request also updates chipmunk and freetype for the Windows 8.1 Universal App
chipmunk v.6.2.2 (removes debug info from release libs)
freetype 2.5.5

This pull request also removes png, tiff and jpeg for Windows 8.1 Universal Apps. These apps now use the Windows Image Component to handle these image types.

This pull request depends on the updated dependencies in the pull request

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/124

### CODE REVIEW

**Comment by stammen** [comment]
This pull request depends on the updated dependencies in the pull request

cocos2d/cocos2d-x-3rd-party-libs-bin#124

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@andyque 
Please remove WP8 build in jenkins.

**Comment by zilongshanren** [comment]
@minggo 
Already removed. [ci rebuild]

**Comment by minggo** [comment]
Thanks @andyque .

**Pull request merged**
