### PR TITLE
Adding the gles2 blackberry version.

### PR DESCRIPTION
**Pull request by dducharme**
First version of the BlackBerry port of cocos2d-x.  Particles not working and tiff support is not in yet.

### CODE REVIEW

**Comment by walzer** [comment]
The grskia lib is tooooo huge. Can we link it and include its header files from bb sdk?

**Comment by dducharme** [comment]
Hey Walzer,

Grskia is the same size as it was in the last cocos repo.  Grskia is not a part of the current sdk.  We require it for font rendering. 
- Dale

----- Original Message -----

**Comment by dumganhar** [comment]
Hi, Dale,
I think it's better to create a 'extensions/proj.blackberry' folder and move .cproject,.project to this folder.

**Comment by dumganhar** [comment]
Hello, Dale,
Do you still focus on this issue?

**Comment by dducharme** [comment]
Hi James,

I was away on holidays last week. I'll be looking at this again this week.
- Dale

**Comment by dumganhar** [comment]
OK :)

**Comment by dumganhar** [comment]
Hi, Dale,
This pull request can't be auto-merged, you should pull the latest codes of cocos2d-x gles20 branch. If no conflicts, just commit them to your remote repo, this PR will be auto-updated, and you don't need to send a PR again.

**Comment by dumganhar** [comment]
Closed this PR since it's merged in the PR #1202.

**Pull request closed without merging**
