### PR TITLE
fix setflip for batch sprite

### PR DESCRIPTION
**Pull request by super626**
Since we use _quad.bl, _quad.br, _quad.tl, _quad.tr, we should modify the texture coordinates of it according to flip flag.

### CODE REVIEW

**Comment by super626** [comment]
@fusijie 
It is maintained by you. Can you confirm this modification?

**Comment by super626** [comment]
move from #14673

**Comment by minggo** [comment]
Why need to modify like this?
Any problem of current implementation?

**Comment by super626** [comment]
111.tmx here failed to display, http://pan.baidu.com/s/1skc4wJr

It shows as following,
5 pic

**Comment by super626** [comment]
@minggo , @ricardoquesada Can you help to review this PR?

**Comment by ricardoquesada** [comment]
what is the best way to reproduce the bug? could you add a test case?
thanks.

**Comment by super626** [comment]
@ricardoquesada 
I added a tmx with filpped spritebatch test.

**Comment by ricardoquesada** [comment]
thanks. merged

**Comment by ricardoquesada** [comment]
sorry, I merged but then I revert the merge because it was merged in v3.10 and I don't control v3.10.
If you send the PR against v3, I'll merge it in v3.

**Pull request merged**
