### PR TITLE
Fix quickly click mouse in "41:Node:Physics -> 6:joints" in cpp-test may cause program crash

### PR DESCRIPTION
**Pull request by xiaofeng11**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Please fix compilation issues

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
The compilation passed, @WenhaiLin please review

**Comment by WenhaiLin** [comment]
@pandamicro It's OK for merge.

**Pull request merged**
