### PR TITLE
Adds `std::nothrow` to the `new` statements

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
@zilongshanren Please review this PR

**Comment by zilongshanren** [comment]
@WenhaiLin
It looks good to me.

**Comment by pandamicro** [comment]
@ricardoquesada Can you approve this PR and merge it ?

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@pandamicro ok for me. thanks.

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Pull request merged**
