### PR TITLE
FEATURE 8766

### PR DESCRIPTION
**Pull request by Sheado**
Added the ability to hide or show the cursor on desktop builds.

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
But we can not add a function that only takes effect on some platforms.
@ricardoquesada 
What do you think?

**Comment by darkdukey** [comment]
I think it's okey, for example desktop don't have accelerometer support. But mobile has them.

we probably need to remove controller code from this PR, since it's been working on #10503

**Comment by darkdukey** [comment]
I clean up the code and create test case at #10720
Close this PR to avoid confusion. Credit goes to @Sheado

**Comment by zilongshanren** [comment]
[ci rebuild]

**Pull request closed without merging**
