### PR TITLE
fix for platforms that do not support VAO's

### PR DESCRIPTION
**Pull request by mannewalis**

### CODE REVIEW

**Comment by stammen** [comment]
@mannewalis This fixed the rendering in the Win32 and Windows 8.1 Phone/Store test apps. However, I am seeing crashes in the Node:Particle3D (PU) tests in CCVertextIndexBuffer.cpp. Just go to the second test and Win32 version will crash around line 214. I am seeing similar crashes on Windows Phone 8.1. It seems to be related to platforms with no VAO support.

**Comment by mannewalis** [comment]
ok thanks, I will take a look.

**Comment by stammen** [comment]
Android builds also appear to be broken by recent CCVertextIndexBuffer.cpp changes

D:\GitHub\cocos2d-x-v4\build../cocos/renderer/CCVertexIndexData.cpp: In constructor 'cocos2d::VertexData::VertexData(
D:\GitHub\cocos2d-x-v4\build../cocos/renderer/CCVertexIndexData.cpp:51:30: error: 'Director' has not been declared

D:\GitHub\cocos2d-x-v4\build../cocos/renderer/CCVertexIndexData.cpp: In destructor 'virtual cocos2d::VertexData::~V
D:\GitHub\cocos2d-x-v4\build../cocos/renderer/CCVertexIndexData.cpp:70:5: error: 'Director' has not been declared

**Comment by mannewalis** [comment]
ok that is fixed https://github.com/cocos2d/cocos2d-x/pull/10567

**Comment by stammen** [comment]
Thanks. I noticed that Android also crashes on the 2nd Node:Particle3D (PU) test.

**Comment by mannewalis** [comment]
So I get a crash here... But I disabled VAO on OSX and ran it... Not sure if that really duplicates the issue or not.

#0  0x000000010df12969 in std::__1::vector<cocos2d::BaseLight*, std::__1::allocator<cocos2d::BaseLight*> >::size() const [inlined] at /Applications/Xcode6.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:656
#1  0x000000010df12969 in cocos2d::MeshCommand::execute() at /Users/justin/cocos/cocos2d-x.fork/cocos/renderer/CCMeshCommand.cpp:340
#2  0x000000010e6fce4a in cocos2d::Renderer::processRenderCommand(cocos2d::RenderCommand_) at /Users/justin/cocos/cocos2d-x.fork/cocos/renderer/CCRenderer.cpp:462
#3  0x000000010e6fee93 in cocos2d::Renderer::visitRenderQueue(cocos2d::RenderQueue&) at /Users/justin/cocos/cocos2d-x.fork/cocos/renderer/CCRenderer.cpp:591
#4  0x000000010e6ff0f7 in cocos2d::Renderer::render() at /Users/justin/cocos/cocos2d-x.fork/cocos/renderer/CCRenderer.cpp:615
#5  0x000000010e3a39e7 in cocos2d::Scene::render(cocos2d::Renderer_) at /Users/justin/cocos/cocos2d-x.fork/cocos/2d/CCScene.cpp:156
#6  0x000000010e03ba76 in cocos2d::Director::drawScene() at /Users/justin/cocos/cocos2d-x.fork/cocos/base/CCDirector.cpp:300

**Comment by mannewalis** [comment]
Actually I get a crash there either way.

**Comment by mannewalis** [comment]
Yeah there's lot of places assuming there's a scene... They crash periodically.

Can you email me the crash log you are getting?

```
const auto& lights = Director::getInstance()->getRunningScene()->getLights();
```

**Pull request merged**
