### PR TITLE
fix rendering font with not null line gap

### PR DESCRIPTION
**Pull request by newnon**
cocos2d-x does not respect line gap in ttf font

### CODE REVIEW

**Comment by minggo** [comment]
how to reproduce it?

**Comment by newnon** [comment]
You need any font with not null line gap you can see it on second picture [http://designwithfontforge.com/en-US/Line_Spacing.html](http://designwithfontforge.com/en-US/Line_Spacing.html), you need for example 2 lines text and then draw once with system render once with own and you will see that line spacing is different

**Comment by minggo** [comment]
could you please add a test case for it

**Comment by zilongshanren** [comment]
@newnon 
What's the difference between `lineSpacing` and `linGap`?  I think there is already a API for changing the line spacing between lines.

**Comment by newnon** [comment]
lineSpacing is our own font param and linGap is internal TTF font param without it font will be misalignment (half of them added to top space half to bottom)

**Comment by zilongshanren** [comment]
@newnon 
It would be good if you could provide a test case to reproduce the issue you talked above.
And the test case could also prevent future false regression.

**Comment by newnon** [comment]
some code refining & test case

**Comment by newnon** [comment]
@minggo have you looked at this?

**Comment by minggo** [comment]
@newnon i haven't tested it. I will test i ASAP.

**Comment by minggo** [comment]
Yep, it looks good to me.

**Comment by minggo** [comment]
@newnon why not use existing ttf file to avoid making the repo bigger.

**Comment by newnon** [comment]
all fonts that included have line gap = 0 or bad
AmericanTypeWriter for example have different values for different systems HH Line Gap & Type Line Gap must be same because (you can see example for bad font on this screen http://www.high-logic.com/fontcreator/manual10/fontcreator_039_font_settings_metrics.png) right params (ascender descender and line gap) used only by mac & iOS and left for params for all other system include lib freetype. 
You can include this code without test i think it is not so bad

**Comment by minggo** [comment]
Ok, thanks. The test case is needed.

**Comment by newnon** [comment]
i can take another font or remove most letters from this and it will be very small

**Comment by minggo** [comment]
@newnon thanks. And please remove the commit log too or it will in the history.

**Comment by newnon** [comment]
small font for test

**Pull request merged**
