### PR TITLE
Fix crash on Windows if pass string more than 16kb to cocos2d::log

### PR DESCRIPTION
**Pull request by Dimon4eg**
Fixed two issues if pass string bigger 16kb to cocos2d::log:
- crash on Windows
- string is cut in output of Visual Studio

Tested on Windows, Android and iOS.

### CODE REVIEW

**Comment by zilongshanren** [comment]
Hi, @Dimon4eg 
This PR seems conflict with main repository. Could you resolve it?
Thanks.

**Comment by Dimon4eg** [comment]
How can I resolve?
I've latest v3 branch and no conflicts.

**Comment by zilongshanren** [comment]
@Dimon4eg 
Sorry for the late reply.
I think you should fetch cocos2d-x upstream and merge the v3 branch to your local branch.
It may have conflicts, you need to resolve it.

**Comment by Dimon4eg** [comment]
I've created new PR #12369.

**Pull request closed without merging**
