### PR TITLE
newest V3 flatbuffers

### PR DESCRIPTION
**Pull request by pipu**

### CODE REVIEW

**Comment by minggo** [comment]
Please fix compiling error.
We plan to release v3.3rc1 on Nov.28, and it is needed in this version.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by stammen** [comment]
This pull request will break the Windows 8.1 universal app as the files were not added to the universal app projects.

**Comment by minggo** [comment]
Thanks @stammen.
@pipu 
Could you please add file for Windows 8.1 too?

**Comment by minggo** [comment]
Why close it?

**Comment by minggo** [comment]
Please add commit in the same PR.

**Comment by minggo** [comment]
Don't create a new one as you did before.

**Pull request closed without merging**
