### PR TITLE
Add getStringLength() support for UITextField

### PR DESCRIPTION
**Pull request by zhouxiaoxiaoxujian**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@zhouxiaoxiaoxujian 
please add const keyword to the end of the function, thanks.

**Comment by zhouxiaoxiaoxujian** [comment]
@andyque
const keyword has be added to getStringLegnth() function, please check PR, thanks.

**Comment by zilongshanren** [comment]
@minggo  
This PR could be merged now.

**Comment by minggo** [comment]
@zhouxiaoxiaoxujian
Could you fix the conflict?
Thanks.

**Comment by zhouxiaoxiaoxujian** [comment]
OK, Should I fix the conflict in new PR?

**Comment by minggo** [comment]
I have asked @andyque to help to fix it.
Thanks.

**Comment by zilongshanren** [comment]
This PR will be merged via https://github.com/cocos2d/cocos2d-x/pull/7015

**Pull request merged**
