### PR TITLE
Update template/android/copy_files.sh

### PR DESCRIPTION
**Pull request by toughrogrammer**
Creating android project did not work well because copy_files.sh did not copy library source.
( refer : http://cocos2d-x.org/boards/6/topics/17075?r=17268#message-17268 )

I added code about copy library source.
Please Check :)

### CODE REVIEW

**Comment by dumganhar** [comment]
Hey, this is not a bug. You should import 'libcocos2dx'(cocos2dx/platform/android/java) in eclipse now.

**Comment by dumganhar** [comment]
All projects will depend on it.

**Comment by toughrogrammer** [comment]
Oh, i don't know that.... 
I think that must post that factor on cocos2d-x-2.0.3 download page.
(I count't see that)

**Comment by dumganhar** [comment]
Sorry for that we forgot to update the wiki page.
Thanks for reminding us. We will update it ASAP.

**Comment by dumganhar** [comment]
So could this Pull Request be closed?

**Comment by toughrogrammer** [comment]
Yeah. Thank you.

**Pull request closed without merging**
