### PR TITLE
fix CCScale9Sprite bugs

### PR DESCRIPTION
**Pull request by biteforest**
fix CCScale9Sprite bugs. when  reading spriteframe frome plist, spriteframe's ratote may be seted. but CCScale9Sprite can't parse spriteframe right. Another bugs is inset of ccscale9sprite.

### CODE REVIEW

**Comment by folecr** [comment]
Hi,

Could you please add a test case for the bugs you fixed?
Current test cases are here:
 https://github.com/cocos2d/cocos2d-js-tests/blob/master/tests/ExtensionsTest/S9SpriteTest/S9SpriteTest.js

Thanks.

**Comment by dumganhar** [comment]
@biteforest 
Also, why did you modify the whole file?
I couldn't see what you changed on github. Was the `RETURN` symbol different?

**Comment by biteforest** [comment]
sorry,its my first time to use github, iam not good at git. next time i will push the bug branch instead of master branch. 

已从手机发送

-------- Original message --------
Subject: Re: [cocos2d-x] fix CCScale9Sprite bugs (#2083)

**Comment by biteforest** [comment]
ok, if im free this weekend, i ll try

已从手机发送

-------- Original message --------
Subject: Re: [cocos2d-x] fix CCScale9Sprite bugs (#2083)

**Comment by biteforest** [comment]
@dumganhar @folecr  
Reject this pull request, i'll send pull request later.

**Comment by biteforest** [comment]
@dumganhar 
i don't why the whole was changed. but i review this change by tortoisgit, the change of file content is ok

**Comment by folecr** [comment]
@biteforest I think your editor is saving the files after changing the whitespace. You should be able to disable that feature.

You can see the diffs on github with whitespace changes ignored by adding a ?w=1 to the URL (from https://github.com/blog/967-github-secrets)

**Comment by biteforest** [comment]
@folecr i copy the two different files and view them in hexeditor, but I never find any diffrent between white spaces. you can try to merge this branch in your test branch. I really don't know what's the problem.

**Comment by minggo** [comment]
May be the line break is different. Did you use VS line break style?

**Pull request closed without merging**
