### PR TITLE
Fixed: when body mass infinity, setGravityEnable(false) does not work

### PR DESCRIPTION
**Pull request by varvelworld**
Fixed: when body mass infinity, function PhysicsBody::setGravityEnable(false) does not work

### CODE REVIEW

**Comment by minggo** [comment]
@varvelworld 
It is a bug of chipmunk?

**Comment by varvelworld** [comment]
@minggo 
Chipmunk does not provide function to set gravity enable. In PhysicsBody, when the GravityEnable is false, give the body a anti-gravity force, I think that this implementation is not good. So I change the chipmunk code directly.

And why is win32_win7 building in jenkins success? but the others are failed.

**Comment by minggo** [comment]
About jenkins, i think it is not your problem. It is about network issue.
@boyu0
Could you take a look about this PR?

**Comment by minggo** [comment]
chipmunk is written in c, so you can not use bool, true.

**Comment by boyu0** [comment]
I think change chipmunk code is not an option. we need to keep chipmunk easy to update, besides, we are going to build chipmunk to a ".a" library...
I think set body mass to infinity is not necessary, there are no "infinity mass object" in real world, I think only the static bodies need to set mass to infinity.
So I think we can keep this bug unfixed unless we find a way to fix it without change the chipmunk code...

**Comment by minggo** [comment]
I agree with @boyu0, change chipmunk codes will make it hard to update.

**Comment by varvelworld** [comment]
I agree with @boyu0 ,too. It's not eassy to update. But I think set body mass to infinity is necessary sometimes.
Now, the static body ( setDynamic(false) ) can't set velocity.I remember that in box2d the static body can has velocity.If I can set body mass to infinity, it is same with "static body" in box2d.

**Comment by boyu0** [comment]
@varvelworld 
ok, so I think which we need is a movable static body, not a dynamic body with infinity mass, I will check is there a possible way to implement this...

**Comment by varvelworld** [comment]
@boyu0 
Look this pr.Thank you!
https://github.com/cocos2d/cocos2d-x/pull/7707

**Comment by minggo** [comment]
@varvelworld 
Can close this PR?

**Comment by varvelworld** [comment]
@minggo  ok.
@boyu0  But I still think that it's a briefer way with modify chipmunk code directly, if we do not care update.

**Comment by minggo** [comment]
@varvelworld 
Update 3rd party is important. We should make it easy to update.
Or will you send a patch to chipmunk?

**Comment by varvelworld** [comment]
@minggo ok.I agree with you. I wiil try.

**Pull request closed without merging**
