### PR TITLE
Add tizen support 

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by minggo** [comment]
It looks good to me, just a few questions:
- It modified `cocos/scripting/lua-bindings/auto/lua_cocos2dx_audioengine_auto.cpp/.hpp` manually, it will be override automatically by travis commits.
- It added `templates/lua-template-default/frameworks/runtime-src/proj.tizen/res/.gitkeep`, what's it?
- It used `templates/lua-template-default/frameworks/runtime-src/proj.tizen/copy_resource.sh` to copy needed resources for Tizen platform, can the script run on windows? It is a shell script.
- Why added these lua files
  - tests/lua-tests/src/ByteCodeEncryptTest/ByteCodeEncryptTest.lua
  -  tests/lua-tests/src/Particle3DTest/Particle3DTest.lua
  -  tests/lua-tests/src/mainMenu.lua

**Comment by zilongshanren** [comment]
@minggo 
1. If `lua_cocos2dx_audioengine_auto` file will be  overrided by travis, I think it's OK. I have already modified the `AudioEngine.cpp` file.
2.  Because `templates/lua-template-default/frameworks/runtime-src/proj.tizen/res/` is a empty folder, github can't push empty folder, the `.gitkeep` file is for resolving this issue.
3. The `copy_resoruce.sh` issue, I will test it on Windows.
4. These lua files are already exists, I only modify them...

**Comment by minggo** [comment]
> If lua_cocos2dx_audioengine_auto file will be overrided by travis, I think it's OK. I have already modified the AudioEngine.cpp file.

Does the bindings supports Tizen? If not, your changes will be lost.

> These lua files are already exists, I only modify them...

Ok, i have to pull it to view the diff in my local machine

**Comment by minggo** [comment]
Ok, the lua files modification looks good to me

**Comment by zilongshanren** [comment]
@minggo 

> Does the bindings supports Tizen? If not, your changes will be lost.
> my changes doesn't matter here, it could be safely override...

Because the bindings-generator could take care of it.

**Comment by minggo** [comment]
I didn't find any modification of bindings-generator. Did you modify in other places?

**Pull request merged**
