### PR TITLE
receive content data even though status code is not 2xx

### PR DESCRIPTION
**Pull request by seobyeongky**

### CODE REVIEW

**Comment by samuele3hu** [comment]
Did you mean that in current mechanism httpclient don't get the error response data.

**Comment by seobyeongky** [comment]
Yes

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by Mazyod** [comment]
This is cool, but unfortunately I didn't see it and submitted a similar PR: https://github.com/cocos2d/cocos2d-x/pull/10543.

I think both PRs are good, because:
- This one covers Android
- My PR replaces the code with assigning a backend error, so the HTTP client works consistently with the old one, and the developer is informed of such behavior.

**Comment by seobyeongky** [comment]
Oh, I missed about the backend error feedback. ^^; I think you are right.

**Comment by minggo** [comment]
Can we close this pull request?

**Comment by Mazyod** [comment]
@minggo I updated my comment, this PR has android related code, as well.

**Comment by minggo** [comment]
So we should merge the two PR into one.
@seobyeongky will you update this PR to include @Mazyod 's modification?

**Comment by seobyeongky** [comment]
OK I will soon. I am going home.

**Comment by seobyeongky** [comment]
OK I will

**Comment by minggo** [comment]
Thanks.

**Comment by seobyeongky** [comment]
Included @Mazyod 's modification

**Comment by Mazyod** [comment]
oh noes .. merge conflicts. It seems more people are submitting PRs for this: #10800

**Comment by samuele3hu** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@seobyeongky 
Could you please fix conflict?

**Comment by seobyeongky** [comment]
OK

**Comment by Mazyod** [comment]
@minggo looks good to me now

**Comment by Mazyod** [comment]
I hope you guys didn't forget about this ^^;

**Comment by minggo** [comment]
Sorry about it.

**Comment by Mazyod** [comment]
Awesome, thanks @minggo !

**Comment by minggo** [comment]
Thanks @Mazyod for noticing me.
Thanks @seobyeongky .

**Pull request merged**
