### PR TITLE
repair linux build and add 64-bit configurations for all linux eclipse projects

### PR DESCRIPTION
**Pull request by ivzave**
didn't test 32-bit builds but should work fine

### CODE REVIEW

**Comment by dumganhar** [comment]
Makefile can work for 32bit and 64bit, but eclipse projects can't work for both 32 and 64bit.
Any idea about that?
Thanks.

**Comment by ivzave** [comment]
I've added 2 separate configurations for 64-bit - Debug64 and Release64. This should work, am I wrong?

**Comment by dumganhar** [comment]
Got it,i will test it.Thanks.
ÔÚ 2012-12-22 ÏÂÎç9:31£¬"Igor Zavorotkin" notifications@github.comÐ´µÀ£º

**Comment by dumganhar** [comment]
Thank you.
It's merged at https://github.com/cocos2d/cocos2d-x/pull/1779.

**Pull request merged**
