### PR TITLE
Add manual Lua binding for TimelineAction:setLastFrameCallFunc()

### PR DESCRIPTION
**Pull request by xpol**
1. Add manual Lua binding for TimelineAction:setLastFrameCallFunc()
2. enable and update related test.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@chengstory 
Please take a look.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by chengstory** [comment]
Thanks  @xpol,  @minggo,  @andyque,  It can be merged.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by xpol** [comment]
Will this be merged soon?

**Comment by coolxiaox** [comment]
Will this be merged soon?

**Comment by xpol** [comment]
@coolxiaox I suggest you use workflow [like this (Chinese)](http://xpol.logdown.com/posts/316157-how-to-elegantly-add-or-modify-lua-bindings-for-cocos2d-x).

**Comment by coolxiaox** [comment]
@xpol  thanks

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
