### PR TITLE
Merge jp support

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by plungeint** [comment]
Hi,

It would be great if we had support for Catalan language. We use it in our games, and other developers I guess.

Thanks a lot!

**Comment by dumganhar** [comment]
Hi, @plungeint 
Could you add this language support and send the Pull Request to us?

**Comment by plungeint** [comment]
ok, I'll try it, I never used GIT :-P 

Thanks!

**Comment by dumganhar** [comment]
It isn't hard to use git. Have a try, besides, don't forget to add it for
all platforms, thanks.
If you have troubles in using git, feel free to let me know. o_O

**Pull request merged**
