### PR TITLE
Adds download-deps.py for v2 branch

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
@sbc100, `nacl` sdk seems update something. Now travis-ci build of native client port was broken.
Could you help to check out?
Please refer to https://travis-ci.org/cocos2d/cocos2d-x/jobs/24624598
It seems that `libfreetype2` didn't link `libbz.so/.a` , or there isn't any libbz.so in current latest sdk.

BTW, we have stripped most binary files in our repo. 
Please test it using `v2` (old master) branch. After you clone the repo, please run `./download-deps.py` to download 3rd libraries. Thanks.

**Comment by sbc100** [comment]
Hi James.  I'll take look.  I've also been meaning to look into a recent regression in chrome where cocos2dx apps have stopped working due to some kind of GL error.

**Comment by sbc100** [comment]
I'm fixing this issue now.   Just revived my branches and rebased onto the new v2 git history.

**Comment by dumganhar** [comment]
@sbc100 , Thanks.
The way to check out a new local `v2` branch to synchronize the remote `v2` is:
Assume you have a remote named as `cocos2d-x` which points to the official repo.

```
$ git fetch cocos2d-x v2
$ git checkout -b new_v2 FETCH_HEAD
$ git cherry-pick `commit id which your old v2 branch`
```

Using `rebase` seems to be not a good solution. If you still face the rebasing problem. Please try my approach . Thanks.

**Comment by sbc100** [comment]
So the bzip2 issues was resolved by publishing a new version of the NaCl SDK where libfreetype was built without bzip2 support.

I've successfully manages to rebase all my branch on the new v2 so hopefully there will be more PRs coming.

In the mean time the v2 branch should be green on travis the next time it builds.

**Comment by dumganhar** [comment]
Thanks,Sam.
2014-6-2 上午6:30于 "Sam Clegg" notifications@github.com写道：

**Pull request merged**
