### PR TITLE
add customization to UIButton and UIPageView

### PR DESCRIPTION
**Pull request by zilongshanren**
1. add zoomScale to UIButton, now developers could customize how much zoom scale is when pressing a button
2. add customScrollThreshold to UIPageView, now developers could determine the swipe distance to trigger a PageView scroll event.
3. add tests to test 1&2.

These two modifications are minor improvements over the hard-code value in our widgets.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by cmzx3444** [comment]
UIButton can suport pressed color change?

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@zii Thanks, I'm glad this patch is useful for you.
@cmzx3444 
What do you mean by "support pressed color change?". You could change the color of UIButton when touch began event occurs.

**Comment by cmzx3444** [comment]
Yes,I think it's usefull, so I don't need another image for pressed status

**Comment by zilongshanren** [comment]
@cmzx3444 
We might need to provide methods to automatically generate pressed state and disabled state images by using shaders or something else.

**Pull request merged**
