### PR TITLE
Updated angle to commit 4a980d2612

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates the Windows 8.1 versions of ANGLE for Windows Store and Windows Phone. This version of ANGLE uses the new interface approved by the ANGLE Project. Please note that the Universal App on the cocos2d-x v3 branch will be broken by this new version of ANGLE until this pull request becomes part of the download-deps. This pull request depends on the following pull request containing the new ANGLE libs and header files:

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/56

### CODE REVIEW

**Comment by minggo** [comment]
Why update Angle?
Does it fix some bugs or performance improved or others?

**Comment by stammen** [comment]
This version now uses the approved interface by the ANGLE Project. Also it has slightly better frame rate and fixes a bug with negative viewport values. Mipmap bugs were also fixed by the angle team.

**Comment by minggo** [comment]
Thanks.
What did you mean `approved interface`?

**Comment by stammen** [comment]
Google AngleProject has accepted the interface changes needed to create the GL Context from the app to angle via EGL. This mean that the Angle interface should now be stable. The code is currently being merged into AngleProject. In a few months, we will probably be able get Angle from the main AngleProject repo and not the MS Open Tech repo.

**Pull request merged**
