### PR TITLE
Lua: add manual bindings for EventDispatcher::addCustomEventListener

### PR DESCRIPTION
**Pull request by ghost**
ref to 
1. https://github.com/cocos2d/cocos2d-x/pull/13167
2. https://github.com/cocos2d/cocos2d-x/issues/13165

### CODE REVIEW

**Comment by yinjimmy** [comment]
test this please

**Comment by minggo** [comment]
Why move the binding codes to manually binding codes? How to test it?

**Comment by ghost** [comment]
> Why move the binding codes to manually binding codes?

some codes modified.

```
        ok &= luaval_to_std_string(tolua_S, 2,&arg0, "cc.EventDispatcher:addCustomEventListener");

        do {
			// Lambda binding for lua is not supported.
			assert(false);
		} while(0)
		;
```

to

```c++
        ok &= luaval_to_std_string(tolua_S, 2,&arg0, "cc.EventDispatcher:addCustomEventListener");
        auto callback = LuaCustomEventListener(tolua_S, 3);

        if(!ok)
        {
            tolua_error(tolua_S,"invalid arguments in function 'lua_cocos2dx_EventDispatcher_addCustomEventListener'", nullptr);
            return 0;
        }
```

> How to test it?

```lua
    eventDispatcher:addCustomEventListener('event_custom' ,function(...)
        print('event_custom')
    end)

    eventDispatcher:dispatchCustomEvent("event_custom")
```
https://github.com/cocos2d/cocos2d-x/commit/8f003f09feeebacad402facc4d426c4652c4b232#diff-d1b608b676db982d90a56adbe86fd3deR617

**Comment by minggo** [comment]
Sounds reasonable, thanks.

**Pull request merged**
