### PR TITLE
fix the resolution issues when create full screen app

### PR DESCRIPTION
**Pull request by Mee-gu**
fix the resolution issues when creating a full-screen app. 
the issue is discussed [here](https://github.com/cocos2d/cocos2d-x/pull/17309)

### CODE REVIEW

**Comment by minggo** [comment]
glfw can register callback for resolution changing, i think it is more reasonable to do some operation there.

**Comment by Mee-gu** [comment]
`glfwWaitEvents` behaves exactly like `glfwPollEvents`, `glfwWaitEvents` is a better choice here since it only needs to update the contents of the window.
Besides, `glfwWaitEvents` as well as `glfwPollEvents` can't be called from a glfw callback.

**Comment by Bilalmirza** [comment]
@Mee-gu  @minggo 
Just few issues I want to point out.
On macbook 2018 15"

1024x640: borders on left and right. cant move the mouse to screen ends either.
fps: 2156

1280x800: works fine
fps: 536

1440x900: works fine
fps: 391


After this it gets weird especially with the fps

1680x1050: works fine... i think the display also loses sharpness you can see some on fonts.
fps: ~1200 

1920x1280: works fine
fps: 740

Screenshots: https://www.dropbox.com/sh/4mqxarh3bjj1usx/AADjhHhDqflSqdKvW3fI18AEa?dl=0

**Comment by Mee-gu** [comment]
@Bilalmirza As for the black borders on both left and right, I try lots of methods but change nothing. So I create an [issue](https://github.com/glfw/glfw/issues/1551) in glfw GitHub hoping for a good workaround.
BTW, I can't view your screenshots, maybe you can directly paste in the edit box.

**Comment by Bilalmirza** [comment]
@mee-gu any idea why fps is so much better in higher resolutions. probably because of retina being disabled in last 2 i think.

**Comment by Mee-gu** [comment]
@Bilalmirza How did you  get the fps?

**Comment by Bilalmirza** [comment]
@Mee-gu    Appdelegate
director->setDisplayStats(true);

    // set FPS. the default value is 1.0/60 if you don't call this
    director->setAnimationInterval(1.0f / 3500);
    glfwSwapInterval(0);

**Comment by Bilalmirza** [comment]
I think this is the issue
https://github.com/cocos2d/cocos2d-x/issues/16561

**Comment by Bilalmirza** [comment]
I have a terrible fix for the fps. It also links the resolution to Display resolution.
You probably wont use this but here it goes.
in info.plist
add "High Resolution Capable" and set it to "NO"
in ccApplication
```
    NSWindow *nsWindow = glview->getCocoaWindow();
    [nsWindow.contentView setWantsBestResolutionOpenGLSurface:NO];

```

in CCGLViewImpl-desktop.cpp
```
    glfwWaitEvents();

//    setFrameSize(rect.size.width , rect.size.height);
    GLView::setFrameSize(rect.size.width , rect.size.height);
```
this prevents the call on updateFrameSize() // which really messes up the resolution.

now everything is fixed. The higher the display resolution in system preference the better the resolution in game.

**Pull request closed without merging**
