### PR TITLE
Added const qualification to some CCNode's getters

### PR DESCRIPTION
**Pull request by ghost**
As we want to be able to copy construct CCNode's subclasses we want to be able to do this:

```
class SubNode : public cocos2d::CCNode
{
public:
    SubNode(const SubNode& other)
    {
        this->setContentSize(other.getContentSize());
    }
};
```

So i've added constness to the following getters:

<ul>
<li>getTag()</li>
<li>getContentSize()</li>
<li>getChildrenCount()</li>
</ul>

Of course this are not the only methods that need const added, but seem the most obvious ones.
We cannot add const to all of them because implementations of them would need to be const as well.

### CODE REVIEW

**Comment by minggo** [comment]
I will review it ASAP.
Thank you @metalgit92.

**Comment by dumganhar** [comment]
You should also modify `CCScrollView::getContentSize` since it overrides the parent's method.

**Comment by gelldur** [comment]
Yeah finally const getters :)

**Comment by ghost** [comment]
@dumganhar I'll make another pull request to add more constness and begin adding methods to it.
@gelldur I've been missing them a lot too :)

**Pull request merged**
