### PR TITLE
Small fix: wrong link in Readme.

### PR DESCRIPTION
**Pull request by psineur**
subj

### CODE REVIEW

**Comment by walzer** [comment]
I'm so careless. Thank you for your fix!

**Comment by psineur** [comment]
BTW readme also have differencies in branches, maybe it should be the same in every branch with a little extra info about each branch.

**Comment by walzer** [comment]
oh, you remine me. I just remove the useless "airplaysdk" & "dev" branches. Now only master & bada. 
I try to merge bada port into master in this month :)

**Comment by psineur** [comment]
Great! Maniac work by the way - allmost all i can see in my GitHub news 
feed is your commits to cocos2d-x.
Thanks for all your work!

**Pull request merged**
