### PR TITLE
Update tiny obj loader and fix empty textrue

### LINKED ISSUE #12734: obj loading failed on windows
.obj file can be downloaded here,
http://pan.baidu.com/s/1kTgUdiJ

This obj file contains many objects, each objects have different vertex attributes.

### PR DESCRIPTION
**Pull request by super626**
fix #12734

### CODE REVIEW

**Comment by super626** [comment]
http://punchbox.info:3000/issues/20764

**Comment by pandamicro** [comment]
@dabingnn Please review

**Comment by super626** [comment]
[ci rebuild]

**Comment by super626** [comment]
1. update tinyobjloader to the latest version.
   https://github.com/syoyo/tinyobjloader
2. fix the render when texture is not exist. (In fact, it worked before material is added).

**Comment by dabingnn** [comment]
Thanks, Is there any documentation to show the changes in `tinyobjloader`?

**Comment by super626** [comment]
https://github.com/syoyo/tinyobjloader/blob/master/tiny_obj_loader.cc

**Comment by super626** [comment]
Update tinyobjloader from 0.9.6 to 0.9.13

**Comment by dabingnn** [comment]
@pandamicro It could be merged.

**Pull request merged**
