### PR TITLE
add WebP support

### PR DESCRIPTION
**Pull request by dualface**
> WebP is a new image format that provides lossless and lossy compression for images on the web. WebP lossless images are 28% smaller in size compared to PNGs. WebP lossy images are 25-34% smaller in size compared to JPEG images at equivalent SSIM index. WebP supports lossless transparency (also known as alpha channel) with just 22% additional bytes. WebP also supports features such as animation, ICC color profile, XMP meta-data and tiling.
> 
> https://developers.google.com/speed/standards/
### ENCODE IMAGE TO WebP

```
cwebp hello.png -o hello.webp
```
### LOAD WebP IN COCOS2D-X

```
CCSprite *sprite = CCSprite::create("hello.webp");
CCTextureCache::sharedTextureCache()->addImage("sheet.webp");
```

FOR RGB565, PLEASE USE PNG.

THANKS:

KunLun, Hui Wang

### CODE REVIEW

**Comment by Tsiannian** [comment]
sounds great! i will try it later.

**Comment by minggo** [comment]
I am not sure if WebP format is needed.

**Comment by dualface** [comment]
Use WebP, can create smaller game package.

Example:

```
RGB565
 JPG (quantity 90)  : 292KB
WebP (quantity 90)  : 154KB

RGBA8888
 PNG               : 405KB
WebP (quantity 95) : 185KB

```

**Comment by Tsiannian** [comment]
i test it on my device. i must say dulaface， you did a great job. i am surly confirm that cocos2d-x will add webp support sooner or later.

**Pull request closed without merging**
