### PR TITLE
add editbox ended event

### PR DESCRIPTION
**Pull request by yongkangchen**

### CODE REVIEW

**Comment by zilongshanren** [comment]
Thanks @yongkangchen 
  When would `controlTextDidEndEditing` method will be called? Could you please add some tests to stress this fix?

**Comment by yongkangchen** [comment]
`controlTextDidEndEditing` method will be called when press return/enter

usage:

```
input:registerScriptEditBoxHandler(function(eventName, sender)
        if eventName == "ended" then
            send()
        end
end)
```

**Comment by minggo** [comment]
@andyque 
How about this PR?

**Comment by zilongshanren** [comment]
@yongkangchen 
Hi, I think we should fix like this : https://github.com/cocos2d/cocos2d-x/pull/7645

**Comment by zilongshanren** [comment]
@minggo 
This PR could be closed now.

**Pull request merged**
