### PR TITLE
[Node::scheduleOnce]Fixed the callback will be executed multiple times if the value of delay parameter equal zero.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
@yangws @zilongshanren Please review this PR.

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@yangws  please review it.

**Comment by yangws** [comment]
reviewed OK, merge it please. @zilongshanren

**Pull request merged**
