### PR TITLE
fix warnings

### PR DESCRIPTION
**Pull request by minggo**
fix warnings

### CODE REVIEW

**Comment by mori1234** [comment]
NSSelectorFromString crash

CDAudioManager.m
selector:    NSSelectorFromString(@"handleInterruption")

terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CDAudioManager handleInterruption]: unrecognized selector sent to instance

change code 
selector:    NSSelectorFromString(@"handleInterruption")
-->
selector:@selector(handleInterruption:)

It works fine.

**Comment by minggo** [comment]
It is wired. Could you please show me how to reproduce it?

**Comment by mori1234** [comment]
i use SimpleAudioEngine.

1. audio pasue
  SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
  SimpleAudioEngine::getInstance()->pauseAllEffects();

2. vungle reward ad show 

repeat ----> 
terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CDAudioManager handleInterruption]: unrecognized selector sent to instance

Note that
CDAudioManager .m encoding 949 

To make a selector, NSSelectorFromString passes a UTF-8 encoded character representation of aSelectorName to sel_registerName and returns the value returned by that function. Note, therefore, that if the selector does not exist it is registered and the newly-registered selector is returned.
Recall that a colon (“:”) is part of a method name; setHeight is not the same as setHeight:.

may be
selector: NSSelectorFromString(@"handleInterruption")
missing colon(:)
selector: NSSelectorFromString(@"handleInterruption:")


I have not tested it.

**Comment by mori1234** [comment]
is missing colon(:) ?
selector: NSSelectorFromString(@"handleInterruption")
--->
selector: NSSelectorFromString(@"handleInterruption:")

**Comment by minggo** [comment]
Yep, i sent https://github.com/cocos2d/cocos2d-x/pull/18375 to fix it

**Pull request merged**
