### PR TITLE
Controller support for Win/Mac/Linux - Issue #9912

### PR DESCRIPTION
**Pull request by Sheado**
Added desktop controller support.
- Currently supports Mac, but should be a matter of ifdefs to support
  Windows and Linux
- Currently maps PS3 controller only
- Remaining tasks are tagged with the comment // TODO - controller

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
Looks like it's breaking the windows build, have you tried building it with cmake under windows? Let me know if you need help.

**Comment by Sheado** [comment]
Sorry about that. I didn't have a Windows environment setup at the time. I do now and it's almost fixed (still need to test it). My latest progress can be found here: https://github.com/Sheado/cocos2d-x/tree/v3-sheado

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
close it since  we don't plan to support it

**Pull request closed without merging**
