### PR TITLE
fix linker errors on osx related to iconv

### PR DESCRIPTION
**Pull request by mrexodia**
closes issue #20435

### CODE REVIEW

**Comment by minggo** [comment]
I can not find any difference from current implementation.

**Comment by mrexodia** [comment]
The difference is that is compiles now, where it didn’t before 🙂

I’m not really sure what’s going on, but for some reason it seems the cmake find_library does not find the right library (see issue for more details).

**Comment by minggo** [comment]
It is wired.

**Comment by mrexodia** [comment]
I am currently installing a VM with the latest OS X to see if this is also happening on a clean installation. My Macbook is from 2015 and has various upgrades so perhaps something is corrupted. Perhaps someone with a Mac could also verify if the `mac` target is compiling?

**Comment by minggo** [comment]
There is not problem in my MBP, and in many other MBPs that i know.

**Comment by mrexodia** [comment]
Which os are you running? Note that this is only for the “mac” target, the
ios works just fine. I’m still installing a VM with the latest and will
report back to you.

**Comment by mrexodia** [comment]
Okay I tried on a clean VM with Catalina and everything is working there. I guess I will do a clean installation of macOS Mojave and try that, likely something is messed up on my system only. If I find a workaround I will post it here, but I think this can be closed.

**Pull request closed without merging**
