### PR TITLE
use different separator on different platforms and make path length short

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by ghost** [comment]
we still have the same issue with this PR too. @minggo 
```
Build command failed.
Error while executing process E:\android-ndk-r13b\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Android.mk NDK_APPLICATION_MK=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=0 APP_PLATFORM=android-9 NDK_OUT=C:/cocos2d-x/tests/cpp-tests/proj.android-studio/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\build\intermediates\ndkBuild\release\lib NDK_TOOLCHAIN_VERSION=4.9 APP_PLATFORM=android-13 NDK_MODULE_PATH=C:\cocos2d-x;C:\cocos2d-x\cocos;C:\cocos2d-x\external -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: WARNING: Ignoring unknown import directory: C:\cocos2d-x    
Android NDK: C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Android.mk: Cannot find module with tag 'cocos' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
process_begin: CreateProcess(NULL, "", ...) failed.
Build command failed.
Error while executing process E:\android-ndk-r13b\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Android.mk NDK_APPLICATION_MK=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=1 APP_PLATFORM=android-9 NDK_OUT=C:/cocos2d-x/tests/cpp-tests/proj.android-studio/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\build\intermediates\ndkBuild\debug\lib NDK_TOOLCHAIN_VERSION=4.9 APP_PLATFORM=android-13 NDK_MODULE_PATH=C:\cocos2d-x;C:\cocos2d-x\cocos;C:\cocos2d-x\external -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: WARNING: Ignoring unknown import directory: C:\cocos2d-x    
Android NDK: C:\cocos2d-x\tests\cpp-tests\proj.android-studio\app\jni\Android.mk: Cannot find module with tag 'cocos' in import path    
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
Android NDK: The following directories were searched:    
Android NDK:         
process_begin: CreateProcess(NULL, "", ...) failed.
```
Btw i can build projects made with "cocos new" command , the problem is just the cpp-tests.

**Comment by ghost** [comment]
@minggo 
why do we use  `APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false` ?
for every project i'm adding these arguments to Application.mk and Android.mk and make them TRUE.
otherwise the project won't be compiled.

**Comment by minggo** [comment]
@mhbich will you please print the result of `NDK_MODULE_PATH `? 

 I don't remember i set `APP_SHORT_COMMANDS=false` and `LOCAL_SHORT_COMMANDS=false`. May be it is the default value, and we should set them to true.

**Comment by minggo** [comment]
Oh, the value of it is `NDK_MODULE_PATH=C:\cocos2d-x;C:\cocos2d-x\cocos;C:\cocos2d-x\external`. It is the path of your environment?

**Comment by ghost** [comment]
@minggo  it's was something else but i modified it in environment variables as you said and the issue is not resolved yet. 
By the way i closed android studio and even restarted the computer.

**Pull request merged**
