### PR TITLE
fix  font size error on MAC

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by liamcindy** [comment]
@minggo  please review this pr for Font size error on MAC

**Comment by WenhaiLin** [comment]
@liamcindy How to reproduced this issue?Maybe we should change the height/width of tImageInfo to float from int.

**Comment by liamcindy** [comment]
@Dhilan007 
        Text\* text_MAC = Text::create("Text Label", "", 20);
        Size textSize = text_MAC->getContentSize();
        text_MAC->ignoreContentAdaptWithSize(false);
        text_MAC->setContentSize(textSize);
        text_MAC->setPosition(Vec2(widgetSize.width / 2.0f - 20, widgetSize.height / 2.0f + text->getContentSize().height / 4.0f - 20));
        _uiLayer->addChild(text_MAC);

it's error only on mac

**Comment by WenhaiLin** [comment]
@liamcindy Thanks.I will test it.

**Comment by liamcindy** [comment]
merge to https://github.com/cocos2d/cocos2d-x/pull/10090

**Pull request closed without merging**
