### PR TITLE
fix normalizedPosition bug

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@darkdukey could you please take a look at this PR?
Does it fix the normalizedPosition bug?

**Comment by minggo** [comment]
@ricardoquesada 
Is it reasonable to fix the bug like this?

**Comment by ricardoquesada** [comment]
This patch breaks the `NodeNormalizedPositionTest2` test.

**Comment by ricardoquesada** [comment]
Patch looks good to me. merging it.

**Pull request merged**
