### PR TITLE
Fix password style text in UTF-16

### PR DESCRIPTION
**Pull request by perminovVS**
Label used UTF-16 in internal.
Need string in UTF-8.

Fix incorrect show password char: ? vs ●.

### CODE REVIEW

**Comment by minggo** [comment]
@perminovVS How can it test it?

**Comment by perminovVS** [comment]
@minggo Need create TextFieldTTF and setSecureTextEntry true

**Comment by minggo** [comment]
I tested on iPhone 6, not difference. And the password is not `?` or `*`, it is a rectangle.

**Comment by perminovVS** [comment]
@minggo rectangle as it https://github.com/cocos2d/cocos2d-x/pull/13903 zilongshanren commented on 21 Sep 2015 ? It rectangle bad char.

Password char ●

**Comment by minggo** [comment]
But what's good char? I input `a`, `b` or numbers, also show rectangles.

**Comment by minggo** [comment]
I tested on iPhone6.

**Comment by perminovVS** [comment]
@minggo good char http://www.fileformat.info/info/unicode/char/25CF/index.htm
But now in utf-16 char 0x25CF
Need in utf-8 char 0xE2 0x97 0x8F
This pr make it.

**Comment by perminovVS** [comment]
@minggo @zilongshanren Bad commit https://github.com/cocos2d/cocos2d-x/commit/90087ae5a7db99cd00606bb44aa5a0b2910ae962

_passwordStyleText = {(char)0xe2, (char)0x80, (char)0xa2, (char)0x00}; <---  UTF-8
_passwordStyleText("\u25CF") <--- UTF-16

**Comment by minggo** [comment]
@perminovVS As i comment above. No matter i applied this PR or not, the password is shown as rectangles. Which means the current codes have an issue, but your PR doesn't fix it.

I tested by running `TextInput` in cpp-tests, tested on Mac and iPhone devices.

**Comment by perminovVS** [comment]
@minggo ok, i tested in win32, winRT and android.
I will test on mac and write this.

**Comment by minggo** [comment]
Thanks

**Comment by perminovVS** [comment]
@minggo yes, it char 0xE2 0x97 0x8F not correct show in mac.
Change to old utf-8 char 0xE2 0x80 0xA2
And add test secure text entry

**Comment by perminovVS** [comment]
Win32, WinRT and Adnroid 0xE2 0x80 0xA2 also correct.

**Comment by minggo** [comment]
Thanks, it works as expected.

**Pull request merged**
