### PR TITLE
Add greater than operator to Vec2

### PR DESCRIPTION
**Pull request by Svenito**
Oddly this was missing in the V3 branch

### CODE REVIEW

**Comment by litefeel** [comment]
why need `operator >` on vector(Vec2)

**Comment by Svenito** [comment]
Do you mean to use the less than operator with the args reversed instead?

**Comment by litefeel** [comment]
what is mean?
`vectorA > vectorB`

**Comment by minggo** [comment]
@lite3 
Yep, the usage is 
`vectorA > vectorB`

**Comment by litefeel** [comment]
@minggo @Svenito

**Comment by litefeel** [comment]
@minggo @Svenito

两个矢量比较大小没有意义，为什么要比较两个矢量的大小？

**Comment by litefeel** [comment]
@minggo @Svenito
Please revert this patch.

**Comment by minggo** [comment]
We already has a `<` operation.

**Comment by litefeel** [comment]
why need `<` operation at vector?

we can remove them.

**Comment by litefeel** [comment]
@minggo @Svenito

我不知道为什么要比较两个矢量的大小，但是我在DirectX3D中也看到有矢量的比较，但是它的逻辑跟这边的不一样。
http://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.comparison.xmvector3less(v=vs.85).aspx

```
return ( V1.x < V2.x && V1.y < V2.y &&  V1.z < V2.z );
```

并不是 x相等再比较y。

**Comment by minggo** [comment]
@super626 
Please take a look.

**Comment by Svenito** [comment]
I added the patch because the "greater than" was missing, but the "less than" operator was there.
I agree that it doesn't make sense to talk about vector size in terms of its components, the operators should compare the magnitude of the vectors instead.

However, should getPosition and setPosition then not use the Point2 type instead of Vec2?

**Comment by litefeel** [comment]
@minggo @super626  
How to treat this patch.

**Pull request merged**
