### PR TITLE
#Improve XML parse performance with rapidxml pure SAX parser

### PR DESCRIPTION
**Pull request by halx99**
This PR is will never break any compatible, and more easy to review.

### CODE REVIEW

**Comment by halx99** [comment]
I will add performance test case later.

**Comment by minggo** [comment]
Why put `rapidxml_sax3.hpp` in `platform`? Is it platform dependent?

**Comment by halx99** [comment]
It's just for CCSAXParser, and CCSAXParser is platform independent.
Where put `rapidxml_sax3.hpp` is better?

**Comment by halx99** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@halx99 i think it is better to move it to `base` folder. And i don't know why `CCSAXParser.cpp` in `platform` folder.

**Comment by halx99** [comment]
@minggo Yes, the new `rapidxml_sax3.hpp` could move to base, but move the `CCSAXParser` will break compatible.

**Comment by halx99** [comment]
standalone test result:
vb j025i1he 11vydr t

test project: https://github.com/halx99/xmldrv3

**Comment by minggo** [comment]
@halx99 yep, just move `rapidxml_sax3.hpp`.

**Comment by zilongshanren** [comment]
@minggo   There is already a `rapidxml.hpp` in external directory?

**Comment by zilongshanren** [comment]
@minggo  My mistake, it's rapidjson..
But  I think rapidxml is also a 3rd party dependencies, it should be in external directory.

**Comment by halx99** [comment]
So, move to external?

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
The ios ci seems dropped:
`ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel`

**Comment by minggo** [comment]
@zilongshanren Yep,  in theory it should be in external folder. But as it is just a header file, so may be should can put it in cocos2d-x repo. @ricardoquesada what's your opinion?

**Comment by halx99** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@minggo 
As you said, in theory it should be in the "external" folder.
But this is only a header file. But if we decide to put it in the cocos/ directory structure, then, where?

Probably it is better to put it in the external folder, even if it is just one file.

**Comment by halx99** [comment]
Yes, I agree, so I create a PR to `cocos2d-x-3rd-party-libs-bin` https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/249

**Comment by minggo** [comment]
guys, you are right. We should put it in external. Sorry about it.

**Comment by halx99** [comment]
Ok，I will changed the code after the PR: cocos2d/cocos2d-x-3rd-party-libs-bin#249 merged.

**Comment by ricardoquesada** [comment]
@halx99 thanks. PR in 3rd-party-libs-bin merged.

**Comment by halx99** [comment]
ok, I just changed the source code.

**Comment by halx99** [comment]
@ricardoquesada It seems needs a new tag `v3-deps-111` of `cocos2d/cocos2d-x-3rd-party-libs-bin`

**Comment by ricardoquesada** [comment]
@halx99 done: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/releases/tag/v3-deps-111

**Comment by halx99** [comment]
ok, but it the release notes seems wrong: 
rlvketpelk_j 2i i5n h

It should be `Includes rapidxml SAX parser` 😀

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@halx99 fixed. thanks :)

**Comment by ricardoquesada** [comment]
looks good to me. merged.

**Pull request merged**
