### PR TITLE
fix precision issue

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by Anywhere-Music-Player** [comment]
Tested(iOS device only). Fixed. Thanks. Will test on Mac soon.

**Comment by Anywhere-Music-Player** [comment]
@minggo 
On mac got some problem. Just compile tests without any changes.

screen shot 2017-06-08 at 1 45 01 pm

**Comment by minggo** [comment]
fixed, `highp` is not a keyword on mac, it uses opengl instead of opgnel es. It seems it supports shader language 1.1.

**Comment by Anywhere-Music-Player** [comment]
Tested, iOS devices & Mac. Fixed. Thanks.

**Pull request merged**
