### PR TITLE
Fixed crash with CCLabelBMFont

### PR DESCRIPTION
**Pull request by moadib**
Fixed crash with CCLabelBMFont when center- or right-aligned text have line breaks each other

You can reproduce crash with

```
CCLabelBMFont* text = CCLabelBMFont::create("abc\n\n1", "font.fnt");
text->setAlignment(kCCTextAlignmentCenter);
addChild(text);
```

### CODE REVIEW

**Comment by minggo** [comment]
I have tested the codes you pasted.
It doesn't crash.
You can test it with my branch "CCLabelBMFont_crash".

**Comment by moadib** [comment]
Hmm :)

Try change 
`CCLabelBMFont* text = CCLabelBMFont::create("abc\n\n1", "font.fnt");`
to
`CCLabelBMFont* text = CCLabelBMFont::create("abc\n\n123", "font.fnt");`

**Comment by minggo** [comment]
You are right.
Thank you.

**Comment by minggo** [comment]
How about add some comment of these codes?
And i have created an issue for it http://www.cocos2d-x.org/issues/1464.

**Pull request merged**
