### PR TITLE
Added glfwSetCursorPos

### PR DESCRIPTION
**Pull request by mignaciolopez**
Added Function glfwSetCursorPos to set cursor in a fixed position in screen coordinates. Also created a test case with an example of a useful application of that function.

It was only tested on Win32.

### CODE REVIEW

**Comment by slackmoehrle** [comment]
@Mee-gu @minggo this PR is from a new contributor. Would you provide feedback on this PR and if you see any adjustments, please mention them.

@mignaciolopez thank you for your first contribution!

**Comment by mignaciolopez** [comment]
These failures is because i need to add
if (CC_TARGET_PLATFORM == CC_PLATFORM_MAC || CC_TARGET_PLATFORM == CC_PLATFORM_WIN32 || CC_TARGET_PLATFORM == CC_PLATFORM_LINUX)

to the test case created. I though Mouse Test was already excluded from ios and android builds.

can i re do with this change?

**Comment by minggo** [comment]
@mignaciolopez thanks for your contribution. But it seems Mouse Test is not excluded from iOS and Android.

**Comment by mignaciolopez** [comment]
The last commits were tested on:
Win32
OSX
IOS
Android

**Comment by mignaciolopez** [comment]
@minggo @slackmoehrle hey guys, i dont want to bother, i'm aware of all the problems the world has, but if you have a little bit of free time, would you give me some feedback please? did you like it? is it useful? was it done properly? when do you have plans to update v3? would you like it more in v4? Thank you, anyway!

**Comment by minggo** [comment]
@mignaciolopez PC is not the first important platform for cocos2d-x, so i will keep this PR open.

**Pull request closed without merging**
