### PR TITLE
Fix cc notification observer perform selector

### PR DESCRIPTION
**Pull request by jzgenius**
1. not retain m_target and m_object in CCNotificationObserver function.
2. not perform m_object to performSelector target.

### CODE REVIEW

**Comment by dumganhar** [comment]
Do we also need to modify the constructor of CCNotificationObserver ?

<pre>
CCNotificationObserver::CCNotificationObserver(CCObject *target, 
                                               SEL_CallFuncO selector,
                                               const char *name,
                                               CCObject *obj)
{
    m_target = target;
    CC_SAFE_RETAIN( m_target );   // Added
    m_selector = selector;
    m_object = obj;
    CC_SAFE_RETAIN( m_object );   // Added
    
    m_name = new char[strlen(name)+1];
    memset(m_name,0,strlen(name)+1);
    
    string orig (name);
    orig.copy(m_name,strlen(name),0);
}
</pre>

**Comment by jzgenius** [comment]
Yes, your right!
Great!

**Comment by dumganhar** [comment]
Thanks. :)

**Comment by dumganhar** [comment]
The 'object' and 'target' parameters should not be retained. We must use weak reference, otherwise the life-cycle of target object will be delayed until the destruction of CCNotificationCenter.

**Comment by dumganhar** [comment]
I have reverted this file.

**Pull request merged**
