### PR TITLE
Added CCGLViewImpl.h

### PR DESCRIPTION
**Pull request by kuzy000**
There is no way to include it for a target platform without including cocos2d.h

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
thanks

**Comment by minggo** [comment]
Oh, sorry for my mistook. There is already `platform/CCGLView.h`, so i have to revert it.

**Pull request merged**
