### PR TITLE
close #3861:fixed NativeActivity issue ANR on android 2.3 when press hardware button.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by dumganhar** [comment]
@Dhilan007 
What about @pyrasis said?

**Comment by pyrasis** [comment]
@dumganhar this patch does not work yet.

**Comment by dumganhar** [comment]
@pyrasis ,could you help to check this issue? Thanks.

**Comment by pyrasis** [comment]
@dumganhar yes. sure.

```
static void process_input(struct android_app* app, struct android_poll_source* source) {
    AInputEvent* event = NULL;
    int processed = 0;
    while (AInputQueue_getEvent(app->inputQueue, &event) >= 0) {
        LOGV("New input event: type=%d\n", AInputEvent_getType(event));
        if (AInputQueue_preDispatchEvent(app->inputQueue, event)) {
            continue;
        }
        int32_t handled = 0;
        if (app->onInputEvent != NULL) handled = app->onInputEvent(app, event);
        AInputQueue_finishEvent(app->inputQueue, event, handled);
        processed = 1;
    }
    if (processed == 0) {
        LOGE("Failure reading next input event: %s\n", strerror(errno));
    }
}
```

this code works fine on android 2.3.

**Comment by dumganhar** [comment]
@pyrasis 
Thanks. I will check it tomorrow since I doesn't have an android device at home. ;)

**Comment by WenhaiLin** [comment]
@pyrasis I tested on Sony Ericsson[2.3.4] and HTC G10[2.3.3],it does work normal.Why you want commented out [hasEnevt = AInputQueue_hasEvents( app->inputQueue );]?Frozen means issue ANR?

**Comment by pyrasis** [comment]
@Dhilan007 Yes. frozen means issue ANR.

**Comment by pyrasis** [comment]
@Dhilan007 

```
int32_t hasEnevt = AInputQueue_hasEvents( app->inputQueue );
while (hasEnevt == 1 && AInputQueue_getEvent(app->inputQueue, &event) >= 0) {
```

these lines make ANR issue on Samsung GalaxyS2 and android 2.3.x.

**Comment by pyrasis** [comment]
@Dhilan007 @dumganhar Thank you very much. :+1:

**Comment by dumganhar** [comment]
:)

**Pull request merged**
