### PR TITLE
issue #1646: Updated spiderMonkey to FF18.0.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by jozef-pridavok** [comment]
@dumganhar where can i find build/make files for spidermonkey? I would like to add spidermonkey and jsb to Mac OS...

**Comment by dumganhar** [comment]
@jpridavok 
You could refer to this repo(https://github.com/ricardoquesada/Spidermonkey).
But plz wait until Riq merge my Pull Request(https://github.com/ricardoquesada/Spidermonkey/pull/11).
It's easy for building MAC library. Just enter js/src/build-osx, and run ./build.sh.

**Comment by jozef-pridavok** [comment]
@dumganhar thank you very much, I am waiting for Riq's merge. Do you think it make sense to push request with Mac binaries? It would be great to have prebuilt spidermonkey for all supported platform...

**Comment by dumganhar** [comment]
@jpridavok , Riq merged the Pull Request.
If you need prebuilt library, just get it in cocos2d-iphone `develop-v2` branch.

**Pull request merged**
