### PR TITLE
Fix template android compilation issue on physics3d

### PR DESCRIPTION
**Pull request by pandamicro**

### CODE REVIEW

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Pull request merged**
