### PR TITLE
update for ui resource test

### PR DESCRIPTION
**Pull request by liamcindy**
@zilongshanren Please review this PR, thanks.

### CODE REVIEW

**Comment by xiaofeng11** [comment]
@ricardoquesada This pr is the tests for cocos studio changes to engine, Please review it, Thanks.

**Comment by ricardoquesada** [comment]
@xiaofeng11 Please add a detail description of what the PR does. Otherwise it is impossible for me to review it. Thank.s

**Comment by liamcindy** [comment]
@ricardoquesada This PR just print property of the resources used by the ui widgets to test the newly added interfaces just like "getRenderFile";

**Comment by ricardoquesada** [comment]
yes... tests cases are good. Not sure if I need to review the tests cases, but they look good to me.

**Pull request closed without merging**
