### PR TITLE
Make precheader files PRIVATE, otherwise they leak to the game project

### PR DESCRIPTION
**Pull request by Stinkfist0**
Make precheader files PRIVATE, otherwise they leak to the game project (e.g. in Visual Studio, Internal\cocos2d\precheader.cpp visible/duplicate also in MyGame project).

### CODE REVIEW

**Comment by Stinkfist0** [comment]
Mac build seems to time out for some reason.

**Comment by Stinkfist0** [comment]
Retriggering the CI build, hopefully Mac build doesn't time out this time.

**Comment by minggo** [comment]
why it can cause memory leak?

**Comment by Stinkfist0** [comment]
By leak I mean that the engine's PCH file is visible and duplicate in the game project files in Visual Studio, causing it to be easily edited by accident. E.g. let say I would use the Boost library in my game and would like to add Boost to the PCH in order to speed up the compilation. Currently (without private precheader.h/cpp) I could very easily end up editing the engine's PCH and cause unnecessary overhead and engine code's recompilation as the engine doesn't use Boost.

**Pull request merged**
