### PR TITLE
Add utils::atof(), fix bug: particle not shown on android.

### PR DESCRIPTION
**Pull request by boyu0**

### CODE REVIEW

**Comment by litefeel** [comment]
why do not use `sprintf`?

**Comment by minggo** [comment]
@lite3 
How to use `spintf` instead?
Thanks.

**Comment by litefeel** [comment]
i am sorry. I was wrong.

**Comment by minggo** [comment]
No problem.

**Comment by felixjingga** [comment]
@minggo why don't use sscanf instead?

**Comment by boyu0** [comment]
@felixjingga I tested it, it has the same problem as atof.

**Comment by boyu0** [comment]
[ci rebuild]

**Comment by litefeel** [comment]
strtod ?

**Comment by minggo** [comment]
It is strange that, if we use atof in samples shift by NDK r9d, then no problem.

Environment:
- NDK r9d
- Clang + libc++

Code:

``` c++
float f = atof("90.099998474121094");
LOGI("Test %f",f);
```

Result:

Test 90.099998  -> in shift sample by NDK r9d
Test -inf -> used in cocos2d-x

**Comment by minggo** [comment]
@lite3 
`strtod`, `std::atof`, `atof` all can not work.
And we found, the result is correct if running with `armeabi-v7s`, which will use fpu.

**Pull request merged**
