### PR TITLE
* add CCNode::getChildrenCount()

### PR DESCRIPTION
**Pull request by dualface**
- add CCNode::getChildrenCount()

### CODE REVIEW

**Comment by minggo** [comment]
There is a function CCNode::getChildren(), why should add this function?

**Comment by dualface** [comment]
CCNode::m_pChildren default is NULL, after first time call CCNode::addChild(), m_pChildren is valid.

CCNode::getChildrenCount() always check m_pChildren.

**Comment by minggo** [comment]
You should check the result of CCNode::getChildren() to compute count every time you want to get children count.
We should keep engine as simple as possible.

**Comment by dualface** [comment]
cancel

**Pull request closed without merging**
