### PR TITLE
add new clang-tidy option

### PR DESCRIPTION
**Pull request by JohnCoconut**
* readability-delete-null-pointer

> Checks the if statements where a pointer’s existence is checked and then deletes the pointer. The check is unnecessary as deleting a null pointer has no effect.

```cpp
int *p;
if (p)
  delete p;
```

Reference: http://releases.llvm.org/7.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-delete-null-pointer.html

### CODE REVIEW

**Comment by JohnCoconut** [comment]
@minggo  Do you wish me to push all future similar `clang-tidy` commits to `metal-support` branch?

**Comment by minggo** [comment]
Yep, you are appreciated if you can send a PR to `metal-support` branch.

**Review by minggo — APPROVED** [review]

**Comment by crazyhappygame** [comment]
@minggo currently I see 3 active cocos2d-x branches:
1. V3
2. Metal-support
3. Cocos2d-x-lite - branched from 3.9 used in cocos creator.

What is the long term plan? 
Will you merge them all to one branch?

**Comment by minggo** [comment]
cocos2d-x-lite is just for creator, it is a different repo.
metal-support is a different branch for metal support, we haven't make a final decision of the version name. metal-support and v3 are in the same repo, but will be different branches.

**Pull request merged**
