### PR TITLE
apply custom request header for every request type (ios)

### PR DESCRIPTION
**Pull request by redism**
I think custom request header should be set not only for POST or PUT, but also every http methods.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by samuele3hu** [comment]
@redism , I agree with you that every http methods should set the request header,Thanks.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by Mazyod** [comment]
This is great, I was thinking of submitting a PR for that myself.

**Pull request merged**
