### PR TITLE
V3 Update Angle to support gl_PointSize on Windows Phone 8.1

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates Angle to ddbf057c52. This version of Angle correctly supports gl_PointSize on Windows Phone 8.1. Shader compilation is also faster due to threaded parallel compilation of vert and frag shaders. This pull request depends upon download-deps.py being updated to include the following pull request:

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/108

### CODE REVIEW

**Comment by darkdukey** [comment]
d:\jenkins\workspace\ccs-pr\node\windows-universal\tests\cpp-tests\proj.win8.1-universal\cpp-tests.Shared........\cocos\platform\win8.1-universal\OpenGLES.cpp(85): error C2065: 'EGL_PLATFORM_ANGLE_DEVICE_TYPE_ANGLE' : undeclared identifier

d:\jenkins\workspace\ccs-pr\node\windows-universal\tests\cpp-tests\proj.win8.1-universal\cpp-tests.Shared........\cocos\platform\win8.1-universal\OpenGLES.cpp(85): error C2065: 'EGL_PLATFORM_ANGLE_DEVICE_TYPE_WARP_ANGLE' : undeclared identifier

**Comment by stammen** [comment]
This pull request depends upon download-deps.py being updated to include the following pull request:

cocos2d/cocos2d-x-3rd-party-libs-bin#108

**Comment by stammen** [comment]
This pull request depends upon download-deps.py being updated to include the following pull request:

cocos2d/cocos2d-x-3rd-party-libs-bin#108

**Comment by stammen** [comment]
@minggo This is a breaking change. It needs the new Angle header files in 

cocos2d/cocos2d-x-3rd-party-libs-bin#108. Please pull the request and update the version of download-deps.py.

The Angle team was required by Google to make this breaking change.

**Comment by stammen** [comment]
@andyque This should fix the problem. I merged in the updates to v3 to get the version 35 of download-deps.py

**Comment by zilongshanren** [comment]
@stammen 
Could you update "external/config.json" file in this PR?  If your PR depends on the v3-deps-35, you should also include the change, otherwise the PR can't pass the CI server.

**Comment by stammen** [comment]
@andyque  I updated external/config.json to version 35.

**Comment by zilongshanren** [comment]
thanks @stammen 

@minggo  We could merge this PR now.

**Pull request merged**
