### PR TITLE
Set focus for widgets

### PR DESCRIPTION
**Pull request by Dimon4eg**
Automatically set focus for widgets if focus enabled.

### CODE REVIEW

**Comment by pandamicro** [comment]
@liamcindy Please help review this PR
@zilongshanren Can you confirm this with @liamcindy ?

**Comment by zilongshanren** [comment]
@Dimon4eg 
Thanks, I have one question here.
Why TextField get focus when touch began and other widgets get focus when touch release?

**Comment by Dimon4eg** [comment]
@zilongshanren Because TextField shows keyboard on touch began.

**Comment by zilongshanren** [comment]
@Dimon4eg 
Thanks for clarification this.

**Pull request merged**
