### PR TITLE
delete unnecessary include file

### PR DESCRIPTION
**Pull request by zhong317**
delete unnecessary include file

### CODE REVIEW

**Comment by zhong317** [comment]
[ci rebuild] ? what's mean?

**Comment by darkdukey** [comment]
it will force build server to rebuild your pull request, unfortunately the build server is broken at the moment, maybe try to do a rebuild tomorrow.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
@zhong317 Thanks.The correct way :  https://github.com/cocos2d/cocos2d-x/pull/9107

**Pull request closed without merging**
