### PR TITLE
When android project build native, using multiple concurrent job process...

### PR DESCRIPTION
**Pull request by pangliang**
When android project build native, using multiple concurrent job processes;

android项目编译时,获取系统cpu核数, 利用"-j"参数, 启用跟cpu数相同的多进程编译

### CODE REVIEW

**Comment by minggo** [comment]
@liang8305 
Good job. And please don't use Chinese words in description in future.
Thanks.

**Comment by minggo** [comment]
@liang8305 
You are appreciated if you can modify build/android-build.py.

**Comment by pangliang** [comment]
@minggo 
I finish it, and pull request #5126

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
