### PR TITLE
Gles20 linux port

### PR DESCRIPTION
**Pull request by tongpengfei**
Hi, this is linux port for cocos2d-x gles20, please review.
issue:
the api cocos2d-x-2.0:
bool CCLabelTTF::initWithString(const char *string, const CCSize& dimensions, 
                                               CCTextAlignment hAlignment, const char *fontName, float fontSize);
is diffent to
cocos2d-x gles:
bool CCLabelTTF::initWithString(const char *string, const char *fontName, float fontSize, 
                                                const CCSize& dimensions, CCTextAlignment hAlignment);
but javascript/bindings/cocos2d_manual_bindings.cpp:228 is refer to the old version api, so I changed this line.

### CODE REVIEW

**Comment by minggo** [comment]
Because cocos2dx_manual_bindings.cpp is not updated to the new api.

**Comment by tongpengfei** [comment]
ok...

**Comment by dumganhar** [comment]
Hi, pengfei,
Your PR has been merged. Thanks.
But I have tested it and found some issues as bellow:
[1] CocosDenshionTest crash.
[2] FontTest result not correct.
Could you fix these issues?

**Comment by tongpengfei** [comment]
Hi, dumganhar, my pleasure, which os do you test?
My ubuntu11.04 did not crash. 
What the acurrate meaning of FontTest result not correct. maybe I should have a look at test result on win32 at first. :)

**Comment by dumganhar** [comment]
I tested this port on my virtual machine which installs Mint13.
The label alignment in FontTest is always top-left.

**Comment by tongpengfei** [comment]
ok, I will download a Mint13 iso and test it. on ubuntu it is ok, but I have not modify any label code.

 ------------------ 原始邮件 ------------------
  发件人: "James Chen"reply@reply.github.com;
 发送时间: 2012年8月3日(星期五) 中午1:40
 收件人: "tongpengfei"27001909@qq.com; 

 主题: Re: [cocos2d-x] Gles20 linux port (#1152)

I tested this port on my virtual machine which installs Mint13.
The label alignment in FontTest is always top-left.

---

**Comment by dumganhar** [comment]
Ok, did FontTest work also fine on your UBUNTU?
BTW, don't forget to add your name to AUTHORS file. Thanks.

**Comment by tongpengfei** [comment]
yes, it works as same as win32. would you please add my name to AUTHORS, I need a new PR if I did. thank you.
  follow the screenshot:

 ------------------ 原始邮件 ------------------
  发件人: "James Chen"reply@reply.github.com;
 发送时间: 2012年8月3日(星期五) 下午3:05
 收件人: "tongpengfei"27001909@qq.com; 

 主题: Re: [cocos2d-x] Gles20 linux port (#1152)

Ok, did FontTest work also fine on your UBUNTU?
BTW, don't forget to add your name to AUTHORS file. Thanks.

---

**Comment by tongpengfei** [comment]
Hi dumganhar, I test it on my new mint13 32bit, but CocosDenshionTest and FontTest works fine.

**Comment by dumganhar** [comment]
=_-!!!, ok,  I will test it on my notebook which install UBUNTU12.04. Thanks.

**Comment by tongpengfei** [comment]
ok. :)

**Comment by dumganhar** [comment]
Hi, tongpengfei,
I tested linux port on my UBUNTU12.04, the CocosDenshionTest works fine, but the FontTest is still incorrect.
The ttf font alignment is always TOP. You can refer to windows port, there are Top, Middle,Bottom alignment if you click the next button. Hope u can fix this bug. Thanks in advance. :)

**Comment by tongpengfei** [comment]
:) could you join my QQ 27001909, for easy talk

------------------ 原始邮件 ------------------
发件人: "James Chen"; 
发送时间: 2012年8月6日(星期一) 上午10:25
收件人: "tongpengfei"27001909@qq.com; 
主题: Re: [cocos2d-x] Gles20 linux port (#1152)

Hi, tongpengfei,
I tested linux port on my UBUNTU12.04, the CocosDenshionTest works fine, but the FontTest is still incorrect.
The ttf font alignment is always TOP. You can refer to windows port, there are Top, Middle,Bottom alignment if you click the next button. Hope u can fix this bug. Thanks in advance. :)

---

**Pull request merged**
