### PR TITLE
retain the sprite frame in sprite

### PR DESCRIPTION
**Pull request by litefeel**
do not removed by SpriteFrameCache::removeUnusedSpriteFrames

### CODE REVIEW

**Comment by litefeel** [comment]
@minggo please review.

**Comment by minggo** [comment]
What's the issue of current implementation?

**Comment by litefeel** [comment]
@minggo  
1. add test.plist, contain a.png
2. create sprite with sprite frame a.png, and retain(use).
3. spriteFrameCache::removeUnusedSpriteFrames()
4. create sprite width sprite frame a.png, (error can not find sprite frame a.png)

**Comment by minggo** [comment]
Yep, it will has problem in this situation.
But there is another problem.
After you create Sprites from sprite frames, then you don't need them, so you want to invoke `spriteFrameCache::removeUnusedSpriteFrames` to reduce memory. Then all sprite fames that are used to create Sprite can not be released. But indeed they are not needed.

**Comment by litefeel** [comment]
@minggo 
你的思路是尽量减少内存，但是主要占用内存的是纹理而不是spriteFrame，所以即便是所有的spriteFrame都移除掉了，但是texture还在被使用，所以内存不会降。
这样就出现了texture还在，但是spriteFrame不能找到了。

**Pull request merged**
