### PR TITLE
AudioEngine:Fixed program may freeze if `AudioEngine::stop` or `AudioEngine::stopAll()` is invoked frequently on Android.

### PR DESCRIPTION
**Pull request by WenhaiLin**
This solution is not perfect, by this method the probability of `freeze` is greatly reduced.

### CODE REVIEW

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by kakamatong** [comment]
Still happen

**Comment by BlackStar0313** [comment]
still happen , test device  nexus6 ,Android 6.0     ,

my describe: http://www.cocoachina.com/bbs/read.php?tid=1679095&page=1&toread=1#tpc

**Comment by dumganhar** [comment]
@BlackStar0313 , thank you for your report, I'll check it.

**Comment by Jayatubi** [comment]
Still happen on GiNOEE F103/amigo3.0.7/Android 5.0

**Comment by dumganhar** [comment]
@Jayatubi, could you try the Pull Request here (https://github.com/cocos2d/cocos2d-x/pull/15875)? I refactored something of AudioEngine for Android.

**Comment by Jayatubi** [comment]
@dumganhar Thanks for your reply but I'm still using the cocos2dx 2.2.6 so I can't merge you pull.

**Comment by dumganhar** [comment]
@Jayatubi , sorry for that we aren't maintaining the v2 branch.
But `AudioEngine` is a new class added from v3.0, if it's a bug of `CocosDension`/ `SimpleAudioEngine`, please just create another issue.

**Comment by Jayatubi** [comment]
@dumganhar Could you provide any hints about how you fix this issue on 3.x? Maybe I can try the same solution on my 2.2.6.

BTW I'm currently using the 2.2.6 with the refactoring from https://github.com/WenhaiLin/cocos2d-x/commit/be0ac68a5e8512c665956acfab90ba5c4e18686f to avoid Android 5 AwesomePlayer issue.

**Comment by dumganhar** [comment]
My PR(#15875) uses a different approach to play effects.
The problem may be resolved and I will do more test on it. :)
What're `AwesomePlayer issue`?

**Comment by Jayatubi** [comment]
@dumganhar Oops it seems I messed up the name should be `Nuplayer`.

In the early releases of the Android 5 the `Nuplayer`, which was experimental and buggy, has been set as the default audio engine for the `SoundPool`. It had a very terrible issue that it will cause the app freeze for a few seconds when load short audio clips. To walk around the audio engine could be changed back to the old `AwesomePlayer` in the `Developer options`.

However, I couldn't tell all my APP users to do such things because they might not understand what was going to do so I have to change all implementation from `SoundPool` to the `OpenSLES`.

**Comment by dumganhar** [comment]
Mmm, but we don't have enough time to continue maintaining v2 branch...
You could refer to my PR for what I changed.

**Pull request merged**
