### PR TITLE
Adding popSceneBack() function to CCDirector

### PR DESCRIPTION
**Pull request by mdkcore0**
This function deletes the running scene and returns the actual scene
back to the caller. This way, we can simply use it to perform a
transition animation, like this:

```
CCDirector::sharedDirector()->replaceScene(
        CCTransitionSlideInL::create(0.5,
        CCDirector::sharedDirector()->popSceneBack()));
```

### CODE REVIEW

**Comment by michaelcontento** [comment]
:+1:

**Comment by minggo** [comment]
If there is one scene, popSceneBack will cause CCDirector::end() to be invoked.

**Comment by mdkcore0** [comment]
Hi @minggo , it's the same behavior of popScene(); do you have another suggestion of behavior for this situation??

**Comment by mdkcore0** [comment]
Closing this PR in favor of a new one (with tests and over the 'develop' branch; PR #3244)

**Pull request closed without merging**
