### PR TITLE
Render rotated transparent sprite correctly

### PR DESCRIPTION
**Pull request by darkdukey**
Change render command to render transparent sprite correctly

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
> ..\renderer\CCQuadCommand.cpp(63): error C3861: 'fmaxf': identifier not found
> 3>..\renderer\CCQuadCommand.cpp(66): error C3861: 'fmaxf': identifier not found
> 3>..\renderer\CCQuadCommand.cpp(69): error C3861: 'fmaxf': identifier not found
> 3>..\renderer\CCQuadCommand.cpp(72): error C3861: 'fmaxf': identifier not found

Please fix the issue.

**Comment by darkdukey** [comment]
Don't merge this yet, to be discussed.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
We're going to use a different approach since perfectly render 2D elements in 3D is very hard to achieve.

**Pull request closed without merging**
