### PR TITLE
Fixed #12145 : formarRenderers in RichText doesn’t update container s…

### LINKED ISSUE #12145: formarRenderers in RichText doesn’t update container size
need to update container size in RichText

http://discuss.cocos2d-x.org/t/formarrenderers-in-richtext-doesnt-update-container-size/21710

### PR DESCRIPTION
**Pull request by yangws**
…ize.

related issue: #12145

### CODE REVIEW

**Comment by pandamicro** [comment]
For fixing #12145

**Comment by fusijie** [comment]
`_elementRenderersContainer` could not be removed. It's will cause error effect. e.g.

``` cpp
richtext->removeAllChildren();
```

**Comment by fusijie** [comment]
That's ok, @pandamicro It's can be merged now.

**Comment by springrider** [comment]
@pandamicro  sorry for bring this up after months, but I found it's still not right,   in the method "formarRenderers", and the _ignoreSize==false branch, it didn't setContentSize after calculated newContentSizeHeight. makes the height not updated. 

shouldn't `this->setContentSize(Size(newContentSizeWidth, newContentSizeHeight));` been added to that branch too?

**Comment by sbrednikhin** [comment]
@pandamicro I agree with @springrider 
I need to know final height of RichText element with limited width.

**Comment by alfogrillo** [comment]
As @sbrednikhin I need the final height of `RichText` with limited width containing multiple elements (to set the parent inner scroll view size). 
@pandamicro  Is this possible?

**Pull request merged**
