### PR TITLE
FEATURE 9912 - Controller support Windows/Mac/Linux

### PR DESCRIPTION
**Pull request by Sheado**
Added desktop controller support.
- Currently supports Mac, but should be a matter of ifdefs to support
  Windows and Linux
- Currently maps PS3 controller only
- Remaining tasks are tagged with the comment // TODO - controller

### CODE REVIEW

**Comment by darkdukey** [comment]
Good job, can you send a pull request for v3 branch as well? Let me know if you needs help.

**Comment by Sheado** [comment]
Thanks @darkdukey,

I submitted to v3, please let me know if the submission is incorrect.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
We have no plan to support PC controller, thanks.

**Pull request closed without merging**
