### PR TITLE
Port Cocos2D-X to Qt 5

### PR DESCRIPTION
**Pull request by thp**
This allows building Cocos2D-X with Qt5 (http://qt-project.org/) on Linux as the backend.

The backend is not fully completed yet (e.g. Accelerometer support), but the basic tests are working, including multi-touch input and GLESv2 rendering.

### CODE REVIEW

**Comment by dumganhar** [comment]
Cool, could you send it to develop branch?

**Comment by ricardoquesada** [comment]
This is a great feature!
Please, send the PR for the "develop" branch. thanks.
I would to play with QT and cocos2d !

**Comment by gelldur** [comment]
Qt can work on WP8?

**Comment by thp** [comment]
Pull request #3273 is the Qt 5 port rebased on top of the "develop" branch. It would be great if both #3225 and #3273 could be reviewed and merged (the "master" branch is the target and tested, the "develop" branch is the future). Also, I noticed that some adaptions (Tizen, Marmalade) are not included in "develop"?

**Comment by dumganhar** [comment]
Closed it since the new PR for develop branch is here (https://github.com/cocos2d/cocos2d-x/pull/3273).

**Pull request closed without merging**
