### PR TITLE
enable setup.py to use on fish

### PR DESCRIPTION
**Pull request by sambaiz**
setup, not only bash but also fish

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, thanks for your contribution.
As i know, fish could read the variables defined in `bash`, right?
So if we invoking `setup.py` in bash, fish will also be able to use it.

**Comment by sambaiz** [comment]
> As i know, fish could read the variables defined in bash, right?

I don't think so by default settings at least.
After run `setup.py` , and  run `echo $COCOS_CONSOLE_ROOT` on fish but I get nothing.
Even after I restart fish, the result is the same.

**Comment by minggo** [comment]
Why need to do special support for fish?
Should we support `Zsh`, `Ksh`?
Support as more as possible is good to have. But it brings more work, test.
And we don't have enough resource for it.
Just one choice and continue to improve it is enough.

**Comment by sambaiz** [comment]
OK. I see.

**Pull request closed without merging**
