### PR TITLE
Fixed WinRT project

### PR DESCRIPTION
**Pull request by Teivaz**
Inserted newly added files to cocos WIN RT project

### CODE REVIEW

**Comment by minggo** [comment]
Thanks.
But it is better not add new pictures if possible. Because it will make repo bigger.

**Comment by Teivaz** [comment]
OK, @minggo, I removed last commit with pictures

**Comment by minggo** [comment]
And please don't let it exist in commit history too.

**Comment by minggo** [comment]
Thanks.

**Comment by Teivaz** [comment]
Sure, it's no longer in the repo in any way.

**Pull request merged**
