### PR TITLE
Added libcurl, libwebsockets, openssl and updated testcpp to support these on Windows Phone 8

### PR DESCRIPTION
**Pull request by martell**
EDIT: WinRT will go in another PR
This should close #3870

### CODE REVIEW

**Comment by dumganhar** [comment]
@martell , so you added an adapter for `curl` and `socket`, right?
Then, `HttpClient.cpp` will not be inserted lots of codes for WP8 and WinRT, right?

**Comment by martell** [comment]
@dumganhar That is right :)

**Comment by martell** [comment]
I haven't done libwebsockets yet. That will be done next.

**Comment by squirrelChen** [comment]
@martell I will test your code, and add the project to the solution and add curltest.cpp.

**Comment by squirrelChen** [comment]
Hi @martell, I test  curltest.cpp in WP8 and results error. like:CurlTest.obj : error LNK2001: unresolved external symbol __imp_curl_easy_init...
May be you create libcurl as a StaticLibrary, but I think it needs to be a Dynamic Library. Because libcurl needs Ws2_32.lib or do you need a CURL_STATICLIB Preprocessor ? 
If you build in solution successful, you can commit your code with the CurlTest.cpp in solution. Thanks。

**Comment by martell** [comment]
@koowolf Yes you must define CURL_STATICLIB for a static libcurl build.
Also on WinRT don't add Ws2_32.lib add winsockrt.lib instead.

I will add them to the testbed soon. Thanks for your help :) 

EDIT: I changed it to a shared version to suit WinRT warnings over c++/cx code in a static lib

**Comment by martell** [comment]
@dumganhar @koowolf @stammen At this point curl should work for wp8.
I wont have a device to test until monday so I won't be able to confirm until then.
(the emulator doesn't get an internet connection on my laptop over wifi bridging issues)

WinRT code has been done (commented out with 2 notes temporarily) 
I need to emulate 4 more win32 functions libcurl uses but I'm a bit stuck here.
This could take some time to figure out.

I was thinking I could change the name of this pull request and get WP8 in first?
And then do another PR with winRT

Your thoughts?

**Comment by dumganhar** [comment]
@martell 
Yep, I think separating them to two PR is a good idea. ;).

**Comment by martell** [comment]
@dumganhar
If that's the case then this PR should be good to merge unless it breaks other platforms?
I'll edit the name now ;)

EDIT: It did break other platforms.

**Comment by stammen** [comment]
Which 4 Win32 functions are you having a problem with?

**Comment by martell** [comment]
It's 5 sorry not 4 as one I thought I fixed still wont link

1>asyn-thread.obj : error LNK2001: unresolved external symbol _InitializeCriticalSectionEx
1>connect.obj : error LNK2001: unresolved external symbol __WSAIOW
1>connect.obj : error LNK2001: unresolved external symbol _CreateEventEx
1>connect.obj : error LNK2001: unresolved external symbol _WSAIoctl
1>curl_threads.obj : error LNK2001: unresolved external symbol __beginthreadex
1>timeval.obj : error LNK2001: unresolved external symbol _GetTickCount64

I fixed _GetTickCount64 and I wrote a wrapper for __beginthreadex but it wont link to it.
Also seems some of the others won't link because it's pure c code in libcurl.

The two I'm mostly worried about are __WSAIOW and _WSAIoctl

**Comment by martell** [comment]
Just rebased against the master branch as the buildbot wont build otherwise.

**Comment by martell** [comment]
Please ignore the build bot (you may have to edit your scripts to remove ios-build.sh every time)

error: The following untracked working tree files would be overwritten by merge:
    tools/jenkins-scripts/ios-build.sh
Please move or remove them before you can merge.
Aborting

This PR is now good to go I've tested it on win32 and android

**Comment by martell** [comment]
@dumganhar
I've just tested it on a Windows Phone 8 and HttpClientTest works.
Were in business for curl on WP8 guys :)

**Comment by stammen** [comment]
Hi Martell,

InitializeCriticalSectionEx is supported on WInRT and WP8

http://msdn.microsoft.com/en-us/library/windows/desktop/ms683477(v=vs.85).aspx

So is CreateEventEx

http://msdn.microsoft.com/en-us/library/windows/desktop/ms682400(v=vs.85).aspx

They require Kernel32.lib

I would be happy to look at your code on Monday to see if I can these functions to link.

Regarding WSAIOW and WSAIoctl. These functions only appear once in the winrtsock and libcurl interface and are used on Win32 for setting KEEPALIVE. Since WinRT does not support the KEEPINTVL and KEEPIDLE  options I suggest you change the defines to use setsockopt (similar to line 151 in connect.c) on WinRT instead of WSAIoctl

#ifdef TCP_KEEPALIVE
    /\* Mac OS X style */
    optval = curlx_sltosi(data->set.tcp_keepidle);
    KEEPALIVE_FACTOR(optval);
    if(setsockopt(sockfd, IPPROTO_TCP, TCP_KEEPALIVE,
          (void *)&optval, sizeof(optval)) < 0) {
      infof(data, "Failed to set TCP_KEEPALIVE on fd %d\n", sockfd);
    }

#endif

Modify the setsockopt function in winrtsock setsockopt.cpp to support the SO_KEEPALIVE option and the set the KeepAlive property on the socket's streamsocketcontrol interface.

http://msdn.microsoft.com/en-us/library/windows/apps/windows.networking.sockets.streamsocketcontrol.keepalive

Thanks,

Dale

**Comment by martell** [comment]
Hey Dale,

Thanks for the feedback CreateEventEx and InitializeCriticalSectionEx Will have to by dynamically loaded just like how I did _GetTickCount64. Should be easy enough then and I'll disable keep alive to suit.
I'll modify to enable the keep alive turned on :)

The last issues is 
__beginthreadex
Which I tried to reimplement in c++/cx but curl is written in pure c so we have issues here :/

Feel Free to fork my repo by the way :)

Can we continue this discussion over on an issue on my repo because it's not cocos specific and I don't want to drag this thread out any longer as it's good to merge for WP8 :)

**Comment by martell** [comment]
I've great news guys. I've added OpenSSL support and added libwebsockets.
They all work on windows phone 8 :)
Will Update shortly

**Comment by minggo** [comment]
@martell  Great news.

**Comment by stammen** [comment]
?Thanks for the awesome news!

**Comment by squirrelChen** [comment]
@martell 
I faced with : fatal error LNK1104: cannot open file 'libeay32.def', while compiled libeay32. Anything woring?

**Comment by squirrelChen** [comment]
Hi @martell ,
any updates?

**Comment by martell** [comment]
@koowolf the .def files were on the git ignore list so thats why they weren't added.
Everything should work fine now :) Sorry about that

**Comment by squirrelChen** [comment]
sorry @martell ,
error LNK2001: unresolved external symbol _sk_num when I builded ssleay32, libeay32 builded OK.

**Comment by minggo** [comment]
@martell 
Any progress of this pull request.
@koowolf reported the link error. Any thought?

**Comment by squirrelChen** [comment]
martell said he didn't face with the error, I will try himself's branch again: https://github.com/martell/cocos2d-x/tree/curl.

**Comment by martell** [comment]
I even have a game on the store with it its all good to me :)

**Comment by squirrelChen** [comment]
@martell  I rebuild again, ssleay32 is OK, but while compile libwebsockets, not found nldef.h, I searched it, it just exists in Windows Kits but not in Windows phone kits. So strange, I build this pr the same results with your branch.. Any ideas?

**Comment by lannes** [comment]
@koowolf I resolve your problem by the way: copy nldef.h from Windows Kits to libwebsockets\lib. Modify  a bit, replace #if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) by #if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_PHONE).

**Comment by squirrelChen** [comment]
Thanks @lannes, it works, but so a strange solution. Not sure it's sdk's bug or we should update vs or sdk.

**Comment by amarcu5** [comment]
I've been successfully using libcurl from @martell in my WP8 game. However when I test with the WP8.1 emulator (using visual studios 2013 Update 2 RC) I cannot make network requests - curl_easy_perform always returns the error code CURLE_RECV_ERROR. Ideas?

**Comment by martell** [comment]
@amarcu5 We are now looking at including this in cocos2d-x as a prebuilt library to ensure consistency. This should be merged during the week. 
Can you try the develop branch with wp8.1 and let me know if it works, if you have the time?
If not I'll have a look at fixing it

**Comment by stammen** [comment]
FYI I am submitting a pull request to the master branch today with the prebuilts libs.

**Comment by martell** [comment]
Hey Dale thanks for the update. :)
@amarcu5 have a look out for this PR

**Comment by stammen** [comment]
I just made the pull request

https://github.com/cocos2d/cocos2d-x/pull/6252

**Pull request closed without merging**
