### PR TITLE
genbinding python detection

### PR DESCRIPTION
**Pull request by luisparravicini**
if PYTHON_BIN is not set, the default value used is /usr/bin
I've added an intermediate step and if PYTHON_BIN is not set, it tries to find python2.7 via "which" and it that fails it defaults to /usr/bin

Issue: http://www.cocos2d-x.org/issues/3732

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks. Could you also update it for `tools/tolua/genbindings.sh`?

**Comment by luisparravicini** [comment]
Done

**Comment by dumganhar** [comment]
Thanks. I will merge it soon.

**Comment by dumganhar** [comment]
We're now using python to generate bindings.
Please refer to https://github.com/cocos2d/cocos2d-x/blob/develop/tools/tojs/genbindings.py#L35
I closed this PR.

**Pull request closed without merging**
