### PR TITLE
Fix linux build

### PR DESCRIPTION
**Pull request by rogerzanoni**
The cocos library uses libpthread and libGL on linux, so we need to link
with them.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @rogerzanoni 
I tested your Pull Request on Ubuntu 12.10 64bit, but it fails with the log as follows:

<pre>
make -C CocosDenshion/proj.linux all
make[1]: Entering directory `/home/james/Project/cocos2d-x/CocosDenshion/proj.linux'
 CXX obj/debug/linux/FmodAudioPlayer.o
 CXX obj/debug/linux/SimpleAudioEngine.o
 LINK ../../cocos2dx/lib/linux/debug/libcocosdenshion.so
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
make[1]: *** [../../cocos2dx/lib/linux/debug/libcocosdenshion.so] Error 1
make[1]: Leaving directory `/home/james/Project/cocos2d-x/CocosDenshion/proj.linux'
make: *** [all] Error 2
</pre>

**Comment by rogerzanoni** [comment]
@dumganhar Do you have libgl1-mesa-dev installed? I don´t see it in the DEPENDS variable in the make-all-linux-project.sh, and I think it's the right package that contains the libGL.so. Maybe it's working for you without the -lGL because another library includes it or another file, like /usr/lib/libGL.so.1, but in my machine (Arch linux 3.7.10-1 - x86_64) I need -lGL to build.

**Comment by rogerzanoni** [comment]
@dumganhar Maybe create another patch adding libgl1-mesa-dev as a dependency?

**Comment by dumganhar** [comment]
@rogerzanoni 
I did install `libgl1-mesa-dev` package. And the package contains file bellow:

<pre>
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libGL.so
/usr/lib/x86_64-linux-gnu/mesa
/usr/lib/x86_64-linux-gnu/mesa/libGL.so
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/gl.pc
/usr/share
/usr/share/bug
/usr/share/bug/libgl1-mesa-dev
/usr/share/bug/libgl1-mesa-dev/control
/usr/share/bug/libgl1-mesa-dev/script
/usr/share/doc
/usr/share/doc/libgl1-mesa-dev
/usr/share/doc/libgl1-mesa-dev/changelog.Debian.gz
/usr/share/doc/libgl1-mesa-dev/copyright
</pre>

**Comment by dumganhar** [comment]
It seems that the path `/usr/lib/x86_64-linux-gnu` wasn't in library search path. 
Is there a way to find out current library linking path in linux system?

**Comment by rogerzanoni** [comment]
ldconfig -v, which also prints the shared libraries found in the listed directories.

**Comment by rogerzanoni** [comment]
I'm not an ubuntu user, so I'm googling this. Looks like in ubuntu the symlinks to shared libraries are mantained by the "alternatives system" and there is no libGL.so pointing to the right version of the GL library in your system.

Can you run 

```
sudo update-alternatives --config gl_conf
```

and see if it shows you some alternatives to GL shared libraries in different locations?

**Comment by dumganhar** [comment]
Hi, @rogerzanoni 
When i executed the command `ldconfig -v | grep GL` in the terminal, it seems to be some `soft link` errors, i mean that the libGL.so link to a wrong place.

<pre>
james@james-vm:~/Project/cocos2d-x$ ldconfig -v | grep GL
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Cannot stat /usr/lib/x86_64-linux-gnu/libGL.so: No such file or directory
/sbin/ldconfig.real: Cannot stat /usr/lib/x86_64-linux-gnu/libnss_db.so: No such file or directory
    libGLU.so.1 -> libGLU.so.1.3.1
    libGLEW.so.1.8 -> libGLEW.so.1.8.0
    libGLEWmx.so.1.8 -> libGLEWmx.so.1.8.0
/sbin/ldconfig.real: Cannot stat /usr/lib/x86_64-linux-gnu/mesa/libGL.so: No such file or directory
    libGL.so.1 -> libGL.so.8.0.18354.823166
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
</pre>

2013-03-20 2 03 47 PM

**Comment by dumganhar** [comment]
Also, `sudo update-alternatives --config gl_conf` can't work in my system. :(

**Comment by rogerzanoni** [comment]
@dumganhar What is the output of `sudo update-alternatives --config gl_conf`?

**Comment by rogerzanoni** [comment]
@dumganhar also `update-alternatives --display gl_conf`

**Comment by rogerzanoni** [comment]
@dumganhar Another solution:

```
sudo apt-get install apt-file
apt-file update
```

Then run `apt-file search libGL.so`, and it'll show the packages containing the lib. Find the package that contains it in the /usr/lib/ and install it.

I've installed ubuntu Lucid Lynx LTS on a virtual machine to test it and the result for this ubuntu version is:

```
zanoni@zanoni-desktop:~$ apt-file search libGL.so | grep "/usr/lib/libGL.so"
libgl1-mesa-dev: /usr/lib/libGL.so
```

**Comment by rogerzanoni** [comment]
@dumganhar In your case, I think it's the `/usr/lib/x86_64-linux-gnu/` folder

**Comment by dumganhar** [comment]
Hi @rogerzanoni 
Are you using a 32bit ubuntu? I'm using 64bit system.
So after i run `apt-file search libGL.so | grep "usr/lib/libGL.so"`, there are nothing output.
But `apt-file search libGL.so` show something as follows:

<pre>
james@james-vm:~$ apt-file search libGL.so
fglrx: /usr/lib/fglrx/libGL.so
fglrx: /usr/lib/fglrx/libGL.so.1
fglrx: /usr/lib/fglrx/libGL.so.1.2
fglrx: /usr/lib32/fglrx/libGL.so.1.2
fglrx-updates: /usr/lib/fglrx/libGL.so
fglrx-updates: /usr/lib/fglrx/libGL.so.1
fglrx-updates: /usr/lib/fglrx/libGL.so.1.2
fglrx-updates: /usr/lib32/fglrx/libGL.so.1.2
libgl1-mesa-dev: /usr/lib/x86_64-linux-gnu/libGL.so
libgl1-mesa-dev: /usr/lib/x86_64-linux-gnu/mesa/libGL.so
libgl1-mesa-glx: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
libgl1-mesa-glx: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
libgl1-mesa-glx-dbg: /usr/lib/debug/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0
lsb-build-base3: /usr/lib/lsb3/libGL.so
nvidia-173: /usr/lib/nvidia-173/libGL.so
nvidia-173: /usr/lib/nvidia-173/libGL.so.1
nvidia-173: /usr/lib/nvidia-173/libGL.so.173.14.35
nvidia-173: /usr/lib/nvidia-173/libGL.so.173.14.36
nvidia-173: /usr/lib32/nvidia-173/libGL.so
nvidia-173: /usr/lib32/nvidia-173/libGL.so.1
nvidia-173: /usr/lib32/nvidia-173/libGL.so.173.14.35
nvidia-173: /usr/lib32/nvidia-173/libGL.so.173.14.36
nvidia-173-updates: /usr/lib/nvidia-173-updates/libGL.so
nvidia-173-updates: /usr/lib/nvidia-173-updates/libGL.so.1
nvidia-173-updates: /usr/lib/nvidia-173-updates/libGL.so.173.14.35
nvidia-173-updates: /usr/lib32/nvidia-173-updates/libGL.so
nvidia-173-updates: /usr/lib32/nvidia-173-updates/libGL.so.1
nvidia-173-updates: /usr/lib32/nvidia-173-updates/libGL.so.173.14.35
nvidia-current: /usr/lib/nvidia-current/libGL.so
nvidia-current: /usr/lib/nvidia-current/libGL.so.1
nvidia-current: /usr/lib/nvidia-current/libGL.so.304.43
nvidia-current: /usr/lib32/nvidia-current/libGL.so
nvidia-current: /usr/lib32/nvidia-current/libGL.so.1
nvidia-current: /usr/lib32/nvidia-current/libGL.so.304.43
nvidia-current-updates: /usr/lib/nvidia-current-updates/libGL.so
nvidia-current-updates: /usr/lib/nvidia-current-updates/libGL.so.1
nvidia-current-updates: /usr/lib/nvidia-current-updates/libGL.so.304.51
nvidia-current-updates: /usr/lib32/nvidia-current-updates/libGL.so
nvidia-current-updates: /usr/lib32/nvidia-current-updates/libGL.so.1
nvidia-current-updates: /usr/lib32/nvidia-current-updates/libGL.so.304.51
nvidia-experimental-304: /usr/lib/nvidia-experimental-304/libGL.so
nvidia-experimental-304: /usr/lib/nvidia-experimental-304/libGL.so.1
nvidia-experimental-304: /usr/lib/nvidia-experimental-304/libGL.so.304.48
nvidia-experimental-304: /usr/lib32/nvidia-experimental-304/libGL.so
nvidia-experimental-304: /usr/lib32/nvidia-experimental-304/libGL.so.1
nvidia-experimental-304: /usr/lib32/nvidia-experimental-304/libGL.so.304.48
nvidia-experimental-310: /usr/lib/nvidia-experimental-310/libGL.so
nvidia-experimental-310: /usr/lib/nvidia-experimental-310/libGL.so.1
nvidia-experimental-310: /usr/lib/nvidia-experimental-310/libGL.so.310.14
nvidia-experimental-310: /usr/lib32/nvidia-experimental-310/libGL.so
nvidia-experimental-310: /usr/lib32/nvidia-experimental-310/libGL.so.1
nvidia-experimental-310: /usr/lib32/nvidia-experimental-310/libGL.so.310.14
</pre>

**Comment by rogerzanoni** [comment]
Can you run `sudo apt-get install --reinstall libgl1-mesa-dev` and see if it creates the correct symlinks?

**Comment by dumganhar** [comment]
OK, i'll try.

**Comment by rogerzanoni** [comment]
It worked?

**Comment by dumganhar** [comment]
Hi, @rogerzanoni 
I have not enough time to test that. I'm very very busy these days.
I'll test it, maybe next week. Thanks. :)

**Comment by vovkasm** [comment]
+1 for merge this request.
I made a similar change in my clone https://github.com/vovkasm/cocos2d-x/commit/3b781e812e9152478e2f00c04d4893f137093d5a
(It works under ArchLinux)

**Comment by mdkcore0** [comment]
+1 for this too
With this change, works flawless on Slackware linux

**Comment by dumganhar** [comment]
@rogerzanoni 
I fixed the issue which can't find `-lGL` by changing the symlinks to the right libGL.so.

<pre>
/usr/lib/x86_64-linux-gnu/libGL.so ~> /usr/lib/x86_64-linux-gnu/mesa/libGL.so
/usr/lib/x86_64-linux-gnu/mesa/libGL.so ~> /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0 (which doesn't exist, but there is a libGL.so.8.0.18354.823166 in the same directory.)
I corrected it by:
sudo cp libGL.so.8.0.18354.823166 libGL.so.1.2.0
</pre>

And it works now.
Is it a bug of `libgl1-mesa-dev` ? Did we need to correct it by `cp` in our `make-all-linux-project.sh`?

**Comment by dumganhar** [comment]
Merged. Thanks.

**Comment by rogerzanoni** [comment]
@dumganhar I think the best solution is to manage the symlinks with the alternatives system or manually changing them

**Pull request merged**
