### PR TITLE
bugfix for UI animation playing crash if GUI JSON file is loaded again.

### PR DESCRIPTION
**Pull request by hongliang-goudou**
_actionDic is a std::unordered_map, the insert() function will not work if the key is already existed. If a UI JSON file is loaded by GUIReader more than once, the animation information should update in the internal _actionDic map, as the rootWidget pointer is different.

...Detail see: http://blog.segmentfault.com/hongliang/1190000000659937

### CODE REVIEW

**Comment by zilongshanren** [comment]
@hongliang-goudou 
Thanks, I will test your code on v3.3.

**Comment by minggo** [comment]
@hongliang-goudou 
I think this PR include many modification that is nothing about this PR.

**Comment by hongliang-goudou** [comment]
@minggo sorry about that, not very good at git and github. :(

**Comment by minggo** [comment]
No matter, would you please send a new PR.
And you can do it like this(suppose you have v3 too):

```
git checkout v3
git pull --rebase https://github.com/cocos2d/cocos2d-x.git
git checkout -b new_branch
```

Than continue your work in new_branch.

**Comment by hongliang-goudou** [comment]
I'll send a new PR. This one close.

**Comment by minggo** [comment]
Thanks @hongliang-goudou .

**Pull request closed without merging**
