### PR TITLE
fix font render blur

### PR DESCRIPTION
**Pull request by dualface**
CCImage rendering fonts on a texture. If the width and height of the texture is not even, then the display will appear blur.

CCImage 渲染字体到一个材质上。如果材质的宽度和高度不是偶数，显示时就会变得模糊。这是因为默认的 anchor point 是材质中心，非偶数的材质中心点位置变成了小数，所以会模糊。

### CODE REVIEW

**Comment by dualface** [comment]
Please merge this pull request, it is very important

**Comment by dumganhar** [comment]
Could this issue be resolved by enabling the macro `CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL`?

**Comment by dualface** [comment]
I think CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL can't solve this problem.

See code in CCSprite:411:

``` c++
#if CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL
        left    = (2*rect.origin.x+1)/(2*atlasWidth);
        right    = left + (rect.size.width*2-2)/(2*atlasWidth);
        top        = (2*rect.origin.y+1)/(2*atlasHeight);
        bottom    = top + (rect.size.height*2-2)/(2*atlasHeight);
#else
        left    = rect.origin.x/atlasWidth;
        right    = (rect.origin.x + rect.size.width) / atlasWidth;
        top        = rect.origin.y/atlasHeight;
        bottom    = (rect.origin.y + rect.size.height) / atlasHeight;
#endif // ! CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL
```

this line :

``` c++
left    = (2*rect.origin.x+1)/(2*atlasWidth);
```

Example:

``` c++
rect.origin.x = 0;
atlasWidth = 99;
left = 0.01010101
```

Whether rect.orgin.x what value, value of **left** is not a integer. CC_FIX_ARTIFACTS_BY_STRECHING_TEXEL make sprite more blur ?

**Comment by tiantian20007** [comment]
It seems work fine when using resource with the same size of designResolution. However, sprite still get blur when using resource image with half size of designResolution. For example, designResolution = (960,640), all my resource image for iPhone3 is under (480,320), and ContentScaleFactor is 0.5.

**Comment by dumganhar** [comment]
> It seems work fine when using resource with the same size of designResolution. However, sprite still get blur when using resource image with half size of designResolution. For example, designResolution = (960,640), all my resource image for iPhone3 is under (480,320), and ContentScaleFactor is 0.5.

@dualface 
Could you fix the issue @tiantian20007 said?

**Comment by sachingarg05** [comment]
I am having same problem with blurred text. Disabling anti-aliasing is a workaround to fix blurred text but it makes other textures look bad. Can we please merge this pull request? Or have cocos2dx disable anti-aliasing for font textures?

**Comment by ricardoquesada** [comment]
Having high quality fonts is a priority.
I haven't reviewed this patch, but if the fonts are blurry we need to fix it.

**Comment by sachingarg05** [comment]
@dualface Why did you close this pull request? Is there another pull request which fixed the blurry fonts or some other fix for this issue?

**Comment by dualface** [comment]
I will send an other PR for this issue :)

YuLei Liao (dualface)
qeeplay.com

**Comment by sachingarg05** [comment]
Thanks. I am really looking forward to a proper fix for this issue. Only 'hack' that I could implement to fix this for my app was to disable anti-aliasing everywhere.

**Pull request closed without merging**
