### PR TITLE
Update for spine runtime

### PR DESCRIPTION
**Pull request by slobodin**
Updates of "spine" animation system.

### CODE REVIEW

**Comment by dumganhar** [comment]
Looks good, Could you tell me which commit in https://github.com/EsotericSoftware/spine-runtimes you synchronized to. Thanks.

**Comment by lumendes** [comment]
Aren't this and PR 2548 issuing the same thing ?

**Comment by slobodin** [comment]
dumganhar, That was https://github.com/EsotericSoftware/spine-runtimes/commit/2e8f66631e3750f34c806d776e20248445ab0060 commit.

**Comment by dumganhar** [comment]
@flaming0 
We can’t automatically merge this pull request. Maybe there are some conflicts.
Could you pull the latest codes?

@lumendes 
Yes, I think this PR is the same as yours. But @flaming0 sync it to EsotericSoftware/spine-runtimes@2e8f666 which is later than you. Do you mind I choose this one, but adding all of you to AUTHORS list?

Thanks.

**Comment by lumendes** [comment]
@dumganhar Sure no problem, this is not a competition. We just want to improve cocos2dx to be even better :)

**Comment by dumganhar** [comment]
@lumendes 
:)

**Comment by slobodin** [comment]
@dumganhar 
Yes, but I can do it later this day.

**Comment by dumganhar** [comment]
@flaming0 
OK. Thanks. :)

**Comment by slobodin** [comment]
I've pushed the latest update of spine runtimes into my branch (Lates commit is https://github.com/EsotericSoftware/spine-runtimes/commit/5f903865f7183561d35ad687d48a07cb55e631f0)

**Comment by slobodin** [comment]
Or maybe should I create new pull request with all changes combined into one commit?

**Comment by minggo** [comment]
@flaming0 
You can do it for your convenience.

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2745.
Thanks. I have added you to AUTHORS.

**Comment by slobodin** [comment]
Thank you!

**Comment by mdkcore0** [comment]
Spine is broken on Linux, again (the same error it has when it was first added).

It's not better to treat it as a git submodule and apply cocos2d-x relative patches on the compilation time?

**Comment by dumganhar** [comment]
@rodrigogolive 
Did you see that it compiled ok at travis-ci (https://travis-ci.org/cocos2d/cocos2d-x/builds/7761144)?
Maybe it's not compatible with gcc 4.7, i think we should send Pull Request to https://github.com/EsotericSoftware/spine-runtimes to avoid these errors when updating spine-runtime. Do you agree?

**Comment by mdkcore0** [comment]
@dumganhar I was editing my comment to add additional information :p

I'm using gcc 4.8.0 here, but I was taking a look on their repository. According to their repo organization, I agree with you that it's better to send PR direct to them.

Thank you ;)

**Pull request merged**
