### PR TITLE
jsb.addRoot is not a function

### PR DESCRIPTION
**Pull request by samael65535**
jsb.addRoot is not a function

### CODE REVIEW

**Comment by pandamicro** [comment]
Thanks I will take a look

**Comment by pandamicro** [comment]
Actually the whole override is not needed anymore, can you remove this section ? @samael65535

**Comment by samael65535** [comment]
嗯, 中文吧, 英文有些不理解, 意思是 cc.GLProgramState.prototype.setUniformCallback  整个函数都删了?

**Comment by minggo** [comment]
@pandamicro any update?

**Comment by ricardoquesada** [comment]
sounds right, `addRoot` doesn't exist. 
according to the other js callbacks, we shouldn't root it.

**Comment by minggo** [comment]
@pandamicro any idea about @samael65535 's new comment?

> �嗯, 中文吧, 英文有些不理解, 意思是 cc.GLProgramState.prototype.setUniformCallback 整个函数都删了?

**Comment by pandamicro** [comment]
Yes, I mean we can remove the whole override of `cc.GLProgramState.prototype.setUniformCallback`, no need to root anything

**Comment by minggo** [comment]
@samael65535 any update?

**Comment by samael65535** [comment]
@minggo 
I have already removed

`
  if (!jsb._root) {     
       jsb._root = {};      
     }      
     var owner = jsb._root;     
    jsb.addRoot(owner, callback);
`

**Comment by minggo** [comment]
@samael65535 if i understand correctly, @pandamicro means to remove all the codes

```
cc.GLProgramState.prototype.setUniformCallback = function (uniform, callback) {      
     if (!jsb._root) {      
         jsb._root = {};        
     }      
     var owner = jsb._root;     
     jsb.addRoot(owner, callback);      
      jsbSetUniformCallback.call(this, uniform, callback);            
  };
```

**Comment by samael65535** [comment]
@minggo 

If I removed all the code, I could not handle shader in Native.

https://github.com/samael65535/GameLab/blob/master/src/HueTest.js#L161

**Comment by minggo** [comment]
I will ask @pandamicro to confirm it.

**Pull request merged**
