### PR TITLE
Implemented CCDictionary::writeToFile with CCDataVisitor.

### PR DESCRIPTION
**Pull request by sergey-shambir**
1. More strict code with wider types set.
2. Visitor is faster than dynamic_cast.
3. Added fully automatic tests.

### CODE REVIEW

**Comment by dumganhar** [comment]
About 2) Visitor is faster than dynamic_cast.?
Did you make a performance test?

**Comment by dumganhar** [comment]
BTW, ci build fails. Could you please look at it?

**Comment by sergey-shambir** [comment]
I've not updated XCode projects for Mac and iOS (and going to do it tomorrow). Everything else was updated (makefiles, vcproj).

**Comment by sergey-shambir** [comment]
I've not updated some makefiles and used exceptions. I will fix it soon.

**Comment by sergey-shambir** [comment]
Please check if it builds correctly on Mac/iOS, since i've added files and folder manually.

`CCData` support and `CCArray::writeToFile` are missed, I think there are no need to fix it in this pull request.

**Comment by sergey-shambir** [comment]
About dynamic cast: virtual method call faster ~10 times on Visual C++ and ~3 times on g++/clang. Also visitor needs only 2 virtual method calls (`accept` & `visit`), while any other approach requires chain of `if` checks, each check needs `dynamic_cast` or substring lookup in `typeid(*obj).name()`.

http://tinodidriksen.com/2010/04/14/cpp-dynamic-cast-performance/

**Pull request closed without merging**
