### PR TITLE
CocosPlayer for iOS

### PR DESCRIPTION
**Pull request by rohankuruvilla**
Includes:
1. CocosPlayer for iOS
2. Bug fixes to CocosPlayer for Android.

Needs a few more bug fixes. Missing features/bugs:
1. Orientation change not working
2. Redirect log statements over the network (Working on iOS)

### CODE REVIEW

**Comment by minggo** [comment]
Thank you.
Could you please also update README?

**Comment by minggo** [comment]
Will you fix bugs in this pull request or create another one?

**Comment by rohankuruvilla** [comment]
Hi Minggo,

Sorry for the late reply. Yes, I'll fix the bugs in this PR.

Note:
1. Send filelist from CocosPlayer Android (Bug in CocosBuilder does not allow consistent behavior after sending updated filelist. Will be fixed in a separate PR)

Thanks,

Rohan

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/2477.
Thanks @rohankuruvilla .

**Pull request merged**
