### PR TITLE
Add destroyCocosStudio()

### PR DESCRIPTION
**Pull request by xiaofeng11**
Unified all singleton class cleanup function to destroyInstance(), and add destroyCocosStudio() to provide cocos reader related resource cleanup function.

### CODE REVIEW

**Comment by minggo** [comment]
Why not deprecated function instead?
It will break compatibility.

**Comment by xiaofeng11** [comment]
OK, We will update the code

**Comment by xiaofeng11** [comment]
code updated with minggo suggestion

**Comment by xiaofeng11** [comment]
Add cocosstudio.cpp and move cleanup function to this file

**Comment by minggo** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@xiaofeng11 , where is the `ArmatureDataManager::destroyInstance()` invoked?

**Comment by dumganhar** [comment]
And where is `SceneReader::destroyInstance()` invoked?

**Comment by dumganhar** [comment]
And `ActionManagerEx::destroyInstance()`

**Comment by dumganhar** [comment]
Why there are `timeline::NodeReader` & `NodeReader`?
I mean `editor-support/cocostudio/ActionTimeline/CCNodeReader.h/.cpp` 
`editor-support/cocostudio/WidgetReader/NodeReader/NodeReader.h/.cpp`
Their class name is the same but in different namespaces. _It's really make people confused!_.

And where is `timeline::NodeReader::destroyInstance()` invoked?

**Comment by pipu** [comment]
@dumganhar 
In cocos2d-x 3.x, editor-support/cocostudio/ActionTimeline/CCNodeReader.h/.cpp have not been used any more.

**Comment by dumganhar** [comment]
Where is `GUIReader::destroyInstance()` invoked?

**Comment by dumganhar** [comment]
@pipu , if it isn't used, why not delete them ?
Is it for compatibility for old version?

**Pull request merged**
