### PR TITLE
fix rotationx and rotationy

### PR DESCRIPTION
**Pull request by super626**
Do not hurry to merge it, discussion is here,
http://discuss.cocos2d-x.org/t/possible-bug-on-rotation-and-scale-in-the-node/18601

### CODE REVIEW

**Comment by darkdukey** [comment]
Can you create a test case for it?

**Comment by ricardoquesada** [comment]
let's add test case and merge it for v3.4

**Comment by minggo** [comment]
@super626 
Could you please add a test case?

**Comment by super626** [comment]
I see

**Comment by minggo** [comment]
What's the relationship with #9611?

**Comment by super626** [comment]
@minggo 
#9611 can fix this issue, I have tested.
So this pull request can be abandoned.

**Pull request closed without merging**
