### PR TITLE
Upgrades to Spine v3.4

### PR DESCRIPTION
**Pull request by ricardoquesada**
Github issue #16115

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@minggo is there a way to skip the "check headers" from CI for the spine project?
I want to use an unmodified spine code. And the builder is failing because of that. thanks.

**Comment by minggo** [comment]
What did you mean `check headers`?

**Comment by ricardoquesada** [comment]
@minggo yes, that one. I can change it myself if you tell where it is. thanks.

**Comment by minggo** [comment]
Oh, i remembered. It is a tool in `tools/coding-style/include-linter.py`. It is contributed by developers. I don't know how to skip spine files. You can take a look and let me know if you need any help.

**Comment by mogemimi** [comment]
Hi. I found the way to skip specific files:
https://github.com/cocos2d/cocos2d-x/blob/v3/tools/coding-style/include-linter.py#L46-L54

I tried the following code and it works fine. :relaxed:

``` python
# ...
class LintContext:
  def __init__(self, root, fix):
    self.exclude = [
      # exclude some platform specific files.
      'platform/win8.1-universal/Cocos2dRenderer.cpp',
      'platform/win8.1-universal/OpenGLES.cpp',
      'platform/win8.1-universal/OpenGLESPage.xaml.cpp',
      'platform/win8.1-universal/OpenGLESPage.xaml.h',
      'platform/win8.1-universal/pch.cpp',
      'platform/winrt/pch.cpp',
      'editor-support/spine/Json.c',
      'editor-support/spine/PathConstraint.h',
      'editor-support/spine/SkeletonJson.c',
    ]
# ...
```

``` sh
$ cd path/to/cocos2d-x
$ python tools/coding-style/include-linter.py
Checking headers in: /path/to/cocos2d-x/cocos
Total: 0 errors in 0 files
```

**Comment by ricardoquesada** [comment]
@minggo @mogemimi thanks!

**Pull request merged**
