### PR TITLE
Fixes crash of lua particle test while building lua-tests in release mode.

### PR DESCRIPTION
**Pull request by dumganhar**
fixed http://punchbox.info:3000/issues/26317

### CODE REVIEW

**Comment by minggo** [comment]
@dumganhar  i think we should send it to v3.16 branch too.

**Comment by dumganhar** [comment]
Yes, I forgot.

**Comment by dumganhar** [comment]
@minggo ,it's here: https://github.com/cocos2d/cocos2d-x/pull/18222

**Comment by minggo** [comment]
thanks

**Pull request merged**
