### PR TITLE
Fix: not cransh on android when mapBuffer() is not present

### PR DESCRIPTION
**Pull request by ricardoquesada**
more info:
https://www.khronos.org/registry/gles/extensions/OES/OES_mapbuffer.txt

Issue #15805

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@dumganhar could you review this patch and test it? if it works, could you merge it? thanks.

**Comment by dumganhar** [comment]
Hi, @ricardoquesada , 
The patch should work.
But does `VAO` depend on `glMapBuffer`? Should they be two different configurations?

For instance:

Now we have code like this:

``` c++
    if (Configuration::getInstance()->supportsShareableVAO())
    {
        //Bind VAO
        GL::bindVAO(_buffersVAO);
        //Set VBO data
        glBindBuffer(GL_ARRAY_BUFFER, _buffersVBO[0]);

        // option 1: subdata
//        glBufferSubData(GL_ARRAY_BUFFER, sizeof(_quads[0])*start, sizeof(_quads[0]) * n , &_quads[start] );

        // option 2: data
//        glBufferData(GL_ARRAY_BUFFER, sizeof(_verts[0]) * _filledVertex, _verts, GL_STATIC_DRAW);

        // option 3: orphaning + glMapBuffer
        // FIXME: in order to work as fast as possible, it must "and the exact same size and usage hints it had before."
        //  source: https://www.opengl.org/wiki/Buffer_Object_Streaming#Explicit_multiple_buffering
        // so most probably we won't have any benefit of using it
        glBufferData(GL_ARRAY_BUFFER, sizeof(_verts[0]) * _filledVertex, nullptr, GL_STATIC_DRAW);
        void *buf = glMapBuffer(GL_ARRAY_BUFFER, GL_WRITE_ONLY);
        memcpy(buf, _verts, sizeof(_verts[0]) * _filledVertex);
        glUnmapBuffer(GL_ARRAY_BUFFER);

        glBindBuffer(GL_ARRAY_BUFFER, 0);

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, _buffersVBO[1]);
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(_indices[0]) * _filledIndex, _indices, GL_STATIC_DRAW);
    }
```

If glMapBuffer doesn't exist on some devices, but they support `VAO` feature, should we not keep using `glMapBuffer`? For example, we could use `glBufferData` or `glBufferSubData`?

**Comment by ricardoquesada** [comment]
@dumganhar yes, probably it is better to do what you said.
Mine was a quick patch based on your comments on the other thread were you commented out the VAO define.

**Comment by dumganhar** [comment]
Yep, it's a quick fix. It's good for me to merge it.
Generally, developers will not change the macros in ccConfig.h. I means `CC_TEXTURE_ATLAS_USE_VAO` is normally disabled for Android. :)
Should I merge it after testing? Or just waiting for the new update?

**Comment by ricardoquesada** [comment]
@dumganhar 
I'll be away until Tuesday. If you can wait, I'll send you a better patch on Tuesday. Thanks

**Comment by dumganhar** [comment]
@ricardoquesada , yep, I'm ok for waiting a better patch. :)

**Comment by minggo** [comment]
@ricardoquesada will you continue working on this PR or you will create a new one?

**Comment by ricardoquesada** [comment]
@minggo I'll update this one later today or tomorrow.

**Comment by minggo** [comment]
@ricardoquesada got it, thanks.

**Comment by ricardoquesada** [comment]
@dumganhar I've just updated the PR. Could you please review it? If you like it, feel free to merge it. Thanks!

@minggo done. PR updated.

**Comment by dumganhar** [comment]
@ricardoquesada , thanks. I'm reviewing. :)

**Comment by dumganhar** [comment]
@minggo , I don't have any problems of this PR. Please merge it. Thanks.

**Comment by minggo** [comment]
Thanks guys.

**Pull request merged**
