### PR TITLE
Android cmake support

### PR DESCRIPTION
**Pull request by ricardoquesada**
CMake support for Android based on this PR: https://github.com/cocos2d/cocos2d-x/pull/13754/files and this one: https://github.com/WenhaiLin/cocos2d-x/pull/6/files

commit 2ef52723dae44204c047cb177d5a5670fb659c79
Merge: 8a5c998 25cf1f1
Author: Ricardo Quesada ricardoquesada@gmail.com
Date:   Tue Mar 1 16:54:04 2016 -0800

```
Merge branch 'v3' into cmake_android
```

commit 8a5c9981192e344fffc9f14be5cb14f66eccfa24
Author: Chaoren Lin chaorenl@google.com
Date:   Thu Feb 11 18:34:46 2016 -0800

```
Fix module name in Android template to match CMake project.
```

commit be85e19e852a9d5fbd6c58cea60c75fe47a5a576
Author: Chaoren Lin chaorenl@google.com
Date:   Thu Feb 11 18:27:45 2016 -0800

```
Add missing platform specific source file to CMake project.
```

commit 705389ac6582107a381d0cbc56268eaa98ffc5c3
Author: Chaoren Lin chaorenl@google.com
Date:   Wed Feb 10 19:21:12 2016 -0800

```
Find AndroidNdkModules.cmake relative to android.toolchain.cmake.
```

commit a10075e2cb30af2e1f9a30da99efac880658ad6b
Author: Chaoren Lin chaorenl@google.com
Date:   Wed Feb 10 19:03:11 2016 -0800

```
Remove cpp-empty-test from project templates.
```

commit e070fcbf210b8628f75785e738202a80a95ac0ff
Author: WenhaiLin wenhai.lin@chukong-inc.com
Date:   Mon Aug 31 09:56:03 2015 +0800

```
Fix CMake for Android Target
```

### CODE REVIEW

**Comment by zilongshanren** [comment]
@ricardoquesada  :+1: 
Thanks, I think the previous PR broken the CI, please help to fix it...

**Comment by ricardoquesada** [comment]
@zilongshanren sure! do you know where?

Also, I noticed you changed the order of `ssl` and `crypto`... in the libs. Why was that? Currently I'm having linking issues with libssl and I don't know why.
Your PR compiles Ok... but after merging everything in v3, it doesn't link. Any idea? Thanks.

**Comment by zilongshanren** [comment]
@ricardoquesada  The jsb auto bindings files for chipmunk are missing, the config files are missing in directory "tools/tojs/"... I think you forget to push them to v3 branch...

ssl dependent on crypto, so when link these two libs, we should put crypto after ssl.

**Comment by ricardoquesada** [comment]
@zilongshanren ok. thanks.

And yes, you are right about the order. I've just read this good article about dependencies in static libraries: http://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking

**Comment by zilongshanren** [comment]
@ricardoquesada  Nice articles!  So when will you plan to fix the jsb bindings issue?

**Comment by ricardoquesada** [comment]
@zilongshanren tomorrow... hopefully everything will run by tomorrow :) (Wednesday)

**Comment by zilongshanren** [comment]
@ricardoquesada  
Great :smile:

**Comment by ricardoquesada** [comment]
@zilongshanren link issue fixed for Android.

do you know why `cocos2d` was renamed to `cocos2dInternal`. CMake + Linux is raising some warnings because of that. It says that "cocos2d" lib is empty.... and I'm having issues with CMake + Mac, which `ar` is not generating the lib (perhaps because it is empty?)

Any idea? Thanks.

**Comment by ricardoquesada** [comment]
squashed PR is this one:
https://github.com/cocos2d/cocos2d-x/pull/15156

**Pull request closed without merging**
