### PR TITLE
[ci rebuild] Notification effect enhancement

### PR DESCRIPTION
**Pull request by ZhangMenghe**
- To solve the problem #13477
- Solved in Web Engine (https://github.com/cocos2d/cocos2d-html5/pull/3073)
- Update testcase in js-test to show notificationNode to  runAction

@fusijie Please have a look, thanks!

### CODE REVIEW

**Comment by fusijie** [comment]
@ZhangMenghe Please check background and foreground status in Android/iOS.

**Comment by fusijie** [comment]
[ci rebuild]

**Comment by ZhangMenghe** [comment]
@fusijie @pandamicro 
I've checked that, everything goes well ; )

**Comment by fusijie** [comment]
To fix https://github.com/cocos2d/cocos2d-x/issues/9466.

@pandamicro It can be merged, and we should tell devers to notice that in release note, because I had told someone to call onEnter/onEnterTransitionDidFinish manually.

**Pull request merged**
