### PR TITLE
fix CCScale9Sprite CapInsets bug for rotated sprite frame

### PR DESCRIPTION
**Pull request by pktangyue**
If a spriteframe is rotated and I set the insets value, the displayed sprite would be in a mess.

### CODE REVIEW

**Comment by dumganhar** [comment]
There is a `Scale9SpriteTest` in `TestJavascript` project. Could you add a test for this issue?

**Comment by pktangyue** [comment]
Sorry, I can't find `Scale9SpriteText` in `TestJavascript` project

**Comment by dumganhar** [comment]
Which platform are you using ?
It's in `cocos2d-x/samples/Javascript/Shared/tests/ExtensionsTest/S9SpriteTest/S9SpriteTest.js`

**Comment by pktangyue** [comment]
I'm using iOS platform, and always use C++. Using js to write a test seems a little difficult to me.

**Comment by dumganhar** [comment]
Yep, I think TestCpp should also contain a test for Scale9Sprite.

**Comment by dumganhar** [comment]
@pktangyue 
I have added `Scale9SpriteTest` for TestCpp project.
It was done at https://github.com/cocos2d/cocos2d-x/pull/3129
Could you add a new test to `ExtensionsTest/Scale9SpriteTest` for this issue now?

**Comment by pktangyue** [comment]
I have added it.

**Comment by dumganhar** [comment]
Thank you. I'll merge it.

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/3133.

**Pull request merged**
