### PR TITLE
Added win32 project for samples/Cpp/SimpleGame

### PR DESCRIPTION
**Pull request by timothyqiu**
A win32 project for samples/Cpp/SimpleGame.
1. Copied the project from template/multi-platform-cpp/proj.win32 
2. Renamed the project files accordingly
3. Added GameOverScene.h and GameOverScene.cpp to SimpleGame.vcxproj and SimpleGame.vcxproj.filters
4. Replaced all relative ../../../xxx to ../../../../xxx

Tested on Windows 7 with Visual Studio Express 2012 for Windows Desktop.

### CODE REVIEW

**Comment by dumganhar** [comment]
Why do we need `SimpleGame.sln`? The project was included in the big `solution`.

**Comment by timothyqiu** [comment]
Sorry. I never opened the big `cocos2d-win32.vc2012.sln` solution before, and thought that it's only a library-building solution. (No wonder I was confused by the missing solution file in HelloCpp/TestCpp...)

Working on it. (Remove the `SimpleGame.sln`, add the project to `cocos2d-win32.vc2012.sln`)

**Comment by timothyqiu** [comment]
Hi,

I made the commit. When I add the project, my Visual Studio Express 2012 removed the whole `GlobalSection(NestedProjects)` section from `cocos2d-win32.vc2012.sln` automatically. I think that section might be important and restored the section manually.

The final solution works for my express version VS, but I am worried that it might not work in other versions. (I searched the commit history, that section was first introduced the same time as the solution file changes from express version to none-express version.)

Could you test it on a none-express version of Visual Studio?

**Comment by dumganhar** [comment]
@timothyqiu 
Thanks. I noticed that, there isn't `SimpleGame` project in VS2012.
Yep, I think we need to add it. I'll test this PR in none-express version of VS.

**Comment by dumganhar** [comment]
SimpleGame was removed from `.sln`.
We moved `samples` to https://github.com/cocos2d/cocos-samples
I closed this PR . Thanks.

**Pull request closed without merging**
