### PR TITLE
ImagePicker utility with support for Android/iOS(iPhone+iPad)/Win/OSX

### PR DESCRIPTION
**Pull request by 0xJimmyBeh**

### CODE REVIEW

**Comment by minggo** [comment]
@Zinitter 
Thanks.
Why add image picker support?

**Comment by lalaloha** [comment]
Finally! I needed this feature before to make apps that can use custom pictures from their phones. Maybe this can be added to extension if it's not making sense to add to core engine :)

**Comment by 0xJimmyBeh** [comment]
@minggo 
Image picker is part of the basic mobile features as issue here : 
https://github.com/cocos2d/cocos2d-x/issues/10293

We can use image picker to upload image and there are many usages with the upload image features.

For example :
Customise our profile picture
Share screenshot (game or report bug)
Exchange photo

Nowadays, we can't provide only playing feature in a game. 
We have to provide more features to attract and keep users in the game like a community which can share and discuss.

From a post on Cocos2d-x forum, @ricardoquesada said
"Yes, we want cocos2d-x to be much more than just a renderer."

http://discuss.cocos2d-x.org/t/development-impression/20862/14

I believe the basic mobile features support are a must to improve gaming experience but not limited to game usage since Cocos2d-x can be used to develop utility app as what i doing now.

Thanks.

**Comment by 0xJimmyBeh** [comment]
Please refer to the pull request of author
https://github.com/cocos2d/cocos2d-x/pull/11344

**Pull request closed without merging**
