### PR TITLE
Added Dutch Language support for 2.x branch

### PR DESCRIPTION
**Pull request by martell**
Added Support for the Dutch language for all possible platforms.

Please Merge

Thank You

### CODE REVIEW

**Comment by dumganhar** [comment]
How about sending this PR to develop branch too?

**Comment by martell** [comment]
I didn't know if you wanted more languages. I have Dutch in a game so no point in wasting code ;) 

I will do a pr for develop in the morning

**Comment by martell** [comment]
Done now for develop branch also

**Comment by martell** [comment]
@dumganhar Can you merge this please?

**Comment by dumganhar** [comment]
Merged. Thanks.

**Pull request merged**
