### PR TITLE
fix property anchorPoint of CCScale9Sprite 

### PR DESCRIPTION
**Pull request by zhanghaojie**
fix property anchorPoint of CCScale9Sprite doesn't work in ccb. Because initSpriteFrame method reset anchor point

### CODE REVIEW

**Comment by zhanghaojie** [comment]
oh!  it seems still not good. setSpriteFrame reset inset property. forget my commit. maybe add a new method or add argument is a good idea

**Comment by zhanghaojie** [comment]
my commit it works for now.  setSpriteFrame is called before setInset method.  but it is dangerous if ccb loader exchange the call sequence

**Comment by dumganhar** [comment]
Hi @zhanghaojie ,
Your change seems great. Thanks for your feedback and bug fix.

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/2370. Thanks.

**Pull request merged**
