### PR TITLE
Fix proj.android/jni/Android.mk

### LINKED ISSUE #17640: Cannot build Android project using cocos compile -p android
- cocos2d-x version: v3 branch up to git commit acc97516d8
- developing environments
   - NDK version: r14b

Steps to Reproduce:

1. Create a new project using git commit acc97516d8 and try to compile for Android
 ````shell
cocos new -l cpp android_build_test
cd android_build_test
cocos compile -p android --ap android-19 -m release -j`nproc` --ndk-toolchain arm-linux-androideabi-4.9
````
2. You'll get the following error:

````
make: Entering directory `.../project_root/proj.android'
make: *** No rule to make target `jni/jni/hellocpp/main.cpp', needed by `obj/local/armeabi/objs-debug/MyGame_shared/jni/hellocpp/main.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory `.../project_root/proj.android'
````

Possible fix:

This issue was introduced in commit 55362547fa. Removing  `$(LOCAL_PATH)` from `LOCAL_SRC_FILES` in `proj.android/jni/Android.mk` fixes this issue.

### PR DESCRIPTION
**Pull request by Rubonnek**
Fixes #17640

### CODE REVIEW

**Comment by minggo** [comment]
It is strange, `LOCAL_PATH` is  the current path.

**Comment by Rubonnek** [comment]
I just added `$(warning $(LOCAL_PATH))` to check, and it seems to point to `.../project_root/androidtest/proj.android/jni` which makes sense, yet
````shell
cocos compile -p android --ap android-19 -m release -j`nproc` --ndk-toolchain arm-linux-androideabi-4.9
````
still doesn't build the project.

I'm not sure if this is related, but I also found it strange that I included `$(warning $(LOCAL_PATH))` only once, but I still get two messages:
```
jni/Android.mk:2: jni
jni/Android.mk:2: jni
```

Here's the full error log for reference:

````
Building mode: release
Using Eclipse project : .../project_root/androidtest/proj.android
running: '/opt/android-sdk/tools/android update project -t android-19 -p .../project_root/androidtest/proj.android'

Updated project.properties
Updated local.properties
Updated file .../project_root/androidtest/proj.android/proguard-project.txt
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
running: '/opt/android-sdk/tools/android update lib-project -p .../project_root/androidtest/cocos2d/cocos/platform/android/java -t android-19'

Updated project.properties
Updated local.properties
Updated file .../project_root/androidtest/cocos2d/cocos/platform/android/java/proguard-project.txt
Building native...
NDK build mode: release
running: '/opt/android-ndk/ndk-build -C .../project_root/androidtest/proj.android -j8 NDK_TOOLCHAIN=arm-linux-androideabi-4.9 NDK_MODULE_PATH=.../project_root/androidtest/cocos2d:.../project_root/androidtest/cocos2d/cocos:.../project_root/androidtest/cocos2d/external NDK_TOOLCHAIN_VERSION=4.9'

Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml    
make: Entering directory `.../project_root/androidtest/proj.android'
jni/Android.mk:2: jni
jni/Android.mk:2: jni
make: *** No rule to make target `jni/jni/../hellocpp/main.cpp', needed by `obj/local/armeabi/objs/MyGame_shared/jni/__/hellocpp/main.o'.  Stop.
make: *** Waiting for unfinished jobs....
make: Leaving directory `.../project_root/androidtest/proj.android'
Error running command, return code: 2.
````

**Comment by Dimon4eg** [comment]
From which folder do you try build?
You should build from root of your project

**Comment by Rubonnek** [comment]
I tried it from the root of the project, and also from inside `proj.android` and I got the same error.

**Comment by minggo** [comment]
I don't think it is an issue, so close it.

**Pull request closed without merging**
