### PR TITLE
fix scrollview render error

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by liamcindy** [comment]
[ci rebuild]

**Comment by liamcindy** [comment]
[ci rebuild]

**Comment by liamcindy** [comment]
@zilongshanren @xiaofeng11 Please review this pr, thanks.

**Comment by zilongshanren** [comment]
@liamcindy Why change it like this?
What's the problem here? you'd better provide a test case for this PR.

**Comment by liamcindy** [comment]
@zilongshanren The test has been added.

**Pull request merged**
