### PR TITLE
Fix win32

### PR DESCRIPTION
**Pull request by dualface**
增加两个热键：
CTRL+X 退出
CTRL+R 重新启动

增加控制台窗口输出，方便脱离 Visual Studio 环境进行调试。

例如美工调试素材，不需要为美工安装 VS，只需要把执行文件、DLL 和资源文件拷贝到美工机器上。美工直接修改资源文件后重启游戏就能看到效果。

对于策划和脚本开发人员，这个修改也可以显著提高工作效率。

### CODE REVIEW

**Comment by minggo** [comment]
Please use English.

**Comment by dualface** [comment]
sorry :)
1. Add two hotkeys for Win32 application:

CTRL+X = Quit
CTRL+R = Restart
1. Add console window for Win32 application, all debug message output to this console window.

---

These two changes can significantly improve the work efficiency.

For the artist:
Without Visual Studio environment, you can always test the effect of the picture displayed in the application.

For game designers:
Can immediately test the modified script file.

**Comment by dumganhar** [comment]
I think we should disable the macro USE_WIN32_CONSOLE by default.

**Comment by minggo** [comment]
And it is better to write a document describes how to use it.
Then other developers will notice the feature and use it.

**Comment by dualface** [comment]
change win32 main.cpp, debug console set default disabled.

how to use: http://cn.cocos2d-x.org/bbs/forum.php?mod=viewthread&tid=434 (CHINESE ONLY)

**Pull request merged**
