### PR TITLE
add stopActionByName()

### PR DESCRIPTION
**Pull request by sxd1140**
cocos2d/cocos2d-js#1190

### CODE REVIEW

**Comment by pandamicro** [comment]
@minggo Can we merge such feature request ? Or is there anything else need to be done before merge it ? An discussion ?

**Comment by minggo** [comment]
I think i should ask studio team to evaluate it.
@chengstory 
Could you review it?

**Comment by chengstory** [comment]
I think it can be merged. Thanks @sxd1140 very much.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@minggo CI build passed

**Pull request merged**
