### PR TITLE
Fixed #12252 : Support new portrait projects from templates.

### LINKED ISSUE #12252: [cocos new] fail to create a portrait project
steps:
1.) cocos new -p com.test.test -l cpp -d ~/Desktop/ --portrait  test
2.) logs from cocos console:
"> Copying cocos2d-x files...

> Rename project name from 'HelloCpp' to 'test'
> Replace the project name from 'HelloCpp' to 'test'
> Replace the project package name from 'org.cocos2dx.hellocpp' to 'com.test.test'
> Replace the mac bundle id from 'org.cocos2dx.hellocpp' to 'com.test.test'
> Replace the ios bundle id from 'org.cocos2dx.hellocpp' to 'com.test.test'
> WARNING: Can't find step change_orientation.
> "

### PR DESCRIPTION
**Pull request by natural-law**
Usage: Add parameter `--portrait` when using `cocos new` command.

### CODE REVIEW

**Comment by natural-law** [comment]
Fixed #12252

**Comment by pandamicro** [comment]
@qiululu Please test it.
@natural-law Can you tell @qiululu how to test the result?

**Comment by qiululu** [comment]
I've test all the projects, at the platform of Win32(Lua, cpp, js project), win8.1-universal(cpp),  winPhone, MacOX(lua, cpp, js), IOS(lua, cpp, js), android(lua, cpp, js),  performs right and work as Vertical screen demos. pictures below have shown the effect of all the projects
cc1
cc2

**Comment by pandamicro** [comment]
Thanks @natural-law @qiululu

**Pull request merged**
