### PR TITLE
updates cocos console

### PR DESCRIPTION
**Pull request by ricardoquesada**
fix github issue #15890 and partially fixes github issue #15889

### CODE REVIEW

**Comment by stammen** [comment]
@ricardoquesada This PR breaks cocos new command for Windows 8.1 and 10

project_new.py",> line 140, in parse_args
    if args.list_templates:
AttributeError: 'Namespace' object has no attribute 'list_templates'

**Comment by ricardoquesada** [comment]
sure. I'll fix it tomorrow Monday. Thanks!

**Comment by codexico** [comment]
Same error, `cocos new` on linux:

> Traceback (most recent call last):
>   File "/home/fk/opt/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 992, in <module>
>     run_plugin(command, argv, plugins)
>   File "/home/fk/opt/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 916, in run_plugin
>     plugin.run(argv, dependencies_objects)
>   File "/home/fk/opt/cocos2d-x/tools/cocos2d-console/plugins/plugin_new/project_new.py", line 258, in run
>     self.parse_args(argv)
>   File "/home/fk/opt/cocos2d-x/tools/cocos2d-console/plugins/plugin_new/project_new.py", line 140, in parse_args
>     if args.list_templates:
> AttributeError: 'Namespace' object has no attribute 'list_templates'

**Comment by ricardoquesada** [comment]
fixed. thanks.

**Comment by ricardoquesada** [comment]
oops... refixing it.

**Pull request merged**
