### PR TITLE
Refactor scroll view's inertia scroll

### PR DESCRIPTION
**Pull request by neokim**
Scroll view used to have two different logics for scroll by inertia and auto scroll. The logics are merged into one. Inertia scroll now uses auto scroll feature.

This is base change to implement scrolling to specific item and magnetic scroll in list view.

### CODE REVIEW

**Comment by WenhaiLin** [comment]
:+1:

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
So guys, who is reviewing this PR and can we merge it ?

**Comment by zilongshanren** [comment]
@pandamicro  I will review this PR later.

**Comment by zilongshanren** [comment]
@neokim  :+1:  I have tested your code and it works great.  Keep up with your improvement over the ScrollView and ListView.

**Comment by neokim** [comment]
@zilongshanren Thanks for reviewing.

I'm adding more features to ListView, and refactoring, too.
Because ScrollView is the very base component, this pull request was necessary for those changes.

Also planning to change PageView to derive from ListView. I saw an issue about vertical PageView. It will be resolved if it shares ListView's implementation. And ScrollView, ListView and PageView will have same user experience about scrolling. Actually PageView is one type of ListView which has magnetic scroll option as center.

**Comment by zilongshanren** [comment]
@neokim 
What features would you plan to add for ListView?  Because currently I'm also trying to add cell reuse to ListView and PageView.

I like the idea which PageView could share some implementations of ListView and ScrollView.
But we should do it carefully, we can't break back compatibility in v3.x versions.

**Comment by neokim** [comment]
@zilongshanren I agree with that we have to take care for back compatibility. I'll try to keep every existing API of PageView.

I'm adding magnetic scroll feature to ListView now. I think that it has no dependency with your reusable cell feature.

**Comment by zilongshanren** [comment]
@neokim  Great :+1:

**Pull request merged**
