### PR TITLE
fix cc.pDistanceSQ

### PR DESCRIPTION
**Pull request by samael65535**

### CODE REVIEW

**Comment by samuele3hu** [comment]
This API refers to the Point::getLengthSq,the "SQ" suffix means square not sqrt.

**Comment by samael65535** [comment]
oringin source:

function cc.pLengthSQ(pt)
    return cc.pDot(pt)
end

It has only one argument. How can I use it?

**Comment by samuele3hu** [comment]
Yeah,It is a bug,We should do like this:
function cc.pLengthSQ(pt)
    return cc.pDot(pt,pt)
end

Is it right?

**Comment by samuele3hu** [comment]
pt is a table like this pt = { x = valueX, y = valueY}

**Comment by samael65535** [comment]
Yeah

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/4985. Thanks.

**Pull request closed without merging**
