### PR TITLE
Adds Spine binary-file format support

### PR DESCRIPTION
**Pull request by ricardoquesada**
fixes issue #10438

### CODE REVIEW

**Comment by minggo** [comment]
`SkeletonBinary.cpp` is missing, seems it is `SkeletonBinary.c`.

**Comment by ricardoquesada** [comment]
@minggo I forgot to update the bindings. thanks.

_update_: ah.. yes, you were right about the .cpp thing

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
