### PR TITLE
New AudioEngine: Fixed play may fail with a large audio file on WIN32.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by andyque** [comment]
[ci rebuild]

**Comment by Dhilan007** [comment]
[ci rebuild]

**Comment by minggo** [comment]
- can not just resize capacity to make issue more hard to happen, should determine if a file is read out
- should modify iOS/Mac too

**Comment by WenhaiLin** [comment]
Hi @mixogames, i submit new commit for fix audio issue10482,please try again.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by mixogames** [comment]
I tried again and it's got better :) 
Now it could play approx 15sec long OGG (pcm was 16bit/44khz) but with larger files it failed again - in this case just played a half second or less part at begining of the song.
 I tried to figure out the file limit and i found that it plays OGG file if its WAV source (44khz/16bit/stereo) size is 2610496 bytes (or less) but it always fails if its WAV source 2652624 bytes (or larger) - the limit is somewhere between these sizes. I hope it helps. 
I can send you ogg if you need them but i tried different files and the result were same.
FYI a used cocos2dx cpp-tests for testing your fixes, nothing were modified.

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by walzer** [comment]
@WenhaiLin, please resend your pull request to v3 branch. I scheduled this issue to v3.7

**Comment by Sheado** [comment]
hey All, 

I just saw this issue (I recently posted on https://github.com/cocos2d/cocos2d-x/issues/10482). This bug isn't fixed for large OGG files (>5mb).

I dug around the code a bit and was able to isolate and partially fix the problem:

AudioEngine-win32.cpp - comment out the contents of AudioEngineImple::update( float dt ).
AudioCache.h - increase the buffer time step:
`#define QUEUEBUFFER_TIME_STEP 0.5f
`
Then in AudioPlayer.cpp:

```
 bool AudioPlayer::play2d(AudioCache* cache)
 {
+       log("AudioPlayer::play2d %d", cache->_alBufferReady);
     if (!cache->_alBufferReady) {
         return false;
     }
@@ -137,6 +138,7 @@ bool AudioPlayer::play2d(AudioCache* cache)

 void AudioPlayer::rotateBufferThread(int offsetFrame)
 {
+       log("AudioPlayer::rotateBufferThread");
     ALint sourceState;
     ALint bufferProcessed = 0;
     mpg123_handle* mpg123handle = nullptr;
@@ -194,7 +196,7 @@ void AudioPlayer::rotateBufferThread(int offsetFrame)

     while (!_exitThread) {
         alGetSourcei(_alSource, AL_SOURCE_STATE, &sourceState);
-        if (sourceState == AL_PLAYING) {
+        //if (sourceState == AL_PLAYING) {
             _ready = true;

             alGetSourcei(_alSource, AL_BUFFERS_PROCESSED, &bufferProcessed);
@@ -248,6 +250,7 @@ void AudioPlayer::rotateBufferThread(int offsetFrame)
                 else if(audioFileFormat ==  AudioCache::FileFormat::OGG)
                 {
                     int current_section;
+                                       log("\tread part");
                     readRet = ov_read(vorbisFile,tmpBuffer,_audioCache->_queBufferBytes,0,2,1,&current_section);
                     if (readRet <= 0) {
                         if (_loop) {
@@ -265,7 +268,10 @@ void AudioPlayer::rotateBufferThread(int offsetFrame)
                 alBufferData(bid, _audioCache->_alBufferFormat, tmpBuffer, readRet, _audioCache->_sampleRate);
                 alSourceQueueBuffers(_alSource, 1, &bid);
             }
-        }
+  //      }
+               //else
+                       if (sourceState != AL_PLAYING)
+                               alSourcePlay(_alSource);

         std::unique_lock<std::mutex> lk(_sleepMutex);
         if (_exitThread)
@@ -273,7 +279,7 @@ void AudioPlayer::rotateBufferThread(int offsetFrame)
             break;
         }

-        _sleepCondition.wait_for(lk,std::chrono::milliseconds(35));
+        _sleepCondition.wait_for(lk,std::chrono::milliseconds(1));
     }
 ExitBufferThread:
     switch (audioFileFormat)

```

These changes allow large OGG files to play all the way through, but it's not perfect and there are many pops and pauses (probably due to wrong buffer sizes and timing). Hopefully these notes can help somebody fix this properly. As for me, I'm trying to decide on whether I should keep trying to fix this or start over with SDL_Mixer which I believe handles cross-platform decoding out of the box.

**Pull request closed without merging**
