### PR TITLE
Adding popSceneBack() function to Director

### PR DESCRIPTION
**Pull request by mdkcore0**
This function deletes the running scene and returns the actual scene
back to the caller. This way, we can simply use it to perform a
transition animation, like this:

Director::sharedDirector()->replaceScene(
        TransitionSlideInL::create(0.5,
        Director::sharedDirector()->popSceneBack()));

### CODE REVIEW

**Comment by ttencate** [comment]
Why not have popScene() return a value, instead of adding another entry point to the API? See also #1307.

**Comment by mdkcore0** [comment]
@ttencate it's a good idea; this PR is open to discuss ;) I can easily change the patch to return the value if anyone more think this is nice

thanks for commenting

**Comment by sniperbat** [comment]
"return the value" +1
But be careful about the scene's init or finish work, don't miss something :)

**Comment by mdkcore0** [comment]
Shame on me; I complete forget about this PR. Will rebase and make the mentioned changes on this.

**Comment by cocosQA** [comment]
Dear rodrigogolive:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6486
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
