### PR TITLE
[tolua]Lua bindings-generator support android-ndk-r9d android-ndk-r10d android-ndk-r10e (win32 support android-ndk-r9d android-ndk-r10d android-ndk-r10e android-ndk-r11c android-ndk-r13b android-ndk-r14b)

### PR DESCRIPTION
**Pull request by xbpiao**
[tolua]Lua bindings-generator support android-ndk-r9d android-ndk-r10d android-ndk-r10e
(win32 support android-ndk-r9d android-ndk-r10d android-ndk-r10e android-ndk-r11c android-ndk-r13b android-ndk-r14b)

macOS下android-ndk-r13b android-ndk-r14b生成时cocos2dx_physics3d.ini会出错其它正确，目前只能测试到这些，其它NDK版本未测试，但相比原来的版本兼容性已经好很多。

### CODE REVIEW

**Comment by xbpiao** [comment]
因为我fork的v3版本比较旧，所以把主线的合并之后再修改的多了两个Merge pull request看了下文件变化都是零，不知道是否有影响。

**Comment by minggo** [comment]
thanks.

@dumganhar @pandamicro could you please take a look?

**Comment by minggo** [comment]
looks good to me, thanks

**Review by dumganhar — APPROVED** [review]

**Review by pandamicro — APPROVED** [review]

**Comment by minggo** [comment]
@xbpiao could you please modify JSB too? Thanks.

**Comment by xbpiao** [comment]
@minggo I use lua, but I can try!

**Comment by minggo** [comment]
thanks

**Comment by xbpiao** [comment]
[tojs]Javascript bindings-generator support android-ndk-r9d android-ndk-r10d android-ndk-r10e (win32 support android-ndk-r9d android-ndk-r10d android-ndk-r10e android-ndk-r11c android-ndk-r13b android-ndk-r14b)

tojs and tolua  the same now.

**Comment by minggo** [comment]
thanks, i will merge it after it passes jenkins.

**Pull request merged**
