### PR TITLE
WP8 fixes for recent commits to V3

### PR DESCRIPTION
**Pull request by stammen**
This pull request fixes the WP8 build broken by recent commits to the V3 branch.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @stammen , thanks for fixing this issue. 
But I have a comment about this file : `cocos/2d/platform/wp8/shaders/precompiledshaders.h`
It's too big, its raw size is : 3,002,937 bytes,  133K after zip packed.
As you know, we compressed our repo recently, it's the last opportunity to rewrite the whole history to remove large files. We don't want large files exist in our repo.
So could we use non -precompiled shader in our engine.
If developer wants to precompiled shader, we need to write a documentation for how to compile it for wp8. 

Ideas?

**Comment by stammen** [comment]
Windows Phone 8.0 cannot compile shaders at run-time. That is why the shaders must be precompiled in order to use cocos2d-x on WP8. It is not reasonable to have developer compile the shaders on their own as it is a complicated process.

I will make a nuget package for the WP8 precompiled shaders. Visual Studio will automatically add the precompiled shaders when the developer tries to build cocos2d-x for WP8. I am moving all of the WP8 dependencies to nuget on both V2 and V3 branches.

**Comment by dumganhar** [comment]
>  I am moving all of the WP8 dependencies to nuget on both V2 and V3 branches.

Seems great,  i'm not familiar with `nuget`, did you mean that dependencies will be automatically downloaded in Visual Studio by `nuget`? 

Is its user experience good ? When will it be finished?

**Comment by stammen** [comment]
The user experience is very good. I have most of the V2 dependencies done and it is very fast to download and update. The dependencies are automatically downloaded by nuget which is part of Visual Studio 2012 Express and higher. So far I have added png, jpeg, tiff, freetype, zlib, libwebsockets, curl and I am finishing Angle today. Both V2 and V3 will use this. 

Also, the visual studio project files for WP8 are a lot cleaner as nuget adds all of the dependency include paths, libs and dlls automatically.

**Comment by stammen** [comment]
Once nuget is working for WP8, you will be able to remove all of the WP8 dependencies from download-deps.py which will help to reduce its size.

**Comment by dumganhar** [comment]
Great work. @stammen 
So do you mind to rebase this PR to remove the change of  the precompiled shader?
After you finish the task, the large precompiled shader will be automatically downloaded by `nuget`.

**Comment by stammen** [comment]
Let's just close this pull request. I will make a new pull request with all of the fixes. WP8 will still be broken until I add the precompiled shaders.

**Comment by dumganhar** [comment]
OK. Thanks :)

**Comment by dumganhar** [comment]
closed.

**Comment by ricardoquesada** [comment]
@stammen 
I fixed the compilation issues here:
https://github.com/cocos2d/cocos2d-x/pull/6782

I also fixed a bit the files in `platform/wp8` and `platform/winrt`
Of course, in order to run properly on wp8, we still need the new shaders.

BTW, how can I test cocos2d-x on winrt ?

**Comment by stammen** [comment]
We have not contributed a WinRT solution for V3 yet.

**Comment by stammen** [comment]
I am working on a shader compilation tool that will run at compile time which will precompile all of the shaders for WP8. It should be ready early next week.

**Comment by ricardoquesada** [comment]
ok. thanks.
BTW, I disabled pre-compiled headers for the WP8 build.
It wasn't compiling for me with it enabled.... not sure why. But, feel free to re-enable it. Thanks!

**Comment by stammen** [comment]
What errors were you seeing with pre-compiled headers? Did you clean your solution?

**Comment by ricardoquesada** [comment]
@stammen 

This is the error (after cleaning, and re-building the project):
`Error  5   error C1083: Cannot open precompiled header file: 'ARM\Release\libcocos2d.pch': No such file or directory   C:\Users\Ricardo\progs\cocos2d-x\external\ConvertUTF\ConvertUTFWrapper.cpp  1`

**Comment by ricardoquesada** [comment]
BTW,  I merged @stammen precompiled headers.
Although the file is big, the diff between the new version and the old version was small.
And since git only stores the "diffes", we didn't increase the git repo by much. 
Also, the it is a text file, so, compression rates are pretty high, so there is no problem in merging big text files when the diff is small.

**Comment by dumganhar** [comment]
But github said the diff is very big.

```
6,604  cocos/2d/platform/wp8/shaders/precompiledshaders.h  Open View
3302 additions, 3302 deletions not shown
```

**Comment by ricardoquesada** [comment]
you are right James. The diff was pretty big.
I thought it was smaller because I did the diff on my machine. Perhaps LR/LF were converted when I pushed my changes.

Anyway, this pull request only increased the repo size in at most 22k. So, we are safe with text diffs.
I just did the quick test, and compressing precompiledshader.h only takes 22k (from 240k).

**Comment by dumganhar** [comment]
That's ok if this change only takes about 22k. :)
BTW, cocos2d-console repo has lost weight successfully.

**Comment by ricardoquesada** [comment]
great. well done James!

**Comment by dumganhar** [comment]
@ricardoquesada , that was done by @natural-law, thank him. :)

**Pull request closed without merging**
