### PR TITLE
Navigation2, remove unused code

### PR DESCRIPTION
**Pull request by super626**

### CODE REVIEW

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by dabingnn** [comment]
This pull request only contains one line adding and two line deletion, however, there are 4 commits, could you please squash them to one commit by using `git merge branch_to_merge --squash`?

**Comment by zilongshanren** [comment]
@super626  I agreed with @dabingnn

**Comment by super626** [comment]
@andyque @pandamicro @dabingnn 
Done.

https://github.com/cocos2d/cocos2d-x/pull/12359

**Pull request closed without merging**
