### PR TITLE
#11020: Cmake 3.2.1 deprecation, no more auto link X11 with OpenGL

### PR DESCRIPTION
**Pull request by samuelion**
@andyque @samuele3hu 
Regarding the cmake 3.2.1 issue I got
To check, comment, ignore, whatever !
No change on Win, change working for me on Linux, should be changed on MACOSX, I try but would be nice to be tested or ignored !

### CODE REVIEW

**Comment by worblehat** [comment]
Works for me on Linux, but shouldn't `cocos_find_package(X11 X11 REQUIRED)` be placed inside the `if(LINUX)`-branch in CMakeLists.txt?

**Comment by samuelion** [comment]
Yes indeed, first I put the findX11 for all platform, second commit was supposed to remove it on Windows, but looks like I have done only half the work ! Will update tomorrow.
Dont know for Mac, but as an Unix I believed it might be needed also ?

**Comment by worblehat** [comment]
I don't know if X11 is used on Mac Os X. If in doubt I would not include it...

**Comment by minggo** [comment]
please send a new PR since there is conflict

**Pull request closed without merging**
