### PR TITLE
layout increase the scale support

### PR DESCRIPTION
**Pull request by litefeel**

### CODE REVIEW

**Comment by litefeel** [comment]
[ci rebuild]

**Comment by litefeel** [comment]
@minggo please review this.

**Comment by minggo** [comment]
Thanks @lite3 .

@chengstory 
Could you please review it?

**Comment by litefeel** [comment]
@minggo please review it.

**Comment by minggo** [comment]
@lite3 
Sorry, we are busing releasing v3.3rc0 these days.

**Comment by litefeel** [comment]
@minggo o.

**Comment by litefeel** [comment]
@minggo  please review this patch.

**Comment by zilongshanren** [comment]
Hi, @lite3 
I'm reviewing the PR. And I will give you feedback later. Be patient :)
I think you should give us more detailed information about your patch. 
What problem do your solved?
Could you give us a little sample code to reproduce the issue?
Thanks.

**Comment by litefeel** [comment]
@andyque
in ListView, if scale the cell, other cell position can not adjust to correct position.

**Comment by litefeel** [comment]
@minggo please review it.

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.

**Pull request closed without merging**
