### PR TITLE
add manual bindings for EventDispatcher::addCustomEventListener.

### PR DESCRIPTION
**Pull request by xpol**

### CODE REVIEW

**Comment by pandamicro** [comment]
Hi, @xpol Thank you ! Can you provide a test case for this ?

**Comment by xpol** [comment]
@pandamicro Sorry It was too complex for me to understand add new test to the `tests/lua-tests/src/NewEventDispatcherTest/NewEventDispatcherTest.lua`.

The test itself is just:

``` Lua
dispatcher:addCustomEventListener('director_after_draw' ,function()
    print('director_after_draw')
end)
```

**Comment by pandamicro** [comment]
OK, we will give it a try

**Comment by xpol** [comment]
@pandamicro Thank you very much!

**Comment by zilongshanren** [comment]
@dualface 
Could you take a look at this issue?
Thanks.

**Comment by xpol** [comment]
+1

**Comment by minggo** [comment]
@xpol Would you mind send a new pull request? This one has conflict issue.

**Comment by xpol** [comment]
@minggo 
Sorry I'm not using cocos2d-x any more. And have have deleted my branch long time ago.

**Comment by minggo** [comment]
@xpol got it, thanks.

**Pull request closed without merging**
