### PR TITLE
Fix linux compilation of CCTexturePVR.cpp

### PR DESCRIPTION
**Pull request by sbc100**
On linux (and possibly other platforms)
GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG is simply not defined since we don't
include GLES/gl2ext.h.

### CODE REVIEW

**Comment by billy1380** [comment]
I think the constant is an opengles thing. Getting the same issue on mac build.

**Comment by sbc100** [comment]
Yes, this fix should work on all platforms that don't have this (e.g. all desktop GL platforms).

**Comment by dumganhar** [comment]
@sbc100 ,thank you.
But did you notice that these macros are used in `PVRTableFormats` array?
And `PVRTableFormats` array is used in `v2_pixel_formathash` and `v3_pixel_formathash`.
I think these two arrays, i mean `v2_pixel_formathash` and `v3_pixel_formathash` also need to check whether `GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG` is defined.
Otherwise, it may cause overflow.

**Comment by minggo** [comment]
Yep, i think @dumganhar is right.
This macro should be applied to v3_pixel_formathash and v2_pixel_formathash too.

**Comment by sbc100** [comment]
Done.

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
