### PR TITLE
Resizable window

### PR DESCRIPTION
**Pull request by elnormous**
Add "resizable" flag to desktop GLView to allow creating a resizable window

### CODE REVIEW

**Comment by zilongshanren** [comment]
Thanks @elvman 
Should we upgrade the GLFW?

**Comment by elnormous** [comment]
No, it works with GLFW 3.1.2

**Comment by zilongshanren** [comment]
@elvman 
thanks, it will be merged in the next release cycle.

**Comment by milos1290** [comment]
Please include dispatching custom event with the new width and height.

**Comment by zilongshanren** [comment]
@milos1290 
maybe you could open a new ticket about the "dispatching custom event problem".

**Pull request merged**
