### PR TITLE
Add V3 flatbuffers

### PR DESCRIPTION
**Pull request by pipu**

### CODE REVIEW

**Comment by stammen** [comment]
@pipu Thanks for adding the flatbuffer files to the Windows 8.1 Universal App. However, the files were added to the wrong projects. Please add the files to the libcocos2d_8_1.Shared project only.

**Comment by pipu** [comment]
@stammen 
Our project does not have libcocos2d_8.1_Shared
Please tell us how to config libcocos2d_8.1_Shared
libcocos2d_8_1 shared

**Comment by stammen** [comment]
What version of Visual Studio are you using?

**Comment by stammen** [comment]
I am cloning your pull request and will make the changes needed. I will then make a pull request back to your cocos2d-x repo.

**Comment by pipu** [comment]
Thanks very much

Please helps us to add the following files into libcocos2d_8_1.Shared project , refer to the picture below

directory widgetreader

**Comment by minggo** [comment]
CMake Error at CMakeLists.txt:284 (add_subdirectory):

@pipu 
It has error on linux.

**Comment by pipu** [comment]
directory json

**Comment by pipu** [comment]
@minggo 
ok
I just commit that Modify CMake Error at CMakeLists.txt:284 (add_subdirectory).

**Comment by minggo** [comment]
Ok.

**Comment by minggo** [comment]
@pipu 
I think think should not modify windows8.1 project because @stammen has said that it will do it and send you a pull request.
Your modification will cause conflict to @stammen .

**Comment by minggo** [comment]
@stammen 
I think you need to work based on @pipu 's latest codes.
Hope it will not bring you too much trouble.

And can i know when you can send a pull request to @pipu ?
Thanks.

**Comment by stammen** [comment]
I made a pull request to @pipu's cocos2d-x repo that fixes the WP8 and Universal App projects. 

https://github.com/pipu/cocos2d-x/pulls

I also made a pull request to fix flatbuffers compiling for WP8 and the Universal App

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/61

**Comment by pipu** [comment]
@stammen 

The web page prompt me "We can’t automatically merge this pull request."
Can you help me how do I solve? 
Thanks

**Comment by stammen** [comment]
@pipu @minggo I updated the pull request with the wp8 and universal app fixes

https://github.com/pipu/cocos2d-x/pull/16

**Comment by minggo** [comment]
Thanks @stammen .

**Comment by pipu** [comment]
@minggo 

 I have merged Stammens's pull request.

**Comment by stammen** [comment]
When you pull this request, please update download-deps.py version to avoid breaking build.

**Comment by minggo** [comment]
Thanks.
In fact, 3rd party lib was updated.

**Comment by minggo** [comment]
@pipu 
Please fix compiling error on linux.

**Comment by chengstory** [comment]
@minggo where  to see compiling error?

**Comment by minggo** [comment]
- click `Details`, then you will see which platform failed.
- click failed platform, and select `console output`
- then you will see error message

**Comment by chengstory** [comment]
@minggo  I have seen compiling error that ButtonTestLayer.cpp in CocosBuilderTest,  we didn't change anything about Cocos Builder Test. Please help us fix it, Thanks very much.

**Comment by minggo** [comment]
`/data/jenkins/workspace/cocos-2dx-pull-request-build/node/linux_centos/external/flatbuffers/idl_parser.cpp: In function ‘void flatbuffers::Error(const string&)’:
/data/jenkins/workspace/cocos-2dx-pull-request-build/node/linux_centos/external/flatbuffers/idl_parser.cpp:40:9: error: exception handling disabled, use -fexceptions to enable
   throw msg;
         ^
/data/jenkins/workspace/cocos-2dx-pull-request-build/node/linux_centos/external/flatbuffers/idl_parser.cpp: In member function ‘bool flatbuffers::Parser::Parse(const char*, const char**, const char*)’:
/data/jenkins/workspace/cocos-2dx-pull-request-build/node/linux_centos/external/flatbuffers/idl_parser.cpp:1125:29: error: ‘msg’ was not declared in this scope`

It is caused by flatbuffer.

**Pull request closed without merging**
