### PR TITLE
use release libs and remove debug libs

### PR DESCRIPTION
**Pull request by squirrelChen**
http://www.cocos2d-x.org/issues/4038

### CODE REVIEW

**Comment by squirrelChen** [comment]
@minggo @dumganhar @stammen I reduce the size from 137.4M to 84.8M.

**Comment by dumganhar** [comment]
@koowolf 
Did you build the release libraries by using the same version of source codes as before?

**Comment by squirrelChen** [comment]
The release libs existed, needn't to compile again. Used release libs in debug and release mode.

**Comment by stammen** [comment]
Did you check if all of the projects build for Debug/Release for Win32/ARM? WinRT and Phone?

**Comment by squirrelChen** [comment]
Yes, It all tests OK.

**Comment by stammen** [comment]
Excellent!

**Pull request closed without merging**
