### PR TITLE
Update 3rd party lib references

### PR DESCRIPTION
**Pull request by rh101**
Update to v3-deps-159

### CODE REVIEW

**Comment by minggo** [comment]
Could you please fix the compiling error?

**Comment by rh101** [comment]
I updated it for both v3 and v4. Sorry about that, I can't figure out why it didn't give me an error when compiling it for v3, otherwise I would have caught the issue.

**Comment by rh101** [comment]
Will you create new deps zip with the v3-deps-160 tag, or just update the current v3-deps-159?

**Comment by minggo** [comment]
I just reuse v3-dpes-159.

**Pull request merged**
