### PR TITLE
fix particle3d crash with error file

### PR DESCRIPTION
**Pull request by liamcindy**
@pandamicro Please review this PR, thanks.

### CODE REVIEW

**Comment by pandamicro** [comment]
This PR is good to be merged
@xiaofeng11 @liamcindy can you check whether the JSON parser have the same problem ?

**Comment by liamcindy** [comment]
@pandamicro Please review this PR again, there is some code changed, thanks

**Comment by xiaofeng11** [comment]
@pandamicro 
Synchronized js modify at https://github.com/cocos2d/cocos2d-x/pull/13250

**Comment by pandamicro** [comment]
OK, thanks guys

**Pull request merged**
