### PR TITLE
issue #4689:Game controller support

### PR DESCRIPTION
**Pull request by WenhaiLin**
API design of Game controller:https://docs.google.com/a/cocos2d-x.org/document/d/1Jf_j9mvYqIXZbXLZyvPT8ZkuAdUwm2U0WB_GZPlhTt4/edit

### CODE REVIEW

**Comment by martell** [comment]
@Dhilan007 can I see the doc with the spec please.
I'm interested in the structure this will take.

**Comment by minggo** [comment]
@martell 
You can send permission requirement for [this doc](https://docs.google.com/a/cocos2d-x.org/document/d/1Jf_j9mvYqIXZbXLZyvPT8ZkuAdUwm2U0WB_GZPlhTt4/edit). And we will write a document for it after release beta0.

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by martell** [comment]
Thankyou @minggo 
It looks good. :)

**Comment by minggo** [comment]
@martell 
Thanks for you feedback.

**Pull request merged**
