### PR TITLE
adding setPositionNormalized

### PR DESCRIPTION
**Pull request by mannewalis**
Added basic implementation of setPositionNormalized.
I can add other overloads that take other params if you want, just let me know.

### CODE REVIEW

**Comment by minggo** [comment]
@ricardoquesada 
I remember you had added similar function, but didn't merge it.
Any reason?

**Comment by ricardoquesada** [comment]
don't merge this PR yet. I'll review it next week.

**Comment by mannewalis** [comment]
I implemented the minimum code to get this working. Let me know if you want
me to add other overloads like setPosition. I think individual X,Y
accessors might be required from script binding, but not sure.

**Comment by minggo** [comment]
@ricardoquesada 
How about this PR?

**Comment by ricardoquesada** [comment]
I haven't reviewed it yet. Please don't merge it.
I'm owning this PR, I'll merge it after reviewing.

**Comment by minggo** [comment]
Got it.
Thanks.

**Comment by ricardoquesada** [comment]
This PR was superseded by this one:
https://github.com/cocos2d/cocos2d-x/pull/6947

**Pull request closed without merging**
