### PR TITLE
tracking memory allocations, to assist memory-leak-detection

### PR DESCRIPTION
**Pull request by heliclei**

### CODE REVIEW

**Comment by heliclei** [comment]
[ci rebuild]

**Comment by gelldur** [comment]
Good thing :)

**Comment by heliclei** [comment]
[ci rebuild]

**Comment by heliclei** [comment]
thanks, This is the initial version, version 2 is coming soon:)

**Comment by cocosQA** [comment]
Dear heliclei:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6439
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
