### PR TITLE
Improving iOS EditBox Implementation

### PR DESCRIPTION
**Pull request by Mazyod**
I will be making a series of commits to improve the implementation of EditBox on iOS. I will focus on better code style and conventions that match Apple's ObjC convention, but will also see if I can optimize the implementation a bit, and resolve a few bugs:

https://github.com/cocos2d/cocos2d-x/issues/10777
https://github.com/cocos2d/cocos2d-x/issues/11732
https://github.com/cocos2d/cocos2d-x/issues/12519

@zilongshanren This is as we discussed. Please let me know of any updates from your side

### CODE REVIEW

**Comment by pandamicro** [comment]
Awesome! Recently we received a lot of improvements for UI, which is just in our roadmap for v3.8.
You guys rock !

**Comment by zilongshanren** [comment]
@Mazyod  Thanks, when your PR is ready, please ping me. 
Do you want to put all the fixes in this PR, or do you want to send several PRs?

**Comment by Mazyod** [comment]
@zhaijialong I was thinking the same way, several PRs make more sense. I will make a few more changes today, and hopefully it will be ready

**Comment by Mazyod** [comment]
@zilongshanren I believe this is enough for one PR. I'll look at the Mac implementation, then revisit this after it's merged to see if I can fix some of the bugs listed above.

**Comment by zilongshanren** [comment]
@Mazyod Thanks.

**Comment by pandamicro** [comment]
Related cleanup PR: https://github.com/cocos2d/cocos2d-x/pull/12901

**Pull request merged**
