### PR TITLE
2026:72: Result of 'malloc' is incompatible with type 'unsigned char *'

### PR DESCRIPTION
**Pull request by iSevenDays**
2026:72: Result of 'malloc' is converted to a pointer of type 'unsigned char', which is incompatible with sizeof operand type 'unsigned char *'

### CODE REVIEW

**Comment by dumganhar** [comment]
OH, shit, who makes this mistake.
Thanks for this patch. :)

**Comment by dumganhar** [comment]
Thanks. Merged.

**Comment by dumganhar** [comment]
How did you find this error?

**Comment by iSevenDays** [comment]
You are welcome.
Xcode static analyzer. There are some possible errors still exists.

**Comment by dumganhar** [comment]
Got it. Thank you. I will also use that tool to check our codes. :)

**Comment by iSevenDays** [comment]
Please use it. There are some possible errors that are hard to reproduce so I fixed only obvious errors..

**Pull request merged**
