### PR TITLE
bug fix: gl_PointSize not support on windows 8.1.

### PR DESCRIPTION
**Pull request by songchengjiang**
see cpp-tests : bugs: Bug-CCDrawNode on windows 8.1

### CODE REVIEW

**Comment by stammen** [comment]
@songchengjiang The ANGLE team at Microsoft is fixing the gl_PointSprite bug for Windows Phone. It requires a new version of the ANGLE dll which I will add to cocos2d-x as soon as it is ready.

On what computer/gpu did you get the crash for Bug-CCDrawNode? The tests all pass for me.

**Comment by stammen** [comment]
Fixed in pull requests:

https://github.com/cocos2d/cocos2d-x/pull/14175
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/181

Angle had a bug with gl_PointSize with certain GPUs.

**Comment by pandamicro** [comment]
@songchengjiang please test after #14175 get merged

**Comment by songchengjiang** [comment]
OK Thanks

**Comment by songchengjiang** [comment]
Ok, thanks!

**Pull request closed without merging**
