### PR TITLE
fixed #14148: Got an error while pressing home button at launch, after resuming from background, SimpileAudioEngine::playEffect will be mute.

### LINKED ISSUE #14148: can not play audio if not playing any effect and come back from background on iOS
15:47:15.912 ERROR:    [0x19e5fa000] >aurioc> 807: failed: '!pla' (enable 2, outf< 2 ch,  44100 Hz, Float32, non-inter> inf< 2 ch,      0 Hz, Float32, non-inter>)

IOS9 xcode7 cocos2d-x3.8.1

进入游戏后如果没有播放任何音效就切出游戏会报以上错误, 之后无法再播放任何音效
如果在进入游戏后播放过一次音效, 之后切出游戏不会再报错误

### PR DESCRIPTION
**Pull request by dumganhar**
fixed #14148 
The error is: ERROR: [0x19e5fa000] >aurioc> 807: failed: '!pla' (enable 2, outf< 2 ch, 44100 Hz, Float32, non-inter> inf< 2 ch, 0 Hz, Float32, non-inter>)

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@minggo , CI passed.

**Comment by itxiaohui** [comment]
Cut out the game, in the WeChat sent a voice.after resuming from background, the game background music and sound effects become great. Hope to solve this problem.

**Comment by dumganhar** [comment]
@itxiaohui , sorry, I don't understand what you said.

**Comment by itxiaohui** [comment]
@dumganhar sorry,my english is poor,may I speak Chinese?（运行游戏后，按Home键切出游戏，在微信中，发语音，并且播放这个语音。之后回到游戏，游戏里的背景音乐和音效声音都变得很大，希望能确认一下这个问题，并解决）

**Comment by dumganhar** [comment]
Is the issue you said related to this Pull Request?
If not, please create another issue for that. Thanks.

**Comment by lintide** [comment]
你好，这个问题在 cocos2dx 3.13.1 iOS 10.2 依然存在。只要在播放背景音乐的时候切入后台，重新回到前台后，音效就无法播放。把 pauseBackgroundMusic 和 resumeBackgroundMusic 注释掉可以解决这个问题，但感觉这不是最好的办法。

```// This function will be called when the app is inactive. Note, when receiving a phone call it is invoked.
void AppDelegate::applicationDidEnterBackground()
{
    Director::getInstance()->stopAnimation();

    // SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
}

// this function will be called when the app is active again
void AppDelegate::applicationWillEnterForeground()
{
    Director::getInstance()->startAnimation();

    // SimpleAudioEngine::getInstance()->resumeBackgroundMusic();
}
```

**Comment by alkaid** [comment]
是的 我们用的3.13.1在ios上也依然存在该问题。我看见有人在2014年就提了这个bug。。。到现在还没解决么。  我又试了市面上近期的几款cocos做的游戏，同样有这个bug. 还请官方重视起来。    只要切到任意能调起键盘的app打几个字再切回游戏，必现。 @dumganhar @minggo

**Comment by minggo** [comment]
@dumganhar please check it again.

**Comment by dumganhar** [comment]
@lintide , @alkaid 
If you're using `AudioEngine`, it's correct to comment all `SimpleAudioEngine` stuffs in your AppDelegate.cpp. BTW, I submitted a PR (https://github.com/cocos2d/cocos2d-x/pull/17485) for avoiding this problem even if you call `SimpleAudioEngine->getInstance()->pause/resumeBackgroundMusic()`, but keep in mind that don't mix use of `AudioEngine` and `SimpleAudioEngine` in your game code.

**Comment by alkaid** [comment]
@dumganhar  解决了 谢谢大神 不过为毛自动生成的AppDelegate里切换前后台时的代码还是用的SimpleAudioEngine.  怨念...

**Comment by dumganhar** [comment]
@alkaid , I submitted a PR (https://github.com/cocos2d/cocos2d-x/pull/17555) for easily to switch audio engine in AppDelegate.cpp.

By default, it will not both AudioEngine and SimpleAudioEngine code will not be invoked in AppDelegate.cpp until you uncomment the `USE_AUDIO_ENGINE` or `USE_SIMPLE_AUDIO_ENGINE` in AppDelegate.cpp.

**Comment by alkaid** [comment]
@dumganhar 看到了 谢谢~

**Comment by fresair** [comment]
only use SimpleAudioEngine, the problem still exist. when application back from background, it still has chance can not play effect (no effect sound)

**Comment by dumganhar** [comment]
@fresair , what error did you get? Which platform and engine version are u using?

**Comment by fresair** [comment]
no error message in the console. 
1. press home button, then press game icon, the effect sound sometimes disappear after the application come back from background.
2. when error 1 happened,  then repeat process 1. the effect sound will become normal again after the application come back from background once again.
3.continue process 1 and 2, the effect sound will repeatedly disappear and show.

cocos2dx js 3.10, ios platform os10.3 and the files under cocos/audio tried both original and the  latest one from git

ps: when I remove pauseBackgroundMusic and resumeBackgroundMusic in applicationDidEnterBackground and applicationWillEnterForeground.  the effect sound can stay good after back from background.
// This function will be called when the app is inactive. When comes a phone call,it's be invoked too
void AppDelegate::applicationDidEnterBackground()
{
    auto director = Director::getInstance();
    director->stopAnimation();
    director->getEventDispatcher()->dispatchCustomEvent("game_on_hide");
    //SimpleAudioEngine::getInstance()->pauseBackgroundMusic();
    SimpleAudioEngine::getInstance()->pauseAllEffects();
}

// this function will be called when the app is active again
void AppDelegate::applicationWillEnterForeground()
{
    auto director = Director::getInstance();
    director->startAnimation();
    director->getEventDispatcher()->dispatchCustomEvent("game_on_show");
    //SimpleAudioEngine::getInstance()->resumeBackgroundMusic();
    SimpleAudioEngine::getInstance()->resumeAllEffects();
}

**Comment by lintide** [comment]
@dumganhar Thx!

**Comment by grrr2828** [comment]
I also have this problem.  SimpleAudioEngine.
cocos 3.4.  iOS 10.3.1

**Comment by xiejiajian** [comment]
@dumganhar Did you mean either AudioEngine or SimpleAudioEngine will invoke in AppDelegate.cpp ? I'm using 3.3, it's obviously much better when I comment the SimpleAudioEngine methods, but is it surely a perfect way ?

**Comment by rhzchina** [comment]
No one can solve the problem？

**Comment by dzCxy** [comment]
cocos2d-x-3.14.1 already fix it

**Comment by xiejiajian** [comment]
@dzCxy could you show me  the differences ?

**Pull request merged**
