### PR TITLE
b2World::DrawDebugData shows contacts in red

### PR DESCRIPTION
**Pull request by NatWeiss**
This pull request adds the ability for static bodies to be drawn in red when they have active contacts.

It was so helpful in my latest project I decided to share.

### CODE REVIEW

**Comment by minggo** [comment]
Thanks. Will you send a pull request to Box2D, or it may be hard for cocos2d-x to update Box2D.

**Comment by NatWeiss** [comment]
Ok, I will. The reason I submitted it here is that cocos2d-x includes it's own copy of Box2d (it's not a project reference / link).

**Comment by minggo** [comment]
It is a separate target on Xcode, has a separate project on VS, android, linux and so on.

**Comment by minggo** [comment]
And we decide to use prebuilt version in near future.

**Comment by NatWeiss** [comment]
I see. Well, I emailed Erin Catto with the updates. I couldn't see any other way to contribute to Box2d.

**Comment by minggo** [comment]
Thanks.

**Pull request closed without merging**
