### PR TITLE
Update CCNode.h

### PR DESCRIPTION
**Pull request by zii**
Exchange the two declarations of "addChild". Let lua-bind priority generate for "string name" method.

### CODE REVIEW

**Comment by minggo** [comment]
What's the benefit?

**Comment by samuele3hu** [comment]
In the `lua_cocos2dx_Node_addChild`,we will judge the type of params, so the overload function with name param would be called,if the third param is string type.I will check it soon.

**Comment by samuele3hu** [comment]
In the `lua_cocos2dx_Node_addChild`,we will judge the type of params, so the overload function with name param would be called,if the third param is string type.I will check it soon.

**Comment by zii** [comment]
@samuele3hu 
Thank you!

**Pull request closed without merging**
