### PR TITLE
Update MathUtilNeon64.inl

### PR DESCRIPTION
**Pull request by wangqm0513**
add arm64bit  neon support

### CODE REVIEW

**Comment by ricardoquesada** [comment]
thanks. unfortunately the build failed with this patch.

anyway, do you think it would be better to migrate to SIMD intrinsics ? thanks.

**Comment by ricardoquesada** [comment]
[rebuild]

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@ricardoquesada, we got a juno board, which is the first arm64 android device, from ARM.
I will check this improvement. 
 @wangqm0513 Thanks for your contribution. :)

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
thanks. looks good.
For future patches, perhaps might want to add support for NEON intrinsics. I think, if we do that, we will get ARM64 Neon for free (but I could be wrong).

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0205j/BABGHIFH.html

**Pull request merged**
