### PR TITLE
Cancel the onSubThreadEnded callback,because _ws may be deleted in the onClose callback.

### PR DESCRIPTION
**Pull request by HoGarfield**
Cancel the onSubThreadEnded callback,because _ws may be deleted in the onClose callback.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, @HoGarfield , Thanks for this patch.
It looks good, but could you tell me how to reproduce this issue?
I tried to use `TestCpp/ExtensionsTest/WebsocketTest` to reproduce it, but no crashes.

**Comment by HoGarfield** [comment]
You can see jsb_websocket.cpp

```
virtual void onClose(WebSocket* ws)
{
    js_proxy_t * p = jsb_get_native_proxy(ws);
    if (!p) return;

    JSB_AUTOCOMPARTMENT_WITH_GLOBAL_OBJCET

    JSContext* cx = ScriptingCore::getInstance()->getGlobalContext();
    JSObject* jsobj = JS_NewObject(cx, NULL, NULL, NULL);
    JS::RootedValue vp(cx);
    vp = c_string_to_jsval(cx, "close");
    JS_SetProperty(cx, jsobj, "type", vp);

    jsval args = OBJECT_TO_JSVAL(jsobj);
    ScriptingCore::getInstance()->executeFunctionWithOwner(OBJECT_TO_JSVAL(_JSDelegate), "onclose", 1, &args);

    js_proxy_t* jsproxy = jsb_get_js_proxy(p->obj);
    JS_RemoveObjectRoot(cx, &jsproxy->obj);
    jsb_remove_proxy(p, jsproxy);
    CC_SAFE_DELETE(ws);
}
```

It delete ws at last.

**Comment by dumganhar** [comment]
Issue http://cocos2d-x.org/issues/4103 was created.

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
