### PR TITLE
Match parent's camera mask when adding child.

### PR DESCRIPTION
**Pull request by stevetranby**
Let me know if you need test or anything else.

### CODE REVIEW

**Comment by minggo** [comment]
@stevetranby could you please connect to the issue? Thanks.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@stevetranby this patch broke the Scene3dTest. No nodes are shown on that test (cpp-tests -> Scene3dTest)

Any idea how improve this patch so that it works with the Scene3dtest ?

Perhaps this patch if fixing a real bug, but I'm worried that perhaps some games are relying on this bug... like Scene3dtest.

@minggo any idea what should we do?

Thanks.

**Comment by stevetranby** [comment]
@ricardoquesada yep, will look into it (see discussion)

**Pull request merged**
