### PR TITLE
Fix Button::setTitleLabel() memory leak

### PR DESCRIPTION
**Pull request by gestern**
It is quite an old bug (at least 2 years old) that existed since the beginning of the cocos2dx v3. I additionally refactored the code. #18677

### CODE REVIEW

**Comment by gestern** [comment]
@minggo Please review the bugfix too...

**Comment by gestern** [comment]
@drelaptop Could you please review this bugfix?

**Comment by drelaptop** [comment]
I am glad to do that @gestern

**Comment by drelaptop** [comment]
modify at `cocos/ui/UIButton.cpp`, looks good to me. but this PR mixed the changes at https://github.com/cocos2d/cocos2d-x/pull/19088 .

suggest to revert commit https://github.com/cocos2d/cocos2d-x/pull/19089/commits/38e5826f575aa91fdc73c217f1767a895c8a74c0 in this PR, I will merge it after un-related changes revert.

**Pull request closed without merging**
