### PR TITLE
 Disable iOS8 Quicktype Keyboard

### PR DESCRIPTION
**Pull request by Javanaise**
Disable iOS8 Quicktype Keyboard

### CODE REVIEW

**Comment by seivan** [comment]
This might also disable auto-correct, might not be that obvious. I like that my phone knows my name and other things.

**Comment by pandamicro** [comment]
I think for general purpose, we'd better keep the default behavior

**Comment by Javanaise** [comment]
Well find it quite confusing, people not on iOS8 or android (?) probably don't expect the textfield content to change from more than 1 letter, and it adds an extra space at the end...

**Comment by Javanaise** [comment]
@pandamicro @seivan  Something else: Quicktype Keyboard collides with the setMaxLength attribute; if the word you select with the Quicktype suggestion is bigger than your setMaxLength, it just get ignored... That looks very buggy.

**Pull request closed without merging**
