### PR TITLE
upgrade external to dep 35

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@stammen 
Your ANGLE patch for v3 can't be built successfully on out jenkins server:

Please refer to  http://104.237.146.7:8080/job/ccs-pr/276/node=windows-universal/parsed_console/
for more information.

**Comment by stammen** [comment]
@andyque Please enable version 35 of download-deps.py for v3 branch. It is still on version 34.

**Comment by zilongshanren** [comment]
@stammen 
I have changed the version to v35 in this PR. And I see it indeed downloaded the deps35. Could you help me to test the v3-deps-35 in your side?

**Comment by stammen** [comment]
@andyque I updated https://github.com/cocos2d/cocos2d-x/pull/10905 to the latest v3 to get the updated version 35 of download-deps.py

**Pull request closed without merging**
