### PR TITLE
2 bugs fix on v3

### PR DESCRIPTION
**Pull request by pShota**
-fix start app crash in android aff00ea
-fix keyboard "done" button bug in android

### CODE REVIEW

**Comment by minggo** [comment]
How to reproduce it.
Thanks.

**Comment by pShota** [comment]
my device: samsung galaxy s2, os 4.1.2
The first one just run the app on device and it will crash on startup, Bundle is null in ApplicationInfo.metaData

the 2nd one is when using TextFieldTTF, in my s2 it has a "done" button with it, when you press done, it will close the keyboard directly so that IMEDelegate::canDetachWithIME is ignore

**Comment by minggo** [comment]
Thanks.
- could you please fix compiling error?
- could you please fix indent?

**Comment by minggo** [comment]
I have tested on Glaxy S2 4.1.2.
No crash happened.

> the 2nd one is when using TextFieldTTF, in my s2 it has a "done" button with it, when you press done, it will close the keyboard directly so that IMEDelegate::canDetachWithIME is ignore

Is it a problem to close keyboard when press done?

**Comment by pShota** [comment]
-could you please fix compiling error?
-could you please fix indent?
ok~

-No crash happened.
thought so, but it keep crashing on my s2 until i add PackageManager.GET_ACTIVITIES flag, let me test more device

-Is it a problem to close keyboard when press done?
yes

**Pull request closed without merging**
