### PR TITLE
Optimize FPS control algorithm under Android.

### PR DESCRIPTION
**Pull request by reckhou**
The algorithm should work fine under Android now.

### CODE REVIEW

**Comment by minggo** [comment]
I tested it on Galaxy Note 2, but not effect.
I added `director->setAnimationInterval(1.0 / 20);` in AppDelegate.cpp.
But the fps is also about 60.

**Comment by reckhou** [comment]
I'm using a Galaxy S3 and it works fine. I test these code on v2, unless v3 is not using Cocos2dxRenderer.java anymore, it must be working.

**Comment by reckhou** [comment]
I've solved this issue, since Application::setAnimationInterval() is not implemented in v3 so it's not working.

**Comment by minggo** [comment]
Thanks.
I will try it tomorrow.

**Pull request merged**
