### PR TITLE
Develop migrate math lib

### PR DESCRIPTION
**Pull request by dabingnn**

### CODE REVIEW

**Comment by minggo** [comment]
I think it is better to rename `Vector2` to `vec2`. Because we already have `Vector`. But there are different meanings.

If we use `Vector2`, then it will be confused.

@ricardoquesada 
What's your opinion?

**Comment by dumganhar** [comment]
Since they're Class, I remember that we need to rename them to 
`Vec2`, `Mat4`

**Comment by ricardoquesada** [comment]
Hi, I already gave my opinion about this on this thread:
https://groups.google.com/d/msg/cocos2d-js-devel/BWDi7oHEtck/5PH04BnZhBwJ

Basically `Vec2`, `Vec3`, etc... are Ok.. but I prefer the longer names a bit better

**Comment by ricardoquesada** [comment]
@dabingnn It can't be merged now, could you update the PR?

thanks.

**Comment by ricardoquesada** [comment]
Apparently it fails for the Windows project. Not a major issues.

**Comment by minggo** [comment]
Oh.
I planned to merge it after resolving compiling error. Or it will block other pull request.
Sorry about not mentioned it here.

**Pull request merged**
