### PR TITLE
Change UI element(Menu and uiWidgets) hit tests from 2D space to 3D s…

### PR DESCRIPTION
**Pull request by IdVincentYang**
…pace.

And scene 3D test change to composite 2D/3D scene by moving UI and camera far away.

Fixed bug : wrong usage of isVisitableByVisitingCamera

Forum thread: http://discuss.cocos2d-x.org/t/found-bugs-when-composite-3d-2d-mixed-scene-by-moving-ui-and-the-camera-which-look-at-far-away/21907

### CODE REVIEW

**Comment by IdVincentYang** [comment]
- remove Node::FLAG_TRANSFORM_DIRTY in Scene::draw
- remove Node::hitTest interface, instead of another helper function
- fix the error usage of isVisitableByVisitingCamera
  @ricardoquesada  @masterhou  @dabingnn

**Comment by IdVincentYang** [comment]
[ci rebuild]

**Comment by IdVincentYang** [comment]
[ci skip] please review this pr @ricardoquesada @masterhou

**Comment by ricardoquesada** [comment]
@IdVincentYang 
I haven't seen anything that called my attention... everything seems to be good.

Although I don't know if the code is "correct" in the sense that I don't know if this code doing what it is supposed to be doing. You guys should determine that. Thanks.

**Comment by dabingnn** [comment]
@ricardoquesada This pull request has some relationship with this pull request #12277.

In the related pull request, you have comment for two things.
1. using `Node::FLAGS_TRANSFORM_DIRTY` flag in Scene::Render()
2. `Node::HitTest`.

I think this pull request is to solve this problem.

To make it clearer and reviewable, I would suggest to decompose it into several pull request.
Does it make sense?

BTW, @yangws and @IdVincentYang are two different accounts hold by `Vincent Yang`.

**Comment by ricardoquesada** [comment]
@dabingnn if that works for you, yes, sure.

**Comment by yangws** [comment]
[ci rebuild]

**Pull request closed without merging**
