### PR TITLE
Fix a potential crash in Scheduler

### PR DESCRIPTION
**Pull request by Pisces000221**
Sometimes the program crashes if we use `ccSchedulerFunc` together with `SEL_SCHEDULE` in one scheduler.
The crash is caused by invalid `static_cast`, and now it's fixed by using `dynamic_cast`.

I'm not sure whether to add a test case for this. Please tell me. Thanks!

### CODE REVIEW

**Comment by minggo** [comment]
Yep, it is better to add a test case in tests/cpp-tests.

**Comment by Pisces000221** [comment]
Okay, I'll add one soon.
What should I name it? Seems like this doesn't have an issue number and I can't think of a short description.

**Comment by minggo** [comment]
There is a `SchedulerTest.cpp`, i think you can add it there. The subtile can be `should not crash` or something else.

**Comment by Pisces000221** [comment]
Thanks, but I can't think of a short title like `SchedulerCallbackTest`. Will SchedulerCallbackWithTwoTypes work?

**Comment by Pisces000221** [comment]
`SchedulerCallbackTest` is a test case name in SchedulerTest.cpp.

**Comment by Pisces000221** [comment]
Sorry for disturbing, I got a shorter name. I'll create the test case soon. Thank you anyway :)

**Comment by Pisces000221** [comment]
The test case is added. Please let me know if there are any mistakes.

(PS. Don't be confused by the long time (2 hrs) between the comment and the commit. I left for a while after the comment and this only took me half an hour, not 2 hours :-D)

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
I run the test case and revert the modification of `CCScheduler.cpp`, no crash happened.

**Comment by minggo** [comment]
@Pisces000221 
Any thought?

**Comment by Pisces000221** [comment]
Are you using a Mac? I'm developing under Linux (Ubuntu 13.10 32-bit) and I think maybe it only crashes on some platforms. I'll revert the modification and re-run the test on my machine now.

**Comment by Pisces000221** [comment]
It doesn't crash after reverting... But it _did_ crash in one of my projects before making this change. I think it's a mandelbug. I don't know what made it crash but after I changed this file in the project, it worked very well instead of halting immediately. That's really strange.

**Comment by Pisces000221** [comment]
May I remove the test case and only make a change in Scheduler? I'm pretty sure it may cause problems in some cases.

**Comment by minggo** [comment]
@Pisces000221 
Because `dynamic_cast` is slower than `static_cast`, so i think it is better to reproduce it before merging this PR.

**Pull request closed without merging**
