### PR TITLE
fix pageview page turning event issue

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/issues/14909

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/issues/14962

**Comment by zilongshanren** [comment]
@pandamicro  帮忙review一下jsb部分的修改。

**Comment by pandamicro** [comment]
No problem for me

**Comment by zilongshanren** [comment]
@WenhaiLin  I have added the missing deprecated functions, please review.

**Comment by zilongshanren** [comment]
Tweak PageView turning event time: https://github.com/cocos2d/cocos2d-x/pull/15018

**Pull request merged**
