### PR TITLE
Use string::empty() to check whether string is empty.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by WenhaiLin** [comment]
@zilongshanren Please review this PR.

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
@zilongshanren Build fail cause by `IOError: [Errno 28] No space left on device`.Sad...

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by WenhaiLin** [comment]
@fusijie Please review this PR.

**Comment by fusijie** [comment]
@pandamicro @zilongshanren, please merge it.

**Comment by fusijie** [comment]
[ci rebuild]

**Pull request merged**
