### PR TITLE
added sensor property to shapes

### PR DESCRIPTION
**Pull request by danutchereches**

### CODE REVIEW

**Comment by andyque** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by danutchereches** [comment]
Are there problems with this?
Anything I can help with?

The feature seems pretty straightforward, so it shouldn't cause any issues.

**Comment by WenhaiLin** [comment]
@loadrunner Sorry for my late reply. @minggo This PR is Ok,we should merge it.

**Pull request merged**
