### PR TITLE
AdvancedSprite class  & AdvanceParticleQuadSystem class

### PR DESCRIPTION
**Pull request by varadharaj**
AdvancedSprite:
             A Subclass of CCSprite to do easier sprite animation. Has advanced controls through methods for controlling FPS, frame range etc. Very useful for all kind of games.

AdvanceParticleQuadSystem:
           A Subclass of CCParticle to do easier texture animation for particles. Has FPS control. Very useful for all types of games.

### CODE REVIEW

**Comment by walzer** [comment]
I'm so amazed by your beautiful design, well documented methods and coding style. Thanks for your contribution!

but ... honestly, besides mark it in the [sticky post](http://www.cocos2d-x.org/boards/6/topics/567),  I cannot merge it into master branch. 

Regarding to the [FAQ of cocos2d](http://www.cocos2d-iphone.org/wiki/doku.php/faq), please read the paragraph of "[Adding new features](http://www.cocos2d-iphone.org/wiki/doku.php/faq?&#adding_a_new_features)" & "[Which features / patches are merged](http://www.cocos2d-iphone.org/wiki/doku.php/faq?&#which_features_patches_are_merged)", and one more rule for cocos2d-x: don't modify methods inherited from cocos2d-iphone. Your pull request doesn't accord with 2 rules:
1. A test (or several sub-tests) that tests the new functionality
2. don't modify methods inherited from cocos2d-iphone.  // you hack a param to the end of CCParticleSystem ::updateQuadWithParticle(tCCParticle\* particle, CCPoint newPosition);
For these reasons, AdvanceSprite & AdvanceParticleQuadSystem are not very suitable for merging to master branch. Instead, developers can download your source from the forum, and easily HACK the engine, use your cool features.

Thanks for your contribution again, and waiting for your further contribution to the community!
BTW: some sample codes for AdvanceSprite/AdvanceParticleQuadSystem on the forum, will be more helpful to others :)

**Comment by varadharaj** [comment]
Ok. If I correct that 2 rules:
1. A test (or several sub-tests) that tests the new functionality
2. don't modify methods inherited from cocos2d-iphone. // you hack a param to the end of CCParticleSystem ::updateQuadWithParticle(tCCParticle\* particle, CCPoint newPosition);

It will be suitable for merging to master branch. 

Please give me some suggestion about this.

**Comment by walzer** [comment]
Yep.
Have you seen the new repository cocos2d/cocos2d-iphone-extensions? We will create a new folder "extensions" in this repository, parallels to cocos2dx/box2d folder. Then you can commit the sources and unit test to it. Just like the "extra" folder in older cocos2d-iphone versions.

**Comment by haqu** [comment]
would love to see these classes in action.

**Comment by varadharaj** [comment]
I can not clone new repository cocos2d/cocos2d-iphone-extensions. Please help me to clone this repository and add my classes in action.

**Comment by walzer** [comment]
Well, I will help you to move the classes into extension folder, after then
you can commit the your test code.

2011/6/20 varadharaj <
reply@reply.github.com>

**Comment by varadharaj** [comment]
I commit test code. Please verify it once so that i can add in extension folder.

**Comment by varadharaj** [comment]
Please check this 467ca182396e38a54c3a  serious commit alone. Other two thing has error.

**Comment by walzer** [comment]
I have moved AdvanceSprite & AdvanceParticleSystemQuad to the new repo http://github.com/cocos2d/coos2d-x-extensions It's the same to cocos2d-iphone-extensions.
Please pull sources into the new repo.

I still cannot build the last source of http://github.com/varadharaj/cocos2d-x.git  You may forget to commit AdvanceSpriteTest.cpp/.h, which cause the tests.xcodeproj cannot find these two files. 

And the AdvanceParticleSystemQuad still need to hack the original source. We can't do this because cocos2d-x will need to follow cocos2d-iphone, hacking sources and logics will make the upgrading job very hard. You can try the approaches such as inherit, polymorphism and so on.

Waiting your pull request in cocos2d-x-extensions!

**Comment by varadharaj** [comment]
I have made change in AdvanceParticleSystemQuad. 
Now I did not change in Base class (ie ParticleSystem).
I have done test also and added to it.
Is there any chance to add my code in Master.

**Pull request closed without merging**
