### PR TITLE
Adding missing includes

### PR DESCRIPTION
**Pull request by mdkcore0**
The TestCpp sample project fails to compile. This commit adds the missing includes for it (pthread and GL).

### CODE REVIEW

**Comment by minggo** [comment]
@rodrigogolive 
Thank you for your pull request.
But i think this PR includes something that not only adding missing includes, and it can not be automatically merged.
Could you please synchronize to latest codes and also update all submodules, then send the pull request again?

**Comment by mdkcore0** [comment]
Hi @minggo, just updated the pull request with the latest changes on master.

Thank you.

**Comment by azmeuk** [comment]
See #2212 :)

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/2212.

**Pull request closed without merging**
