### PR TITLE
Adding Async FileUtils to cocos2d-x

### PR DESCRIPTION
**Pull request by DavidDeSimone**
Following through on https://github.com/cocos2d/cocos2d-x/issues/16846

This adds "async" versions of the major FileUtil functions, that will be performed off thread, and callback to the main thread when complete with their result. 

Important Notes:

- I used the AsyncTaskPool under the task type IO.
- In order to keep the details of the async mechanism self contained, I pulled the functionality to a function called performOperationOffthread. This way if we ever want to change the mechanism from AsyncTaskPool to another threading mechanism, it should be easy.
- While FileUtils is not thread safe, I was able to work around this by calling "fullPathForFilename" on the main thread before calling the delegate functions. 
- I attempted several template meta-programming solutions to this problem before settling on the submitted approach. All of the template solutions were too complex, and non readable in my opinion.
- You can see I am using a number of value types instead of const-references. This is intentional as we are moving this data between threads, and I want to leverage move semantics.

### CODE REVIEW

**Comment by DavidDeSimone** [comment]
It looks like the auto binding generator doesn't like that I have all the callbacks using r-value references either. In fact, it looks like the auto generator doesn't handle taking non-pointer/booleans in lambda callbacks well.

**Comment by DavidDeSimone** [comment]
After talking with some colleagues, it seems the best way to fix the issue of data copying would be to have the async functions take their data by value instead of by reference. This way a user who wants to avoid a copy can just std::move their data at the function call.

**Comment by DavidDeSimone** [comment]
I apologize for the large number of commits I have made as part opening this PR. I have been having trouble getting the binding generator to work lately, and I'm not set up to iterate on certain compilers (like Visual Studio 2013).

So most of these commits have been in an effort to prevent copying data unnecessarily via move operations. I was very close to getting everything working, however it looks like Visual Studio 2013 does not support many of the tricks I was employing to move variables into lambdas for offthread execution. For the time being, I am going to let this PR sit in it's current state and let the maintainers examine it and comment. I still believe there is value merging this PR in it's current state, as file I/O on the main cocos thread will be detrimental to a smooth loading experience.

**Comment by DavidDeSimone** [comment]
@minggo What do you think of this PR? is this something worth adding to cocos2d-x?

**Comment by minggo** [comment]
Thanks, it looks good. Could you please add comments for all these new functions. Especially mentioned that they are asynchronous.

**Comment by DavidDeSimone** [comment]
@minggo Going to close this PR and open a new one that is squashed to keep the history clean.

**Pull request closed without merging**
