### PR TITLE
Multi touch

### PR DESCRIPTION
**Pull request by Macarse**
Check issue:
http://www.cocos2d-x.org/issues/247

### CODE REVIEW

**Comment by minggo** [comment]
I think there is an issue of multitouch.
You send as many as the pointers handleActionMove events to render, and then to c++.
Why?

**Comment by Macarse** [comment]
My last two commits contains Logs.
I can't solve two things:

a) Using the SingleTouchFilter:

I) nativeTouchesEnd doesn't work correctly.

cocos2d::CCTouch\* pTouch = s_pTouches[id[i]];
always returns null. I don't understand why.

II) the main screen, it doesn't scroll the list. I don't understand why :(

b) Using the MultiTouchFilter
It's "working" now but it doesn't feel good in the TouchesTest.

I am also concerned that the TouchesTest doesn't use my whole screen:
http://imageshack.us/photo/my-images/829/paddles.png/

**Comment by minggo** [comment]
I have tested your last pull request. And it runs ok on simulator.
It can scroll the list.

**Comment by Macarse** [comment]
ming:
Now we have two filters: SingleTouch and MultiTouch. The emulator must be using MultiTouch.
Try hardcoding the SingleTouch to test it.

**Pull request merged**
