### PR TITLE
updated version and filesize to get latest winrt websockets builds

### PR DESCRIPTION
**Pull request by stammen**
Updated config.json version and filesize to get latest winrt websockets builds

PR requested by @minggo https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/211

### CODE REVIEW

**Comment by minggo** [comment]
Oh, it failed on win32 and windows universal. The error said:

(ClCompile target) -> 
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\PerformanceAllocTest.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\PerformanceEventDispatcherTest.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\Profile.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\tuple(135): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\controller.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\AppDelegate.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\PerformanceCallbackTest.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\PerformanceContainerTest.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdexcept(33): fatal error C1090: PDB API call failed, error code '23' : '( (..\Classes\tests\BaseTest.cpp) [f:\win32_slave\workspace\ccs-pr\node\win32_bak\tests\performance-tests\proj.win32\performance-tests.vcxproj]

**Comment by minggo** [comment]
And could you please send to v3.11 branch?

**Comment by stammen** [comment]
@minggo This is a known Jenkins issue with parallel builds. It has nothing to do with this pull request which did not change any Win32 files.  I will make the pull request on the v3.11 branch.

https://issues.jenkins-ci.org/browse/JENKINS-9104

**Comment by stammen** [comment]
Replaced by PR https://github.com/cocos2d/cocos2d-x/pull/15400

**Pull request closed without merging**
