### PR TITLE
Eclipse project fix & debug support(compatibility version)

### PR DESCRIPTION
**Pull request by newnon**
Eclipse project compile fix(for all eclipse versions)
resource link fix
disabled syntax error highlighting 
disabled CDT syntax warning about override final nullptr
added ability do debug c++ code
fixed include warning

### CODE REVIEW

**Comment by newnon** [comment]
#### Adding and running from Eclipse

Import libcocos2dx library project:
1. File->New->Project->Android Project From Existing Code.
2. Click **Browse** button and open `your_project_path/cocos2d/cocos/2d/platform/android/java` directory.
3. Click **Finish** to add project
1. File->New->Project->Android Project From Existing Code
2. **Browse** to your project directory. eg: `your_project_path/proj.android/`
3. Add the project 
4. Set up NDK location Eclipse->Preferences->Android->NDK
5. Right click on your project and find Android Tools->Add native support
6. Right click on your project Properties->C/C++ Build change build command to ${ProjDirPath}/build_native.py -n NDK_DEBUG=1
7. Click **Run** or **Debug** to compile C++ followed by Java and to run on connected device or emulator.
8. Now you can click Debug as -> Android Native Application 
9. If you want you cant turn code analysis to off Right click on your project Properties->C/C++ General->Code Analysis->Use project settings and uncheck "Syntax and Semantics errors"

**Comment by dumganhar** [comment]
Still could not find `Add native support`. :)
I will try the normal version of eclipse.

**Comment by newnon** [comment]
strange may be you have some old settings in work space try to create new ability ti add native support checking this 4 line in .project
<nature>org.eclipse.cdt.core.cnature</nature>
<nature>org.eclipse.cdt.core.ccnature</nature>
<nature>org.eclipse.cdt.managedbuilder.core.managedBuildNature</nature>
<nature>org.eclipse.cdt.managedbuilder.core.ScannerConfigNature</nature>
i checked this project with 2 different versions latest bundle and latest original eclipse
both work fine

**Comment by dumganhar** [comment]
screen shot 2014-04-09 at 17 21 54
I checked that. the 4 lines did exist there.
PS: I used OSX system.

**Comment by newnon** [comment]
are you sure? you can see my pull request removes this 4 lines and .cproject file maby merge errors?

**Comment by newnon** [comment]
or may be your cocos console take cocos from other place? first time it save cocos path to bash variables and then just take it from where, even if you call setup.py once more

**Comment by dumganhar** [comment]
OK, so those 4 lines need to be removed. I used `cpp-empty-test` for testing.

**Comment by dumganhar** [comment]
I found the reason at https://groups.google.com/forum/#!topic/adt-dev/n8vGW15IbBg .

**Comment by newnon** [comment]
and i only remove it from template not from tests

**Comment by newnon** [comment]
full version is better i close this pull request and update full version

**Pull request closed without merging**
