### PR TITLE
Updated the Layout Component demo

### PR DESCRIPTION
**Pull request by doomsdayer**
Improved the demo for Layout Component, show all features of this system, now users can understand it completely.
The resource for this demo has been updated:
https://github.com/dumganhar/ccs-res/commit/db9f846d39f686df4f11f0ae963659bfe3b8c39d
image

### CODE REVIEW

**Comment by chengstory** [comment]
@minggo  think it can be merged. Thanks @doomsdayer!

**Comment by zilongshanren** [comment]
Thanks, @doomsdayer 
you should also update the ccs-res submodule commit pointer in the main repository.

**Comment by zilongshanren** [comment]
@doomsdayer 
Your tests has unused variables which are not allowed in iOS & Mac platform.
So please remove these unused variables.

**Comment by doomsdayer** [comment]
The submodule has been updated.

**Comment by doomsdayer** [comment]
The unused variable has been removed.

**Comment by doomsdayer** [comment]
[ci rebuild]

**Pull request merged**
