### PR TITLE
Testcase for CCS 1.6 animations with only one frame

### PR DESCRIPTION
**Pull request by patriciog**
This time I created a new branch in my fork and I'm doing a pull request from it. I think it is better a better and clean choice.

My old attempt was https://github.com/cocos2d/cocos2d-x/pull/15686

Thanks and best!

### CODE REVIEW

**Comment by minggo** [comment]
@patriciog Should update ccs submodule to pass the test?

**Comment by patriciog** [comment]
Yes, you should because I created a CCS project with two animation with only one frame each one. It was exported and merged with [PR #59](https://github.com/dumganhar/ccs-res/pull/59).

Thanks and best!

**Comment by minggo** [comment]
Could you please update the submodule? I think it is part of this PR.

**Comment by patriciog** [comment]
Sure, but I wouldn't like to make more mistakes, or other blunders.

Could you help me with it, please?

**Comment by patriciog** [comment]
@minggo I checked commits of ccs-res repository. The issue is [PR #58](https://github.com/dumganhar/ccs-res/pull/58) did remove several CCS resources but the references haven't been updated on cocos2d-x testcases.

I can't update the submodule, because all these references will be point to null.

Example: `var s_Cowboy_json = "ccs-res/armature/Cowboy.ExportJson"; \\ This was removed on PR #58!`

Thanks and best!

**Comment by minggo** [comment]
@patriciog yep, it is converted when merge v3.11 back to v3. I will take a look.

**Comment by patriciog** [comment]
Thanks @minggo.

If you need anything more please let me know.

**Comment by minggo** [comment]
@patriciog How to test it? I can not find the entry of this test case. Thanks.

**Comment by patriciog** [comment]
Sorry, I see it is only accesible on web. I'm going to add it to CocosStudioTest directly (cocoStudioTestItemNames instead g_guisTests).

**Comment by patriciog** [comment]
Hi @minggo:

I've created a new section: _MainMenu > CocoStudio > CCSIssueTest_. My testcase was added into this new one.

Thanks and best!

**Comment by minggo** [comment]
@patriciog Thanks, i will try it ASAP.

**Comment by minggo** [comment]
@patriciog yep, i can run the test case, but there is not way to back to parent scene, could you please add a menu item to go back to parent scene?

**Comment by patriciog** [comment]
Hi @minggo:

I tested again yesterday but I can back from Issue Scene to MainMenu without problems.

What is the wrong flow exactly?

Thanks and best!

**Comment by minggo** [comment]
@patriciog When you run the test case, how can you back to main menu?

screen shot 2016-05-31 at 4 27 21 pm

**Comment by minggo** [comment]
ping @patriciog

**Comment by patriciog** [comment]
The `BackCallback` was added. I don't understand why doesn't work now.
- Back to Issue Test Scene into AnimationsWithOnlyOneFrame.js

```
BackCallback: function(pSender){
    var pScene = new CCSIssueTestScene();
    pScene.runThisTest();
}
```
- Back to Coco Studio Test Scene into CCSIssueTest.js

```
BackCallback: function(pSender){
    var pScene = new CocoStudioTestScene();
    pScene.runThisTest();
}
```

It should be sufficient @minggo

**Comment by minggo** [comment]
@patriciog I have not idea.
@pandamicro Any idea?

**Comment by minggo** [comment]
@patriciog I sent you a PR to update ccs-res submodule, please merge it.

**Comment by patriciog** [comment]
Oks, @minggo.

When I'll be back home at night, because it is pointing to old resources now.

Thanks!

**Comment by patriciog** [comment]
I've merged it @minggo!

Thanks.

**Comment by patriciog** [comment]
Hi @minggo!

Sorry, I've fixed Back button visibility now. Button position are using VisibleRect now to fix to all devices screens.

Thanks and best!

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
