### PR TITLE
Fixed bug with cascade opacity and color for control button. #4881

### PR DESCRIPTION
**Pull request by zifter**
http://www.cocos2d-x.org/issues/4881

### CODE REVIEW

**Comment by zifter** [comment]
Why my build is failed for win32?
According to the output of building: failed python script, which I have not changed!
ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/cocos2d/cocos2d-x/statuses/fa45f3f4e0255b7b0a370595a3fc52833487067d (Caused by <class 'socket.gaierror'>: [Errno 11004] getaddrinfo failed)
....
Build step 'Execute Python script' marked build as failure
Finished: FAILURE
http://115.28.134.83:8000/job/cocos-2dx-pull-request-build/3100/node=win32_win7/console

**Comment by dumganhar** [comment]
it'S not your fault,we will check the ci issue,thanks
2014-5-10 下午5:27于 "Strokachuk Oleg" notifications@github.com写道：

**Comment by zilongshanren** [comment]
thx @zifter

**Comment by minggo** [comment]
[ci rebuilt]

**Pull request merged**
