### PR TITLE
close #3642:fix bounding box of new label is incorrect.

### PR DESCRIPTION
**Pull request by WenhaiLin**

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks.

**Comment by minggo** [comment]
Great.
And please update the progress in corresponding thread in forum.
Thanks.

**Comment by hanjukim** [comment]
@Dhilan007 Please see my new pull request
https://github.com/cocos2d/cocos2d-x/pull/5185
I think y position for new label is not fixed yet...

**Comment by huangzhentao** [comment]
I agree with @hanjukim

**Comment by WenhaiLin** [comment]
@hanjukim  I agree with you.I will fix it ASAP.We will merge your PQ.

**Pull request merged**
