### PR TITLE
Fix iCCP profile using mogrify

### PR DESCRIPTION
**Pull request by v1993**
I get a lot of `libpng warning: iCCP: known incorrect sRGB profile` on tests/templates.

This PR should fix it. For more information, refer to https://stackoverflow.com/a/22747902/5697743.

### CODE REVIEW

**Comment by v1993** [comment]
@drelaptop @minggo Can you take alook at it, please?

**Comment by drelaptop** [comment]
@v1993 wonderful, thanks for this good patch. I  will check it later.

**Comment by minggo** [comment]
@drelaptop I think we need to add something in doc to mention it.

**Comment by minggo** [comment]
@slackmoehrle I think we need to add something in doc to mention it.

**Comment by drelaptop** [comment]
Tested by TemplateCpp, it truly solved this issue. 

and I have new a issue for doc requirement https://github.com/cocos2d/cocos2d-x-docs/issues/161

**Comment by minggo** [comment]
And do not forget to set the milestone of this PR.

**Pull request merged**
