### PR TITLE
Adds support for Spine runtime 2.3

### PR DESCRIPTION
**Pull request by ricardoquesada**
Adds support for Spine runtime 2.3. Previous version was 2.1

### CODE REVIEW

**Comment by ricardoquesada** [comment]
[ci-rebuild]

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Hi, Riq, I found there is some JSB issues for upgrading Spine Runtime, I will take a look at it tomorrow

**Comment by pandamicro** [comment]
@ricardoquesada please take a look at my PR, it should fix the compilation issue

https://github.com/ricardoquesada/cocos2d-x/pull/2

**Comment by ricardoquesada** [comment]
@pandamicro thanks. Yes, I noticed that my PR was failing but I didn't have the time to look at it.

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
@ricardoquesada You haven't merged my PR, so the build won't pass

**Comment by ricardoquesada** [comment]
Thanks!. I've just merged your PR

**Pull request merged**
