### PR TITLE
Cleaner build script

### PR DESCRIPTION
**Pull request by folecr**
I noticed you were cleaning up the directory structure. Now is a good time to clean up the build scripts too :)
I've modified the build_native.sh
- Avoid duplicate path variables
- Use environment variables after testing
- If not, use sensible defaults

References
- http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
- http://stackoverflow.com/questions/228544/how-to-tell-if-a-string-is-not-defined-in-a-bash-shell-script

### CODE REVIEW

**Comment by minggo** [comment]
The script is more readable now, thank you.

I have a suggestion: not use "debug" and "verbose", and just pass parameter from console?
Because ndk-build accepts many parameters, like "clear", "debug=1" and so on.
I think we don't have to do the same job as ndk-build does.

**Comment by folecr** [comment]
Yes, it's a personal preference if those options should be at the script level or whether the call to ndk-build should use the script's command line arguments ...

I'll remove that change (it's a separate commit) and then you can merge the pull request.

**Comment by folecr** [comment]
Done. Please merge.

**Comment by minggo** [comment]
Thank you.

Would you mind also changing other samples and android template.

**Comment by folecr** [comment]
I could do that next week. I'll open a separate pull request.

**Comment by minggo** [comment]
ok, thank you.

**Pull request merged**
