### PR TITLE
#Improve RichText::createWithXml performance.

### PR DESCRIPTION
**Pull request by halx99**
# Improve RichText::createWithXml performance with real XML SAX parser.

### CODE REVIEW

**Comment by halx99** [comment]
[ci rebuild]

**Comment by halx99** [comment]
- And what's about replace tinyxml2 with rapidxml?

**Comment by halx99** [comment]
@minggo Take a look about this PR?

**Comment by minggo** [comment]
> And what's about replace tinyxml2 with rapidxml?

It is good for speed, but it may break compatibility.

@ricardoquesada could you please take a look of this PR? I am not familiar with these codes. Thanks.

**Comment by halx99** [comment]
As we known, the official rapidxml only support DOM parse, but it easy to add pure SAX parse(without any additional memory alloc) support based on rapidxml, and this PR already complete it.
For more detail and test project see: https://github.com/halx99/xmldrv3

**Comment by ricardoquesada** [comment]
@minggo I haven't review the whole code, but yeah, SAX should be faster and/or consume less memory. at least in theory.

@halx99 could you add a performance test with and without your patch? thanks.

**Comment by halx99** [comment]
see the new PR: https://github.com/cocos2d/cocos2d-x/pull/16419

**Pull request closed without merging**
