### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by gzito**
Fixed memory leak with jpeg files (http://www.cocos2d-x.org/boards/13/topics/9347)
Fixed wrong touch screen location when window is scaled (http://www.cocos2d-x.org/boards/13/topics/9227)

### CODE REVIEW

**Comment by minggo** [comment]
Did you synchronize your codes before pulling request?
This pull request can not be automatically merged.

**Comment by gzito** [comment]
You're right! I synchronized the code and I'm testing again now.

**Comment by minggo** [comment]
Thank you.
But it still can not be automatically merged.
I don't know why, could you please check it?

**Comment by gzito** [comment]
Sorry, I mean that I didn't push the code again.
After synchronization I'm experiencing compilation issues:

cocos2d-x\cocos2dx\tilemap_parallax_nodes\cctmxlayer.cpp(400): error C2872: 'size_t' : ambiguous symbol
          could be 'd:\cocos2d-x\tests\test.marmalade\build_test_vc10\predefined c++ types (compiler internal)(19) : unsigned int size_t'
          or       'd:\marmalade\6.0\s3e\h\std\sys\types.h(29) : _STL::size_t'

Same error in ccspriteframecache.cpp, ccparticlesystemquad.cpp and ccparticlesystempoint.cpp.

Do you want to close/abort this pull request or do you prefer to wait and keep it opened?

**Comment by minggo** [comment]
If you will resolve this issue.
I will wait and keep it opened.

**Comment by gzito** [comment]
Ok, I'll let you know.

**Comment by minggo** [comment]
Any progress?

**Comment by gzito** [comment]
Not yet. If you want you may close this request, I'll open a new one when resolved.

**Comment by minggo** [comment]
Ok, thank you.

**Pull request closed without merging**
