### PR TITLE
issue #4693: add getName(), setName() and getChildByName()

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
I will deprecate `getTag()`, `setTag()` and `getChildByTag()` in other PR.
@ricardoquesada 
Would you please review it?

**Comment by ricardoquesada** [comment]
The code is Ok, but it is not complete.
We need an API more flexible, like SpriteKit's

https://developer.apple.com/library/ios/documentation/SpriteKit/Reference/SKNode_Ref/Reference/Reference.html#//apple_ref/doc/uid/TP40013023-CH1-SW36

This PR has part of the code: https://github.com/cocos2d/cocos2d-x/pull/5671
But what's missing is support for regular expressions in the search.

Please, don't merge this PR until the feature is complete. Thanks.

**Comment by minggo** [comment]
I will not merge it.

I don't see the implementation of SpriteKit will search its children recursively in [enumerateChildNodesWithName:usingBlock](https://developer.apple.com/library/ios/documentation/SpriteKit/Reference/SKNode_Ref/Reference/Reference.html#//apple_ref/doc/uid/TP40013023-CH1-SW36). 

Should we search it recursively as #5671 did?

**Comment by minggo** [comment]
@ricardoquesada 
`enumerateChildren` is added.
Please review again.
Thanks.

**Comment by ricardoquesada** [comment]
could you please add some tests ? thanks.

**Comment by minggo** [comment]
Sure. I will add test cases if the API seems ok.

**Comment by ricardoquesada** [comment]
The API seems Ok, but the best way to test they API is by looking at examples... real use cases.
Also, a PR cannot be merged (even if the API is OK) without test cases.

**Comment by minggo** [comment]
I agree.
I will add test case in this PR.

**Comment by ricardoquesada** [comment]
ok. thanks.

**Comment by minggo** [comment]
Test case was added.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
Thanks for adding more test cases Minggo.
But we need to add more like:

``` c++
// enumerate all the children from scene
enumerateChildren("/scene/*", ....);

// enumerate all children from "layer" that start with sprite
enumerateChildren("/scene/layer/sprite*", ....);

// enumerate all some grandchildren
enumerateChildren("child/*", ....);
```

Please, take a look at this as an example:
https://developer.apple.com/library/ios/documentation/GraphicsAnimation/Conceptual/SpriteKit_PG/Nodes/Nodes.html#//apple_ref/doc/uid/TP40013043-CH3-SW17

**Comment by minggo** [comment]
Now `enumerateChildren` doesn't support advanced research.
I will read the doc.

**Comment by ricardoquesada** [comment]
Yes, I noticed that :)
Regular expressions is the killer feature here. The good news is that regexp is part of C++11.

**Comment by minggo** [comment]
Yep. I know it.
But the implementation of SpriteKit is more than just match the name with regular expression. It is more about the tree structure.

**Comment by minggo** [comment]
I mean the regular expression is something about tree structure.
I will do the same thing as it did.
It seems great.

**Comment by ricardoquesada** [comment]
ok. great!

**Comment by minggo** [comment]
Regular expression is supported:)
And i have added corresponding tests.
Now you can use it like this
- enumerateChildren("name")
- enumerateChildren("[[:alnum:]]")
- enumerateChildren("/name")
- enumerateChildren("//name")
- enumerateChildren("name/name2")
  ...

**Comment by ricardoquesada** [comment]
great!

**Comment by minggo** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
The api name `enumerateChildren` seems to be a little bit complicated to me, why not `findChildren` ?
I really like the idea, it's like jQuery's selector

**Comment by dingpinglv** [comment]
This feature is cool. 
I agree with @pandamicro , `findChildren` is better than `enumerateChildren`.

**Comment by minggo** [comment]
I will merge it if not problem.
Then deprecated getChildByTag() in another pull request.

**Comment by minggo** [comment]
@pandamicro
@dingpinglv
The name comes from SpriteKit.
And it is to find a child.
It will enumerate children, then invoke a call back when a name matched.

**Comment by minggo** [comment]
It is not to find a child.

**Comment by pandamicro** [comment]
@minggo why not just return all children matches the condition? Isn't callbacks over designed here?

**Comment by minggo** [comment]
You can return false to match all nodes.

**Comment by minggo** [comment]
If call back function returns false, it will continue to match next one.
It is a observer design pattern.

**Comment by darkdukey** [comment]
I agree with @pandamicro 
We should have a function `Vector<Node*> findChildren(name)` which will return all the children with the same name, I can see it been really useful in game development and more intuitive to use in some case, we can keep `enumerateChildren` they can play different role

**Comment by minggo** [comment]
Ok.
Let's add it in another pull request. It is easy to implement based on `enumerateChildren`.

**Comment by minggo** [comment]
#7218 was added to add findChildren().
I don't think we should add it in `Node`, it is a helper function, so i added in `utils`.

**Comment by darkdukey** [comment]
Why not, the children belongs to the `Node`. It's natural to have it there.

**Pull request merged**
