### PR TITLE
Adds mac workspace

### PR DESCRIPTION
**Pull request by ricardoquesada**
for the moment it includes TestCpp.
But Chipmunk, Box2d, cocos2dx, extensions and CocosDenshion are libraries
Like in the iOS project

### CODE REVIEW

**Comment by dumganhar** [comment]
I don't know why we ignored `*.xcworkspacedata` files in `.gitignore`. -_-!!!
Therefore, one thing has to be done is either to remove it from `.gitignore` or `git add -f cocos2d-mac.xcworkspacedata/contents.xcworkspacedata`.

**Comment by ricardoquesada** [comment]
fixed.

**Comment by dumganhar** [comment]
Merged. :) So would you add other projects to mac workspace?

**Comment by ricardoquesada** [comment]
yes, I will add more projects to it.

**Pull request merged**
