### PR TITLE
android emulator stensil fix

### PR DESCRIPTION
**Pull request by newnon**
there is no more need to use this Android Simulator support all modes

### CODE REVIEW

**Comment by minggo** [comment]
Why there is not need to do it like this?

**Comment by newnon** [comment]
1. it disables stencil buffer(it can break logic dependence on it)
2. it not needed now new Android simulator can handle most pixel modes

**Comment by minggo** [comment]
I am not sure, but please comment it instead of delete it. Then we can enable it again easily if needed.

**Comment by newnon** [comment]
done

**Pull request merged**
