### PR TITLE
Support for play sound effect with pitch , pan, gain

### PR DESCRIPTION
**Pull request by veena-peruvaje**
Port code from object c to  play sound effect with pitch, pan, gain

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, you added a new function(playEffect) for iOS, but other platform will be broken.
See here: https://travis-ci.org/cocos2d/cocos2d-x/builds/7662164.

**Comment by sergey-shambir** [comment]
We faced with same problem and just used this topic to tweak local cocos2d version: http://www.cocos2d-x.org/boards/6/topics/5572?r=10217

Pitch/pan/gain have known implementations for iOS/OSX/android, but not for other platforms... So can we create separate branch which will be merged to `develop` when pitch/pan/gain will be done for all platforms? I can try to implement it for Linux (afaik it have 2 CocosDension backends: FMOD and OpenAL).

**Comment by minggo** [comment]
@sergey-shambir 
I think you can implement it for other platforms and update them in this pull request.

**Comment by sergey-shambir** [comment]
Ok, I'm working on implementations for other platforms. What's done:
- correct iOS/Mac backend
- Linux (FMOD/OpenAL) - it's also tested.
- Nacl, Blackberry (both OpenAL) backends
- Better doxygen and extended CocosDenshion test in TestCpp application.

Emscipten and tizen ports partially done, win32 and marmalade not started yet.

Now I encountered following problems:
- Emscripten port uses SDL, which have no support for pitch. There are workaround implemented Doom port for Linux: directly edit sound buffer data. There are also another solution: rewrite all code to use OpenAL, which now supported by Emscripten: https://github.com/kripken/emscripten/blob/master/src/library_openal.js . Which approach I should use?
- Tizen port uses Tizen::Media::Player which have poor api (I see no way to implement pinch&pan). I also propose rewrite it to OpenAL which is part of Tizen SDK 2.1 (cocos2d-x uses 2.0 at this moment).

P.S. Why win32 port have no license headers and contains non-unicode comments ;) ?

**Comment by minggo** [comment]
@sergey-shambir 
Awesome job.
To be honest, i am not familiar with all platforms.
We focus on iOS and android. Other platforms are not target to release.
So i think you can do as much as you can for Emscriten and Tizen port.

**Comment by minggo** [comment]
And other developers will contribute for it if he/she is familiar with that platform.

**Comment by cocosQA** [comment]
Dear veena-peruvaje:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6498
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
