### PR TITLE
Return non-zero if ndk build fails.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by minggo** [comment]
If we build with `all` or `lua`, we don't want to it exit at once. May be should continue.

**Comment by minggo** [comment]
Because travis also use `all` to build all android samples. So it is reasonable to exit when meeting an error.

**Comment by dumganhar** [comment]
> If we build with all or lua, we don't want to it exit at once. May be should continue.

If cpp codes contain errors, why not to exit directly?
`Return directly` is needed when `cplusplus` source codes have errors.

BTW, the old logic of  `build_native.sh` did it like this.

**Comment by dumganhar** [comment]
In this way, the result of travic-ci will be correct.
You could refer to the latest ci-build of android port.
Although, the cpp codes triggered compilation errors, but it didn't quit. What was worse, it return 0 which means `no errors`.

**Comment by minggo** [comment]
Yep, may be we should add an option to control if should exit at once in future.

**Comment by dumganhar** [comment]
Agree.

**Pull request merged**
