### PR TITLE
Desktop and WinRT use correct keyboard codes

### PR DESCRIPTION
**Pull request by perminovVS**
Desktop:
GLFW_KEY_ENTER equals KEY_ENTER ( GLFW_KEY_KP_ENTER = KEY_KP_ENTER)
WinRT:
VK_PRIOR equals KEY_PG_UP ( not KEY_KP_PG_UP )

### CODE REVIEW

**Comment by pandamicro** [comment]
@WenhaiLin @stammen Can you confirm this ?

**Comment by stammen** [comment]
WinRT change looks good.

**Comment by WenhaiLin** [comment]
@dumganhar I think it's OK for merge. Please help confirm this ?

**Comment by pandamicro** [comment]
Thanks guys

**Pull request merged**
