### PR TITLE
Minor bugfix extensions/GUI/CCScrollView/CCTableView.cpp

### PR DESCRIPTION
**Pull request by ncrothe**
numberOfCellsInTableView returns unsigned int so, if it returns 0 and you subtract 1, you get a very big number and idx is never bigger than that - there are some places that did not handle this very well. I propose a few fixes.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hey, I think this issue has been fixed. You haven't pull the lastest code.
You could look inside the file(https://github.com/cocos2d/cocos2d-x/blob/gles20/extensions/GUI/CCScrollView/CCTableView.cpp).

**Comment by ncrothe** [comment]
Drat, you're right. I'll check if that version works for us.

**Comment by dumganhar** [comment]
Hi @ncrothe,
Could i close this Pull Request?

**Comment by ncrothe** [comment]
Yes, the changes seem to work for us, thanks.

**Pull request closed without merging**
