### PR TITLE
Getter always must be a const method.

### PR DESCRIPTION
**Pull request by zifter**

### CODE REVIEW

**Comment by shujunqiao** [comment]
[ci rebuild]

**Comment by zifter** [comment]
Something wrong with builder... again.
fatal: Couldn't find remote ref pull/6721/merge

**Comment by shujunqiao** [comment]
[ci rebuild], ref pull/6721/head is ok.i will rebuild again.

**Comment by shujunqiao** [comment]
in external/config.json, your pr is "current_libs_version:", the lastest version is "version:"
so you need merge the lastest code.

**Comment by dumganhar** [comment]
@zifter , sorry for the inconvenience. Could you pull our latest codes of v3 branch? Thanks.
BTW, this PR could not be automatically merged. :)

**Comment by zifter** [comment]
Thank you for replying.
Done.

**Comment by minggo** [comment]
@zifter 
I will merge it after releasing rc0.
We will release rc0 today.

**Comment by zifter** [comment]
@minggo 
Can you merge this PR? rc0 already released.
Thanks.

**Comment by minggo** [comment]
@ricardoquesada said we should only merge PR that fixed bugs. 
But i think this PR can be treated as bug fix. So I think we can merge this PR.
What's your opinion, @ricardoquesada ?

**Comment by ricardoquesada** [comment]
yes, this PR can be merged. thanks.

**Pull request merged**
