### PR TITLE
Textfiled support cursor v1.1

### PR DESCRIPTION
**Pull request by perminovVS**
Add StringUtils::StringUTF8 for easy manipulate utf8 string.
If TextField active(focused input text) show text cursor( default '|',
change TextFieldTTF::setCursorChar ).
Show/Hide interval CURSOR_TIME_SHOW_HIDE
Change position text cursor control key: KEY_HOME, KEY_END,
KEY_LEFT_ARROW, KEY_RIGHT_ARROW
CC_PLATFORM_MAC, CC_PLATFORM_WIN32, CC_PLATFORM_LINUX default use
cursor( For change state TextFieldTTF::setCursorUse )
Desktop implement dispatchControlKey
WinRT support key repeat and implement dispatchControlKey
Text cursor worked only on LabelType::TTF

new version it: #13600 , for easy merge

### CODE REVIEW

**Comment by perminovVS** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@perminovVS 
Hi, there is a problem when moving the cursor with arrow key.

I tested it in Mac OS X.

image

**Comment by perminovVS** [comment]
@zilongshanren ok, i will try to build and test the mac

**Comment by perminovVS** [comment]
@zilongshanren it no my code bag, see master branch cocos2d/v3.
glfw in OSX send unicode char for control key(Test it for cocos2d/v3), on Windows it not send.
I fix it, check CharCallback on contains control unicode char and not send them.

**Comment by perminovVS** [comment]
[ci rebuild]

**Comment by perminovVS** [comment]
@pandamicro @zilongshanren check it.

**Comment by 0xJimmyBeh** [comment]
@pandamicro @zilongshanren

Any news on this cursor support?

Would like to use this feature in v3.9 with JS.

Thank you.

**Comment by zilongshanren** [comment]
@perminovVS 
Hi, I'm very sorry for the late reply.
Do you mind to continue the work to add cursor support for TextField?
Since many people are asking for this feature and I would glad to help to merge your code.

**Comment by zilongshanren** [comment]
@Zinitter

With JS, do you mean H5 or JSB?

**Comment by 0xJimmyBeh** [comment]
@zilongshanren 

It is JSB.

**Comment by perminovVS** [comment]
@zilongshanren yes, I ready.

**Comment by zilongshanren** [comment]
@perminovVS  :+1:

**Comment by zilongshanren** [comment]
@Zinitter 
OK, I see, I will make sure the JSB is working after merging this PR.

**Comment by perminovVS** [comment]
@zilongshanren recreate for easy merge ?

**Comment by 0xJimmyBeh** [comment]
@zilongshanren 
Glad to see if it can be used in JSB of coming version.

@perminovVS 
Good to see you are ready to bring this great feature to engine. 

A lot of people would happy and benefit with the cursor support.
Thank you for the efforts!

**Comment by zilongshanren** [comment]
@perminovVS 
Recreate is better, thanks.

**Comment by zilongshanren** [comment]
@perminovVS  
When your PR is ready, please ping me.
thanks.

**Comment by 0xJimmyBeh** [comment]
@perminovVS @zilongshanren 

Is there any update with this on v3.10? 

Thank you.

**Comment by perminovVS** [comment]
@Zinitter sorry, little time.
I try to send it.

**Comment by 0xJimmyBeh** [comment]
@perminovVS 

Is ok, nothing to be sorry.
Just wish to use this awesome feature.

Thank you for your effort!

**Comment by perminovVS** [comment]
@zilongshanren see new #15195

**Pull request closed without merging**
