### PR TITLE
Fix a bug in Scheduler which may case Force Close

### PR DESCRIPTION
**Pull request by waiter**
Fix a bug in Scheduler which may case Force Close

### CODE REVIEW

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by dabingnn** [comment]
@waiter Thanks.
In my opinion, the new code seems to be safer, but `dynamic_cast` is slower than `static_cast`. Would you give a small test case to reproduce the bug?

**Comment by waiter** [comment]
@dabingnn 
There are two type of selectors: `TimerTargetCallBack` and `TimerTargetSelector`
SO, If one Node scheduled both of the two type selectors, then , call the function `isScheduled(xx,xx)`
Because all selectors will `static_cast` to `TimerTargetCallBack` or `TimerTargetSelector`, and one of the selectors can't cast successful.
And when cast failed, `static_cast` will cast **FORCE CLOSE**! But `dynamic_cast` will just return null!

**Comment by WenhaiLin** [comment]
@dabingnn I think this PR is OK for merge.`Scheduler::unschedule` is not the key point of the overall performance.

**Comment by dabingnn** [comment]
@waiter Thanks, it seems that `TimerTargetCallBack` and `TimerTargetSelector` are subclass of `Timer`, but we need the concrete information on the subclass. My thoughts is that we can refine it.
Although this pull request can be merged, but we may need a better design for it.
@WenhaiLin What is your thoughts?

**Comment by waiter** [comment]
@dabingnn 
You are right, just fix it for now.

**Pull request merged**
