### PR TITLE
#FIX Label size calculation bug.

### PR DESCRIPTION
**Pull request by halx99**
see issue: #16399

### CODE REVIEW

**Comment by minggo** [comment]
The codes is changed by @cezheng in #16172. @cezheng could you please take a look?

**Comment by cezheng** [comment]
I don't see why this is a bug after looking at the issue. FYI,  #16172

**Comment by cezheng** [comment]
Also, I think this code is wrong if contentScaleFactor or _bmFontScale does not equal to 1.0

**Comment by minggo** [comment]
@cezheng you can refer to #16399 for detail information.

**Comment by cezheng** [comment]
I guess my PR is moving letters from right to left as you can see in the screenshots in #16172. However the screenshots in #16399 the letters seems to be overlapping with the right of the boundingbox.

**Comment by cezheng** [comment]
I can't say much yet. My advice:
1. Also test with bitmap fonts
2. Also test with different contentScaleFactor
3. Also test with different _bmfontScale
4. Also test with different Alignment configurations

My fix might not be right in all situations, but neither is this PR at the moment I guess.

**Comment by halx99** [comment]
How about:

```
tokenRight = letterPosition.x + letterDef.width * _bmfontScale / contentScaleFactor; // #FIX Label size calculation bug.
```

**Comment by minggo** [comment]
@halx99 @cezheng Yep, i think we should add test case for it first.

**Comment by halx99** [comment]
Yes

**Comment by minggo** [comment]
@halx99 will you add the test case?

**Comment by halx99** [comment]
I have not add test case, but I test in our game, it's work ok:
test with bitmap fonts(work ok)
test with different contentScaleFactor(work ok)
test with different _bmfontScale(the engine implement always 1.0)
test with different Alignment configurations(work ok)
arp2nsmm505hn wk4 vs bp

**Comment by minggo** [comment]
@halx99 can you add these test cases in cpp-tests?

**Comment by halx99** [comment]
And where shoud I add to? bug-test?

**Comment by minggo** [comment]
I think it can be added in `UITest`, now the test case is nothing about cocos studio.

**Comment by halx99** [comment]
OK, I will add later.

**Comment by minggo** [comment]
thanks

**Comment by cezheng** [comment]
This just reverts #16172 and it will cause problems for right alignment for bitmap font.

**Comment by cezheng** [comment]
Let me explain a little bit about why I made the changes in #16172 

Characters that have different `letterDef.width`, for example 0 and 1, the calculated `letterRight` for 1 will be smaller than 0. If we use this value for calculating line width, if the last character for different lines will have problems when alignment is set to right.

#16172 change it to use the starting position of the next character to calculate the line width, which makes right alignment look normal. Because this adds xAdvance & additionalKerning to it, which make all characters the same width. The original formula ends with calculating the last character of each line a little bit narrower.

**Comment by halx99** [comment]
Actually the new Label have anothor incorrect behavior:

vb441wk122 nnsxa 0cw

**Comment by halx99** [comment]
so still need test

**Pull request closed without merging**
