### PR TITLE
V3: Added Windows 10 UWP librecast. Fix Windows 8.1 librecast

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates the Windows 10 UAP projects to add the missing librecast, and NavMesh files and tests. The cpp-templates and js-templates were also updated to build correctly.

This pull request depends on files added in the PR https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/165

### CODE REVIEW

**Comment by zilongshanren** [comment]
@stammen  I have created a `v3-deps-66` to your 3rd party libs.

**Comment by stammen** [comment]
@andyque Thanks. However,When I try to use  v3-deps-66 in config.json I get the error

  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'E:\\GitHub\\cocos2d-x-v3\\external\\framework-compile'

Should I remove         "framework-compile":"tools" from config.json?

**Comment by stammen** [comment]
@andyque Thanks. I updated the version in config.json.

**Comment by stammen** [comment]
@ricardo @andyque @minggo Please pull this code as the Universal Apps were broken by the addition of librecast and NavMesh.

**Comment by ricardoquesada** [comment]
ok. done.

**Comment by stammen** [comment]
Thanks!

**Pull request merged**
