### PR TITLE
Rename `MutiTouchTest` to `MultiTouchTest`

### PR DESCRIPTION
**Pull request by mogemimi**
Hello, I fixed a misspelled test case (`MutiTouchTest` -> `MultiTouchTest`) and also fixed the `MultiTouchTest` filename in build projects.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@mogemimi , thanks, it was merged.

**Comment by mogemimi** [comment]
@dumganhar @zilongshanren Thank you for reviewing and confirming this!

**Pull request merged**
