### PR TITLE
fix #10242, reload shader when light number changed

### LINKED ISSUE #10242: loadConfigFile() should be called earlier than the default shader's initialization
For example, when we modify the light' number from 1 to 3 in the file of "config-example.plist", we also just have one light, because "loadConfigFile()" is called later than "GLProgramCache::loadDefaultGLProgram()" , so the light's number in the shader is still one.

### PR DESCRIPTION
**Pull request by super626**
fix #10242

### CODE REVIEW

**Comment by yangws** [comment]
@pandamicro @super626 
This pr is OK for this issue.
But i have another idea about this issue below:
How about fix this bug using event mechanism?
Add a custom event like "config reloaded", subscribe this event in glstatuscache.
Thus, the new API "GLProgramCache::isInstanceCreated" is not necessary.
In the other hand, this will meet other requirements which reaction of config file loaded.

**Comment by pandamicro** [comment]
@super626 What do you think, I think event system is a good idea

**Comment by super626** [comment]
@yangws 
Thanks. It is great idea.

**Comment by super626** [comment]
@yangws 
@pandamicro 
Done

**Pull request merged**
