### PR TITLE
Update Android.mk

### PR DESCRIPTION
**Pull request by Quanwei1992**
自动包含classes的源文件.避免cocos2d-x发生undefined reference to `XX'等错误

### CODE REVIEW

**Comment by minggo** [comment]
I have done it as you did. But not all platforms support it well.

**Comment by Mazyod** [comment]
@minggo Then, can you please add this code as a comment with the supported platforms? This is an extremely desired feature.

**Comment by Quanwei1992** [comment]
Can use python, the build the android project, modify android.mk  file. Add all the source files into it.

------------------ 原始邮件 ------------------
发件人: "Mazyad Alabduljaleel";notifications@github.com;
发送时间: 2014年4月14日(星期一) 下午4:21
收件人: "cocos2d/cocos2d-x"cocos2d-x@noreply.github.com; 
抄送: "Sky"573011406@qq.com; 
主题: Re: [cocos2d-x] Update Android.mk (#6268)

@minggo Then, can you please add this code as a comment with the supported platforms? This is an extremely desired feature.

**Comment by minggo** [comment]
Pleas refer to the discussion in #3355.

**Comment by cocosQA** [comment]
Dear qq573011406:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6413
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
