### PR TITLE
Fix JPEG images not loading properly on iOS 4.3.x

### PR DESCRIPTION
**Pull request by rtissera**
Please refer to this thread for more details on the issue : http://www.cocos2d-x.org/boards/6/topics/17929?r=17955
Fix verified on iPad 1st gen 4.3.3 and iPad 2nd Gen 4.3.3

### CODE REVIEW

**Comment by minggo** [comment]
@rtissera
Thank you for work.

Could you please use a separate branch for a pull request?
I found you modified CCControlSwitch.cpp and AUTHORS in master branch.

If i merge your PR, these modifications will be merged too.

Thank you.

**Comment by rtissera** [comment]
Closing as we discovered this has some side issues, please disregard.

**Comment by minggo** [comment]
Could you tell me what't the side issues?

**Comment by tiantian20007** [comment]
We came across this issue too. So again: what't the side issues ?

**Comment by rtissera** [comment]
Sorry for late reply.
Actually it's safe to merge it, was had issues unrelated to this fix.

We improved the fix by limiting this behaviour to iOS versions before 5.x
in the following way :

<<<< CCImage.mm line 54 <<<<<<
    pImageinfo->hasAlpha =  (info == kCGImageAlphaPremultipliedLast)
                            || (info == kCGImageAlphaPremultipliedFirst)
                            || (info == kCGImageAlphaLast)
                            || (info == kCGImageAlphaFirst);

```
// If OS version < 5.x, add condition to support jpg
float systemVersion = [[[UIDevice currentDevice] systemVersion]
```

floatValue];
    if(systemVersion < 5.0f)
    {
        pImageinfo->hasAlpha = (pImageinfo->hasAlpha || (info ==
kCGImageAlphaNoneSkipLast));
    }

Hope it helps, will try to make a clean PR with a branch when I have time.
Or you can manually fix on master, as you wish.

2013/3/21 tiantian20007 notifications@github.com

**Comment by tiantian20007** [comment]
This pr is clean now, should be merged

**Comment by rtissera** [comment]
Yes, please merge.

Thanks !

2013/5/2 tiantian20007 notifications@github.com

**Pull request closed without merging**
