### PR TITLE
v4-multi-meta-textures, inprogress.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by minggo** [comment]
We will be releasing v4 recently, so i will not merge it into v4.0.

**Comment by halx99** [comment]
ok, could be v4-next, and there still somethings to be done.

**Comment by halx99** [comment]
@minggo  And I have a question, currently if device doesn't support, then the cocos2d-x v4 app will crash due to create device failed.

**Comment by halx99** [comment]
> @minggo And I have a question, currently if device doesn't support, then the cocos2d-x v4 app will crash due to create device failed.

confirmed, iphone device is ok, iphone simulator does support metal

**Comment by minggo** [comment]
Yep, v4 only supports metal. And macOS 15 + Xcode 11 supports metal in iPhone simulator.

**Comment by halx99** [comment]
[ci rebuild]

**Pull request closed without merging**
