### PR TITLE
[ci skip]add chinese note for CCRenderer.h

### PR DESCRIPTION
**Pull request by dabingnn**

### CODE REVIEW

**Comment by dabingnn** [comment]
@fusijie could you please review it? Thanks

**Comment by fusijie** [comment]
`@brief`
`@return`
`@para`
...

**Comment by dabingnn** [comment]
@VisualSJ @fusijie I do not know who is my reviewer, could you please review my pr? Thanks

**Comment by zilongshanren** [comment]
@dabingnn   please refer to https://docs.google.com/document/d/1bql0rIPUk5HDNV70KkFPRkPgb-REZVUC4F7vvc71aS0/edit

**Comment by VisualSJ** [comment]
@andyque This PR is ok for merge.

**Pull request merged**
