### PR TITLE
add WebView

### PR DESCRIPTION
**Pull request by zilongshanren**
1. Add WebView support for IOS and Android
2. Add tests to test the WebView feature.

### CODE REVIEW

**Comment by gin0606** [comment]
Thanks a lot @andyque !
Your work looks OK to me!

**Comment by minggo** [comment]
@andyque 
Please fix conflict.

**Comment by 0xJimmyBeh** [comment]
@andyque 

I found that WebView Android not support file upload.

There is no openFileChooser in WebView Android which allow user to choose file for upload in WebView.

WebView iOS is working properly for photo select and take photo with camera.

Tested with webpage :
http://www.anyimg.org/

Can you please help me on this Android issue?

Thanks.

**Comment by 0xJimmyBeh** [comment]
https://github.com/cocos2d/cocos2d-x/issues/10862

**Pull request merged**
