### PR TITLE
fixed indentation of Python files

### PR DESCRIPTION
**Pull request by kompjoefriek**
- Changed tabs to spaces
- Changed 2 spaces to 4 spaces

### CODE REVIEW

**Comment by darkdukey** [comment]
[ci skip]

**Comment by kompjoefriek** [comment]
Should have added [ci skip]

**Comment by minggo** [comment]
[ci rebuild]

**Comment by kompjoefriek** [comment]
Same as with my other pull request, i seemed to have messed up when merging...

Maybe i should get a fresh copy of v4, make a new branch and submit a new pull request?

**Comment by darkdukey** [comment]
It's okey, I think it's the build server's problem

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@kompjoefriek 
It seems that this pull request not only fix indent issue.
It modifies many other files.
Could you please revert other modification except for indent issue?
And could you please fix conflict?

Thanks.

**Comment by kompjoefriek** [comment]
@minggo 
Sorry for making such a mess earlier. It looks like i got it right this time.

**Pull request merged**
