### PR TITLE
Enabling c++ 11 support for iOS. cocos2dx/proj.ios/cocos2dx.xcodeproj also needs to be updated.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by sergey-shambir** [comment]
New standard isn't enabled for Mac, is it?

**Comment by minggo** [comment]
@sergey-shambir 
What's your meaning?
Could you please describe it more in detail?
Thank you.

**Comment by sergey-shambir** [comment]
Sorry, I didn't check latest Mac OS X xcodeproj.

**Comment by minggo** [comment]
k, i got it.
I thought there was a new standard of Mac:)

**Pull request merged**
