### PR TITLE
Eclipse Project import - Documentation Added and Tested

### PR DESCRIPTION
**Pull request by rohankuruvilla**
Note: I've added README files and tested with @folecr

Allows cocos2d-x Android projects to easily be included in Eclipse. 

Big thanks to @onedayitwillmake for his earlier work in a similar direction. Was of great help. Project can be found here. https://github.com/onedayitwillmake/EclipseAndroid_NDK_SDK

Features:
1. Complete workflow from Eclipse. Including
   a. Build C++
   b. Clean C++
   c. Build and Run whole project
   d. Logcat view
2. True C++ editing, including
   a. Code completion
   b. Jump to definition
   c. Refactoring tools etc.
   d. Quick open C++ files

Pre-Instructions for warming up Eclipse.
1. Install Eclipse and install ADT and CDT packages.
2. Import libcocos2dx project as new Android Application project. Steps:
   a. File->new->Project..->Android Project From Existing Code
   b. Click Browse button and open cocos2dx/platform/android/java directory
3. Set Path Variables for cocos2d-x root. Steps:
   a. Eclipse->Preferences->General->Workspace->Linked Resources
   b. Click the New button to add a variable called "COCOS2DX" and point it to the root cocos2d-x directory (Directory containing cocos2dx, external, scripting, tools etc.)
   c. Add "NDK_ROOT" variable for the root path to NDK from Eclipse->Preferences->General->C/C++->Build->Environment->Add

NOTE: These steps need to be done only once. After this you can import as many projects as need be, with no additional modifications

Now you can create new project using project creator, or open a sample project. 

Note: Open proj.android folder from File->New->Project..->Android Project From Existing Code

TODO:
1. NDK-GDK support within Eclipse

### CODE REVIEW

**Comment by fape** [comment]
Hi!
I think this is very usefull PR. Thanks.
I'd like to try under windows 7 x64. I completed the Pre-Instructions steps without error but after I imported the HelloCpp project I got this error message: "\bin\bash not found in PATH".
Could you please help me? What I miss?

**Comment by rohankuruvilla** [comment]
@fape 

Hi,

I've changed the build command for C++ from /bin/bash to just bash. So as long as you have Cygwin installed, it should have bash in your PATH. Unfortunately, I do not have a Windows machine to test it out on. 

This command can be found in Project->Properties->C/C++ Build

**Comment by fape** [comment]
@rohankuruvilla
Thanks It works for me. I can run Samples/Cpp apps on my phone.
 I do the following steps:
1. Install Cygwin (to C:\Cygwin) with make
2. Add 'C:\Cygwin\bin' to system PATH variable
3. Add this line `none /cygdrive cygdrive binary,noacl,posix=0,user 0 0` to C:\cygwin\etc\fstab
4. Change file ending to unix in build_native.sh (I think Git clone/fetch changed the file ending to windows format)
5. Add CYGWIN variable with "nodosfilewarning" value   Eclipse->Preferences->General->C/C++->Build->Environment->Add    (this may unnecessary)

**Comment by rohankuruvilla** [comment]
@fape 

That's awesome! Do you think you can update the README files for each Android project to include steps to run on Windows?

Thanks a lot,

Rohan

**Comment by dumganhar** [comment]
Thanks.

**Comment by fape** [comment]
@rohankuruvilla 
Yes, I'm going to update readme-s and also add CocosDension link to some project.
Can we use `bash -o igncr ${ProjDirPath}/build_native.sh` instead of `bash ${ProjDirPath}/build_native.sh` in build command ? `-o igncr` is hide unix vs window line ending in windows/cygwin.

**Pull request merged**
