### PR TITLE
fix crash when fore call remove child bone from a bone which already …

### PR DESCRIPTION
**Pull request by geron-cn**
fix crash when fore call remove child bone from a bone which already removed from a skeleton.

### CODE REVIEW

**Comment by geron-cn** [comment]
@pandamicro  could you please review at this, thx.

**Comment by pandamicro** [comment]
Next time, please make sure the first line of commit message less than 50 letters, otherwise it will be wrapped

**Comment by geron-cn** [comment]
Yes, I will watch out this .

**Comment by pandamicro** [comment]
Rearranged to https://github.com/cocos2d/cocos2d-x/pull/13256

**Pull request closed without merging**
