### PR TITLE
Add kLanguageKorean to ccLanguageType and getCurrentLanguage()

### PR DESCRIPTION
**Pull request by wenbin1989**
- Add Korean Language Type in ccLanguageType and CCApplication::getCurrentLanguage() function.
- complement implement of CCApplication::getCurrentLanguage() in mac port

### CODE REVIEW

**Comment by wenbin1989** [comment]
Korea is an important market of mobile game, so I think it is necessary to add Korean Language Type.
Thanks.

**Comment by minggo** [comment]
Do you mind modify corresponding test case in samples/TestCpp/CurrentLanguageTest/CurrentLanguageTest.cpp?
Thank you.

**Comment by wenbin1989** [comment]
Hi minggo:

I have added Korean Language Type in CurrentLanguageTest.cpp, and tested in ios,
android, mac. Works fine.

Check please, thanks.

**Comment by minggo** [comment]
Thank you.

**Pull request merged**
