### PR TITLE
add PlayableFrame

### PR DESCRIPTION
**Pull request by geron-cn**
1. add PlayableProtocol
2. add PlayableFrame

### CODE REVIEW

**Comment by geron-cn** [comment]
@xiaofeng11  @pandamicro  
please review this pr,  if this pr can be merge, the next step we will play/stop the particle and audio in animation.

**Comment by geron-cn** [comment]
[cr skip]

**Comment by geron-cn** [comment]
@ricardoquesada  could you please review this, thx

**Comment by geron-cn** [comment]
@ricardoquesada 
requirement:  make it possible to play/stop particle and audio in animation.
so i modified  `CCProtocols.h` `CCParticleSystem.h` `CCParticleSystem.cpp` and some editor-support code, could  you checkout the modification about the three files. Thank you.

**Comment by ricardoquesada** [comment]
@geron-cn looks good to me, although I haven't tested the Cocos Studio part.
Are you going to continue working on this PR?

**Comment by geron-cn** [comment]
than you.
no, the continue part is for parsing binary file export from Cocos Studio, I will make a another pr  in later time.

**Comment by xiaofeng11** [comment]
The cocos studio part is good to me. It can be merge.

**Pull request merged**
