### PR TITLE
not set _orderOfArrival to 0 after in visit

### PR DESCRIPTION
**Pull request by minggo**
There may be a problem in this situation

``` c++
auto node1 = Node::node();
auto node2 = Node::node();
addChild(node1);
addChild(node2);
```

`node1` will be visited before `node2` because it is added first. But after visit, _orderOfArrival of node1 and node2 are 0. And the implementation of `nodeComparisonLess` is

``` c++
bool nodeComparisonLess(Node* n1, Node* n2)
{
    return( n1->getLocalZOrder() < n2->getLocalZOrder() ||
           ( n1->getLocalZOrder() == n2->getLocalZOrder() && n1->getOrderOfArrival() < n2->getOrderOfArrival() )
           );
}
```

It will return false, which means node2 will be visited before node1.

### CODE REVIEW

**Comment by minggo** [comment]
Of course, we should invoke `Node::reorderChild()` to trigger sort operation.

@ricardoquesada 
Why set `_orderOfArrival` to 0?

And i found Label::visit() and SpriteBatchNode::visit also invoke `setOrderOfArrival(0);`.
Why?

Am i missed something?

**Comment by minggo** [comment]
@ricardoquesada 
What's your opinion?

**Comment by dumganhar** [comment]
I also feel confused about that.

**Comment by dumganhar** [comment]
@minggo , why did you close this PR?

**Comment by minggo** [comment]
I wrongly deleted the corresponding branch.
No matter, can fix it in other pull request after confirm it.

**Comment by ricardoquesada** [comment]
I can't remember why it is there.
But removing that code before releasing v3.0 is too risky.

**Comment by minggo** [comment]
Ok, so remove it in v3.1.

**Pull request closed without merging**
