### PR TITLE
Add Horizontal Text Alignment to UIEditBox

### PR DESCRIPTION
**Pull request by joshbodily**
57174bec-9158-11e6-8747-3e1cbf207c5d

### CODE REVIEW

**Comment by minggo** [comment]
@joshbodily is this PR still valid?

**Comment by joshbodily** [comment]
Yes, it is still valid.  I need to fix the Win32 compile error in Jenkins, but after that it should be ready.

**Comment by minggo** [comment]
@zilongshanren could you please take a look?

**Comment by zilongshanren** [comment]
@joshbodily  thanks, it looks good to me. 👍

**Comment by joshbodily** [comment]
Thanks guys! 🙏 👍

**Pull request merged**
