### PR TITLE
Combine Cocos Studio change to simulator

### PR DESCRIPTION
**Pull request by xiaofeng11**
Add dllexport to make libsimulator can be compiled as dynamic library.
Fix some irregular implementation, function implement in simulator project, but use in libsimulator project

@ricardoquesada @minggo @pandamicro Please review this pr.

### CODE REVIEW

**Comment by minggo** [comment]
Sorry, i am not familiar with simulator.

**Comment by xiaofeng11** [comment]
@minggo Then who can review this PR now? I won't know LiaoYuLei's nickname on github, does's him can review this PR?

**Comment by minggo** [comment]
I think @linshun knows.

**Comment by linshun** [comment]
YuLei's github ID is @dualface .
Hi @dualface , could you please review this PR?

**Comment by xiaofeng11** [comment]
We found a new way to change simulator, Lua-binding & js-binding together, It can decrease modifies, this PR will be closed and make a new PR.

**Comment by ricardoquesada** [comment]
@linshun I think you should update the "owners" spreadsheet and add there the owner of the simulator.

**Comment by linshun** [comment]
@ricardoquesada Yes, I am looking a right guy to take this job.

**Pull request closed without merging**
