### PR TITLE
add opacity support to DrawNode

### PR DESCRIPTION
**Pull request by zilongshanren**
fixed issue: https://github.com/cocos2d/cocos2d-x/issues/8764

### CODE REVIEW

**Comment by davidchai-6waves** [comment]
In cocos/renderer/ccShader_PositionColorLengthTexture.vert, should "uniform float u_alpha;" place outside the if else block?

**Comment by minggo** [comment]
@davidchai-6waves good catch. I just tested in mac. I will send a pr to fix it.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/17324

**Comment by intmainreturn00** [comment]
At what version of the engine It should work? 
I tested with 3-13 and it doesen't work..

**Pull request merged**
