### PR TITLE
fix bug: #21904 : cpp-tests Renderer Test -> New Render Drag the laye…

### PR DESCRIPTION
**Pull request by yangws**
…r to test the result of culling test ckick regin error after drag.

### CODE REVIEW

**Comment by dabingnn** [comment]
@pandamicro This pull request can fix the touch bug, but it break compatibility.
`Scene` could be moved by calling `SetPostion` functions Before. And if this pull request is merged, `Scene` could be moved, but it takes no effect.
My proposal is
1. Try to find a solution which has no side effects.
2. If we can not find one, we must choose one in this options: `touch bug fixed` and `Scene can be moved`.

**Comment by pandamicro** [comment]
I think backward compatibility is important, move a scene seems like a behavior many user may have, so I also suggest to find another way to fix this problem

**Comment by dabingnn** [comment]
The bug does not exist before Version 3.5.

**Comment by zilongshanren** [comment]
@pandamicro @dabingnn Could we accept this patch?

**Pull request closed without merging**
