### PR TITLE
TextFieldTTF support text cursor

### PR DESCRIPTION
**Pull request by perminovVS**
Add StringUtils::StringUTF8 for easy manipulate utf8 string.
If TextField active(focused input text) show text cursor( default '|',
change TextFieldTTF::setCursorChar ).
Show/Hide interval CURSOR_TIME_SHOW_HIDE
Change position text cursor control key: KEY_HOME, KEY_END,
KEY_LEFT_ARROW, KEY_RIGHT_ARROW
CC_PLATFORM_MAC,  CC_PLATFORM_WIN32, CC_PLATFORM_LINUX default use
cursor( For change state TextFieldTTF::setCursorUse )
Desktop implement dispatchControlKey
WinRT support key repeat and implement dispatchControlKey

### CODE REVIEW

**Comment by perminovVS** [comment]
Example use: http://youtu.be/g6jpmaip1fY

**Comment by pandamicro** [comment]
@zilongshanren @WenhaiLin Please take a look at this PR

**Comment by felixjingga** [comment]
Hi @perminovVS is this support ios and android? because the youtube version is showing desktop version. is this the TextField that exists within ui namespace?

**Comment by perminovVS** [comment]
@felixjingga yes, but it is disabled by default( Use TextFieldTTF::setCursorUse for enable).
For mobile not implement control key, cursor show worked, but you can use set cursor position, on touch event( Use TextFieldTTF::setCursorFromPoint )

**Comment by perminovVS** [comment]
@felixjingga >is this the TextField that exists within ui namespace?
No, for TextFieldTTF.
ui::TextField is wrapper on TextFieldTTF.

**Comment by zilongshanren** [comment]
@perminovVS 
I have tested on Mac platform, the are some issues I found:
1. The cursor don't blink on default
2. When use arrow key to move cursor position, it will generate some weird characters.

qq20150828-1 2x

**Comment by perminovVS** [comment]
@zilongshanren thank, you tested TextFieldTTF or ui::TextField ?

**Comment by zilongshanren** [comment]
@perminovVS 
I have tested both and they all have this issue.

**Comment by perminovVS** [comment]
@zilongshanren please see, you merged CCLabelTextFormatter.cpp ?

**Comment by zilongshanren** [comment]
@perminovVS  
Yes, I clone a local copy of your branch.

**Comment by perminovVS** [comment]
TextFieldTTF not always use TTF.
By default no create TTF Label, use LabelType::STRING_TEXTURE
Text cursor work only TTF.

I change TextFieldTTF::initWithPlaceHolder for check exist ttf by fontName and
setTTFConfig.

@zilongshanren test it, please

**Comment by 0xJimmyBeh** [comment]
@perminovVS 

So great that we can have cursor support on TextFieldTTF.

Would it work with Cocos2d-JS JSB on ccui.TextField?

**Comment by perminovVS** [comment]
@Zinitter yes, if have auto implement. I not test it, not use js.

**Comment by 0xJimmyBeh** [comment]
@perminovVS 
That's great! It is a good feature that i'm waiting to implement in ccui.TextField.

@pandamicro 
Do the features added to Cocos2d-X would auto generated the JSB by the system now?
If not, can we enjoy this feature with Cocos2d-JS in v3.9?

Thank you.

**Comment by zilongshanren** [comment]
Sorry @perminovVS 
I missed your comments. Could you please fix the merge conflicts and I will test it after that.
Thanks.

**Comment by pandamicro** [comment]
@perminovVS  Can you fix the conflict ? We are about to submit a version of v3.9 to our QA team tomorrow, so it will be great if this PR can get merged before that

**Comment by perminovVS** [comment]
@zilongshanren @pandamicro ok, do it.

**Comment by perminovVS** [comment]
new version #13903

**Pull request closed without merging**
