### PR TITLE
V4 Update Angle to support gl_PointSize on Windows Phone 8.1

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates Angle to ddbf057c52. This version of Angle correctly supports gl_PointSize on Windows Phone 8.1. Shader compilation is also faster due to threaded parallel compilation of vert and frag shaders.

https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/109

### CODE REVIEW

**Comment by stammen** [comment]
@andyque I need the v4-develop download-deps.py updated to version 10 in order for this to build. The zip files does not yet exist.

==> Prepare to download external libraries!
==> Ready to download 'v4-deps-10.zip' from 'https://github.c
==> Error: Could not find the file from url: 'https://github.
==> Http request failed, error code: 404, reason: Not Found

**Comment by zilongshanren** [comment]
@stammen 

I will update the v4-deps-10.zip later. Because I also have some package need to be updated.
Sorry for the inconvenience.

**Comment by stammen** [comment]
@andyque  Thanks for the update.

**Comment by zilongshanren** [comment]
hi, @stammen 

I found that the v4-develop branch couldn't pass the Windows-universal slave. 
Could this patch solve the problem?

Maybe you need upgrade "external/config.json" in this PR.

thanks.

**Comment by zilongshanren** [comment]
@stammen 
Now the v4-deps-10.zip is ready to use.

**Comment by stammen** [comment]
@andyque I updated external/config.json to version 10 and merged in the latest v4-develop code. Thanks for preparing the v4-deps-10.zip.

**Comment by zilongshanren** [comment]
@stammen  oops, my upgrade broke your PR. @ricardoquesada can you help me to merge this PR?

**Comment by zilongshanren** [comment]
@stammen  @ricardoquesada  sorry guys, maybe it is better to cherry pick your commit in my PR

**Comment by zilongshanren** [comment]
@stammen 
I have cherry-picked your commit at https://github.com/cocos2d/cocos2d-x/pull/10951

@ricardoquesada   When my PR is ready, please merge it. thanks.

**Comment by zilongshanren** [comment]
hi, @stammen  This PR could be closed now.

**Pull request closed without merging**
