### PR TITLE
fix CCARRAY_FOREACH use wild pointer

### PR DESCRIPTION
**Pull request by vizee**

### CODE REVIEW

**Comment by minggo** [comment]
Could you please add a test case for it?
Thanks.

**Comment by vizee** [comment]
should i add the test to BugTest?

**Comment by vizee** [comment]
```
// 1. fill pArray
CCArray * pArray = CCArray::createWithCapacity(2);
for (int i = 0; i < 2; i++) {
    CCObject * pObject = new CCObject();
    pObject->autorelease();
    pArray->addObject(pObject);
}
// 2. enumerate
CCObject * pItem;
unsigned int id = pArray->objectAtIndex(0)->m_uID;
CCARRAY_FOREACH(pArray, pItem) {
    CCLOG("%p", pArray->data->arr);
    CCLOG("%d", pItem->m_uID);
    // 3. add new object in some case
    if (pItem->m_uID == id) {
        CCObject * pObject = new CCObject();
        pObject->autorelease();
        pArray->addObject(pObject);
    }
}
```

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
I run your pasted codes on v2, not crash happened.

**Comment by minggo** [comment]
Any thought?

**Comment by vizee** [comment]
Have you try it in windows?

**Comment by minggo** [comment]
No. It only happened on windows?

**Comment by vizee** [comment]
HeapFree释放内存后会把内存设置0xfeeefeee, 所以野指针指向了一个错误的内存, 我不知道Linux下是怎么处理释放后的内存

**Comment by minggo** [comment]
Thanks for the PR. V2 is in maintain mode, only merge very critical bugs, so i will close this PR.

**Pull request closed without merging**
