### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by super626**
1. clamp asin value to [-1,1]
2. sync RenderState::StateBlock

### CODE REVIEW

**Comment by pandamicro** [comment]
What problem does this PR solve ?

**Comment by super626** [comment]
Euler angle is NaN when update Euler angle from quaternion and asin value is not between -1 and 1 by accident.

**Comment by pandamicro** [comment]
@dabingnn Please review

**Comment by dabingnn** [comment]
@super626 Could you please give a case for the bug?
EG,if a quaternion q = XXXX, the Euler angle would be NaN.

**Comment by super626** [comment]
(cocos2d::Quaternion) $1 = (x = 0, y = -0.707106829, z = -0, w = 0.707106829)
2.f \* (w \* y - z \* x) = $3 = -1.00000012

0.707106829 equals sqrtf(2) / 2.

**Comment by super626** [comment]
@dabingnn @pandamicro

**Comment by dabingnn** [comment]
Thanks, it seems that the Nan happens because of the float precision problem. We need to fix it.
Besides of this, I suggest we normalise quaternion when user call `Node::setRotationQuat()` with a non-normalised quaternion.

**Pull request merged**
