### PR TITLE
change the resolution size of js template to (960 * 640) ,consistent with other templates

### PR DESCRIPTION
**Pull request by GuoLunHao**

### CODE REVIEW

**Comment by GuoLunHao** [comment]
@xiaofeng11 @pandamicro

**Comment by pandamicro** [comment]
No problem for me

**Comment by GuoLunHao** [comment]
[ci rebuild]

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Pull request merged**
