### PR TITLE
UserDefaultData based on ValueMap store 

### PR DESCRIPTION
**Pull request by perminovVS**
UserDefault very slow, each call need read / write and parse xml file.
Delegate makes it possible to use other variants.

UserDefaultData stores user variables on ValueMap.
Get and Set is fast.
Loading data once, save on demand(use standart metod UserDefault::flush)
For call UserDefaultData::makeCurrentUserDefault() use on standart
UserDefault(Delegate UserDefault to new UserDefaultData )

Supports different ways to store( make you store based on
DataStoreDelegate, and set it UserDefaultData::setDataStoreDelegate)

Default data store based on standart UserDefault xml file, see
DataStoreXml in CCUserDefaultData.cpp

### CODE REVIEW

**Comment by minggo** [comment]
@perminovVS 
The design seems good.

I agree that make UserDefault extendable, but i think it is better to let developers to add UserDefaultData if they need.

**Comment by perminovVS** [comment]
@minggo 
Old version is very slow, and need other code for android(CCUserDefault-android.cpp) and ios(CCUserDefault-apple.mm).
New version(UserDefaultData) support delegate store(UserDefaultData::setDataStoreDelegate), and need implementation DataStoreAndroid and DataStoreIos if incorrect work DataStoreXml.

I propose to leave both options, testing, implement Android and Ios and in the future to make UserDefaultData default.

please see other request: #10983 #10911 #10910

**Comment by minggo** [comment]
UserDefault is not a small memory-based database. It will record all settings permanently. Because some it will lost data sometimes on iOS, so we replace xml with NSUserDefault on iOS and SharedPreference on Android.

**Comment by perminovVS** [comment]
well understand.
Recreate request only "UserDefault support delegate" ?

**Comment by minggo** [comment]
Yep, may be.
But the developer should implement all functions, so what's the difference between `delegate` and `create your own database` :)

**Comment by perminovVS** [comment]
new UserDefaultData based on ValueMap delayed up to support the implementation of android and ios. 
UserDefault only setDelegate see #11499

**Pull request closed without merging**
