### PR TITLE
Port Cocos2D-X to Qt 5 (develop branch)

### PR DESCRIPTION
**Pull request by thp**
This is basically the same as pull request #3225, but rebased against the "develop" branch and fixed so that it builds with all the changes in "develop".

### CODE REVIEW

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
@thp 
Could you please write a `how to` document [here]"http://www.cocos2d-x.org/projects/cocos2d-x/wiki"?
Thanks.

**Comment by ricardoquesada** [comment]
I tried to build it using QT Creator and I got this error message at compile time:

```
/home/riq/progs/cocos2d-x/cocos2dx/platform/qt5/CCGL.h:4: error: GLES2/gl2.h: No such file or directory
```

Any idea? thanks.

**Comment by thp** [comment]
@minggo Yes, I'll try to add a howto soon to that wiki page.

@ricardoquesada Right now it's tailored towards mobile platforms and GLESv2 on the Desktop. If you change it to "GL/gl.h", you should be able to compile it against Desktop GL as well.

**Comment by thp** [comment]
Mini-Howto added to the wiki: http://www.cocos2d-x.org/projects/cocos2d-x/wiki/Qt_5_Environment_Setup

**Comment by minggo** [comment]
Thanks @thp.

@thp said

> > @ricardoquesada Right now it's tailored towards mobile platforms and GLESv2 on the Desktop. If you change it to "GL/gl.h", you should be able to compile it against Desktop GL as well.

I think support desktop platforms is important. Many developers said they wanted to use it to create tools. And i think it is easy to control include which header file. Right?

**Comment by ricardoquesada** [comment]
@thp 
Thanks.

I replaced `GLES2/xxx` with `GL/glew.h`. It compiled a few more files with that change, but it failed in CCApplication.h with the following errors:

Error 1:

```
/home/riq/progs/cocos2d-x/cocos2dx/platform/qt5/CCApplication.h:67: error: 'ccLanguageType' does not name a type
```

Error 2:

```
/home/riq/progs/cocos2d-x/cocos2dx/platform/qt5/CCApplication.h:84: error: 'TargetPlatform' does not name a type
```

I guess those errors happen because `CCApplication` was not updated to use the new `enum class` variables.

Regarding gles20 vs gl, what do you mean by "tailed for mobile platforms" ? Can I compile an iOS or Android build ? If so, how ?
And which desktops support gles20 ? Thanks.

**Comment by thp** [comment]
@ricardoquesada See https://github.com/cocos2d/cocos2d-x/pull/3345 for the build errors.

Desktop platforms (on Linux) have libGLESv2 if you install them from Mesa (http://www.mesa3d.org/opengles.html).

**Comment by ricardoquesada** [comment]
Thanks.
I uploaded the project (using `develop` from a few minutes ago) and I installed I installed libgles2-mesa-dev (Ubuntu 13.04), and I got his error:

```
/usr/include/GL/gl.h:872: error: declaration of C function 'void glClearDepthf(GLclampd)' conflicts with
```

I tried to comment out the definition of `glClearnDepthf` in CCGL.h, but if I do that, then other parts of cocos2d-x will complain because `glClearDepthf` won't be defined.

The thing is that `glClearDepth` is being defined in `QOpenGLContext`

Any idea ? thanks.

**Comment by thp** [comment]
Yes, you have to build Qt 5 against the same OpenGL variant (Desktop or ES) that you plan to use in your library. To build Qt 5 against Desktop GL, use `-opengl desktop` in configure, or use `-opengl es2` to build against Mesa's GL ES 2.

**Comment by cfclavijo** [comment]
Hello Guys, I know this is not the right place for presentations, anyway, I'm Carlos and this is what I found
Build Qt 5.1, download the everywhere version
./configure -opengl es2
make -j4
sudo make install (by default it will be installed into /usr/local/Qt-5.1.0)

In order to build cocos2dx with qt it was necessary to modify platform/qt5/CCGL.h

> #ifndef **CCGL_H**
> #define **CCGL_H**
> #define glClearDepth glClearDepthf
> #include `<GLES2/gl2.h>`
> #include `<GLES2/gl2ext.h>`
> #define GL_DEPTH24_STENCIL8       GL_DEPTH24_STENCIL8_OES
> // android defines GL_BGRA_EXT but not GL_BRGA
> #ifndef GL_BGRA
> #define GL_BGRA  0x80E1
> #endif
> #endif // **CCGL_H**

and link the library on cocos2dx/proj.qt5/common.pri, something like
COCOS2DX_SYSTEM_LIBS += -lfontconfig -lfreetype -lGLESv2 (on fedora this is the name, I don't know on ubuntu how is it)

finally copy the resources to the directory where the executable was generated.

The examples starts but they do not read the mouse input, I don't know if it's because the gles2 workaround or what.

**Comment by ricardoquesada** [comment]
thanks @thp 

I didn't have time to continue playing with QT5 + cocos2d-x in the past days, but I think by default it needs to "just work". Either with gles20 or Desktop GL, but by default, provided that you installed the required libraries, it should compile and run OK.

I will try it again in a few days (or weeks).

thanks.

**Comment by thp** [comment]
@cfclavijo Can you provide a patch for the changes you needed to get it running?

**Comment by akof1314** [comment]
thanks @thp 
can you change the proj.qt5 to support Qt 5 for Windows MinGW (Qt Creator )?

**Comment by thp** [comment]
Sorry, don't have a Windows machine, so can't really change it - does it not work by default? Also, the Qt 5 port might have some Linux-specific (or at least Unix-specific) customizations, so for Windows, you might be better of using the official Windows port of Cocos2D-X.

**Pull request merged**
