### PR TITLE
Refactor audio engine module, replace backend with OpenAL for android platform.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by drelaptop** [comment]
many checks failed, even Mac and iOS, strictly it should only have effect on android build.

**Comment by halx99** [comment]
let's check.

**Comment by crazyhappygame** [comment]
@halx99 what exactly is changed here? It seems like you touch all platforms. Is it possible to split to few smaller pull requests?

**Comment by halx99** [comment]
You are right, I will split to few smaller pull requests.

**Comment by crazyhappygame** [comment]
And what will be in those few smaller pull requests? :)

**Comment by halx99** [comment]
Let's do android only.

**Comment by crazyhappygame** [comment]
Why Android? What is wrong, what you would like to fix it? 
We have problem with Linux fmod - is not open source. Could you start with Linux?

**Comment by halx99** [comment]
@drelaptop see the new PR: https://github.com/cocos2d/cocos2d-x/pull/18961,  BEFORE the 3rd party libs update, ci check can't sucess.
@crazyhappygame The original implentation of android does not support streaming mode, and have some issues, such as deadlock when play/stop music frequently. After finish android, may continue work for Linux.

**Pull request closed without merging**
