### PR TITLE
cocos2d/cocos2d-js#1658: Fix js_load_remote_image issue with multithread

### PR DESCRIPTION
**Pull request by pandamicro**

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Test done on Mac, iOS, Android

@jianglong0156 Please review and test it on windows

**Comment by pandamicro** [comment]
Test done on Mac, iOS, Android

**Comment by jianglong0156** [comment]
test over in win32 and wp8.1.. the remote cache test fail to load remote texture. releate issue:https://github.com/cocos2d/cocos2d-x/issues/12183

**Comment by pandamicro** [comment]
Thank you, the other issue will be fixed later

**Pull request merged**
