### PR TITLE
add destroyInstance for ScriptHandlerMgr

### PR DESCRIPTION
**Pull request by jinyuliao**
prevent vld complain memory leak

### CODE REVIEW

**Comment by dumganhar** [comment]
Thanks for your contribution.
And I don't know where should `ScriptHandlerMgr::destroyInstance` be invoked?
In the destructor of `AppDelegate`, or `Director::purgeDirector`?
IMO, it needs to be invoked at `Director::purgeDirector`. :)

**Comment by jinyuliao** [comment]
now, i invoke the method in my demo, like this:
class CocosGC
{
public:
    ~CocosGC()
    {
        Configuration::destroyInstance();
        cocostudio::ObjectFactory::destroyInstance();
        ScriptHandlerMgr::destroyInstance();
        ScriptEngineManager::destroyInstance();
        PoolManager::destroyInstance();
    }
};
static CocosGC g_cocosgc;

invoke these method in Director::purgeDirector not always make sense
e.g:
1.in Director::purgeDirector, it will call Configuration::destroyInstance();
2.Director's destructor has been called, it will delete _renderer
3.in the Renderer's destructor it will call Configuration::getInstance(), Configuration now has been alloced again,then vld will give me the message about memory leak

**Comment by dumganhar** [comment]
Correct my mistake:

> IMO, it needs to be invoked at Director::purgeDirector.

Yep, you're right, it should not be at Director::purgeDirector since it's lua relative codes.

**Comment by dumganhar** [comment]
Merged. thanks.

**Pull request merged**
