### PR TITLE
#Use Data::takeBuffer replace deep copy data.

### PR DESCRIPTION
**Pull request by halx99**
see: https://github.com/EsotericSoftware/spine-runtimes/pull/650

### CODE REVIEW

**Comment by minggo** [comment]
thanks

**Comment by ricardoquesada** [comment]
this PR broke spine. it is crashing now :( I'll revert it until we find a solution that doesn't crash.

**Comment by halx99** [comment]
It fetch latest v3 and test, the default spine test case not crash.

**Comment by ricardoquesada** [comment]
@halx99 in which platform did you try it? which test did you try?
I tried it on Mac OS X 10.11 and run Scene3DTest and SpineTest and both crashed on the spine runtime.
I reverted this PR, and those tests started to work again.

**Comment by halx99** [comment]
@ricardoquesada I run the win32.sln at Windows 10 14393

**Comment by minggo** [comment]
@ricardoquesada i think you should revert it on v3.13 branch too. I will have a test too.

**Comment by minggo** [comment]
@ricardoquesada i tested on Mac 10.11.6, and there is not crash.

**Comment by minggo** [comment]
Oh, the codes in v3.13 is changed too. I will apply the PR and test again.

**Comment by minggo** [comment]
Yep, it will crash on Mac. Let me check why.

**Comment by halx99** [comment]
Think about follow reason:

cocos2d-x getDataFromFile use C global function malloc and pass 1 parameters to alloc memory
The spine MALLOC is defined as _malloc/_free and pass 3 parameters, see follow

```
#ifndef SPINE_EXTENSION_H_
#define SPINE_EXTENSION_H_

/* All allocation uses these. */
#define MALLOC(TYPE,COUNT) ((TYPE*)_malloc(sizeof(TYPE) * (COUNT), __FILE__, __LINE__))
#define CALLOC(TYPE,COUNT) ((TYPE*)_calloc(COUNT, sizeof(TYPE), __FILE__, __LINE__))
#define NEW(TYPE) CALLOC(TYPE,1)
...
/* Frees memory. Can be used on const types. */
#define FREE(VALUE) _free((void*)VALUE)
```

And at windows the `malloc/free` and `_malloc/_free` behavior is same, but on Mac maybe not.

**Comment by ricardoquesada** [comment]
Found the issue. The culprit was this line:

``` c++
return (char*)(data.takeBuffer((ssize_t*)length));
```

`length` is `int`. You cannot convert it to `ssize_t` since `ssize_t` might be bigger in certain platforms, specially in 64-bit platforms.

**Pull request merged**
