### PR TITLE
software pvr decompression support

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by dumganhar** [comment]
It's really an `awesome` feature.
But how could i test it?

**Comment by newnon** [comment]
you can make windows or linux or android project and just load any pvr compressed image and you will see it on screen

**Comment by dumganhar** [comment]
OK, thanks. I'll test it.

**Comment by dumganhar** [comment]
Hi @newnon ,
I tested this patch, but unfortunately, `PVRTDecompressPVRTC`  was never invoked.
I used `cpp-tests/Texture2DTest` which contains lots of test for PVR format.

**Comment by newnon** [comment]
ok i'll see on this demo may be a loose some code than making branch with this feature

**Comment by dumganhar** [comment]
OK, thank you.

**Comment by newnon** [comment]
done

**Comment by dumganhar** [comment]
Thanks. I'll check it again.

**Comment by newnon** [comment]
and does it works?

**Comment by dumganhar** [comment]
The following tests could not work, i tested it on Mac.
￼
0f62ea56-407d-4284-83bc-6492a46d7c95

screen shot 2014-03-25 at 9 51 15

screen shot 2014-03-25 at 9 51 40

**Comment by newnon** [comment]
fixed

**Comment by dumganhar** [comment]
Thanks. I'm testing it.

**Comment by newnon** [comment]
every thing ok or some other problems?

**Comment by cocosQA** [comment]
Dear newnon:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6441
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
