### PR TITLE
Full unicode support

### PR DESCRIPTION
**Pull request by newnon**
Full range unicode support including emoji symbols

### CODE REVIEW

**Comment by minggo** [comment]
Awesome PR. Could you please add a test case for emoji symbols?

**Comment by newnon** [comment]
sorry may be later i'have too much work on my job.

**Comment by newnon** [comment]
emoji test

**Comment by minggo** [comment]
@newnon thanks, i tested on Mac, it seems the emoji font loses color information
screen shot 2017-02-06 at 9 50 29 am

**Comment by newnon** [comment]
No it is just black & white emoji font
To support colour emoji font you need to compile freetype with png support and some small fixes in font rendering classes. I have tried this and it is possible. May be you can ask man who responding for libraries to add png support to freetype?

**Comment by minggo** [comment]
Thanks, yep, i think we should rebuild freetype with png support in future.

**Comment by sbrednikhin** [comment]
What is the status of freetype rebuilding& Wright now it looks like it cant render color emoji.

**Pull request merged**
