### PR TITLE
Setting _viewPortRect for GLViewImpl::initWithRect on desktops.

### PR DESCRIPTION
**Pull request by ericmux**
Please read #9821.

### CODE REVIEW

**Comment by minggo** [comment]
@huangshiwu 
Please take a look?

**Comment by ghost** [comment]
@ericmux Thank you for your PR. Yes the problem is exist indeed, but the engine still work well for the touch event handle have already consider this situation.Does some thing wrong caused by this? If not I think we don't need to merge the PR for we don't sure if it will cause some other side-effects.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Yep, i agree with @ghost, so close this PR.

**Pull request closed without merging**
