### PR TITLE
add search path to simpleAudioEngine in WinRT and WP8.1

### PR DESCRIPTION
**Pull request by zilongshanren**
This issue fixed https://github.com/cocos2d/cocos2d-x/issues/10389

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by stammen** [comment]
@minggo @andyque This pull request breaks the build. See http://stammen.no-ip.info:8080/job/v4-develop/20/

   8>E:\Jenkins\jobs\v4-develop\workspace\projects\MyGame\cocos2d\cocos\2d\libcocos2d_8_1\libcocos2d_8_1\libcocos2d_8_1.Shared........\audio\winrt\SimpleAudioEngine.cpp(84): error C2653: 'FileUtils' : is not a class or namespace name [E:\Jenkins\jobs\v4-develop\workspace\projects\MyGame\cocos2d\cocos\2d\libcocos2d_8_1\libcocos2d_8_1\libcocos2d_8_1.Windows\libcocos2d_8_1.Windows.vcxproj]

Did you forget to update the Universal App projects?

**Comment by minggo** [comment]
@stammen 
Sorry.
We will fix it.

**Comment by stammen** [comment]
We are still working on getting a build machine for Windows Phone/Store cocos2d-x that you can access.

**Comment by minggo** [comment]
Thanks.
It is better that we cover WP platform in jenkins.

**Comment by linshun** [comment]
@stammen thanks for offering cocos2d-x a Jenkins node for Windoes phone compiling. @Andyque will work on it with you guys. Thanks.

**Comment by minggo** [comment]
@stammen
It is fixed in #10426.

**Comment by zilongshanren** [comment]
Thanks @stammen 
If we could get a WP8 Jenkins node that would be great.  If the build machine is ready, please email me. Thanks.

**Pull request merged**
