### PR TITLE
CCImage.cpp: initWithS3TCData() - Allow non-mipmapped textures

### PR DESCRIPTION
**Pull request by wefiends**
Currently, s3tc compressed textures with no mipmaps fail to load due to missing the appropriate PixelFormat, since it is only set when loading mipmaps. 

This patch sets the pixel format before mipmap loading (if s3tc hardware support is present).

### CODE REVIEW

**Comment by dumganhar** [comment]
@boyu0, what's your opinion about this PR?

**Comment by boyu0** [comment]
I think `_numberOfMipmaps` value is equal to 1 when s3tc has no mipmaps. it won't be less than 1. But I'm not sure of this, I didn't find any explanation in internet.
But if so, I think set `_numberOfMipmaps` to 1 is a better idea.

**Comment by wefiends** [comment]
DXT1/5 dds files with mip maps disabled that are created with the Squish library (used by Nvidia SDK) or Crunch have their mipmaps set to zero (which is why they failed to load).

Since the PixelFormat is per Image/Texture, is there any reason to reassign _renderFormat for every mipmap?

**Comment by boyu0** [comment]
@wefiends Thanks for reply.
No, it's not. But if you want move this outside of `for` loop, I think it's better to add an `else` part and move `_renderFormat = Texture2D::PixelFormat::RGBA8888;` outside too.
Set `_numberOfMipmaps` to 1 can force program go inside `for` loop once, it can go to `else` part and decode image data for which device doesn't support s3tc format. I think `_numberOfMipmaps` is equal to 0 or 1 make no difference, and we deal with them as the same in `Texture2D`.

**Comment by wefiends** [comment]
I did what you suggested. 
- Moved the `_renderFormat` assign for software decode out of the `for` loop.
- `_numberOfMipmaps` is forced to 1 if the DDS header reports 0. Needed for software decode. I think this is the correct behavior anyways.

Tested and Working (DXT5 DDS with mipmaps disabled):
- Mac OS 10.9 (gl.supports_S3TC: true)
- iPhone 4S - iOS 7 (gl.supports_S3TC: false)
- iPad 3rd Gen - iOS 6.1.3 (gl.supports_S3TC: false)

You can download the texture I used [here](https://dl.dropboxusercontent.com/u/39502/hud.dds.gz).

**Comment by boyu0** [comment]
Great! Thanks very much!
@dumganhar I have tested it, I think it's ready for merge.
@wefiends I want add a test case for this bug in TestCpp, and I want use the image your provide, Is that ok for you?

**Comment by dumganhar** [comment]
Thanks.

**Comment by wefiends** [comment]
@boyu0 Sure, go ahead. Thanks for your help.

**Comment by boyu0** [comment]
The PR add this test case is: https://github.com/cocos2d/cocos2d-x/pull/5414
@wefiends Thanks for the image :)

**Pull request merged**
