### PR TITLE
Update Reference plugin-x

### PR DESCRIPTION
**Pull request by giuslape**

### CODE REVIEW

**Comment by minggo** [comment]
@giuslape 
Why update it?
I am not sure if plugin-x is ready to update or not.

@darkdukey
Is it ready to update plugin-x?

**Comment by darkdukey** [comment]
@giuslape 
Thanks, I'll take a look at this one.

**Comment by giuslape** [comment]
@minggo 
This update solves compiling errors on HelloSamples Android project

**Comment by minggo** [comment]
Unable to checkout '9c803c7c6d95f00f4ddc8d7c939554cea3811297' in submodule path 'plugin'

Is it a correct commit?

**Comment by darkdukey** [comment]
I fix the submodule, this pr looks good. seems the build server have some issue though.

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
