### PR TITLE
Makefiles cleanup

### PR DESCRIPTION
**Pull request by Lucretia**
Hi, can you take a look at these changes and possibly implement them in the master?

I modified the makefile's because I'm on 64-bit and using the native libs was better for me.

### CODE REVIEW

**Comment by minggo** [comment]
Thank you.
I think int is big enough, because it is used as the index, not used for address.

**Comment by Lucretia** [comment]
Int is not big enough as it fails the build on a 64-bit machine.

**Comment by minggo** [comment]
Linux port is used for developing, so I don't think it is valuable to modify logic code of engine to make it work on 64-bit.

**Comment by Lucretia** [comment]
I do, I'm using it to develop my game and then I test on Android (and later iOS). So, I really want this to work properly.

I also find it strange that the OGLES libs aren't used on Linux like they are on the Win32 version.

**Pull request closed without merging**
