### PR TITLE
修正Linux下中文显示问题

### PR DESCRIPTION
**Pull request by CaiCQ**
修正Linux下中文显示问题

### CODE REVIEW

**Comment by minggo** [comment]
@CaiCQ
How to reproduce the issue?
Because there is a test case named `Node:Label-New API`. And it can show Chinese characters correctly. 
It can't show some Chinese characters in `Node:Label-Old API`, but this PR doesn't fix it.

**Comment by CaiCQ** [comment]
这是解决中文显示不全问题，中文变方块是因为系统没对应字体，不是该问题

**Comment by minggo** [comment]
How to reproduce it?
Could you paste some demo codes?

**Comment by minggo** [comment]
PS: Please use English in future.
Because other developers will join the discussion.

Thanks.

**Comment by CaiCQ** [comment]
## example：

``` c++
    auto font = LabelTTF::create();
    font->setFontName("文泉驿微米黑");
    font->setFontSize(32);
    font->setString("中文显示不全问题例子");
    this->addChild(font);
```

**Comment by minggo** [comment]
Thanks.

**Pull request merged**
