### PR TITLE
fix printf compile error in Linux

### PR DESCRIPTION
**Pull request by yvanc**
Fixed compile error when performing make under Ubuntu linux

### CODE REVIEW

**Comment by dumganhar** [comment]
Which version of Ubuntu are you using? We are using `Travis` for CI. You could refer to 
https://travis-ci.org/cocos2d/cocos2d-x/builds
And there aren't any problems when compiling.

**Comment by dumganhar** [comment]
Travis CI is using `Ubuntu 12.04 64bit`.

**Comment by yvanc** [comment]
Linux mint 14 32-bit

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/4908/files.
Thanks.

**Pull request closed without merging**
