### PR TITLE
v3.11 Windows 10 UWP fixes 

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates the Windows 10 UWP project files to support cocos2d-x v3.11. This pull request depends upon the updated chipmunk libs in the pull request https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/206

This PR does the following:

Adds missing files to the Windows 10 UWP projects
Updates the chipmunk include path
Updates the Windows 10 app framework to pass WACK testing
external/config.json is updated to v3-deps-84.

### CODE REVIEW

**Comment by stammen** [comment]
@ricardoquesada @pandamicro Why am I not allowed to look at the build results?

http://45.56.80.45:8080/job/ccs-pr/3984/

This site can’t be reached

45.56.80.45 refused to connect.

**Comment by ricardoquesada** [comment]
@stammen No idea :(
I can see them here:
http://45.56.80.45:8080/job/ccs-pr/3984/node=win32_bak/console

and I'm not even logged in.

**Comment by ricardoquesada** [comment]
@minggo this is another PR that we should include for v3.11 (added milestone)

**Comment by stammen** [comment]
Please hold off pulling this request. I am still fixing damage caused by pull request https://github.com/cocos2d/cocos2d-x/pull/15281

**Comment by stammen** [comment]
I am going to resubmit this pull request with the commits cleaned up.

**Comment by ricardoquesada** [comment]
@stammen ok. thanks.

**Comment by minggo** [comment]
@stammen may i know when will you put a new pull request?
Thanks.

**Comment by minggo** [comment]
@ricardoquesada @stammen I created #15307 for new pull request.

**Comment by stammen** [comment]
@minggo @ricardoquesada fixed in PR https://github.com/cocos2d/cocos2d-x/pull/15311

**Pull request closed without merging**
