### PR TITLE
fix app crash when dimensions too large

### PR DESCRIPTION
**Pull request by ghost**
app will crash when video dimensions too large

### CODE REVIEW

**Comment by zilongshanren** [comment]
@VindroidH 
Thanks, how could I reproduce this issue?

**Comment by ghost** [comment]
@zilongshanren 
You can create a videoplayer then use **videoplayer->setScale()** to reproduce this issue.

**Comment by zilongshanren** [comment]
@VindroidH 
Thanks, I will give it a test.

**Comment by minggo** [comment]
I add `_videoPlayer->setScale(1.5);` in `UIVideoTest.cpp`, not crash on huawei p9.

**Pull request closed without merging**
