### PR TITLE
Fix for win32 release mode build in VS2019

### PR DESCRIPTION
**Pull request by rh101**
This is to address the issue described in #19836

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@rh101 could you explain what and how it is fixed?
If this is VS compiler error could you provide link to compiler error?

**Comment by rh101** [comment]
The explanation is in the issue I linked: https://github.com/cocos2d/cocos2d-x/issues/19836

The compiler freezes when it is trying to optimize a certain section of code.  All that this fix does is disable global optimization ("g" option in the as described here: https://docs.microsoft.com/en-us/cpp/preprocessor/optimize?view=vs-2019) for the ControllerImpl class in CCControllers-linux-win32.cpp.  Other optimizations stay on (like speed optimization etc).  The global optimization is turned back on at the end of that class declaration.

At the moment /O2 flag is used for release mode optimization, and as detailed [here](https://docs.microsoft.com/en-us/cpp/build/reference/o1-o2-minimize-size-maximize-speed?view=vs-2019), it is equivalent to:

```
/O2 (Maximize Speed) turns on /Og /Oi /Ot /Oy /Ob2 /GF /Gy
```
The /Og ([global optimization](https://docs.microsoft.com/en-us/cpp/build/reference/og-global-optimizations?view=vs-2019)) is the one that is causing an issue here for the ControllerImpl class.

The compiler freezing is the same as what this post describes:
https://developercommunity.visualstudio.com/content/problem/525689/vs2019-x64-x86-cross-compiler-freeze-compiling-som.html

Quote from that site: "This is an issue with a newer optimization that can have a O(n^2) behavior in certain cases which will be fixed in a future update, most likely VS 2019 update 2."

**Comment by crazyhappygame** [comment]
Thank you for explanation.

I think that we should refactor function with more than 4500 lines of code. It is bad habit to have such long functions...

One my idea is to create const table. And than loop instead of repeating:
```
deviceName = "device name";
buttonInputMap.clear();
axisInputMap.clear();
//Init
// Add the controller profile to the map
s_controllerProfiles.insert(std::make_pair(deviceName, std::make_pair(buttonInputMap, axisInputMap)));
```

**Comment by rh101** [comment]
I think your idea is good, since yes, it's an excessively long function.  Refactoring it may actually fix the optimization issue, so there would be no need to apply this work-around I've submitted.

Also, I noticed this comment in the code:
```
//FIXME: Once GLFW 3.3 is bundled with cocos2d-x and no extra
//controllers have been added here, remove all the code here.
```

Now there is another issue logged #19610 which is exactly about updating to GLFW 3.3, so if that is done, then I guess the code in that function can be removed?

**Comment by crazyhappygame** [comment]
Could you close this PR and refactor more than 4500 long function in new PR?

**Comment by rh101** [comment]
Unfortunately, I can't simply take time away from working on my own projects at the moment, so I'm not sure I'll be able to dedicate time to figuring out what this 4500 function does and how best to refactor it.   

Also, I'm not sure that closing this PR is a good idea, since it's a valid fix that affects no other part of the code, and perhaps it's best to leave it open for now in case no-one gets around to refactoring that code.  In addition to that, refactoring the code is not a guarantee that the compile issue will be fixed.  

Also, given this is somehow related to the use of GLFW 3.3, is Cocos2d-x going to be updated to use that version?

**Comment by crazyhappygame** [comment]
OK. I see your point. But please do not commit this. I have a filling that soon VS 2019 will be fixed and than we will have unneed fix for VS 2019.1 in cocos2d-x code.

If you do not have time I will try to this refactoring in the meantime ...

**Comment by rh101** [comment]
I'm going to close this pull request because I need to fix some issues with my github repo. I'll recreate it later if required.

**Pull request closed without merging**
