### PR TITLE
Fix sourcePosition bug for ParticleSystem.

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by minggo** [comment]
Sounds reasonable, is there any test case to reproduce it?

**Comment by halx99** [comment]
You can see, actually, the old code will be missing sourcePosition value from .plist file, and always be ZERO.

**Comment by Dimon4eg** [comment]
Details here at the end
[http://discuss.cocos2d-x.org/t/x-studio365-a-more-powerful-game-develop-ide-support-particlesystem-editing-ui-editing-adapting-preview-spine-animation-preview-support-lua-debug-edit-syntax-highlight-outlinng/29660/72](http://discuss.cocos2d-x.org/t/x-studio365-a-more-powerful-game-develop-ide-support-particlesystem-editing-ui-editing-adapting-preview-spine-animation-preview-support-lua-debug-edit-syntax-highlight-outlinng/29660/72)

**Comment by dumganhar** [comment]
I don't know whether this change is correct. But this PR breaks the compatibility.
The result of cpp-tests->37:Node: Particles ->  1、2、3、21、22、24、25、27、29、30、31、32、35、36、40、44、46、47、48、49、52` are totally wrong now.

**Comment by dumganhar** [comment]
In 3.15:
image 1
In current v3 branch:
image 2

**Comment by minggo** [comment]
@halx99 i think we have to revert the codes.

**Comment by halx99** [comment]
Does the test case plists specific sourcePosition?

**Comment by halx99** [comment]
@minggo  @dumganhar I have checked, all the test particles has sourcePosition, so the behavior is right. so I think  remove the sourcePosition from test case's particle plists is better.

**Comment by halx99** [comment]
And at ParticleBatchHybrid::onEnter() should call setEmitterPosition to center the particle.

**Comment by minggo** [comment]
@halx99 sorry, did you mean we should just`setEmitterPosition in ParticleBatchHybrid::onEnter()`? Or we should also modify remove `sourcePosition ` in plist files too?

If we should remove `sourcePosition ` to make it work correctly, then it will break compatibility.

**Comment by halx99** [comment]
Yes.

**Comment by halx99** [comment]
because, the particle are not design in any scene/ui editor, so the testcase particle postion  shoud not dependent the plist sourcePosition.
As the particlesystem design, I think the sourcePosition, Node position is different.

**Comment by halx99** [comment]
In the old engine, It seems (+bug) + (-bug) = 0(looks no bug).

**Comment by minggo** [comment]
particle is created by [PartcileDesigner](https://71squared.com/particledesigner).

**Comment by halx99** [comment]
but the sourcePosition is never applied in the old engine.

**Comment by halx99** [comment]
It just a Particle designer, not UI designer.

**Comment by minggo** [comment]
But other developers will meet the same problem as cpp-tests, we can not ask all developers do it as your suggestion. Old engine may not work correctly, but developers use it like that way. Is there any way to fix it and not break compatibility?

**Comment by halx99** [comment]
I think, there are three choice: 
  1. reserved the bug, not break compatibility
  2. fix the engine bug, break compatibility
  3. fix the bug, Add a function for ParticleSystem, enableCompatibleMode(), and the default the compatible mode is enabled in several engine versions in the future, but should mark the function as depecrated.

**Comment by minggo** [comment]
I am not sure if change to
```c++
this->setPosition(Vec2(x,y));
this->setSourcePosition(Vec2(x,y));
```
will work or not.

**Comment by halx99** [comment]
Let'us try it.

**Comment by halx99** [comment]
But I think add a member _compatibleMode to control it is better:
`
if(!_compatibleMode)
{
   this->setSourcePosition(Vec2(x,y));
}
else 
{
   this->setPosition(Vec2(x,y));
}
`

**Comment by halx99** [comment]
the function should be:
 void setCompatibleMode(bool compatibleMode);
 bool isCompatibleMode() const;

**Comment by minggo** [comment]
Sounds reasonable. But don't make it as deprecated, because it will bring warnings.
`setCompatibleMode ` is not clear, may be can change to `setSourcePositionCompatible`

**Comment by halx99** [comment]
ok

**Comment by halx99** [comment]
agree with you

**Comment by minggo** [comment]
could you please send a PR to v3.16, thanks

**Comment by halx99** [comment]
ok, see here: https://github.com/cocos2d/cocos2d-x/pull/18230

**Pull request merged**
