### PR TITLE
BlackBerry project template updates

### PR DESCRIPTION
**Pull request by lewellyn**
- Updated .cproject to use workspace_loc to enable copying the template out of the cocos2d-x tree.
- Updated bar-descriptor.xml to be more modern. Tested with Tablet OS 2.1.0 and BlackBerry 10 (10.1 and 10.2) SDKs.
- Removed now-unneeded empty file.

Note that this commit will likely cause projects to not work with the Tablet OS 2.0.0 tooling, and will almost certainly not work with the now-obsolete 1.0 tooling. Considering that 2.1.0 released in April 2012, there should be no reasons to use a downlevel SDK. These changes improve compatibility with future SDK releases by removing the deprecated `<action>` tags and replacing them with `<permission>` tags.

### CODE REVIEW

**Comment by rcmaniac25** [comment]
It looks good to me. My only worry is that it uses workspace variables for paths. Someone may not have the projects setup in Eclipse for those to be used.

**Comment by lewellyn** [comment]
It's better than the original version, which required copying the template into a specific location under the cocos2dx tree.

Since you need the linked projects configured anyhow for Momentics to build your project (even without my changes), it's a reasonable assumption that the workspace is properly configured (else, one will hit issues before the changes I made).

**Comment by ghost** [comment]
It's definitely a plus for the library to be more workspace-friendly for BB10. I spent a day configuring the original configuration as it was to get it working. The updates for tablet OS 2.1 would also be good to have.

**Comment by lewellyn** [comment]
Can this issue be re-opened? The PR which closed this issue has nothing to do with this issue.

This issue is related to the Eclipse project for BlackBerry 10. The commit which closed the issue has something to do with a Firefox crash.

**Comment by ghost** [comment]
Yes I agree, this was not fixed by the pull request. It's not even for the same platform (Blackberry 10)

**Comment by jerobarraco** [comment]
its a need. Please reopen, this issue is not done. Thanks.

**Comment by ghost** [comment]
I see that Github is living up to its fine reputation for management and quality.

Issue relates to Eclipse.

Issue is closed because of Firefox.

What.  The.  Fuck.

**Comment by PaulBone** [comment]
Closing this issue makes no sense.  There has been no resolution (either
accept or reject).  Closing it from an unrelated commit makes even less
sense.

**Comment by jcarty** [comment]
Any word on this one?

**Comment by dumganhar** [comment]
I don't know why this commit closed this PR

```
closed #3856: Crash when Firefox connects to JSB application.
```

@walzer has re-opened it. I'll test this PR next week. Thanks for the improvements for Blackberry port.

**Comment by dumganhar** [comment]
Thanks. Could you also update other project configuration?

**Comment by lewellyn** [comment]
Thanks for merging this. :)

Which other configurations did you want me to look at?

**Comment by dumganhar** [comment]
For example, `HelloCpp`, `TestCpp`, `HelloLua` and `TestLua`.

**Pull request merged**
