### PR TITLE
fix: release texture in RenderState

### PR DESCRIPTION
**Pull request by ricardoquesada**
memory leak fixed in RenderState

fixes github issue #16155

### CODE REVIEW

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@ricardoquesada i think this test case is hard to test. Can just use reference count to test it, for example

```
assert(reference_count >=2);
```

**Comment by ricardoquesada** [comment]
@minggo you are right.
I could do that if needed. I was just checking it with the debugger and it was releasing it. the thing is that if that same texture was already cached it could affect the ref count.
that's why I chose the "quick & dirty" way to test it. 
I'll improve it later this afternoon.

**Comment by ricardoquesada** [comment]
@minggo new PR here: https://github.com/cocos2d/cocos2d-x/pull/16418

**Pull request merged**
