### PR TITLE
Hide/Show Cursor - FEATURE 8766

### PR DESCRIPTION
**Pull request by Sheado**
Added the ability to hide or show the cursor on desktop builds.

### CODE REVIEW

**Comment by darkdukey** [comment]
Thanks a lot, can you send this pull request for v3 branch as well :)

**Comment by Sheado** [comment]
Hi @darkdukey,

I'm still getting the hang of contributing code. I followed the instructions here: https://github.com/cocos2d/cocos2d-x/wiki/Contributing-to-Cocos2d-x 

Then I used the GitHub app and submitted the pull request to cocos2d:v3
https://github.com/cocos2d/cocos2d-x/pull/10502

Please let me know if I did this wrong and if there's more specific instructions on how to best submit pull requests to cocos2d-x. 

Thanks

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
close this pr since v4 is freezed

**Pull request closed without merging**
