### PR TITLE
[preview] Adds thread pool support

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
This PR is just for preview. Please leave comments if you have any advice or questions.

**Comment by WenhaiLin** [comment]
:+1:

**Comment by zilongshanren** [comment]
@yangws  please take a look at this PR.

**Comment by dumganhar** [comment]
@minggo ,could you please review this PR? I think common threadpool class is a big improvement for Cocos2d-x.

I know this fix may need more polish, but just see whether the design match our needs. :)

**Comment by minggo** [comment]
I will take a look when i have time. This PR may take more time.

**Comment by dumganhar** [comment]
Thank you. :)

**Comment by minggo** [comment]
I have some questions:
- what's the difference from `AsyncTaskPool`
- it seems the class mixed all types of thread pool and use flags to do different things, can use inheritance internally, such as `CacheThreadPool` inherits from ThreadPool, of course `CacheThreadPool` is internally implementation

**Comment by dumganhar** [comment]
> > what's the difference from AsyncTaskPool

AsyncTaskPool just uses only only one thread for a type of task.

``` c++
    enum class TaskType
    {
        TASK_IO,
        TASK_NETWORK,
        TASK_OTHER,
        TASK_MAX_TYPE,
    };
```

It means that `IO` will use one thread, `NETWORK` also use one thread.

ThreadPool shares all threads for tasks.

> > it seems the class mixed all types of thread pool and use flags to do different things, can use inheritance internally, such as CacheThreadPool inherits from ThreadPool, of course CacheThreadPool is internally implementation

Seems a better idea, if in that case, I think the inheritance should not be internal, it should be public. Something like:

``` c++
static CachedThreadPool* newCachedThreadPool(int minThreadNum, int maxThreadNum, int shrinkInterval, int shrinkStep, int stretchStep);
static FixedThreadPool* newFixedThreadPool(int threadNum);
static SingleThreadPool* newSingleThreadPool();
```

BTW, `AsyncTaskPool` is more like `SingleThreadPool` here. :)

**Comment by halx99** [comment]
I think, for client program, multi-threadpool is not necessary.

**Comment by cezheng** [comment]
I'm not sure how good the performance of this implementation is, but I think having a thread pool is definitely good for many asynchronous loading scenario.

iOS has the advantage of libdispatch in its runtime, which is a highly performant thread pool implementation, since it is optimized for apple's hardware.

I tried replacing the async loading code using AsyncTaskPool with `dispatch_async`s in the project I'm currently working on, it gives my a 20%-30% shorter loading time on a dual-core iPhone 5, which is very appealing(Many Android phone have up to 8 cores today, so the performance boost would be even better on these devices).

For Android, libdispatch is ported by PSPDFKit-labs last year: https://github.com/PSPDFKit-labs/libdispatch

But later they moved away from it and switched to boost due to the fact that none of the Android debugging & instrument tools understand the block syntax. (refer to this blog post: https://pspdfkit.com/blog/2016/a-pragmatic-approach-to-cross-platform)

I'm yet to test the actual performance of `boost::asio::io_service` to decide wether to use it or not.

**Comment by minggo** [comment]
I think using an mature framework is better if there is one.

**Comment by halx99** [comment]
I found `CCThreadPool` already add to cocos/audio/android/ by other guy.

**Comment by minggo** [comment]
It is added by @dumganhar, only used in audio engine to have good performance. We can replace it if we found a mature library.

**Comment by dumganhar** [comment]
@halx99 , currently CCThreadPool is only used for AudioEngine of Android platform.
It's internal use only.

**Pull request closed without merging**
