### PR TITLE
fix memory leak cocos studiov2.0 engine v3.3

### PR DESCRIPTION
**Pull request by aeonmine**

### CODE REVIEW

**Comment by aeonmine** [comment]
all of using cocostudio widget, action timeline, csloadder , haven memory leak.

**Comment by darkdukey** [comment]
@pipu can you take a look :(

**Comment by aeonmine** [comment]
fix memory leak for zipUtils

**Comment by aeonmine** [comment]
on windows build an error occurred

FATAL: hudson.remoting.RequestAbortedException: java.net.SocketException: Connection reset

it likes the hudson error 

do i have to send pullrequest again?

**Comment by aeonmine** [comment]
hi darkdukey 

what does [ci rebuild] mean?

**Comment by aeonmine** [comment]
for windows 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
python: can't open file 'tools/jenkins-scripts/pull-request-builder.py': [Errno 2] No such file or directory
python: can't open file 'tools/jenkins-scripts/pull-request-builder.py': [Errno 2] No such file or directory
python: can't open file 'tools/jenkins-scripts/pull-request-builder.py': [Errno 2] No such file or directory

**Comment by aeonmine** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild] will force build server to rebuild

**Comment by darkdukey** [comment]
Probably a bug in the build server.

**Comment by pipu** [comment]
I think that could merge this pull request.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by aeonmine** [comment]
the build server always occur error for windows.
could you please merge this pull request?

**Comment by aeonmine** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Yep, there is an issue of windows build machine.
We are fixing it.
But we should merge this PR until there is not building error.

**Comment by aeonmine** [comment]
[ci rebuild]

**Comment by aeonmine** [comment]
hi minggo the the building was success for all platform could you please marge it?

**Pull request merged**
