### PR TITLE
Win10 UWP and Windows 8.1 fixes for v3.11

### PR DESCRIPTION
**Pull request by stammen**
This pull request updates the Windows 10 UWP and Windows 8.1 Universal project files with the changes needed to support v3.11.

This pull request fixes issue https://github.com/cocos2d/cocos2d-x/issues/15307.

Please note that WebSockets is broken for Windows 8.1 Phone. This will be fixed in another PR.

This pull request also fixes changes to include paths introduced by pull request https://github.com/cocos2d/cocos2d-x/pull/15281

### CODE REVIEW

**Comment by stammen** [comment]
@minggo @ricardoquesada  I am not able to access http://45.56.80.45:8080/job/ccs-pr/3993/ to see the build results. I get a the following error:

This site can’t be reached

45.56.80.45 refused to connect.
ERR_CONNECTION_REFUSED

**Comment by ricardoquesada** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@stammen not sure why you can't access it. Perhaps it is a security setting in your browser doesn't allow you to go to IP addresses ? I can access it without problem and I'm not logged in.

**Comment by minggo** [comment]
@stammen I can access it without login too. And i found  the error on all platforms:

Checking headers in: /android_slave/workspace/ccs-pr/node/android/cocos
platform/win8.1-universal/Cocos2dRenderer.cpp:
    #include "Cocos2dRenderer.h" should be #include "platform/win8.1-universal/Cocos2dRenderer.h"
platform/win8.1-universal/OpenGLES.cpp:
    #include "OpenGLES.h" should be #include "platform/win8.1-universal/OpenGLES.h"
platform/win8.1-universal/OpenGLESPage.xaml.h:
    #include "Cocos2dRenderer.h" should be #include "platform/win8.1-universal/Cocos2dRenderer.h"
    #include "OpenGLES.h" should be #include "platform/win8.1-universal/OpenGLES.h"
platform/win8.1-universal/OpenGLESPage.xaml.cpp:
    #include "OpenGLESPage.xaml.h" should be #include "platform/win8.1-universal/OpenGLESPage.xaml.h"

**Comment by zilongshanren** [comment]
@stammen  Hi, we have cleaned up the header file include.  Only the `$engine/cocos` search path is available now. So every include path should relative to the search path or otherwise it can't pass the jenkins,  because we put a linter script https://github.com/cocos2d/cocos2d-x/blob/v3/tools/coding-style/include-linter.py in CI.

**Comment by stammen** [comment]
@minggo @ricardoquesada These files are specific to the Windows 10 and Windows 8.1 platform only. They should not be linted. The c++ template project files are generated from these files and they become local to the project directory. They should not be forced to have to be the platform/win8.1-universal directory.

The linter needs to be able to handle platform specific project files. Is there no way to exempt some files from the linter?

**Comment by xpol** [comment]
@stammen 

Sorry for that.

Update: Here is the PR fixes it: https://github.com/MSOpenTech/cocos2d-x/pull/190

~~Would you please change the linter https://github.com/cocos2d/cocos2d-x/blob/v3/tools/coding-style/include-linter.py#L46-L50~~

~~from:~~

``` python
    self.exclude = [
      # we are leaving win8.1 and winrt pch.cpp unchanged.
      'platform/win8.1-universal/pch.cpp',
      'platform/winrt/pch.cpp'
    ]
```

~~to:~~

``` python
    self.exclude = [
      # exclude some platform specific files.
      'platform/win8.1-universal/Cocos2dRenderer.cpp',
      'platform/win8.1-universal/OpenGLES.cpp',
      'platform/win8.1-universal/OpenGLESPage.xaml.cpp',
      'platform/win8.1-universal/OpenGLESPage.xaml.h',
      'platform/win8.1-universal/pch.cpp',
      'platform/winrt/pch.cpp',
    ]
```

So that your PR will immediately passed.

**Pull request merged**
