### PR TITLE
Added the ability to set physics debug color of Shapes & Joints

### PR DESCRIPTION
**Pull request by TheCodez**
This pr adds the ability to change the physics debug color of the Shapes fill and outline. 
You can also change this on the PhysicsBody itself to change the color of all its shapes. 
Additionally, you can also set the line and point color of Joints

### CODE REVIEW

**Comment by TheCodez** [comment]
@pandamicro @WenhaiLin any chance to get this into 3.10?

**Comment by WenhaiLin** [comment]
@pandamicro This PR seems good to me.

**Comment by pandamicro** [comment]
@TheCodez, v3.10 can't add any more features, so after merge, it could be published with v3.11

**Comment by pandamicro** [comment]
@xiaofeng11 Please confirm whether we can merge this improvement to v3.11.

**Comment by xiaofeng11** [comment]
@TheCodez Please add a test case for this feature, thanks!
@pandamicro Yes, it can be merge to v3.11 after add a test case for testers can verify the function.

**Comment by TheCodez** [comment]
It has already some examples in the Physicstest, but i can add an extra test.

**Comment by xiaofeng11** [comment]
Hi TheCodez,
We have a testing group verify all new features or functions, when add new features or functions we should provide a testing document to testing group to explain how to confirm it's works fine. So please add an extra test, that will be much helpful for explain how to verify this new feature. Thank you very much.

**Comment by TheCodez** [comment]
@xiaofeng11 @pandamicro OK, added test case.

**Comment by minggo** [comment]
@TheCodez Could you please fix conflict?

**Comment by TheCodez** [comment]
I don't think it's possible anymore to change color on individual shapes as this is now handled by chipmunk.
@newnon you changed to the new chipmunk debug system. Is the above still possible?

**Comment by newnon** [comment]
I'm not sure chipmunk just call primitive call method with Paramus there is some method with which you can set color of this primitives, but it needs some additional research...

**Comment by minggo** [comment]
@TheCodez  i think i have to close the PR, and please send a new one to fix it if needed. thanks.

**Pull request closed without merging**
