### PR TITLE
the ui widget need to refresh size by ignore state

### PR DESCRIPTION
**Pull request by liamcindy**

### CODE REVIEW

**Comment by zilongshanren** [comment]
Hi, @liamcindy 
Why remove the if statement here?
I think it exists only for performance issue. Could you give me a example why we need this fix?

**Comment by liamcindy** [comment]
@andyque We need to refresh widget's size while refresh ignoreSize state

**Comment by zilongshanren** [comment]
ok, thanks @liamcindy 
@minggo We could merge this PR now.

**Comment by minggo** [comment]
@andyque 
Please create a corresponding issue.
Thanks.

**Comment by zilongshanren** [comment]
@minggo 
This PR is not perfect. @liamcindy  will send another PR to fix this problem.

**Pull request merged**
