### PR TITLE
added feature ListView select item by index

### PR DESCRIPTION
**Pull request by AlexanderBykin**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@liamcindy 
please have a look at this PR, thanks.

**Comment by liamcindy** [comment]
@zilongshanren It looks good to be merged.

**Comment by zilongshanren** [comment]
@AlexanderShniperson 
Hi, sorry for the late reply, could you solve the merge conflicts, I'm ready for merging it.

**Comment by AlexanderBykin** [comment]
Hi @zilongshanren, sorry i cant resolve it, because i am not skilled with Git

**Comment by zilongshanren** [comment]
@AlexanderShniperson 
All right, I will do it later.

**Comment by minggo** [comment]
I think this PR include many unneeded commits, so i will close it.

**Pull request closed without merging**
