### PR TITLE
Fixed #12652 Add retain/release for XMLHTTPReqest in JSB

### LINKED ISSUE #12652: cc.loader.getXMLHttpRequest() can't be retain in JSB
cocos js 3.6.1在jsb下 cc.loader.getXMLHttpRequest() 赋值给全局变量后，下次再调用的话，已经被释放，希望能加个类似retain的方法。

### PR DESCRIPTION
**Pull request by pandamicro**

### CODE REVIEW

**Comment by pandamicro** [comment]
Fixed #12652

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by jianglong0156** [comment]
it's ok . can be merge

**Comment by jianglong0156** [comment]
[ci rebuild]

**Pull request merged**
