### PR TITLE
Avoid of type overflow while list size calculation.

### PR DESCRIPTION
**Pull request by sbrednikhin**
If _items container is empty `(length - 1) * _itemsMargin` will be large positive value. 
Using `size_t` causes type overflow and large positive sizes.
Using int will cause negative size values.
Direct check looks like the best way.

### CODE REVIEW

**Comment by drelaptop** [comment]
you said is right, overflow occurs when the container is empty. but I can't sure we have enough reason to modify it, because this situation didn't case any issues. what do you think ? @sbrednikhin

**Comment by sbrednikhin** [comment]
It might look like bad surprise while debugging.
First time I saw it, I thought this is a bug, and spent some time to read code carefully and understand it. Just want to safe some time for others.

**Comment by drelaptop** [comment]
I can't decide which is better, what do you think?  @minggo

**Comment by minggo** [comment]
I think @sbrednikhin makes the codes more clear.

**Review by drelaptop — CHANGES_REQUESTED** [review]
@sbrednikhin Sorry for a long response from the time you make PR, now it has conflicts with the latest code, will you solve it? after that PR will be merged.

**Comment by sbrednikhin** [comment]
It's ok. Everything has being resolved.

**Comment by minggo** [comment]
i will merge it after passing travis

**Comment by drelaptop** [comment]
this PR can be merged @minggo

**Pull request merged**
