### PR TITLE
improve the api doc for node.

### LINKED ISSUE #15100: lots of methods not exists in api reference
hi

im using visual studio and i see lots of (sprite / node) method if i serch for it in the online api reference dosent exists like

setOpacity and setColor

and more i hope to fix it

### PR DESCRIPTION
**Pull request by zilongshanren**
fixes https://github.com/cocos2d/cocos2d-x/issues/15100

### CODE REVIEW

**Comment by zilongshanren** [comment]
@xiaofeng11  please review..thanks.

**Comment by xiaofeng11** [comment]
It's OK, merged. Please update v3-doc branch either, thanks!

**Comment by zilongshanren** [comment]
@xiaofeng11 
The merging of v3-doc branch  could be done later before version release.

**Comment by xiaofeng11** [comment]
OK

**Pull request merged**
