### PR TITLE
Improve Android file system read performance

### PR DESCRIPTION
**Pull request by folecr**
Faster file system read performance on Android!
- Raw filesystem read is approximately 40% faster
- Game startup is approximately 12% faster
- Uses Native AssetManager
- ... Instead of custom unzip code

Tests 
- Tested with https://github.com/folecr/SlideShowFSTest
- Test results are average of 3 runs
- Tested on Galaxy Nexus with Android 4.2.2

Test 1 https://github.com/folecr/SlideShowFSTest/tree/master/samples/Cpp/RawFSTest
- Reads image data using CCFileUtils
- Time taken to read data
  - Before : 297.5 millis
  - After : 125 millis
- Approximately 40% faster

Test 2 https://github.com/folecr/SlideShowFSTest/tree/master/samples/Cpp/SlideShowFSTest
- Creates and displays sprites from image data
- Approximately 12% faster to display all sprites

### CODE REVIEW

**Comment by folecr** [comment]
@mingulov @dumganhar Could you please review before merge?

**Comment by minggo** [comment]
@folecr 
These codes can only run on Android2.3 or upper.
I am not sure if we can give up 2.2.
May be we can discuss it in forum.
What's your opinion?

**Comment by folecr** [comment]
Sure - we can discuss either on github.com or on forum.

**Comment by minggo** [comment]
I have created a thread to discuss it: http://www.cocos2d-x.org/boards/6/topics/26862.

**Comment by folecr** [comment]
I opened a new pull request https://github.com/cocos2d/cocos2d-x/pull/2983

**Pull request closed without merging**
