### PR TITLE
updating for tizen

### PR DESCRIPTION
**Pull request by sukwonsuh**
updating for tizen based on cocos2d-x.3.4

### CODE REVIEW

**Comment by minggo** [comment]
- Why are there so many source codes in `build` folder?
- Could you please add cpp template too?

**Comment by sukwonsuh** [comment]
Why are there so many source codes in build folder?

> Sorry, I'll remove that.
> Could you please add cpp template too?
> Okay, I"ll add cpp-template.

**Comment by QingliWang** [comment]
cpp-template has been created, which named hellocpp.

**Comment by minggo** [comment]
templates/lua-template-default/frameworks/runtime-src/proj.tizen/.cproject (819)
A templates/lua-template-default/frameworks/runtime-src/proj.tizen/.project (50)
A templates/lua-template-default/frameworks/runtime-src/proj.tizen/.tproject (11)
A templates/lua-template-default/frameworks/runtime-src/proj.tizen/shared/res/HelloLua.png (0)
A templates/lua-template-default/frameworks/runtime-src/proj.tizen/src/main.cpp (17)
A templates/lua-template-default/frameworks/runtime-src/proj.tizen/tizen-manifest.xml (7)

@QingliWang 
But i just found these files.

**Comment by WenhaiLin** [comment]
@sukwonsuh I think you should not add the following files:

``` cpp
 tests/cpp-empty-test/proj.tizen/Classes/AppDelegate.cpp
 tests/cpp-empty-test/proj.tizen/Classes/AppDelegate.h
 tests/cpp-empty-test/proj.tizen/Classes/AppMacros.h
 tests/cpp-empty-test/proj.tizen/Classes/HelloWorldScene.cpp
 tests/cpp-empty-test/proj.tizen/Classes/HelloWorldScene.h
 tests/lua-empty-test/project/proj.tizen/Classes/AppDelegate.cpp
tests/lua-empty-test/project/proj.tizen/Classes/AppDelegate.h
 tests/lua-empty-test/project/proj.tizen/Classes/lua_module_register.h
```

You should use the source files cocos engine do have.

**Comment by WenhaiLin** [comment]
Hi @sukwonsuh, please merge this PR: https://github.com/sukwonsuh/cocos2d-x/pull/1

**Comment by WenhaiLin** [comment]
Hi @sukwonsuh Please merge this PR: https://github.com/sukwonsuh/cocos2d-x/pull/2.

**Comment by WenhaiLin** [comment]
Hi @sukwonsuh  The specific files of WP8/WIN32 should be filtered out on Tizen. Please merge https://github.com/sukwonsuh/cocos2d-x/pull/3

**Comment by WenhaiLin** [comment]
Hi @sukwonsuh, C source files not be build successfully on Tizen. Is it a know issue of Tizen?

**Comment by sukwonsuh** [comment]
Hi @Dhilan007
That is Not known issue.
How can I reproduce it?

**Comment by WenhaiLin** [comment]
Console outputs error message when build c source file on Tizen. Let’s have a look at an example below:

``` cpp
/usr/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/sh: -c: line 1: syntax error: unexpected end of file
external/ConvertUTF/subdir.mk:25: recipe for target 'external/ConvertUTF/ConvertUTF.o' failed
make: *** [external/ConvertUTF/ConvertUTF.o] Error 258
make: *** Waiting for unfinished jobs....
```

It could be build successfully after change 'ConvertUTF.c'/'xxhash.c' to 'ConvertUTF.cpp'/'xxhash.cpp'

**Comment by sukwonsuh** [comment]
@Dhilan007
I'll check it. thanks.

**Comment by WenhaiLin** [comment]
@sukwonsuh My development environment : win8.1 64 + Tizen IDE 2.3.0_Rev1
Is Tizen IDE only supported win7 as @QingliWang told me?

**Comment by QingliWang** [comment]
Just wonder, still checking...

**Comment by sukwonsuh** [comment]
I cannot reproduce compile error problem in my environment.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
In file included from /android_slave/workspace/ccs-pr/node/android/build/../cocos/ui/UIWebView.cpp:29:0:
/android_slave/workspace/ccs-pr/node/android/build/../cocos/ui/UIWebViewImpl-tizen.h:29:18: fatal error: Evas.h: No such file or directory
 #include "Evas.h"

**Comment by zilongshanren** [comment]
Hi, @sukwonsuh 
It breaks the original Android build.  You might need to add platform guard macro to UIWebViewImpl-tizen.h

**Comment by sukwonsuh** [comment]
Hi, @andyque 
That right. I'll submit that.

**Comment by QingliWang** [comment]
To build lua-empty-test,
we need to 
1.delete Classes folder in the "Project Explorer" and imported it again.
2.add some including paths into Properties->C/C++ Build->Settings->Tool Settings->Includes
3.add 3rd libs in this order: cocos2dxluabindings
                                           cocos2dx
                                           chipmunk png jpeg tiff webp websockets
into C++ Linker->Libraries.
The first two libs' order is fixed.
4.build successfully.

**Comment by WenhaiLin** [comment]
@sukwonsuh Please merge this pr:https://github.com/sukwonsuh/cocos2d-x/pull/6

**Comment by QingliWang** [comment]
about the crash issue when close the app,
please change one fuction like this:
"
void GLViewImpl::end()
{
    //app_exit();
    exit(0);
}
"

**Pull request closed without merging**
