### PR TITLE
Cpp Check

### PR DESCRIPTION
**Pull request by fnz**
CppCheck is a popular static analysis tool which detects a variety of nasty bugs. This commit adds a target to cocos2d_tests.xcodeproj consisting of a python script that executes cppcheck v 1.66 (latest one) with all necessary settings. Output is set to be XCode-friendly, so one can jump to the error causing place instantly like it was a regular c++ error. CppCheck takes it's time to run, so be sure to wait until the script finishes.

XCode has a certain limit on custom error/warning messages. If there are more than 200 than messages, the script can be run manually and the output will be seen in console or channeled to a file.

### CODE REVIEW

**Comment by fnz** [comment]
mac/ios build fails with following messages:
Traceback (most recent call last):
  File "tools/jenkins-scripts/pull-request-builder.py", line 327, in <module>
    sys_ret = main()
  File "tools/jenkins-scripts/pull-request-builder.py", line 188, in main
    check_current_3rd_libs(branch)
  File "tools/jenkins-scripts/pull-request-builder.py", line 63, in check_current_3rd_libs
    copy(current_file, backup_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'../../../cocos-2dx-external/node/ios_mac/v3-deps-10.zip'
excute build script...
1
Build step 'Execute Python script' marked build as failure
Finished: FAILURE

Seems like it has nothing to do with my pr)

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@fnz 
Thanks. How to use it?

**Comment by fnz** [comment]
Just run Cpp Check target in test ios/mac project. It will output first 200 errors as regular xcode errors. To view full output execute the script "by hand". Most of the errors are related to a variable scope that can be reduced or it++ instead of ++it, but there are some sneaky ones like uninitialized variables.

**Comment by minggo** [comment]
Thanks. It seems great.
I have a question, why there is a modification of `modified:   build/cocos2d_tests.xcodeproj/project.pbxproj` after i merging your branch locally?

**Comment by fnz** [comment]
These changes add a new target so cpp check can be ran directly from xcode http://gyazo.com/bb5d8e0ab398842d63d2db4f81e135f9

**Comment by minggo** [comment]
What i was confused is that, why it caused modified after merging?
Because i have merged it, why it also has a modification when you run

git status

**Comment by fnz** [comment]
No idea. And what are the changes?

2014-09-25 6:51 GMT+04:00 minggo notifications@github.com:

**Comment by minggo** [comment]
```
A03101308207:cocos2d-x minggo$ git pull https://github.com/fnz/cocos2d-x.git cppcheck
From https://github.com/fnz/cocos2d-x
 * branch            cppcheck   -> FETCH_HEAD
Already up-to-date.
A03101308207:cocos2d-x minggo$ git status
On branch cpp-check
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   build/cocos2d_tests.xcodeproj/project.pbxproj
```

**Comment by minggo** [comment]
```
A03101308207:cocos2d-x minggo$ git diff
diff --git a/build/cocos2d_tests.xcodeproj/project.pbxproj b/build/cocos2d_tests
index 3cc7300..8c92b69 100644
--- a/build/cocos2d_tests.xcodeproj/project.pbxproj
+++ b/build/cocos2d_tests.xcodeproj/project.pbxproj
@@ -9207,6 +9207,7 @@
                                6372172A19C87BA6002C1D2E /* Release */,
                        );
                        defaultConfigurationIsVisible = 0;
+                       defaultConfigurationName = Debug;
                };
                A035ACBC1782469800987F6C /* Build configuration list for PBXAggr
                        isa = XCConfigurationList;
```

**Comment by fnz** [comment]
No idea

**Comment by minggo** [comment]
The PR is outdated since the Xcode project file is changed a lot.

**Pull request closed without merging**
