### PR TITLE
2.2.6 version OHOS adaptation

### PR DESCRIPTION
**Pull request by IceBBBBB**

### CODE REVIEW

**Comment by minggo** [comment]
Please just add source code into external, not including other resources, such as .png files and other documents.

**Comment by IceBBBBB** [comment]
> Please just add source code into external, not including other resources, such as .png files and other documents.

removed

**Comment by minggo** [comment]
Please only include .h and .cpp.

**Comment by IceBBBBB** [comment]
> Please only include .h and .cpp.

ok，removed

**Comment by minggo** [comment]
- Missing prebuilt lib for Box2D,chipmunk
- Why libpng, libjpeg, openssl, zlib have prebuilt lib and source code
- Please don't include examples in libwebp
- Is pvmp3dec/Androoid.mk needed?
- Why inlcude both webp and libwebp-0.4.2

**Comment by IceBBBBB** [comment]
> * Missing prebuilt lib for Box2D,chipmunk
> * Why libpng, libjpeg, openssl, zlib have prebuilt lib and source code
> * Please don't include examples in libwebp
> * Is pvmp3dec/Androoid.mk needed?
> * Why inlcude both webp and libwebp-0.4.2

Box2D and chipmunk are the original third-party libraries of the engine, and the HarmonyOS platform uses the source code；
The rest has been modified.

**Comment by minggo** [comment]
> Why libpng, libjpeg, openssl, zlib have prebuilt lib and source code?

It seems it is not modified.

**Comment by IceBBBBB** [comment]
> > Why libpng, libjpeg, openssl, zlib have prebuilt lib and source code?
> 
> It seems it is not modified.

it's like this，libpng, libjpeg, zlib uses the source code. openssluses prebuild lib .

**Comment by minggo** [comment]
What i mean is that, there is external/lib/libpng_static.a, and also has the source code in external/libpng. jpeg and libz also have the same problem.

**Comment by IceBBBBB** [comment]
> What i mean is that, there is external/lib/libpng_static.a, and also has the source code in external/libpng. jpeg and libz also have the same problem.

The source code needs to link to these prebuild lib, Otherwise, an error will be reported，I will study whether it is possible to unify later when I have free time

**Comment by minggo** [comment]
.a should not depend on .cpp files. I will not merge it until it is fixed.

**Comment by IceBBBBB** [comment]
> .a should not depend on .cpp files. I will not merge it until it is fixed.

It is cpp dependent on. a, not. a dependent on cpp.

**Comment by minggo** [comment]
Ok. Please fix it before merging. Should just use source code or prebuilt lib, not mix them.

**Comment by IceBBBBB** [comment]
> Ok. Please fix it before merging. Should just use source code or prebuilt lib, not mix them.

ok，modified

**Pull request merged**
