### PR TITLE
Update Lua

### PR DESCRIPTION
**Pull request by dualface**
更新 Lua 的部分文件，以适应 cocos2d-x 源代码的更新
增加 typedef int LUA_HANDLE，让 CCLuaEngine 中的定义更清晰
修正 CCObject::~CCObject() 在 CCLuaEngine 已经销毁时仍然尝试删除 Lua 绑定的问题

### CODE REVIEW

**Comment by dualface** [comment]
从 Lua 绑定删除 CCTexturePVR（内部使用的对象，不应该暴露给 Lua）
将 CCNode::getPosition()、setPosition() 等方法改为 virtual。因为 CCSprite 中覆盖了这些方法。

**Comment by minggo** [comment]
Please use English.

**Comment by minggo** [comment]
Did you modify CCSprite.h and CCSpirte.cpp?

So please revert files that you don't modify anything and repull again.

Thank you for your work.

**Comment by dualface** [comment]
1. Update Lua binding for latest master sources
2. add typedef LUA_FUNCTION, LUA_HANDLE
3. fix crash when delete CCObject with Lua binding
4. Remove CCTexturePVR from Lua binding
5. change CCNode methods to virtual:
   
   ```
   virtual const CCPoint& getPositionLua(void);
   virtual void getPosition(float* x, float* y);
   virtual float getPositionX(void);
   virtual float getPositionY(void);
   virtual void setPositionX(float x);
   virtual void setPositionY(float y);
   virtual void setPosition(float x, float y);
   virtual void setPositionInPixels(float x, float y);
   ```
6. add CCSprite methods:
   
   virtual void setPosition(float x, float y);
   virtual void setPositionInPixels(float x, float y);

**Comment by minggo** [comment]
But there are these functions in CCSprite:

virtual void setPosition(float x, float y);
virtual void setPositionInPixels(float x, float y);

pwd: This pull request can not be merged automatically, there may be a conflict.

**Comment by minggo** [comment]
Oh, I am sorry.
The parameters are different.
They are added for the  convenience of lua binding?

**Comment by dualface** [comment]
CCSprite::setPosition () methods are virtual, so base class CCNode, these methods should also be virtual.

The add CCSprite::setPosition(float x, float y) and CCSprite::setPositionInPixels(float x, float, y) is to be consistent with CCNode.

**Comment by minggo** [comment]
CCNode::setPosition() is virtual.

CC_PROPERTY_PASS_BY_REF(CCPoint, m_tPosition, Position)

**Comment by dualface** [comment]
this pull request has problems ?

**Comment by minggo** [comment]
As I mentioned, it can not be automatically merged.
There is a conflict, so please resolve it and repull a request.

Thank you.

**Pull request merged**
