### PR TITLE
fixed retro pos.

### PR DESCRIPTION
**Pull request by fusijie**
@yangws Please take a look.

### CODE REVIEW

**Comment by fusijie** [comment]
relative pr: https://github.com/cocos2d/cocos2d-x/pull/13295

**Comment by yangws** [comment]
@pandamicro  reviewed OK, please merge it.

**Comment by zilongshanren** [comment]
@fusijie  please don't add punchbox issue link here...

**Comment by fusijie** [comment]
@zilongshanren ok... ╮(╯▽╰)╭

**Pull request merged**
