### PR TITLE
Adding 'the greatest change.' 

### PR DESCRIPTION
**Pull request by pauljonescodes**
A resolution policy that will scale based on which difference in design resolution and screen size is the bigger one.

### CODE REVIEW

**Comment by dumganhar** [comment]
Why do you name it 'greatest'? That's a bit confused.

**Comment by dumganhar** [comment]
And could you describe that in what situation we need to use this strategy?

**Comment by dumganhar** [comment]
@PLJNS 
And could you describe that in what situation we need to use this strategy?

**Comment by cocosQA** [comment]
Dear PLJNS:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6488
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
