### PR TITLE
enable changing percentage of ui::Slider at touching a bar sprite

### PR DESCRIPTION
**Pull request by Naruto**
Added detection that hit a bar sprite to Slider::hitTest.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@Naruto  Is it the right behavior? I have tested the UIKit, it is using slider ball to control the slider. We can't touch the slider bar sprite to change the percentage.
Could you confirm it?

**Comment by zilongshanren** [comment]
@Naruto  I will try to implement it in v3.9. Thanks.

**Comment by Naruto** [comment]
@zilongshanren thanks.

**Comment by zilongshanren** [comment]
@Naruto  
new PR is https://github.com/cocos2d/cocos2d-x/pull/13826

**Comment by zilongshanren** [comment]
@Naruto  please help to review the code, thanks.

**Pull request closed without merging**
