### PR TITLE
Fixes for CocosDragonJS and WatermelonWithMe

### PR DESCRIPTION
**Pull request by rohankuruvilla**

### CODE REVIEW

**Comment by dumganhar** [comment]
Looks great.I will test it,thanks.

**Comment by dumganhar** [comment]
Hi, Rohan,
The PR cannot be automatically merged! Could you pull our latest codes?
ÔÚ 2012-12-1 ÉÏÎç6:44£¬"Rohan Kuruvilla" notifications@github.comÐ´µÀ£º

**Comment by rohankuruvilla** [comment]
Hi James,

My mistake, you should be able to merge it automatically now.

Thanks,

Rohan

**Comment by dumganhar** [comment]
Thanks,i`ll test it about a hour later,if no problems,i will merge it.
PS,i am still on the bed,and it`s 8:20am,Sat. :-)

**Comment by dumganhar** [comment]
Thanks, Rohan.

**Pull request merged**
