### PR TITLE
use prebuilt version of Box2D

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by Anywhere-Music-Player** [comment]
@minggo  what exactly Box2D version you are used for this?

**Comment by minggo** [comment]
v2.3.1, the latest released version.

**Comment by Anywhere-Music-Player** [comment]
@minggo I was sure that your are using not latest version, just asked.
And I already created bug about this before.

**Comment by minggo** [comment]
i used this script to generate it: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/commit/b74c0955e72e1839003102c98c1afd4e5c3c5ef0.

**Comment by Anywhere-Music-Player** [comment]
I don’t know anything about it. I just know that Box2D is v2.3.2
Better to use original repo of Box2D.

**Comment by minggo** [comment]
```
+BOX2D_VERSION := 2.3.1
 +BOX2D_URL := https://codeload.github.com/erincatto/Box2D/tar.gz/v$(BOX2D_VERSION)
```
download the source code from github. Does it mean Box2D has wrong version information? And there is not 2.3.2 in https://github.com/erincatto/Box2D/releases.

**Comment by Anywhere-Music-Player** [comment]
I don’t know anything about releases system on git.
I only know that latest Box2D is v2.3.2, you can check it by yourself too in Box2D sources.
Moreover last commit of Box2D was 4 months ago and that release is 2014 year. It’s obviously that it’s not latest.

**Comment by minggo** [comment]
if it is not set a tag to release, then it means it is not about to release? And how to check the Box2D version?

**Comment by Anywhere-Music-Player** [comment]
As I said I don’t know what is releases on git, never used and wanted to use.
Just take Box2D source code, it’s obviously latest and I’m using it for my games.

**Comment by Anywhere-Music-Player** [comment]
https://github.com/cocos2d/cocos2d-x/issues/17776

**Comment by minggo** [comment]
https://github.com/erincatto/Box2D/commit/6a38df1a2cb7f83c85b8ad5905d25427af54327d, so the author use wrong version information.

You can don't use git release, but i have to use a release version to make sure that it is a release version.

**Comment by minggo** [comment]
Oh, my fault. The version is changed after releasing 2.3.1. But the author doesn't release 2.3.2. Then i don't know use which commit to build Box2D.

**Comment by Anywhere-Music-Player** [comment]
I’m using latest code just it’s simpler, I don’t understand why you not sure.

**Comment by minggo** [comment]
I created an issue: https://github.com/erincatto/Box2D/issues/478 to ask the author when to release 2.3.2.

**Comment by Anywhere-Music-Player** [comment]
I don’t think he will answer)

**Comment by minggo** [comment]
Use latest github codes is dangerous. You can use it in your project, it is ok, it is just your own project. But cocos2d-x is used in many games, we should make sure to use stable version.

**Comment by Anywhere-Music-Player** [comment]
I’m using latest for a long time. It’s obviously for me that I  should use latest code. If you want make sure and test it or not , no problem. 
Do you think author of Box2D testing it really? Not more than testbed App, lol. 
Anyway after you used not latest prebuilt Box2D and I update cocos - how I should update it by myself? Currently it’s in external folder so I can just copy paste code. But with prebuilt how I can update it?

**Comment by minggo** [comment]
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src, it supports to build prebuilt versions. About Windows, it is easy to use VS to build libs.

**Comment by vkreal** [comment]
I have a custom version of Box2d and since cocos now uses prebuilt how can I use my version. I dont have Windows. What i have done when after upgrading cocos replace the box2d files.

**Comment by vkreal** [comment]
Maybe making box2d prebuilt is not the way to go?

**Comment by Anywhere-Music-Player** [comment]
Minggo just use latest code, I’ve used it for years with couple big games and it’s stable.
You really thinking that author of Box2D will test it like in games or cocos before release? Don’t make me laugh.. he just will click: release-> v2.3.2 -> done. Here you go ))

**Comment by minggo** [comment]
@KAMIKAZEUA which is the latest one? It is changed 5 months ago, and you used it for years, did you mean we have to update it when there is a new commit? 

@vkreal you can change to use source code, it is not so hard. In fact, all 3rd part libs should use prebuilt version. It will speed up building speed and fix many warnings. The final goal is to remove all warnings, then make warnings as error.

**Comment by Anywhere-Music-Player** [comment]
I’m telling that I’m always using latest code from git for years(follow any Box2D code updates) and never faced problems.

**Comment by vkreal** [comment]
@minggo fair enough about the fixing warnings.

**Comment by minggo** [comment]
Yep, then when to update Box2D? Every time it has a new commit? And you can use the script to build prebuilt version if you want.

Indeed, cocos2d-x doesn't depend on Box2D, i can adjust the project settings to remove it from linking. Then you guys can determine how to use it.

**Comment by Anywhere-Music-Player** [comment]
Every time yes, it’s like every day? No, check timeline of commits and you will understand.

**Comment by vkreal** [comment]
@minggo `i can adjust the project settings to remove it from linking` lets keep it the way it is now :)

**Comment by Anywhere-Music-Player** [comment]
I’m suggesting you remove anything else that not depends, currently engine is too heavy and compiling is a nightmare. What is pity that many of thing is never ever used by recompile’s every time..

**Comment by minggo** [comment]
@KAMIKAZEUA i will create a discuss thread in forum. I think listening other developers' opinion is good. I will paste the link here. Yep, that's why i use prebuilt version. I will continue to have more prebuilt version of other codes, such as 3d related codes.

@vkreal thanks for understanding.

**Comment by Anywhere-Music-Player** [comment]
I’ve already a nightmare experience with building prebuilt libs of cocos and now I would need also play with other not needed compiling.. ohh

**Comment by KAMIKAZEUA** [comment]
Just remove that libs from cocos and make it more lighter

**Comment by Anywhere-Music-Player** [comment]
I actually don’t care what other devs will say, I just need to be able to use latest v2.3.2 Box2D, that’s it. And what if I have custom Box2D code? Or I don't have windows to recompile libs? Or I have to do too much to replace box2d lib now..
And I was sure that with this merge it’s not latest, that’s why I wrote.

**Comment by minggo** [comment]
I create a thread here: http://discuss.cocos2d-x.org/t/use-which-version-of-box2d/39758.

@KAMIKAZEUA the engine is not just for you.

**Comment by Anywhere-Music-Player** [comment]
Just add two options: prebuilt lib 3y old and prebuilt lib using latest commit. In cocos config change that. My game code can’t be even compiled with old one. And there are a lot of fixes I need for stable work of my game.

**Comment by Anywhere-Music-Player** [comment]
@minggo when you will remove Box2D from cocos2d-x remove all **results of macro**:  CC_ENABLE_BOX2D_INTEGRATION from cocos2d-x.  THanks.

screen shot

And any Box2D specific code:

screen shot

**Comment by minggo** [comment]
Oh, i don't notice that some codes depends on Box2D. Then i can not remove it.

**Comment by Anywhere-Music-Player** [comment]
@minggo revert back to source code, as it was before. Or use latest commit as in vote.

**Comment by minggo** [comment]
Yep, i think i have to use latest commit as in vote.

**Comment by minggo** [comment]
Done in  https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/308

**Pull request merged**
