### PR TITLE
improve ActionTimeline api

### PR DESCRIPTION
**Pull request by 2youyou2**
Fow now, the code to create an ActionTimeline and play it is a little complex.

Example:

```
Node* node = CSLoader::createNode("ActionTimeline/boy_1.csb");
ActionTimeline* action = CSLoader::createTimeline("ActionTimeline/boy_1.csb");

node->runAction(action);
action->gotoFrameAndPlay(0, 60, true);
```

To get an existing action from node:
    ActionTimeline\* action = node->getActionByTag(node->getTag());

So we want to make the api more easy to use.
We plain to to create an ActionTimelineNode class, and add some helper api to CSLoader.

ActionTimelineNode wrap the root node and action, we can expend animation api to ActionTimelineNode easily.

ActionTimelineNode will auto create node with action according to the parameters.

```
static cocostudio::timeline::ActionTimelineNode* createActionTimelineNode(const std::string& filename);
Static cocostudio::timeline::ActionTimelineNode* createActionTimelineNode(const std::string& filename, int startIndex, int endIndex, bool loop); 
```

Example after changed:

```
ActionTimelineNode*node=CSLoader::createActionTimelineNode("ActionTimeline/boy_1.csb", 0, 60, true);
```

To get an existing action from node:
    ActionTimeline\* action = node->getActionTimeline();

### CODE REVIEW

**Comment by minggo** [comment]
Don't add new features after releasing rc0 version.

**Comment by 2youyou2** [comment]
So when can we do these things?
@chengstory

**Comment by darkdukey** [comment]
What @minggo means we can plan it for the later version, @2youyouo2 also I have a question regarding this API, how do I play this animation with `ActionTimelineNode`?

Can we do something like play animation by name?

**Comment by 2youyou2** [comment]
Play animation by name is in our plan.
We will add an animation list in edtor, so users can specify a index region by name.

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Please fix compiling error.

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by 2youyou2** [comment]
There is a linux compile error : 
raise TranslationUnitLoadError("Error parsing translation unit.")
TranslationUnitLoadError: Error parsing translation unit.

But i do not know what's the error

**Comment by minggo** [comment]
Please run in linux machine and fix the error.
And this PR has a conflict.

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Please don't modify submodule.

**Comment by minggo** [comment]
If it will break tests, please modify lua test too.

**Comment by 2youyou2** [comment]
@minggo  
have fixed all, please review again.

**Comment by minggo** [comment]
Two questions:
1. It has conflict, please fix it again, sorry about it.
2. Is it needed by Cocos Studio? Because we have already released RC2, and will release final this week, we don't want to add new features.

**Comment by 2youyou2** [comment]
1. fixed 
2. ok, final version just need to fix bugs,  this pr can merge at next version

**Comment by minggo** [comment]
[ci rebuild]

**Comment by 2youyou2** [comment]
[ci rebuild]

**Comment by 2youyou2** [comment]
@minggo 
Jenkins CI  build successfully, please review

**Comment by minggo** [comment]
Please fix conflict.

**Comment by 2youyou2** [comment]
T_T!

**Comment by 2youyou2** [comment]
@minggo fixed.

**Pull request merged**
