### PR TITLE
const correctness: use cbegin/cend, const std::string

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @daltomi ,
Did our codes cause some warning on your platform if don't use `cbegin`, `cend` and `const std::string`?

**Comment by kis2009dsh** [comment]
Hi @daltomi 

There exist two methods of std::map::find  which listing as follow 

iterator find( const Key& key );
const_iterator find( const Key& key ) const;

You shall only use const_iterator when the object is const qualified . 

Thanks.

**Comment by ghost** [comment]
Hi @dumganhar 
No, no warning at all.

**Comment by dumganhar** [comment]
Thanks. merged.

**Pull request merged**
