### PR TITLE
Adding VC2012 sln file and VS2012 changes to build-win32.bat & install-templates.msvc.bat

### PR DESCRIPTION
**Pull request by trentmillar**
I changed the ordering in the bat file to process newer VC++ versions before older ones. 

This was an issue for me running multiple versions of VS on my box.

Tested with VS2012 RTM.

### CODE REVIEW

**Comment by minggo** [comment]
It doesn't have corresponding 2012 project, does it open corresponding 2010 project?

**Comment by trentmillar** [comment]
Yes, the environment variables are checked so whatever version of Visual Studio the user has will be the solution that is used in the build. MSBuild will then target the correct version when compiling the project in release & debug.

If I understand correctly, the project files are version agnostic to begin with. Only until you actually open the solution file in Visual Studio will the version actually get added to each project and they are re-written by Visual Studio to match the correct version.

This is what is added to the vcxproj files:
 &lt;PlatformToolset&gt;v110&lt;/PlatformToolset&gt;

My changes are leveraging what was already used by cocos2d-x.

I did notice that the vcproj file is referring to, Version="9.00"  but it must have been this way for a long time and doesn't look to cause issues with VS2010 or 2012 so I left that.

**Comment by trentmillar** [comment]
I went through my changes again and changed the version of the sln file, I had the incorrect version.

Also in the build-win3.bat file I added a Clean before targeting the build. Also I parallelized the release & debug builds

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
