### PR TITLE
Closes websocket connection by dispatching a 'resetDirector' event.

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by xiaofeng11** [comment]
@zilongshanren @pandamicro This pr fix after https://github.com/cocos2d/cocos2d-x/pull/14867 merged,  cpp-empty-test and new project create by cocos script can not compiled under android platform. Please review.

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@ricardoquesada ,@pandamicro ,could this PR be merged?

**Comment by ricardoquesada** [comment]
looks good to me. Having a test case in the `DirectorTest` would great.

**Comment by dumganhar** [comment]
@ricardoquesada , thanks for reply.
But Director reset event is only triggered while exiting game. It's hard for me to make a `DirectorTest`.
:(

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Comment by ricardoquesada** [comment]
@dumganhar what about a standalone test? or attached to the "exit" button in the cpp-test?

**Comment by dumganhar** [comment]
Hi, @ricardoquesada , there is already a `close` button in `cpp tests`.
For testing this fix, you could enter `21Extensions/6WebSocketTest`, click some button in this test and click the window's `close` button to exit.

**Comment by ricardoquesada** [comment]
ok. it is not that I want to test it, but I want that every feature that is added has tests.
as long as it is documented somehow, it is good.
For example the test could say: "press the exit button and see the console... you should see XXX".

**Comment by dumganhar** [comment]
@ricardoquesada , It was added by @xiaofeng11 , i will merge his code.

**Comment by dumganhar** [comment]
@ricardoquesada , @xiaofeng11 's test case was added. please check.

**Comment by ricardoquesada** [comment]
ok. thanks. it is good for me.
@dumganhar should I merge it ? or you ? thanks.

**Comment by dumganhar** [comment]
@ricardoquesada , yes please merge. Thanks.

**Comment by ricardoquesada** [comment]
ok. merged :)

**Comment by dumganhar** [comment]
:) Thanks.

**Pull request merged**
