### PR TITLE
Let a static body can be moveable, without modify chipmunk code.

### PR DESCRIPTION
**Pull request by varvelworld**
Let a static body can be moveable, without modify chipmunk code.

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@boyu0
Could you please review this PR?

**Comment by boyu0** [comment]
Thank you for improve our physics intergration.
I ran your test, I found that the yellow box is walk through the wall without collision, and even doesn't invoke a contact callback function. I think this might be a problem.
And, I think damping should be work either...

**Comment by varvelworld** [comment]
@boyu0 
The yellow box is walk through the wall, because both of them are static.So I think it's not a problem.The problem is that the collision callback function is not invoked.
I think the key is that a static body is not in "space".
I will have a try to fix it.

**Comment by minggo** [comment]
Any update of this PR?

**Pull request closed without merging**
