### PR TITLE
Crash fix for postNotification()

### PR DESCRIPTION
**Pull request by BodbDearg**
Fix crashes in CCNotificationCenter::postNotification caused by unsafe iteration of the observers list. The code should maintain a strong reference to all observer targets while iterating through the list, in case they are destroyed while we iterate.

### CODE REVIEW

**Comment by BodbDearg** [comment]
Note: another (possibly better?) way of fixing this problem might be to have 'NotificationObserver' observer maintain a strong reference rather than a weak reference to it's target object. I think that would be a very big architectural change however and potentially very dangerous for existing cocos2dx codebases since it would greatly affect the object lifecycle and when things get destroyed. This change is much more limited in scope and far less risky.

**Comment by minggo** [comment]
Thanks @DarraghCoy 
We will integrate `NotificationCenter` into `EventDispatcher`. And `NotificationCenter` will be deprecated or removed.

**Comment by dumganhar** [comment]
@DarraghCoy 
Could you try `EventDispatcher` to dispatch event?
I deprecated `NotificationCenter` in PR https://github.com/cocos2d/cocos2d-x/pull/3864 .

**Comment by BodbDearg** [comment]
Thanks! I had not realised NotificationCenter had been deprecated since we are still using Cocos2dx 2.x (we're planning to migrate to 3.x soon). I will close this pull request.

**Pull request closed without merging**
