### PR TITLE
Update CCSprite3D.cpp

### PR DESCRIPTION
**Pull request by hcqmaker**
FileUtils use lookup will be fail

### CODE REVIEW

**Comment by hcqmaker** [comment]
FileUtils use lookup will be fail

**Comment by minggo** [comment]
@super626 
Could you please take a look?

**Comment by dabingnn** [comment]
Similar to #9713

**Comment by dabingnn** [comment]
This pr will be closed, if you have any feedbacks, please add a detailed description of bug and reopen it.
Thanks.

**Pull request closed without merging**
