### PR TITLE
spine simple JS binding supported

### PR DESCRIPTION
**Pull request by seobyeongky**
hi
This branch has simple Spine JS binding. I tested on iOS. But no test on other platforms.

### CODE REVIEW

**Comment by dumganhar** [comment]
Could you paste the test codes?

**Comment by minggo** [comment]
It is better to add test case for it.

**Comment by seobyeongky** [comment]
OK I wil commit test case soon

**Comment by dumganhar** [comment]
@seobyeongky 
Thanks. Merged at #4611

**Pull request merged**
