### PR TITLE
sync cocos2d-x-libs-src repository and remove flatbuffers

### PR DESCRIPTION
**Pull request by zilongshanren**
This PR mainly does the following things:
1. remove flatbuffers
2. upgrade rapidjson
3. update deps to v4-deps-10
4. add glew, sqlite3 and libcurl prebuilt version for linux
5. cherry-pick ddbf057c52 from MSOpenTech

other minor fix for compilation issues.

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by stammen** [comment]
@andyque do you mean
1. update deps to v4-deps-10 and not v3-deps-10?

**Comment by zilongshanren** [comment]
yes, @stammen 
It's a typo. I have changed the content.
Thanks.

**Comment by zilongshanren** [comment]
@darkdukey  @ricardoquesada  all platform passed the CI slaves, but the Mac slave always goes offline.

Really wired. But I think it has already compiled successfully..

I will try to figure out the offline issue later.

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by darkdukey** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Pull request merged**
