### PR TITLE
Improved EditBox implement for platform win32

### PR DESCRIPTION
**Pull request by zilongshanren**

### CODE REVIEW

**Comment by summerinsects** [comment]
Thanks for accepting

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/issues/13431

**Comment by WenhaiLin** [comment]
@zilongshanren +1 I think this pr is OK for merge.

**Comment by WenhaiLin** [comment]
@wohaaitinciu I think you should revert to the original state when user cancel input.

**Comment by zilongshanren** [comment]
@wohaaitinciu  
When user press the cancel button, all the inputed text should be removed.
Before your patch, the text in the popup window only sync to EditBox when user pressed done.

Now the sync behavior happens when user starts to type.

The patch break the back compatibility.

**Comment by WenhaiLin** [comment]
@wohaaitinciu Any updates?

**Comment by summerinsects** [comment]
I see

**Comment by summerinsects** [comment]
So, cancel button pressed means it will give up all the edit operations in this time?

**Comment by summerinsects** [comment]
For example, original text was `hello', then I do some edit operations, such as deleting, appending or modifying, now the displaying text may no longer be`hello' (see article 6), and then I press cancel button, should it revert to `hello'?

Very sorry for keeping you waiting so long
@WenhaiLin @zilongshanren

**Comment by WenhaiLin** [comment]
@wohaaitinciu Yes,give up all the edit operations in this time that is the expected result. @zilongshanren  What do you think?

**Comment by wohaaitinciu** [comment]
see https://github.com/zilongshanren/cocos2d-x/pull/25

**Comment by WenhaiLin** [comment]
@zilongshanren I think this PR is OK for merge now. @wohaaitinciu Thank you very much!

**Pull request merged**
