### PR TITLE
Overhaul UTF modules and add full set of UTFs conversion functions.

### PR DESCRIPTION
**Pull request by xpol**

### CODE REVIEW

**Comment by xpol** [comment]
Any change to merge?

**Comment by dumganhar** [comment]
It looks great :+1: 

@ricardoquesada , @zilongshanren , Is there any reason that this PR isn't merged?

**Comment by zilongshanren** [comment]
@dumganhar  no..

**Comment by zilongshanren** [comment]
@xpol  Sorry for the late response..

**Pull request merged**
