### PR TITLE
Fix a fatal bug in EditBox implement for platform win32

### PR DESCRIPTION
**Pull request by summerinsects**
@zilongshanren @WenhaiLin  
Very sorry to say that, I found my PR (https://github.com/cocos2d/cocos2d-x/pull/13206) has a fatal bug.
In the earlier version, the Win32InputBox is a modal dialog box, and it would block rendering, then I use a timer to do rendering in that PR. However, there is a fatal error, i.e., main loop of Director was re-entered.
For example, when the dialog box is not yet closed, and try to remove the EditBox in a schedule, it will crash.

This PR uses modaless dialog box, which avoids re-entry, and won't crash any more.
I've done a series of tests, such as removing an EditBox in a schedule, in a Callback action, etc.

Please do some more test before merging.
Sorry trouble you.

### CODE REVIEW

**Comment by ricardoquesada** [comment]
Thanks. Could you add a test case as well?

**Comment by summerinsects** [comment]
In cpp-tests?

**Comment by zilongshanren** [comment]
@wohaaitinciu 
Yes, cpp-tests is OK.

**Comment by summerinsects** [comment]
@zilongshanren test case is added

**Comment by zilongshanren** [comment]
@wohaaitinciu :+1:

**Pull request merged**
