### PR TITLE
GlobalZOrder is used for render priority...

### PR DESCRIPTION
**Pull request by ricardoquesada**
...and not vertexZ

Node::setGlobalZOrder() is used to change that.

Node::setZOrder() -> Node::setLocalZOrder();

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @ricardoquesada ,
Since we have modified the API, getZOrder --> getLocalZOrder, and added s/getGlobalZOrder, could you please update release note(https://github.com/cocos2d/cocos2d-x/blob/develop/docs/RELEASE_NOTES.md) ?

**Comment by ricardoquesada** [comment]
yes, sure, I will update them.

**Comment by ricardoquesada** [comment]
done: https://github.com/cocos2d/cocos2d-x/pull/5170

although more info is still needed.

**Comment by dumganhar** [comment]
Thanks :)

**Pull request merged**
