### PR TITLE
Feature #687 - add preloadBackgroundMusic and unloadBackgroundMusic to Android

### PR DESCRIPTION
**Pull request by augustorsouza**
These 3 commits are an attempt to add preloadBackgroundMusic and unloadBackgroundMusic to Android. It is a first version implementation. I think a good approach is to have an ArrayList of MediaPlayer objects in Cocos2dxMusic class, instead of just one MediaPlayer. But, we need to discuss which approach is best before implementing, for now I think this is a start.

It aims to implement feature #687: http://www.cocos2d-x.org/issues/687

### CODE REVIEW

**Comment by minggo** [comment]
Is unloadBackgroundMusic needed? Because we only allow playing one background music at a time.

**Comment by augustorsouza** [comment]
In the feature #687 description, it is requested. The way I implemented it is useless, but I think it is a good idea to let the code there and improve it in the next releases. If the ideia of having an ArrayList of MediaPlayer objects is accepted by you guys, the unloadBackgroundMusic is going to be really usefull.

**Comment by minggo** [comment]
Cocos2d-iphone also supports playing one background music at a time, and I am not sure we need playing more than one background music, so I think unloadBackgroundMusic is not needed now.

But thank you again. Could you modify the code and repull the code?

**Comment by augustorsouza** [comment]
I agree with you. Let's follow the cocos2d-iphone behavior! =)

unloadBackgroundMusic removed successfully! I will try help the project more from now on. It is a really interesting project. I will keep looking in the website to check for open issues or features, but send me an email every time you guys need help, ok?

Best regards...

**Comment by minggo** [comment]
You are welcome to join us. What's your id in the forum? I will ask walzer to add you to the developer list, then you can modify the issue.
And what's your email? Which field are you familiar with?

**Comment by minggo** [comment]
My email is ming@cocos2d-x.org. I will merge the pull request, and it will be closed. 
Connect me, man.

**Pull request merged**
