### PR TITLE
Fix issue #17654 so that slicing information is not lost when loading textures.

### PR DESCRIPTION
**Pull request by tiagomartines11**
This is a possible solution for #17654. 

It works for my requirements and mimics the behavior from versions before v3.14.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@tiagomartines11  This PR is just a workaround, we'd better provide a fix on the Sprite.
I will consider to fix it, thanks .

**Comment by tiagomartines11** [comment]
I agree! A proper fix is ultimately needed - I can see other issues that exist ever since the Sprite/Scale9 classes were reworked. As long as we keep backwards compatibility, it is okay to refactor and add new functionality, but the changes from 3.14 (and some before that) broke a lot of past features - it should be reviewed as soon as possible :)

Thank you!

**Comment by zilongshanren** [comment]
@tiagomartines11 
I have made a new PR:  https://github.com/cocos2d/cocos2d-x/pull/18065
Could you help to test it?
 thanks.

**Review by zilongshanren — CHANGES_REQUESTED** [review]
This PR is hacking, so I'd rather close it ATM.

**Pull request closed without merging**
