### PR TITLE
Fix cocostudio 3d test crash on mobile platform

### PR DESCRIPTION
**Pull request by xiaofeng11**

### CODE REVIEW

**Comment by pandamicro** [comment]
Please also fix the problem for Lua/JS 3d test

**Comment by xiaofeng11** [comment]
Lua version won't have the crash bug, in order to make it more safety, I add search path to lua version. And add no content notice to lua version Node3d test to synchronize with cpp version.

JS won't have this test

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Merged in https://github.com/cocos2d/cocos2d-x/pull/13283

**Pull request closed without merging**
