### PR TITLE
Add getChildByName method for get a node that can be cast to Type T

### PR DESCRIPTION
**Pull request by zhouxiaoxiaoxujian**

### CODE REVIEW

**Comment by minggo** [comment]
Why need this function?

**Comment by zhouxiaoxiaoxujian** [comment]
Thank you for you reply.

Because , when use UIWidget Components, I need always cast to subType of UIWidget. like this:

```
::cocos2d::ui::Button btn = static_cast<::cocos2d::ui::Button*>(this->getChildByName("btn"));

::cocos2d::ui::Button btn = this->getChildByName<::cocos2d::ui::Button*>("btn");
```

I think below could be much more  readable  and usable than above.

**Comment by darkdukey** [comment]
I like this, definitely made it easier

**Comment by Mazyod** [comment]
Unity style, love it.

**Comment by darkdukey** [comment]
Can we merge this, this is much easier to use.

**Pull request merged**
