### PR TITLE
fixed #1081 cocosbuilder , error when loading CCControlButton from ccbi

### LINKED ISSUE #1081: cocosbuilder , error when loading CCControlButton from ccbi
Cocos2d-x crashes with an "Unexpected property: backgroundSpriteFrame|4" error. 

Assertion failed: (false), function onHandlePropTypeSpriteFrame, file ..../libs/cocos2dx/extensions/CCBReader/CCNodeLoader.cpp, line 748.

### PR DESCRIPTION
**Pull request by simdm**
CCControl.h  in cocos2d-x

/*\* The possible state for a control.  */
enum 
{
    CCControlStateNormal       = 1 << 0, // The normal, or default state of a control—that is, enabled but neither selected nor highlighted.
    CCControlStateHighlighted  = 1 << 1, // Highlighted state of a control. A control enters this state when a touch down, drag inside or drag enter is performed. You can retrieve and set this value through the highlighted property.
    CCControlStateDisabled     = 1 << 2, // Disabled state of a control. This state indicates that the control is currently disabled. You can retrieve and set this value through the enabled property.
    CCControlStateSelected     = 1 << 3  // Selected state of a control. This state indicates that the control is currently selected. You can retrieve and set this value through the selected property.
};

CCControlButtonLoader.cpp in cocos2d-x
# define PROPERTY_ZOOMONTOUCHDOWN "zoomOnTouchDown"
# define PROPERTY_TITLE_NORMAL "title|1"
# define PROPERTY_TITLE_HIGHLIGHTED "title|2"
# define PROPERTY_TITLE_DISABLED "title|3"
# define PROPERTY_TITLECOLOR_NORMAL "titleColor|1"
# define PROPERTY_TITLECOLOR_HIGHLIGHTED "titleColor|2"
# define PROPERTY_TITLECOLOR_DISABLED "titleColor|3"
# define PROPERTY_TITLETTF_NORMAL "titleTTF|1"
# define PROPERTY_TITLETTF_HIGHLIGHTED "titleTTF|2"
# define PROPERTY_TITLETTF_DISABLED "titleTTF|3"
# define PROPERTY_TITLETTFSIZE_NORMAL "titleTTFSize|1"
# define PROPERTY_TITLETTFSIZE_HIGHLIGHTED "titleTTFSize|2"
# define PROPERTY_TITLETTFSIZE_DISABLED "titleTTFSize|3"
# define PROPERTY_LABELANCHORPOINT "labelAnchorPoint"
# define PROPERTY_PREFEREDSIZE "preferedSize" // TODO Should be "preferredSize". This is a typo in cocos2d-iphone, cocos2d-x and CocosBuilder!
# define PROPERTY_BACKGROUNDSPRITEFRAME_NORMAL "backgroundSpriteFrame|1"
# define PROPERTY_BACKGROUNDSPRITEFRAME_HIGHLIGHTED "backgroundSpriteFrame|2"
# define PROPERTY_BACKGROUNDSPRITEFRAME_DISABLED "backgroundSpriteFrame|3"

1 << 2 equals 4, not 3

### CODE REVIEW

**Comment by minggo** [comment]
Thank you.

**Comment by minggo** [comment]
Why the issue number is 1081?
The issue number should be one of this http://www.cocos2d-x.org/projects/native/roadmap.

**Comment by simdm** [comment]
#1081 is github issue number.
same problem.

**Comment by minggo** [comment]
Ok.

**Pull request merged**
