### PR TITLE
Fix bug: Clipping node doesn't work on Android 5.0.

### PR DESCRIPTION
**Pull request by yangws**
The related issue:
https://github.com/cocos2d/cocos2d-x/issues/10759

In this pr, if configattribs matched, choose the first one config.
If not match, sort all configs, then use bin search to find a closest one.

sorted configs example:
[0]: { color: 0565; depth: 0; stencil: 0;}
[1]: { color: 0565; depth: 0; stencil: 0;}
[2]: { color: 0565; depth: 0; stencil: 0;}
[3]: { color: 0888; depth: 0; stencil: 0;}
[4]: { color: 0888; depth: 0; stencil: 0;}
[5]: { color: 0888; depth: 0; stencil: 0;}
[6]: { color: 0888; depth: 0; stencil: 0;}
[7]: { color: 0888; depth: 0; stencil: 0;}
[8]: { color: 0888; depth: 0; stencil: 0;}
[9]: { color: 0565; depth: 0; stencil: 8;}
[10]: { color: 0565; depth: 0; stencil: 8;}
[11]: { color: 0565; depth: 0; stencil: 8;}
[12]: { color: 0888; depth: 0; stencil: 8;}
[13]: { color: 0888; depth: 0; stencil: 8;}
[14]: { color: 0888; depth: 0; stencil: 8;}
[15]: { color: 0888; depth: 0; stencil: 8;}
[16]: { color: 0888; depth: 0; stencil: 8;}
[17]: { color: 0888; depth: 0; stencil: 8;}
[18]: { color: 0565; depth: 16; stencil: 0;}
[19]: { color: 0565; depth: 16; stencil: 0;}
[20]: { color: 0565; depth: 16; stencil: 0;}
[21]: { color: 0888; depth: 16; stencil: 0;}
[22]: { color: 0888; depth: 16; stencil: 0;}
[23]: { color: 0888; depth: 16; stencil: 0;}
[24]: { color: 0888; depth: 16; stencil: 0;}
[25]: { color: 0888; depth: 16; stencil: 0;}
[26]: { color: 0888; depth: 16; stencil: 0;}
[27]: { color: 0565; depth: 24; stencil: 8;}
[28]: { color: 0565; depth: 24; stencil: 8;}
[29]: { color: 0565; depth: 24; stencil: 8;}
[30]: { color: 0888; depth: 24; stencil: 8;}
[31]: { color: 0888; depth: 24; stencil: 8;}
[32]: { color: 0888; depth: 24; stencil: 8;}
[33]: { color: 0888; depth: 24; stencil: 8;}
[34]: { color: 0888; depth: 24; stencil: 8;}
[35]: { color: 0888; depth: 24; stencil: 8;}
[36]: { color: 8888; depth: 0; stencil: 0;}
[37]: { color: 8888; depth: 0; stencil: 0;}
[38]: { color: 8888; depth: 0; stencil: 0;}
[39]: { color: 8888; depth: 0; stencil: 8;}
[40]: { color: 8888; depth: 0; stencil: 8;}
[41]: { color: 8888; depth: 0; stencil: 8;}
[42]: { color: 8888; depth: 16; stencil: 0;}
[43]: { color: 8888; depth: 16; stencil: 0;}
[44]: { color: 8888; depth: 16; stencil: 0;}
[45]: { color: 8888; depth: 24; stencil: 8;}
[46]: { color: 8888; depth: 24; stencil: 8;}
[47]: { color: 8888; depth: 24; stencil: 8;}

@pandamicro @dabingnn  @felixjingga

### CODE REVIEW

**Comment by felixjingga** [comment]
Hi, thanks @yangws  for helping to perfect my PR. at first glance, I think it's okay and this is what I had in mind.. Sorry for couldn't perfecting my previous PR..

@dabingnn @pandamicro

**Comment by pandamicro** [comment]
@zilongshanren There is already an issue for this PR.
@dabingnn Can you help review this PR ？

**Comment by dabingnn** [comment]
@pandamicro This pull request has been reviewed. It is ready to be merged.
Thanks.

**Comment by pandamicro** [comment]
Thanks guys

**Pull request merged**
