### PR TITLE
Support ETC1 Alpha Channel in the Spine Library

### PR DESCRIPTION
**Pull request by ghost**
For support **ETC1** alpha channel in spine.

### CODE REVIEW

**Comment by minggo** [comment]
As the license of Spine, we can not modify the codes. Could you please send a PR  to Spine runtime, then we can merge it after it is merged by Spine runtime.

**Comment by ghost** [comment]
OK. I have send a PR to the Spine runtime.

**Comment by minggo** [comment]
thanks

**Comment by halx99** [comment]
It's good.

**Comment by minggo** [comment]
@Kameiha could you please paste the link of the PR sent to Spine runtime?
Thanks.

**Comment by ghost** [comment]
https://github.com/EsotericSoftware/spine-runtimes/pull/877

**Comment by minggo** [comment]
thanks

**Comment by LittleIronMan** [comment]
Friends, I can't add alpha channel of ETC1 compressed texture for spine animation. I created a [topic](https://discuss.cocos2d-x.org/t/etc1-texture-in-spine-animations/46298) on the cocos2d forum. I really hope for your help.

**Comment by LittleIronMan** [comment]
This feature is very necessary for our project. Are there any examples or tests using it?

**Pull request merged**
