### PR TITLE
fixed #2034:make CCUserDefault compatible with previous version on Android and iOS

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by ChrisOrz** [comment]
It doesn't work with cocosbuilder v3.0 alpha3.Incompatible ccbi file version .

**Comment by minggo** [comment]
Why?

**Comment by jimmy0807** [comment]
Hi mingo
in CCUserDefault.cpp or CCUserDefaultAndroid.cpp
in function static tinyxml2::XMLElement\* getXMLNodeForKey(const char\* pKey, tinyxml2::XMLDocument **doc)
pXmlBuffer hasn't been released

**Comment by minggo** [comment]
@jimmy808126 
Thank you.

**Pull request merged**
