### PR TITLE
upgrades to new spidermonkey API

### PR DESCRIPTION
**Pull request by rolandoam**
FF beta - this fixes the auto-compartment issue

Please merge this only after upgrading to the new spidermonkey API (ricardo should update it soon). This is required in order for the debugger to work: there's a problem with the autocompartments in FF16.

### CODE REVIEW

**Comment by rolandoam** [comment]
just a note: the new FF version is already on riq's repo

**Comment by dumganhar** [comment]
OK, I will test it. Thanks.

**Comment by dumganhar** [comment]
Hey Rolando,
I built the spidermonkey library in Riq's repo. But I got some errors when building it for android. 
The details are as follows:

<pre>
/Users/james/Project/cocos2d/Spidermonkey/js/src/jsapi.cpp:882: undefined reference to `js::JMCheckLogging()'
../libjs_static.a(jsinterp.o): In function `js::RunScript(JSContext*, JSScript*, js::StackFrame*)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/jsinterp.cpp:268: undefined reference to `js::JMCheckLogging()'
../libjs_static.a(YarrJIT.o): In function `JSC::ARMAssembler::spewInsWithOp2(char const*, JSC::ARMAssembler::Condition, int, unsigned int)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/ARMAssembler.h:1390: undefined reference to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)'
../libjs_static.a(YarrJIT.o): In function `JSC::ARMAssembler::spewInsWithOp2(char const*, JSC::ARMAssembler::Condition, int, int, unsigned int)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/ARMAssembler.h:1378: undefined reference to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)'
../libjs_static.a(YarrJIT.o): In function `JSC::ARMAssembler::linkJump(JSC::ARMAssembler::JmpSrc, JSC::ARMAssembler::JmpDst)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/ARMAssembler.h:1096: undefined reference to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)'
../libjs_static.a(YarrJIT.o): In function `JSC::AssemblerBufferWithConstantPool<2048, 4, 4, JSC::ARMAssembler>::flushConstantPool(bool)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/AssemblerBufferWithConstantPool.h:268: undefined reference to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)'
../libjs_static.a(YarrJIT.o): In function `JSC::ARMAssembler::pop_r(int, JSC::ARMAssembler::Condition)':
/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/ARMAssembler.h:808: undefined reference to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)'
../libjs_static.a(YarrJIT.o):/Users/james/Project/cocos2d/Spidermonkey/js/src/build-android/../assembler/assembler/ARMAssembler.h:952: more undefined references to `js::JaegerSpew(js::JaegerSpewChannel, char const*, ...)' follow
collect2: ld returned 1 exit status
make[2]: *** [js] Error 1
make[1]: *** [libs] Error 2
make: *** [default] Error 2
</pre>

Could you check it and find out what the problem is ?

**Comment by rolandoam** [comment]
what steps are you using to build it?

**Comment by dumganhar** [comment]
cd xxx/js/src/build-android
HOME=/Users/james/Software ./build.sh -r

my ndk and sdk are placed at /Users/james/Software/bin

ios and win32 work right. Any idea?
ÔÚ 2012-10-27 ÉÏÎç1:43£¬"Rolando Abarca" notifications@github.comÐ´µÀ£º

**Comment by rolandoam** [comment]
I think the build script is missing the --with-android-platform flag... These are the new options:

```
  --with-android-ndk=DIR
                          location where the Android NDK can be found
  --with-android-toolchain=DIR
                          location of the android toolchain
  --with-android-version=VER
                          android platform version, default 5 for arm, 9 for x86/mips
  --with-android-platform=DIR
                           location of platform dir
```

Just a guess though...

**Comment by folecr** [comment]
The configure flags needed to be updated to match the latest version of spidermonkey. It builds correctly after updating the flags.

00993488b37270886c754ef9576b8543363d63d5 of https://github.com/ricardoquesada/Spidermonkey has my fixes.

**Comment by rolandoam** [comment]
confirming that it also built for me using the new flags

**Comment by nicolasgramlich** [comment]
It would be awesome if this PR could be merged =)

**Comment by dumganhar** [comment]
When using FF-17.0beta3 on android, there are some linking error when building TestJavascript.
Something like as follows:

<pre>
./obj/local/armeabi/js_static.a(jscntxt.o): In function `_ZNSt13basic_filebufIcSt11char_traitsIcEE16_M_setup_codecvtERKSt6localeb.part.102':
(.text._ZNSt13basic_filebufIcSt11char_traitsIcEE16_M_setup_codecvtERKSt6localeb.part.102+0x10): undefined reference to `std::locale::_M_use_facet(std::locale::id const&) const'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `std::basic_filebuf<char, std::char_traits<char> >::imbue(std::locale const&)':
(.text._ZNSt13basic_filebufIcSt11char_traitsIcEE5imbueERKSt6locale[std::basic_filebuf<char, std::char_traits<char> >::imbue(std::locale const&)]+0x1e): undefined reference to `std::locale::_M_get_facet(std::locale::id const&) const'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `std::basic_filebuf<char, std::char_traits<char> >::imbue(std::locale const&)':
(.text._ZNSt13basic_filebufIcSt11char_traitsIcEE5imbueERKSt6locale[std::basic_filebuf<char, std::char_traits<char> >::imbue(std::locale const&)]+0x48): undefined reference to `std::locale::_M_use_facet(std::locale::id const&) const'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `std::basic_filebuf<char, std::char_traits<char> >::showmanyc()':
(.text._ZNSt13basic_filebufIcSt11char_traitsIcEE9showmanycEv[std::basic_filebuf<char, std::char_traits<char> >::showmanyc()]+0x34): undefined reference to `std::_Filebuf_base::_M_seek(long, int)'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `std::basic_filebuf<char, std::char_traits<char> >::showmanyc()':
(.text._ZNSt13basic_filebufIcSt11char_traitsIcEE9showmanycEv[std::basic_filebuf<char, std::char_traits<char> >::showmanyc()]+0x3c): undefined reference to `std::_Filebuf_base::_M_file_size()'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RSbIS4_S5_T1_ES4_.constprop.124':
(.text._ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RSbIS4_S5_T1_ES4_.constprop.124+0x64): undefined reference to `std::ios_base::_M_throw_failure()'
./obj/local/armeabi/js_static.a(jscntxt.o): In function `_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RSbIS4_S5_T1_ES4_.constprop.124':
(.text._ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RSbIS4_S5_T1_ES4_.constprop.124+0x20c): undefined reference to `std::__node_alloc::_M_deallocate(void*, unsigned int)'
</pre>

**Comment by folecr** [comment]
It seems like SpiderMonkey is hardcoded to use STLPORT for C++ support on Android. Cocos2D-X uses GNU libstdc++.

**Comment by folecr** [comment]
My branch has spidermonkey with patches to build with gnu-libstdc++ https://github.com/folecr/spidermonkey.riq/tree/gnu-libstdc++

Builds correctly and TestJavaScript seems to run fine. I will issue a pull request after some more testing.

Could you help test?

**Comment by dumganhar** [comment]
Sure, I will test it right now.

**Comment by dumganhar** [comment]
Merged. Thank all of you. :)

**Comment by nicolasgramlich** [comment]
Yay =)

---

Letters were harmed in this message!

**Pull request merged**
