### PR TITLE
fix cc scale9 sprite bug

### PR DESCRIPTION
**Pull request by biteforest**
fix cc scale9 sprite bug. i didn't write the test file, because it always failed that update submodules.

### CODE REVIEW

**Comment by dumganhar** [comment]
Could you send the test file to me and @folecr? Thank you.

**Comment by biteforest** [comment]
@dumganhar  i've send the test code to you. please check your email. I didn't find @folecr  's email address anywhere.

**Comment by folecr** [comment]
folecr@gmail.com

**Comment by folecr** [comment]
@biteforest - Could you please describe what the bug was that you fixed? Are sprites rotated counter-clockwise in some cases and clockwise in others?

**Comment by biteforest** [comment]
@folecr have you test the testcase i send you?  appearently, the part of  button in testcase is hidden.

**Comment by folecr** [comment]
@biteforest I've added your resource to the test https://github.com/cocos2d/cocos2d-js-tests/pull/131 
I'll review the fix in a couple days.

**Comment by biteforest** [comment]
@folecr I usually write code in c++. so i don't know how to run cocos2d-js-test project.
When i clone cocos2d-js-tests project, i run TestJavascript in VS, but there's a lot of errors when compiling.
so i switch os to mac os. compling is ok, but TestJavascript is running, there're errors from output view like this 
OpenGLTest/OpenGLTest.js:545:TypeError: cc.GLNode is undefined
Cocos2d: (evaluatedOK == JS_FALSE)
So I still work on c++ ~~~

**Comment by folecr** [comment]
@biteforest Thanks for your contributions and your testing.

This is not an issue with your setup - it is a known problem with cocos2d-x : cocos2d-x uses an older cocos2d-js-tests due to issues on Windows (which I think you might have encountered.) We will be fixing it soon so that all developers of cocos2d-x can use the latest tests repository.

Meanwhile, here is how I tested -
- generate patch of your test from latest cocos2d-js-tests (git format-patch c3513d93361d83584941e6b5ca3ceb575427799b ~.. c3513d93361d83584941e6b5ca3ceb575427799b -o ~/tmp )
- apply this patch on the submodule in cocos2d-x (cd samples /Javascript/Shared && git am ~/tmp/001*)
- Now you can build and run with the Scale9Sprite test even on the current cocos2d-x!

I realize this might be inconvenient ... and will work on fixing it soon.
Meanwhile, please let me know if you are able to test with the above (inconvenient) procedure. I was able to reproduce an error in rendering with your tests and will review the fixes next week.

**Comment by biteforest** [comment]
@folecr I have already followed your tutorial, and run the js project successfully. The S9_TexturePacker testcase show me a wrong result without merging my "CCScale9Sprite"pull request.  In my branch of cocos2d-x that fixed CCScale9Sprite, it was rendering right!

**Comment by minggo** [comment]
@folecr 
Can this PR be merged?

**Comment by folecr** [comment]
The tests look good - this patch should be merged! Thanks.

**Pull request merged**
