### PR TITLE
Android native build improvements

### PR DESCRIPTION
**Pull request by newnon**
Build Android project using new CMake 
Everything works out of box 
some time AndroidStudio hangs on build such a big project  
this helps me http://stackoverflow.com/questions/25629368/how-to-fix-android-studio-getting-stuck-executing-gradle-tasks

### CODE REVIEW

**Comment by newnon** [comment]
it also better fix this problem https://github.com/cocos2d/cocos2d-x/issues/16033 because it set arm mode only for armeaby

**Comment by newnon** [comment]
You also can use simple build with Gradle from command line no need to any external build tools

**Comment by minggo** [comment]
@newnon why did you say it is better than https://github.com/cocos2d/cocos2d-x/pull/15676?

**Comment by newnon** [comment]
1 because cmake is more flexibke then NDK - buikd
2 because you don't need to support one more build system

**Comment by newnon** [comment]
For example i've made arm build for armaeby and thumb for armv7a it is not easy with ndk build

**Comment by minggo** [comment]
> because you don't need to support one more build system

We used to ndk-bulid before Android Studio, it is not a new build system. Most people are familiar with it, and i think it is the mainstream usage in NDK world. That's why i ask the google guys to support ndk-build.

Use only cmake is good, but currently the cocos2d-x's cmake build system is complex. And i don't have enough time to refactor it.

**Comment by newnon** [comment]
for example build for arm mode in armv7 less effective as thumb but you can't select arm for armaeby and thumb for armv7 with NDK build but you can with CMake

**Comment by newnon** [comment]
and you can offer both system, may be cmake as default and NDK in comments for easy migration

**Comment by minggo** [comment]
@newnon i am not sure, may be we should use NDK-build as default. Can i debug c++ codes with this PR?

**Comment by newnon** [comment]
Sure you can. You also can edit all c++ code right from Android studio.

**Comment by ghost** [comment]
@newnon 
hi 
i'm trying this PR , but it doesn't work. first it starts to build and then after 3 mins gradle build will be failed.
im using ndk-r12b and android studio 2.3 beta 2 and cocos2d-xv3.14.1. can u please help me with this?

and the error is : 
```
FAILED: cmd.exe /C "cd . && E:\android-ndk-r12b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  -target aarch64-none-linux-android -gcc-toolchain E:/android-ndk-r12b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=E:/android-ndk-r12b/platforms/android-21/arch-arm64 -fPIC -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -std=c++11 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -std=c++11 -frtti -fexceptions -std=c++11 -Wno-deprecated-declarations -Wno-reorder -stdlib=libc++ -g -Wall  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libMyGame.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libMyGame.so CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.o CMakeFiles/MyGame.dir/Classes/HelloWorldScene.cpp.o CMakeFiles/MyGame.dir/proj.android-studio/app/jni/hellocpp/main.cpp.o  lib/libcocos2d.a -Wl,-whole-archive lib/libcocos2dxandroid_static.a -Wl,-no-whole-archive lib/libcocos2dInternal.a ../../../../../../cocos2d/external/zlib/prebuilt/android/arm64-v8a/libz.a lib/libunzip.a ../../../../../../cocos2d/external/jpeg/prebuilt/android/arm64-v8a/libjpeg.a ../../../../../../cocos2d/external/png/prebuilt/android/arm64-v8a/libpng.a ../../../../../../cocos2d/external/tiff/prebuilt/android/arm64-v8a/libtiff.a lib/libtinyxml2.a ../../../../../../cocos2d/external/freetype2/prebuilt/android/arm64-v8a/libfreetype.a ../../../../../../cocos2d/external/websockets/prebuilt/android/arm64-v8a/libwebsockets.a ../../../../../../cocos2d/external/curl/prebuilt/android/arm64-v8a/libcurl.a ../../../../../../cocos2d/external/curl/prebuilt/android/arm64-v8a/libssl.a ../../../../../../cocos2d/external/curl/prebuilt/android/arm64-v8a/libcrypto.a lib/libxxhash.a -lGLESv1_CM -lGLESv2 -lEGL -llog -landroid -lOpenSLES ../../../../../../cocos2d/external/webp/prebuilt/android/arm64-v8a/libwebp.a ../../../../../../cocos2d/external/chipmunk/prebuilt/android/arm64-v8a/libchipmunk.a lib/libbullet.a lib/librecast.a cocos2d/cocos/libcpufeatures.a -ldl -lm "E:/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a" "E:/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a" "E:/android-ndk-r12b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libandroid_support.a" && cd ."
E:/android-ndk-r12b/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: cannot find -lc++
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
``` 

and Thanks for this patch.

**Comment by newnon** [comment]
@mhbich
What did you try to build? test or project from template?

**Comment by newnon** [comment]
@mhbich
try again i found one more place where was libc++

**Comment by ghost** [comment]
@newnon 
it works now , Thanks mate.
you ARE my HERO ^_^

**Comment by minggo** [comment]
@newnon thanks, i will test it and merge it if it doesn't break compatibility, for example `cocos compile -p android --android-studio` can work.

**Comment by newnon** [comment]
you must remove native build phase from cocos compile now it makes by gradle

**Comment by minggo** [comment]
Fond the error
```
External Native Build Issues
Build command failed.
Error while executing '/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/bin/cmake' with arguments {-H/Users/minggo/SourceCode/cocos2d-x -B/Users/minggo/SourceCode/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/.externalNativeBuild/cmake/release/armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/minggo/SourceCode/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/build/intermediates/cmake/release/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=9 -DCMAKE_CXX_FLAGS=-frtti -fexceptions -DCMAKE_FIND_ROOT_PATH= -DANDROID_STL=c++_static -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DBUILD_CPP_TESTS=FALSE -DBUILD_LUA_LIBS=FALSE -DBUILD_JS_LIBS=FALSE}
-- Configuring incomplete, errors occurred!
CMake Error at /Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/android.toolchain.cmake:837 (message):
  ANDROID_STL is set to invalid value "c++_static".
  The possible values are:
    none           -> Do not configure the runtime.
    system         -> Use the default minimal system C++ runtime library.
    system_re      -> Same as system but with rtti and exceptions.
    gabi++_static  -> Use the GAbi++ runtime as a static library.
    gabi++_shared  -> Use the GAbi++ runtime as a shared library.
    stlport_static -> Use the STLport runtime as a static library.
    stlport_shared -> Use the STLport runtime as a shared library.
    gnustl_static  -> (default) Use the GNU STL as a static library.
    gnustl_shared  -> Use the GNU STL as a shared library.
Call Stack (most recent call first):
  /Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/share/cmake-3.4/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:39 (project)
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Error:executing external native build for cmake /Users/minggo/SourceCode/cocos2d-x/CMakeLists.txt
Build command failed.
Error while executing '/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/bin/cmake' with arguments {-H/Users/minggo/SourceCode/cocos2d-x -B/Users/minggo/SourceCode/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/.externalNativeBuild/cmake/debug/armeabi-v7a -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi-v7a -DANDROID_NDK=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/minggo/SourceCode/cocos2d-x/tests/cpp-empty-test/proj.android-studio/app/build/intermediates/cmake/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=9 -DCMAKE_CXX_FLAGS=-frtti -fexceptions -DCMAKE_FIND_ROOT_PATH= -DANDROID_STL=c++_static -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_NEON=TRUE -DBUILD_CPP_TESTS=FALSE -DBUILD_LUA_LIBS=FALSE -DBUILD_JS_LIBS=FALSE}
-- Configuring incomplete, errors occurred!
CMake Error at /Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/android.toolchain.cmake:837 (message):
  ANDROID_STL is set to invalid value "c++_static".
  The possible values are:
    none           -> Do not configure the runtime.
    system         -> Use the default minimal system C++ runtime library.
    system_re      -> Same as system but with rtti and exceptions.
    gabi++_static  -> Use the GAbi++ runtime as a static library.
    gabi++_shared  -> Use the GAbi++ runtime as a shared library.
    stlport_static -> Use the STLport runtime as a static library.
    stlport_shared -> Use the STLport runtime as a shared library.
    gnustl_static  -> (default) Use the GNU STL as a static library.
    gnustl_shared  -> Use the GNU STL as a shared library.
Call Stack (most recent call first):
  /Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/share/cmake-3.4/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:39 (project)
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Error:executing external native build for cmake /Users/minggo/SourceCode/cocos2d-x/CMakeLists.txt
```

**Comment by minggo** [comment]
What Android Studio version is required? Mine is 2.2.

**Comment by newnon** [comment]
may be you have too old ndk?
or not actual version of cmake try to use embedded ndk and update sdk
i use 2.2.3 version of Android Studio

**Comment by newnon** [comment]
my cmake file path looks diferent /Development/android-sdk/cmake/3.6.3155560/bin/cmake
and toolchain path /Development/android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake
how do you build with some command line or right from android studio?

**Comment by minggo** [comment]
I just use Android Studio to build the project. My NDK is r13.

**Comment by newnon** [comment]
try to update cmake you toolchain path is /Users/minggo/bin/android/adt-bundle-mac-x86_64/sdk/cmake/android.toolchain.cmake from cmake folder, and on my system from ndk /android-sdk/ndk-bundle/build/cmake/android.toolchain.cmake

**Comment by ghost** [comment]
@newnon 
hi , there is another missing header file , can you please help to fix it?
`Error:fatal error: 'bullet/LinearMath/btScalar.h' file not found`

thanks

**Comment by newnon** [comment]
may be you just forgot to run download-deps.py ?

**Comment by ghost** [comment]
@newnon i have that file in cocos2d\external\bullet\LinearMath directory , but in android studio it's not added . 
and i did run download-deps.py , but let me check it out.

**Comment by newnon** [comment]
firs what did you try to compile? test or template which one? try to add "-DUSE_BULLET=TRUE" to cmake { arguments
yes by default bullet is off i will add one more commit to fix it

**Comment by ghost** [comment]
@newnon thanks man , it works now. 
one more question , for enabling box2d i just have to add  "-DUSE_BOX2D=TRUE" to cmake args in build.gradle , right?

**Comment by newnon** [comment]
Yes but it can conflict with chipmunk i'me not sure

**Comment by ghost** [comment]
@newnon 
hi , can you please tell me how can i enable spine in a project?? 
it can't complie the project if i include spine in a class.
thank you

**Comment by newnon** [comment]
Ok i look whats wrong may be it is some problems with include path for spine
may be you can try #include "editor-support/spine/spine.h" ?

**Comment by ghost** [comment]
@newnon 
already tried that line , but no luck . it still can't compile. 
it says : 
`Error:fatal error: 'spine/spine.h' file not found`

**Comment by newnon** [comment]
try to edit cmake file include_directories(
  /usr/local/include/GLFW
  /usr/include/GLFW
  ${COCOS2D_ROOT}/cocos
  ${COCOS2D_ROOT}/cocos/platform
  ${COCOS2D_ROOT}/cocos/audio/include/
  ${COCOS2D_ROOT}/cocos/editor-support
  Classes
)

**Comment by minggo** [comment]
We still consist to use ndk-build instead of cmake in Android Studio support. So close this PR.

**Pull request closed without merging**
