### PR TITLE
Removed scale factor for label shadow

### PR DESCRIPTION
**Pull request by danutchereches**
Scale factor is not needed here.

### CODE REVIEW

**Comment by danutchereches** [comment]
Is this related #14004 ?

**Comment by pandamicro** [comment]
@liamcindy Please review both #14107 and #14004 
@WenhaiLin will help you to confirm

**Comment by WenhaiLin** [comment]
@pandamicro It's OK for merge.

**Comment by joewan** [comment]
@liamcindy @WenhaiLin @pandamicro Please review #14004

**Pull request merged**
