### PR TITLE
converts  endline form windows to unix

### PR DESCRIPTION
**Pull request by ricardoquesada**
These changes were generated automatically by Github for Windows.

Basically it converts the `\r\n` to `\n` and adds converting rules in
.gitattributes

This way we won't have issues on windows and unix.

### CODE REVIEW

**Comment by minggo** [comment]
@ricardoquesada 
This pull request has some conflicts. I think it is because @dumganhar fixed some bugs and merged them. Can i convert it by a command line? I want to convert it again and send a new pull request.

**Comment by ricardoquesada** [comment]
@minggo 

Yes, sure. The way to generate it again is by:
1. Open a Windows machine
2. Download "Github for Windows"
3. Run "Github for Windows"
4. Select the cocos2d-x repo
5. Click on Tools -> Settings
6. Click on "Add the recommended .gitattribute files"
7. Click on "update"

done.

**Comment by minggo** [comment]
@ricardoquesada 
Thanks. I will try the commands.
And i will close this pull request.

**Comment by ricardoquesada** [comment]
I sent another one here:
https://github.com/cocos2d/cocos2d-x/pull/3713

**Pull request closed without merging**
