### PR TITLE
Fixed to use TexturePacker with cocosstudio.

### PR DESCRIPTION
**Pull request by yalab**
This is same as https://github.com/cocos2d/cocos2d-x/pull/16008 for UIButton and Slider.

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@yalab could you please add a test case?

**Comment by yalab** [comment]
@minggo Which file should I write test?

**Comment by minggo** [comment]
@yalab you can add a test case in `tests/cpp-tests/Classes/UITest/CocoStudioGUITest`

**Pull request merged**
