### PR TITLE
fix building with system prebuilt libs

### PR DESCRIPTION
**Pull request by martell**
@ricardoquesada Hi again :)

can this PR also be merged into the 3.7.1 branch if possible.
currently building within a distro is broken without this

### CODE REVIEW

**Comment by martell** [comment]
Checking out files:  59% (357/605)
Checking out files:  60% (363/605)
Slave went offline during the build

every build passes. the ios slave just decided to go offline :/

**Comment by WenhaiLin** [comment]
[ci rebuild]

**Comment by martell** [comment]
@WenhaiLin Thank you :)
All looks good

**Comment by ricardoquesada** [comment]
yes, sure. looks good to me.

**Comment by pandamicro** [comment]
Hi, @martell If you want this PR be merged into v3.7.1, please resubmit a PR to the branch v3.7.1.

v3 branch won't be merged to v3.7.1, instead, we will merge v3.7.1 branch into v3 branch once it's released

**Comment by martell** [comment]
Sure :)
I will do one after this is merged to HEAD

**Comment by pandamicro** [comment]
Ok, this one is merged

**Pull request merged**
