### PR TITLE
fix Shader-Sprite crash when shader can not compile

### PR DESCRIPTION
**Pull request by super626**
Blur shader can not compile on XiaoMi3 because of the for statement in the shader.
And it will crash.

### CODE REVIEW

**Comment by super626** [comment]
Move from #14687

**Comment by minggo** [comment]
So should we modify the shader instead?

**Comment by super626** [comment]
XiaMi3 does not support "for" statements and "for" could not be unrolled. In this test case, we adjust the blur radius.

**Comment by minggo** [comment]
So i think we can do it in two ways:
1. Delete this test case, because many developers will refer to test cases to write their codes, and they don't know that the test case has some limitation.
2. Create a documents that describe the issues that we found during development

I prefer method 2, because all developers will benefit from it.

**Comment by zhaijialong** [comment]
那个for的终止条件是个uniform。。这应该es2.0不允许的，改成常量/宏吧，话说cocos还缺少管理shader里宏的机制。。。

**Comment by super626** [comment]
@ricardoquesada Any idea about this?

**Comment by ricardoquesada** [comment]
@super626  your PR looks good to me. No need to remove the test case. 

@minggo what part of this PR you don't like? thanks.

**Comment by minggo** [comment]
This PR just avoid issues on some devices, and we will meet this problem again if we don't have a method to handle it. That's why i ask for some mechanism to handle it above.

**Comment by ricardoquesada** [comment]
yes, but your proposals were:
- remove the sample: doesn't solve the issue.
- or document it: doesn't solve the issue... cocos2d-x will keep crashing if we don't apply @super626 patch.

What I mean... we can still add more documentation, but is there something that you don't like about the patch?

I mean, the correct solution is to detect the device, and use a shader that doesn't use `for` when running on Xioami3... that that will take a lot of time, but it is the correct solutiuon.

**Comment by minggo** [comment]
This PR looks good to me.
I just mean we need to add a documentation about it, it will help us and all developers, and yep, it is another issue. I just mention it here.

**Comment by ricardoquesada** [comment]
Ok. thanks. So I'm merging this PR.

**Pull request merged**
