### PR TITLE
v4: Fix win32 resource search path to be relative to the executable.

### PR DESCRIPTION
**Pull request by vovkasm**
This is the patch against `v4-develop` branch. It contains commits from #10431 that was done against `v3`, but additionally tune new `js-tests` MSVC project.

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by minggo** [comment]
@vovkasm 
Could you please fix conflict or create a new pull request for it?
Thanks.

**Comment by vovkasm** [comment]
Yes, I'll do it during the week.

**Comment by minggo** [comment]
Thanks.

**Comment by vovkasm** [comment]
Conflict fixed, but please, do not merge it yet. I'll port templates fix (#10784).

**Comment by vovkasm** [comment]
Hmm.. Are templates broken in `v4-develop` branch?
And what to do with it? Merge this pull request as is or wait until templates will be fixed?

Steps and errors:
1. generate project

``` sh
$ cocos new -l cpp
Running command: new
> Copy template into C:\msys64\home\vovkasm\tmp\MyCppGame
> Copying cocos2d-x files...
> Rename project name from 'HelloCpp' to 'MyCppGame'
> Replace the project name from 'HelloCpp' to 'MyCppGame'
> Replace the project package name from 'org.cocos2dx.hellocpp' to 'org.cocos2dx.MyCppGame'
> Replace the mac bundle id from 'org.cocos2dx.hellocpp' to 'org.cocos2dx.MyCppGame'
> Replace the ios bundle id from 'org.cocos2dx.hellocpp' to 'org.cocos2dx.MyCppGame'
```
1. open in Visual Studio
   libSpine project not found
2. try "Build Solution" -> many-many errors
   many compile errors

**Comment by vovkasm** [comment]
@minggo 
I fix cpp and js templates, now their works. But still can't deal with lua templates, because project generated by `cocos new -l lua` command still not builds.

**Comment by vovkasm** [comment]
@minggo 
Lua templates are fixed. I think that the patch now is ready to be merged.

**Comment by minggo** [comment]
@vovkasm 
v4 is suspend, now we all focus on v3.x.
Sorry about that.

**Pull request closed without merging**
