### PR TITLE
Modify that parsing attribute "fontName" of TextReader

### PR DESCRIPTION
**Pull request by pipu**

### CODE REVIEW

**Comment by minggo** [comment]
[ci rebuild]

**Comment by joewan** [comment]
"微软雅黑".

we'd better define default font macro, so that users can replace default font conveniently.
@minggo

**Comment by darkdukey** [comment]
@pipu Can you change the default font to some universal font instead of "微软雅黑"

**Comment by pipu** [comment]
Okay.
I could change the default font to "Helvetica" for TextReader.
But, I gotta discuss it with designer of cocosstudio first.

**Comment by minggo** [comment]
Yep, please don't use magic string as @joewan  said.

**Comment by minggo** [comment]
@pipu
Any update?

**Comment by pipu** [comment]
I still wait for design of designer of CocosStudio editor.

**Comment by minggo** [comment]
I think there are two things:
- use macro in codes
- use another font as default font

I think you can use macro first.
Then i will merge this pull request.

**Comment by pipu** [comment]
@minggo 
I think you could merge this pull request.
Because, this pull request fixes that parse ".ttf" file to set font name for Text widget of ui framework in TextReader.cpp.
And then, I think that I could use another font as default font refer to your advise at next pull request.

Thanks a lot.

**Pull request merged**
