### PR TITLE
fix a problem where WebSocket messages may pile up

### PR DESCRIPTION
**Pull request by billtt**
In the original implementation, only one message (frame) will be processed per tick, so the WebSocket messages will pile up if server sends them faster than client's frame rate.
Fixed by processing all messages in the queue in one update.

### CODE REVIEW

**Comment by pandamicro** [comment]
@yangws Can you help to review this PR ?

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Logic OK, I think it can be merged, @dumganhar Please confirm

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by dumganhar** [comment]
@pandamicro, it's ok for me for merging this patch. :)

**Pull request merged**
