### PR TITLE
a solution about bug #942

### PR DESCRIPTION
**Pull request by leopoldchen**
#942 Invoke CCScheduler:sharedScheduler():scheduleScriptFunc in lua may cause crashion.

this solution is quite similar to the original unscheduleSelector. 
use a flag to mark if we want to delete the scriptfunc entry.
and in the unscheduleScriptFunc function, we only set this flag (currentTimerSalvaged) as true, then in the tick function, we delete it after timer update.

file list:
CCScheduler.h/cpp
&test code is in hello.lua

### CODE REVIEW

**Comment by minggo** [comment]
Thank you.
But please not add these files:
cocos2d-win32.vc2010.sdf
ipch/cocos2d-win32-5f8e8667/libcocos2d-f1ffc4f1.ipch
ipch/cocos2d-win32-5f8e8667/libcocos2d-f1ffc4f1.ipch

**Comment by leopoldchen** [comment]
I delete these files now

**Comment by minggo** [comment]
Thank you.
Because pull request: https://github.com/cocos2d/cocos2d-x/pull/706 refactor the lua supporting, and fix this bug.
So, I think I should close the pull request.
Sorry.

**Comment by leopoldchen** [comment]
I see, is that a cool job done by YAOGUAI?
waiting for it!!!

**Comment by minggo** [comment]
Yes, it is.
He has developed with lua for a few games.
He is an expert of lua.

**Pull request closed without merging**
