### PR TITLE
add setIgnoreAnchorPointForPosition(bool) func, clean lines

### PR DESCRIPTION
**Pull request by njh0602**
and, removed completed @todo comments.

### CODE REVIEW

**Comment by minggo** [comment]
@njh0602 Thanks. But i think it is better to remove the usage of `ignoreAnchorPointForPosition()`. Because this function is used so many places, so i think it's better not to modify it.

**Comment by njh0602** [comment]
@minggo Thanks to opinion, But `ignoreAnchorPointForPosition()` call `setIgnoreAnchorPointForPosition()`. So I think It does not affect the existing codes.

**Comment by minggo** [comment]
But i will bring many warnings.

**Comment by njh0602** [comment]
@minggo i think it has some mistakes. i will check again.

**Comment by njh0602** [comment]
@minggo i understand your opinion now. for example, Sprite class has ignoreAnchorPointForPosition and many other classes? if i fix all classes methods, is it ok?

**Comment by minggo** [comment]
Yep, there are two cases:
- Classes that inherits from Node and override `ignoreAnchorPointForPosition()` should be deprecated too and add new implementation
- codes that invoked `ignoreAnchorPointForPosition()` should use new functions

**Comment by njh0602** [comment]
@minggo ok, i will be back.

**Pull request closed without merging**
