### PR TITLE
When can Ido batching for sprite3D(/mesh)?

### PR DESCRIPTION
**Pull request by gcheih**
In order to reduce draw call, I need to batch my models.
When can I do batching for sprite3D(/mesh)?
thank you~~QQ

### CODE REVIEW

**Comment by gcheih** [comment]
Sorry I push the message on the wrong place~~

**Comment by darkdukey** [comment]
@super626 Can you take a look?

**Comment by minggo** [comment]
@gcheih 
So can i close this pull request?

**Comment by gcheih** [comment]
Yes! thank you!! please

**Pull request closed without merging**
