### PR TITLE
Upgrade minizip to 1.2.0

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by halx99** [comment]
require: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/375

**Comment by minggo** [comment]
You should update `external/config.json` to `v3-deps-164`.

**Comment by minggo** [comment]
@halx99 it seems new version of minizip can not compile on mac.

**Comment by halx99** [comment]
> @halx99 it seems new version of minizip can not compile on mac.

ok, let me check it.

**Comment by halx99** [comment]
see: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/378

**Comment by minggo** [comment]
@halx99 you should update external to deps-166

**Comment by halx99** [comment]
ok, I will do when I can access github.com after go back to workplace beijing.

Best Regards, HALX99
Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
