### PR TITLE
JPEG and File fixes

### PR DESCRIPTION
**Pull request by mrmop**
- Fixes to JPEG loader
- Fixes to image loader to load tiff and unknown formats properly

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi Mat,
Since this pull request cannot be automatically merged, could you pull our latest codes?

**Comment by mrmop** [comment]
No problem, would this be with the main repo or your  dumganhar repo?

**Comment by dumganhar** [comment]
Hi,it certainly should be the main repo, and gles20 branch.:-) Not my repo.
ÔÚ 2012-11-30 ÏÂÎç10:54£¬"Mat Hopwood" notifications@github.comÐ´µÀ£º

**Comment by mrmop** [comment]
I've pulled and merged the latest. Will the changes be include din the next release?

**Comment by dumganhar** [comment]
Sure, it will be in next release.
But this Pull Request still cannot be automatically merged.
And it contains lots of file changes, about **674** files, why does it contain so many changes?

**Comment by dumganhar** [comment]
Did you use the command <code>git pull https://github.com/cocos2d/cocos2d-x.git gles20</code> ?
I didn't see any _merged_ codes.

**Comment by mrmop** [comment]
Yes thats the branch I used. I have no idea why there were so many changed as I am not responsible for them, I simply merged them into my branch from the main repo

**Comment by dumganhar** [comment]
OK, I will pick some of your commits tomorrow. Thanks, Mat.

**Comment by dumganhar** [comment]
Merged at https://github.com/cocos2d/cocos2d-x/pull/1706.
Thanks.

**Pull request closed without merging**
