### PR TITLE
 README for default cocos projects

### PR DESCRIPTION
**Pull request by HTC77**
You can add README, .gitignore and default Screenshot.png files into default cpp/lua or js templates in cocos2d-x. It's important when you pushing your project to GitHub and introducing the cocos2d-x to GitHub users and game developers.
[init.zip](https://github.com/cocos2d/cocos2d-x/files/3124686/init.zip)

### CODE REVIEW

**Comment by HTC77** [comment]
https://docs.cocos2d-x.org/cocos2d-x/en/installation/prerequisites.html

**Comment by minggo** [comment]
Sorry, i can not catch the idea. What's the PR for?

**Comment by HTC77** [comment]
> Sorry, i can not catch the idea. What's the PR for?

When we create a cocos project by `cocos new "project name"...` command, it's better to add some useful files (automatically by the cocos engine) to the default cocos2d-x project such as :

- Default README.md file (it's default [cocos2d-x README](https://github.com/cocos2d/cocos2d-x/blob/v3/README.md) on GitHub + `` tag at the top)
- Defualt .gitignore file (ignores all but Classess & resources)
- Default Screenshot.png file with default cocos2d-x picture

It's better to know game and game engine when game source has pushed on GitHub.

Screenshot (391)
Screenshot (392)

**Comment by HTC77** [comment]
> > Sorry, i can not catch the idea. What's the PR for?
> 
> when we create a cocos project by `cocos new "project name"...` command, it's better to add some useful files to the default cocos2d-x project such as :
> 
> * default README.md file (it's default [cocos2d-x README](https://github.com/cocos2d/cocos2d-x/blob/v3/README.md) on GitHub + `` tag at the top)
> * defualt .gitignore file (ignores all but Classess & resources"
> * default Screenshot.png file with default cocos2d-x picture
>   it's better to know game and game engine when game source has pushed on GitHub.

Screenshot (391)
Screenshot (392)

**Comment by minggo** [comment]
I get your idea, you just want to show cocos2d-x git repo in README? Right? If so, i think add the repo information in other places is better.

**Pull request closed without merging**
