### PR TITLE
V3 WP8/Universal App fixes for Particle3D

### PR DESCRIPTION
**Pull request by stammen**
This pull request fixes the broken builds for WP8/Universal App. The missing Particle3D files were added. The precompiled shaders for WP8 were also updated.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@stammen 
Now the v3 branch WP8/universal app is broken in your side?

**Comment by stammen** [comment]
Yes. It was broken. This pull request fixes it.

**Comment by zilongshanren** [comment]
@stammen  But it is built successfully on our Jenkins slave. Weird...
BTW, do you know how to change Path environment variable in Windows salve?

**Comment by stammen** [comment]
@andyque  to change Path environment variable in Windows slave?
1. Right click on Windows Icon in bottom left hand corner of screen
2. Select System
3. Select Advanced system settings
4. Click on Environment Variables button
5. Select Path from System variables list

**Comment by zilongshanren** [comment]
Thanks, @stammen 

I did this, but it doesn't work. After upgrading Jenkins to 1.602, the problem was solved.

**Comment by stammen** [comment]
OK. Thanks for the update. I will upgrade my Jenkins server to 1.602 as well.

**Pull request merged**
