### PR TITLE
Fix a collision detection bug at TableView

### PR DESCRIPTION
**Pull request by ledyba**

### CODE REVIEW

**Comment by dumganhar** [comment]
What did you mean `collision detection`?

**Comment by dumganhar** [comment]
@ledyba 
What is the bug?  Could you describe more about it ? Thanks.

**Comment by ledyba** [comment]
you cannot touch the cell in table view because the condition of the if-statement(I fixed at this pull req) was wrong.

**Comment by dumganhar** [comment]
@ledyba , thank you.
But could you please add a test case to `TableViewTest` ?

**Comment by ledyba** [comment]
ok, thanks. please wait.

**Comment by cocosQA** [comment]
Dear ledyba:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6476
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
