### PR TITLE
arc support #12518

### PR DESCRIPTION
**Pull request by Shulepov**
Arc still needs to be enabled/disabled manually in project settings. But that the only thing that should be done.

### CODE REVIEW

**Comment by pandamicro** [comment]
Thanks for your contribution, please submit it to v3 branch, because we are closing v3.8

**Comment by zilongshanren** [comment]
@Shulepov @pandamicro 
I think cocos2d-x can't support ARC. There are many `autorelease` call scattered in the code base.
And the patch only modify the template project...

**Comment by Shulepov** [comment]
@zilongshanren
Actually, autorelease used in subproject. And if main project support ARC, there is not requirement for any sub-project or library to also support ARC. So it's safe to do this.

I modified only template project, because it won't give any performance penalties for cocos2d-x itself, also it will simplify integration of different libraries and sdks, and writing Obj-C code itself.

 Ofc, it's easy to do this migration manually each time, but i found that slightly annoying...

**Comment by zilongshanren** [comment]
@Shulepov  
I see. Feel free to reopen this PR. Thanks.

**Comment by zilongshanren** [comment]
@Shulepov  Maybe you should send a PR in v3 branch.

**Pull request closed without merging**
