### PR TITLE
Camera Background Clear brush

### PR DESCRIPTION
**Pull request by super626**
Add camera background clear brush
And test demo

Usage
camera->setBackGroundBrush(CameraBackGroundBrush::createSkyboxBrush(...));
camera->setBackGroundBrush(CameraBackGroundBrush::createDepthBrush(...));
And so on.

### CODE REVIEW

**Comment by pandamicro** [comment]
@super626 Android build failed, please fix it

**Comment by pandamicro** [comment]
@dabingnn please review this PR
I think the API added is proper

**Comment by dabingnn** [comment]
I like the logic, it is a good refactor and enhancement for camera clear.
A small issue in this pr: `drawBackGround` should be `drawBackground`.

**Comment by super626** [comment]
@dabingnn @pandamicro 
Done

**Pull request closed without merging**
