### PR TITLE
Cocos2dx master hotfix (small bug)

### PR DESCRIPTION
**Pull request by gelldur**
If in .plist file we don't have those lines
    <key>textureFileName</key>
    <string>mainscreen.png</string>

We should have CCAssert now. Before changes application crush with SIGSEGV

### CODE REVIEW

**Comment by gelldur** [comment]
?

**Comment by dumganhar** [comment]
Could you also send this patch to develop branch?

**Comment by gelldur** [comment]
ok

**Comment by gelldur** [comment]
OK i merge to master  + small fix in documentation. I can't find gif support.

Here is PR for develop: https://github.com/cocos2d/cocos2d-x/pull/4846

**Comment by dumganhar** [comment]
Master branch is only for critical bug fixes. So I closed this PR. 
BTW, I have merged your PR of develop branch. Thanks.

**Pull request closed without merging**
