### PR TITLE
Remove Swap Alpha Operate in the nativeInitBitmapDC

### PR DESCRIPTION
**Pull request by Yodesoft**
Swap Alpha in the nativeInitBitmapDC is not necessary. 
Remove those codes to get a great performance improvement.

### CODE REVIEW

**Comment by dumganhar** [comment]
@Yodesoft 
Why isn't the swap alpha operation needed?

**Comment by Yodesoft** [comment]
Each value of ARGB is the same value, so we don't need to swap alpha.

**Comment by minggo** [comment]
Now the value passed into opengl is RGBA. So should swap alpha.

**Comment by Yodesoft** [comment]
ARGB to RGBA is correct way, but each value of the data come from the canvas.drawText is as below:
11011100,11011100,11011100,11011100
10010010,10010010,10010010,10010010
As you saw, swap alpha is not necessary, we dont have to do swap.

**Comment by minggo** [comment]
@Yodesoft 
I will test your commit.
But i still don't understand your meaning.
I can not find clues by the data you pasted.

**Comment by Yodesoft** [comment]
We dump the bitmap data(drawn by canvas.drawText) to binary format, and found that each value of RGBA of one point is same value all the time. 

example:
one point from bitmap data is 2459079314(unsigned int)
to RGBA is 146,146,146,146
to binary is 11011100,11011100,11011100,11011100
If value of R is always equal value of A, so swap alpha is not necessary.

Hope those infomations could help you understand what i meaning.

**Comment by minggo** [comment]
Can you confirm all R equals to A?

**Comment by Yodesoft** [comment]
Yes.
I write a testcase in nativeInit Bitmap DC then found all R is equals A.

This commit was tested on my Desire HD with Android 4.2.1. Of course, more tests needed.

**Pull request closed without merging**
