### PR TITLE
Remove boring logs in cocos studio supporting module.

### PR DESCRIPTION
**Pull request by xpol**
They are helpless for debugging, we should use break points for debugging.

They are really boring and useless, I just load one `csb` I got:

> [LUA-print] Loading "my.csb"...
> suffix = csb
> textureSize = 0
> classname = Node
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d086a00
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName clickTab cannot be found
> size = 1
> classname = Button
> callBackName clickTab cannot be found
> size = 2
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d08d600
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d08e200
> child = 0x13d088200
> child = 0x13d087a00
> classname = Panel
> callBackName clickTab cannot be found
> size = 1
> classname = Button
> callBackName  cannot be found
> size = 2
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13c8c9e00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c8caa00
> child = 0x13d099a00
> child = 0x13c894200
> classname = Panel
> callBackName clickTab cannot be found
> size = 1
> classname = Button
> callBackName  cannot be found
> size = 2
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13c900a00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c901600
> child = 0x13c8f7200
> child = 0x13c8f6a00
> classname = Panel
> callBackName clickTab cannot be found
> size = 1
> classname = Button
> callBackName  cannot be found
> size = 2
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d0cdc00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d0ce800
> child = 0x13d81f600
> child = 0x13c90e600
> child = 0x13d087200
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d826600
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c90ee00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d832c00
> child = 0x13d820e00
> classname = Panel
> callBackName  cannot be found
> size = 16
> classname = ListView
> Stencil buffer is not enabled.
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d0d9400
> classname = ImageView
> callBackName  cannot be found
> size = 2
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c85c400
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c924a00
> child = 0x13d0d9c00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c91ca00
> child = 0x13d0d8c00
> child = 0x13d0dc400
> classname = Panel
> callBackName  cannot be found
> size = 8
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d103000
> child = 0x13d833200
> classname = Button
> callBackName clickBack cannot be found
> size = 0
> child = 0x13d103800
> classname = Button
> callBackName clickFront cannot be found
> size = 0
> child = 0x13d845e00
> classname = Button
> callBackName clickZoom cannot be found
> size = 0
> child = 0x13d0ab800
> classname = Button
> callBackName clickCloth cannot be found
> size = 0
> child = 0x13d83ba00
> classname = Button
> callBackName clickClear cannot be found
> size = 0
> child = 0x13d85e400
> classname = Button
> callBackName clickPalette cannot be found
> size = 1
> classname = ImageView
> libpng warning: iCCP: known incorrect sRGB profile
> callBackName  cannot be found
> size = 0
> child = 0x13d118600
> child = 0x13d127600
> classname = Button
> callBackName clickErase cannot be found
> size = 0
> child = 0x13d12a600
> child = 0x13c927800
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Button
> callBackName back2Diy cannot be found
> size = 0
> child = 0x13d85f200
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d155e00
> child = 0x13d14d200
> classname = ListView
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d160600
> classname = Text
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c930a00
> child = 0x13d160e00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c913c00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d174800
> child = 0x13d15fe00
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d176200
> classname = Text
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c935000
> child = 0x13d176a00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d865e00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c941200
> child = 0x13d860600
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d106a00
> classname = Text
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d86b600
> child = 0x13d107200
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d879c00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d190a00
> child = 0x13d866a00
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d87bc00
> classname = Text
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d878800
> child = 0x13d87c400
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d88f800
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d182400
> child = 0x13d87b400
> child = 0x13d163600
> child = 0x13d85ea00
> classname = Panel
> callBackName  cannot be found
> size = 5
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13c944400
> child = 0x13c943800
> classname = Button
> callBackName backFromSplash cannot be found
> size = 0
> child = 0x13c944c00
> classname = Button
> callBackName clickClearInSplash cannot be found
> size = 0
> child = 0x13d89a400
> classname = Button
> callBackName gotoCompleteFromSplash cannot be found
> size = 0
> child = 0x13d8a9600
> classname = Button
> callBackName clickZoomInSplash cannot be found
> size = 0
> child = 0x13d8b8a00
> child = 0x13c823000
> classname = Panel
> callBackName  cannot be found
> size = 6
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13c947c00
> child = 0x13d8c1e00
> child = 0x13d8c1200
> classname = Button
> callBackName back2DiyAdv cannot be found
> size = 0
> child = 0x13d8c2600
> classname = Button
> callBackName frontFromGlitch cannot be found
> size = 0
> child = 0x13d8d1800
> classname = Button
> callBackName pauseGlitch cannot be found
> size = 0
> child = 0x13d8e0a00
> classname = Button
> callBackName clearGlitch cannot be found
> size = 0
> child = 0x13d18ba00
> classname = Button
> callBackName clickZoomInGlitch cannot be found
> size = 0
> child = 0x13d8e1000
> child = 0x13d8c0a00
> classname = Panel
> callBackName  cannot be found
> size = 6
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13c94d200
> child = 0x13c94c600
> classname = Button
> callBackName back2DiyAdvFromMosic cannot be found
> size = 0
> child = 0x13c94da00
> classname = Button
> callBackName frontFromMosic cannot be found
> size = 0
> child = 0x13d8f1a00
> classname = Button
> callBackName clearMosic cannot be found
> size = 0
> child = 0x13d8f9a00
> classname = Button
> callBackName clickShape cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d90aa00
> child = 0x13d90a200
> classname = Button
> libpng warning: iCCP: known incorrect sRGB profile
> callBackName clickMosicShape cannot be found
> size = 2
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c956e00
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d1a9a00
> child = 0x13d889600
> classname = Button
> callBackName clickMosicShape cannot be found
> size = 2
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d1b0c00
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d1b2600
> child = 0x13d1aa600
> classname = Button
> callBackName clickMosicShape cannot be found
> size = 2
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d923400
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d1c0600
> child = 0x13d91d800
> child = 0x13d909a00
> child = 0x13d901a00
> classname = Button
> callBackName clickZoomInMosic cannot be found
> size = 0
> child = 0x13d1c1200
> child = 0x13d8e9000
> classname = Panel
> callBackName  cannot be found
> size = 8
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d1bba00
> child = 0x13d1bae00
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Button
> callBackName openKeyboard cannot be found
> size = 0
> child = 0x13d1c3000
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c969800
> classname = Button
> callBackName clickPaletteInWord cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d1d8800
> child = 0x13c971a00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d1d9400
> child = 0x13d1c2800
> classname = Button
> callBackName clickBackFromWorld cannot be found
> size = 0
> child = 0x13d1eb200
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d1e1a00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d1f1e00
> classname = Button
> callBackName clickClothInWord cannot be found
> size = 0
> child = 0x13d1f9e00
> classname = Button
> callBackName openKeyboard cannot be found
> size = 0
> child = 0x13d201e00
> classname = Button
> callBackName clickZoomInWord cannot be found
> size = 0
> child = 0x13d209e00
> child = 0x13d1ba600
> classname = Panel
> callBackName  cannot be found
> size = 7
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = Panel
> libpng warning: iCCP: known incorrect sRGB profile
> callBackName  cannot be found
> size = 0
> child = 0x13d213200
> child = 0x13d212600
> classname = Button
> callBackName clickBackFromImage cannot be found
> size = 0
> child = 0x13c972600
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d86e000
> classname = Button
> callBackName clickZoomInImage cannot be found
> size = 0
> child = 0x13d92fc00
> classname = Button
> callBackName clickClothFromImage cannot be found
> size = 0
> child = 0x13d222a00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13d22aa00
> classname = Button
> callBackName loadFilter cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d928c00
> child = 0x13d244600
> classname = ListView
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d238200
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d92c600
> child = 0x13d237a00
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13c95c000
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c960a00
> child = 0x13c95b800
> child = 0x13d237200
> child = 0x13d246c00
> child = 0x13d243e00
> child = 0x13d232a00
> child = 0x13d211e00
> classname = Panel
> callBackName  cannot be found
> size = 9
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d937200
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13c942c00
> child = 0x13d940e00
> classname = Button
> callBackName clickBackFromComplete cannot be found
> size = 0
> child = 0x13c943200
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c97aa00
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c989c00
> classname = Button
> callBackName add2ShopInComplete cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d95b800
> child = 0x13d94c600
> classname = Button
> callBackName saveForComplete cannot be found
> size = 0
> child = 0x13d95c400
> classname = Button
> callBackName clickZoomInComplete cannot be found
> size = 0
> child = 0x13d96b600
> classname = Button
> callBackName clickPublishInComplete cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d071400
> child = 0x13d07c800
> child = 0x13c961e00
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Button
> callBackName clickCancelInPublishPanel cannot be found
> size = 0
> child = 0x13d974c00
> classname = Button
> callBackName clickPublishInPublishPanel cannot be found
> size = 0
> child = 0x13d975c00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d976a00
> child = 0x13c99b200
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d25ae00
> child = 0x13d93a800
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d25c200
> classname = ImageView
> callBackName  cannot be found
> size = 1
> classname = TextField
> callBackName  cannot be found
> size = 0
> child = 0x13c9a8a00
> child = 0x13c99ba00
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d26b800
> classname = Text
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d269a00
> child = 0x13d263e00
> child = 0x13d25ba00
> child = 0x13d25a600
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d271000
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Button
> callBackName fromAlbum cannot be found
> size = 0
> child = 0x13d274000
> classname = Button
> callBackName fromCamera cannot be found
> size = 0
> child = 0x13d27d200
> classname = Button
> callBackName closeLoadImgPanel cannot be found
> size = 0
> child = 0x13d997a00
> child = 0x13d278e00
> child = 0x13d271800
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Button
> callBackName clearEffect cannot be found
> size = 0
> child = 0x13d297000
> classname = Button
> callBackName  cannot be found
> size = 0
> child = 0x13c9c7c00
> classname = Button
> callBackName closeClearPanel cannot be found
> size = 0
> child = 0x13d2ad200
> child = 0x13d296800
> child = 0x13c99e800
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = ImageView
> libpng warning: iCCP: known incorrect sRGB profile
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13c9ca200
> child = 0x13d2c3e00
> classname = Button
> callBackName closeWaitForSave cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d9b9000
> child = 0x13c9d7a00
> classname = Button
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 0
> child = 0x13d9ba800
> child = 0x13d9b9800
> child = 0x13d2c3600
> classname = Panel
> callBackName  cannot be found
> size = 4
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d2c4400
> child = 0x13d9bb800
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Button
> callBackName clickClothType cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d8e9800
> child = 0x13d2ca600
> classname = Button
> callBackName clickClothType cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d8eb200
> child = 0x13d8ea400
> classname = ImageView
> libpng warning: iCCP: known incorrect sRGB profile
> callBackName  cannot be found
> size = 0
> child = 0x13c9d8800
> child = 0x13d2c5e00
> classname = Panel
> callBackName  cannot be found
> size = 3
> classname = Button
> callBackName clickClothStyle cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d995200
> child = 0x13d2cb400
> classname = Button
> callBackName clickClothStyle cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d996c00
> child = 0x13d995e00
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d9c0000
> child = 0x13c9d8e00
> classname = Panel
> callBackName  cannot be found
> size = 2
> classname = Button
> callBackName clickClothColor cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d9cb200
> child = 0x13d2cc200
> classname = Button
> callBackName clickClothColor cannot be found
> size = 1
> classname = ImageView
> callBackName  cannot be found
> size = 0
> child = 0x13d9d3e00
> child = 0x13d9cbe00
> child = 0x13d9c0c00
> child = 0x13d9bb000
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Panel
> callBackName  cannot be found
> size = 1
> classname = Text
> callBackName  cannot be found
> size = 0
> child = 0x13d9d5a00
> child = 0x13d9d5200
> child = 0x13d9d4a00
> child = 0x13d0db400

### CODE REVIEW

**Comment by xpol** [comment]
@zilongshanren 

Sorry, I'm here again.
Would you help merge this. Just remove logs NO logic changes.

**Comment by zilongshanren** [comment]
@xpol 
Thanks, I think it's OK.

@xiaofeng11   please decide whether to merge or not?

**Comment by xiaofeng11** [comment]
@zilongshanren Yes, it can be merge after jenkins check OK.

**Comment by xpol** [comment]
thans!

xiaofeng11 notifications@github.com于2015年11月27日周五 下午5:21写道：

**Pull request merged**
