### PR TITLE
Fixes warning: field 'isVertsOwner' will be initialized after field 'rect'

### PR DESCRIPTION
**Pull request by xpol**

### CODE REVIEW

**Comment by zilongshanren** [comment]
@xpol  I have fixed this issue in my PR ... This PR is still in progress..

**Comment by xpol** [comment]
@zilongshanren OK, I hope your PR will merged soon. This warnings come out each time I build by project.

**Comment by zilongshanren** [comment]
@xpol  it will be merged in v3.11, keep tune..

**Comment by minggo** [comment]
@zilongshanren Please do one thing in a pull request.

**Pull request merged**
