### PR TITLE
Constructed with3d 

### PR DESCRIPTION
**Pull request by jianglong0156**
add PointLight support constructor
add SpotLight support constructor
add Terrain support constructor
add Camera support constructor

### CODE REVIEW

**Comment by jianglong0156** [comment]
relate issue:https://github.com/cocos2d/cocos2d-x/issues/12404

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by pandamicro** [comment]
Please solve Mac/iOS compilation issue

**Pull request merged**
