### PR TITLE
add CCShapeNode

### PR DESCRIPTION
**Pull request by dualface**
CCShapeNode.h includes:
-   CCCircleShape
-   CCRectShape
-   CCPointShape
-   CCPolygonShape

easy use, more flexibility

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, CCDrawingPrimitives will be deprecated.
So could you use CCDrawNode to implement CCxxxShape?

**Comment by dumganhar** [comment]
My meaning is that make CCxxxShape inherit from CCDrawNode.
That will be better.

**Comment by dualface** [comment]
OK

**Comment by leszek-s** [comment]
i'm looking forward to see this feature in cocos2d-x

**Pull request closed without merging**
