### PR TITLE
fix, replace std::sort by std::stable_sort

### PR DESCRIPTION
**Pull request by halx99**
Developer feedback: http://forum.cocos.com/t/cocos2dx-3-12/37958

### CODE REVIEW

**Comment by halx99** [comment]
Need review

**Comment by halx99** [comment]
@minggo: 
 I post some test result at http://forum.cocos.com/t/cocos2dx-3-12/37958 please take a look.

**Comment by minggo** [comment]
@halx99 looks good me, thanks.

**Comment by minggo** [comment]
since mac slave is offline, so merge it

**Pull request merged**
