### PR TITLE
some fixes to the debugger

### PR DESCRIPTION
**Pull request by rolandoam**
Some things were left out from the merge last time. This PR is meant to fix that.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @Rolando,
I can't apply the patch(https://bug822383.bugzilla.mozilla.org/attachment.cgi?id=694110) to Riq's spidermonkey repo.
I just save the patch file to my desktop. Then enter the directory of spidermonkey.
And run command `git apply ~/jsdebugger.patch`.
But it told me that there is an error as bellow:
`fatal: corrupt patch at line 86`
Any ideas?

**Comment by folecr** [comment]
try

```
git am ~/jsdebugger.patch
```

**Comment by dumganhar** [comment]
@folecr 
I tried that, but still fails.

<pre>
JamestekiMacBook-Pro:Spidermonkey james$ git am ~/Desktop/jsdebugger.patch 
Applying: Bug 822383 - Allow arbitrary proxies on the scope chain. v1
fatal: corrupt patch at line 81
Patch failed at 0001 Bug 822383 - Allow arbitrary proxies on the scope chain. v1
When you have resolved this problem run "git am --resolved".
If you would prefer to skip this patch, instead run "git am --skip".
To restore the original branch and stop patching run "git am --abort".
JamestekiMacBook-Pro:Spidermonkey james$ git am --resolved ~/Desktop/jsdebugger.patch 
previous rebase directory /Users/james/Project/Spidermonkey/.git/rebase-apply still exists but mbox given.
</pre>

**Comment by dumganhar** [comment]
Merged. But i still can't make the patch work.
Thanks.

**Pull request merged**
