### PR TITLE
before draw event

### PR DESCRIPTION
**Pull request by newnon**

### CODE REVIEW

**Comment by zilongshanren** [comment]
The JSB and Lua bindings are not taken into consideration in this PR.

**Comment by newnon** [comment]
i'm not sure about bindings

**Comment by minggo** [comment]
> The JSB and Lua bindings are not taken into consideration in this PR.

@zilongshanren i think lua/jsb just need to listen the corresponding events. Or what should need to do for lua and JSB?

**Comment by zilongshanren** [comment]
@minggo 
I mean if you want to use the before draw event in Lua or Js app, there is no way to do.

**Comment by minggo** [comment]
I think lua/js can just register event listener and check the event type as others.

**Pull request merged**
