### PR TITLE
Marmalade port: changed "airplay" to "marmalade". Implemented CCImage::initWithString.

### PR DESCRIPTION
**Pull request by gzito**
I added "marmalade" folders and new *_marmalade files, e.g. platform/marmalade/CCEGLView_marmalade.cpp.
Also I renamed symbols, such as CC_PLATFORM_AIRPLAY into CC_PLATFORM_MARMALADE.
I left old "airplay" files and folders in place until you finally decide to perform the switch, however other developers should be notified about the change.

CCImage::initWithString for Marmalade is a contribution by Alex Builder and Francis Styck

### CODE REVIEW

**Comment by gzito** [comment]
Other commits:

The stuff below fix errors when the program exits, purging CCDirector and releasing memory correctly.
-    CCDirector (updates done only for CC_PLATFORM_MARMALADE)
    sharedDirector(): s_sharedDirector is now a pointer (it was a static instance)
    purgeDirector():  m_pobOpenGLView, the CCEGLView shared instance, is deleted
  -   CCApplication_marmalade:
    Run() method modified to handle correctly quit requests, CCDirector::purge() is requested before exiting
  -  CCEGLView_marmalade:
    shared instance is now a pointer (it was a static instance)
    the CCEGLView::release notifies the CCApplication about quit

Additions and other fixes:
- CocosDenshion/marmalade/SimpleAudioEngine
      Added possibility to play more than one sound fx at once
- CCImage_marmalade (contribution by Alex Builder and Francis Styck)
    implemented initWithString
    added jpeg support (contribution by Alex Builder)
  - Integrations for marmalade port
    libFreetype and libjpeg
  - test/AppDelegate
    CCDirector shared instance is deleted in AppDelegate destructor
  - test/all
    The X icon now quit the app

Open issues:
    CCLabelTTF in the Marmalade port are _very_ slow
    Device rotation doesn't work properly, see "Director Test"

**Comment by dumganhar** [comment]
Hi, thanks for your pull request. I am merging your code to master. But I have some questions:
1. sharedDirector(): s_sharedDirector is now a pointer (it was a static instance), Why should change to this? 
2. In 'CCDirector::purgeDirector()' function
// OpenGL view
#if (CC_TARGET_PLATFORM != CC_PLATFORM_MARMALADE)  
    m_pobOpenGLView->release();
    m_pobOpenGLView = NULL;
#else
    CC_SAFE_DELETE(m_pobOpenGLView) ;
#endif
Why should use 'CC_SAFE_DELETE(m_pobOpenGLView)'  instead of 'm_pobOpenGLView->release();'? In my opition, m_pobOpenGLView reference is always 1. using 'release' method will delete it.

**Comment by gzito** [comment]
Hi, thanks  for your comment.
1. When I tested the code Marmalade runtime checker reported memory leaks because CCDirectory was destroyed after the main (in the atexit function).
   I just tried to rollback the code and tested it again right now, it seems that this issue disappeared. So may be I need some more time to test it better.
2. Unfortunately CCEGLView is not a CCObject, so calling release() will not delete it. I looked at win32 implementation and in fact release() method perform a "delete this" as last instruction. I tried now to add "delete this" into Marmalade implementation, it seems to work.

Please could you delay the merge and wait until i better look at both the points and perform some more tests?

Thanks again.
G.Z.

**Comment by dumganhar** [comment]
OK, waiting for your good news.
By the way, I had compiled your code successfully. And run it on bada 2.0 WVGA. There are still a lot of issues needed to be resolved. You can modify your code by basing on my repo 'https://github.com/dumganhar/cocos2d-x/tree/issue908_marmalade'. Thanks for your effort!

**Comment by gzito** [comment]
Hi dumganhar,

I fixed things in CCEGLVIew, so that it's now aligned to win32 version (release method perform "delete this").
Added a fix to CCApplication::run in order to support quit from simulator and also rollback changes in CCDirector (the shared instance is static again).
I tested things on the simulator and also on iPhone, it works. You can safely go on with merge into master now.

Please let me aware about some of the opened issues you mentioned in your comment.

Thanks
Giovanni

**Comment by dumganhar** [comment]
Hi, your 'pull request' have been meged into master.
Thanks for your effort!

**Pull request merged**
