### PR TITLE
Remove wrong @Override to fix compilation error on newest Eclipse

### PR DESCRIPTION
**Pull request by ngocdaothanh**
Newest Eclipse reports compilation error with @Override

### CODE REVIEW

**Comment by minggo** [comment]
I think it can not be removed for compatibility.
You can fix the error by doing this:
Project -> Properties -> Java Compiler -> Compiler compatibility level
select 1.6

**Comment by minggo** [comment]
What's your Eclipse version?

**Comment by minggo** [comment]
My Eclipse version is 3.7.2.
You can fix the problem by clean the project.

**Comment by minggo** [comment]
Any progress?

**Comment by ngocdaothanh** [comment]
I'm using Eclipse 3.7.2 on Mac.
It uses Java 1.5 by default.
You're right, setting "Compiler compatibility level" to 1.6 solves the @Override compilation error.

**Pull request closed without merging**
