### PR TITLE
closed #4497: use /z7 to build without .pdb

### PR DESCRIPTION
**Pull request by squirrelChen**
use /z7 to build without .pdb, or will face with error c3130.

### CODE REVIEW

**Comment by minggo** [comment]
Any side-effect to remove .pdb file?

**Comment by squirrelChen** [comment]
I run appliction ok, and as the link :http://msdn.microsoft.com/zh-cn/library/958x11bc.aspx said, it just has some difference of output.

**Comment by dumganhar** [comment]
But `ProgramDatabase` is used in release mode for other targets. Why should `cpp-tests` change it but others not?

**Comment by squirrelChen** [comment]
only cpp-tests face with error c3130, some .cpp in cpp-tests will face with this problem, but without any document about how to solve it...

**Comment by stevetranby** [comment]
Why did this get closed? Shouldn't we strive to allow for Edit and Continue when debugging?

**Pull request merged**
