### PR TITLE
Fix the bug in ui::LoadingBar->setProgress()

### PR DESCRIPTION
**Pull request by doomsdayer**
Think about this code:

```
auto bar = ui::LoadingBar::create("1.png");  //create the bar
bar->setPercent(80); //set to 80%
bar->loadTexture("2.jpg"); //change the bar's background to another image, and it is reverted to 100%
bar->setPercent(80); //BUG: This will not work, because the same percent, it is returnd in setPercent()
```

@andyque 
Please have a look.

### CODE REVIEW

**Comment by doomsdayer** [comment]
[ci rebuild]

**Comment by geron-cn** [comment]
do not do that, fix this bug like this is ok, please:  add 

```
 do 
    {
        if (_percent == 100.0f)
            break;

        if (_scale9Enabled)
        {
            setScale9Scale();
        }
        else
        {
            float res = _percent / 100.0f;
            Rect rect = innerSprite->getTextureRect();
            rect.size.width = _barRendererTextureSize.width * res;
            innerSprite->setTextureRect(rect, innerSprite->isTextureRectRotated(), rect.size);
        }
    } while (0);
```

to UILoadingBar.cpp line: 191
or you can refator this  code block as updateRectByPercent()

**Comment by zilongshanren** [comment]
Thanks @geron-cn

**Comment by doomsdayer** [comment]
It is done.

**Comment by minggo** [comment]
@andyque 
Any problem of this pull request?

**Comment by zilongshanren** [comment]
@doomsdayer 
I will send a PR to resolve this issue. Because your PR has some code duplication, so we can't merge it. 

After that, @doomsdayer  please help me to review it.
Thanks.

@minggo  there are some duplication here. I need to refactor it.

**Comment by zilongshanren** [comment]
hi, @doomsdayer 

Let's discuss this issue on PR: https://github.com/cocos2d/cocos2d-x/pull/10209

Please close this PR, thanks.

**Comment by doomsdayer** [comment]
Ok,  I'll review it.

**Pull request closed without merging**
