### PR TITLE
Fix UIWebViewImpl::loadHTMLString()

### PR DESCRIPTION
**Pull request by jgod**
As described [here](https://github.com/cocos2d/cocos2d-x/issues/9117).

### CODE REVIEW

**Comment by heliclei** [comment]
[ci rebuild]

**Comment by jgod** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Thanks.
Could you please add a test case for it?

**Comment by jgod** [comment]
@minggo, what kind of test would you like? 
If there's any already existing test code for this class it should be transparent since it's just the implementation that changed (functionally the same).
This is my first pr in this repo so still figuring things out.

**Comment by minggo** [comment]
Hi @jgod ,
Just add a test case that can reproduce this issue.
There is already a test case in `tests/cpp-tests/Classes/UITest/CocoStudioGUITest/UIWebViewTest/UIWebViewTest.cpp`, you can add a test case in it.

**Comment by jgod** [comment]
@minggo, Ah I think I understand.

Create a test case as part of the PR that shows how it is broken without this fix? Like a unit test almost

**Comment by minggo** [comment]
Yep.
Thanks.

**Comment by jgod** [comment]
I added a test. It kind of covers [https://github.com/cocos2d/cocos2d-x/pull/9157] too because they both are dealing with the same thing, just different implementation. Let me know what you think

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Fixed in #10909

**Pull request closed without merging**
