### PR TITLE
Implement Full GC Relied memory model

### PR DESCRIPTION
**Pull request by pandamicro**
Related bindings generator PR: https://github.com/cocos2d/bindings-generator/pull/217

@ricardoquesada I just migrated my solution based on your modifications, haven't got time to run through the test, may have compilation issues too, but please take a look already, I will make it working tomorrow.

In the old PR, I have explained my solution, maybe you can get a clearer idea in the comments: https://github.com/cocos2d/cocos2d-x/pull/14224

Essential codes are in the first commit, 
the third one applies the solution to manual bindings, 
the fourth one is very important, it shows how and which native references are passed to script scope

### CODE REVIEW

**Comment by ricardoquesada** [comment]
@pandamicro 
Ok. I'll take a look tomorrow Thursday.

**Comment by ricardoquesada** [comment]
@pandamicro also, what is the best way to test it? Although you haven't run the official tests, have you done some ad-hoc tests that verify that it is working as expected?
thanks.

**Comment by pandamicro** [comment]
I will do the test today and keep update this PR

**Comment by pandamicro** [comment]
Now the compilation issues have been fixed, I still have a few issues on events, will fix them tomorrow

**Comment by ricardoquesada** [comment]
@pandamicro it seems that the build is still broken... should I still try it?

**Comment by pandamicro** [comment]
@ricardoquesada Now the compilation should pass, the jenkins fail because I haven't updated bindings generator.

There is still a few bugs, so no need to try it out, I mean you may want to take a look at the code first

**Comment by ricardoquesada** [comment]
@pandamicro the best way for me to test/review the bindings is by testing it.
JS bindings are so complex, that we need to have this thing working in order to know that it works.

I can review it if you want, but I won't be able to find "bugs" without testing it.
Just let me know what you want me to do, and I can do it.

**Comment by pandamicro** [comment]
@ricardoquesada Ok, I will let you know when bugs are fixed on my side

**Comment by pandamicro** [comment]
@ricardoquesada I fixed all bugs I met, please try this memory model
Don't forget to get my bindings generator in https://github.com/cocos2d/bindings-generator/pull/217
After regenerating the bindings, the compilation should pass

**Comment by ricardoquesada** [comment]
yeah!!! i'll try it today!

**Comment by ricardoquesada** [comment]
@pandamicro hey, it didn't compile for me.
I regenerated the bindings but it complains that it can't find `jsb_ref_finalize`

I tried downloading your PR and also downloading your branch directory and it gives me that error.
My guess is that updated the bindings sub-repo but didn't push it.
Is that correct?

**UPDATE**: Ha ha... I've just seen your comment... ignore my previous comment. thanks!

**Comment by ricardoquesada** [comment]
@pandamicro So, I was able to compile it with your bindings repo and it runs and doesn't crash.
But I think it is leaking lot of objects... For example I put a breakpoint in `Menu::~Menu` and it never gets called.

**Comment by pandamicro** [comment]
Migrated to https://github.com/cocos2d/cocos2d-x/pull/14759

**Pull request closed without merging**
