### PR TITLE
Some updates for neon64 instruction

### PR DESCRIPTION
**Pull request by dumganhar**
- Adding Math performance test
- Recognizing android arm64 device correctly and using NEON64 instruction directly for android arm64 device.
- Workaround for missing `__ctype_get_mb_cur_max` function in ndk-r10c when using `arm64-v8a`
- Adding UnitTest for MathUtil, for comparing the results of MathUtilC and MathUtilNeon/MathUtilNeon64
- Bug fix of `MathUtilNeon64::crossVec3` in PR #9202

### CODE REVIEW

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
Please don't merge this PR until #9193 is merged.

**Comment by dumganhar** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
[ci rebuild]

**Comment by minggo** [comment]
[ci rebuild]

**Pull request merged**
