### PR TITLE
Adding xxtea to ios/mac project and Android.mk file

### PR DESCRIPTION
**Pull request by milos1290**
This commit adds xxtea to be built in ios and mac project, and also in Android.mk file.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@milos1290  
Hi, thanks for the patch. But xxtea is used for Lua script encryption and it has already been added in the lua-bindings/proj.android/Android.mk.

**Comment by milos1290** [comment]
Yeah, but it is not added for C++ for ios/mac and android project. If i want to use it i have to manually add it to xcode and to android.mk file.

**Comment by zilongshanren** [comment]
@milos1290  xxtea is an optional component, not everyone need it, right?

**Comment by minggo** [comment]
Yep, developers should add it themselves if they need it since xxtea is added for lua projects.

**Pull request closed without merging**
