### PR TITLE
Fix win32 cpp-template, speedup appveyor, add cocos new CI configuration

### PR DESCRIPTION
**Pull request by crazyhappygame**

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@minggo could you merge it?

**Comment by crazyhappygame** [comment]
@Dimon4eg Could you check below error:
https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.728/job/ufh2a93bnhrhnq26

It works fine before rebasing your changes
https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.723/job/16m9kp7n36eqypbn

Step to reproduce
cocos new -l cpp -p com.test.test Test1
open Visual Studio solution, compilation failed

c1xx : fatal error C1083: Cannot open source file: '..\precheader.cpp': No such file or directory [C:\projects\cocos2d-x\cocos_new_test\cocos2d\cocos\2d\libcocos2d.vcxproj]

**Comment by crazyhappygame** [comment]
@minggo Do not merge this for now.
After https://github.com/cocos2d/cocos2d-x/pull/18662 "cocos new" created incorrect project for win32. Compilation fails

**Comment by crazyhappygame** [comment]
@Dimon4eg I think that I fixed "cocos new" https://github.com/cocos2d/cocos2d-x/pull/18663/commits/e71610cdbf9154f886d6e4b62f3411fa9171c57a

**Comment by Dimon4eg** [comment]
Nice, thank you!

**Comment by crazyhappygame** [comment]
@minggo could you merge it?

**Comment by minggo** [comment]
thanks

**Pull request merged**
