### PR TITLE
Multitouch support improvements

### PR DESCRIPTION
**Pull request by newnon**
getAllTouches like in cocoa

### CODE REVIEW

**Comment by minggo** [comment]
Any doc for `getAllTouches` of cocoa?
Thanks.

**Comment by newnon** [comment]
https://developer.apple.com/library/ios/documentation/uikit/reference/UIEvent_Class/Reference/Reference.html#//apple_ref/occ/instm/UIEvent/allTouches

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
I think touches information dispatched by EventDispatcher::dispatchEvent() already includes all touches information.

Because when a touch is released, it will be removed in `g_touches`. 
So i don't know what's requirement of `getAllTouches`.

**Comment by newnon** [comment]
No EventDispatcher get information only on changed touches not all active touches. And if you make system of touch recognizing you need to now about all touches on screen. I think it not so expensive function, because it copy only pointers to new vector but it adds useful functionality missing from cocoa.(and also from cocos2d)

**Comment by minggo** [comment]
It is not expensive in `touchBegan` and `touchEnded`, but it is expensive in `touchMove`.
Because these informations are not needed for everyone. 
So i think it is better just add `getAllTouches`, but not invoked in all touch event handler. 
Developers invoke it if needed.

**Comment by newnon** [comment]
It is not expensive even in touchMove because maximum touches count can be 5 and copy 5 pointers is not so expensive operation.

**Comment by heliclei** [comment]
[ci rebuild]

**Comment by newnon** [comment]
[ci rebuild]

**Comment by minggo** [comment]
It will create object, do computation.
And we know it is not needed each time.
Though it is not expensive, i think we should make engine as fast as possible.

**Comment by newnon** [comment]
i have made new PR https://github.com/cocos2d/cocos2d-x/pull/7225
just stand alone getAllTouches()

**Pull request closed without merging**
