### PR TITLE
fixed potential crash in CCScheduler::removeHashElement

### PR DESCRIPTION
**Pull request by Weeds**
If the scheduler is the last object to have retained the pElements target and
the targets desctructor calls CCScheduler::unschedule() invalid memory is
accessed as pElement->timers is already freed, but the pElement is not removed
yet.
Therefore the call to target->release() should be made after pElement has been
removed from the hash table

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @Weeds 
I think your changes is right. Thank you.
But could you send me a Demo to reproduce this issue since i couldn't  reproduce this crash?

**Comment by Weeds** [comment]
I could add a test case to the SchedulerTest.
Still you may need to use valgrind or a similar tool to verify that something is broken.
If the memory area that was occupied by the timer array has not been reused, you may not see a crash.

**Comment by dumganhar** [comment]
OK, I'll also check that by using `valgrind`.
When could you add the new test for `SchedulerTest`?

**Comment by Weeds** [comment]
I've added the testcase, it seems that the issue only occurs when using custom selectors.

I know that this code looks wrong:
testNode->release();
testNode->unscheduleAllSelectors();

But as I said in the commit notes, it might not be that easy to tell who has ownership of the objet in real-world applications.
The code would also work (i.e. cause the crash) if zhe testNode retain()/release() calls where to be removed.

I'm not sure on the naming of the TesCase I used Issue 2268 as it is the issue number of the pull request.
If you track this by redmine issues, you might want to open a report there and I'll update the code.

**Comment by dumganhar** [comment]
OK, remind issue http://www.cocos2d-x.org/issues/2003 was created.
Thank you.

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
