### PR TITLE
visit and draw improved.

### PR DESCRIPTION
**Pull request by ricardoquesada**
`visit()` and `draw()` are improved.
they both receive:
- `Renderer`
- `kmMat4` for transformation
- `bool` whether or not the transform changed from the previous frame

Although `draw` and `visit` are not using the 3 new parameters,
they will start using it in the coming days (or weeks, or months).

Those parameters are needed for:
- `Renderer` shouldn't be a singleton. There should be one renderer per Director. There could be more than one renderer
- we should get rid of `kmGLXXX` functions since nodoby knows what is happening. the `kmMat4` is for that.
- whenever possible, we should try to optimize the multiplications. the `dirty` flag is for that.

We need those changes, so, it is better to change the API now, and not right after v3.0-final is released.

### CODE REVIEW

**Comment by minggo** [comment]
It seems good to me. I will run `testcpp` and give the feedback.

Just one question: why remove `CC_TEXTURE_ATLAS_USE_TRIANGLE_STRIP` support?

**Comment by ricardoquesada** [comment]
I removed `CC_TEXTURE_ATLAS_USE_TRIANGLE_STRIP` because it was not needed.
I added in cocos2d-iphone like 5 years ago when I was testing performance.
`TRIANGLE_STRIP` was never useful and I left it in the code just in case. But the reality is it is not useful, make the code less maintainable, and the rest of the code doesn't support it (Progress, QuadCommand, Effects don't support TRIANGLE_STRIP)

**Comment by minggo** [comment]
Got it. Thanks.

**Comment by minggo** [comment]
I have run `TestCpp` on iOS simulator, it seems good.

**Comment by dabingnn** [comment]
This pr is a big improvement. I tested `testcpp`, there is a bug on RenderTextureTest->Testing Z Buffer in RenderTexture, it seems the viewport are resized use a wrong size. However, we can fix the bug when it is merged.

**Comment by ricardoquesada** [comment]
I'm glad that you like it. I'll take a look at the bug. But if I can't fix it today, as you said, we can merge the PR and fix the bug later.

**Pull request merged**
