### PR TITLE
fix compile error in visual studio 2015

### PR DESCRIPTION
**Pull request by GuoLunHao**
There's no include file "afxres.h" in visual studio 2015 Enterprise version, so that change it to "winresrc.h"

### CODE REVIEW

**Comment by GuoLunHao** [comment]
@xiaofeng11 @pandamicro

**Comment by xiaofeng11** [comment]
Seems afxres.h only contain in vs2013 and lower version, winres.h and winresrc.h contain in all version, but winres.h is MFC based include file, cocos2dx is not dependecy MFC lib, so we use winresrc.h to make it compatible with all version of visual studio.

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Comment by xiaofeng11** [comment]
[ci rebuild]

**Pull request merged**
