### PR TITLE
Fix when button reader bug

### PR DESCRIPTION
**Pull request by xiaofeng11**
Fix when button set to disabled mode and won't have a disable texture will cause simulator won't show button in disabled gray mode

### CODE REVIEW

**Comment by pandamicro** [comment]
@VisualSJ It may need to be merged to JS
@andyque Please review this PR

**Comment by VisualSJ** [comment]
@pandamicro This bug has been fixed in JS
H5:
https://github.com/cocos2d/cocos2d-html5/blob/develop/extensions/cocostudio/loader/parsers/timelineParser-2.x.js#L622
JSB:
https://github.com/cocos2d/cocos2d-x/blob/v3/cocos/scripting/js-bindings/script/studio/parsers/timelineParser-2.x.js#L622

**Comment by pandamicro** [comment]
[ci rebuild]

**Comment by zilongshanren** [comment]
@pandamicro  This PR is OK.

**Comment by pandamicro** [comment]
[ci rebuild]

**Pull request merged**
