### PR TITLE
issue #12078 added audio, network, physics, platform and storage group.

### PR DESCRIPTION
**Pull request by linshun**
issue #12078 added audio, network, physics, platform and storage group.

### CODE REVIEW

**Comment by minggo** [comment]
Following is my feedback:
- `audio`, `network`, `renderer` and `storage` looks good to me
- About `platform`: though these files are under `platform` folder, but i think it is not good to name the module to `platform`. The implementation of these class are platform dependent, but it will be confused if the module is named `platform`.
- Now there are 2d physics and 3d physics, so i think it is better to distinguish them. How about `physics2d` and `physics3d`?

**Comment by linshun** [comment]
- As to `platform`, how about name it as `support`?
- As to `physics`, it could be:

`physics`
         - `physics 2d`
         - `physics 3d`
What do you think?

**Comment by minggo** [comment]
Though i think `support` is not a good name, but i can't find a better one.
`physics 2d` and `physics 3d` looks good.

**Comment by pandamicro** [comment]
Maybe we don't need a `platform` module, they can remain in `core`, what do you think?

**Pull request merged**
