### PR TITLE
Update CCImageCommon_cpp.h

### PR DESCRIPTION
**Pull request by bopohaa**
webp don't work for me

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi, @bopohaa 
Thanks for this patch, could you tell me which platform are you using to reproduce the issue?

**Comment by bopohaa** [comment]
I used win32 platform and compile on Visual Studio 2013.

**Comment by dumganhar** [comment]
So,  did the `webp test` of `Texture2DTest` crash?

**Comment by dumganhar** [comment]
Thanks.

**Pull request merged**
