### PR TITLE
Fix crash TextFieldTTF::setCursorFromPoint

### PR DESCRIPTION
**Pull request by perminovVS**
A similar problem of
https://github.com/cocos2d/cocos2d-x/issues/15926
And fix it in https://github.com/cocos2d/cocos2d-x/commit/afaa9be8262e64fbc090cf2c202871efe779b94e

### CODE REVIEW

**Comment by minggo** [comment]
how to reproduce it?

**Comment by perminovVS** [comment]
@minggo Now it api need used in user code.
Add call it, in touch event to TextFieldTTF or UITextField.

**Comment by minggo** [comment]
Could you please add a test case?

**Comment by perminovVS** [comment]
@minggo Well, if possible, I will add.

**Comment by minggo** [comment]
any update?

**Comment by perminovVS** [comment]
There is no time. I'll try to do it on the weekend.

**Comment by perminovVS** [comment]
@minggo test it in https://github.com/cocos2d/cocos2d-x/pull/18336

**Pull request merged**
