### PR TITLE
Extended Tiled Map: Render background.

### PR DESCRIPTION
**Pull request by syrokomskyi**
Manually rebased ) from #2515.

### CODE REVIEW

**Comment by boyu0** [comment]
please commit your resource files used in new tests, thanks.

**Comment by syrokomskyi** [comment]
Oh, sorry. Files are added.

**Comment by syrokomskyi** [comment]
Well, how fix this "x Failed"?

**Comment by dumganhar** [comment]
The error message is 

```
/jenkins/workspace/cocos-2dx-pull-request-build/node/android_mac/build/../cocos/2d/CCTMXTiledMap.cpp:106: error: undefined reference to 'cocos2d::TMXImageLayer::create(cocos2d::TMXImageLayerInfo*, cocos2d::TMXMapInfo*)'
/jenkins/workspace/cocos-2dx-pull-request-build/node/android_mac/build/../cocos/2d/CCTMXTiledMap.cpp:241: error: undefined reference to 'typeinfo for cocos2d::TMXImageLayer'
```

**Comment by cocosQA** [comment]
Dear signmotion:
  We have created a new branch 'v3' to replace branch 'develop', and this PR has been moved from 'develop' branch to 'v3' branch, the new PR is https://github.com/cocos2d/cocos2d-x/pull/6420
The old 'develop' branch will be deleted soon, and this PR will be closed accordingly.

**Pull request closed without merging**
