### PR TITLE
Update HelloCpp.csproj

### PR DESCRIPTION
**Pull request by PhamDinhTri**
fix adding assets

### CODE REVIEW

**Comment by minggo** [comment]
What's the difference compared to #9613.

**Comment by PhamDinhTri** [comment]
sorry no difference

**Comment by minggo** [comment]
Ok.
Could you please close one.

And what's the issue?
There is compiling error of new WP8 project?

**Comment by minggo** [comment]
@phamdinhtribk 
Why open it again?

**Pull request closed without merging**
