### PR TITLE
add helper funcion to invoke a function in gl thread

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
I will modify `AssetsManager` and other modules to use `ThreadHelper`.

**Comment by ricardoquesada** [comment]
We are synchronized :)

I've just implemented something similar for the console that I'm working on:
https://github.com/ricardoquesada/cocos2d-x/blob/console/cocos/2d/CCScheduler.cpp#L829

Instead of creating another class, I just added the `performFunctionInCocosThread` method in `Scheduler`.

IMO, `Scheduler` is better than `ThreadHelper` for this particular case.

What do you think about it ?
thanks.

**Comment by minggo** [comment]
Ok, would you send a pull request for it?
I will change the codes.

**Comment by ricardoquesada** [comment]
Yes, I'll send a PR once I finish the console code.
It will be next week.
thanks!

**Comment by minggo** [comment]
Thanks. It sounds reasonable to implement it in `Schedule`.

**Pull request merged**
