### PR TITLE
2.1.5 bug fixes

### PR DESCRIPTION
**Pull request by dumganhar**

### CODE REVIEW

**Comment by dumganhar** [comment]
@sbc100

Could you check that why native-client build failed on the travis-ci ? Thanks.

**Comment by sbc100** [comment]
Sure thing, will do.

**Comment by dumganhar** [comment]
> Sure thing, will do.

Thanks. Any results?

**Comment by sbc100** [comment]
Looks like a missing include of <sys/mount.h>.

Do you want me to add a PR for this?  (I will do it now and you can use it if you like).

**Comment by sbc100** [comment]
https://github.com/cocos2d/cocos2d-x/pull/3456

**Comment by dumganhar** [comment]
Thanks. I will add it to my PR. :)

**Comment by minggo** [comment]
@sbc100 
Include <sys/mount.h> causes error in latest codes.
Could you help to checkout it?

Thanks.

**Comment by sbc100** [comment]
Sure.  Can you point me to the failure?  Is it failing on travis?

**Pull request merged**
