### PR TITLE
proper handling of keyboard repeat events after update to glfw3

### PR DESCRIPTION
**Pull request by marrone**
Keyboard onKeyReleased events are being repeatedly fired even before the you physically release the keyboard. 
This appears to have happened with the move from glfw2 to glfw3 which now enabled REPEAT by default, see:
http://www.glfw.org/docs/3.0/moving.html#moving_repeat

To preserve the original behaviour where the onKeyReleased event is fired only when the keyboard key is actually physically released, we need to ignore the GLFW_REPEAT action, see:
http://www.glfw.org/docs/3.0/group__input.html#ga592dd1919f8a1dc7576b13cdd8b7b695

### CODE REVIEW

**Comment by minggo** [comment]
Thanks @marrone.
It is a nice patch. Could you please modify MAC and windows too?

**Comment by marrone** [comment]
I could make the change, but I don't currently have either a Mac or Windows platform to verify against

**Comment by marrone** [comment]
Ok, I've updated mac and win32 platforms... though like I said I am not currently able to actually verify on those platforms myself

**Comment by dumganhar** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/5018 . Thanks.

**Pull request closed without merging**
