### PR TITLE
Fix for unaligned memory access crash in CCBReader::readFloat()

### PR DESCRIPTION
**Pull request by BodbDearg**
A fix for a potential unaligned memory access crash in CCBReader::readFloat(), caused by incorrect compiler optimisations/assumptions surrounding the use of memcpy().

See source comments for more details on the change.

### CODE REVIEW

**Comment by BodbDearg** [comment]
Checked for the same issue in the Cocos2d/Objective-C version of CCBReader - looks as though the issue was worked around there with a byte by byte copy:

https://github.com/cocos2d/CCBReader/commit/a205146d4664e15f5fcf9d47146b26f016d6a055#commitcomment-2574544

This would be an alternate way of fixing the problem.

**Comment by dumganhar** [comment]
Thank you. Merged.

**Comment by BodbDearg** [comment]
Thanks very much!

**Comment by sunxiaoyu** [comment]
this issue occurred to me on my release version,but codes works well on real-device debug,I have notice that cocos2d for iPhone share the same codes as your pre version,but it still works well,there is no different compiler settings between two testing projects.So I wonder if this bug only happened in some very particular conditions:)

**Comment by minggo** [comment]
Could you please use latest codes? This file is changed a little.
Thank you.

**Comment by sunxiaoyu** [comment]
okay! I have already did

**Comment by minggo** [comment]
Can you reproduce it?

**Comment by sunxiaoyu** [comment]
This fix has already solved my issue,I just got confused why didin't I meet the same issue on my project which is based on cocos2d for iphone

**Pull request merged**
