### PR TITLE
Hot fix for seting shader in CCSprite::setTexture

### PR DESCRIPTION
**Pull request by gelldur**
Those changes fix TestCPP with CCControlSwitch example

More comments at https://github.com/cocos2d/cocos2d-x/commit/a87cba80dbeaa991de2098ef359e533f28883d12#cocos2dx/sprite_nodes/CCSprite.cpp

### CODE REVIEW

**Comment by dumganhar** [comment]
It was fixed. Your codes was based on which a month ago.
Could you pull our latest codes and test it again?
This Pull Request is not needed.

**Comment by gelldur** [comment]
hmm funny i just pull latest master
Last commit to master is about 1 month ago.
I see This branch is 0 commits ahead and 1206 commits behind develop and last commit https://github.com/cocos2d/cocos2d-x/commit/9b99bec944addce232d72b2add2d97bb07994fee

**Comment by gelldur** [comment]
bug still exist on master

**Comment by gelldur** [comment]
This PR makes bug with CCSprite::init() so i close it. You should merge fix to master from develop?

**Comment by minggo** [comment]
master branch is to hold stable releasing, not for developing.

**Comment by gelldur** [comment]
ok i understand but no fix on master for this bug?

Ok i fixed it like on develop i think now it is working i test CCControlSwitch and Sprite::init and works. So please check and pull if all ok.

**Comment by gelldur** [comment]
Sorry for closing/opening i forgot to do clean :). Tested again works fine.

**Pull request closed without merging**
