### PR TITLE
using auto instead of auto& when the correct places

### PR DESCRIPTION
**Pull request by ricardoquesada**

### CODE REVIEW

**Comment by zilongshanren** [comment]
why use auto instead of auto&?  The auto keyword would result extra copy in the loop.   auto& is fast?  correct me if I am wrong here.

**Comment by ricardoquesada** [comment]
@andyque 
http://discuss.cocos2d-x.org/t/on-auto-vs-auto/22134/11

**Comment by ricardoquesada** [comment]
@andyque @minggo 
if there are no objections, I'll merge this PR.

**Comment by ricardoquesada** [comment]
Don't merge this PR

**Comment by ricardoquesada** [comment]
invalid.

**Pull request closed without merging**
