### PR TITLE
cpp-tests add apk signing

### PR DESCRIPTION
**Pull request by crazyhappygame**
Signed CppTests-release.apk can be dowloaded from appveyor and installed on Android device

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@drelaptop could you merge it?
After this change you can just install signed apk on your device:
go to: https://ci.appveyor.com/project/minggo/cocos2d-x/build/1.0.1159/job/xwl2l80hpdoi6a9g/artifacts
download  CppTests-release.apk
adb install  CppTests-release.apk

**Comment by drelaptop** [comment]
Not a so necessary feature for the build tests, the sign-process should be done by developers. further more, this will case to un-uniform, we didn't test sign for mac build test, and iOS build test.

**Comment by crazyhappygame** [comment]
I see your point. 
But why not enable this only for Android if it is so easy?
This will allow us easily test android builds. You just go to appveyor, download apk, install and test it on device.
You can download apk for each build and pull request. 
You can check if e.g. some regression was not introduced few months ago
appveyor store artifacts (build outputs apk) for 6 months.

**Comment by drelaptop** [comment]
> This will allow us easily test android builds. You just go to appveyor, download apk, install and test it on device.

APK build on debug mode also can achieve this goal, more logs on debug mode. Days before you changes `gradlew build` to `gradlew assembleRelease` to build release mode only. 

Is it better to build debug mode only? not care sign, more logs @crazyhappygame

**Comment by crazyhappygame** [comment]
OK.
https://github.com/cocos2d/cocos2d-x/pull/18969

**Pull request closed without merging**
